### ISSUE TITLE
UI:  Plugins Page

### ISSUE THREAD

**Issue by retroneo** [oznu/homebridge-config-ui-x#10]
Suggestion for UI:

1.  "Installed" is in red, should be green.
2.  "Update Available" should stay in red.
3.  Plugins with "Update Available" should be at top of list
4. "UPGRADE" button should say "UPDATE" to match above.

Thanks for awesome plugin

**Comment by oznu** [comment]
@retroneo, thanks for your suggestions and using this plugin.

I have made both of these changes in version 2.0.6:

* Plugins with "Update Available" should be at top of list
* "UPGRADE" button should say "UPDATE" to match above.

As for the colour changes, I'll keep them in mind as a tweak the color scheme more later on.
