### ISSUE TITLE
You are using a depreciated log config format...

### ISSUE THREAD

**Issue by sorriso93** [oznu/homebridge-config-ui-x#100]
Hello
in the log with the last version I get this message

[5/28/2018, 12:25:55 AM] [Config] You are using a depreciated log config format, please update your config.json to use this new format:
[5/28/2018, 12:25:55 AM] [Config] {"method":"systemd","service":"homebridge"}

I use systemd and this configuration:

        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "restart": "sudo -n systemctl restart homebridge",
            "log": "systemd",
            "sudo": true
        }

In the readme I don't find any info about the message, and till the previous version it was all ok.
Should I change something in the config.json?
thks

PS: I tried the suggested configuration but homebridge hangs, v0.4.38

**Comment by oznu** [comment]
You should replace "systemd" with the config shown in the logs.

https://github.com/oznu/homebridge-config-ui-x#logs-from-systemd
