### ISSUE TITLE
UI REST API: Accessories not available after restart until accessed first in browser

### ISSUE THREAD

**Issue by Lorccan** [oznu/homebridge-config-ui-x#1005]
**Describe The Bug:**
After restarting the homebridge server, empty JSON is returned by the `http://homebridge.local/api/accessories` endpoint unless accessories are first accessed in the homebridge UI (with a browser). 

**To Reproduce:**
• Restart homebridge server
• Try using UI REST API to return all accessories (e.g. in Swagger, after authorisation success)
• Empty JSON [] is returned
• Browse to the Accessories tab in homebridge UI
• Use UI REST API to return all accessories
• JSON now contains all accessories

**Expected behavior:**
UI REST API to return accessories without need to access UI first

**Logs:**
I don't have any relevant logs
```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
{
"bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51423,
        "pin": "111-11-1111"
    },
"platforms":[
{
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "orange",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
]
}
```

**Screenshots:**
Can be provided if this is not clear without them

**Environment:**

* **Node.js Version**: v14.15.1
* **NPM Version**: v6.14.9
* **Homebridge Version**: v1.1.7
* **Homebridge Config UI X Version**: v4.36.0
* **Operating System**: Raspbian 
* **Process Supervisor**: Systemd

**Comment by jimbju** [comment]
I have the same issue, any updates or workarounds exist for this issue? Thanks!

**Comment by SiarAneas** [comment]
@Lorccan , @idsnowghost , @jimbju did someone of you ever get this issue solved or found a workaround?

I'd suggest to re-open that issue since I'm still facing the same problem (on Homebridge 1.5.1)

I'm using the API for controlling some devices in my home through a 3rd party solution -  it's super annoying having to manually login to the web UI every now and then when there's a power cut or for whatever reason Homebridge decides to restart.

**Comment by anonymouz4** [comment]
Bump

**Comment by jochen-schmidt-microstep** [comment]
This is still an issue, even with version 1.9.0.
Is there any solution or workaround?
