### ISSUE TITLE
Feature Request: Longer/customizable cookie expiration

### ISSUE THREAD

**Issue by BewhiskeredBard** [oznu/homebridge-config-ui-x#1007]
**Is your feature request related to a problem? Please describe:**

I haven't checked, but the auth cookie seems to expire very quickly (an hour?). I'd rather stay authenticated for a much longer period of time (30 days?).

**Describe the solution you'd like:**

Either extend the expiration, or add a config option to do so.

**Describe alternatives you've considered:**

N/A

**Additional context:**

N/A

**Comment by oznu** [comment]
This is already a thing. Adjust the Session timeout under the UI Settings -> Advanced.

The default expiry is 8 hours.

**Comment by BewhiskeredBard** [comment]
I totally missed that. Thanks!
