### ISSUE TITLE
Listen only on localhost?

### ISSUE THREAD

**Issue by f1s3c** [oznu/homebridge-config-ui-x#1009]
**Question:**

Is it possible to have the UI listen only on localhost?

**Environment:**

* **Node.js Version**: v14.15.1
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.16
* **Homebridge Config UI X Version**: 4.36.0
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Set the host option to 127.0.0.1

https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#host
