### ISSUE TITLE
Accessory Names from homebridge-homeassistant Plugin

### ISSUE THREAD

**Issue by bittles** [oznu/homebridge-config-ui-x#101]
For some reason, all of the accessories that this plugin brings over into homebridge are just named as a generic item (eg. "Switch", "Lightbulb", "Temperature Sensor").  So I have about 15 generic switches. No issue with other homebridge plugins.  Any idea what the issue there is?

**Comment by oznu** [comment]
Accessory names are labeled based on the default name the plugin provides.

You probably renamed these in the iOS Home app when you first setup the accessories, unfortunately these custom names are stored in iCloud and not sent back to Homebridge.
