### ISSUE TITLE
No SSL option in Settings Homebridge UI

### ISSUE THREAD

**Issue by JLafranca** [oznu/homebridge-config-ui-x#1010]
Dear reader,

I absolutely love your plugin for the UI, as being not a hardcore IT-guy. However, I noticed the connection runs via http rather than on https://..

I extensively looked into the options, I see printscreens on the hub of an option to configure your SSL in the UI interface, but with me, it is not showing.

Probably I'm doing something very wrong..

Thanks in advance!,
Jeff

I'm using Homebridge via Docker on a Synology NAS

Node.js Version: v14.15.1
npm version: v6.14.8
Homebridge version 1.2.4.
homebridge-config-ui-x v4.36.0
Operating System: Docker

**Comment by oznu** [comment]
You can add it to the config using the config editor.

https://github.com/oznu/homebridge-config-ui-x#enabling-ssl
