### ISSUE TITLE
Log to MQTT

### ISSUE THREAD

**Issue by ntableman** [oznu/homebridge-config-ui-x#1012]
**Is your feature request related to a problem? Please describe:**
Sort of: I have all these things being controlled by homebridge and I'd like to dump the outputs of plugins to MQTT to I can do something with it.

**Describe the solution you'd like:**
send each log line to a topic

**Describe alternatives you've considered:**
I have changed nearly all the plugins to call an MQTT code snippet I wrote, but I have to redo this every time they are updated.

**Comment by oznu** [comment]
You may be able to achive this with a 3rd party solution; it's not something the UI will implement.
