### ISSUE TITLE
Problems installing hb-service (it’s using mkdirs from homebridge-config-ui-x)

### ISSUE THREAD

**Issue by SubZane** [oznu/homebridge-config-ui-x#1019]
**Describe Your Problem:**
My problem is two problems really (I think). When trying to install hb-service, it crashes using mkdirs located in the fs-extra folder in homebridge-config-ui-x. (See log 1). 

When installing homebridge-config-ui-x I get several warnings related to node version (Log 2). However. I do NOT have node 8 installed. when typing ”node -v” I get 12. I also tried installing version 10 using nvm, but still the installtion script says I have version 8. I’m confused....

**Logs:**
***Log 1***
pi@homebridge:/ $ sudo hb-service install --user pi
/usr/lib/node_modules/homebridge-config-ui-x/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/fs-extra/lib/mkdirs/index.js:3:44)

***Log 2***
pi@homebridge:/ $ sudo npm install -g homebridge-config-ui-x
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/usr/bin/homebridge-config-ui-x -> /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js/usr/bin/hb-service -> /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
npm WARN notsup Unsupported engine for homebridge-config-ui-x@4.36.0: wanted: {"node":">=10.17.0","homebridge":">=0.4.22"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-config-ui-x@4.36.0
npm WARN notsup Unsupported engine for fs-extra@9.0.1: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@9.0.1
npm WARN notsup Unsupported engine for ora@5.2.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: ora@5.2.0
npm WARN notsup Unsupported engine for semver@7.3.4: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.3.4
npm WARN notsup Unsupported engine for tar@6.0.5: wanted: {"node":">= 10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: tar@6.0.5
npm WARN notsup Unsupported engine for universalify@1.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: universalify@1.0.0
npm WARN notsup Unsupported engine for universalify@2.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: universalify@2.0.0
npm WARN notsup Unsupported engine for chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.0
npm WARN notsup Unsupported engine for log-symbols@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: log-symbols@4.0.0
npm WARN notsup Unsupported engine for chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.0
npm WARN notsup Unsupported engine for chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.0
npm WARN notsup Unsupported engine for lru-cache@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: lru-cache@6.0.0
npm WARN notsup Unsupported engine for chownr@2.0.0: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: chownr@2.0.0
npm WARN notsup Unsupported engine for mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.11.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: mkdirp@1.0.4

**Environment:**

* **Node.js Version**: 10.23.0 and 12.20.0
* **NPM Version**: 6.14.10
* **Homebridge Version**: 1.1.7
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian

**Comment by oznu** [comment]
Your nvm setup is causing issues. Remove it and install node as per wiki guides.

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

**Comment by SubZane** [comment]
Thanks! worked like a charm :)
