### ISSUE TITLE
Upgrade to latest homebridge-ui-x failed and now I couldn't start homebridge at all

### ISSUE THREAD

**Issue by ssllii** [oznu/homebridge-config-ui-x#1024]
**Describe Your Problem:**
I have updated the plug-in for 6 months or so and decided to do it today.
When it got to updating homebridge-ui-x, there was an error.

**Logs:**  from /var/lib/homebridge.log
[1/3/2021, 4:33:08 PM] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge@latest
[1/3/2021, 4:33:11 PM] [Homebridge UI] Command failed. Please review log for details.

Where is the other log that has the details.

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.15.1

* **NPM Version**:  even this failed with 
* internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module '/usr/lib/node_modules/npm/node_modules/core-util-is/lib/util.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/are-we-there-yet/node_modules/readable-stream/lib/_stream_readable.js:67:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/lib/node_modules/npm/node_modules/core-util-is/package.json',
  requestPath: 'core-util-is'
}

* **Homebridge Version**: 
* **Homebridge Config UI X Version**: 4.34.0
* **Operating System**: Raspbian
* **Process Supervisor**:  Systemd

**Comment by mmmrvn** [comment]
Same issue here, update failed. Running "systemctl status homebridge" shows Homebridge is running but accessories show no response and cannot access web UI.

**Comment by oznu** [comment]
```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by oznu** [comment]
@ssllii - in your case the local copy of `npm` is corrupted.

See https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux for instructions on how to fix Node/npm issues.

**Comment by mmmrvn** [comment]
> ```
> # cleanup
> sudo npm uninstall -g homebridge-config-ui-x
> 
> # reinstall
> sudo npm install -g --unsafe-perm homebridge-config-ui-x
> ```

Cleaned up and installed again but UI refuses to connect on browser.

**Comment by oznu** [comment]
Did you restart the service after running the commands?

**Comment by mmmrvn** [comment]
> Did you restart the service after running the commands?

"sudo homebridge service restart"?

**Comment by oznu** [comment]
Probably

**Comment by mmmrvn** [comment]
> Probably

Restarted and now it says "config.json (/root/.homebridge/config.json) not found." Made no changes to config.json location beforehand, which was working seamlessly prior to failed update.

Appreciate the assistance, hope we can get this running again without having to do a fresh install (the thought of renaming all accessories all over again and reconfiguring automations stresses me out lol)

**Comment by oznu** [comment]
Is that where your config.json should be?

Where is it saying this??

**Comment by oznu** [comment]
I can't really help much without knowing about your setup.

Please raise a new support request and fill in all the details:

https://github.com/oznu/homebridge-config-ui-x/issues/new?assignees=&labels=question&template=support-request.md&title=

**Comment by mmmrvn** [comment]
No, prior to update it was and still is at /home/hoobs/config/config.json

It says this after running restart and/or DEBUG on Terminal (Mac)

I've placed a copy of my config.json on /root/.homebridge/config.json but still refusing to connect to the UI

**Comment by oznu** [comment]
ok you're running a very old setup.

run `systemctl restart homebridge-config-ui-x`

**Comment by mmmrvn** [comment]
> ok you're running a very old setup.
> 
> run `sudo systemctl restart homebridge-config-ui-x`

That fixed it! Thank you so much @oznu 😄

**Comment by oznu** [comment]
That should get your UI back online, but then you probably want to move to a modern setup:

Remove the homebridge-config-ui-x service:

```
sudo systemctl stop homebridge-config-ui-x

sudo systemctl disable homebridge-config-ui-x

sudo rm -rf /etc/systemd/system/homebridge-config-ui-x.service
```

Remove the homebridge service:

```
sudo systemctl stop homebridge

sudo systemctl disable homebridge

sudo rm -rf /etc/systemd/system/homebridge.service
```

Use `hb-service` to create the new service file:

```
sudo hb-service install --user hoobs
```

This should get you back up and running with a "modern" setup without loosing any config.
