### ISSUE TITLE
Request: Editing Accessories and Persistent data

### ISSUE THREAD

**Issue by Jan18101997** [oznu/homebridge-config-ui-x#1025]
**Is your feature request related to a problem? Please describe:**

I was trying to remove a device from a Plugin. It was using the accessories/cachedAccessories to store them after they where discovered. It sucked removing them manually.

**Describe the solution you'd like:**

A simple way to edit cachedAccessories and persistent data would be great.

**Describe alternatives you've considered:**

Editing it manually but it was annoying

**Additional context:**

**Comment by oznu** [comment]
This feature already exists. To use it you must be running your setup using `hb-service`.

Upper right drop down menu -> Homebridge Settings -> Remove single cached accessory.

If you don't see the option, you aren't using `hb-service`.
