### ISSUE TITLE
Downgrande homebridge from UI X

### ISSUE THREAD

**Issue by masterfordev** [oznu/homebridge-config-ui-x#1027]
**Describe Your Problem:**
Just to confirm. If I click on the homebridge version and select an older version, it will be downgraded safely, right?

**Screenshots:**

![Captura de Pantalla 2021-01-08 a la(s) 11 17 41 p m](https://user-images.githubusercontent.com/29960705/104084863-55f0ea00-5208-11eb-8829-925c112c6111.png)

**Environment:**

* **Node.js Version**: 12.8.3
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.5
* **Homebridge Config UI X Version**: 4.36.0
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Yes.

**Comment by masterfordev** [comment]
thank you for your quick response. 😅
