### ISSUE TITLE
Install homebridge-weather-plus silently fail 

### ISSUE THREAD

**Issue by maisun** [oznu/homebridge-config-ui-x#1028]
**Describe Your Problem:**

I'm trying to install homebridge-weather-plus plugin, the installation completes after a long time, but the plugin isn't installed afterwards.

**Logs:**

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-weather-plus@latest

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated text-encoding@0.6.4: no longer maintained
[            ......] \ extract:googleapis: sill extract googleapis@>39.1.0 extr

**Environment:**

* **Node.js Version**: v14.15.1
* **NPM Version**: v6.14.8
* **Homebridge Version**: 1.2.5
* **Homebridge Config UI X Version**: 4.36.0
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by maisun** [comment]
The author of the plugin writes: Install this plugin using: npm install -g homebridge-weather-plus Note: The installation might take 5 minutes.
Is there timeout when installing plugin from the GUI?

**Comment by oznu** [comment]
> Is there timeout when installing plugin from the GUI?

There is no timeout. Try again, or try installing manually as per Docker plugin install instructions.
