### ISSUE TITLE
Feature Request : Disable Plugins

### ISSUE THREAD

**Issue by qtzar** [oznu/homebridge-config-ui-x#1029]
**Is your feature request related to a problem? Please describe:**
Currently if a Plugin starts failing due to 3rd party API changes ( for example MyQ recently changed their API and the MyQ plugin is currently not working) there can be lots of errors in the logs as the plugin tries to reinitialize itself. The only way to stop the errors is to edit the config.json to remove the relevant section for the plugin which can be quite messy.

**Describe the solution you'd like:**
It would be nice if there was a 'disable plugin' feature that would remove the relevant section from the config.json and save it off to a file ( like plugin-name.config.json.disabled ) and then prompt to restart the server. Then maybe there could be an 'enable plugin' option that would read the file and reintegrate it back to the main config.json.

This would save a lot of time over doing it manually.

**Comment by oznu** [comment]
Same as https://github.com/oznu/homebridge-config-ui-x/issues/287

**Comment by oznu** [comment]
The solution to this feature request will land in the next release. 

It will require Homebridge 1.3.0-beta.47 or later to support the new `disabledPlugins` array (https://github.com/homebridge/homebridge/pull/2775).

As part of these changes users will be able to toggle enable/disable a plugin, their config will be able to remain in the config.json and not stop Homebridge from loading.

![image](https://user-images.githubusercontent.com/3979615/105021438-a552d800-5a9c-11eb-8f9c-f69b23dc1801.png)
![image](https://user-images.githubusercontent.com/3979615/105021494-b4398a80-5a9c-11eb-9fca-1fcf38e2fafd.png)
