### ISSUE TITLE
Add install/update timestamp to plugins panel

### ISSUE THREAD

**Issue by nyjklein** [oznu/homebridge-config-ui-x#1031]
****Is your feature request related to a problem? Please describe:**
Add install/update timestamp to plugins panel**

****Describe the solution you'd like:**
Please add the latest install/update timestamp to the version information for each plugin on the plugins panel**

****Describe alternatives you've considered:**
None**

**Additional context:**

**Comment by Tinymaite** [comment]
Untouchable quality
