### ISSUE TITLE
Package my edited plugin to use it in my Raspberry

### ISSUE THREAD

**Issue by aefn** [oznu/homebridge-config-ui-x#1040]
Dear All,
I have started to modify the config-ui-x plugin a few days ago in my mac. I followed [this manual](https://github.com/oznu/homebridge-config-ui-x/blob/master/CONTRIBUTING.md)
I am using the homebridge on a raspberry and I used [this image](https://github.com/homebridge/homebridge-raspbian-image)

Now, I would like to use my edited version in my raspberry but I don't have any clue how should I do that.
I appreciate if you could guide me.

Just for information: 
I tried to use `npm pack` in my dev branch to create a new package but I don't know how should I install that in my raspberry.
I tried to just copy my public and dist folders from my mac into raspberry, but again it does not work.

**Comment by oznu** [comment]
Run:

```
sudo npm install -g --unsafe-perm the-file-generated-from-npm-pack.tgz
```

**Comment by aefn** [comment]
I think I am close, but I got an error.
`Error: ENOENT: no such file or directory, open '/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/public/index.html'`

the structure of my new installed plugin is like this :

`
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/CHANGELOG.md
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/CONTRIBUTING.md
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/LICENSE
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/README.md
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/config.schema.json
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/extract-plugin-alias.js
/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/package.json

/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/dist:
app.controller.d.ts
app.controller.js
app.controller.js.map
app.gateway.d.ts
app.gateway.js
app.gateway.js.map
app.module.d.ts
app.module.js
app.module.js.map
app.service.d.ts
app.service.js
app.service.js.map
bin
core
index.d.ts
index.js
index.js.map
main.d.ts
main.js
main.js.map
modules
self-check.d.ts
self-check.js
self-check.js.map

/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules:
big list of installed modules

/srv/plugins/homebridge/lib/node_modules/homebridge-config-ui-x/package:
dist
public
`

**Comment by oznu** [comment]
Make sure you ran `npm run build` before packing it - so the UI is compiled.

**Comment by aefn** [comment]
> Make sure you run `npm run build` before packing it - so the UI is compiled.

Thanks, it worked.
