### ISSUE TITLE
Firewall on Big Sur blocking access to Configure?

### ISSUE THREAD

**Issue by Kraiggers** [oznu/homebridge-config-ui-x#1044]
Hey I feel dumb posting this, but I will do so in case someone else may benefit from my stupidity. 

I've got homebridge and config-ui-x running fine. On the computer where they are running, I can see the admin panel on localhost:8581. No problems. 

But I can **only** see the admin panel successfully on my iPad if I turn **off** the firewall on my Mac. There's doesn't seem to be a way to open a specific port on Big Sur?  Unless it's tied to an app? I guess?

What am I missing...?

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:3C:E9:D9:D4:16",
        "port": 51826,
        "pin": "703-97-586"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        }
    ],

**Environment:**

* **Node.js Version**: 15.4.0
* **NPM Version**: 7.0.15
* **Homebridge Version**: 1.1.7
* **Homebridge Config UI X Version**: 4.36.0
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
You probably need to add the node.js binary to the firewall exception list.

Run `which node` at the command line to find the full path.

**Comment by Kraiggers** [comment]
Node is already allowed in my exceptions. I'm genuinely perplexed.

**Comment by oznu** [comment]
You are trying to access via http://IP-ADDRESS:8581 right? not http://localhost:8581 on the remote device?

**Comment by Kraiggers** [comment]
Correct. I'm using my local (fixed) ip for my server computer.

**Comment by Kraiggers** [comment]
Which, incidentally, was working fine before I installed hb-server...

**Comment by oznu** [comment]
you can try also whitelisting hb-service and homebridge:

```
which hb-service
```

```
which homebridge
```

**Comment by Kraiggers** [comment]
I added homebridge. No change. 

I cannot add hb-service -- it is grayed out in non-selectable in the file selection panel. (?)

**Comment by Kraiggers** [comment]
Maybe because it's a js file not a binary?

**Comment by oznu** [comment]
Maybe, which is why allowing the node binary should have been the solution.

**Comment by oznu** [comment]
I can't replicate it being blocked in a Big Sur VM with the firewall enabled.

I installed the service with hb-service after enabling the firewall.

![image](https://user-images.githubusercontent.com/3979615/105941711-2409cf80-60b2-11eb-86d7-73513de51b6a.png)

**Comment by oznu** [comment]
I assume you have installed Node.js as per the wiki guide? Using the signed installer from the Node.js website?

**Comment by Kraiggers** [comment]
I don't even know. Maybe?

**Comment by oznu** [comment]
What's your path to node?

**Comment by Kraiggers** [comment]
Usr/local/bin/node
