### ISSUE TITLE
Several Translation Strings Missing

### ISSUE THREAD

**Issue by Alperen-Ozturk** [oznu/homebridge-config-ui-x#1046]
**Describe The Bug:**

I am unable to translate several parts of Config UI X to my language because there is no translation string line related to the those parts available in the translation file.

**Screenshots:**

Some examples:

_drag here text when there is an empty room available_

<img width="205" alt="Ekran Resmi 2021-01-30 15 54 22" src="https://user-images.githubusercontent.com/63194133/106356901-e1473200-6313-11eb-9092-3e04005c7735.png">

_speaker text when there is a tv accessory added to homebridge_

<img width="172" alt="Ekran Resmi 2021-01-30 15 53 47" src="https://user-images.githubusercontent.com/63194133/106356911-f6bc5c00-6313-11eb-8e7d-d1f18285af12.png">

_all of the interface settings - not just limited to this screenshot_

<img width="742" alt="Ekran Resmi 2021-01-30 15 55 04" src="https://user-images.githubusercontent.com/63194133/106356940-24a1a080-6314-11eb-9786-910491ca7700.png">

**Comment by oznu** [comment]
Thanks @Alperen-Ozturk 

I've added the translation string for "Drag Here".

The "Speaker" is the accessory name is from Homebridge / HAP - you can change it by clicking the cog icon on the tile.

The UI Settings is using the generated schema form UI which at this time does not support translations - I plan to move this to a dedicated screen at some point which will include translatable labels.

**Comment by Alperen-Ozturk** [comment]
Thanks for the info.
