### ISSUE TITLE
Child bridge restart option

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#1050]
I use this new feature Child Bridge in my system and working OK, but I have one improvements or feature request.
It will be nice to have possibility display a restart option for Child Bridge direct on The plugin tile below the setting icon. Right now we need after plugin update go to the Bridge settings and here initiate the restart.

**Comment by oznu** [comment]
During this first release my plan is to do try and keep the child bridge stuff isolated from everything else, once it proves mature I'll be doing more integration into the plugin title and the plugins main settings screen.

In the mean time; I've added an optional child bridge widget for the dashboard. I'm thinking most people might replace the QR code widget with this one if they use child bridges.

The widget will provide a quick-restart button for each bridge, and show it's current status:

![image](https://user-images.githubusercontent.com/3979615/106604435-c09d0780-65b3-11eb-9628-bbbc9889e244.png)

This requires Homebridge v1.3.0-beta.49 and Homebridge UI 4.37.1-test.9.

**Comment by grzegorz914** [comment]
Nice 
i se this now and also added to main screen the widget but plugin update make from another screen and after update we need go to main screen first and restart the bridge. This is one step more as press restart option on plugin tile after update it(if available).

**Comment by oznu** [comment]
It might have taken > 1 year... but here we go:

![image](https://user-images.githubusercontent.com/3979615/168608218-8dac6a1b-d39b-47ad-87cb-39e4495870f7.png)
