### ISSUE TITLE
[Bug] Irrigation System GUI Incorrect

### ISSUE THREAD

**Issue by mitch7391** [oznu/homebridge-config-ui-x#1056]
**Describe The Bug:**

Hey @oznu I have noticed an issue with the irrigation system accessory. In config-ui-x it always shows as ‘running’, whereas in HomeKit it shows as ‘scheduled’ and appears off (which is correct).

**Expected behavior:**

It should appear as off and say 'Scheduled' in my case; but seems to think the irrigation system is running. I believe the characteristic responsible is [`ProgramMode`.](https://developers.homebridge.io/#/characteristic/ProgramMode)

**Logs:**

```
N/A
```

**Homebridge Config:**

```json
N/A
```

**Screenshots:**

![510B64FD-5341-49A2-B064-3FDC76D0F88A](https://user-images.githubusercontent.com/40288237/81484804-2b1a5480-927b-11ea-8492-dec9292d5ff9.png)
![98AFCC56-F7C0-4B56-BA41-9162B55B7FE5](https://user-images.githubusercontent.com/40288237/81484805-30779f00-927b-11ea-857a-3b4b746585d9.jpeg)

**Environment:**

* **Node.js Version**: v14.15.4
* **NPM Version**: v6.14.11
* **Homebridge Version**: v1.2.5
* **Homebridge Config UI X Version**: v4.37.0
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Can you show the accessory info (click the cog) when it's in the different states?

**Comment by mitch7391** [comment]
Sprinklers off:
![image](https://user-images.githubusercontent.com/40288237/107111982-2c6ec100-688f-11eb-9b6a-d764702505c0.png)

Sprinkler manual on:
![image](https://user-images.githubusercontent.com/40288237/107112072-c0d92380-688f-11eb-8412-f64164e82929.png)

Not able to get an auto scheduled run example until Sunday :) hope this helps!

**Comment by oznu** [comment]
I will make it "on" based on the value of the "InUse" characteristic

**Comment by mitch7391** [comment]
That makes sense :) thanks Oznu!

**Comment by oznu** [comment]
Please check the beta - this should be fixed.

**Comment by mitch7391** [comment]
That looks much better @oznu :) appears as 'off' when it is 'off'.

![image](https://user-images.githubusercontent.com/40288237/107624520-fae26500-6c95-11eb-9108-473202487b3b.png)
 
One small thing is that even when it is 'off' in Homekit, if it has a program scheduled it will say 'scheduled' instead of 'off'. I can live without that if it is too much effort.

![image](https://user-images.githubusercontent.com/40288237/107624781-5280d080-6c96-11eb-861c-be41b7b42685.png)

Thanks for your work :)
