### ISSUE TITLE
are you kiding me 

### ISSUE THREAD

**Issue by Vale-sail** [oznu/homebridge-config-ui-x#1059]
The date and time on your Homebridge server is different to your browser. This may cause login issues.

**Comment by Vale-sail** [comment]
are you think timezone ?

**Comment by oznu** [comment]
Yes. The tokens used for authentication  generate server side are JSON Web Tokens which are signed with an expiry time stamp. 

If your sever is more than ~7 hours behind the real time then the tokens would be invalid as soon as they are generated.

The times are in UTC and it doesn't care about your timezone.

Fix servers system clock and you won't see this message.

**Comment by Vale-sail** [comment]
my service time is  Fri Feb  5 04:52:30 CST 2021
my edge time is 2021年 2月 5日 星期五 16时52分31秒 CST
you api /api/auth/settings is  serverTimestamp: "2021-02-04T20:52:30.697Z"

the error display  ,how i can do

**Comment by oznu** [comment]
> my service time is Fri Feb 5 04:52:30 CST 2021
my edge time is 2021年 2月 5日 星期五 16时52分31秒 CST

Your server and browser have different times set.  

Your server is 12 hours behind.

04:52 is not the same as 16:52.

**Comment by Vale-sail** [comment]
> > my service time is Fri Feb 5 04:52:30 CST 2021
> > my edge time is 2021年 2月 5日 星期五 16时52分31秒 CST
> 
> Your server and browser have different times set.
> 
> Your server is 12 hours behind (assuming CST = China Standard Time).
> 
> 04:52 is not the same as 16:52.

I sorry . I find it. thank you
