### ISSUE TITLE
Beta Child Bridge feature

### ISSUE THREAD

**Issue by A-vesalius** [oznu/homebridge-config-ui-x#1061]
**Is your feature request related to a problem? Please describe:**
Easier Child bridge setup for optional features

**Describe the solution you'd like:**
Add an "Advanced" button at the bottom of the "Bridge Settings" window that allows Gui configuration of the Bridge name and the optional settings listed on the https://github.com/homebridge/homebridge/wiki/Child-Bridges page.

> You can also optionally set the following:
> 
> - pin - optional - defaults to the same as the main bridge
> - port - optional - defaults to a random unused port assigned by HAPNode.js
> - name - optional - defaults to accessory/platform name
> - model - optional - defaults to same as main bridge
> - manufacturer - optional - defaults to same as main bridge
> - setupID - optional - default to unique setup id generated by HAPNode.js (so we can have different QR codes for each child bridge eventually)

  

**Describe alternatives you've considered:**
Instead of an "advanced" button, a solution that would take up less real estate is to add an edit icon button next to the Bridge Name on the Bridge Settings Window. From there a drop down of the options above would be available to edit. This would be consistent with many of the Plugin Settings windows in Homebridge-config-UI

**Additional context:**

![Screen Shot 2021-02-05 at 10 41 59 AM](https://user-images.githubusercontent.com/64748380/107062653-27cadf80-679f-11eb-9ca1-2da8e9c4c38c.jpg)

**Comment by torandreroland** [comment]
Would also be great to be able to set debug and insecure mode per child bridge.
