### ISSUE TITLE
Intermittent thing happened yesterday after updating homebridge ui and adding some x10 switches to insteonlocal platform

### ISSUE THREAD

**Issue by vhm14u2c** [oznu/homebridge-config-ui-x#1065]
Had a ongoing log that kept repeating Same message in red (for ring)
![image](https://user-images.githubusercontent.com/73516993/107188571-e19b9900-69b5-11eb-8973-9c4fee10b489.jpeg)

Restart made the repeating error stop.

Next checked dependencies, and seen this error-
![image](https://user-images.githubusercontent.com/73516993/107189333-34298500-69b7-11eb-95e8-d5ed172e773e.jpeg)

Next I did a test on npm, and looks like I'm missing a package.json file-
![image](https://user-images.githubusercontent.com/73516993/107189815-f5e09580-69b7-11eb-84af-eeef226dcf5e.jpeg)

Right now, every thing is working (no repeating errors) but guessing some of my config issues might get in the way someday.

Was wondering if there way anything you want me to try to fix those errors I shown, and thanks!

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**
posted above

**Environment:**

* **Node.js Version**:  v12.19.0
* **NPM Version**:  6.14.8
* **Homebridge Version**: 1.1.7
* **Homebridge Config UI X Version**:4.38.0
* **Operating System**: Raspbian 3
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
> Next I did a test on npm, and looks like I'm missing a package.json file-

You shouldn't have one - that's fine. Not sure why you're running npm test? This won't do anything.

> Next checked dependencies, and seen this error-

There error reported is from a dependency of the insteonlocal plugin. If the plugin is still working you can probably ignore it.

> Had a ongoing log that kept repeating Same message in red (for ring)

This is a ring plugin problem.

----

Sorry I can't be if much help, everything you've shown looks fine - apart from ring but as you said a restart solved the problem.

The UI runs in an isolated seperate process to the rest Homebridge so as long as Homebridge is "starting" it's pretty much impossible to cause conflicts or issues with plugins (designed this way intentionally).
