### ISSUE TITLE
Status Page Widget - Child Bridge Bridge Status

### ISSUE THREAD

**Issue by TeslaOwnerTips** [oznu/homebridge-config-ui-x#1066]
**Describe The Bug:**

The gear icons on all widgets stop working.
Any gear icon will work one after the page is reloaded.

**To Reproduce:**

Add any widgets.
Add the Child Bridge Status widget.
Try different gear icons.

**Expected behavior:**

A popup window.

**Logs:**

How do I get this?
```
Show the Homebridge / Homebridge Config UI X logs here.
```
How do I get this?
**Homebridge Config:**

```json
Show your homebridge config.json here
```
{
    "bridge": {
        "name": "Garagebridge",
        "username": "0E:54:FE:25:75:73",
        "port": 51370,
        "pin": "559-90-131"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "teslas": [
                {
                    "id": "5YJSA1EF151",
                    "name": "Tessa",
                    "ble": "84:EE:03:ED:EA:1B",
                    "email": "@yahoo.ca",
                    "password": "****",
                    "access_token": "-",
                    "refresh_token": "-",
                    "expires_in": 0,
                    "expires_at": 0,
                    "token_type": "Bearer",
                    "pressent": false,
                    "type": "occupancy"
                }
            ],
            "ble_beacons": [
                {
                    "id": "0YJSA1E41FF11",
                    "address": "38-B5-df-d4-56-26-3c-8d",
                    "name": "Tile",
                    "pressent": false,
                    "type": "occupancy"
                },
                {
                    "id": "0YJSA1E41FF21",
                    "address": "E2:62:51:1F:23:D8",
                    "name": "LR Beacon 100m",
                    "pressent": false,
                    "type": "occupancy"
                }
            ],
            "sensors": [
                {
                    "id": "1",
                    "name": "One",
                    "type": "occupancy"
                }
            ],
            "platform": "HttpWebHooks"
        }
    ]
}
**Screenshots:**

**Environment:**
Do you mean Mac, Safari?
Mac, Safari
* **Node.js Version**: v14.15.4
* **NPM Version**: v6.14.11
* **Homebridge Version**: 1.1.7
* **Homebridge Config UI X Version**: v4.38.0
* **Operating System**: Raspbian 
* **Process Supervisor**: hb-service 

Node.js Version | v14.15.4
-- | --
v6.14.11
pi
/var/lib/homebridge
/var/lib/homebridge/config.json
Yes

**Comment by oznu** [comment]
This occurred when child bridge support was not enabled in Homebridge (requires beta 1.3).

Fixed in the latest beta build of the UI.
