### ISSUE TITLE
Status Page Widgets Mess-up When Moved

### ISSUE THREAD

**Issue by TeslaOwnerTips** [oznu/homebridge-config-ui-x#1067]
**Describe The Bug:**

When a widget is moved from the bottom up the widgets loose their layout.
**To Reproduce:**

Create 3 rows of widgets.
Move the bottom widget to the top.

**Expected behavior:**

Widgets that are not being moved must maintain the left to right layout.

Below requested information same as issue
#1066 
![Screen Shot 2021-02-09 at 11 09 15 AM](https://user-images.githubusercontent.com/78335749/107394379-cfab1a80-6ac9-11eb-8a9c-dd1da0b78aed.png)

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
You can drag widgets to a location without messing up other widgets if you make space for them first.

Changing how the widget grid will reduce flexibility and mess up everyones existing dashboard layouts.
