### ISSUE TITLE
Local host cannot be reached.

### ISSUE THREAD

**Issue by RakshithGB** [oznu/homebridge-config-ui-x#107]
It says its listening on port 8080 but none of my browsers can open the page.

log from homebridge:
```
  [6/3/2018, 1:20:36 PM] [Config] Using Form Authentication
  [6/3/2018, 1:20:36 PM] [Config] Console v3.7.0 is listening on port 8080.
```

**Comment by oznu** [comment]
Are you trying to access the site on the same device you are running homebridge on?

**Comment by RakshithGB** [comment]
Nope. Homebridge is running on pi and I tried accessing on my Mac and iPhone.

**Comment by oznu** [comment]
Are you attempting to access the site using https://<ip address of pi>:8080 or even https://raspberrypi.local:8080 ?

**Comment by RakshithGB** [comment]
I tried `https://raspberrypi.local:8080` I forgot to try with the IP address directly, thank you it works fine!
