### ISSUE TITLE
Reinstall problem

### ISSUE THREAD

**Issue by MarcinGabrowski** [oznu/homebridge-config-ui-x#1070]
root@raspberrypi:~# sudo npm uninstall -g homebridge-config-ui-x; sudo npm install -g --unsafe-perm homebridge-config-ui-x
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-10T22_54_53_417Z-debug.log
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

**Comment by oznu** [comment]
Delete this:

```
sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
```

**Comment by oznu** [comment]
If that didn't work; delete this too, the re-install:

```
rm -f /usr/local/lib/node_modules/homebridge-config-ui-x
```
