### ISSUE TITLE
Adding support for HTTPs and binding only to a specific interface

### ISSUE THREAD

**Issue by KoMa1978** [oznu/homebridge-config-ui-x#1073]
Hi,

I love this UI!!

The only things I miss so far are:

1. Binding the UI only to a specific interface. In my case the device has 2 interfaces (to allow mDNS reflections between 2 subnets) but I only want to UI on one of the NICs (of course I can filter with iptables but native functionality is better I think).

2. Support for HTTPs and certificates in combination with listening on port 443. Of course I can handle it with NGINX but native support is better.

Thanks a lot,
 KoMa1978

**Comment by KoMa1978** [comment]
Please ignore "1" ...

I just found the "host" directive ...

**Comment by oznu** [comment]
SSL support exists too:

https://github.com/oznu/homebridge-config-ui-x/wiki/Manual-Configuration#enabling-ssl

It replaces the http server / port.

**Comment by KoMa1978** [comment]
WOW ... overread that ...

Is it also possible to bind the UI to port 443?
Or will that not work because it is not started as root?

THANKS!

**Comment by oznu** [comment]
It should run on 443 without root if you grant the systemd service the correct capabilities  on Linux - if you used hb-service to create the service this will have done it for you.

**Comment by KoMa1978** [comment]
Yes just tested it ... works fine. 

Thanks a lot

**Comment by KoMa1978** [comment]
Is there also an option to listen on port 80 and redirect traffic to port 443 that I have missed?

**Comment by oznu** [comment]
You haven't missed it.

**Comment by KoMa1978** [comment]
May I add this as enhancement request? Should I open a new issue or can we take this one?

**Comment by oznu** [comment]
Probably not, nginx is the way I think it should be done - this is how the Homebridge Raspberry Pi image does it.

**Comment by KoMa1978** [comment]
I thought that and that how I realized it. But ngingx only for port redirection sounds like some kind over overkill ;-)
