### ISSUE TITLE
Modify value displaying in a accessory tile

### ISSUE THREAD

**Issue by GTPatriots** [oznu/homebridge-config-ui-x#1075]
**Describe Your Problem:**
I'd like to be able to modify the value that displays in a tile.  For example for a "Air Purifier" tile something besides rotation speed or a "Filter Maintenance" tile something besides the words "Filter Maintenance".  My real goal is I'd like the "Filter Maintenance" tile to display "Filter Life Level".  Is this possible today or do I need a feature request?

**Logs:**
N/A

**Homebridge Config:**

{
    "bridge": {
        "name": "Homebridge 4821",
        "username": "0E:37:CD:64:48:21",
        "port": 51212,
        "pin": "640-05-738"
    },
    "accessories": [
        {
            "name": "Occupied Guest room",
            "delay": 900000,
            "disableSensor": true,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "Airmega",
            "username": "username",
            "password": "password"
        }
    ]
}

**Screenshots:**

![image](https://user-images.githubusercontent.com/78316546/107888025-2a80af80-6ed8-11eb-8e04-307f2e50fa00.png)

**Environment:**

* **Node.js Version**: 14.15.3
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.2.5
* **Homebridge Config UI X Version**: 4.38.0
* **Operating System**:  Windows 
* **Process Supervisor**:  none

**Comment by oznu** [comment]
Hover over the tile, click the cog, edit the name to be whatever you like 😄

**Comment by GTPatriots** [comment]
@oznu , that will change the name.  That's not the goal here.  That's "Airmega Max2-filter" in the screenshot above.  The goal is I want to change the "Filter Maintenance" field, which I believe is blank and thus why the name of the field is being printed (though that is only a guess), to the "Filter Life Level" field which should read as a % of remaining filter life.  If I pull up the cog it says "Filter Life Level" is 34.  My goal would be to see the "34%" instead of "Filter Maintenance".

**Comment by oznu** [comment]
Ah ok. Filter Maintenance accessory type is not currently supported by the Homebridge UI - you could make a pull request to add this functionality.

Currently supported types are here:

https://github.com/oznu/homebridge-config-ui-x/tree/master/ui/src/app/core/accessories/types

**Comment by GTPatriots** [comment]
@oznu , I can't seem to figure out how to open a pull request.  Could we re-open this and convert to an enhancement request?
