### ISSUE TITLE
REST endpoint or cli option to check for out-of-date plugins?

### ISSUE THREAD

**Issue by jusso-dev** [oznu/homebridge-config-ui-x#1080]
**Describe Your Problem:**

Is there a way to programmatically check for out-of-date plugins?

**Logs:**
N/A

```json
Show your homebridge config.json here
```
N/A
**Screenshots:**
N/A

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
N/A

**Comment by oznu** [comment]
Yes. Call the /plugins endpoint - see the Swagger API documentation.

https://github.com/oznu/homebridge-config-ui-x/wiki/API-Reference
