### ISSUE TITLE
Log viewing again broken

### ISSUE THREAD

**Issue by twynne** [oznu/homebridge-config-ui-x#1082]
**Describe The Bug:**
It seems each time I allow config-ui-x to update, it breaks the log viewer configuration.  My log viewing was working fine prior to 4.39, and again today it no longer works.

The configuration is:

            "log": {
                "method": "file",
                "path": "homebridge.log"
            },

The homebridge.log file is in my homebridge folder, which is located at Users/{myuser}/.homebridge.

Further, the link to documentation on how to configure the log viewing is broken.  It links to the GitHub site, but there no longer appears to be any such section on log viewer config.  (See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.)

**To Reproduce:**
1. Confirm log viewing is working
2. Update config-ui-x
3. Observer log viewing no longer working

**Expected behavior:**

As the log viewer configuration has not changed, it should have continued working as it was configured and working previously.

**Logs:**

Loading logs using "file" method...
CMD: sudo -n tail -n 500 -f homebridge.log

execvp(3) failed.: No such file or directory

The log tail command "-n tail -n 500 -f homebridge.log" exited with code 1.
Please check the command in your config.json is correct.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

**Homebridge Config:**

            "log": {
                "method": "file",
                "path": "homebridge.log"
            },

**Environment:**

* **Node.js Version**: 14.15.1
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.5
* **Homebridge Config UI X Version**: 4.39.0
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
> Process Supervisor: hb-service

If you're using hb-service then no log viewer config is required - though I suspect you're not actually using hb-service as your log config would be ignored in this mode.

>    "path": "homebridge.log"

You need a full path here.

Better yet, remove your exisiting service, setup the service again using `hb-service`, and let it all just happen automatically :)

**Comment by twynne** [comment]
Hi there,

I *am* actually using hb-service, and suspect you're right as I've tried entering the full path to the log as /Users/homeserver/.homebridge/homebridge.log and that doesn't work either.  It appears to be ignored as the error message generated is still showing the following:

The log tail command "-n tail -n 500 -f homebridge.log" exited with code 1.
Please check the command in your config.json is correct.

So what do I change the log viewing method to?  None??

**Comment by oznu** [comment]
> So what do I change the log viewing method to? None??

remove it.

**Comment by twynne** [comment]
So in UI Settings, I've changed the log viewing to 'None' and restarted.  I still get the following:

Loading logs using "undefined" method...
CMD: sudo -n tail -n 500 -f homebridge.log

execvp(3) failed.: No such file or directory

The log tail command "-n tail -n 500 -f homebridge.log" exited with code 1.
Please check the command in your config.json is correct.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

**Comment by twynne** [comment]
Or are you suggesting I manually edit the config and remove everything related to logging?

**Comment by oznu** [comment]
Are you restarting after making the changes?

**Comment by twynne** [comment]
Yes, I'm restarting from config-ui.

**Comment by oznu** [comment]
Do this in the terminal:

```
sudo hb-service restart
```

And provide log output from that command here.

**Comment by twynne** [comment]
From terminal I get the following:

sudo hb-service restart
ℹ Restarting Homebridge Service
ℹ Stopping Homebridge Service...
✔ Homebridge Stopped
ℹ Starting Homebridge Service...
✔ Homebridge Started

and from homebridge.log:

[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m Homebridge Storage Path: /Users/homeserver/.homebridge
[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m Homebridge Config Path: /Users/homeserver/.homebridge/config.json
[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m Logging to /Users/homeserver/.homebridge/homebridge.log
[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m OS: Darwin 17.7.0 x64
[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m Node.js v14.15.1 /usr/local/bin/node
[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[37m[2/16/2021, 10:17:38 PM][0m [36m[HB Supervisor][0m UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m Homebridge Storage Path: /Users/homeserver/.homebridge
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m Homebridge Config Path: /Users/homeserver/.homebridge/config.json
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m Logging to /Users/homeserver/.homebridge/homebridge.log
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m OS: Darwin 17.7.0 x64
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m Node.js v14.15.1 /usr/local/bin/node
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[37m[2/16/2021, 10:17:48 PM][0m [36m[HB Supervisor][0m UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m Homebridge Storage Path: /Users/homeserver/.homebridge
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m Homebridge Config Path: /Users/homeserver/.homebridge/config.json
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m Logging to /Users/homeserver/.homebridge/homebridge.log
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m OS: Darwin 17.7.0 x64
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m Node.js v14.15.1 /usr/local/bin/node
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[37m[2/16/2021, 10:17:59 PM][0m [36m[HB Supervisor][0m UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js

**Comment by oznu** [comment]
Run:

```
sudo hb-service uninstall

sudo hb-service install
```

**Comment by twynne** [comment]
Hmmm...

wl21:~ homeserver$ sudo hb-service uninstall
ℹ Removing Homebridge Service
ℹ Stopping Homebridge Service...
✔ Homebridge Stopped
✔ Removed Homebridge Service
wl21:~ homeserver$ sudo hb-service install
ℹ Installing Homebridge Service
✖ ERROR: Port 8581 is already in use by another process on this host.
✖ You can specify another port using the --port flag, eg.
✖ EXAMPLE: hb-service install --port 8581

**Comment by oznu** [comment]
So slowing confirming my suspicions that you're not running hb-service.

**Comment by oznu** [comment]
Stop the service:

```
sudo hb-service stop
```

And please check if you can still access the web interface.

On the status dashboard in the system information widget, does it say "Services Mode: Yes"

**Comment by twynne** [comment]
But the uninstall (above) says it removed the homebridge service.

I get the following:

wl21:~ homeserver$ sudo hb-service stop
? Stopping Homebridge Service...
/Library/LaunchDaemons/com.homebridge.server.plist: No such file or directory
4 Homebridge Stopped

Yes, can still access the web UI.  I'm not seeing 'services mode':


Timezone | GMT+0000
-- | --
macOS
- deleted -
fe80::8c63:71c0:a3c7:d5ab
v14.15.1
v6.14.8
homeserver
/Users/homeserver/.homebridge
/Users/homeserver/.homebridge/config.json

**Comment by oznu** [comment]
Ok, so not using `hb-service` which explains the issue, or you've had two services running, probably an older one from before hb-service was a thing.

Try stop using this:

```
launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist
```

If you're no longer able to access the UI after doing that; remove that plist file.

```
sudo rm -f ~/Library/LaunchAgents/com.homebridge.server.plist
```

Then install using hb-service:

```
sudo hb-service install
```

**Comment by twynne** [comment]
Success!

Clearly my implementation has been around since long before hb-service existed, but it's been running fine for ages as it was.  Hopefully that has sorted it for good.

Must admit I was occasionally having that issue with log viewing, always after updating config-ui, then it seemed to magically sort itself out.

Thanks for the help in any case!

**Comment by oznu** [comment]
Happy to help.

As you're now on a modern setup you've unlocked some new features!

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#features
