### ISSUE TITLE
homebridge -I

### ISSUE THREAD

**Issue by RSMBS** [oznu/homebridge-config-ui-x#109]
helle community,

how do I set up my home bridge so it starts with "homebridge -I" automatically?

**Comment by theo-69** [comment]
Thats not config ui related, However just use systemctl

**Comment by RSMBS** [comment]
i am not really in this topic.
is there any tutorial?

**Comment by theo-69** [comment]
severall try [Google](http://www.lmdfdg.com/?q=systemctl+homebridge)

**Comment by oznu** [comment]
Please see https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-Accessory-Control
