### ISSUE TITLE
NL translations for Homebridge Settings > Network > Network Interfaces missing

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#1092]
**Describe The Bug:**

NL translations for Homebridge Settings > Network > Network Interfaces missing

**To Reproduce:**

1. Set Homebridge UI language to Dutch (nl)
2. View the Homebridge Settings > Network > Network Interfaces screen
3. Observe that the text is in English

**Expected behavior:**

Text of the affected screen should be in Dutch

**Environment:**

* **Homebridge Version**: v1.3.0
* **Homebridge Config UI X Version**: homebridge-config-ui-x v4.39.0
* **Operating System**: Microsoft Windows 10 Home
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Translations are provided by users such as yourself 😄 

Feel free to make a pull request with the missing translations.

https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/i18n/nl.json

**Comment by tooh** [comment]
Created PR with improved NL translation

**Comment by jsiegenthaler** [comment]
@tooh  thanks. I was reporting this for an NL colleague, and could not do the translations myself
