### ISSUE TITLE
Improve mobile install log experience 

### ISSUE THREAD

**Issue by ifeign** [oznu/homebridge-config-ui-x#1097]
**Is your feature request related to a problem? Please describe:**
When using a mobile browser to access the UI to install or update a plugin the update log displays a rapidly scrolling and difficult to read wall of text that would normally be displayed as a progress bar. Instead each increment of the progress bar displays a new line

**Describe the solution you'd like:**
If possible, fix this behavior so that the update log shows an incremental progress bar like on a desktop browser. This is an issue on iOS devices. I am unable to test it on Android.

**Additional context:**
![Untitled-1](https://user-images.githubusercontent.com/32289760/108896377-b033e780-75c9-11eb-8ce4-3671660090aa.jpg)

**Comment by oznu** [comment]
Done, it will now adjust to the screen size correctly.

**Comment by ifeign** [comment]
Wonderful, thank you!
