### ISSUE TITLE
Log enhancement request - Filter Logs

### ISSUE THREAD

**Issue by joberembt** [oznu/homebridge-config-ui-x#1099]
**Is your feature request related to a problem? Please describe:**

I am frustrated when trying to review logs for a single plugin, having to navigate the interspersed logs of the various plugins, especially when it comes to child bridges.

**Describe the solution you'd like:**

I would love the ability to filter logs to show a specific plugin, with or without the "system" homebridge optionally shown as well. I would also like the ability to filter for specific child bridge logs.

**Describe alternatives you've considered:**

Save off log, search for bridge name, save off results - additional steps

**Additional context:**

**Comment by epheterson** [comment]
+1

Wow, just had the same idea and came here to post it! I think the best interface would be to hyperlink the plug-in names on each log line and make them clickable, then if I click one it automagically filters on that string and populates the filter field/box/UI where ever that ends up.

**Comment by ifeign** [comment]
This would be very helpful

**Comment by jsiegenthaler** [comment]
+1
I had the same idea yesterday, and just came here to add the request and saw that other people want it too.

A filter by plugin name would be fantastic

**Comment by jsiegenthaler** [comment]
Bump

**Comment by jsiegenthaler** [comment]
Bump
