### ISSUE TITLE
Restart in Debug Mode option

### ISSUE THREAD

**Issue by carlosgamezvillegas** [oznu/homebridge-config-ui-x#1102]
Hello Team,

When I try to debug the plugins I am writing I have to convert "console.log.debug" to "console.log" and after I am done I have to switch it back.

Would it be possible to add an option to restart Hombridge UI X in debug mode?

I have seen some screenshots of a Debug options being available before, but I can seem to find it.

Thanks.

**Comment by donavanbecker** [comment]
Homebridge settings is where you can find homebridge debug mode

**Comment by carlosgamezvillegas** [comment]
Hello Donovan,

I don't see that option, please look at the image attached.

Thank you.
![Hombridge](https://user-images.githubusercontent.com/67111609/109338752-870a9580-781b-11eb-8c30-4a7ec6f80455.PNG)

**Comment by donavanbecker** [comment]
@carlosgamezvillegas What environment are you running on?

**Comment by carlosgamezvillegas** [comment]
@donavanbecker I have it on a Raspberry Pi, Raspbian GNU/Linux Buster (10),
Node.js Version  v15.4.0,  Version v7.0.15

**Comment by oznu** [comment]
This feature is available when running with "hb-service". See the current instructions on the Homebridge wiki / website.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command
