### ISSUE TITLE
hb-service start is not working

### ISSUE THREAD

**Issue by boldiebold** [oznu/homebridge-config-ui-x#1104]
**Describe The Bug:**

hb-service start is not working, no Homebridge service will start
hb-service run --allow-root is working

**To Reproduce:**

QNAP with LXC container unbuntu 18.04 
standard installation guide for ubuntu
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

**Expected behavior:**

hb-service start will start the service as described

**Logs:**

No logs will provide if I start it hb-service start 

root@HomebridgeOne:/home/piuser# sudo hb-service install --user homebridge
ℹ Installing Homebridge Service
ℹ Created service user: homebridge
ℹ Creating Homebridge directory: /var/lib/homebridge
ℹ Creating default config.json: /var/lib/homebridge/config.json
ℹ Starting Homebridge Service...
✔ Homebridge Started

Manage Homebridge by going to one of the following in your browser:

* http://localhost:8581
* http://192.168.178.20:8581
* http://[fe80::42:3cff:fe54:c8ed]:8581

Default Username: admin
Default Password: admin

✔ Homebridge Setup Complete
```
Show the Homebridge / Homebridge Config UI X logs here.
Log is generated with hb-service run --allow-root 
with hb-service start - no log is generated

[37m[2/28/2021, 11:23:02 AM][0m [36m[HB Supervisor][0m OS: Linux 4.2.8 arm
[37m[2/28/2021, 11:23:02 AM][0m [36m[HB Supervisor][0m Node.js v14.16.0 /usr/bin/node
[37m[2/28/2021, 11:23:02 AM][0m [36m[HB Supervisor][0m Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[37m[2/28/2021, 11:23:02 AM][0m [36m[HB Supervisor][0m UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[0;37m[2/28/2021, 11:23:06 AM] [0m[0;36m[Homebridge UI][0m [0;33mHomebridge Config UI X v4.39.1 is listening on :: port 8581[0m
[37m[2/28/2021, 11:23:06 AM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I
[37m[2/28/2021, 11:23:06 AM][0m [36m[HB Supervisor][0m Started Homebridge v1.3.1 with PID: 3597
[0;37m[2/28/2021, 11:23:07 AM] [0m[0;36m[Homebridge UI][0m [0;33mAdded new user: admin[0m
[0;37m[2/28/2021, 11:23:07 AM] [0m[0;36m[Homebridge UI][0m Username and password have been set to default:
[0;37m[2/28/2021, 11:23:07 AM] [0m[0;36m[Homebridge UI][0m Username: admin
[0;37m[2/28/2021, 11:23:07 AM] [0m[0;36m[Homebridge UI][0m Password: admin
Initializing HAP-NodeJS v0.9.2...
[37m[2/28/2021, 11:23:07 AM] [39mLoaded config.json with 0 accessories and 1 platforms.
[37m[2/28/2021, 11:23:08 AM] [39m---
[37m[2/28/2021, 11:23:08 AM] [39mLoaded plugin: homebridge-config-ui-x@4.39.1
[37m[2/28/2021, 11:23:08 AM] [39mRegistering platform 'homebridge-config-ui-x.config'
[37m[2/28/2021, 11:23:08 AM] [39m---
[37m[2/28/2021, 11:23:08 AM] [39mLoading 1 platforms...
[37m[2/28/2021, 11:23:08 AM] [39m[36m[Config][39m Initializing config platform...
[37m[2/28/2021, 11:23:08 AM] [39m[36m[Config][39m Running in Service Mode
Preparing Advertiser for 'Homebridge FAD3 172D' using bonjour-hap backend!
Setup Payload:
X-HM://0024UCWNL4NWO
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[30m[47m                       [49m[39m
[30m[47m    ┌────────────┐     [49m[39m
[30m[47m    │ 830-17-297 │     [49m[39m
[30m[47m    └────────────┘     [49m[39m
[30m[47m                       [49m[39m
Starting to advertise 'Homebridge FAD3 172D' using bonjour-hap backend!
[37m[2/28/2021, 11:23:09 AM] [39mHomebridge v1.3.1 (Homebridge FAD3) is running on port 51727.

**Homebridge Config:**
```json
Show your homebridge config.json here
{
    "bridge": {
        "name": "Homebridge FAD3",
        "username": "0E:9C:71:9D:FA:D3",
        "port": 51727,
        "pin": "830-17-297"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}



**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: <!-- node -v -->
14.16.0
* **NPM Version**: <!-- npm -v -->
* 6.14.11
* **Homebridge Version**: <!-- homebridge -V -->
1.3.1
* **Homebridge Config UI X Version**:
4.39.1
* 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
ubuntu 18.04  - LXC Container. (Qnap Docking station)
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
* hb-service


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by oznu** [comment]
What does the output of `sudo journalctl -n 200 -u homebridge` show?

**Comment by boldiebold** [comment]
root@HomebridgeOne:/home/piuser# sudo journalctl -n 200 -u homebridge
-- Logs begin at Sun 2021-02-28 11:07:25 UTC, end at Sun 2021-02-28 11:31:25 UTC. --
Feb 28 11:30:01 HomebridgeOne systemd[4551]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:01 HomebridgeOne systemd[4551]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:01 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
Feb 28 11:30:01 HomebridgeOne systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 28 11:30:04 HomebridgeOne systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Feb 28 11:30:04 HomebridgeOne systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 182.
Feb 28 11:30:04 HomebridgeOne systemd[1]: Stopped Homebridge.
Feb 28 11:30:04 HomebridgeOne systemd[1]: Starting Homebridge...
Feb 28 11:30:05 HomebridgeOne systemd[1]: Started Homebridge.
Feb 28 11:30:05 HomebridgeOne systemd[4559]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:05 HomebridgeOne systemd[4559]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:05 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
Feb 28 11:30:05 HomebridgeOne systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 28 11:30:08 HomebridgeOne systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Feb 28 11:30:08 HomebridgeOne systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 183.
Feb 28 11:30:08 HomebridgeOne systemd[1]: Stopped Homebridge.
Feb 28 11:30:08 HomebridgeOne systemd[1]: Starting Homebridge...
Feb 28 11:30:09 HomebridgeOne systemd[1]: Started Homebridge.
Feb 28 11:30:09 HomebridgeOne systemd[4567]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:09 HomebridgeOne systemd[4567]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:09 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
Feb 28 11:30:09 HomebridgeOne systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 28 11:30:12 HomebridgeOne systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Feb 28 11:30:12 HomebridgeOne systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 184.
Feb 28 11:30:12 HomebridgeOne systemd[1]: Stopped Homebridge.
Feb 28 11:30:12 HomebridgeOne systemd[1]: Starting Homebridge...
Feb 28 11:30:13 HomebridgeOne systemd[1]: Started Homebridge.
Feb 28 11:30:13 HomebridgeOne systemd[4575]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:13 HomebridgeOne systemd[4575]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:13 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
Feb 28 11:30:13 HomebridgeOne systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 28 11:30:16 HomebridgeOne systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Feb 28 11:30:16 HomebridgeOne systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 185.
Feb 28 11:30:16 HomebridgeOne systemd[1]: Stopped Homebridge.
Feb 28 11:30:16 HomebridgeOne systemd[1]: Starting Homebridge...
Feb 28 11:30:16 HomebridgeOne systemd[1]: Started Homebridge.
Feb 28 11:30:16 HomebridgeOne systemd[4583]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:16 HomebridgeOne systemd[4583]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:16 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
Feb 28 11:30:16 HomebridgeOne systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 28 11:30:19 HomebridgeOne systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Feb 28 11:30:19 HomebridgeOne systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 186.
Feb 28 11:30:19 HomebridgeOne systemd[1]: Stopped Homebridge.
Feb 28 11:30:19 HomebridgeOne systemd[1]: Starting Homebridge...
Feb 28 11:30:20 HomebridgeOne systemd[1]: Started Homebridge.
Feb 28 11:30:20 HomebridgeOne systemd[4591]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:20 HomebridgeOne systemd[4591]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:20 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
Feb 28 11:30:20 HomebridgeOne systemd[1]: homebridge.service: Failed with result 'exit-code'.
Feb 28 11:30:23 HomebridgeOne systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Feb 28 11:30:23 HomebridgeOne systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 187.
Feb 28 11:30:23 HomebridgeOne systemd[1]: Stopped Homebridge.
Feb 28 11:30:23 HomebridgeOne systemd[1]: Starting Homebridge...
Feb 28 11:30:24 HomebridgeOne systemd[1]: Started Homebridge.
Feb 28 11:30:24 HomebridgeOne systemd[4599]: homebridge.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Feb 28 11:30:24 HomebridgeOne systemd[4599]: homebridge.service: Failed at step CAPABILITIES spawning /usr/lib/node_modules/homebridge-config-ui-x/d
Feb 28 11:30:24 HomebridgeOne systemd[1]: homebridge.service: Main process exited, code=exited, status=218/CAPABILITIES
lines 1-58


Am 28.02.2021 um 12:30 schrieb oznu <notifications@github.com<mailto:notifications@github.com>>:

sudo journalctl -n 200 -u homebridge

**Comment by oznu** [comment]
You're running an older kernel (passed through from QNAP) that does not support some of the systemd features hb-services uses, edit the `/etc/systemd/system/homebridge.service` file and remove the `CAPABILITIES` and `Ambient CAPABILITIES` lines, then reload systemd with `sudo systemctl daemon-reload` and restart the service.

**Comment by oznu** [comment]
Alternatively just use the Homebridge Docker image, there in an Ubuntu variant available.

**Comment by boldiebold** [comment]
> You're running an older kernel (passed through from QNAP) that does not support some of the systemd features hb-services uses, edit the `/etc/systemd/system/homebridge.service` file and remove the `CAPABILITIES` and `Ambient CAPABILITIES` lines, then reload systemd with `sudo systemctl daemon-reload` and restart the service.

Thanks a lot, working now. Great support.
