### ISSUE TITLE
New logfile entries?

### ISSUE THREAD

**Issue by drheck** [oznu/homebridge-config-ui-x#1106]
Hello,

i am using version: homebridge-config-ui-x v4.39.1
I have since the update following messages in the logfile:
[28.2.2021, 13:43:50] [Zone1Q2] Switch is currently OFF
    root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 26142
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root

How can i solve these entries?

Thank you for support.

Peter

**Comment by oznu** [comment]
What you are seeing is not new, it's been there for a long time.

Replace your service supervisor with `hb-service` (still backed by systemd) and these entries will not be displayed.

Remove your existing service first.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command

**Comment by drheck** [comment]
Hello oznu,

thank you for your answer.
I have running homebridge with the old way.
I am using the following commands.
sudo systemctl restart homebridge
systemctl status homebridge
sudo systemctl stop homebridge
sudo systemctl start homebridge
sudo systemctl disable homebridge
sudo systemctl enable homebridge

The homebridge is running on port 8080 and the files (config.json etc.) are in the directory: /var/homebridge

I have tried to install the hb-service in the following way:
sudo systemctl stop homebridge
sudo systemctl disable homebridge


Then I installed:
sudo hb-service install --user homebridge

After this, i have a empty config.json in an other directory (I think it was /etc/homebridge)?

How can I get all my old homebridge running with hb-service in the old directory or can I copy all files from /var/homebridg to /etc/homebridge ?

Thank you very much for helping,
Peter


Mit freundlichen Grüßen
   Dr.-Ing. Peter Heck
________________________________
Dr.-Ing. Peter Heck
Beethovenstraße 5
67685 Weilerbach
Telefon: +49 6374 993322
Mobiltelefon: +49 172 6124786


Von: oznu <notifications@github.com>
Gesendet: Sonntag, 28. Februar 2021 14:51
An: oznu/homebridge-config-ui-x <homebridge-config-ui-x@noreply.github.com>
Cc: drheck <drheck@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [oznu/homebridge-config-ui-x] New logfile entries? (#1106)


What you are seeing is not new, it's been there for a long time.

Replace your service supervisor with hb-service (still backed by systemd) and these entries will not be displayed.

Remove your existing service first.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command
