### ISSUE TITLE
update fails

### ISSUE THREAD

**Issue by BerkTam** [oznu/homebridge-config-ui-x#111]
Guys, I can see that the update to 3.8.0 fails because of a wrong link …  Can someone confirm?
If yes, than this should actually not happen as you can imagine whats behind this beautiful work …

**Comment by BerkTam** [comment]
Yes, it says that there is an issue with the given … and it hastn right for permission

**Comment by oznu** [comment]
Can you show the full output from the update modal?

**Comment by BerkTam** [comment]
it says again 
npm ERR! code EINTEGRITY
npm ERR! erno EINTEGRITY
npm ERR! Invalid response body while trying to fetch: https://registry.npmjs.org-body-parser: Integrity verification fialed for …

this shows that something simply does not work …

**Comment by oznu** [comment]
Hi,

This should not happen, please try and reinstall to ensure all files are in place:

https://github.com/oznu/homebridge-config-ui-x#1-errors-during-installation

```shell
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by BerkTam** [comment]
Hi oznu, 

I have tried that already but havent work neither. 

Any other plan?

regards
bet

**Comment by BerkTam** [comment]
unfortunately NO,  removing config-ui-x does work and is fine but 
whenever I try to install it again it brings up the same message.

**Comment by oznu** [comment]
Can you provide the full output?

A copy/paste of the command entered till it's exit. It is very hard to tell what is going on with only partial snippets.

**Comment by oznu** [comment]
The latest version, 3.8.3, might fix the `EINTEGRITY` issue. I've removed a postinstall script that was messing with the `node_modules` directory after installation.

**Comment by BerkTam** [comment]
Hi Oznu, 

thanks really for your help here as I think this is a very good tool. 

Unfortunately I am still facing this issue. I have again completely removed 
the config-ui-x and tried to install it again. 
It says again:

code EINTEGRITY
errno EINTEGRITY 
ERR! invalid responde body while trying to fetch: https://registry.npmjs.org/body-parser: <https://registry.npmjs.org/body-parser:> Integrity verification failed for ……

After that I need to install a full backup from the whole SD-Cart I have done weeks before otherwise 
I cannot use config-ui-x anymore. 

Can you please check that again?


May I ask where you are located or where from?

Kind regards

Berkant

**Comment by oznu** [comment]
Try this:

```
sudo npm cache clean --force
sudo npm install -g npm
sudo npm uninstall -g homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by BerkTam** [comment]
Hi, thanks for feedback. 

Can you please confirm that cache cleaning npm wont delete any other
homebridge-plugin?

If yes, than this description doesnt helps really. 

Thx

**Comment by oznu** [comment]
It won't. It just clears the cache.

**Comment by seanbetts** [comment]
I jus tried to update from 3.8.3 to 3.8.5 through the UI and it failed. I got the following message:

USER: sean
DIR: /usr/local/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-config-ui-x@latest

sudo: npm: command not found

Command failed. Please review log for details

Any ideas?

**Comment by BerkTam** [comment]
Thanks and great. 

Finally it this has worked. Homebrige-ui-x is up to date now.

**Comment by mkormendy** [comment]
@seanbetts what SHELL and PATH are you setting up with your environment variables for launching homebridge with?

On my MacMini, I have a LaunchDaemon plist loading homebridge automatically on startup. Inside the plist I had to add both the PATH and the SHELL environment variables.
