### ISSUE TITLE
registry.npm.js.org not reachable after update

### ISSUE THREAD

**Issue by GitGabKat** [oznu/homebridge-config-ui-x#1126]
**Describe The Bug:**
After having updated the plug-in, there is no check for updates possible anymore due to not able to reach registry.npm.js.org 
However I am able to ping the service properly from my devices. 

**To Reproduce:**
If I got to Status at the ui the service try to connect. You find then the massage beneath at the logs. 

**Expected behavior:**
Even the message itself doesn't interrupt the service. There is no check for updates possible, which is essential. 

**Logs:**
![image](https://user-images.githubusercontent.com/65626478/110788658-2fcee100-826f-11eb-86e6-d4b7fa82f831.jpeg)

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json {
    "bridge": {
        "name": "Homebridge",
        "username": "XXXXXX",
        "port": 51687,
        "pin": "XXXX",
        "advertiser": "bonjour-hap",
        "bind": [
            "wlan0"
        ]
    }
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**:14.15.5
* **NPM Version**: 7.6.2
* **Homebridge Version**: 1.3.2
* **Homebridge Config UI X Version**:4.40.0
* **Operating System**: Raspbian
* **Process Supervisor**:

**Comment by karel-hu** [comment]
Hi all

I'm experiencing the same errors, while Homebridge works flawlessly.
Further info: i cannot update or install new plugins from the ui: 
![hbfail](https://user-images.githubusercontent.com/81379492/112511512-c2ed3800-8d92-11eb-8db2-b16efe28c442.jpg)
, but i can with command line & npm install method.
Also the npmjs registry checks out fine from web browser.

Karel
