### ISSUE TITLE
using the api to change Brightness does not work. 

### ISSUE THREAD

**Issue by justme-1968** [oznu/homebridge-config-ui-x#1128]
**Describe The Bug:**
using the api endpoint ​/api​/accessories​/{uniqueId} to change Brightness does not work for me. other characteristic types like On, TargetPosition or Hue and Saturation do work

**To Reproduce:**
PUT {"characteristicType": "Brightness", "value": "41" } does nothing

**Expected behavior:**
Brightness should change. like for the other working characteristic types.

how can i verify if the error is on my side or not? I'm sending data created exactly the same way to the same endpoint.

**Comment by oznu** [comment]
```
To Reproduce:
PUT {"characteristicType": "Brightness", "value": "41" } does nothing
```

The value should be an integer (unquoted).

**Comment by justme-1968** [comment]
i see. but why then is the behavior different
