### ISSUE TITLE
Home bridge is working but status is "Homebridge Not running - View Logs"

### ISSUE THREAD

**Issue by myevit** [oznu/homebridge-config-ui-x#1129]
Not sure is it's UI or Homebridge itself has a bug. UI reporting that homebridge is't running but everything is working just fine.

![image](https://user-images.githubusercontent.com/13375246/111039015-13ef4a80-83e9-11eb-9b76-492b3e6ebda9.png)

**Comment by oznu** [comment]
Try the beta, it changes they way the status is detected for hb-service users.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by dbisping** [comment]
Unsubscribe

O the joy of my spirit - it is uncaged - it darts like lightning!
It is not enough to have this globe or a certain time,
I will have thousands of globes and all time.

- Walt Whitman

**Comment by myevit** [comment]
Homebridge Config UI X v4.41.0-test.3 - fixed Not Running issue.
