### ISSUE TITLE
Question on updates

### ISSUE THREAD

**Issue by dcaccount** [oznu/homebridge-config-ui-x#113]
Hello,
I have installed Config UI X and it works smoothly. Thanks!

I have also updated Homebridge always with no issue.

What I am wondering if Config UI X allows to detect updates of the single plugin and to update them.

Please advise, thanks, dan

**Comment by oznu** [comment]
Hi @dcaccount,

This plugin will monitor all your installed plugins and advise when an update is available. As with Homebridge itself; your can also update plugins with a single click from inside the UI.
