### ISSUE TITLE
README.md Documentation Typo

### ISSUE THREAD

**Issue by shanemcw** [oznu/homebridge-config-ui-x#1134]
**Describe The Bug:**
Readme documentation typo

**To Reproduce:**
View the README.md

**Expected behavior:**
the sentence
"If the Accessories tab is not show then you are not running …"
should be
"If the Accessories tab is not *shown* then you are not running …"

**Logs:**
Logs are NA

Show the Homebridge / Homebridge Config UI X logs here.
Logs are NA

**Homebridge Config:**
NA

Show your homebridge config.json here
NA

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* v1.3.4
* **Homebridge Config UI X Version**:
* v4.40.0
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* Ubuntu
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
Thanks
