### ISSUE TITLE
Homebridge widget layout

### ISSUE THREAD

**Issue by T-IOOO** [oznu/homebridge-config-ui-x#1137]
The widgets for uptime, CPU and Memory are centered within the widget.
I personally think that the three Homebridge Widget icons should be centered aswell. It would look much better.
Also the widget should be renamed to "Status" or maybe "Homebridge Status" to be more correct?

**Comment by nov-** [comment]
Thank you for amazing ui plugin! is there any plan to add widget with free space on sd card left? because I have a situation when if there no free space on sd card then HomeKit always show all homebridge accessories like "No Response" even after cleaning sd card.
