### ISSUE TITLE
NPM version not listed correct in UI

### ISSUE THREAD

**Issue by tomsteenbakkers** [oznu/homebridge-config-ui-x#1140]
**Describe The Bug:**
When Homebridge is started and the Config UI X interface is loaded it shows a different version of NPM.

**To Reproduce:**
When I update NPM to the latest version nothing happens on Config UI X.

**Expected behavior:**
When checking the version using Terminal I get the right version number. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/24613800/112714870-e3290e00-8edc-11eb-95d8-712c3349967c.png)

![image](https://user-images.githubusercontent.com/24613800/112714883-eb814900-8edc-11eb-839c-563ee280173b.png)

**Environment:**
See screenshot

**Comment by oznu** [comment]
Restart service (not just Homebridge) and the current version will be displayed.

**Comment by tomsteenbakkers** [comment]
Already did that. Also rebooted the RaspberryPI but not effect.

Is there a special command to update NPM? I have used under the account of pi:

`sudo npm -g install npm`

**Comment by macjeff** [comment]
Rather than open a new topic- any way for homebridge to offer NPM updates?   I can start a new topic if you want but for example right now I am on 6.14.11 and they are on a 7.x version I think at least.  I am always worried to update.

**Comment by eliassylvain** [comment]
Hello,
I got the same issue. The NPM version shown on the web interface is not the right one installed on my homebridge, I already tried a reboot. 
![Capture d’écran 2021-04-06 à 14 04 56](https://user-images.githubusercontent.com/68815997/113708283-530b7580-96e1-11eb-9809-ed4845c8d9fa.png)
![Capture d’écran 2021-04-06 à 14 05 24](https://user-images.githubusercontent.com/68815997/113708285-530b7580-96e1-11eb-8fc0-682bd7349f2f.png)

**Comment by oznu** [comment]
You both likely have multiple copies of Node / NPM installed and it's picking up the alternative copy.

The UI only presents what it finds on disk (after a restart so the in-memory cache is cleared).

You can see the full path to the copy of NPM the UI is reading the version from by hovering over the "npm version" text in the system information widget. Compare this path to the output of the `which npm` command.

**Comment by tomsteenbakkers** [comment]
You are right. The UI is looking to `/usr/lib` and the nom command is looking at `/usr/local/lib/node_modules/npm`

Do you know how I can change this?

**Comment by oznu** [comment]
You probably have two copies of Node.js installed as well, this is going to cause you all sorts of headaches until cleaned up.

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

**Comment by tomsteenbakkers** [comment]
Ok, this looks like a reinstall 🙁 You mention only Node.js. In the UI this version is listed correct, it's only NPM which is not correct. It there a way to only fix NPM?

**Comment by oznu** [comment]
You'll have two copies of Node as well. One in `/usr/local/bin/node` and other other in `/usr/bin/node`

**Comment by tomsteenbakkers** [comment]
I think I know what has caused this. I have installed `n` to update node. This was because I didn't know that `hb-service` has a command to update node. I need to reserve some time to do a complete re-install.

**Comment by oznu** [comment]
>  I have installed n to update node.

That'll do it :)

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js#what-to-avoid

**Comment by tomsteenbakkers** [comment]
I'm using Homebridge for a long time now and not used to using the UI. I will plan a compete reinstall. I think that's the best option. The RaspberryPi is only used for Homebridge.

**Comment by oznu** [comment]
Consider using the Homebridge image then, you can do a backup of your existing install, and restore it to a fresh install.

https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

Probably a 15 minute job depending on your internet speed, and you don't loose any config and shouldn't have to re-pair with HomeKit or reset up automations / rooms etc.

**Comment by tomsteenbakkers** [comment]
I already saw the Wiki so I will take that route! Thanks for the support.

**Comment by macjeff** [comment]
How do we know what version of NPM we should run with the latest Homebridge and UI?  I am on 6.14.11.

**Comment by oznu** [comment]
v6.4.11 is the current version that ships with LTS Node.is and is the recommended version. Users do not need to update npm manually, it will be updated to the recommended version whenever they update Node.js.

**Comment by macjeff** [comment]
> v6.4.11 is the current version that ships with LTS Node.js and is the recommended version. Users do not need to update npm manually, it will be updated to the recommended version whenever they update Node.js.

THANK YOU.  Thats what I thought.  I do know it updates with NPM but i saw in some log there is a new 7.x NPM.  I think an installer log but I did not update.

**Comment by tomsteenbakkers** [comment]
> I already saw the Wiki so I will take that route! Thanks for the support.

Installed today a fresh Homebridge. Not using the homebridge image because I use a SSD to boot. Restore went flawless and everything is up-and-running without any problems.

and moist important. With 1 Node installation!
