### ISSUE TITLE
UI is not displaying installed NPM version

### ISSUE THREAD

**Issue by bearreth** [oznu/homebridge-config-ui-x#1147]
**Describe The Bug:**
UI isn't showing correct NPM version. I am running 7.8.0, but Homebridge UI displays 6.14.12 as current version, and tooltip suggests latest NPM version.

**Expected behavior:**
Display current NPM version.

**Environment:**

* **Node.js Version**: v14.16.1
* **NPM Version**: 7.8.0
* **Homebridge Version**: 1.3.4
* **Homebridge Config UI X Version**: 4.41.0
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Do a full restart of the service.
