### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by theo-69** [oznu/homebridge-config-ui-x#115]
Some Words are not translated 100% are giving confusion, example instead of Installieren (install) there is Installiert (installed).

**Comment by oznu** [comment]
Hi @theo-69,

The translations are here:

https://github.com/oznu/homebridge-config-ui-x/tree/master/ui/src/i18n

Would you mind creating a PR to fix any changes you think should be made?

@razer4908

**Comment by theo-69** [comment]
no problem will try this week

**Comment by theo-69** [comment]
done, will check later if there is more ;-)

**Comment by razer4908** [comment]
I already corrected myself, but the merge of my PR didn´t changed anything in Config Ui X

**Comment by theo-69** [comment]
strange, I have it on one of my homebridges but not on all. There where only one or two small misunderstandings. Like "Installiert" instead of "Installieren" And I thought "Config" is making more sense then "Konfig"

**Comment by razer4908** [comment]
I also stuggled between "Config" and "Konfig" but @oznu has given this before so i did not change it. Thank you for correcting.  "Installiert" instead of "Installieren" was also an not wanted eyecatcher for me  
I hope this time everything will be fine :)

**Comment by theo-69** [comment]
Just figured out, you have to clear your browser cache :-)

**Comment by theo-69** [comment]
and found some lower upper case typos will fix them, just for the Eye ;-)
