### ISSUE TITLE
Newer Categories not known in Homebridge UI for ids >32

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#1154]
**Is your feature request related to a problem? Please describe:**

Homebridge UI shows "Other" for Categories that it does not know
Specifically:
Categories

32 TARGET_CONTROLLER
33 ROUTER
34 AUDIO_RECEIVER
35 TV_SET_TOP_BOX
36 TV_STREAMING_STICK

See https://developers.homebridge.io/#/categories

**Describe the solution you'd like:**

Homebridge UI should support all currently known categories.

**Comment by oznu** [comment]
Done in the next version.
