### ISSUE TITLE
Filter option in Log File view

### ISSUE THREAD

**Issue by Donni1966** [oznu/homebridge-config-ui-x#1169]
Hi, first of all a big positive feedback for this plugin. 

one of the nice to features was: 

in the Log set a filter zu see only one plugin infos. By maybe type in the plugin name and than, all messages auto filters by this text. 

do you think this will be possible?

**Comment by montanaishome** [comment]
+1! if there just was a search bar that would grep the log by a particular string, it would be extremely useful!
