### ISSUE TITLE
Restart Bridge Server Without Rebooting Device

### ISSUE THREAD

**Issue by mickelsn** [oznu/homebridge-config-ui-x#1173]
**Is your feature request related to a problem? Please describe:**
Not directly related to a problem.

**Describe the solution you'd like:**
I've recently moved to "native" Homebridge from HOOBS. The one feature that HOOBS has that I wish was available via Homebridge UI was to restart the bridge server software without rebooting the entire device (in my case, a Raspberry Pi 4). That way I wouldn't lose access to other services running on my Pi when the Homebridge server is restarted to install a new plugin or whatever.

**Describe alternatives you've considered:**
N/A -- HOOBS has this feature in their web interface, and it was useful.

**Additional context:**
N/A

**Comment by oznu** [comment]
Press the restart button on the menu bar. The only way your entire server would restart if you've been selecting the "Restart Server" option from the dropdown menu.
