### ISSUE TITLE
Enable Homebridge to set unique serial number for every device

### ISSUE THREAD

**Issue by mbierman** [oznu/homebridge-config-ui-x#1187]
**Problem**
1. HomeKit requires accessories to have unique serial numbers. It is robust enough to not break if an accessory has a non unique serial numbers for now, but that shouldn’t be relied on. It could break in the future. There is at least one solution, [Controller](https://apps.apple.com/us/app/controller-for-homekit/id1198176727), that depends on Homekit accessories having unique serial numbers. This has also caused other applications issues such as Home Assistant and Eve.
2. None of the homebridge plugins I use or have searched allow you to set the serial number. 
3. Homebridge never required plugins to make this work, even Verified plugins.
4. Homebridge already implements uuids for every accessory for internal purposes, but those are not exposed to homekit. 
5. One solution is to use these serial numbers for homekit to solve an underlying problem.

**Proposed solution**
I’d like to homebridge to provide a unique serial number for each accessory. Allowing the user to override that might be nice, but not essential.

`config.json` could have a new block that associates accessories and Serial numbers. These could be defaulted to unique values but editable to the user. If edited of course that could cause automation rules to break, etc. but the user would have the choice and if it were unique then that won't happen often.

 If a plug-in supports serial numbers then the ID could be left out, duplicated, or this new association could take priority over what the plugin says. 
 
Another approach is to use the UUIDs homebridge already creates for the Accessory page when an accessory of the plug-in doesn’t provide one. (Thanks to @rcoletti on discord for suggesting this.)

**Alternate approach**
Leave this to the thousands of homebridge plugins. Problem: that won’t ensure that any particular user gets unique serial numbers on every accessory. Homebridge is the best place to solve this problem.

**Comment by mkormendy** [comment]
This seems to be an issue with the iOS app (Controller in particular) and not Homebridge/Homekit.

This is also the issue of the plugin itself and I suggest contacting the plugin creator to fix this.

If the plugin doesn't assign a serial number characteristic (unique or otherwise) on accessory setup, then the default name will be something like "Default-serialnumber". That default value is already a convenience afforded by Homebridge, but Homebridge isn't in the business of:

1. assigning meaningful visible unique serial number values beyond being told to do that by the plugin
2. accommodating external iOS application missing or strict requirements

The keyword here to remember is the word "bridge", and that's exactly what Homebridge is, a bridge to HomeKit, a messenger .. don't kill it.

**Comment by mbierman** [comment]
I have to respectfully, but strongly disagree.

1. This isn’t a requirement by some 3rd party app. HomeKit devices are supposed to have unique IDs. The fact that it doesn’t break without them doesn’t mean it isn’t wrong.
2. Putting the onus on plugins means this will probably never be done. It isn’t even required for a plug-in to be verified.
3. Homebridge already knows about unique accessories and assigns them unique IDs for the accessory layout. Why can’t that be used as the accessory ID for bonjour purposes as well?
4. Who said anything about killing anything? This would bring homebridge accessories more in align with HomeKit certified accessories without creating a huge burden on plug-in developers.

**Comment by mkormendy** [comment]
I'll just link to [this overly lengthy discussion on Discord](https://discord.com/channels/432663330281226270/432671265774632961/860773864883355658) here for my reasoning.

**Comment by mbierman** [comment]
Please don’t close.

**Comment by mbierman** [comment]
I still would love to see this addressed.

**Comment by cronjevh** [comment]
I want to use Homebridge with Home Assistant, and the lack of serial numbers is preventing me from discovering devices that I can see in iOS Home. 

This issue on the Home Assistant/ Homekit Controller project seems to make a good argument for why it's reasonable to expect unique serial numbers. https://github.com/home-assistant/core/issues/34121

I'm seeing if I can figure out a solution at the plugin level for the Paradox Alarm plugin I'm using https://github.com/e-mcgee/paradox_platform/issues/38
