### ISSUE TITLE
Fix Radio Buttons Styling In Plugin Config Interface

### ISSUE THREAD

**Issue by mkormendy** [oznu/homebridge-config-ui-x#1191]
**Describe The Bug:**
I posted this on Discord but I'm not sure if you use this for tracking changes.
I am using radio buttons for some options in the `config.schema.json` for my plugin and I noticed that the styling isn't quite up to snuff as it is with the checkboxes.

**To Reproduce:**
See attached config.schema.json file (search for "radios").
[config.schema.json.txt](https://github.com/oznu/homebridge-config-ui-x/files/6820734/config.schema.json.txt)

**Expected behavior:**
Should take on the styling of larger round circles and have a bit of padding between the control object and the label, use checkbox fields as a reference for adjustment.

**Screenshots:**
![Screen_Shot_2021-07-12_at_2 10 52_PM](https://user-images.githubusercontent.com/1437667/125737006-cb72a0da-6321-405a-8cbe-1991807c5af8.png)

**Comment by mkormendy** [comment]
unstale

**Comment by mkormendy** [comment]
🎲

**Comment by AdamHumble** [comment]
I would like to work on this issue. Can you please assign?

**Comment by mkormendy** [comment]
Not stale. Please respond to Adam.

**Comment by mkormendy** [comment]
Not stale. Please assign to @AdamHumble per his request.
