### ISSUE TITLE
Plugins page doesn't load

### ISSUE THREAD

**Issue by gtrnz** [oznu/homebridge-config-ui-x#12]
After updating to the current version and configuring, the plugin page just stays loading with the spinning wheel. 
This is my config for the plugin

![screen shot 2018-01-14 at 1 56 38 pm](https://user-images.githubusercontent.com/25584103/34911605-ca6cc11a-f932-11e7-9d4d-0f1f5c20a2b2.png)

**Comment by oznu** [comment]
Strange, it should at least throw an error if the http request to load the installed plugins failed:

https://github.com/oznu/homebridge-config-ui-x/blob/296e682ae2478011bf337ebe505b5aba7e38107f/ui/src/app/plugins/plugins.component.ts#L29-L35

Are there any errors in the javascript console of the browser?

Are there any errors in the homebridge log output?

**Comment by gtrnz** [comment]
I couldn't find any and rebooted it just now and its functioning as expected :)
