### ISSUE TITLE
Not working with node 10

### ISSUE THREAD

**Issue by theo-69** [oznu/homebridge-config-ui-x#120]
Hi I can not getting startet with 10.4.0

**Comment by oznu** [comment]
I have this running on 10.4.0. Make sure you rebuild the npm module after updating.

**Comment by theo-69** [comment]
strange did that and still how did you rebuild?

**Comment by oznu** [comment]
This should do the trick:

```
cd $(npm -g prefix)
npm rebuild
```

**Comment by oznu** [comment]
Or just uninstall and reinstall the plugin.

**Comment by theo-69** [comment]
thats what I did :-(, will try later again... Thanks

**Comment by oznu** [comment]
Closing as this does work on Node 10+.

![image](https://user-images.githubusercontent.com/3979615/41349754-43bfcb2e-6f54-11e8-9035-72c3bfde2784.png)

@theo-69  feel free comment here if you need any other assistance with this your setup though.

**Comment by theo-69** [comment]
yep confirming it works...
