### ISSUE TITLE
update v4.41.2 suddenly sudo gets error 'usr/bin/sudo must be owned by uid 0

### ISSUE THREAD

**Issue by bmonninkhof** [oznu/homebridge-config-ui-x#1201]
**Describe The Bug:**
update v4.41.2 suddenly sudo gets error 'usr/bin/sudo must be owned by uid 0

**To Reproduce:**
Don't update to the latest version would be my advise. I restored my raspbian with a backup, updated all files with apt. Then I updated the plugins one by one. Every time I tested sudo su and with all plugins there were no problems. The last plugin I updated is Homebridge config UI-X. The result error sudo.

**Expected behavior:**
Result "usr/bin/sudo must be owned by uid 0"

**Logs:**
-

Show the Homebridge / Homebridge Config UI X logs here.
-

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.16.1
* **NPM Version**: 7.11.2
* **Homebridge Version**: Initializing HAP-NodeJS v0.9.4...1.3.4
* **Homebridge Config UI X Version**: v4.41.2
* **Operating System**:  Debian 
* **Process Supervisor**: ???

**Comment by DigiH** [comment]
Unfortunately I had the same issue when updating to 4.41.5 just now :(
