### ISSUE TITLE
Fails to open after adding SSL code

### ISSUE THREAD

**Issue by TheSwartz** [oznu/homebridge-config-ui-x#121]
Hello

I was experimenting with adding the SSL configuration. After adding the lines (using the config editor in homebridge-config-ui-x), the config web page fails to load. I am certain it's because I am not pointing to the correct cert files (as I'm trying to figure out how to do this and actually haven't installed it yet; long story, trying to figure this out).

I had backed up the prior config.json code before doing this.

So, I SSH'd into my Raspberry Pi
cd .homebridge/
nano config.json

and what comes up is a very old version of my config.json file. So, I deleted that, pasted the backup (prior to adding the SSL code), and reboot my Pi. But I'm still not able to open the Config UI web page (either through http or https).

I'm a little confused, but I am guessing that Config UI changes the location of the config.json file that is being used? If so, where is this?

Thanks!

**Comment by TheSwartz** [comment]
Hello!

I don't see a /var/lib/homebridge (cd /var/lib/ and then listing doesn't show a homebridge folder)

So, I'm a little confused why the homebridge/config.json file was radically different than what was showing within the config ui editor. But I move on..

Homebridge otherwise is working fine.

I ran a command to see what processes are running (ps -acx), and homebridge and homebridge-conf are running.

I've rebooted the Pi a few times through all this.

The IP address of the Pi hasn't changed, so I'm still trying to open via http://xxx.xxx.xxx.xxx:8080

If I were to uninstall homebridge-config-ui-x and then re-install, might this fix the problem? If so, any recommended ways to do this? Or different ideas?

Thanks!!

**Comment by oznu** [comment]
Try opening via https://xxx.xxx.xxx.xxx:8080, note the `https`.

**Comment by oznu** [comment]
You'll need to find where your real config.json is located.

Try looking at the config for whatever process supervisor you're using. There will be a -U flag with a path to the directory.

If homebridge is running as another user, for example, homebridge,  it might even be under `/home/homebridge/.homebridge`

**Comment by TheSwartz** [comment]
I'm sorry, this is starting to get way beyond what I have known what to do... but your last comment triggered something to help me figure it out.

Thankfully, I had written down exactly every single step I used to set all this up in the first place (I had done a lot of trial and error to find what worked; and posted [here](url=https://forum.universal-devices.com/topic/23772-how-to-homebridge-on-raspberry-pi-for-controlling-isy-with-apple-homekit-and-siri-integration/?tab=comments#comment-236283)). It was a step referring to these instructions https://timleland.com/setup-homebridge-to-start-on-bootup/

It was under /var/homebridge

Got it. Thanks a lot!!

**Comment by oznu** [comment]
Great, the logs from the config plugin will hopefully tell you why it couldn't start the plugin with https (cert invalid etc).

I intentionally did not make it fall back to `http` if it was configured incorrectly; as this might have created a security vulnerability, which for an app that some people use to secure their houses (locks) wouldn't be very good.

**Comment by TheSwartz** [comment]
Absolutely! makes sense!

Now that I've figured out how to go back and forth, time to figure out how to add SSL certs, etc.

Thanks! This is an indispensable add-on for homebridge!
