### ISSUE TITLE
Your GUI does not offer the latest version of my plugin to install

### ISSUE THREAD

**Issue by RMCob** [oznu/homebridge-config-ui-x#1210]
**Describe Your Problem:**
I am the author of RMCob/homebridge-wyze-connected-home-op. The latest version is V0.5.6, but when searching for the plugin using your GUI it only offers V0.5.3 as the latest version available. Obviously I have something misconfigured in my repository but I don't know what that is. Thanks in advance for any assistance.....

**Environment:**

* **Node.js Version**:    v14.17.4
* **NPM Version**:    v6.14.14
* **Homebridge Version**:    1.3.4
* **Homebridge Config UI X Version**:    4.41.2
* **Operating System**:    Raspbian 
* **Process Supervisor**:    hb-service

**Comment by oznu** [comment]
You need to publish to NPM.

https://www.npmjs.com/package/homebridge-wyze-connected-home-op
