### ISSUE TITLE
config UI not working behind reverse proxy for proper security

### ISSUE THREAD

**Issue by ustaerk** [oznu/homebridge-config-ui-x#1211]
**Describe The Bug:**
Homebridge-config-ui-x uses absolute URIs and URLs almost everywhere, making it impossible to run behind a proxy server providing proper security such as TLS termination and monitoring.

Apart from the way that homebridge-config-ui-x is currently being served being a security risk (by default binding to all interfaces, well-known standard admin password, no TLS, etc.), it is accepted best practice to make any webapp reverse proxy friendly in order to support TLS termination and other features provided by proxies.

**To Reproduce:**

1. Install homebridge
2. Install http(s) proxy, e.g. nginx
3. configure proxy to serve homebridge
4. Homebridge-config-ui-x won't work even when providing rewrites for most URLs. It fails at the latest when trying to dynamically fetch child modules of the web app

**Expected behavior:**
Homebridge-config-ui-x works out of the box because it uses relative URIs

**Logs:**
not applicable

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

not applicable

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: any
* **NPM Version**: any
* **Homebridge Version**: any
* **Homebridge Config UI X Version**: any
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by ustaerk** [comment]
Possible duplicate of #628.

**Comment by mriksman** [comment]
Same here. Surely someone has a fix?

**Comment by vniehues** [comment]
still no fix for this?

**Comment by Unstable0** [comment]
This is still not fixed
