### ISSUE TITLE
mqttthing plug-in cannot load in version 1.3.5

### ISSUE THREAD

**Issue by EjvindHald** [oznu/homebridge-config-ui-x#1225]
This morning I upgraded Homebridge from version 1.3.4 to version 1.3.5, and all my device related to mqttthing plugin disappeared from the Home app.

In the log I receive an error message like this:
ERROR LOADING PLUGIN homebridge-mqttthing:
/homebridge/node_modules/homebridge-mqttthing/index.js:1282
let data = message?.toString() ?? '';

and a SyntaxError: Unexpected token.

After that many other error messages, which are all derived from the plugin not loaded.

I am not sure whether this a Homebridge problem or it is problem in the plugin. But it happens after upgrade to a new Homebridge version.

**Comment by arachnetech** [comment]
Please see https://github.com/arachnetech/homebridge-mqttthing/issues/479 - mqttthing 1.1.31 required Node.js 14. Currently your options are to upgrade to Node.js 14 or downgrade to mqttthing 1.1.30.

**Comment by EjvindHald** [comment]
Thanks for making me aware. I had just been running Homebridge in Docker for a long time and was not aware that I need to refresh the docker image from time to time to get new updated version of node red.
