### ISSUE TITLE
Label/alt text for dropdown menu in Plugins Page

### ISSUE THREAD

**Issue by rfiorentino1** [oznu/homebridge-config-ui-x#1226]
**Bug Description:**
Hi. I've been using HomeBridge for a while, and REALLY appreciate this UI, it's incredible, thank you!
I'm totally blind, and use a screen reader called VoiceOver, on Mac OS, to navigate and use the computer. The UI web interface works beautifully with the screenreader, except for one thing. I can't see the label/button for the menu to uninstall a plugin. Is there any way you could look into fixing this?
I'm also a software developer, so I'd be happy to help you troubleshoot/test this as well.

**To Reproduce:**
This is very hard to describe how to reproduce, if you don't know how to properly use/navigate with VoiceOver. But in general:
1. Turn on VoiceOver by pressing Command f5, or on newer Macbook laptops, holding command and pressing the power button 3 times quickly.
2. Using arrow keys, navigate through the Plugins page, and notice that you can see the plugin name, GitHub repository, settings, etc. But you can't click on the dropdown for uninstalling, etc.

**Environment:**

* **Node.js Version**: 16.9.1
* **NPM Version**: 7.21.1
* **Homebridge Version**: 1.3.5
* **Homebridge Config UI X Version**: 4.41.2
* **Operating System**: Mac OS Catalina (10.15.7)
* **Process Supervisor**: HB-Service

**Comment by rfiorentino1** [comment]
This issue also applies to the main drop-down on the homepage, to get to settings, users, etc., as well as any sliders, like turning on debug mode, etc.

**Comment by oznu** [comment]
Thanks, I suspect it's due to me using non-button/anchor elements as clickable items. I'll fix that up.

**Comment by oznu** [comment]
I've gone through the UI and fixed these up where I've spotted them. There could be a few items still missing.

You can test in @4.41.5-test.2 or later.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by rfiorentino1** [comment]
I'm so sorry, just realized this issue was still open and thought I replied to you earlier. Everything looks great now, thank you so much! Only thing I still can't see is the terminal window where I can type from the UI, and the logs that appear in the text box on the status page. But I don't mind either of these at all, because I can get to the actual log file from my computer, and same with terminal. Thank you so much, I really appreciate it
