### ISSUE TITLE
Connection failed: NT_STATUS_HOST_UNREACHABLE

### ISSUE THREAD

**Issue by fender7083** [oznu/homebridge-config-ui-x#1234]
**Describe Your Problem:**
I built a new desktop PC. My old one had homebridge successfully working. Now I must have forget a step. It would be amazing to have this feature again, I posted log and config. I have no practical programming language skills. Thanks!
[homebridge.log.txt](https://github.com/oznu/homebridge-config-ui-x/files/7448679/homebridge.log.txt)

**Logs:**

[31/10/2021, 07:43:28] [PC] NetworkDevice "PC" (192.168.1.13) went from status "Online" to "Shutting Down"
[31/10/2021, 07:43:28] [PC] Attempting to shut down "PC" (192.168.1.13) using "net"
[31/10/2021, 07:43:34] [PC] An error occured while trying to shut down "PC" (192.168.1.13): Error: Command failed: net rpc shutdown --ipaddress 192.168.1.18 --user forkoff%1965
Could not connect to server 192.168.1.18
Connection failed: NT_STATUS_HOST_UNREACHABLE
Could not connect to server 192.168.1.18
Connection failed: NT_STATUS_HOST_UNREACHABLE

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'net rpc shutdown --ipaddress 192.168.1.18 --user forkoff%1965',
  stdout: '',
  stderr: 'Could not connect to server 192.168.1.18\n' +
    'Connection failed: NT_STATUS_HOST_UNREACHABLE\n' +
    'Could not connect to server 192.168.1.18\n' +
    'Connection failed: NT_STATUS_HOST_UNREACHABLE\n'
}
[31/10/2021, 07:43:34] [PC] Waiting for shutdown grace time (15000ms) for "PC" (192.168.1.13)
[31/10/2021, 07:43:49] [PC] NetworkDevice "PC" (192.168.1.13) went from status "Shutting Down" to "Online"

```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge Pi",
        "username": "0E:79:7D:3D:54:D4",
        "port": 51365,
        "pin": "936-58-373"
    },
    "accessories": [
        {
            "name": "PC",
            "ip": "192.168.1.13",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "16:18:c3:ff:36:06",
            "broadcastAddress": "192.168.1.13",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownCommand": "net rpc shutdown --ipaddress 192.168.1.18 --user forkoff%1965",
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": false,
            "accessory": "NetworkDevice"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "app_list": false,
            "devices": [
                {
                    "name": "Samsung q80T",
                    "ip": "192.168.1.11",
                    "mac": "44:5C:E9:90:95:96",
                    "uuid": "01132feb-82d5-42f4-baf4-a17bbf83e254",
                    "options": [
                        "Frame.RealPowerMode"
                    ],
                    "inputs": [
                        {
                            "type": "app"
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        }
    ],
    "disabledPlugins": [
        "homebridge-winpc-mg",
        "homebridge-brpc",
        "homebridge-winpc"
    ]
}

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Windows / 
* **Process Supervisor**: none?


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by many7695** [comment]
I’m getting this when adding Homebridge to home 
![5061AFD7-B103-4880-ABDE-FE66B9CA9B00](https://user-images.githubusercontent.com/3122959/140619536-91a91d3f-2905-4fcb-9841-0f2cc11e2066.png)
