### ISSUE TITLE
Update error for version 4.41.3

### ISSUE THREAD

**Issue by cl4udiu5** [oznu/homebridge-config-ui-x#1243]
<img width="1010" alt="Bildschirmfoto 2021-11-25 um 14 51 04" src="https://user-images.githubusercontent.com/74124378/143454001-b650a52c-e252-468e-aa19-75e979775072.png">

**Describe Your Problem:**
Update error when running the update from terminal (macOS).
Update error when running the update from homebridge web interface (macOS Safari).
See Screenshot

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "sessionTimeout": 28800,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            },
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "192.168.0.59"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "noResponse": true,
            "resource": true,
            "users": {
                "001788FFFE28C21C": "ZakWR-pTjHhrN81Onbsnbfjshd87jCjUrSFJjwbHUPN"
            },
            "platform": "Hue"
        },
        {
            "name": "Harmony",
            "hubIP": "192.168.0.251",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "TVAccessory": true,
            "mainActivity": "Watch TV (WZ)",
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "Watch Blu-ray",
                    "CommandsList": [
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "Samsung Blu-ray Player;Play"
                        },
                        {
                            "CommandName": "BACK",
                            "NewCommand": "Samsung Blu-ray Player;Pause"
                        },
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Samsung Blu-ray Player;PopUp"
                        }
                    ]
                }
            ],
            "switchAccessories": true,
            "platform": "HarmonyHubWebSocket"
        },
        {
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "TV",
                    "ip": "192.168.0.234",
                    "mac": "64:1C:AE:E4:30:BA",
                    "inputs": [
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "Disney+",
                            "type": "app",
                            "value": "3201901017640"
                        },
                        {
                            "name": "Prime Video",
                            "type": "app",
                            "value": "3201512006785"
                        },
                        {
                            "name": "DAZN",
                            "type": "app",
                            "value": "3201607009920"
                        },
                        {
                            "name": "Spotify",
                            "type": "app",
                            "value": "3201606009684"
                        },
                        {
                            "name": "ARD Mediathek",
                            "type": "app",
                            "value": "3201412000679"
                        },
                        {
                            "name": "ZDF Mediathek",
                            "type": "app",
                            "value": "3201705012365"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Mute",
                            "mute": true
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        }
    ],
    "accessories": [],
    "disabledPlugins": [
        "homebridge-laundrify-official"
    ]
}
```

**Environment:**

* **Node.js Version**: 16.13.0
* **NPM Version**: 8.1.4
* **Homebridge Version**: 1.3.8
* **Homebridge Config UI X Version**: 4.41.2
* **Operating System**: Raspbian
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by tombenton55** [comment]
I’m getting the same issue

**Comment by FranciRoosters** [comment]
Same

**Comment by Stetocasa** [comment]
Same

**Comment by Stetocasa** [comment]
https://github.com/homebridge/homebridge/issues/3018

**Comment by oznu** [comment]
Manually delete the folder listed under the "dest" part of the error.

**Comment by Stetocasa** [comment]
> Manually delete the folder listed under the "dest" part of the error.

Thanks
Could you provide more details on how do it ?
Thanks

**Comment by oznu** [comment]
> Could you provide more details on how do it ?

```
sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-*
```

or for other users:

```
sudo rm -rf /usr/lib/node_modules/.homebridge-config-ui-x-*
```

**Comment by Stetocasa** [comment]
pi@homebridge:~ $ sudo npm install -g homebridge-config-ui-x --unsafe-perm
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-26T08_20_53_124Z-debug.log
pi@homebridge:~ $ sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-*
pi@homebridge:~ $ sudo rm -rf /usr/lib/node_modules/.homebridge-config-ui-x-*
pi@homebridge:~ $ sudo npm install -g homebridge-config-ui-x --unsafe-perm
npm WARN deprecated class-transformer@0.3.2: This release contains a breaking change from 0.3.1 but otherwise functions properly. Please read the changelog on Github to learn more.

changed 348 packages, and audited 349 packages in 4m

38 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
pi@homebridge:~ $ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file
^[[B^[[B^[[B^[[B^[[B
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-26T08_27_31_875Z-debug.log
pi@homebridge:~ $

**Comment by Stetocasa** [comment]
Above my log after your input, the broswer still not loading the UI 🤔

**Comment by oznu** [comment]
Did you restart after?

**Comment by Stetocasa** [comment]
> Did you restart after?

Yes

**Comment by oznu** [comment]
Run

```
sudo hb-service stop
sudo hb-service install --user homebridge
```

**Comment by saltysmith1** [comment]
> > Could you provide more details on how do it ?
> 
> ```
> sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-*
> ```
> 
> or for other users:
> 
> ```
> sudo rm -rf /usr/lib/node_modules/.homebridge-config-ui-x-*
> ```
> 
> Then try install again:
> 
> ```
> sudo npm install -g homebridge-config-ui-x --unsafe-perm
> ```

Thanks @oznu this fixed it for me

**Comment by Stetocasa** [comment]
> Run
> 
> 
> 
> ```
> 
> sudo hb-service stop
> 
> sudo hb-service install --user homebridge
> 
> ```

Now can access the UI, good news!
Any chance to recover previous json config? Seems that all plug-in has already installed but I lost the config

**Comment by oznu** [comment]
It should be on disk somewhere, however if it's not showing up it's not in the default location - /var/lib/homebridge ob Linux - those command didn't remove any config.

You could try looking in /home/pi/.homebridge/

**Comment by FranciRoosters** [comment]
Si, what’s the exact command line that fixes it? And why do you lose the json config?

**Comment by Stetocasa** [comment]
> It should be on disk somewhere, however if it's not showing up it's not in the default location - /var/lib/homebridge on Linux - those command didn't remove any config.
> 
> 
> 
> You could try looking in /home/pi/.homebridge/
> 
> 
> 
> 

Thanks, I installed homebridge in my PI3+ trough the image.
Can you tell me how navigate into the folder in order to find the previous config? Sorry I'm in a beginner phase

**Comment by Stetocasa** [comment]
> Si, what’s the exact command line that fixes it? And why do you lose the json config?

The procedure wrote by @oznu generated a new instance and in HomeKit this generated a new hub to be added

**Comment by FranciRoosters** [comment]
So, not really a fix then, is it?

**Comment by Stetocasa** [comment]
> So, not really a fix then, is it?
> 
> > On 26 Nov 2021, at 09:59, Stetocasa ***@***.***> wrote:
> > 
> > ﻿
> > Si, what’s the exact command line that fixes it? And why do you lose the json config?
> > 
> > The procedure wrote by @oznu generated a new instance and in HomeKit this generated a new hub to be added
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

The only positive thing compared a reflash sd is that all plugins are already installed 
Recovering the old config this will help to avoid the new config in homebdige and let "just" the HomeKit automation new setup
I wanna die

**Comment by Stetocasa** [comment]
@oznu Any possibility to recover the previous homebridge instance ?

**Comment by oznu** [comment]
The instructions provided will not have removed your config. If it's not there then some other command must have removed it; or homebridge was setup in a non-standard way so the config is in a different location.

**Comment by Stetocasa** [comment]
> The instructions provided will not have removed your config. If it's not there then some other command must have removed it; or homebridge was setup in a non-standard way so the config is in a different location.

Can you help me please to find it?

**Comment by Stetocasa** [comment]
> The instructions provided will not have removed your config. If it's not there then some other command must have removed it; or homebridge was setup in a non-standard way so the config is in a different location.

pi@homebridge:~ $ /var/lib/homebridge/config.json
-bash: /var/lib/homebridge/config.json: Permission denied

**Comment by cl4udiu5** [comment]
> > Could you provide more details on how do it ?
> 
> ```
> sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-*
> ```
> 
> or for other users:
> 
> ```
> sudo rm -rf /usr/lib/node_modules/.homebridge-config-ui-x-*
> ```
> 
> Then try install again:
> 
> ```
> sudo npm install -g homebridge-config-ui-x --unsafe-perm
> ```

Thank you @oznu. Works fine for me.

**Comment by adrianopery** [comment]
> sudo hb-service install --user homebridge

I just could execute the first command.
After that, my homebridge doesn't start anymore.

**Comment by tombenton55** [comment]
I’m not sure what happened but my instance is toast too. Rebuilding from scratch isn’t fun.

**Comment by FranciRoosters** [comment]
So, to make sure I understand, @oznu’s solution fixes the issue but requires you to rebuild all of your HomeKit set-up from scratch? What is the reason for this issue in the first place anyway? Thank you.

**Comment by saltysmith1** [comment]
> @oznu’s solution fixes the issue but requires you to rebuild all of your HomeKit set-up from scratch?

Nope didn’t have to rebuild mine from scratch followed it slighty different and it’s working as it should 

> > > 
> Thanks @oznu this fixed it for me tho i did it slightly different i ran sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-* then i ran sudo hb-config and updated from there

**Comment by FranciRoosters** [comment]
This 100% won’t erase my entire HomeBridge settings and HomeKit setup, right?

**Comment by adrianopery** [comment]
I'm facing the same issue but after I executed the commands

> > Could you provide more details on how do it ?
> 
> ```
> sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-*
> ```
> 
> or for other users:
> 
> ```
> sudo rm -rf /usr/lib/node_modules/.homebridge-config-ui-x-*
> ```
> 
> Then try install again:
> 
> ```
> sudo npm install -g homebridge-config-ui-x --unsafe-perm
> ```

I executed the commands and my Homebridge shows as Updated, even show the new version on the dashboard.
For some reason, after some time, the bridge restarts and show the old version again.
I really don't understand what is happening.

Any idea?

**Comment by adrianopery** [comment]
After that, on dashboard is showing 4.41.3 but, after some time, the homebridge restart and again is on version 4.41.2.

**Comment by adrianopery** [comment]
Any update on this issue?

**Comment by FranciRoosters** [comment]
I haven’t input any sudo commands. I don’t feel safe doing it.

**Comment by adrianopery** [comment]
> I haven’t input any sudo commands. I don’t feel safe doing it.
> […](#)
> On 30 Nov 2021, at 17:33, adrianopery ***@***.***> wrote: ﻿ Any update on this issue? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I tried, but doesn't work.
It's crazy it......
The upgrade is complete as successful but after a restart, revert for old version!

**Comment by oznu** [comment]
For the late comers, solution here: https://github.com/oznu/homebridge-config-ui-x/issues/1243#issuecomment-979530200
