### ISSUE TITLE
hb-service update-node fails for node-darwin-arm64

### ISSUE THREAD

**Issue by ahndee** [oznu/homebridge-config-ui-x#1246]
**Describe The Bug:**
If the original node installation an Apple M1 hardware is using the official darwin-arm64 version of node, "hb-service update-node" fails with "Architecture not supported: arm64."

**To Reproduce:**
1. Install node using https://nodejs.org/dist/v16.13.0/node-v16.13.0-darwin-arm64.tar.gz
2. Run "sudo hb-service update-node"

**Expected behavior:**
Node should be updated to 16.13.1

**Logs:**
N/A

**Homebridge Config:**
N/A

**Screenshots:**
N/A

**Environment:**

* **Node.js Version**: v16.13.0
* **NPM Version**: 8.2.0
* **Homebridge Version**: 1.3.8
* **Homebridge Config UI X Version**: v4.41.3
* **Operating System**: macOS 12.0.1
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Hi @ahndee,

I've made some changes so allow this to work.

Can you please test?

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

I've you've already updated to 16.13.1 you can test the process by downgrading using the tool:

```bash
# downgrade
sudo hb-service update-node 16.13.0

# upgrade to latest LTS
sudo hb-service update-node
```

**Comment by ahndee** [comment]
Updated to 4.41.4-test.2 via the GUI and was able to use use update-node after that. Thanks!
