### ISSUE TITLE
Is upgrading to 1.3.8 safe?

### ISSUE THREAD

**Issue by bjornand1** [oznu/homebridge-config-ui-x#1247]
Having had my Homebridge setup messed up completely by trying to upgrade from 1.3.5 to 1.3.6, I keep seeing the alert that 1.3.8 is available. Is it likely this upgrade will cause problems or have people generally have this run without problems?

**Comment by oznu** [comment]
Should be fine. 1.3.8 fixed a few bugs overlooked in 1.3.6.
