### ISSUE TITLE
Blank accessory screen, -I & config seem ok

### ISSUE THREAD

**Issue by colparkes1** [oznu/homebridge-config-ui-x#1248]
Hi, I have Homebridge & Config-UI-X installed and working on a Raspberry Pi 2 running Bullseye.
I just can’t get any accessories to show up in the accessories tab, been trying for days and it’s driving me nuts! I’d appreciate any help you can give.
I’m definitely set to run in insecure mode (tried both directly in /etc/default/homebridge and using the slider in the gui).
My config.json works in terms of homebridge is happy with it and I can see and control my devices/accessories through the HomeKit app on my iPhone.
I’m also trying to setup the Homebridge-Alexa plugin so Homebridge is set to run as root with —allow-root option in /etc/default/homebridge

> HOMEBRIDGE_OPTS=-U "/var/lib/homebridge" -I --allow-root

> UIX_STORAGE_PATH="/var/lib/homebridge"

> # To enable web terminals via homebridge-config-ui-x uncomment the following line

> HOMEBRIDGE_CONFIG_UI_TERMINAL=1

> DISABLE_OPENCOLLECTIVE=true

The only thing showing up in the /var/lib/homebridge/homebridge.log is the Alexa plug-in asking me to check my config:

> 11/12/2021, 16:59:33] [Alexa] ERROR: HAP Discovery failed, please review config

**Homebridge Config:**

{
    "bridge": {
        "name": "Homebridge",
        "username": "DD:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "bind": [
            "enxb827eb3445bb"
        ]
    },
    "description": "blah blah.",
    "platforms": [
        {
            "platform": "LightWaveRF",
            "name": "LightWaveRF",
            "ip_address": "192.168.1.5",
            "manager_host": "web.trustsmartcloud.com",
            "email": "colsemail",
            "pin": "1234",
            "devices": [
                {
                    "roomId": 1,
                    "roomName": "Garage",
                    "deviceId": 1,
                    "deviceName": "Door",
                    "deviceType": "S"
                },
                {
                    "roomId": 3,
                    "roomName": "Back Garden",
                    "deviceId": 1,
                    "deviceName": "Lights",
                    "deviceType": "S"
                },
                {
                    "roomId": 3,
                    "roomName": "Back Garden",
                                        "deviceId": 2,
                    "deviceName": "Sprinkler Upper",
                    "deviceType": "S"
                },
                {
                    "roomId": 3,
                    "roomName": "Back Garden",
                    "deviceId": 3,
                    "deviceName": "Sprinkler Centre",
                    "deviceType": "S"
                },
                {
                    "roomId": 3,
                    "roomName": "Back Garden",
                    "deviceId": 4,
                    "deviceName": "Sprinkler Patio",
                    "deviceType": "S"
                },
                {
                    "roomId": 2,
                    "roomName": "Whole House",
                    "deviceId": 1,
                    "deviceName": "Pergola Lights",
                    "deviceType": "S"
                },
                {
                    "roomId": 4,
                    "roomName": "Front Garden",
                    "deviceId": 1,
                    "deviceName": "Lights",
                    "deviceType": "S"
                }
            ]
        },
        {
            "name": "Config",
            "port": 8581,
                        "platform": "config"
        },
        {
            "name": "Alexa",
            "username": "colin@*********.co.uk",
            "password": "ColsPasswd",
            "pin": "031-45-154",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        }
    ],
    "accessories": [
        {
            "name": "Lounge Left",
            "id": 1000001,
            "prog": false,
            "accessory": "Somfy RTS Remote"
        },
        {
            "name": "Lounge Right",
            "id": 1018617,
            "prog": false,
            "accessory": "Somfy RTS Remote"
        },
        {
            "name": "Lounge Both",
            "id": 1857477,
            "prog": true,
            "accessory": "Somfy RTS Remote"
        }
    ]
}

**Environment:**

* **Node.js Version**: 
V16.13.1
* **NPM Version**: 
8.1.2
* **Homebridge Version**: 
1.3.8
* **Homebridge Config UI X Version**:
V4.41.3
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
Raspbian Bullseye
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
hb-service

**Comment by oznu** [comment]
```json
"bind": [
"enxb827eb3445bb"
]
```

Check your network settings allow calls from the host back to this network interface. The accessory discovery process attempts to connect on the IP advertised.

**Comment by colparkes1** [comment]
Hi, thanks very much for replying.
You were right, it’s a network problem, I think IPv6 is the issue. I’ve disabled it on my Pi and reinstalled Homebridge + Config UI and I now have Accessories and Alexa is happy!
Thanks again for your help.
