### ISSUE TITLE
Missing Icons since 4.41.4

### ISSUE THREAD

**Issue by cl4udiu5** [oznu/homebridge-config-ui-x#1249]
**Describe The Bug:**
After the update 4.41.4 some icons are missing / wrong.

<img width="1776" alt="Bildschirmfoto 2021-12-14 um 13 41 57" src="https://user-images.githubusercontent.com/74124378/146000605-495f66fe-8228-4289-bdbc-db13b5459be2.png">
<img width="1776" alt="Bildschirmfoto 2021-12-14 um 13 42 02" src="https://user-images.githubusercontent.com/74124378/146000613-adeecb4a-b7f3-4c7b-a228-bb0c91cb6e72.png">

**Environment:**

* **Node.js Version**: 16.13.1
* **NPM Version**: 8.2.0
* **Homebridge Version**: 1.3.8
* **Homebridge Config UI X Version**: 4.41.4
* **Operating System**: Raspbian

**Comment by oznu** [comment]
I can't replicate this, and the UI build hasn't changed for a few releases in a row.

Please force refresh the page, if the problem persists re-install the UI.
