### ISSUE TITLE
Upgrade node,js on my synology/docker is not working

### ISSUE THREAD

**Issue by ChalesGiron** [oznu/homebridge-config-ui-x#1253]
**Describe The Bug:**
When I try to upgrade node,js on my synology/docker using "sudo hb-service update-node" I am running in the following issue:

/homebridge # sudo hb-service update-node
ℹ Updating Node.js from v14.17.1 to v16.13.1...
✖ Updating Node.js on Alpine Linux / Docker is not supported by this command.
✖ To update Node.js you should pull down the latest version of the oznu/homebridge Docker image.
/homebridge # 

**Environment:**

* **Node.js Version**: 	v14.17.1
* **NPM Version**: v6.14.13
* **Homebridge Version**: v1.3.8
* **Homebridge Config UI X Version**: v4.41.4 
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
To update Node.js you should pull down the latest version of the oznu/homebridge Docker image.

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology#updating-homebridge-on-synology
