### ISSUE TITLE
update stuck

### ISSUE THREAD

**Issue by saltysmith1** [oznu/homebridge-config-ui-x#1254]
Trying to update config-ui and its got stuck, Screen shot attached. any ideas how to fix please 
<img width="801" alt="Screenshot 2021-12-17 at 12 51 59" src="https://user-images.githubusercontent.com/87123578/146548100-838bc133-18ed-4132-b313-e7299c41b321.png">

**Comment by oznu** [comment]
Be patient, while that window is open it's doing things.

**Comment by saltysmith1** [comment]
> Be patient, while that window is open it's doing things.

its been like it for about 15 mins now should it take that long?

**Comment by saltysmith1** [comment]
1 Hour later and still stuck on the same screen :-(

**Comment by saltysmith1** [comment]
Fitxed it had to ssh into pi and  ran sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-* then i ran sudo hb-config and updated from there

**Comment by oznu** [comment]
Great, happy that you've fixed it.
