### ISSUE TITLE
update to 4.41.5 fails at the very end

### ISSUE THREAD

**Issue by fate8383** [oznu/homebridge-config-ui-x#1256]
2205 verbose stack Error: process terminated
2205 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:194:39
2205 verbose stack     at process.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
2205 verbose stack     at process.emit (node:events:402:35)
2206 verbose cwd /usr
2207 verbose Linux 5.10.63-v7+
2208 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-config-ui-x@latest"
2209 verbose node v16.13.1
2210 verbose npm  v8.1.2
2211 error process terminated
2212 error signal SIGTERM
2213 verbose exit 1

4.41.4 update also gave error but tried few times and it worked somehow. Now I have the same issue with 4.41.5 and it is already my 5th attempt, not successful. Restarted HB and server (rpi) still no success. Any suggestion?

also seeing this in HB logs
[12/18/2021, 12:03:48 AM] [Homebridge UI] npm cache clear command executed with exit code 0
[12/18/2021, 12:03:48 AM] [Homebridge UI] Command failed. Please review log for details.

**Comment by jamieburchell** [comment]
I was able to get the command to complete by stopping the homebridge service first. Suspect some sort of resource exhaustion?

**Comment by fate8383** [comment]
> I was able to get the command to complete successfully by stopping the homebridge service first. Suspect some sort of resource exhaustion? Stopping the service first freed up ~60MB RAM.

How do you update from UI, if HB service is stopped? I need to run command from root rpi then.

**Comment by saltysmith1** [comment]
i was a bit hesitant to update as the last one almost broke my setup, i updated it via ssh into the pi then sudo hb-config and updated from there without any issues

**Comment by jamieburchell** [comment]
> > I was able to get the command to complete successfully by stopping the homebridge service first. Suspect some sort of resource exhaustion? Stopping the service first freed up ~60MB RAM.
> 
> How do you update from UI, if HB service is stopped? I need to run command from root rpi then.

`
sudo service homebridge stop
sudo -E -n npm install -g homebridge-config-ui-x@latest
`

**Comment by fate8383** [comment]
> > How do you update from UI, if HB service is stopped? I need to run command from root rpi then.
> 
> 
> 
> You can't from the UI but you can if you SSH in as the pi user:
> 
> 
> 
> ```
> 
> sudo service homebridge stop
> 
> sudo -E -n npm install -g homebridge-config-ui-x@latest
> 
> ```

Thanks I will use it for sure in the next update. But for now I just opened the II website and it showed me "you updated the UI pending restart" may not be correct with exact wording but have me just restart option and after restart I am updated :) no idea what happened but I swear I tried update, reboot cycle at least 10+ times, always got the error I put in the first report. It seems like on the background it just did something and it is done. It is good but also a little scary that it is running without my knowledge. Any idea what would that be?

**Comment by jamieburchell** [comment]
I tried lots of times from the UI - it suddenly jumped to complete pending restart, but after restart it still showed as update required.

The UI runs the same update command when you ask it to update, so npm runs in the background. Except I think it can get interrupted if it's closed, but I'm not familiar with how exactly this works.

**Comment by mm98** [comment]
> I tried lots of times from the UI - it suddenly jumped to complete pending restart, but after restart it still showed as update required.
> 
> The UI runs the same update command when you ask it to update, so npm runs in the background. Except I think it can get interrupted if it's closed, but I'm not familiar with how exactly this works.

I can confirm this (on QNAP). Restarting the container after update keeps the current v4.41.4.

`[12/18/2021, 2:09:22 PM] Loaded plugin: homebridge-config-ui-x@4.41.4`
`[12/18/2021, 2:09:22 PM] Registering platform 'homebridge-config-ui-x.config'`

**Comment by pascals92** [comment]
> > I tried lots of times from the UI - it suddenly jumped to complete pending restart, but after restart it still showed as update required.
> > The UI runs the same update command when you ask it to update, so npm runs in the background. Except I think it can get interrupted if it's closed, but I'm not familiar with how exactly this works.
> 
> I can confirm this (on QNAP). Restarting the container after update keeps the current v4.41.4.
> 
> `[12/18/2021, 2:09:22 PM] Loaded plugin: homebridge-config-ui-x@4.41.4` `[12/18/2021, 2:09:22 PM] Registering platform 'homebridge-config-ui-x.config'`

same problem here .. runs on proxmox, is there a solution?

**Comment by FranciRoosters** [comment]
> > How do you update from UI, if HB service is stopped? I need to run command from root rpi then.
> 
> You can't from the UI but you can if you SSH in as the pi user:
> 
> ```
> sudo service homebridge stop
> sudo -E -n npm install -g homebridge-config-ui-x@latest
> sudo service homebridge start
> ```

Did doing this break your setup?

**Comment by jamieburchell** [comment]
> Did doing this break your setup?

No

**Comment by FranciRoosters** [comment]
> > Did doing this break your setup?
> 
> No

I've copied and pasted sudo service homebridge stop and now Homebridge won't restart. Ugh! Any ideas as to why and what I can do to solve this?

**Comment by maschbaer** [comment]
I tired to install it with the HB turned off
`sudo service homebridge stop
sudo -E -n npm install -g homebridge-config-ui-x@latest
sudo service homebridge start`

However, this gave the same error as when I try to do the update via the UI

`npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-25T19_06_43_193Z-debug.log`

regards,
Jan

**Comment by fettesb** [comment]
same error here

pi@raspberrypi:~ $ sudo -E -n npm install -g homebridge-config-ui-x@latest
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-26T16_39_37_299Z-debug-0.log

**Comment by Fraserhardy** [comment]
Same issue here. My homebridge on Raspberry pi was then unable to start. I couldn't get it working so thought i had broken it so did a fresh install of home bridge, all working fine until I tried updating to 4.41.5 again. It just hangs at the start screen: 
![image](https://user-images.githubusercontent.com/1138877/147674226-ca01f312-83ff-4bdc-81a5-9f3bdb46cae6.png)

**Comment by MrFly72** [comment]
Same here. Even tried it with "manual" approach mentioned above (HB stop, install, HB start).
But it gave me the same error
`sudo -E -n npm install -g homebridge-config-ui-x@latest
sudo service homebridge start
npm notice
npm notice New minor version of npm available! 8.1.0 -> 8.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0
npm notice Run npm install -g npm@8.3.0 to update!
npm notice
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/helmet: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-30T08_33_05_877Z-debug.log
`

**Comment by jamieburchell** [comment]
Looking at the error messages, the issues reported here appear to be different to the original issue reported (a sudden termination of the process during update).

You should probably open a new issue, providing the required information there.

**Comment by MrFly72** [comment]
It seems so. I updated NPM like said in the text and now it updated even with the GUI.

**Comment by mm98** [comment]
> @MrFly72 Looking at the error message, this looks to be a different issue. You should probably open a new issue, providing the required information there.
> 
> Those with the error message about renaming failing could try this first:
> 
> ```
> cd /usr/local/lib/node_modules
> sudo rm -R .homebridge-config-ui-x-3gtnOIj4
> ```

@jamieburchell Thanks! This solved the problem by me 🥳
