### ISSUE TITLE
error  on  HA0.72 homebridge2.6.1

### ISSUE THREAD

**Issue by jyz0501** [oznu/homebridge-config-ui-x#126]
/usr/bin/homebridge-config-ui-x -> /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js

> node-pty@0.7.6 install /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty
> node scripts/install.js

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by jyz0501** [comment]
python版本不对吗？？

**Comment by oznu** [comment]
Hi @jyz0501,

Installing or fixing your installation of python should fix this.
