### ISSUE TITLE
homebridge kills itself with SIGTERM when homebridge-config-ui-x is added to config.json on FreeBSD

### ISSUE THREAD

**Issue by RyuKojiro** [oznu/homebridge-config-ui-x#1264]
**Describe The Bug:**
On FreeBSD homebridge dies when the config UI plugin is enabled. Originally I encountered this will a much more complex config, but the problem started as soon as I added the config platform, but after trying on a fresh install of everything (including the OS), with a config that only adds the config platform, it still happens. So, I've included a trimmed down reproduction case.

**To Reproduce:**

1. Install FreeBSD (12.2-RELEASE in this case)
2. `sudo pkg install npm-node14 avahi-libdns`
3. `sudo npm install -g homebridge`
4. `sudo npm install --unsafe-perm -g homebridge-config-ui-x`

Add the example config platform blurb to your config's `"platforms"`:
```
		{
		  "platform": "config",
		  "name": "Config",
		  "port": 8080,
		  "sudo": false
		}
```

**Expected behavior:**
Homebridge stays running like it did before the config change, and the UI web server runs

**Logs:**

```
[12/31/2021, 2:46:20 PM] Loaded config.json with 0 accessories and 1 platforms.
[12/31/2021, 2:46:20 PM] Loaded 0 cached accessories from cachedAccessories.
[12/31/2021, 2:46:20 PM] ---
[12/31/2021, 2:46:20 PM] Loaded plugin: homebridge-config-ui-x@4.41.5
[12/31/2021, 2:46:20 PM] Registering platform 'homebridge-config-ui-x.config'
[12/31/2021, 2:46:20 PM] ---
[12/31/2021, 2:46:20 PM] Loading 1 platforms...
[12/31/2021, 2:46:20 PM] [Config] Initializing config platform...
[12/31/2021, 2:46:20 PM] [Config] Spawning homebridge-config-ui-x with PID 1443
Setup Payload:
X-HM://0023ISYWY3N7Y
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/31/2021, 2:46:21 PM] Homebridge v1.3.9 (HAP v0.9.8) (TestHomebridge) is running on port 58760.
[12/31/2021, 2:46:26 PM] Got SIGTERM, shutting down Homebridge...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "TestHomebridge"
    },
    
    "description": "Test Homebridge",

    "platforms": [
		{
		  "platform": "config",
		  "name": "Config",
		  "port": 8080,
		  "sudo": false
		}
    ]
}
```

**Environment:**

* **Node.js Version**: v14.17.0
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.3.8
* **Homebridge Config UI X Version**: 4.41.3
* **Operating System**: FreeBSD 12.2
* **Process Supervisor**: Running from a shell

**Comment by RyuKojiro** [comment]
I used dtrace to determine that the signal originated within the node process running homebridge:
```
  0  62823                 none:signal-send 
              kernel`sys_kill+0x194
              kernel`amd64_syscall+0x387
              kernel`0xffffffff8106785e

              libc.so.7`kill+0xa
              node`0x15f74db
              node`v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo)+0x210
              node`0x17487e9
              node`0x1747ed8
              node`0x1ee8c39
              node`0x1e81a22
              node`0x1e81a22
              node`0x1e7b959
              node`0x1e81a22
              node`0x1e7b959
              node`0x1e81a22
              node`0x1e81a22
              node`0x1e7f73a
              node`0x1e7f518
              node`0x180c59c
              node`v8::internal::Object v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>(int, v8::internal::Object*)+0xdd
              node`v8::Function::Call<v8::Value> v8::Function::Call(v8::Local<v8::Context>(int, v8::Value*)+0x1cc
              node`int node::Environment*::Object node::InternalMakeCallback(node::Environment*, v8::Local<node::Environment*::Object>(v8<node::Environment*::Function>(v8<node::Environment*::Value>*, node::async_context)+0x310
              node`int node::AsyncWrap::MakeCallback(v8::Local<node::AsyncWrap::MakeCallback::Function>(v8<node::AsyncWrap::MakeCallback::Value>*)+0xbf
```

**Comment by mganjoo** [comment]
I'm facing this issue too, with the minimal reproduction case mentioned above. Commenting here in case anyone happens to know of a solution.

EDIT:

This is the minimal reproduction case that _does_ work:

```
{
  "bridge": {
    "username": "CC:22:3D:E3:CE:30"
  },
  "platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    }
  ]
}
```

Removing the `bridge` block, or having a `bridge` block that doesn't have the `username` field, causes Homebridge to terminate with the SIGTERM error. Not sure what that username field does, as the logs don't produce ay other error message when it is removed and Homebridge shuts down.

Another user seems to have discovered that this "non-minimal" sample config (which also includes username) is necessary to prevent Homebridge from SIGTERMing: https://github.com/homebridge/homebridge-config-ui-x/issues/991#issuecomment-748370344
