### ISSUE TITLE
I can't reach the HomeBridge using its IP!

### ISSUE THREAD

**Issue by VCTGomes** [oznu/homebridge-config-ui-x#1265]
I'm using an PC as the server to run the HomeBridge and using the SSH to instal and manage the home bridge. I've install everything successfully, but now I can't open the web app!

My browser show IP refused to connect. I tried to use another browser, but I got the same problem.

I also can post the logs because when I tried the hb-service logs, the terminal returns ERROR: Log file does not exist at expected location: /var/lib/homebridge/homebridge.log.

So I was look for some solution and when I use the command sudo hb-service run --allow-root --stdout, I can access the HB web app, but if I close the terminal, I just STOPP!

**Comment by Staubgeborener** [comment]
Just try `sudo hb-service --allow-root restart`. I think your `stdout` could be the problem.
