### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by maschbaer** [oznu/homebridge-config-ui-x#1267]
I tired to update with the HB turned off
`sudo service homebridge stop sudo -E -n npm install -g homebridge-config-ui-x@latest sudo service homebridge start
`
However, this gave the same error as when I try to do the update via the UI

` npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! A complete log of this run can be found in:
npm ERR! /home/pi/.npm/_logs/2021-12-25T19_06_43_193Z-debug.log
`

Same error reported in some posts by other user here
[Link](https://github.com/oznu/homebridge-config-ui-x/issues/1256) 

regards,
Jan

**Comment by Stefan-83** [comment]
same error on one of my homebridges :-(

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/1243#issuecomment-979530200

**Comment by maschbaer** [comment]
Worked like a charm. Thanks
