### ISSUE TITLE
Battery Service Showing null

### ISSUE THREAD

**Issue by donavanbecker** [oznu/homebridge-config-ui-x#1269]
**Describe The Bug:**

Battery Percentage displays as null with new [Battery](https://developers.homebridge.io/#/service/Battery) Service since Battery Level is not required.

**To Reproduce:**

Add New [Battery](https://developers.homebridge.io/#/service/Battery) Service without only required Characteristic  of Status Low Battery and Battery percentage will display as null

**Expected behavior:**

If Battery Level is not provided, then hide percentage.

**Screenshots:**

<img width="528" alt="Screen Shot 2022-01-12 at 9 29 06 AM" src="https://user-images.githubusercontent.com/9875439/149170604-bbef79eb-a7e9-457c-a788-756a99c71c89.png">

**Environment:**

* **Node.js Version**: 16.13.2
* **NPM Version**: 8.3.0
* **Homebridge Version**: 1.4.0-beta.4
* **Homebridge Config UI X Version** :4.41.6-test.3
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by donavanbecker** [comment]
-

**Comment by donavanbecker** [comment]
-

**Comment by oznu** [comment]
Thanks

**Comment by donavanbecker** [comment]
@oznu Thanks!
