### ISSUE TITLE
Plugin ui support

### ISSUE THREAD

**Issue by marck1991** [oznu/homebridge-config-ui-x#127]
Hi oznu,
hi all,

at first I'd like to say a big thanks for the hard work.

Second I'd like to relate to https://github.com/normen/homebridge-platform-maxcube/issues/8 and ask whether it is planed to implement a plugin ui support.
So when config-x is installed another homebridge plugin could display some additional stuff there.

**Comment by oznu** [comment]
Hi @marck1991,

Plugins can define their own UI settings by publishing a `config.schema.json`.

See https://github.com/homebridge/Documentation/blob/master/Schema.md for details.
