### ISSUE TITLE
Create a "remember this browser" option for 2-factor authentication

### ISSUE THREAD

**Issue by rfiorentino1** [oznu/homebridge-config-ui-x#1271]
**Is your feature request related to a problem? Please describe:**
I love the fact that the UI provides 2-factor authentication, but because I log into it from both my phone and computer, I'm constantly having to pull up the code from my phone, when I'm loging in from my computer.
**Describe the solution you'd like:**
It would be awesome if there could be a "trust this browser" option or something similar, so you'd only have to authenticate once with that specific device. Or, adding an additional two-factor app/method for that device.

**Comment by oznu** [comment]
Setting the "session timeout" to be a really long number (86400000) under UI Settings > Advanced will achieve what you want.

**Comment by rfiorentino1** [comment]
Awesome, thank you. I’ll try it in the next few days and let you know how it goes

**Comment by rfiorentino1** [comment]
This works great. I think my initial thought was for it to still ask for username and password, but bypass the two factor authentication. But I actually don't mind it just remembering my complete login for certain machines. :-) Thank you

**Comment by rfiorentino1** [comment]
I've been using the session time-out method for a little while now, and while it works in short term, I'd still love to have a checkbox to "don't ask again on this browser" or something similar. When the time out expires, I have to go into my phone to retrieve the authentication code again just to log in on my computer.
Another option could be to add multiple/backup two FA methods, so I could add my computer as a trusted authentication generation device. Just some food for thought :)
