### ISSUE TITLE
Where is terminal in homebridge macOs

### ISSUE THREAD

**Issue by coralienyr** [oznu/homebridge-config-ui-x#1278]
**Describe Your Problem:**
I install homebridge and homebridge config ui x on my mac.
I ran "sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x" and then "sudo hb-service install"

Now, if I go to http://localhost:8581/ it's okay, I can log in but after I can't find the terminal. Where is it ?

**Environment:**

* **Node.js Version**:  16.13.2
* **NPM Version**: 8.1.2
* **Homebridge Version**: 1.4.0
* **Homebridge Config UI X Version**:
* **Operating System**: MacOS

**Comment by oznu** [comment]
The terminal is intentionally not enabled on macOS and Windows as these are typically multi-purpose machines and enabling a web based shell with user-level access would be an unacceptable security risk.

A terminal is provided on Linux as Homebridge is typically run "headless".

**Comment by coralienyr** [comment]
so how to install npm package on homebridge ?

**Comment by oznu** [comment]
You can use your regular Terminal application, or use the UI to find plugins and install them.
