### ISSUE TITLE
UI installed on alternate port doesn't correctly report status

### ISSUE THREAD

**Issue by robacarp** [oznu/homebridge-config-ui-x#1287]
**Describe The Bug:**, **To Reproduce:**

When I run `hb-service install --port=8080` and later run `hb-service status`, the status check doesn't read the configured port and instead checks the default port.

**Expected behavior:**

I expected the status command to read the port from the config file, rather than requiring me to pass it in again.

**Screenshots:**

![image](https://user-images.githubusercontent.com/208647/153653561-cb31e778-75c9-4d67-ad8e-78d4d2f1d5c1.png)

**Environment:**

* **Node.js Version**:  v16.14.0
* **Homebridge Config UI X Version**:
```
homebridge-config-ui-x> cat package.json 
{
  "name": "homebridge-config-ui-x",
  "displayName": "Homebridge UI",
  "version": "4.42.0",
```
* **Operating System**: macOS 
* **Process Supervisor**:  hb-service

**Comment by robacarp** [comment]
so uh, no hope eh

**Comment by oznu** [comment]
You can run:

```
hb-service status --port 8080
```

This command was only added for some internal status checks.
