### ISSUE TITLE
Possible to bring back login page?

### ISSUE THREAD

**Issue by gtrnz** [oznu/homebridge-config-ui-x#13]
The current version presents us with a login window which doesn't play nice with keychain auto fill in safari on iOS/macOS, possibly 1password and others for those that use them on other browsers/OS?
Where as the login page before played nice with autofill for credentials.
Whats the chance of having a login work like it did before in the last version?

**Comment by oznu** [comment]
Hi @gtrnz,

This is something I'm working towards. The front end is using Angular 5 so the old method didn't work very well. I'm planning to re-implement this using JWT authentication which I'm already using for the Websocket connections.

My plans are to allow users to specify what auth method they want to use once I implement this, letting them choose from:

* **Basic** - what we have now
* **Form** - what you want
* **None** - useful for those running behind a reverse proxy that provides the auth layer

**Comment by oznu** [comment]
Hi @gtrn,

The forms-based login is back and is the default option. 

If you're going to upgrade the plugin from inside the UI, please immediately restart Homebridge after doing so, then do a hard refresh (CTRL + F5 or CMD + SHIFT + R) of the UI. This will ensure everything keeps working smoothly.

For anyone else watching - if you want to change the auth method you can add it as an option in your `config.json`.

To turn back on Basic Authentication:

```json
"platform":[
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "auth": "basic"
    }
]
```

To turn off authentication:

```json
"platform":[
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "auth": false
    }
]
```

**Comment by gtrnz** [comment]
Just updated. Looks like by default it reverts to form style login like it used to be with out having an auth type defined in the config.
