### ISSUE TITLE
Homebridge 1.4.0 compatibility with iPad and iOS 10.3.3

### ISSUE THREAD

**Issue by Honosapiens** [oznu/homebridge-config-ui-x#1304]
I have 2 old iPads that would like to use them wall mounted to control HomeKit Devices.  And for some strange reason, HomeKit running on iPadOS 10.3.3, all Homebridge devices are not responding.  Homebridge and all its plugins are up to date.  Is there a plug-in or a setup I'm missing to make old iOS devices compatible with an up to date Homebridge?

**Comment by oznu** [comment]
This is not a UI issue... however, if your Homebridge setup is exposing devices that are to "new" for the iOS version, it won't work. Try separating the plugins into child bridges and see which ones work and which ones don't.

https://github.com/homebridge/homebridge/wiki/Child-Bridges

Further help is probably best gotten from Reddit / Discord.

**Comment by Honosapiens** [comment]
Hombridge is working with the newest iOS (15.4) and MacOS (12.3.1).  However on old devices with iOS 10.3.4 or older, Homebridge devices are listed, but all are shown as not responding.  Other devices that are HomeKit compatible work without any issue.
