### ISSUE TITLE
Memory widget should use "GiB" as the unit and not "GB"

### ISSUE THREAD

**Issue by seidnerj** [oznu/homebridge-config-ui-x#1306]
The memory widget displays memory figures in units of Gibibytes, e.g. it says "7.71 GB", but it should should say "7.1. GiB".

For example, on my RP4 there's a total of 8,282,619,904 bytes of memory, this is 8282619904/1024^3 = ~7.7.1 Gibibytes ("GiB"), which is equal to ~8.28 Gigabytes ("GB"). Since the widget displays the former figure, it should use "GiB" as the unit and not "GB".

**Comment by seidnerj** [comment]
This also applies to the Network widget (once merged) and potentially other places which display relevant figures.

**Comment by oznu** [comment]
I think I've had this discussion before, perhaps it was on discord. RAM is typically measured and sold in GB, despite GiB being more correct, the macOS Activity Monitor app does this.

**Comment by seidnerj** [comment]
The current historical notation used is confusing, since GB/MB is used for both 10 and 2 base. Software is slowly but surely is migrating to the new formal notation.

The question I guess is whether or not we should adhere to the new standard or perpetuate the former. I vote for the former but its a general decision to make for the entire project.

**Comment by seidnerj** [comment]
Bump
