### ISSUE TITLE
Make CORS configurable

### ISSUE THREAD

**Issue by codepoet80** [oznu/homebridge-config-ui-x#1307]
**Is your feature request related to a problem? Please describe:**
Alternate web UIs cannot use the API because CORS is only configured to trust a couple local origins by default.

**Describe the solution you'd like:**
in `src/main.ts` the `// setup cors` section (line 93 currently) has two hard-coded localhost origins. It would be great if this setting could be configured through the config.json to allow alternate clients -- such as [this one for retro devices](https://github.com/codepoet80/EnyoHomeControl).

**Describe alternatives you've considered:**
I have this working by setting up an apache2 reverse proxy where I can configure the CORS settings.

I have also made it work by modifying the running code at `/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js` line 82505 to `Set  origin: '*',`

However, both of these solutions are too complex for most users. A configuration option would be greatly appreciated!

**Comment by jwise-cesmii** [comment]
I do the same with Apache, but it would be nice to have this built-in/configurable.

**Comment by codepoet80** [comment]
I do the same with Apache, but it would be nice to have this built-in/configurable.

**Comment by codepoet80** [comment]
Any thoughts on giving the user control over CORS without having to hack at the source or setup a proxy?
