### ISSUE TITLE
UI config editor on iOS

### ISSUE THREAD

**Issue by PerthSteve** [oznu/homebridge-config-ui-x#131]
Hello,
I've just installed this as part of the docker homebridge installation, and it seems to be working so far. I've been trying to use the config editor within the UI and have been having a couple of issues.
1. When typing into the config.json window there is no ability to scroll, and if you keep adding lines the cursor disappears behind the keyboard. This makes it impossible to make changes this way.
2. After making the required changes (for example adding the accessory config) and tapping SAVE I keep getting a syntax error. I made the exact same changes manually using nano and the file has loaded without issues. 
3. There's no ability to paste text into the config edit window.

Thanks!
PerthSteve

**Comment by oznu** [comment]
The editor used is [Ace Editor](https://ace.c9.io/). I have no intentions of spending to much time making the editor mobile compatible as that's out-of-scope for this project.

https://github.com/ajaxorg/ace/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20mobile

The solution might be to just use a plain `<textarea>` on mobile devices?

**Comment by PerthSteve** [comment]
FYI the save issue seems to have corrected itself. 

Cheers

**Comment by oznu** [comment]
This will be resolved in 3.8.8
