### ISSUE TITLE
Misspelling on Bridge Settings dialog

### ISSUE THREAD

**Issue by shanemcw** [oznu/homebridge-config-ui-x#1315]
**Describe the bug:**

Misspelling on the "Bridge Settings" dialog.
"Each child bridge platform or accessory will need to be paired with HomeKit **sep<ins>e</ins>rately**."

**To reproduce:**

View the "Bridge Settings" dialog.

**Expected behavior:**

"Each child bridge platform or accessory will need to be paired with HomeKit **sep<ins>a</ins>rately**."

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js version**: 
* **NPM version**: 
* **Homebridge version**: 
* **Homebridge Config UI X version**:
homebridge-config-ui-x v4.42.0
* **Operating system**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
fixed in the next release, thanks.
