### ISSUE TITLE
easy way to install ssl

### ISSUE THREAD

**Issue by platini76** [oznu/homebridge-config-ui-x#1321]
hello, I need help please.
I start with this page:
https://snapcraft.io/install/certbot/raspbian

but I am at the end and I don't know hot to continue...
if this is good method... if not please can you drive me to a guide to install a simple auto renew cert for my homebridge?
thanks

**Comment by oznu** [comment]
This is beyond the scope of this project.

An SSL cert can be manually set in the config:

https://github.com/oznu/homebridge-config-ui-x/wiki/Manual-Configuration#enabling-ssl

Or use Nginx as a reverse proxy:

https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Nginx-and-SSL

Or if using the Homebridge Raspberry Pi Image:

https://github.com/homebridge/homebridge-raspbian-image/wiki/SSL-HTTPS-Access#lets-encrypt--certbot

**Comment by platini76** [comment]
I tried this... (I have raspbian 11)

but give this:

pi@homebridge:/var/lib/homebridge $ sudo apt-get install certbot python-certbot-nginxReading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python-certbot-nginx

if you cannot help please only say me where to post this help request.
THANKS VERY MUCH!!!!
