### ISSUE TITLE
Errror while updating

### ISSUE THREAD

**Issue by noppie** [oznu/homebridge-config-ui-x#1322]
During the updat of the plugin I get this error:

USER: pi
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-config-ui-x@latest

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-config-ui-x' -> '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-04-25T07_24_11_291Z-debug-0.log

**Comment by ukjimbow** [comment]
Getting the same issue here

![image](https://user-images.githubusercontent.com/2206204/165075212-88db0aa5-eb44-4a8b-a1f7-c3e4ed21d526.png)

End of log showing the issue:

`
<...SNIP...>
2169 timing reifyNode:node_modules/homebridge-config-ui-x Completed in 226602ms
2170 http fetch GET 200 https://registry.npmjs.org/rxjs/-/rxjs-7.5.5.tgz 213352ms (cache miss)
2171 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/rxjs Completed in 242497ms
2172 http fetch GET 200 https://registry.npmjs.org/core-js-pure/-/core-js-pure-3.22.2.tgz 219850ms (cache miss)
2173 timing reifyNode:node_modules/homebridge-config-ui-x/node_modules/core-js-pure Completed in 243348ms
2174 timing reify:unpack Completed in 243672ms
2175 timing reify:rollback:createSparse Completed in 39009ms
2176 timing reify:rollback:retireShallow Completed in 8ms
2177 timing command:install Completed in 360384ms
2178 verbose stack Error: process terminated
2178 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:194:39
2178 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
2178 verbose stack     at process.emit (node:events:402:35)
2179 verbose cwd /usr/local
2180 verbose Linux 5.10.63-v7+
2181 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-config-ui-x@latest"
2182 verbose node v16.13.1
2183 verbose npm  v8.3.0
2184 error process terminated
2185 error signal SIGTERM
2186 verbose exit 1
2187 timing npm Completed in 362982ms
2188 verbose unfinished npm timer reify 1650881961494
2189 verbose code 1
2190 error A complete log of this run can be found in:
2190 error     /home/pi/.npm/_logs/2022-04-25T10_19_18_909Z-debug-0.log`

**Comment by oznu** [comment]
@noppie:

```
sudo /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

@ukjimbow: not the same issue as @noppie, but I've only ever seen it do what you're seeing when the Pi / server is out of memory / resources. You can try at the command line using:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by ukjimbow** [comment]
> @ukjimbow: not the same issue as @noppie, but I've only ever seen it do what you're seeing when the Pi / server is out of memory / resources. You can try at the command line using:
> 
> ```
> sudo npm install -g --unsafe-perm homebridge-config-ui-x
> ```

@oznu that worked! Thank you! :)

**Comment by noppie** [comment]
Did it but get the message now  Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-config-ui-x'.

**Comment by noppie** [comment]
Tried it but get message:   Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-config-ui-x'.

**Comment by rknabe** [comment]
Had the same issue, and had to first remove the temp dire /usr/lib/node_modules/.homebridge-config-ui-x-?????, then did the install as mentioned above.

This is on an rpi 3 with plenty of ram and disk (only thing running). Built from the homebridge image a few months ago, and had upgrade the ui from the web interface, then started getting the failures mentioned above.

**Comment by noppie** [comment]
I don't see any temp directories in this directory:  /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO

**Comment by rknabe** [comment]
I had to delete .homebridge-config-ui-x-ni8KP3nO before reinstall

**Comment by nsomneeak** [comment]
For me the rename command in the installer was failing with a directory not empty error
`error ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-config-ui-x' -> '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'
`


I used mv to rename the folder and then ran the install again without issue

`sudo mv '/usr/lib/node_modules/homebridge-config-ui-x' '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'
sudo npm install -g --unsafe-perm homebridge-config-ui-x`

**Comment by noppie** [comment]
> For me the rename command in the installer was failing with a directory not empty error `error ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-config-ui-x' -> '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO' `
> 
> I used mv to rename the folder and then ran the install again without issue
> 
> `sudo mv '/usr/lib/node_modules/homebridge-config-ui-x' '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'`
> 
> `sudo npm install -g --unsafe-perm homebridge-config-ui-x`

That worked for me!   Thanks

**Comment by dieig** [comment]
I got this issue, I read the thread but I don't know how to fix it. Can someone help me please
<img width="795" alt="Schermata 2022-04-26 alle 22 28 04" src="https://user-images.githubusercontent.com/77574981/165389761-6098cae3-8a60-4223-a41e-cd43a03ab653.png">
?

**Comment by noppie** [comment]
Post form [nsomneeak](https://github.com/nsomneeak):

I used mv to rename the folder and then ran the install again without issue

sudo mv '/usr/lib/node_modules/homebridge-config-ui-x' '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'

sudo npm install -g --unsafe-perm homebridge-config-ui-x

**Comment by dieig** [comment]
I tried to do what you said and everything seemed work fine. Today I tried to restar Homebridge but now I cannot start it anymore.
<img width="1008" alt="Schermata 2022-04-28 alle 19 54 59" src="https://user-images.githubusercontent.com/77574981/165823352-d17b1b2e-4da6-4d89-847b-0aaa2b86a45e.png">

I connected via ssh and that's what I see but I don't really know what to do to fix it.

<img width="968" alt="Schermata 2022-04-28 alle 20 39 24" src="https://user-images.githubusercontent.com/77574981/165823523-bbb9c57d-924e-41a9-a7bf-452c8af845d7.png">

Can someone please help me?

thank you

**Comment by domre77** [comment]
I’ve having the exact same issue (on my Pi 3b). None of the above advice helps. 

When I try sudo mv '/usr/lib/node_modules/homebridge-config-ui-x' '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO' - it says no such file or directory.

**Comment by oznu** [comment]
```
sudo rm -rf /usr/lib/node_modules/.homebridge-config-ui-x*
sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x*
sudo npm install -g homebridge-config-ui-x
```
