### ISSUE TITLE
Install / Delete / Update plugins via REST API

### ISSUE THREAD

**Issue by CGKF** [oznu/homebridge-config-ui-x#1323]
Hi everyone,

I recently started using this plugin's REST API to automate some processes.
Is there currently any way to use the API to install / delete / update plugins? I couldn't find anything related to using npm commands in the swagger documentation.

Any help will be appreciated. Thanks.

**Comment by oznu** [comment]
These operations aren't exposed via HTTP API calls. They should only be called by the UI.
