### ISSUE TITLE
Cant update to latest Homebridge UI

### ISSUE THREAD

**Issue by dfizzo** [oznu/homebridge-config-ui-x#1327]
**Describe Your Problem:**
I am getting an error message when i try to update UI to 4.43.2 that says the following. Log detail follows below. Can you please advise how i can go about rectifying this issue? I have tried updating the UI multiple times now. Thanks so much!

SER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-config-ui-x@latest

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-config-ui-x' -> '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-04-30T16_58_46_786Z-debug-0.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Command failed. Please review log for details.

**Logs:**
_[0 - 1467 removed due to exceeding max characters]_
1467 error path /usr/lib/node_modules/homebridge-config-ui-x
1468 error dest /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO
1469 error errno -39
1470 error ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-config-ui-x' -> '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'
1471 verbose exit -39
1472 timing npm Completed in 26644ms
1473 verbose unfinished npm timer reify 1651337927525
1474 verbose unfinished npm timer reify:retireShallow 1651337953387
1475 verbose code -39
1476 error A complete log of this run can be found in:
1476 error     /home/homebridge/.npm/_logs/2022-04-30T16_58_46_786Z-debug-0.log

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v16.14.2
* **NPM Version**:  v.8.5.0
* **Homebridge Version**:  homebridge-config-ui-x v4.43.1
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian 
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/1322#issuecomment-1115976859

**Comment by dfizzo** [comment]
Thank you! This worked like a charm
________________________________
