### ISSUE TITLE
Child bridges don't support color status text

### ISSUE THREAD

**Issue by jvmahon** [oznu/homebridge-config-ui-x#1329]
### Analysis

I have some plugins that use "Chalk" to generate color text.
If the plugins are installed without using a child bridge, everything works fine and color text is rendered to the config-ui-x "Status" window. However, if the plugin is installed as a bridge, I no longer get colored text.

### Expected Behavior

The use of child bridges should not strip out color from logged text.

### Steps To Reproduce

Install a plugin using color and observe its output.
Switch to using the plugin via a bridge and observe.

### Logs

```markdown
None.
```

### Configuration

```json
Homebridge 1.41. and latest config.ui-x used.
```

### Environment

- OS:  Windows and Raspberry
- Software:
- Node: 18.0.0
- npm:

### Process Supervisor

hb-service

### Additional Context

None.

**Comment by oznu** [comment]
Child bridges emit their own colour logs using "chalk" - this seems to be working fine?

Windows 10 you probably won't get colour, I noticed this when testing a while back, only the primary process seems to get colour. As native Windows installs make up a fraction of a percent of the user base, it's not worth the effort trying to fix it.
