### ISSUE TITLE
Cannot update to 4.43.2 Verbose stack error

### ISSUE THREAD

**Issue by salmundo11** [oznu/homebridge-config-ui-x#1332]
**Describe The Bug:**
Unable to update the home bridge-config-ui-x plugin to version 4.43.2

**To Reproduce:**
Attempt to update via the GUI

**Expected behavior:**
Expect plugin to update

**Logs:**
```
2174 timing reify:unpack Completed in 454720ms
2175 timing reify:rollback:createSparse Completed in 62839ms
2176 timing reify:rollback:retireShallow Completed in 58ms
2177 timing command:install Completed in 656777ms
2178 verbose stack Error: process terminated
2178 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:198:39
2178 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
2178 verbose stack     at process.emit (node:events:539:35)
2179 verbose cwd /usr/local
2180 verbose Linux 5.15.32+
2181 verbose node v16.15.0
2182 verbose npm  v8.8.0
2183 error process terminated
2184 error signal SIGTERM
2185 verbose exit 1
2186 timing npm Completed in 659383ms
2187 verbose unfinished npm timer reify 1651538953336
2188 verbose code 1
```

**Homebridge Config:**

```
{
    "bridge": {
        "name": "Homebridge 9267",
        "username": "DDDD",
        "port": 51820,
        "pin": "822-28-642"
    },
    "accessories": [
        {
            "accessory": "PurpleAir",
            "name": "PurpleAir",
            "purpleID": "DD",
            "updateFreq": 1800,
            "adjust": "EPA",
            "includePM10": true
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "orange",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "units": "us",
            "interval": 90,
            "stations": [
                {
                    "nameNow": "Out Back",
                    "service": "weatherunderground",
                    "key": "DDDD",
                    "stationId": "DDDD",
                    "language": "en",
                    "compatibility": "home",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Air Pressure",
                        "Dew Point"
                    ]
                },
                {
                    "service": "openweathermap",
                    "language": "en",
                    "compatibility": "home",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus"
        }
    ],
    "disabledPlugins": []
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v16.15.0
* **NPM Version**: 8.8.0
* **Homebridge Version**: 1.4.1
* **Homebridge Config UI X Version**: 4.43.1
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by skra72** [comment]
I have exactly the same problem and it happened on the last two updates of homebridge-config-ui-x. Updating other plugins work from the UI.

However, when running the update via SSH as homebridge user everything works.

**Comment by oznu** [comment]
I've only seen these issues on low powered devices - the system just runs out of resources when trying to do an update.

`npm` is very cpu heavy and pretty much wants to check and rebuild all the dependencies every update, even if none have changed.

I've been working on an alternative, that is currently going out to new users following the Ubuntu / Raspbian wiki guides:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

These setups use `pnpm` instead of `npm` which reduced UI update times on a basic Raspberry Pi Zero W from 5-10 minutes, down to about 45 seconds.

**Comment by salmundo11** [comment]
uninstall homebridge via apt-get remove homebridge, then install via the new method? And this would preserve the existing configuration?

**Comment by oznu** [comment]
Assuming your setup uses the default `/var/lib/homebridge` storage path:

* [Do a backup](https://github.com/homebridge/homebridge/wiki/Backup-and-Restore) to be safe
* Keep the existing service running (the new installer will use this to get info about existing plugins to restore)
* Then just follow the instructions using the new method
* Everything should start back up as normal

Let me know how you go.

**Comment by salmundo11** [comment]
The rebuild went perfectly, thanks! We'll see how updates go.

**Comment by skra72** [comment]
Switch to apt worked for me too! Thanks.

Does this mean to not do any homebridge or homebridge-ui updates in place anymore and to wait for apt to deliver a new version?

**Comment by oznu** [comment]
You can keep using the UI to do updates, they should work more reliably now.

**Comment by salmundo11** [comment]
SO, uninstall homebridge via apt-get remove homebridge, then install via
the new method? And this would preserve the existing configuration?
