### ISSUE TITLE
Upgrade stuck on reify:find-my-way

### ISSUE THREAD

**Issue by tooh** [oznu/homebridge-config-ui-x#1337]
**Describe The Bug:**

Upgrade is stuck on reify-find-my-way

**To Reproduce:**

Upgrade to latest.

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/429386/168337371-a7a3568f-0194-49fc-ad5a-ff5957b7599d.jpeg)
**Environment:**

Raspberry Pi

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by tooh** [comment]
In the meantime installed 4.44.1.

Upgrade succesful.

**Comment by oznu** [comment]
npm is being slow.

See https://github.com/oznu/homebridge-config-ui-x/issues/1332#issuecomment-1115973930
