### ISSUE TITLE
Command failed: vcgencmd get_throttled

### ISSUE THREAD

**Issue by TinyMito** [oznu/homebridge-config-ui-x#1338]
**Describe The Bug:**

After updating to homebridge-config-ui-x v4.44.1 - I am seeing error after rebooting the homebridge.

**To Reproduce:**

Everytime after a reboot.

**Expected behavior:**

**Logs:**

[2022-05-13, 4:18:26 p.m.] [Homebridge UI] Could not check vcgencmd get_throttled: Command failed: vcgencmd get_throttled
VCHI initialization failed

[2022-05-13, 4:33:00 p.m.] [Homebridge UI] Could not check vcgencmd get_throttled: Command failed: vcgencmd get_throttled
VCHI initialization failed

**Homebridge Config:**

{
    "bridge": {
        "name": "Homebridge 23CA",
        "username": "",
        "port": 51811,
        "pin": "",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Nest",
            "refreshToken": "",
            "fanDurationMinutes": 60,
            "platform": "Nest"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "switchModels": [
                "HS210"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "Plex Webhooks Platform",
            "sensors": [
                {
                    "name": "Plex",
                    "filters": [
                        [
                            {
                                "path": "Player.title",
                                "value": "SHIELD Android TV"
                            }
                        ]
                    ]
                }
            ],
            "verbose": false,
            "platform": "PlexWebhooks"
        },
        {
            "name": "Lifx Plugin",
            "duration": 0,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "debug": false,
            "autoDiscover": true,
            "bulbs": [
                {
                    "name": "LIFX Beam",
                    "address": "192.168.1.248"
                }
            ],
            "platform": "LifxPlugin"
        },
        {
            "platform": "Ikea Trådfri Gateway",
            "name": "Ikea Trådfri Gateway",
            "host": "192.168.1.104",
            "securityCode": "",
            "expose": [
                "lightbulbs",
                "outlets",
                "blinds"
            ]
        }
    ]
}

**Screenshots:**

![Mito 2022-05-13 at 16 33 25@2x](https://user-images.githubusercontent.com/75095713/168385704-041f489a-6ed8-4ff5-9265-9d1ccbb8d4b6.png)

**Environment:**

* **Node.js Version**: 16.15.0 
* **NPM Version**: 18 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**: 4.44.1 
* **Operating System**: Raspbian 

* **Process Supervisor**: none

**Comment by oznu** [comment]
This isn't hurting anything, I'll suppress it next release.

What version if Raspbian are you running?

**Comment by TinyMito** [comment]
```
pi@pi:~ $ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by oznu** [comment]
I wouldn't have expected the "raspi-config" tool to be installed on Debian - I was using the presence of this tool to to see if it was a raspberry pi

**Comment by TinyMito** [comment]
The official one Lite 64bit

![Mito 2022-05-13 at 22 37 46@2x](https://user-images.githubusercontent.com/75095713/168407849-86047685-bf5d-4d53-819d-556fdba92155.png)
![Mito 2022-05-13 at 22 38 25@2x](https://user-images.githubusercontent.com/75095713/168407850-f6ef3b92-3dbd-40ce-839c-62ace9da766d.png)
![Mito 2022-05-13 at 22 39 15@2x](https://user-images.githubusercontent.com/75095713/168407851-f70126c3-4a49-4361-9254-5c9e61c49e57.png)

**Comment by oznu** [comment]
Adding the "homebridge" user to the "video" group might fix this.

The Debian repo is suppose to add homebridge user to this group on Raspbian, but obviously the 64 bit image identifies differently.

https://github.com/homebridge/homebridge-apt-pkg/blob/master/deb/debian/postinst#L56

**Comment by TinyMito** [comment]
I just ran the following command:
`sudo usermod -a -G video homebridge`

And then re-update back to the latest. The error seems to be gone now. :)

![Mito 2022-05-13 at 22 48 26@2x](https://user-images.githubusercontent.com/75095713/168408082-7b6f7112-1365-47fb-a12d-c6b35fc80f50.png)

I'll let you know if it occurs again in the future and thank you for the troubleshooting!

**Comment by oznu** [comment]
Thanks, it's highlighted an issue with 64bit I need to address, so that's good to know!

**Comment by oznu** [comment]
Fixed for the debian pkg build in https://github.com/homebridge/homebridge-apt-pkg/commit/2773f572d8d19f9c51d9c524217c8f3d9f29b62a

**Comment by joshuaseltzer** [comment]
@oznu just saw this in the logs myself. Should I add the homebridge user to the video group or is that no longer necessary when you release the next update?

**Comment by oznu** [comment]
The next ui update is just going to hide the error, the next apt pkg release will add the homebridge user to the video group.

Adding the user to the video group is the correct solution here, and will ensure the "under voltage detection" feature works.

**Comment by joshuaseltzer** [comment]
@oznu Ah okay, thanks for the explanation. Sounds like I can just wait for the updates to come out to get the fixes. Thanks again!
