### ISSUE TITLE
Dulpicate Accessories

### ISSUE THREAD

**Issue by malmentm** [oznu/homebridge-config-ui-x#134]
Some of my accessories shows up as duplicate. One with support and one not supported? Any ideas why? This is the same temperature and humidity sensor.

http://forumbilder.se/H7ESN/forum

**Comment by oznu** [comment]
Hi @malmentm,

Accessories can expose multiple "services". So while you may have one physical device, it may show up as multiple endpoint in homekit. The UI reflects this.

**Comment by malmentm** [comment]
@oznu Ok, can you add an option to hide all devices with status "not supported" so it does not show in the gui? As of now i can see 2 of the sam instance, one tempsensor with the correct valua and anopther instance with the status not supported.
