### ISSUE TITLE
No Restart or Shutdown Server Commands

### ISSUE THREAD

**Issue by thehauntedmattress** [oznu/homebridge-config-ui-x#1348]
### Current Situation

Had an issue where I had to resintall homebridge and homebridge-config-ui-x on top of an existing installation on a Raspberry Pi Zero W.  After the install, the options to restart and shutdown the sever are missing from the upper right UI dropdown menu.  I was wondering what I can do to get these back.  Thanks.
![Screen Shot 2022-05-24 at 3 40 43 PM](https://user-images.githubusercontent.com/7905480/170118971-aa779c65-c9fb-4b08-85a9-271236d600bb.png)
!

### Config

```json
"platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
```

### Homebridge UI Version

4.45.0

### Homebridge Version

1.4.1

### Node.js Version

16.15.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi Zero W

**Comment by oznu** [comment]
Run `sudo systemctl edit homebridge`

Add this, replacing "pi" if necessary with a user account that has password-less sudo access.

```
[Service]
User=pi
Environment="UIX_CAN_SHUTDOWN_RESTART_HOST=1"
```

Then run `sudo systemctl restart homebridge`.

To under any changes run `sudo systemctl revert homebridge` followed by the restart command.

**Comment by thehauntedmattress** [comment]
Do I need to get rid of all the # that are in front of the lines?  Every time I try to save the buffer I get "/etc/systemd/system/homebridge.service.d/override.conf" canceled: temporary file is empty."

**Comment by oznu** [comment]
That file should only contain the text above.

**Comment by thehauntedmattress** [comment]
Alright I just made that file with only that text above and the issue still persists.
