### ISSUE TITLE
Config Backup Issues

### ISSUE THREAD

**Issue by mpearon** [oznu/homebridge-config-ui-x#135]
**Version Information**
Homebridge: `0.4.44`
Config-UI-X:  `3.8.5`
NodeJS:         `10.6.0`
Browsers:       Edge, Chrome

**Issue Description**
When I click the _BACKUP_ button on `./config`, nothing happens.
I used Debugging tools to expose the hyperlink, and it consists of the entire JSON with HTML escapes. 

`
<a class="btn btn-elegant waves-effect" href="data:text/json;charset=UTF-8,%7B%0A%20%20%20%20%22bridge%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22Homebridge%22%2C%0A%20%20%20%20%20%20%20%20%22username%22%3A%20%22CC%3A22%3A3D%3AE3%3ACE%3A30%22%2C%0A%20%20%20%20%20%20%20%20%22port%22%3A%2051826%2C%0A%20%20%20%20%20%20%20%20%22pin%22%3A%20%220~REDACTED-PIN~%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22platforms%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22platform%22%3A%20%22config%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22Config%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22port%22%3A%208080%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22log%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22method%22%3A%20%22systemd%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22service%22%3A%20%22homebridge%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22restart%22%3A%20%22systemctl%20restart%20homebridge.service%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22platform%22%3A%20%22Server%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22Homebridge%20Server%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22port%22%3A%208765%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22log%22%3A%20%22systemd%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22restart%22%3A%20%22systemctl%20restart%20homebridge%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22platform%22%3A%20%22Wink2%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22~REDACTED-NAME~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22username%22%3A%20%22~REDACTED-EMAIL~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22password%22%3A%20%22~REDACTED-PASSWORD~%24%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22client_id%22%3A%20%22~REDACTED-ID~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22client_secret%22%3A%20%22~REDACTED-SECRET~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22direct_access%22%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22hide_groups%22%3A%20%5B%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22hide_ids%22%3A%20%5B%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22fan_ids%22%~REDACTED~%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22a025b7aa-846c-4af5-8b6c-c27823490a66%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22platform%22%3A%20%22Alexa%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22Alexa%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22username%22%3A%20%22~REDACTED-USERNAME~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22password%22%3A%20%22~REDACTED-PASSWORD~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pin%22%3A%20%22~REDACTED-PIN~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22refresh%22%3A%2015%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22platform%22%3A%20%22People%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22ignoreReEnterExitSeconds%22%3A%205%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22people%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22~REDACTED-NAME~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22target%22%3A%20%22~REDACTED-IP~101%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22~REDACTED-NAME~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22target%22%3A%20%22~REDACTED-IP~102%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%2C%0A%20%20%20%20%22accessories%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22accessory%22%3A%20%22NetworkDevice%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22SRV1%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22mac%22~REDACTED-MAC~%20%20%20%20%20%20%20%20%20%20%20%20%22ip%22%3A%20%22~REDACTED-IP~11%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pingInterval%22%3A%2060%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownCommand%22%3A%20%22bash%20%2Fvar%2Fhomebridge%2Fscripts%2Fshutdown.sh%20~REDACTED-IP~11%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownGraceTime%22%3A%2060%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22accessory%22%3A%20%22NetworkDevice%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22SRV2%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22mac%22%~REDACTED-MAC~%20%20%20%20%20%20%20%20%20%20%20%20%22ip%22%3A%20%22~REDACTED-IP~12%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pingInterval%22%3A%2060%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownCommand%22%3A%20%22bash%20%2Fvar%2Fhomebridge%2Fscripts%2Fshutdown.sh%20~REDACTED-IP~12%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownGraceTime%22%3A%2060%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22accessory%22%3A%20%22NetworkDevice%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22Hyper%20Core%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22mac%22%3A%20%22~REDACTED-MAC~%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22ip%22%3A%20%22~REDACTED-IP~13%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pingInterval%22%3A%2060%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownCommand%22%3A%20%22bash%20%2Fvar%2Fhomebridge%2Fscripts%2Fshutdown.sh%20~REDACTED-IP~13%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownGraceTime%22%3A%2060%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22accessory%22%3A%20%22NetworkDevice%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22SRV3%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22mac%22%~REDACTED-MAC~%20%20%20%20%20%20%20%20%20%20%20%20%22ip%22%3A%20%22~REDACTED-IP~21%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pingInterval%22%3A%2060%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownCommand%22%3A%20%22bash%20%2Fvar%2Fhomebridge%2Fscripts%2Fshutdown.sh%20~REDACTED-IP~21%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownGraceTime%22%3A%2060%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22accessory%22%3A%20%22NetworkDevice%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22Desktop%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22mac%22%~READACTED-MAC%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22ip%22%3A%20%22~REDACTED-IP~31%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22pingInterval%22%3A%205%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownCommand%22%3A%20%22bash%20%2Fvar%2Fhomebridge%2Fscripts%2Fshutdown.sh%20~REDACTED-IP~31%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22shutdownGraceTime%22%3A%2090%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22accessory%22%3A%20%22Broadband%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22name%22%3A%20%22~REDACTED-NAME~%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D" download="config.json">Backup</a>
`

**Comment by mpearon** [comment]
Is it possible that this is due to special characters in the JSON?

**Comment by oznu** [comment]
@mpearon,

Can you provide your `config.json`?

I am unable to replicate this on my end.

**Comment by mpearon** [comment]
Absolutely.  I appreciate your assistance!

I've redacted sensitive information, but have left the special characters and a way to indicate the form.  The characters are all still in their original positions.  Se attached.
`L` = upper-case letter
`l` = lower-case letter
`0` = number

[config.json.txt](https://github.com/oznu/homebridge-config-ui-x/files/2188697/config.json.txt)

**Comment by oznu** [comment]
Should be resolved in 3.8.6 - it now just downloads the file normally.
