### ISSUE TITLE
Revive cached/existing accessories after disabling/re-enabling a plugin

### ISSUE THREAD

**Issue by rfiorentino1** [oznu/homebridge-config-ui-x#1351]
### Describe The Bug

Hi. I'm currently trying to troubleshoot a faulty plugin, that Is causing a coast of cascading issues throughout my Homebridge, suddenly. I feel like the best way to do this is to disable plugins one at a time, and see if the issues are resolved. However, I'm terrified to do this, because it seems like if you disable and re-enable a plugin, it's no different than uninstalling it, other then the fact that the plugin still is part of your plugin list. But when it's re-enabled, everything shows up as brand new accessories, with no association to previous automation, scenes, etc. Is there any way to fix this, and restore accessories from disabled plugins to their last known state? Is this some kind of apple HomeKit limitation? I tried to search for this as an existing issue, but couldn't find anything for this specific behavior. Not sure if this is even possible, or of a better place to file it, so figured I'd start here :)

### Homebridge UI Version

4.46.0

### Homebridge Version

1.4.1

### Node.js Version

16.15.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

**Comment by oznu** [comment]
Under "Homebridge Settings" you can find the `Keep accessories of uninstalled plugins` option - which should achieve what you want to do. Though using "Child Bridges" would be a better much more robust solution.
