### ISSUE TITLE
Shut down menu item -> restart

### ISSUE THREAD

**Issue by permaMonk** [oznu/homebridge-config-ui-x#1353]
### Describe The Bug

If click on "Shutdown Server" the system restarts. I use this in a german translation. If I want a restart I usually use the menu item "Server neustarten". Anything switched in translation?

Log says: Need my password.

### Logs
[Homebridge UI] Shutting down linux server with command: "sudo -n shutdown -h now"
[Homebridge UI] Command failed: sudo -n shutdown -h now
sudo: a password is required

_No response_

### Homebridge UI Version

4.46.0

### Homebridge Version

1.4.1 

### Node.js Version

16.5.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by oznu** [comment]
Your homebridge service user does not have "passwordless sudo" access to the shutdown command - adjust the sudo settings for this user and it will work.
