### ISSUE TITLE
Cannot Update homebridge-config-ui-x 4.46.0 

### ISSUE THREAD

**Issue by Stetocasa** [oznu/homebridge-config-ui-x#1358]
### Describe The Bug

I cannot complete the update of version 4.46.0 

### Logs

```text
CMD: sudo -E -n npm install -g homebridge-config-ui-x@latest

npm ERR! process terminated
npm ERR! signal SIGTERM

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-06-08T09_50_20_019Z-debug-0.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Command failed. Please review log for details.
```

### Homebridge UI Version

v4.43.1

### Homebridge Version

v8.12.1

### Node.js Version

16.15.1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

**Comment by ddong3000** [comment]
Me too.

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/1332#issuecomment-1115973930
