### ISSUE TITLE
FIDO "Passkey" support for log-in

### ISSUE THREAD

**Issue by thomaschow19** [oznu/homebridge-config-ui-x#1359]
### Feature Description

With the upcoming FIDO "Passkey" support in Android, iOS, macOS and Windows, it would be great if homebridge UI can support this authentication method.

**Comment by oznu** [comment]
I looked into this a while ago, it seems to require a HTTPS context which is not something most users would have as it requires additional configuration.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
