### ISSUE TITLE
Update failed 

### ISSUE THREAD

**Issue by Moerte** [oznu/homebridge-config-ui-x#1362]
### Current Situation

Hello,

I'm trying to update the homebridge-config-ui-x but it is returning always an error.
The error is as follows:

USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-config-ui-x@latest

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-06-15T11_26_30_573Z-debug.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Command failed. Please review log for details.

Best regards

### Homebridge UI Version

v4.41.3

### Homebridge Version

v1.4.1

### Node.js Version

7.17.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by oznu** [comment]
```
sudo rm -rf /usr/local/lib/node_modules/.homebridge-*
sudo rm -rf /usr/lib/node_modules/.homebridge-*
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```
