### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by dieig** [oznu/homebridge-config-ui-x#1363]
### Current Situation

I tried to upload homebridge config ux but the plugin disappear after update

### Logs

```text
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.7 kB]                               
Get:3 https://repo.homebridge.io stable InRelease [3,242 B]                                                   
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:5 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [279 kB]
Get:6 https://repo.homebridge.io stable/main armhf Packages [570 B]                                                                                               
Ign:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages                                                                                       
Ign:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages                                                                                       
Err:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
  Connection timed out [IP: 93.93.128.193 80]
Fetched 322 kB in 1min 11s (4,551 B/s)
Reading package lists... Done
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/bullseye/main/binary-armhf/Packages  Connection timed out [IP: 93.93.128.193 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  homebridge
1 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Need to get 54.3 MB of archives.
After this operation, 808 kB disk space will be freed.
Get:1 https://repo.homebridge.io stable/main armhf homebridge armhf 1.0.24 [54.3 MB]
Fetched 54.3 MB in 38s (1,435 kB/s)                                                                                                                               
apt-listchanges: Reading changelogs...
(Reading database ... 89884 files and directories currently installed.)
Preparing to unpack .../homebridge_1.0.24_armhf.deb ...
Running pre-upgrade steps...
Stopping Homebridge service...


Terminal disconnected. Is the server running?
```

### Homebridge UI Version

4.43

### Homebridge Version

latest

### Node.js Version

Cannot check

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi Zero W

**Comment by jnubz** [comment]
Mine won't finish the update. Fails before the restart. Stuck on reify:@types/jsonweb.

**Comment by jnubz** [comment]
Update seemed to finish. It deleted my config.json file completely, and homebridge is damaged beyond use. I'm trying to figure out how to reinstall it.

**Comment by oznu** [comment]
How did you trigger this update?

**Comment by vvdheuvel** [comment]
Update killed my Homebridge. It was damaged beyond use. I had to reinstall it.

**Comment by dieig** [comment]
Same, update killed the whole system. I tried to update both via the plugin and via terminal but same issue

**Comment by jnubz** [comment]
> How did you trigger this update?

Same way I always do. Updated through the HomeBridge UI web portal.

Fortunately I had a backup of my config.json so I fully reinstalled homebridge, added the plugins back in, and I'm back up and running. But there was definitely something wrong with the update this time.

**Comment by xJARiD** [comment]
Downgrading to the following [Docker image](https://hub.docker.com/layers/homebridge/oznu/homebridge/2022-06-02-ubuntu/images/sha256-0a048dc30b2e870a301f63edef679f63ea5147bbcc776499a840ed37f24c1dfc?context=explore) has resolved my issues

**Comment by vvdheuvel** [comment]
> > How did you trigger this update?
> 
> Same way I always do. Updated through the HomeBridge UI web portal.
> 
> Fortunately I had a backup of my config.json so I fully reinstalled homebridge, added the plugins back in, and I'm back up and running. But there was definitely something wrong with the update this time.

Same here!

**Comment by b2un0** [comment]
same for me (aarch64 docker)

```plain
[6/16/2022, 4:52:11 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: Node.js global modules rebuild required. See log errors above.
    at main (/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.47.0/node_modules/homebridge-config-ui-x/dist/main.js:77970:19)
    at Object.1808 (/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.47.0/node_modules/homebridge-config-ui-x/dist/main.js:78014:1)
    at __webpack_require__ (/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.47.0/node_modules/homebridge-config-ui-x/dist/main.js:82382:42)
    at /homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.47.0/node_modules/homebridge-config-ui-x/dist/main.js:82415:1
    at /homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.47.0/node_modules/homebridge-config-ui-x/dist/main.js:82514:3
    at Object.<anonymous> (/homebridge/node_modules/.pnpm/homebridge-config-ui-x@4.47.0/node_modules/homebridge-config-ui-x/dist/main.js:82519:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)


```

**Comment by vvdheuvel** [comment]
Now running 4.4.8.1 fixed it for me

**Comment by mpuff** [comment]
I can't update to v4.48.1, I use no-avahi-arm32v6 docker image

**Comment by ultrathew** [comment]
Still can't update either, this is the error message I get:

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

**Comment by oznu** [comment]
@ultrathew

Remove the offending folder:

```
sudo /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
```

You can then try and update normally, or run this command:

```
curl -fsSL https://raw.githubusercontent.com/oznu/homebridge-config-ui-x/master/upgrade-install.sh | sudo sh -s -- "4.49.0" "$(npm -g prefix)"
```

**Comment by ultrathew** [comment]
@oznu 

Thanks! That did the trick.
