### ISSUE TITLE
login Wallpaper missing since homebridge-config-ui-x v4.47.0 

### ISSUE THREAD

**Issue by Harry423** [oznu/homebridge-config-ui-x#1365]
### Describe The Bug

Hallo,

since my update to homebridge-config-ui-x v4.47.0  the standard login wallpaper is missing?

### Homebridge UI Version

homebridge-config-ui-x v4.47.0 

### Homebridge Version

1.4.1

### Node.js Version

v16.15.1 

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.47.0
