### ISSUE TITLE
node-js update failed

### ISSUE THREAD

**Issue by Lorccan** [oznu/homebridge-config-ui-x#1366]
### Describe The Bug

Attempting to update from Node.js v16.15.0 to v16.15.1:

ssh'd to homebridge server
executed `sudo hb-service update-node`
response:
```
ℹ Updating Node.js from v16.15.0 to v16.15.1...
ℹ Target: /usr/local
✔ Download complete.
✔ Cleaned up npm at at /usr/local/lib/node_modules/npm
✔ Installed Node.js v16.15.1
ℹ Restarting Homebridge Service...
✔ Homebridge Restarted
```

When homebridge server comes back up, homebridge web ui (config-ui-x) does not start.
Running: `sudo.  hb-service logs` gets error" `/usr/bin/env: ‘node’: No such file or directory`

I have restarted from backup and been able to reproduce.

### Homebridge UI Version

v4.47.0

### Homebridge Version

v1.4.1 (HAP v0.10.2)

### Node.js Version

v16.15.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by oznu** [comment]
> Official Homebridge Raspberry Pi Image

Use `sudo hb-config` to "Update Node.js" this should re-install it for you.
