### ISSUE TITLE
Homebridge-config-ui-x Update Fail (Error: ENOTEMPTY

### ISSUE THREAD

**Issue by Denss02** [oznu/homebridge-config-ui-x#1367]
### Describe The Bug

I can't update the plugin. I've tried to re-install the plugin, restart the service, updated node and npm, ... but with no success. 

Notable Changes of the plugin:

Auth: Login wallpaper is now a solid colour matching the users current theme, custom wallpaper images are still used if configured
System: If the UI detects it's own dependencies are missing or corrupt, it will trigger a task to fix them (on certain systems only, update required)
**System: Stale temporary npm directories that prevent the UI and other plugins from updating (```npm ERR! code ENOTEMPTY```) will be removed when doing a full service restart for users running on Linux with [hb-service]**(https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command)

Update Error:
```
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-config-ui-x@latest

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-config-ui-x' -> '/usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-06-18T12_16_58_708Z-debug-0.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Command failed. Please review log for details.
```
[2022-06-18T12_16_58_708Z-debug-0.log](https://github.com/oznu/homebridge-config-ui-x/files/8933541/2022-06-18T12_16_58_708Z-debug-0.log)

### Homebridge UI Version

v4.43.2

### Homebridge Version

v1.4.1

### Node.js Version

v16.15.1

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by oznu** [comment]
> System: Stale temporary npm directories that prevent the UI and other plugins from updating (npm ERR! code ENOTEMPTY) will be removed when doing a full service restart for users running on Linux with [hb-service]

Only after you manage to update 😄 

```
rm -rf /usr/lib/node_modules/.homebridge-config-ui-x-ni8KP3nO
```

**Comment by Denss02** [comment]
I have now another problem 😬

<img width="1412" alt="Bildschirmfoto 2022-06-18 um 17 33 42" src="https://user-images.githubusercontent.com/64380771/174445634-a6b2ab94-db24-489c-81c4-c17265a260cf.png">

**Comment by Denss02** [comment]
is it because there is no homebridge-config-ui-x folder in the directory /usr/lib/node_modules?

**Comment by oznu** [comment]
Forgot the re-install step:

```
# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by Denss02** [comment]
```
sudo npm install -g --unsafe-perm homebridge-config-ui-x
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 344 packages, and audited 345 packages in 11m

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
After installation, the web interface still does not work.

**Comment by oznu** [comment]
If you're still having this issue, run this to get back up and running:

```
curl -fsSL https://raw.githubusercontent.com/oznu/homebridge-config-ui-x/master/upgrade-install.sh | sudo sh -s -- "4.49.0" "$(npm -g prefix)"
```

```
sudo hb-service uninstall
```

```
sudo hb-service install --user=homebridge
```
