### ISSUE TITLE
Please help me solve the problem

### ISSUE THREAD

**Issue by Damianod27** [oznu/homebridge-config-ui-x#1368]
### Current Situation

Hello. I need help. I have been struggling with the problem for several days without success.

For the last two years I have been using Homebridge with homebridge-config-ui-x on my Raspebrry Pi 4.
Unfortunately it broke. Due to the lack of Raspebrry Pi computers on the market, I temporarily purchased an Orange Pi.

When I used Homebridge with homebridge-config-ui-x on Raspebrry Pi 4 when I made some changes to config.json or installed a new plugin I did a restart using the button available on the main desktop. After this process, all changes were saved.
For example: I was able to disconnect Raspebrry from the power supply and after restarting the whole configuration was up to date.

I have installed Homebridge with homebridge-config-ui-x on Debian Buster and Armbian Buster on my Orange Pi computer and I have a problem with it. When I make some changes to the config.json file or install a plug-in and use the button on the main desktop to restart the change work, but when I turn off the Orange Pi from the power supply, the homebridge-config-ui-x configuration returns to its original state. I added homebridge to root or sudo groups. I also gave homebridge full access to directories but nothing helps. Memorizing the settings only works when I log in to SSH Terminal and do a full restart of Sudo Reboot.

It's nice if there was a function in homebridge-config-ui-x that allows you to customize the restart command of the button on the main desktop according to your needs.

Can someone help me make the button function on the main desktop work like on the Raspebrry Pi 4?
Thanks for any help.

### Homebridge UI Version

4.47.0

### Homebridge Version

1.41

### Node.js Version

16.15.1

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [x] Using hb-service?

### Raspberry Pi Model

Other (specify in description)

**Comment by Damianod27** [comment]
@oznu Can anyone help me with my problem and give some tips?

**Comment by jasonlboggs** [comment]
This sounds like you might have a bad SD card.  Try writing a random file somewhere on disk, maybe to your home directory.  Shut down the device and disconnect power.  After powering back up, is the file still there?  If not, then you may have a bad SD card.  I have no ideas otherwise.  Good luck!

**Comment by Damianod27** [comment]
@jasonlboggs Thank you for your advice, but it's not the Micro SD card's fault.  Mostly I use Sandisk Extreme Pro or SAMSUNG Pro Plus from European distribution.  Not Chinese fakes.  I suppose it's the fault of the permissions.  On a Raspberry Pi 4 with the same Micro SD cards, I had no problems.  When using the command in the SSH terminal - sudo reboot, all changes are remembered. Regards
