### ISSUE TITLE
Cant access login screen.

### ISSUE THREAD

**Issue by QuiveryNut** [oznu/homebridge-config-ui-x#137]
Hello, I've installed this plugin using an image with a startup script to get homebridge running with a camera added, so homebridge starts automagically. I ran the install command for unsafe-perm and it seems to have installed correctly (although i don't know how to check this without a gui) and i edited the config file, but i get "Unable to connect" on Firefox and "Connection Refused" on Chrome. What should I be doing next?

**Comment by oznu** [comment]
What do the homebridge logs show?
