### ISSUE TITLE
NPM Version System Information missing

### ISSUE THREAD

**Issue by cl4udiu5** [oznu/homebridge-config-ui-x#1370]
### Describe The Bug

NPM Version is missing where system information is shown
Installed NPM version 8.12.2

<img width="1787" alt="Bildschirmfoto 2022-06-25 um 00 28 32" src="https://user-images.githubusercontent.com/74124378/175712967-9e716c45-650e-4a95-a457-8deeb619284d.png">

### Homebridge UI Version

4.46.0

### Homebridge Version

1.5.0

### Node.js Version

16.15.1

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 1 B

**Comment by oznu** [comment]
This was intentionally removed several versions ago.
