### ISSUE TITLE
Read the JSON Config from a file saved on disk directly

### ISSUE THREAD

**Issue by uswong** [oznu/homebridge-config-ui-x#1376]
#### The issue
I am using CMD4 plugin and it requires a 10 lines JSON Config for each accessory and I have about 100 accessories, ie I need ~1,000 lines JSON Config.  

#### What I would like to see
It would be wonderful if the plugin can read the JSON Config from a file saved on disk directly.  It is much easier to create and edit the JSON Config file on a Terminal rather than within Homebridge plugin JSON Config editor.

#### Workaround
I still can create and edit he JSON Config file on a Terminal then copy and paste into Homebridge plugin JSON Config editor, but it is a **pain!**

**Comment by oznu** [comment]
You'd probably need to raise this request with the plugin developer, as it's not something the Homebridge UI can handle.
