### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by williamccc** [oznu/homebridge-config-ui-x#138]
How to reset password?

**Comment by Dedcad** [comment]
How I can delete auth.json, I don't understand.

**Comment by oznu** [comment]
`rm -rf auth.json`

**Comment by Dedcad** [comment]
Nothing changed.
My problem is that after changing the admin password and creating a new user, I turned on the Basic Form authorization. Everything worked.
After I turned on the form authorization method, after that none of my passwords is accepted.

Maybe you can change the authorization method by SSH?
The plugin was used in the assembly of SprutHub

**Comment by mcquaas** [comment]
Same here... deleting auth.json didn't do it.

**Comment by MTapester** [comment]
Once you delete the file and restart. Use admin/admin to get in

**Comment by adamrzanek** [comment]
Hi i have similar problem... how can i delete this file on the mac?

**Comment by cjpatoilo** [comment]
To solve the issue:

1. Delete the `~/.homebridge/auth.json`, for example, `rm -rf ~/.homebridge/auth.json`
1. Reinstall the server, for example, `sudo hb-service uninstall && sudo hb-service install`

ps: maybe works for you `sudo hb-service rebuild --all`. I don't try this command but seems to make sense for me.

**Comment by lludo** [comment]
After deleting `auth.json` -> `sudo systemctl restart homebridge`
