### ISSUE TITLE
Add an end-user customizable nickname to each plugin

### ISSUE THREAD

**Issue by dcompane** [oznu/homebridge-config-ui-x#1381]
### Feature Description

When looking at plugins, they all are homebridge-DS, with sometimes non-intuitive letters following.

we cannot ask the developers to change thir plug-in names to make it easier for end users, but the app may allow for nicknames that allow for more intuitive understanding and management of the increasingly long plugins lists.

ideally, the plugins list would be sorted either by nickname and/or real name.

**Comment by oznu** [comment]
> we cannot ask the developers to change thir plug-in names to make it easier for end users

Plugin developers can set a "nice" display name:

https://github.com/oznu/homebridge-config-ui-x/blob/master/package.json#L3
