### ISSUE TITLE
Child bridge current mode reset after HB restart

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#1383]
### Describe The Bug

After set the Child Bridge to stop and restart HB the Child Bridge state is reverted to running.

### Homebridge UI Version

4.49.0

### Homebridge Version

1.5.0

### Node.js Version

16.15.1

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

**Comment by grzegorz914** [comment]
Oh, you are right.

**Comment by oznu** [comment]
It might be confusing with them serving similar functions. The "stop" functionality is only available when running with `hb-service` though, so I need to keep the "disabled" there for other users.
