### ISSUE TITLE
Thanks for

### ISSUE THREAD

**Issue by r2ixuz** [oznu/homebridge-config-ui-x#1384]
### Current Situation

all these wonderful test release emails I receive from this project... ;-)

### Homebridge UI Version

latest

### Homebridge Version

latest

### Node.js Version

latest

### Operating System

Other (specify in description)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

**Comment by oznu** [comment]
![image](https://user-images.githubusercontent.com/3979615/178148797-38e14365-995f-473f-ae44-02c06fff090a.png)
