### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Serpanok** [oznu/homebridge-config-ui-x#139]
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-config-ui-x

> (node:954) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
> npm ERR! Error: Method Not Allowed
> npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
> npm ERR!     at /usr/share/npm/lib/cache/add-named.js:120:12
> npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
> npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>
> 
> npm ERR! System Linux 4.14.52-v7+
> npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-config-ui-x"
> npm ERR! cwd /home/pi
> npm ERR! node -v v8.11.1
> npm ERR! npm -v 1.4.21
> npm ERR! code E405
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/pi/npm-debug.log
> npm ERR! not ok code 0

help me plz.

**Comment by oznu** [comment]
Hi @Serpanok,

```
npm ERR! npm -v 1.4.21
```

You're version of `npm` looks very out of date. Try upgrading:

```
npm install -g npm
```

**Comment by Serpanok** [comment]
Hi @oznu,

thank you, everything worked!
