### ISSUE TITLE
Please add cpu temperature again 

### ISSUE THREAD

**Issue by EjvindHald** [oznu/homebridge-config-ui-x#1392]
### Feature Description

In the latest version, the very useful cpu temperature was not shown anymore. Only cpu percentage load is now shown.

Please add the temperature again or make it a configuration option in the UI.

Thanks!

**Comment by Staubgeborener** [comment]
I tried the latest version 1.5.0 and also the 1.5.1-beta.0 - both got the cpu temperature feature. I can't confirm this issue.

**Comment by EjvindHald** [comment]
Version 1.5.0 refers to the Homebridge server itself.

The temperature shown in the UI comes from the Homebridge UX plugin 😉

I am on vacation now, so I am not able to share a screen shot without the temperature.

**Comment by Staubgeborener** [comment]
@EjvindHald Yep, i know, and like i said i am using the latest homebridge-config-ui-x version 4.50.0 without any issues and with the cpu temperature feature (see second screenshot).

**Comment by EjvindHald** [comment]
Are you also running it as a Docker container like I do?

**Comment by Staubgeborener** [comment]
Yes. I run the latest docker image with `Ubuntu Focal Fossa (20.04.4 LTS)` on a manjaro system.

```shell
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./volumes/homebridge:/homebridge
```

**Comment by EjvindHald** [comment]
I am also running Docker in an Ubunto environment, so I do not know why it is not showing up.

I can try to reinstall with latest image when I come home from vacation. Currently, it is only updated via UI.

**Comment by EjvindHald** [comment]
This is quite strange. I have 2 instances running - one with temperature and another without (!)

I have deleted the original image and recreated both containers several times with version "latest". However, it seems like the latest ux-ui patch is not reflected in the latest Docker image.
