### ISSUE TITLE
Restarting command won't work…

### ISSUE THREAD

**Issue by albi** [oznu/homebridge-config-ui-x#14]
Trying to…

launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist

… fails from Config UI X. From the Terminal it will work as expected.

**Comment by oznu** [comment]
If you're using a launch agent config like this one:

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS#starting-homebridge-automatically-with-launchd

That contains this config:

```
    <key>KeepAlive</key>
        <true/>
```

You should just be able to remove the restart command from your `config.json` and let launchd handle restarting homebridge when the process ends.

**Comment by albi** [comment]
so simple! thank you!
