### ISSUE TITLE
UI plugin load failed.

### ISSUE THREAD

**Issue by RamyaGandreti** [oznu/homebridge-config-ui-x#140]
i installed moodle in my laptop and installed coderunner plugin in that...I am getting this error

please help me

**Comment by oznu** [comment]
@RamyaGandreti - please provide the homebridge logs and your `config.json` and I'll see what's going on.

**Comment by RamyaGandreti** [comment]
I can't find config.json file in coderunner and even in moodle i can't find config.json

**Comment by RamyaGandreti** [comment]
and please help me to put the jail server in ubuntu for moodle

**Comment by oznu** [comment]
I'm not sure what this project has to do with moodle or coderunner?

**Comment by RamyaGandreti** [comment]
moodle by having coderunner plugin

**Comment by oznu** [comment]
How does that link in with Homebridge?

**Comment by RamyaGandreti** [comment]
dont know about homebridge

**Comment by oznu** [comment]
This is a homebridge project, I think you've raised this issue on the wrong project.
