### ISSUE TITLE
The log on the main page is not displayed anything

### ISSUE THREAD

**Issue by bo-2221** [oznu/homebridge-config-ui-x#1401]
### Describe The Bug

Hello, as of recently, no log is displayed on my start page, but the tile is there. If I go to view log in the top right corner, something is shown to me. Is this a known problem, or is it just me?

### Homebridge UI Version

4.50.0

### Homebridge Version

1.5.0

### Node.js Version

16.16.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/1400
