### ISSUE TITLE
Could not create a backup of the config,json file

### ISSUE THREAD

**Issue by Hunt3rle** [oznu/homebridge-config-ui-x#1403]
### Current Situation

Heyho Oznu,

when i made a change in the config.json i got an error message:
could not create a backup of the config.json file to /var/lib/homebridge/backups/config-backups 
EXDEV: cross-device link not permitted, rename '/var/lib/homebridge/config.json' -> '/var/lib/homebridge/backups/config-backups/config.json-1659942429640'

Is there any chance to fix that failure?

Thx a lot for your help!

### Homebridge UI Version

4.50

### Homebridge Version

1.5

### Node.js Version

16.6

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by oznu** [comment]
Have you done something to `/var/lib/homebridge/backups/*` to make it be on a different mount?

Show the output of:

```
ls -la /var/lib/homebridge
ls -la /var/lib/homebridge/backups
```

**Comment by Hunt3rle** [comment]
rwxrwxrwx 12 homebridge users   4096 Aug  8 02:56 .
drwxr-xr-x 31 root       root    4096 Aug  8 08:04 ..
drwxrwxrwx  2 homebridge users   4096 Aug  8 08:18 accessories
-rw-rw-rw-  1 homebridge users    359 Aug  8 02:13 auth.json
drwxrwxrwx  9 homebridge users   4096 Aug  8 03:03 backups
drwxrwxrwx  2 homebridge users   4096 Aug  8 02:13 bwp91_cache
-rwxrwxrwx  1 homebridge users     87 Aug  8 02:13 .camera.ui.secrets
-rw-rw-rw-  1 homebridge users  21080 Aug  8 09:07 config.json
drwxrwxrwx  3 homebridge users   4096 Aug  8 02:13 db
drwxrwxrwx  2 homebridge users   4096 Aug  8 02:13 fritzbox
-rw-rw-rw-  1 homebridge users  16792 Aug  8 08:32 homebridge-hue.json.gz
-rw-rw-rw-  1 homebridge users 566488 Aug  8 09:31 homebridge.log
-rw-rw-rw-  1 homebridge users    237 Aug  8 02:13 laundrify-official.json
drwxrwxrwx 18 homebridge users   4096 Aug  8 02:43 node_modules
drwxrwxrwx  3 homebridge users   4096 Aug  8 02:13 .node-persist
-rwxrwxrwx  1 homebridge users    136 Jul 16 13:28 .npmrc
-rw-rw-rw-  1 homebridge users    591 Aug  8 02:42 package.json
drwxrwxrwx  2 homebridge users   4096 Aug  8 02:13 persist
drwxrwxrwx  3 homebridge users   4096 Aug  8 02:13 plugin-persist
-rwxrwxrwx  1 homebridge users   1595 Aug  8 09:20 .uix-dashboard.json
-rwxrwxrwx  1 homebridge users     81 Aug  8 02:13 .uix-secrets
drwxrwxrwx  2 homebridge users   4096 Aug  8 02:13 .webosTv

And
drwxrwxrwx  9 homebridge users 4096 Aug  8 03:03 .
drwxrwxrwx 12 homebridge users 4096 Aug  8 02:56 ..
-rwxrwxrwx  1 homebridge users 1837 Aug  8 00:15 .bash_history
drwxrwxrwx  2 homebridge users 4096 Aug  8 01:07 config-backups
-rwxrwxrwx  1 homebridge users  171 Aug  7 23:45 .dropbox_uploader
drwxrwxrwx  3 homebridge users 4096 Aug  7 23:27 .gnupg
drwxrwxrwx  2 homebridge users 4096 Aug  8 05:25 instance-backups
drwxrwxrwx  3 homebridge users 4096 Aug  8 00:15 .local
drwxrwxrwx  2 homebridge users 4096 Aug  8 03:03 @Recycle
drwxrwxrwx  2 homebridge users 4096 Aug  7 23:24 .@upload_cache
drwxrwxrwx  3 homebridge users 4096 Aug  8 00:15 .vnc

I tested yesterday to save logs via dropbox uploader but i canceled it later.
How can i set these to the correct folder again.

**Comment by oznu** [comment]
Not sure, you can try deleting `/var/lib/homebridge/backups` and restarting the service.

**Comment by Hunt3rle** [comment]
Ok .. after a reboot my homebridge is totally dead.
Homebridge UI not runnig.  Config-ui-x is not comming up anymore.
I think i have to do a reinstall. :/

**Comment by Hunt3rle** [comment]
Node Version 12.22.12 <- but when i try to update via hb-config it told me that 16.6 is installed.  Weird.

**Comment by Hunt3rle** [comment]
Just uninstalled all via hb-config and made a restore with backup. Hope the most will work again.
