### ISSUE TITLE
Under-voltage report

### ISSUE THREAD

**Issue by JanLp** [oznu/homebridge-config-ui-x#1414]
### Describe The Bug

This is a ridiculous feature! I use the original power supply and I boot from the sd, nothing else is connected ... yes a Conbee2. Otherwise nothing else.
<img width="473" alt="Skærmbillede 2022-10-06 kl  17 49 44" src="https://user-images.githubusercontent.com/55313117/194360575-b0edc56e-5d1a-4092-8095-8567ac4f13b9.png">

### Logs

```text
Nothing to show
```

### Config

```json
... Relative standard
```

### Homebridge UI Version

4.50.1

### Homebridge Version

1.5.0

### Node.js Version

16.17.1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by JanLp** [comment]
I can ignore the error...but it irritates my eyes.

**Comment by oznu** [comment]
This is just showing what the Raspberry Pi is reporting. If you had a screen plugged in you'd see a ⚡on the Raspbian Desktop too.

Undervoltage can lead to SD card corruption, especially during CPU intensive tasks like updating plugins.
