### ISSUE TITLE
running update-node on 32-bit system with 64-bit kernel enabled corrupts system

### ISSUE THREAD

**Issue by seidnerj** [oznu/homebridge-config-ui-x#1417]
### Describe The Bug

If one is running a 32-bit Raspberry Pi OS with a 64-bit kernel enabled (via the arm_64bit=1 flag in /boot/config.txt), running hb-service update-node results in installing a 64-bit of node which  corrupts the system making it unusable. I assume this happens because "uname -m" returns aarch64 when running with a 64-bit kernel.

A strange sideeffect of this, at least on my configuration, is that SSH takes forever to log-in, a few minutes. Once logged in, running commands etc. works just fine.

I solved this by downloading the node binaries directly from node's website and overwriting the copies found at /usr/local.

### Homebridge UI Version

v4.50.1

### Homebridge Version

v1.5.0

### Node.js Version

v16.17.1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by yjeanrenaud** [comment]
very odd. I recently migrated to a x64 kernel, too and have no issues on updates.

**Comment by seidnerj** [comment]
And have you run update-note after that and had an updated version actually installed? 

After running the update, the node executable I had installed was for aarch64 (confirmed via the "file" command).

**Comment by yjeanrenaud** [comment]
I had the update ran beforehands. I will ry again

**Comment by seidnerj** [comment]
Then that's the difference, if you run it now, there will be nothing to update so you will experience this issue.
