### ISSUE TITLE
package.json does not contain the keyword 'homebridge-plugin'.

### ISSUE THREAD

**Issue by yjeanrenaud** [oznu/homebridge-config-ui-x#1418]
### Describe The Bug

shows up in log.
everything seems to run, though.

### Logs

```text
[12/10/2022, 11:34:01] Plugin /usr/lib/node_modules/homebridge-config-ui package.json does not contain the keyword 'homebridge-plugin'.
```

### Homebridge UI Version

v4.50.1

### Homebridge Version

v1.5.0

### Node.js Version

v16.17.1

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3

**Comment by oznu** [comment]
That is a different package. Just delete it.

This is `homebridge-config-ui-x` not `homebridge-config-ui`.

**Comment by yjeanrenaud** [comment]
ah sorry!
