### ISSUE TITLE
UI in general and "loading logs using native method..." hangs

### ISSUE THREAD

**Issue by MiOrt** [oznu/homebridge-config-ui-x#1422]
### Describe The Bug

Homebridge running on Synology DS916+ (DSM 7.1.1-42962 Update 1) in Docker, latest Version (1.5.1), UI Ver. 4.50.1, has been running for al long time without issues on all older versions. Last login into UI weeks ago.

Wanted to log into HB UI yesterday (being on v1.5.0), took extremely long to get into the system, very slow UI loading. Although HB is running fine and working, the "looking for update"-wheel is constantly spinning, no content on tabs "configuration" and "devices". Tab "plugins" populates correctly. Coming from any tab and clicking "status" results in an empty page with only the purple header showing up: page only loads correct by pressing reload in browser. The protocol is not working at all, "loading logs using native method..." hangs.

I already downloaded the latest image in docker and reset the container, same result. After trying to reload the page again and again only one time the "looking for update"-wheel stopped and displayed info about newer version 1.5.1. I clicked it right away, update-popup appeared without content, took a long time and then v1.5.1 shows up as installed version. Still with the bug described above. Since then no change.

![Screenshot 27 10 2022 um 09 02 14 AM](https://user-images.githubusercontent.com/31467468/198216500-ba52ae15-b9d1-48e6-af96-07d72011faae.png)

When clicking the devices tab it is empty as described above. Sometimes after a few seconds the page suddenly shows "standard room" with the "drag here" icon. After another 30-60 seconds or so, suddenly all devices appear.
![Screenshot 27 10 2022 um 09 17 18 AM](https://user-images.githubusercontent.com/31467468/198217005-50ffb7c4-fb04-4402-9a8a-21361c1040fd.png)

Empty config-tab not being populated even staying open a long time in browser:
![Screenshot 27 10 2022 um 09 23 11 AM](https://user-images.githubusercontent.com/31467468/198217878-9ab6e0a8-4c4a-4960-878e-0cfaff4b42a3.png)

### Homebridge UI Version

4.50.1

### Homebridge Version

1.5.1

### Node.js Version

16.18.0

### Operating System

Synology DSM

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

**Comment by michaelherger** [comment]
Same behaviour here, with a very similar configuration: HB in Docker on DSM 7.1. It took me all the time to come to this repo, look at some bugs and PRs etc. before the web UI became updated again. Several minutes. I previously gave up, as I usually don't expect things to start working again after minutes of waiting.

What I saw yesterday was that the main page loaded ok. But some of the additional files (CSS, JS) were in a hanging state.  Maybe that only was an artifact of the actual problematic call. I'll try to get a list of all open requests next time.

**Comment by MiOrt** [comment]
Short update since I experimented a little more, at first I only tried to access my HB as usual only on my Mac Mini...

With all browsers on MacOS Monterey 12.6: Page starts loading (little blue progress bar) and stops at about 20%
Safari on a freshly updated MacBook (MacOS Ventura 13.0): Page loads as expected
Safari on iPad latest iPadOS:Page loads as expected

So I actually have no idea why the UI does not load anymore on a Monterey Mac, because I changed nothing except the Synology Update. Maybe it broke somewhen I didn't notice - usually I don't access the HB UI that much if everything works as expected.

**Comment by MiOrt** [comment]
Just figured out the same problem occurs on other docker-containers as well. All UI can be reached by mobile devices like iPad, iPhone etc but not from my my (no matter which browser). Just ran into that issue trying out scrypted, so it seems not to be a Homebridge (UI) problem?
