### ISSUE TITLE
Disable LOG

### ISSUE THREAD

**Issue by NorbertM21** [oznu/homebridge-config-ui-x#1424]
### Feature Description

Please, let us disable all those obsolete LOG-entrys:

_pam_unix(sudo:session): session opened for user root by (uid=0)
    root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 14169
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root_

**Comment by JurgenLB** [comment]
maybe just a filter on the log would be a great help. so you can check te log for a single plugin.
I believe there are cases that you need to know the user/uid info
