### ISSUE TITLE
config-ui installed and running in homebridge but can't access gui

### ISSUE THREAD

**Issue by davidkerr82** [oznu/homebridge-config-ui-x#143]
![image](https://user-images.githubusercontent.com/41842026/43360901-5d8dd9aa-92b9-11e8-9a57-2e58a2443057.png)

The plugin seems to have installed correctly in homebridge and I have successfully added the platform details to my config.json. I cannot access the gui on chrome by going to localhost:8080 . I am getting the following message:
![image](https://user-images.githubusercontent.com/41842026/43360916-ab1e398a-92b9-11e8-83ab-e8db304a5324.png)

What am I doing wrong!!??

**Comment by davidkerr82** [comment]
Hi, Homebridge is on the same computer as Chrome.  I've attached a full copy and pasted log right through to showing the port that Homebridge is running on.

[homebridge log.txt](https://github.com/oznu/homebridge-config-ui-x/files/2238670/homebridge.log.txt)

**Comment by oznu** [comment]
The logs don't show the UI starting at all. Can you post your full config.json?

**Comment by oznu** [comment]
You have placed the config block in the wrong spot.

What you have:

```json
  "platforms": [
    {
      "platform": "Nest",
      "clientId": "xxxxx",
      "clientSecret": "xxxxxx",
      "token": "xxxxx"
    },
    {
      "platform": "homebridge-plex-sensors.Plex",
      "sensors": [
        {
          "name": "Plex Playing",
          "players": [
            "Living Room Apple TV"
          ]
        },
        {
          "platform": "config",
          "name": "Config",
          "port": 8080,
          "sudo": true
        }
      ]
    }
  ]
```

What you should have:

```json
  "platforms": [
    {
      "platform": "Nest",
      "clientId": "xxxxx",
      "clientSecret": "xxxxxx",
      "token": "xxxxx"
    },
    {
      "platform": "homebridge-plex-sensors.Plex",
      "sensors": [
        {
          "name": "Plex Playing",
          "players": [
            "Living Room Apple TV"
          ]
        }
      ]
    },
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": true
    }
  ]
```

**Comment by davidkerr82** [comment]
Thanks a million, all fixed and running!!

**Comment by erokoder** [comment]
> Are you running homebridge on the same computer as chrome?
> 
> Can you show the rest of the homebridge logs? It should output that's its running on port XXXX once it's all up and running.

Can possible that I go to 192.168.2.50:8080 (192.168.2.50 rasapberry pi with homebridge) becouse chrome is not to raspberry pi than on my own computer 192.168.2.51?
