### ISSUE TITLE
config.json backup yields 1 line with "/var/homebridge/config.json" (app v 3.8.7)

### ISSUE THREAD

**Issue by SteveW25561** [oznu/homebridge-config-ui-x#144]
Every backup I make of config.json using the UI yields a 27 byte file that only has this line in it:

`/var/homebridge/config.json`

NOTHING else.  I can see the whole json file in the Config tab.  When I manually cut & paste this into a json file, it is 3 KB in size.

Using  homebridge-config-ui-x v3.8.7 on a Pi, saving to a Mac.

**Comment by oznu** [comment]
I can replicate this. I'll fix it soon.

**Comment by oznu** [comment]
Thanks for reporting this @SteveW25561.

Fixed in 3.8.8.
