### ISSUE TITLE
No "shut down" and "Restart" options.

### ISSUE THREAD

**Issue by mafyata** [oznu/homebridge-config-ui-x#1443]
### Current Situation

Hi. I changed my old Raspberry pi zero w with Raspberry pi 4B. I installed raspbian and homebridge. I made backup/restore and everythink work like on my old raspberry.
I have one problem. There is no "shut down" and "Restart" options in config-ui-x. I think that there was this option on my old raspberry.
![IMG_3274](https://user-images.githubusercontent.com/48009267/209474551-caf33ece-1900-4d3a-8ca0-d75dec48d4e0.PNG)

### Homebridge UI Version

v4.50.2

### Homebridge Version

v1.6.0

### Node.js Version

v18.12.1

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by JurgenLB** [comment]
on the right there are 3 buttons. "log", "restart", "options"
'shut-down' is for a server not needed in the webpage, it is possible true the command line.
![image](https://user-images.githubusercontent.com/77586573/211221274-f7b5185e-5cc4-4f05-8549-b726efba20e6.png)

kind regards.

**Comment by mafyata** [comment]
I use Raspberry pi 4. How can I add "restart server" and "shut down server" in ... (3 dot) menu?
