### ISSUE TITLE
Issue with restore (not 4.50.2 Uploading issue)

### ISSUE THREAD

**Issue by almonde** [oznu/homebridge-config-ui-x#1463]
### Current Situation

I have Homebridge running on a Synology in Docker, I want to retire that NAS, so I setup Homebridge using the VM image for Windows / Hyper-V. It runs fine, however when I tried to restore I get the following error on the Hyper-V VM Homebridge:

`Error: Cannot overwrite non-directory '/var/lib/homebridge' with directory '/tmp/homebridge-backup-FUOpZM/storage'`

Any ideas how to resolve this?

Synology is running Homebridge 1.6 with UI 4.50.2, node.js 16.16.0.  Windows VM is latest VM image with Homebridge 1.60, downgraded Config UI to 4.50.0 due to stuck on uploading issue and node.js 18.13.0 (also reported here)

### Homebridge UI Version

4.50.0

### Homebridge Version

1.60

### Node.js Version

18.13.0

### Operating System

Windows 10

### Environment Info

- [ ] Using Docker?
- [X] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by seidnerj** [comment]
I have the same issue trying to restore to an installation on a Raspberry Pi, it is simply stuck on "uploading".

**Comment by almonde** [comment]
Wiped out Windows, installed Mint bare metal and installed Homebridge on the bare metal linux install. All working now.
