### ISSUE TITLE
homebridge backup not uploading to server

### ISSUE THREAD

**Issue by nulltooth** [oznu/homebridge-config-ui-x#1465]
### Current Situation

Hi 
I have a home bridge server that is running on truenas through docker and as the server is changed and reconfigured often i quite often backup my file and restore from the backup however this time after i did an update the server and home bridge the homebridge was reset and now when i select a file to restore from it just spins and spins and spins. where before when i restored from a backup it was instant but now it never uploads the file. i have checked the integrity of the file by temporarily running it on a synology nas where it doesn't run in docker but wherever i run homebridge in docker it cannot restore from a backup. i have tried on truenas, Linux mint and Ubuntu and non of them can seem to accept a backup

many thanks 
alex

### Homebridge UI Version

1.60

### Homebridge Version

1.60

### Node.js Version

18.13.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by Staubgeborener** [comment]
I can confirm this issue, and it seems to be a fairly known one:
https://github.com/oznu/homebridge-config-ui-x/issues/1463
https://github.com/oznu/homebridge-config-ui-x/issues/1457

But @oznu is missing for quite a while.

**Comment by nulltooth** [comment]
Has anyone been able to fix the issue or is it a wait until the developer gets back kind of fix

**Comment by shanemcw** [comment]
Workaround worked for me:

1. "Install Alternate Version" from the wrench icon.
2. Choose an earlier version some ways back before this bug. 
3. Restart.
4. Restore backup.
5. Re-install latest Homebridge UI version.
6. Share here what previous version worked for you.

**Comment by shanemcw** [comment]
I was able to restore a backup with version 4.46.0—if you are attempting, try one newer and let us know!

**Comment by Staubgeborener** [comment]
Issue seems to be in [this](https://github.com/oznu/homebridge-config-ui-x/commit/ecbe9e426446528afc6325e37e0471a333f7362c) or [this](https://github.com/oznu/homebridge-config-ui-x/commit/5422c317d88ddbc12f02bb651d59cb512f058c82#diff-7ae005b637f26d452a603faf7ca58283e466942e38736966555b33f0d5e7534d) commit, i guess.
