### ISSUE TITLE
[homebridge-config-ui-x] Invalid token sent by admin: jwt expired

### ISSUE THREAD

**Issue by ipa64** [oznu/homebridge-config-ui-x#147]
Hi,

In the log I get token and webSocket errors, about every 3-10 seconds
[homebridge-config-ui-x] Invalid token sent by admin: jwt expired
[homebridge-config-ui-x] Unauthorised WebSocket Connection Closed

Yesterday I have updated the UI to v3.8.8,  I do not know if it's related or if it's another plugin

Thanks for advice

**Comment by oznu** [comment]
Do you have a tab open somewhere with an expired session?

**Comment by ipa64** [comment]
Oups maybe!!!
but because I have tried many things to understand why, I had the bad idea to uninstall the package to tried a clean install.
But now I get this error when I try to install the package:
Failed to install package error = [263]
