### ISSUE TITLE
Confirmation Dialogue For Plugin Uninstall

### ISSUE THREAD

**Issue by tsviper** [oznu/homebridge-config-ui-x#148]
Just uninstalled a plugin and noticed that it didn't offer any sort of confirmation before uninstalling.  This could easily happen by accident.  Suggest adding confirmation dialogue before removal.

**Comment by oznu** [comment]
Hi @tsviper,

Thanks for your suggestion.

I'm not sure about this. I dislike adding confirmation messages / dialogs for easily reversible actions. In this case uninstalling a plugin is easily reversed by re-installing the plugin.

UX Ref:

https://ux.stackexchange.com/a/89162
https://ux.stackexchange.com/a/39350

**Comment by tsviper** [comment]
Okay, that makes sense.
