### ISSUE TITLE
Control KlikaanKlikuit receivers via Homebridge in Docker GPIO access

### ISSUE THREAD

**Issue by pjansen75** [oznu/homebridge-config-ui-x#149]
Hi,

I need access to GPIO via Homebridge in Docker, but I don't get it to work.
I have Klikaanklikuit (kaku) receivers in the house and I now want to control them via Homebridge in Docker.
Do someone have experience with this? How to get it working in Docker via rpi driver?

bcm2835_init: Unable to open /dev/mem:

**Comment by oznu** [comment]
This issue should probably be on oznu/docker-homebridge; but I'll answer it here.

Hi @pjansen75,

If you need access to the rPI GPIO, you'll need to run homebridge outside of the Docker container. I would recommend setting Homebridge up using systemd instead.

https://gist.github.com/johannrichard/0ad0de1feb6adb9eb61a/
