### ISSUE TITLE
Plugin /homebridge/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.

### ISSUE THREAD

**Issue by henkied** [oznu/homebridge-config-ui-x#151]
after updating i get this error message.

What can i do? Homebridge is online but does not work anymore in the homeapp

**Comment by oznu** [comment]
`homebridge-lib` is part of some other plugin you have installed, not this one. 

The message you've posted is just a warning, it shouldn't prevent homebridge from starting.

**Comment by henkied** [comment]
all right thx @oznu
