### ISSUE TITLE
'save' button on homebridge-config-ui-x settings does not work

### ISSUE THREAD

**Issue by g-arjones** [oznu/homebridge-config-ui-x#153]
Clicking the 'Save' button on homebridge-config-ui-x settings form does not save the changes. The spinner runs forever and config.json is not updated. I don't mean the config.json file edtior (this one works as expected) what I mean is the one that is available in the 'Plugins' tab. Nothing unusual is shown in the logs, btw.

**Comment by oznu** [comment]
I cannot replicate this. What does your setup look like? Both your issues are probably caused by something unique to your environment.

**Comment by g-arjones** [comment]
I am running homebridge-config-ui-x as a plugin in a docker container. It suddenly started working as expected and can't reproduce it right now.

The other issue was likely caused by a failed update attempt though I don't think `npm` would remove  the existing package in that case.

Feel free to close both issues if you think they are not helpful, I will open again if have more info. Thanks!
