### ISSUE TITLE
Error message when I try to uninstall

### ISSUE THREAD

**Issue by avoud** [oznu/homebridge-config-ui-x#1573]
### Current Situation

I am running Homebridge in Raspberry Pi and I try to uninstall it, but I receive the following message. 

The 'hb-service uninstall' command is not available when Homebridge is running as a system package.

I tries as root and the problem persists. Any ideas?

### Homebridge UI Version

v 4.50.5

### Homebridge Version

v 1.6.1

### Node.js Version

v 18.16.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi Zero W

**Comment by bwp91** [comment]
Hi @avoud you may be running homebridge in a non-traditional or non-recent way.

There is a wiki article here about standalone mode

- https://github.com/homebridge/homebridge-config-ui-x/wiki/Standalone-Mode

and also an article about switching from the above mode to `hb-service`-mode

- https://github.com/homebridge/homebridge-config-ui-x/wiki/How-To-Swap-From-Standalone-Mode-to-Service-Mode

maybe one or both of these could help? or at least help you understand how you are running homebridge and so the correct method of uninstallation?
