### ISSUE TITLE
Not understandable language

### ISSUE THREAD

**Issue by Husian3li** [oznu/homebridge-config-ui-x#1575]
### Current Situation

I have my home bridge installed yesterday and it was working fine, today o logged in ti find the most worlds are not understandable, how to fix this?

### Homebridge UI Version

latest

### Homebridge Version

latest

### Node.js Version

latest

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @Husian3li 

Not understanding what you mean by this

> find the most worlds are not understandable, how to fix this?

could you clarify what you mean? Do you ~~worlds~~ words?
