### ISSUE TITLE
Translation with POEditor

### ISSUE THREAD

**Issue by YellowNest** [oznu/homebridge-config-ui-x#1576]
### Feature Description

I have a suggestion on how to work more easily with the translation of the homebridge ui. I'm involved in some translation jobs for various projects out there and many projects use POEditor, a really awesome tool that makes translation jobs a lot easier!

**Comment by YellowNest** [comment]
No one?

**Comment by T-IOOO** [comment]
No one?

**Comment by donavanbecker** [comment]
@T-IOOO Most translations are user submitted. So if you want to implement this int Homebridge Ui, we can review it

**Comment by YellowNest** [comment]
Yes I know that you need to submit changes for review but it’s way more easier with POEditor. It’s easier to collaborate with other translators that way.
