### ISSUE TITLE
Error message when opening frontend

### ISSUE THREAD

**Issue by YellowNest** [oznu/homebridge-config-ui-x#1577]
### Describe The Bug

I get the following error now when opening the frontend. I am opening from safari on iOS 17.

Service Restart Required

WARNING: Homebridge UI v4.50.7-test.9 has been installed, but the server service is still running v4.50.7-test.9.

### Homebridge UI Version

v4.50.7-test.9

### Homebridge Version

v1.6.2-beta.0

### Node.js Version

18.18.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by Snowedin3** [comment]
Same thing for me when I tried out the Beta.

**Comment by bwp91** [comment]
This should no longer be present in the newest beta 👍
