### ISSUE TITLE
Logfile timestamp wrong

### ISSUE THREAD

**Issue by RMCob** [oznu/homebridge-config-ui-x#1581]
### Describe The Bug

The timestamps in the logfile are all -1 hour off. The timestamp will be 10:05am when it's actually 11:05am. The Status page shows the correct timezone (GMT-0500) and if I go to the Linux command line the 'date' command shows the correct time.

### Homebridge UI Version

4.50.6

### Homebridge Version

1.6.1

### Node.js Version

18.17.1

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by RMCob** [comment]
It seems as though it it not honoring Daylight Savings Time here in the US.

**Comment by NorthernMan54** [comment]
That seems odd, as it works okay in the Eastern time zone.
