### ISSUE TITLE
One log file per child bridge

### ISSUE THREAD

**Issue by ohmantics** [oznu/homebridge-config-ui-x#1588]
### Current Situation

Some plugins cause a constant spray of errors and warnings, especially recently after changes to indicate that a plugin slows down Homebridge.

While the correct fix is to fix each and every plugin, this is a slow process as plugins are all volunteer-authored.

With such a spray of log data, the log rolling removes potentially useful data about other plugins.

### Proposed Change

It would be useful for now to be able to have child bridges each end up with their own log files. This is of particular help to plugin authors who are trying watch for issues with their own plugin.

**Comment by mkz212** [comment]
As for the logs:
- Logs visible in the browser should be a minimum of 24 hours
- Logs on the sd card should be save from each day and be overwritten only after 30 days.

**Comment by ohmantics** [comment]
(Not a fan of auto-stale.)

**Comment by mkz212** [comment]
Added in 4.54.1. Issue can be closed.

**Comment by ohmantics** [comment]
Just updated to 4.54.1. I don't see how the logs are being split by child bridge. I'm still wading through the countless messages that the TplinkSmarthome plugin sprays.

**Comment by donavanbecker** [comment]
Go to each plugin and click the cog (gear) for the plugin and click plugin logs

**Comment by ohmantics** [comment]
Ah, thanks! I was going through the bridge icon.
