### ISSUE TITLE
placeholder not working for boolean fields

### ISSUE THREAD

**Issue by dkerr64** [oznu/homebridge-config-ui-x#1594]
### Describe The Bug

The placeholder attribute on a property is being ignored.  For example,

```json
"logErrors": {
    "title": "Log errors",
    "type": "boolean",
    "placeholder": true
}
```

Results in the GUI displaying the checkbox without it being checked, when the expected behavior is for it to be checked.
Placeholder is working fine for other field types, e.g. number and string.

### Homebridge UI Version

homebridge-config-ui-x v4.50.6

### Homebridge Version

v1.6.1

### Node.js Version

v18.17.1

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
You would want to do `default` instead of `placeholder`.

**Comment by dkerr64** [comment]
> You would want to do `default` instead of `placeholder`.

Yes default works.  But it has different behavior... that will write the setting to config.json whether it is changed from the default or not.  I was looking for a way to only write settings that are changed from the default value.

I think I understand why it is this way... because the support is really tied up in how browsers / HTML allow a placeholder value to be displayed in an entry field and that is not available for checkboxes.

It can be worked around if you go whole-hog and write a custom UI script.  But that is a lot of work.

Thanks.
