### ISSUE TITLE
Allow me to remove Cached Accessory directly from Accessories view (/accessories)

### ISSUE THREAD

**Issue by bamodio** [oznu/homebridge-config-ui-x#1597]
### Feature Description

I sometimes need to remove a cached accessory. It's hard to detect which one I specifically need to remove.
1. Display names in /accessories don't always match name in Homebridge Settings/Remove Single Cached Accessory
2. UUID in Remove Single Cached Accessory can't be easily found elsewhere. E.g. it would be useful if it showed up in the Accessory Details page (clicking gear on an accessory) or in HomeKit itself (gear, which shows a serial number).
3. This makes it very hard to sometimes find the accessory to remove.

Would love it if this was more obvious, in order of preference.
1. Allow a user to remove an accessory directly from the /accessories page
2. Show serial number in Remove Single Cached Accessory
3. Show UUID in /accessories page settings for a given accessory.

**Comment by bamodio** [comment]
A number 4 option: Show display name in Remove Single Cached Accessory that matches the display name as is in the /accessories page.

**Comment by bamodio** [comment]
Doing each one of the above would be the cherry on top. ;)

**Comment by BenSmartHome** [comment]
Would recommend that! For real, that would be awesome...

**Comment by mkz212** [comment]
@bamodio @BenSmartHome I will reveal that this is in the plans and that the next (or one of the next) versions will bring many changes

**Comment by BenSmartHome** [comment]
Awesome! Thanks mate!
