### ISSUE TITLE
Nodesource - Failed to update Node.js: Command failed: curl -fsSL 

### ISSUE THREAD

**Issue by Growianer** [oznu/homebridge-config-ui-x#1605]
### Describe The Bug

Linux raspiSmart 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Oct 26 19:53:27 2023 from 192.168.188.55
pi@raspiSmart:~ $ sudo hb-service update-node
ℹ Updating Node.js from v18.17.1 to v20.9.0...
ℹ Updating from NodeSource...
OK:1 http://phoscon.de/apt/deconz buster-beta InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                  
OK:3 http://archive.raspberrypi.org/debian buster InRelease                           
Holen:4 http://giteduberger.fr rpimonitor/ InRelease [1.933 B]                        
Holen:5 https://deb.nodesource.com/node_18.x buster InRelease [4.584 B]
Es wurden 6.517 B in 2 s geholt (3.975 B/s).
Paketlisten werden gelesen... Fertig
Paketlisten werden gelesen... Fertig
Abh?ngigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
ca-certificates ist schon die neueste Version (20200601~deb10u2).
curl ist schon die neueste Version (7.64.0-4+deb10u7).
gnupg ist schon die neueste Version (2.2.12-1+rpi1+deb10u1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
gpg: '/etc/apt/keyrings/nodes' kann nicht erzeugt werden: Datei oder Verzeichnis nicht gefunden
gpg: Keine g?ltigen OpenPGP-Daten gefunden.
gpg: Entfernen der ASCII-H?lle ist fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
(23) Failed writing body
✖ Failed to update Node.js: Command failed: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/nodes
pi@raspiSmart:~ $ 

### Homebridge UI Version

4.51.1

### Homebridge Version

1.6.1

### Node.js Version

18.17.1

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by NorthernMan54** [comment]
Tks for sharing this issue, we have resolved this with 4.51.2
