### ISSUE TITLE
502 - Homebridge Starting now...

### ISSUE THREAD

**Issue by LordZork** [oznu/homebridge-config-ui-x#1609]
### Describe The Bug

I just updated the [homebridge-config-ui-x](https://github.com/homebridge/homebridge-config-ui-x).  However, it's late and I performed the update via the [Homemanager app](https://www.homemanager-app.de/), on my phone, before noticing the warning.  Now, when I try to load Homebridge, I get the following message...

> 502 - Homebridge Starting now...

I have Homebridge installed on a Raspberry Pi, via the [Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image), and I don't think I have SSH enabled (if I do, I don't remember doing so or the password).  I don't even know or remember how to SSH into Homebridge, and was thinking it wasn't something you could do when Homebridge was installed via an image (instead of installed on an OS).

Also, sadly and embarrassingly, I don't have any even remotely recent backups.

Do I have any options for fixing this?  Can I pull the SD card out of my Pi and fix the issue from my computer?  Or, is my Homebridge setup essentially bricked... do I have to rebuild everything?

Why is this update even still available with such a known bug?

Any help would be greatly appreciated!

### Homebridge UI Version

I don't remember and am unable to check.

### Homebridge Version

I don't remember and am unable to check.

### Node.js Version

I don't remember and am unable to check.

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by NorthernMan54** [comment]
@LordZork The homebridge raspbian image comes with SSH enabled, so if you have the password setup when the image was installed you could do that.

If not, you can access the homebridge backups from the SD card. They are in the directory `/var/lib/homebridge/backups/instance-backups`.  Copy one backup off, install a fresh homebridge image onto a different SD card, then restore the backup.

**Comment by LordZork** [comment]
@NorthernMan54 

Thanks for that info!

Do you know if there is a default password in the event one was not setup?

Also, this is probably a dumb question, but does Homebridge auto-generate any (recent) backups on its own?  Or would the only backups I find be the old ones I created?

**Comment by NorthernMan54** [comment]
It creates daily backups

ls -l instance-backups/
total 2620
-rw-r--r-- 1 homebridge homebridge 395970 Oct 24 01:03 homebridge-backup-BC223DE3CF31.1698123828204.tar.gz
-rw-r--r-- 1 homebridge homebridge 395609 Oct 25 01:03 homebridge-backup-BC223DE3CF31.1698210228527.tar.gz
-rw-r--r-- 1 homebridge homebridge 395107 Oct 26 05:05 homebridge-backup-BC223DE3CF31.1698311152540.tar.gz
-rw-r--r-- 1 homebridge homebridge 394642 Oct 27 05:05 homebridge-backup-BC223DE3CF31.1698397549742.tar.gz
-rw-r--r-- 1 homebridge homebridge 363820 Oct 28 05:42 homebridge-backup-BC223DE3CF31.1698486167562.tar.gz
-rw-r--r-- 1 homebridge homebridge 363888 Oct 29 05:42 homebridge-backup-BC223DE3CF31.1698572567490.tar.gz
-rw-r--r-- 1 homebridge homebridge 363999 Oct 30 05:42 homebridge-backup-BC223DE3CF31.1698658967596.tar.gz

And we do not have a default password

**Comment by LordZork** [comment]
@NorthernMan54 

I just found this: [How To Connect Via SSH](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Connect-Via-SSH)

As you mentioned...
> SSH is enabled by default.

However, it also states...
> The default username is pi with password raspberry.

I tried the default password and it worked!...
![Homebridge-ssh](https://github.com/homebridge/homebridge-config-ui-x/assets/65878888/c25ae3fa-eb64-4d5c-82bb-d5a1d7bc55dd)
That said, according to the notes—for [Release 4.51.2 (2023-10-27)](https://github.com/homebridge/homebridge-config-ui-x/releases/tag/4.51.2)—I can do the following...

> If the system does not start after the update, connect via SSH and run:
> `sudo hb-service rebuild`

However, I am wondering if I should pull the latest backup (or maybe the last few backups) from the SD card, first?  Or, is the rebuild process safe (in that it will not delete the auto-generated backups)?

Also, if it's better to first save a backup file to my Mac (before running the rebuild), can I do that via SSH?  Or would I still need to pull the SD card for that?

Thanks again for your help—I very much appreciate it!

**Comment by NorthernMan54** [comment]
The rebuild is safe

With network access you can use the sftp command to retrieve files

**Comment by LordZork** [comment]
@NorthernMan54 

That worked!  I was able to copy over my backups (via sftp), and then successfully run `sudo hb-service rebuild`.

That said, regarding [Release 4.51.2 (2023-10-27)](https://github.com/homebridge/homebridge-config-ui-x/releases/tag/4.51.2)...

> Before updating to NodeJS 20, check what version of GLIBCXX you have. In the terminal run:
> 
> `strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX`
> 
> If there is 3.4.26 then you can update the node to version 20, if not - DO NOT UPDATE NODE!
> If you do not have GLIBCXX 3.4.26 but you want to update node, you must either perform a fresh installation ( The homebridge Raspbian image is a good choice ) with the latest version of Homebridge and then restore the backup.

I don't have **GLIBCXX 3.4.26** (the latest I have is **3.4.25**).  Can you advise on the following?...
- If I wait (for a fix), will I eventually be able to update to **NodeJS 20** _WITHOUT_ having to first "perform a fresh installation... and then restore the backup"?
- Another option is implied ("you must EITHER perform a fresh installation") but not provided.  Is there another option?

Thanks again for your help!

**Comment by NorthernMan54** [comment]
With the NodeJS 20 update, it will requires updates to the operating system.  Besides a fresh install, you could look thru here for options https://github.com/homebridge/homebridge/issues/3453

**Comment by LordZork** [comment]
@NorthernMan54 

Being that the main issue here was resolved, I will close with this comment.  If I find another workable solution for updating to **NodeJS 20**—without performing a fresh installation—I will report back in that other [issue](https://github.com/homebridge/homebridge/issues/3453) you linked.

Thanks again for all of your help (and for your quick replies)—it is much appreciated!
