### ISSUE TITLE
Can't install unverified plugins from ui

### ISSUE THREAD

**Issue by vsternbach** [oznu/homebridge-config-ui-x#1610]
### Describe The Bug

Can't install unverified plugins from ui (running `npm install` with sudo from terminal works), is it the expected behavior?
How users are supposed to install plugins from `homebridge-config-ui-x` then?

### Logs

```text
USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-yeelight-ble@2.1.0

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/homebridge
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/homebridge'
npm ERR!  [Error: EACCES: permission denied, mkdir '/home/homebridge'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/homebridge'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /home/homebridge/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

Operation failed. Please review log for details.
```

### Homebridge UI Version

v4.50.6

### Homebridge Version

v1.6.1

### Node.js Version

v18.18.2

### Operating System

Raspbian GNU/Linux Buster (10)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3

**Comment by vsternbach** [comment]
I also don't understand what and why tries to run this command in the above log: `mkdir '/home/homebridge'`

**Comment by donavanbecker** [comment]
Have you tried installing other unverified plugins? Do they do the same thing?

Looks like with this plugin's readme, it requires a python library to be installed for this plugin to work.

**Comment by vsternbach** [comment]
yes, it's for all of them, I see in the code of `homebridge-config-ui-x` that it installs verified plugins differently, by not running `npm install` but with plugin-upgrade-install.sh script

**Comment by donavanbecker** [comment]
I just installed 
```
homebridge-yeelight-ble
```
On docker, with no issues.

**Comment by vsternbach** [comment]
Probably worth mentioning that I've removed homebridge after upgrading to node 20, uninstalling it and returning back to 18 according these instructions https://github.com/nodesource/distributions#installation-instructions and then did fresh homebridge install according to the instructions https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

And before that I didn't have any problem installing from ui either, it started after fresh installation from scratch.

**Comment by vsternbach** [comment]
Digging a bit further I see that I don't have homebridge directory in `/home`, after creating it manually with `sudo mkdir` and trying plugin install from ui I'm getting this error:
```
USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-yeelight-ble@2.1.0

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/homebridge/.npm
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 999:995 "/home/homebridge/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /home/homebridge/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

Operation failed. Please review log for details.
```
I expect it has something to do with npm configuration and where it caches npm modules

**Comment by NorthernMan54** [comment]
`sudo chown -r homebridge /home/homebridge`

**Comment by vsternbach** [comment]
@NorthernMan54 It's `sudo chown -R homebridge /home/homebridge` and obviously it solves the issue, but I think the problem is bigger and it lies somewhere between fresh homebridge installation and/or homebridge ui implementation, how come that after fresh install of homebridge on Raspbian there's no `/home/homebridge` directory with correct permissions? and that installation of plugins from homebridge ui behaves differently between verified and unverified plugins, I mean for verified plugins there's no need for `/home/homebridge` directory to be present at all.

**Comment by NorthernMan54** [comment]
The home directory is used by NPM to store its work in progress files and cache.  I think at some point something happened to your /home/homebridge directory.

PS Both myself and @donavanbecker did a quick regression test, and were not able to recreate the issue.

PSS My test environment is a docker image, that installs the homebridge apt package on a RPI, and then runs it.

**Comment by vsternbach** [comment]
@NorthernMan54 So you're saying that after fresh install of homebridge with apt on RPI /home/homebridge directory should exist? If so, then something went wrong during my installation probably. Thanks for the help and we can close this issue then I suppose.
