### ISSUE TITLE
Display of Accessory Setup Code inconsistent with current Home app

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#1612]
### Describe The Bug

Homebridge UI displays 123-45-678 for the Home app accessory setup code
The Apple Home app now displays 1234-5678 (the format has changed)
The display of the code is inconsistent.
Homebridge UI should update the displayed setup code format to 1234-5678

### Logs

```text
n/a
```

### Config

```json
n/a
```

### Homebridge UI Version

homebridge-config-ui-x v4.52.0-beta.42

### Homebridge Version

v1.7.0-beta.6

### Node.js Version

v20.9.0

### Operating System

Windows 10

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
This will be resolved in the next release of Homebridge-coming-ui-x

**Comment by jsiegenthaler** [comment]
Thanks

**Comment by donavanbecker** [comment]
This broke setup of the code. Will try to display it differently in the future, but if generated this way it messes up with pairing.
