### ISSUE TITLE
Will it be safe to update the plugin from 4.51.0 to 4.51.2?

### ISSUE THREAD

**Issue by remlio** [oznu/homebridge-config-ui-x#1613]
### Current Situation

I updated the plugin to 4.51.0 on Raspberry PI normally and without any issues, but at this point I'm too afraid to update it to 4.51.2. Will it be safe or should I wait some time? I’m on Node v20.9.0 now. Raspbian GNU/Linux 11 (bullseye)

### Homebridge UI Version

4.51.0

### Homebridge Version

1.6.1

### Node.js Version

20.9.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 2

**Comment by bo-2221** [comment]
Everything worked for me. Make a backup of your SD card, if things go wrong, restore the backup!

**Comment by remlio** [comment]
thanks for the advice, i’m doing the backup

**Comment by remlio** [comment]
great, I just updated without any issues
