### ISSUE TITLE
v4.52.0-beta.49 Prebuild binary missing for platform. System Windows_NT 10.0.19045

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#1621]
### Describe The Bug

v4.52.0-beta.49 fails to install over homebridge-config-ui-x v4.51.2, on Win10, throwing error Prebuild binary missing for platform. System Windows_NT 10.0.19045

### Logs

```text
npm ERR! Prebuild binary missing for platform.
npm ERR! prebuild-install info begin Prebuild-install version 7.1.1
npm ERR! prebuild-install info looking for local prebuild @ prebuilds\node-pty-prebuilt-multiarch-v0.11.8-beta.2-node-v115-win32-x64.tar.gz
npm ERR! prebuild-install info looking for cached prebuild @ C:\Users\me\AppData\Local\npm-cache\_prebuilds\f625a1-node-pty-prebuilt-multiarch-v0.11.8-beta.2-node-v115-win32-x64.tar.gz
npm ERR! prebuild-install http request GET https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.8-beta.2/node-pty-prebuilt-multiarch-v0.11.8-beta.2-node-v115-win32-x64.tar.gz
npm ERR! prebuild-install http 404 https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.8-beta.2/node-pty-prebuilt-multiarch-v0.11.8-beta.2-node-v115-win32-x64.tar.gz
npm ERR! prebuild-install warn install No prebuilt binaries found (target=20.9.0 runtime=node arch=x64 libc= platform=win32)
```

### Config

```json
n/a
```

### Homebridge UI Version

homebridge-config-ui-x v4.51.2

### Homebridge Version

1.7.0

### Node.js Version

v20.9.0

### Operating System

Windows 10

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
@jsiegenthaler Spent a bit of time this AM looking into this, and can not recreate the issue.

The first message `Prebuild binary missing for platform.` is expected as the NPM package only bundles prebuilds for linux based environments.  But the error 404 at the next step is not expected.

I tried the download URL `https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.8-beta.2/node-pty-prebuilt-multiarch-v0.11.8-beta.2-node-v115-win32-x64.tar.gz` and for me it works

Can you try the url from your browser ?  I'm wondering if something in your local environment is blocking the download.

And you can see the downloads on the server - `https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/v0.11.8-beta.2/`

FYI - Contents of the download should be this

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/19808920/42d7f04c-1a3c-4425-8c07-c4c014310baf)

**Comment by jsiegenthaler** [comment]
This afternoon it installed without error. You can close the issue.

**Comment by NorthernMan54** [comment]
Tks for testing the beta for us
