### ISSUE TITLE
Generated code is not accepted, when trying to add devices

### ISSUE THREAD

**Issue by mensa84** [oznu/homebridge-config-ui-x#1625]
### Describe The Bug

In v4.52.0 the new code is not accepted, when I want to add a device although it is the same as displayed in the logfile.
See here: https://github.com/maxileith/homebridge-appletv-enhanced/issues/10#issuecomment-1793498279

### Homebridge UI Version

4.52.0

### Homebridge Version

1.7.0

### Node.js Version

20.9

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
@mensa84, can you share your config?

Specifically the stuff in your bridge section:

```json
 "bridge": {
        "name": "Homebridge 678D",
        "username": "1A:2B:34:5C:67:8D",
        "port": 12345,
        "pin": "456-04-985",
        "advertiser": "ciao",
        "manufacturer": "Homebridge.io",
        "model": "Bridge"
    }
```

**Comment by mensa84** [comment]
This is my config, but I have downgraded to v4.51.2 now, so that adding devices will work again:

```
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "advertiser": "avahi"
}
```

**Comment by donavanbecker** [comment]
On well then we will close this as you have it resolved. Unless you are willing to test?

**Comment by mensa84** [comment]
I think the bug is still there in v4.52.
Is the conde random in the new version?

**Comment by donavanbecker** [comment]
I agree, but can you test it?

**Comment by donavanbecker** [comment]
closing as we reverted the changs in 4.52.1

**Comment by mensa84** [comment]
@donavanbecker How can I install 4.52.1?

**Comment by donavanbecker** [comment]
Once it is released. It's is currently in beta, which you can install from the alternative version menu.
