### ISSUE TITLE
Synology DSM HomeBrdige IU update

### ISSUE THREAD

**Issue by Bike-ops04** [oznu/homebridge-config-ui-x#1630]
### Current Situation

Hi, When I update to the newest plugin and restart it never restarts and ask me to manually restart but then I can't get back in to the login screen. I am on platform for synology and everything is up to date. Are they working on this issue?
 I had to reinstall homebridge to be able to login.

### Logs

```markdown
none
```

### Configuration

```json
none
```

### Environment

- OS: Synology
- Software: homebridge newest version
- Node: v18
- npm:?

### Process Supervisor

other (Explain in `Additional Context`)

### Additional Context

Synology

**Comment by NorthernMan54** [comment]
Is this a duplicate of this https://github.com/homebridge/homebridge-syno-spk/issues/138

**Comment by Bike-ops04** [comment]
> Is this a duplicate of this homebridge/homebridge-syno-spk#138

I think it is but I didn’t see anything for the synology dsm platform. I can erase it if it’s the same

**Comment by NorthernMan54** [comment]
homebridge-config-ui-x@4.52.1 should have resolved homebridge/homebridge-syno-spk#138.  To see if this is a new issue, could you try the update again, and ssh in and look at the home bridge log ?

**Comment by Bike-ops04** [comment]
I did try this on Saturday and it doesn’t work. I can try again but won’t be able to for another week or so

**Comment by chadmccan** [comment]
> homebridge-config-ui-x@4.52.1 should have resolved homebridge/homebridge-syno-spk#138. To see if this is a new issue, could you try the update again, and ssh in and look at the home bridge log ?

It is resolved with the 4.52.1 update. I just installed it and it works on Synology now.

**Comment by Bike-ops04** [comment]
ok that is great thank you
