### ISSUE TITLE
Status page - new default widget order

### ISSUE THREAD

**Issue by mkz212** [oznu/homebridge-config-ui-x#1634]
### Feature Description

I think that could be the default layout of widgets. In the current one, you have to scroll down to see the logs and scroll down to see all system info.

<img width="1443" alt="Zrzut ekranu 2023-11-6 o 12 48 36" src="https://github.com/homebridge/homebridge-config-ui-x/assets/82271669/4995f84b-09e6-4a97-9eeb-21b3048b3973">

**Comment by donavanbecker** [comment]
The reason for the change was to show off the child bridge widget.

**Comment by donavanbecker** [comment]
In the future, if you would like changes please open a PR and we can consider it.
