### ISSUE TITLE
Node update problem

### ISSUE THREAD

**Issue by dfizzo** [oznu/homebridge-config-ui-x#1640]
### Current Situation

Hi - I updated node.js with sudo hb-service update-node, and now I cannot access homebridge UI. I am not an expert here so any guidance would be extremely appreciated!! Thank you everyone!!

### Logs

```markdown
Don’t have.
```

### Configuration

```json
Don’t have.
```

### Environment

- OS: raspbian
- Software: ?
- Node: ?
- npm: ?

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Duplicate of https://github.com/homebridge/homebridge/issues/3453

**Comment by bwp91** [comment]
Closing as looks like it's a duplicate. Please feel free to reopen if you don't agree!
