### ISSUE TITLE
Supported accessory aren't showed

### ISSUE THREAD

**Issue by martinorob** [oznu/homebridge-config-ui-x#165]
Hi and thanks for this great project.
On my Mac works well but I don't see all of my home accessories. 
Like Thermostat or my hue light.

With I'm doing wrong?

Thanks
M.

**Comment by oznu** [comment]
Are those accessories from homebridge plugins or are they native HomeKit accessories? This app will only show homebridge-plugin accessories.

**Comment by martinorob** [comment]
okay, my thermostat or other are native HomeKit accessories.. 😕

**Comment by oznu** [comment]
They won't show up unfortunately. It's not possible to bypass the HomeKit device encryption, even if we know the original pairing pin.

If your device also has a homebridge plugin (like Phillips Hue), you might be able to get around the issue that way.
