### ISSUE TITLE
Not working behind nginx

### ISSUE THREAD

**Issue by martinorob** [oznu/homebridge-config-ui-x#166]
Please add the nginx config on the wiki

Thanks

this is my conf

`server {
	    listen 443 ssl;
	    listen [::]:443 ssl;

	    server_name my.domain.com;

	    ssl_certificate /volume1/cert/fullchain.pem;

	    ssl_certificate_key /volume1/cert/privkey.pem;

	    location / {

		        proxy_connect_timeout 60;
		        proxy_read_timeout 60;
		        proxy_send_timeout 60;
		        proxy_intercept_errors off;
		        proxy_http_version 1.1;
		        proxy_set_header        Host            $http_host;
		        proxy_set_header        X-Real-IP            $remote_addr;
		        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;
		        proxy_set_header        X-Forwarded-Proto            $scheme;
				rewrite ^(.*)$ /http://192.168.3.80:8181/$1;
				proxy_pass http://192.168.3.80:8181;
				    }

			    error_page 403 404 500 502 503 504 @error_page;

			    location @error_page {
				        root /usr/syno/share/nginx;
				        rewrite (.*) /error.html break;
				        allow all;
								    }
}`

**Comment by oznu** [comment]
See 
https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-SSL-with-Nginx
