### ISSUE TITLE
change node version

### ISSUE THREAD

**Issue by platini76** [oznu/homebridge-config-ui-x#167]
I am getting crazy on change node version:

<img width="650" alt="schermata 2018-10-13 alle 16 53 03" src="https://user-images.githubusercontent.com/10352902/46906726-90279000-cf08-11e8-9071-2b9462e3378a.png">

all my node used version a re v10.0.0 but homebridge-config-ui-x use v10.12.0
where to change it?

pi@raspberry:~ $ nvm ls
->      v10.0.0
         system
default -> v10.0.0
node -> stable (-> v10.0.0) (default)
stable -> 10.0 (-> v10.0.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.4 (-> N/A)
lts/carbon -> v8.12.0 (-> N/A)

$ $ $ nvm ls
->      v10.0.0
         system
default -> v10.0.0
node -> stable (-> v10.0.0) (default)
stable -> 10.0 (-> v10.0.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.4 (-> N/A)
lts/carbon -> v8.12.0 (-> N/A)

root@raspberry:~# nvm ls
->      v10.0.0
         system
default -> v10.0.0
node -> stable (-> v10.0.0) (default)
stable -> 10.0 (-> v10.0.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.4 (-> N/A)
lts/carbon -> v8.12.0 (-> N/A)

**Comment by oznu** [comment]
Hi @platini76,

`homebridge-config-ui-x` will use whatever version of node Homebridge is using. You're question might be better directly to the [Homebridge Community](https://github.com/nfarina/homebridge#community) Slack or Reddit channels as I don't have experience with `nvm`.

**Comment by platini76** [comment]
as you see all system and all users use version v10.0.0
