### ISSUE TITLE
Homebridge Log Location on OSX

### ISSUE THREAD

**Issue by mrtekkid** [oznu/homebridge-config-ui-x#168]
Where do the Homebridge logs store on OSX so that Config UI can access them? I already modified the sudoers file but nothing helps. 

its not in /var/logs/ as it is on Linux 

All Config in browser shows when viewing logs is:

Using systemd to tail logs
CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge

sudo: journalctl: command not found

The log tail command "sudo -n journalctl -o cat -n 500 -f -u homebridge" exited with code 1.
Please check the command in your config.json is correct.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

**Comment by oznu** [comment]
Hi @mrtekkid,

You'll need to refer to the guide you used to setup Homebridge on macOS. Each setup is different and I'm not sure where you would be saving the logs to.

You'll be wanting to use the [Logs From File](https://github.com/oznu/homebridge-config-ui-x#logs-from-file) method. [Logs from Systemd](https://github.com/oznu/homebridge-config-ui-x#logs-from-systemd) is a Linux-only logging method.

**Comment by robertgranholm** [comment]
This doesn't answer the question and I have the same one, the log location referenced IS INCORRECT on Mac, where are the log files?
