### ISSUE TITLE
Scrolling logs on mobile not working 

### ISSUE THREAD

**Issue by satrik** [oznu/homebridge-config-ui-x#1695]
### Describe The Bug

Since the last update, scrolling logs on my iPhone works only if the touch event does not start on text. It works only on the free spaces between text 

### Homebridge UI Version

4.52.2

### Homebridge Version

1.7.0

### Node.js Version

18.18.2

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
I noticed this about 5 minutes before you posted the issue. Looking into this!

**Comment by mkz212** [comment]
iPhone 14, iOS 17.1.1. Safari. 

Edit. Sorry. After a thorough analysis it really does not move on the text. In logs and in logs widget.

**Comment by mkz212** [comment]
in beta 24 it is ok! 👍 . 

Only that the left margin is smaller than the right one.
<img width="599" alt="Zrzut ekranu 2023-11-13 o 16 35 19" src="https://github.com/homebridge/homebridge-config-ui-x/assets/82271669/91eff7d8-cd0c-4a55-8cd6-ba28eeea475a">

**Comment by bwp91** [comment]
Closing this as should be fixed with latest release
