### ISSUE TITLE
Can’t update Homebridge-config-uni-x to latest version

### ISSUE THREAD

**Issue by dvd2000k** [oznu/homebridge-config-ui-x#1716]
### Describe The Bug

![IMG_0505](https://github.com/homebridge/homebridge-config-ui-x/assets/17496560/aca91f35-875a-404f-8668-bc77903b0450)

Tried to upgrade several time, same error appear.

### Homebridge UI Version

4.52.2

### Homebridge Version

1.7.0

### Node.js Version

18.18

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by donavanbecker** [comment]
Sorry are on 4.52.2 and are trying to go to 4.52.3?

**Comment by NorthernMan54** [comment]
@dvd2000k The message `sudo npm: command not found` is the cause here.  With your installation it appears that the root/sudo account does not have access to npm

Which guide did you use to set this up?  I'm asking the /usr/local/lib isn't one of our typical locations

**Comment by dvd2000k** [comment]
Is an homebridge installation via official image. Never happened before the update. 
I’m on 4.52.2.

**Comment by dvd2000k** [comment]
![IMG_0506](https://github.com/homebridge/homebridge-config-ui-x/assets/17496560/8f5d7ef7-428a-4ba4-a00a-f4d05848e032)
Before this happened I’ve tried to upgrade node with “sudo hub-service update-node” but it failed.

**Comment by dvd2000k** [comment]
Issue solved by reinstalling node 18.8.2.
Now the update can be done without errors.

The UI tell me there is an updated version of node again. Is it safe now to update?

**Comment by NorthernMan54** [comment]
We fixed a small issue with update-node in 4.52.2, so update to 4.52.3, then it should be okay.

**Comment by dvd2000k** [comment]
I mean if it is safe now to update node. The UI tell me there is an updated node (i think 20.x)…
All the problems started after updating node….

**Comment by dvd2000k** [comment]
Successfully updated to node 20.9. We can close, thank you.
