### ISSUE TITLE
Add missing icons for Accessory Categories 32-36

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#1732]
### Feature Description

Icons for the Accessory Categories 32-36 do not exist
These are:
32	TARGET_CONTROLLER
33	ROUTER
34	AUDIO_RECEIVER
35	TV_SET_TOP_BOX
36	TV_STREAMING_STICK
Icons exist in HomeKit for 34, 35 and 36, which can be used as inspiration for the svg file

**Comment by bwp91** [comment]
When I got the email notification about this I was hoping it was a pull request, not an issue 🤭

**Comment by jsiegenthaler** [comment]
Happy to help if I can. Let me find an SVG editor...

**Comment by jsiegenthaler** [comment]
Hmmm... I cloned the code and am looking through it. I see it supports Accessory_Service_Types, of which Television is one. But I haven't found any code for Accessory_Category_Type. Does the UI even support Accessory_Category_Type? For a Settop Box, the Service Type = Television but the Category Type = TV_SET_TOP_BOX

**Comment by bwp91** [comment]
Hey sorry my first reply wasn’t meant to make you feel like you needed to sort this, apologies if that came across the wrong way.

Are you on the homebridge discord server? Maybe would be cool to chat about this implementation whether we get to a solution or not!

**Comment by jsiegenthaler** [comment]
I'll head over to the discord server now...

**Comment by jsiegenthaler** [comment]
Bump

**Comment by jsiegenthaler** [comment]
Bump
