### ISSUE TITLE
Login Button Inactive in Google Chrome when password stored

### ISSUE THREAD

**Issue by MarkThielen** [oznu/homebridge-config-ui-x#175]
Hey there,

when you store the Config-UI-X password within Chrome (Web / Mobile) Login Button is disabled, see screenshots below. 

- Mac Chrome Version 70.0.3538.77 (official build)
- iOS Chrome Version 70.0.3538.75 

**Chrome running on IOS - User / Password filled in but Login Button is disabled**
![image-1](https://user-images.githubusercontent.com/6243768/48313374-d7fb0f00-e5bb-11e8-8cc4-32cc6f0583d0.jpeg)

**Chrome running on MacOSX - User / Password filled in but Login Button is disabled**
![image](https://user-images.githubusercontent.com/6243768/48313393-23adb880-e5bc-11e8-85d8-5d6fb8e9a6ac.png)

Cheers,
Mark

**Comment by oznu** [comment]
Thanks, this has been fixed and will be published in the December release.
