### ISSUE TITLE
Small glitch

### ISSUE THREAD

**Issue by sschuste** [oznu/homebridge-config-ui-x#178]
Hi, thanks for your wonderful work.

I installed a plugin directly from GitHub with npm install -g --unsafe-perm https://github.com/hallos/homebridge-cmdtrigger. Everything is working fine, and the plugin is listed correctly in homebridge-config-ui-x.

Of course, homebridge-config-ui-x doesn't show the NPM button, but right handed it shows the link to GitHub. Unfortunately, there is no link provided by the cmdtrigger plugin. So if you click on the icon the plugin list is being reloaded. I understand completely why this happens, but is it necessary to show the icon when no link is available?

Stefan

**Comment by oznu** [comment]
Thanks, this has been fixed and will be published in the December release.
