### ISSUE TITLE
hb-service update-node error

### ISSUE THREAD

**Issue by Jeepmg** [oznu/homebridge-config-ui-x#1796]
### Describe The Bug

hb-service update-node error

### Logs

```text
sudo hb-service update-node
/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js:796
        const currentLts = versionList.filter(x => x.lts)[0];
                                       ^

TypeError: versionList.filter is not a function
    at HomebridgeServiceHelper.checkForNodejsUpdates (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js:796:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0
```

### Homebridge UI Version

4.52.3

### Homebridge Version

latest

### Node.js Version

20.09

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by donavanbecker** [comment]
Working on a fix for this.

As a workaround, can you try downgrading to 4.52.0 and then `update-node` and then update homebridge-config-ui-x

Edit: Actually, Try it again and see if you are able to update normally without the workaround above first.

**Comment by Jeepmg** [comment]
Ended up working after four or five tries. I do not know why.  Internet problem ?

Thank you for all.

**Comment by bwp91** [comment]
We think it was a temporary issue with the node website that wasn’t returning a version list properly. So not particular to any version of homebridge or the ui.

we will add a check for this in our code to handle this more gracefully in the future if it happens again.
