### ISSUE TITLE
Accessory cog icon does not display on Chrome iOS / iPad OS

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#1823]
### Describe The Bug

On Chrome in Win10 in the Accessory page: Mouse-over an Accessory icon fades in a cog icon which can be clicked to show a very useful accessory service values page.
On Chrome in iPad OS in the Accessory page: the cog icon never displays, you have to guess where the right place is to tap and open the accessory service values page. 

It would be good to have the cog icon displayed all the time in Chrome on iOS / iPadOS so the user knows where to tap. Especially as the common pointer method is the Fat-Finger 

### Homebridge UI Version

homebridge-config-ui-x v4.53.0

### Homebridge Version

v1.7.0

### Node.js Version

v20.10.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by mkz212** [comment]
@jsiegenthaler 

The fact that the cog does not display is not a mistake but normal operation - does not display on devices with a narrow screen. This is how it is currently programmed.

I suggested that a long press on the accessory should open the modal and in it: device control, below the settings, and even below the button that gives the ability to remove from the cache.

**Comment by bwp91** [comment]
Need to rework the accessory tile. In some ways for consistency, I would like to scrap the long tap, and a single tap brings up any accessory control (with a button in the modal for more info) and if the accessory does not have control within the UI, then immediately show the accessory info.

Or maybe somehow mirroring what HomeKit does now with common accessories like lights and switches where a part of the tile is for control, and another part is for opening accessory info. Although I do not like the 'unknown'-ness of homekit accessory tiles in that it takes a bit of trial and error to know what click will do what.

**Comment by mkz212** [comment]
Fixed in 4.54.1. Issue can be closed.
