### ISSUE TITLE
aqara sensor: air pressure not available in tab devices

### ISSUE THREAD

**Issue by fezzz** [oznu/homebridge-config-ui-x#183]
### Problem
connecting the aqara sensor for temp/humidity/air pressure with conbee workes fine. All values are available in deconz. Connecting with homebridge-hue to homebridge shows 3 devices for 1 sensor where temp. and humidity are working great but the air-pressure is shown as "not supported". All values are correctly routed to homekit including the air-pressure, but it is not shown in the homebridge-config-ui-x in the tab devices.
![image](https://user-images.githubusercontent.com/6622789/49331594-073fe300-f5a0-11e8-8393-ec2ec494b0a7.png)

### used versions
deconz: 2.05.49 / 29.11.2018 (same on 2.5.48)
conbee: 0x262f0500
homebridge: Version 0.4.45
homebridge-hue: v0.11.1
homebridge-config-ui-x: v3.9.0
nodejs: v11.2.0

**Comment by oznu** [comment]
Hi @fezzz,

See the #47 for a list of supported devices. I will try and add these new accessory types when I get some spare time, PRs are welcome also.

Tagging meta issue and closing: https://github.com/oznu/homebridge-config-ui-x/issues/47
