### ISSUE TITLE
issue after update to latest version v3.9.1

### ISSUE THREAD

**Issue by BerkTam** [oznu/homebridge-config-ui-x#185]
After the last update to homebridge-config-ui-x v3.9.1 I cannot see me homematic devices with latest version 20181126.

Can you fix this asap please. It is somhow really bothering. 

Isnt it possible to check those versions before a final release?

thx

**Comment by oznu** [comment]
Hi @BerkTam,

The last update made no changes to accessory control. Can you see any accessories?

**Comment by BerkTam** [comment]
Actually I did only run the update of homebridge-config-ui-x yesturday. Afterwards I could see any devices in the Home-App on my iPhone which worked before quite well. 
So currently I cannot see any device in the Home-App but the server is running.

**Comment by oznu** [comment]
To confirm, is the issue you're having that you cannot see homematic devices in the iOS Home app?

**Comment by BerkTam** [comment]
yes, exactly …  and this was possible before
