### ISSUE TITLE
Log Filtering

### ISSUE THREAD

**Issue by epheterson** [oznu/homebridge-config-ui-x#1861]
### Feature Description

This has been brought up a bunch of times but they're all stale. 

Hopefully this isn't a hard feature to implement, and the value is huge during debugging sessions.

Filtering two ways would be sweet:
1) Custom string in a text box
2) Click on any plugin title on its log line, then use that title for filtering (populate it in the text box)

Thanks!

https://github.com/homebridge/homebridge-config-ui-x/issues/1099
https://github.com/homebridge/homebridge-config-ui-x/issues/1169
https://github.com/homebridge/homebridge-config-ui-x/issues/1207
https://github.com/homebridge/homebridge-config-ui-x/issues/1284
https://github.com/homebridge/homebridge-config-ui-x/issues/1488
https://github.com/homebridge/homebridge-config-ui-x/issues/1616

**Comment by mkz212** [comment]
@epheterson I will tell you that work is already underway and in the next version (or one of the next) there will be huge changes, in this you will be able to see the logs for only one selected plugin.

**Comment by jsiegenthaler** [comment]
This has been included in 4.54.0, released yesterday. This issue can be closed

**Comment by epheterson** [comment]
Hey thanks! This isn't super intuitive, took me a while to find it behind the gear of each Plugin in the Plugins tab.

It still would be nice to filter on arbitrary strings unrelated to a specific plugin, though the existing implementation is very useful!
