### ISSUE TITLE
UI-X crashs after trying to change the color

### ISSUE THREAD

**Issue by t6a** [oznu/homebridge-config-ui-x#188]
UI-X crashs after trying to change the color (in the config-ui-x plugin setting)
Fails to load any menu

- installed (default image) on Docker on Synology DS716+II
- Secure Mode
- restart of container doesn't help
- had to delete the Homebridge folder (sub folder from docker in file browser) and reinstall Homebridge

<img width="1013" alt="screenshot 2018-12-07 at 22 27 39" src="https://user-images.githubusercontent.com/16940364/49673660-81c0a500-fa6f-11e8-8350-a988fb4032bd.png">

**Comment by oznu** [comment]
Hi @t6a,

Does this happen every time?

**Comment by oznu** [comment]
I'm not able to replicate that. If you provide a copy of the `config.json` after you adjust via the UI, but before you delete everything, it might shed some light. I suspect it's probably being corrupted on save (maybe due to slow IO?).

**Comment by t6a** [comment]
It had the system running in a docker container on Synology DS 716 + II

I switched to iO Broker now, more complex but also more possibilities :-)
