### ISSUE TITLE
Heaters can't be linked with temperature sensor since update

### ISSUE THREAD

**Issue by granborja** [oznu/homebridge-config-ui-x#1898]
### Describe The Bug

Since ios update the "show as" heater function doesn't work anymore.. the control of temperature is not showed on home app

### Homebridge UI Version

v1.6.1

### Homebridge Version

1.6.1

### Node.js Version

v18.13.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
We would need more info, like config, plugins, etc. as this is more then likely a plugin issue.
