### ISSUE TITLE
Not able to access through LAN

### ISSUE THREAD

**Issue by Qianli-Ma** [oznu/homebridge-config-ui-x#19]
`
    "platform":[
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": true
    }
]
}`

This is my config but when I try to access it through my Pi's IP address 10.0.1.190:8080 it shows that safari isn't able to connect to server.
When I check to see if 8080 on my pi is listening it seem that it isn't listening on port 8080

**Comment by oznu** [comment]
Can you confirm the Homebridge log shows the config plugin starting on port 8080?

If the log looks ok, make sure you don't have any firewall rules setup on the Pi that might be blocking inbound connections on port 8080.

**Comment by oznu** [comment]
I see why. I had an error in my documentation.

`platform` should be plural, `platforms`.

```json
"platforms": [
         {
               "platform": "config",
               "name":  "Config",
               "port": 8080,
               "sudo": true
         }
]
```

I have fixed the docs here: https://github.com/oznu/homebridge-config-ui-x/commit/0e97d15fea57556ab8a1ff8054bc054cbd4998af
