### ISSUE TITLE
request to add rss support to gui.

### ISSUE THREAD

**Issue by philboycn** [oznu/homebridge-config-ui-x#191]
wanna to display sensors status on pc screen with rainmeter(using plugin webparser).see this pls:[https://docs.rainmeter.net/tips/webparser-tutorial/](url).

if a rss webpage is not diffcult to build, pls add it to your plan. thanks.

**Comment by oznu** [comment]
Hi @philboycn,

I don't think this is in-scope for this project. Exposing an rss feed based on the status of the homebridge accessories is probably best handled in a separate homebridge plugin.
