### ISSUE TITLE
How to Update Docker Image from ozno/homebridge to homebridge/homebridge

### ISSUE THREAD

**Issue by thetatae** [oznu/homebridge-config-ui-x#1916]
### Current Situation

I have a working homebridge running on the Synology DSM6 using the Docker. It seems like that I need to update Node.js to version 18.15 or newer to keep my homebridge working sooner or later. But the current Docker Image is ozno/homebridge. To update the Node.js, I believe that I need to change the image to homebridge/homebridge as per my understanding. 
Please kindly help to provide step-by-step procedures to accomplish this. I have a beginner level of programming or coding so I'm just afraid that I might break my working homebridge if I try to do this myself. Any insights or instructions are highly appreciated! =D
<img width="1057" alt="Screenshot 2023-12-08 at 3 04 07 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/57340871/2922835f-75be-4498-ba5f-81a7eb80acb9">
 
<img width="390" alt="Screenshot 2023-12-08 at 3 23 13 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/57340871/977503b4-9dce-4af3-b56a-3b5cdb3214fa">

### Homebridge UI Version

v4.53.0

### Homebridge Version

v1.6.1

### Node.js Version

v18.13.0

### Operating System

Synology DSM

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

None

**Comment by grunchy99** [comment]
Hi thetatae,

You need to delete your current homebridge docker and relaunch your docker (compose up or docker run) with replacing oznu/homebridge by homebridge/hombridge. Before delete, be sure your home bridge data are external to the docker itself, if not, you will loose your homebridge config and the HomeKit devices !!

**Comment by thetatae** [comment]
> Hi thetatae,
> 
> You need to delete your current homebridge docker and relaunch your docker (compose up or docker run) with replacing oznu/homebridge by homebridge/hombridge. Before delete, be sure your home bridge data are external to the docker itself, if not, you will loose your homebridge config and the HomeKit devices !!

Hi Grunchy99,

Thanks for your help. It would be highly appreciated if you can help me with a few more questions about this. 
Can you elaborate on the steps to delete the current homebridge docker? Do you mean deleting the whole docker or deleting homebridge container or oznu/homebridge image?
<img width="1058" alt="Screenshot 2023-12-09 at 8 54 51 AM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/57340871/39dad3bf-7369-4854-a638-3da929f89836">
<img width="1056" alt="Screenshot 2023-12-09 at 8 54 58 AM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/57340871/11103017-5bb8-4dfb-a8ad-58e658c1bb60">

And after that how to add the docker image homebridge/hombridge back without loosing the running homebridge?

Currently I have all homebridge configuration files under the directory /docker/homebridge/

I just don't understand how to replace the existing oznu/homebridge with homebridge/hombridge.

Thanks for your support =D

**Comment by networkoctopus** [comment]
You don't need to upgrade your docker image to Homebridge:Homebridge, in order to upgrade your node.js. I have successfully upgraded my node.js and am also running the oznu image. 

From the Homebridge web interface, launch terminal and run command:

hb-service update-node

I have the same setup as you. 

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/77534662/c5d274fb-70df-465a-a583-66fe4b803e30)

**Comment by thetatae** [comment]
@dwyeraidan 
It works!!! And it's so easy and straightforward. Thanks a lot!

**Comment by lionproud** [comment]
I kept delaying the node.js update for months since it didn't seem straight-forward.  I found this solution and was done in two minutes.  Thank you so much.
