### ISSUE TITLE
All Accessories now returning "No Response" after latest update, 

### ISSUE THREAD

**Issue by danmcpherson** [oznu/homebridge-config-ui-x#1922]
### Describe The Bug

I installed the latest version, and since then I've been unable to control any accessories in Homekit, all are returning "No response". No obvious errors in the error logs on the Homebridge side. I've tried restarts (cold and warm) and I've tried upgrading to betas, and downgrading to earlier version. 

### Config

```JSON
I have a number of child bridges, and around 60 accessories, none are working.
```

### Homebridge UI Version

4.54.1

### Homebridge Version

1.70

### Node.js Version

20.9.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [X] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by NorthernMan54** [comment]
Have you changed anything with your networking ?

**Comment by danmcpherson** [comment]
I dont know what caused it, however I did two things:
1) I had a Homepod that required an update to 7.2, I did that. 
2) I did an apt-get update and upgrade which did include a http related library. I then rebooted. 

Now, many accessories are back again...but not all yet.

**Comment by danmcpherson** [comment]
After a while the issue came back again. I unplugged the HomePod, which was acting as the standby Home Hub and it started working again. 

So there is something going wrong between that HomePod and my Homebridge and I think since the recent update.
