### ISSUE TITLE
Getting `Load failed: 5: Input/output error` when running `sudo hb-service start`

### ISSUE THREAD

**Issue by wheelerlaw** [oznu/homebridge-config-ui-x#1923]
### Current Situation

When I execute the following command:

```
sudo hb-service start
```

I receive the following output:

```
ℹ Starting Homebridge Service...
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
✔ Homebridge Started
```

It doesn't look like here is a verbose option with `hb-service` that I can use to print out more logging information. 

Is there a way I can get a more detailed logging output so I can try to track this down?

### Logs

ℹ Starting Homebridge Service...
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
✔ Homebridge Started

### Config

```JSON
n/a as this problem applies to a blank config
```

### Homebridge UI Version

4.54.1

### Homebridge Version

1.7.0

### Node.js Version

20.10.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by wheelerlaw** [comment]
I have tried nuking the homebridge install by deleting the `node_modules` directory in `/opt/homebrew/lib`. And also tried removing node altogether as well. But doing neither of those helped.

**Comment by NorthernMan54** [comment]
On Mac OS the start command runs this - https://github.com/homebridge/homebridge-config-ui-x/blob/f63405f68a55416be3f9bb3ee4d47227b78d691c/src/bin/platforms/darwin.ts#L74

Which is just a one liner

`launchctl load -w /Library/LaunchDaemons/com.homebridge.server.plist`

Try  `hb-service uninstall` and `hb-service install` to recreate com.homebridge.server.plist
