### ISSUE TITLE
Homebridge UI

### ISSUE THREAD

**Issue by MarkP63** [oznu/homebridge-config-ui-x#1932]
### Feature Description

Latest UI seems difficult to easily identify which plug-in has an update waiting? All icons look the same?

**Comment by donavanbecker** [comment]
<img width="739" alt="Screenshot 2023-12-11 at 8 55 14 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/9875439/719539e0-99dd-4cd2-9ee1-9e1ab61b2161">

When update or something else needs to happen the cog (gear) is orange

**Comment by jeremynoesen** [comment]
I feel like if in the unused space in the top right of the card there was some sort of indicator that appeared when action is needed, it could help it stand out more. Even a colored card border could help. The current color change of the update and settings icon are possibly too subtle.

**Comment by donavanbecker** [comment]
<img width="821" alt="Screenshot 2023-12-14 at 10 36 31 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/9875439/c36e79ff-0033-433f-9942-04ee20b3ca74">

Things are being worked on to improve this.

**Comment by bwp91** [comment]
How about the icon here? It also gently flashes like the cog button in the existing release.

Also (as before) plugins with updates will be sorted to show before other plugins.

![Screenshot 2023-12-18 at 15 58 02](https://github.com/homebridge/homebridge-config-ui-x/assets/43026681/0ebef8f6-4626-4a91-9fa4-8fca15aa47b8)

**Comment by jeremynoesen** [comment]
I think that looks good and helps keep it easy to distinguish. 

One thing you could possibly do for consistency/simplicity is remove the "Installed:" text next to the version, if that no longer shows when an update is available. This would make it match the 3 above it I think.

**Comment by MarkP63** [comment]
Sorry it must be me but still not sure what I am looking at. The green or blue icons? And is it colour or presence or..?Seems everyone is hung up on hyrogliphics (icons) these days symbols for everything but nobody knows what they mean. Whats wrong with words ?  Call me old fashioned but the word Update worked well.ThanksMarkOn 18 Dec 2023, at 15:59, Ben ***@***.***> wrote:﻿
How about the icon here?
Also (as before) plugins with updates will be sorted to show before other plugins.
Screenshot.2023-12-18.at.15.58.02.png (view on web)

**Comment by bwp91** [comment]
The "up" icon in the top right hand corner that will only show when a plugin update is available

**Comment by MarkP63** [comment]
Ok thanks On 18 Dec 2023, at 20:19, Ben ***@***.***> wrote:﻿
The "up" icon in the top right hand corner that will only show when a plugin update is available
