### ISSUE TITLE
GUI alignment

### ISSUE THREAD

**Issue by nyjklein** [oznu/homebridge-config-ui-x#1945]
### Describe The Bug

Reall a nitpick. Alignment of the GUI on the status dashboard. Could the Homebridge status be aligned with the Plugins status?
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/76184316/4869457a-9c4c-4290-a42d-dfb908d6b199)

### Homebridge UI Version

 v4.54.1

### Homebridge Version

v1.7.0

### Node.js Version

v10.20.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi @nyjklein 

This is something that has been 'fixed' in the beta version of the UI. Will be included in the next release!

![Screenshot 2023-12-18 at 10 39 41](https://github.com/homebridge/homebridge-config-ui-x/assets/43026681/4c2c932c-873b-4cc7-a755-c40ed2b7ec5e)
