### ISSUE TITLE
No puedo agregar más accesorios 

### ISSUE THREAD

**Issue by Diegoid7** [oznu/homebridge-config-ui-x#1947]
### Current Situation

Necesito ayuda para poder agregar mis accesorios, si me aparecen en la app del cel pero solo pocos me aparecen en el Homebridge 
![IMG_6819](https://github.com/homebridge/homebridge-config-ui-x/assets/90568559/6f4c9862-44ea-457a-af0e-0fe720c07d83)
![IMG_6820](https://github.com/homebridge/homebridge-config-ui-x/assets/90568559/5e58569c-9996-4f1a-8947-78b4690422df)

### Homebridge UI Version

V4.54.1

### Homebridge Version

V1.7.0

### Node.js Version

20.10.0

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hola @Diegoid7 

Since this question is related to the behaviour of a certain plugin, you will need to ask the question on the plugin's GitHub page.

Which plugin are you using for this app?

**Comment by Diegoid7** [comment]
Estoy usando varios plugin pero en ninguno me deja en el de eWeLink me agrega pero solo tres de los 23 accesorios que tengo en la app y en los otros dos que son el de tuya y el de Google Home no me deja agregar ninguno, no importa cuál se quede lo importante es que con cualquiera de los 3 me deje agregar todos los dispositivos

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Ben ***@***.***>
Enviado: Monday, December 18, 2023 4:45:18 AM
Para: homebridge/homebridge-config-ui-x ***@***.***>
Cc: Diegoid7 ***@***.***>; Mention ***@***.***>
Asunto: Re: [homebridge/homebridge-config-ui-x] No puedo agregar más accesorios (Issue #1947)


Hola @Diegoid7<https://github.com/Diegoid7>

Since this question is related to the behaviour of a certain plugin, you will need to ask the question on the plugin's GitHub page.

Which plugin are you using for this app?
