### ISSUE TITLE
GitHub Link removed from search results

### ISSUE THREAD

**Issue by davidjbradshaw** [oznu/homebridge-config-ui-x#1950]
### Describe The Bug

I think the new UI is a big step forward, however, now when I do a search for a plugin I no longer see links to GitHub or NPM. In the past this was really useful when presented with several similar plugins, as it allowed you to read about each of them, before deciding which one to go with.

### Homebridge UI Version

4.54.1

### Homebridge Version

1.7

### Node.js Version

20.10

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

4B 4GB

**Comment by bwp91** [comment]
Hi @davidjbradshaw 

The link has moved to the information modal that can be accessed by the `(i)` icon - it is the plugin homepage link.

![Screenshot 2023-12-18 at 19 39 39](https://github.com/homebridge/homebridge-config-ui-x/assets/43026681/a6c889f5-590d-49f7-8bd0-1a1e40347552)
