### ISSUE TITLE
High CPU usage with two specific widgets (Log widget & Network Widget)

### ISSUE THREAD

**Issue by TheEngineerGuy** [oznu/homebridge-config-ui-x#1960]
### Describe The Bug

On my RPi 4, CPU, Memory, Status, uptime, sys info, QR code and Weather widgets combined hit 1% CPU usage, which is quite efficient.

However, the moment I enable Logs widget and network widget, they take additional 5% CPU. I am not sure what is so heavy in these widgets' operations to tax the CPU 5 times as much as all the other widgets combined.

Please see the screen shot below. As a side note, all other widgets (listed above) which have 1% combined CPU usage were active throughout, only log and network widgets were toggled to exhibit this observation.

<img width="805" alt="Screenshot 2023-12-30 at 9 58 04 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/16248146/8be4008e-401d-4a78-ad5b-2e6aedc2c69a">

Let me know if you need any additional info, but I think this should be easy to reproduce.

### Homebridge UI Version

v4.54.1

### Homebridge Version

v1.7.0

### Node.js Version

v20.10.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by TheEngineerGuy** [comment]
Not stale.

**Comment by TheEngineerGuy** [comment]
Still active.

**Comment by TheEngineerGuy** [comment]
Recent GUI updates seem to have reduced the CPU overhead from these widgets. Now the CPU usage with all widgets enabled, (including network and logs), hovers around 2%.

**Comment by bwp91** [comment]
This is awesome to hear 👏
