### ISSUE TITLE
Locking accessory icon in one place.

### ISSUE THREAD

**Issue by WeeMan1990** [oznu/homebridge-config-ui-x#197]
I am currently using this on my main control hub instead of domoticz or any other interface since this uses my homebridge config directly. Lately i have been running it on a 17" touchscreen mounted to a wall in the house. The only problem i have is that when using the touch, it sometimes moves the icons around by accident, does anyone know a way to prevent this from happening? Either by just removing tha function from the code or create a button to lock the icons in place or unlock to move them around?

**Comment by oznu** [comment]
Available in 3.9.3:

![image](https://user-images.githubusercontent.com/3979615/50721074-f0476000-110c-11e9-84bd-7d8eb7482b03.png)

**Comment by WeeMan1990** [comment]
@oznu thank you! Works like a charm and feels really great on the touchscreen! 👍 Before the update when i was going to dim light and had to hold the icons it messed everything up, now it just works!
