### ISSUE TITLE
4.54.3/55.1-alpha UI check state in loop mode

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#1970]
### Describe The Bug

Hi,

The gear on Homebridge widget to check Homebridge UI update is in loop mode, never ending the check.

### Homebridge UI Version

4.54.3-alpha.0
4.55.1-alpha.0

### Homebridge Version

1.7.1-beta.21

### Node.js Version

20

### Operating System

macOS

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
fixed with: `4.55.1-alpha.1`
