### ISSUE TITLE
Error when updating/log

### ISSUE THREAD

**Issue by yepecece** [oznu/homebridge-config-ui-x#198]
I am trying to resolve an error when trying to update or see logs.

It seems it is a user/permission problem but I am not able to find a solution.

I tried these 2 solutions which are very similar to my problem but with no luck:
https://github.com/oznu/homebridge-config-ui-x/issues/106#issuecomment-395956896
https://github.com/oznu/homebridge-config-ui-x/issues/87#issuecomment-385610290

**This is the error I get when updating**
```
USER: homebridge
DIR: /usr/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-webos-tv@latest

sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin

Command failed. Please review log for details
```

**this is the error I get when checking the log**
```
Using systemd to tail logs
CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge

sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin

The log tail command "sudo -n journalctl -o cat -n 500 -f -u homebridge" exited with code 1.
Please check the command in your config.json is correct.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.
```

If I type that log tail command via ssh if works without a problem.

**This is my config**
```
{
   "name": "Config",
   "port": 8080,
   "theme": "red",
   "restart": "sudo -n systemctl restart homebridge",
   "tempUnits": "c",
   "sudo": true,
   "platform": "config",
   "log": {
      "method": "systemd",
      "service": "homebridge"
   }
},
```

I have also activated **Password-less sudo required**

Let me know if you need any other information.

Thanks

**Comment by oznu** [comment]
Try su-ing to your `homebridge` service user and see if you can `sudo` from here without a password. If not you may need to adjust your `sudoers` file to suit your system.

**Comment by yepecece** [comment]
I already added homebridge and pi users to sudoers via visudo.
I also tried running homebridge as pi user and it gives me the same error as running as homebridge user.

I also tried to run as root user just to check and it gives me this error:
```
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

I followed this tutorial to run homebridge at startup:
`https://timleland.com/setup-homebridge-to-start-on-bootup/`

Thanks

**Comment by antagosteenl** [comment]
I've  got the same problem. I think this happens after an apt-get upgrade.
I hop that helps.

**Comment by Desio90** [comment]
Hi yepecece, I solved this error changing the service file of HomeBridge: 

/etc/systemd/system/homebridge.service

the parameter that chenge is "CapabilityBoundingSet".

my file, that working, is:

```
[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge -I $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_NET_RAW CAP_NET_ADMIN CAP_SETUID CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target
```
I hop that helps.

**Comment by oznu** [comment]
Thanks @Desio90, nice work figuring that out.

I'll do some testing / research and if it's all good I'll add a "best practice" systemd service file to the wiki.

**Comment by yepecece** [comment]
Wow.

Thanks @Desio90. Works right away.

**Comment by oznu** [comment]
Thanks again, I've added a guide to the wiki that contains the updated systemd service file.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)

While testing on Ubuntu 18.04 and Raspbian I found I needed to add a few more items to the `CapabilityBoundingSet` list to get all the features working:

`/etc/systemd/system/homebridge.service`:

```shell
[Unit]
Description=Homebridge
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target
```

`/etc/default/homebridge`:

```shell
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/lib/homebridge -I

# If you uncomment the following line, homebridge will log more
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*

# To enable web terminals via homebridge-config-ui-x uncomment the following line
# HOMEBRIDGE_CONFIG_UI_TERMINAL=1
```
