### ISSUE TITLE
Network widget only shows one NIC

### ISSUE THREAD

**Issue by ohmantics** [oznu/homebridge-config-ui-x#1981]
### Feature Description

My Homebridge server is running with both wired and wireless connections, each to a separate network (wired is trusted LAN, wireless is untrusted IoT VLAN, the router is handling bridging mDNS traffic with Avahi). The network widget just shows eth0 traffic.

Two possible UI directions:
1. Allow adding more than one network widget and configuring each widget for which interface
2. Have the network widget show more than one interface in it, either knowing all the interfaces HB is using or allowing it to be configured for which interfaces to show.

**Comment by ohmantics** [comment]
Feature requests should not go stale.

**Comment by ohmantics** [comment]
Feature requests should not get marked stale.

**Comment by bwp91** [comment]
I will initially do some work to be able to select a custom network interface for the graph. 

Can see where this leads

**Comment by ohmantics** [comment]
Feature requests should not be marked stale.

**Comment by ohmantics** [comment]
Stale bots suck.

**Comment by ohmantics** [comment]
Stale bots suck

**Comment by donavanbecker** [comment]
Since no one has picked this feature request up, I am going to close it. If you want to open a PR, feel free too.
