### ISSUE TITLE
latest update displays blank page

### ISSUE THREAD

**Issue by homersdonut** [oznu/homebridge-config-ui-x#1983]
### Describe The Bug

The latest update only displays a blank white page for me now. Nothing at all, whenever there is an update now I’ll have to do it via terminal, because there is literally no UI to speak of.

### Homebridge UI Version

Newest as of todays date

### Homebridge Version

Newest as of todays date

### Node.js Version

Newest as of todays date

### Operating System

macOS

### Environment Info

None

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @homersdonut 

Are you able to check these things to see if any errors are highlighted?

- the homebridge log which you can access via the macos terminal
- the developer tools in your browser when you visit the ui itself?

**Comment by NorthernMan54** [comment]
@bwp91 my thought is that the UI crashed for some reason, and the logs would show why.

@homersdonut could you find the homebridge logs on you Mac and share?

**Comment by homersdonut** [comment]
I can confirm that this is only happening with Safari. It does open fine in Chrome.

**Comment by chungccm** [comment]
After update the homebridge-config-ui-x v4.55.1, 
(In iPhone iOS 13.5) when I use Safari or Chrome to open HomeBridge admin web portal, it will display white blank page. If I use puffin browser in this iPhone, it will display "Error 102 (net::ERR_CONNECTION_REFUSED) when loading URL" 

(In iPhone iOS 15.6 or 15.8) when I use Safari or Chrome to open HomeBridge admin web portal, it will display normally.

As before, homebridge-config-ui-x v4.54.2, no occur this issue.

NodeJS: v20.10.0
HomeBridge v1.7.0
Raspberry Pi 3B+ (using homebridge-raspbian-image v1.1.2)

**Comment by NorthernMan54** [comment]
@chungccm as mentioned earlier logs are needed to triage any further

**Comment by chungccm** [comment]
HomeBridge debug log - (In iPhone iOS 13.5) when I use Safari or Chrome to open HomeBridge admin web portal, it will display white blank page.

{"level":30,"time":1706254670580,"pid":4846,"hostname":"homebridge","reqId":"req-6","req":{"method":"GET","url":"/","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":52562},"msg":"incoming request"}
{"level":30,"time":1706254670589,"pid":4846,"hostname":"homebridge","reqId":"req-6","res":{"statusCode":200},"responseTime":8.092466999776661,"msg":"request completed"}

**Comment by chungccm** [comment]
HomeBridge debug log - when I use Windows Chrome browser to open HomeBridge admin web portal, it will display normally.

{"level":30,"time":1706254757134,"pid":4846,"hostname":"homebridge","reqId":"req-7","req":{"method":"GET","url":"/","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48120},"msg":"incoming request"}
{"level":30,"time":1706254757141,"pid":4846,"hostname":"homebridge","reqId":"req-7","res":{"statusCode":200},"responseTime":6.0071100001223385,"msg":"request completed"}
{"level":30,"time":1706254757175,"pid":4846,"hostname":"homebridge","reqId":"req-8","req":{"method":"GET","url":"/runtime.c196acafeba5625a.js","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48130},"msg":"incoming request"}
{"level":30,"time":1706254757208,"pid":4846,"hostname":"homebridge","reqId":"req-9","req":{"method":"GET","url":"/polyfills.985044b7a7399140.js","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48132},"msg":"incoming request"}
{"level":30,"time":1706254757224,"pid":4846,"hostname":"homebridge","reqId":"req-a","req":{"method":"GET","url":"/main.d9826997f5ab5570.js","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48148},"msg":"incoming request"}
{"level":30,"time":1706254757239,"pid":4846,"hostname":"homebridge","reqId":"req-8","res":{"statusCode":200},"responseTime":60.578348999843,"msg":"request completed"}
{"level":30,"time":1706254757244,"pid":4846,"hostname":"homebridge","reqId":"req-b","req":{"method":"GET","url":"/scripts.a3c9ccae4e478a7d.js","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48156},"msg":"incoming request"}
{"level":30,"time":1706254757255,"pid":4846,"hostname":"homebridge","reqId":"req-9","res":{"statusCode":200},"responseTime":45.41640500025824,"msg":"request completed"}
{"level":30,"time":1706254757260,"pid":4846,"hostname":"homebridge","reqId":"req-c","req":{"method":"GET","url":"/styles.3422f0a086a2d157.css","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48162},"msg":"incoming request"}
{"level":30,"time":1706254757332,"pid":4846,"hostname":"homebridge","reqId":"req-b","res":{"statusCode":200},"responseTime":86.34091599984095,"msg":"request completed"}
{"level":30,"time":1706254757365,"pid":4846,"hostname":"homebridge","reqId":"req-c","res":{"statusCode":200},"responseTime":104.57146700005978,"msg":"request completed"}
{"level":30,"time":1706254757512,"pid":4846,"hostname":"homebridge","reqId":"req-a","res":{"statusCode":200},"responseTime":286.6882370002568,"msg":"request completed"}
{"level":30,"time":1706254757642,"pid":4846,"hostname":"homebridge","reqId":"req-d","req":{"method":"GET","url":"/api/auth/settings","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48164},"msg":"incoming request"}
{"level":30,"time":1706254757650,"pid":4846,"hostname":"homebridge","reqId":"req-d","res":{"statusCode":200},"responseTime":7.022636000066996,"msg":"request completed"}
{"level":30,"time":1706254757667,"pid":4846,"hostname":"homebridge","reqId":"req-e","req":{"method":"GET","url":"/favicon.ico","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48166},"msg":"incoming request"}
{"level":30,"time":1706254757680,"pid":4846,"hostname":"homebridge","reqId":"req-e","res":{"statusCode":200},"responseTime":11.748802999965847,"msg":"request completed"}
{"level":30,"time":1706254757710,"pid":4846,"hostname":"homebridge","reqId":"req-f","req":{"method":"GET","url":"/fa-solid-900.ce4938a30389d90a.woff2","hostname":"192.168.0.28","remoteAddress":"::ffff:127.0.0.1","remotePort":48178},"msg":"incoming request"}
{"level":30,"time":1706254757735,"pid":4846,"hostname":"homebridge","reqId":"req-f","res":{"statusCode":200},"responseTime":23.739223000127822,"msg":"request completed"}
