### ISSUE TITLE
Config.json not saved changes if use very big oneOf function.

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#1987]
### Describe The Bug

The config not save its changes if use very big `oneOf` functions. In my case is 600 objects.
The plugin to test: 
https://github.com/grzegorz914/homebridge-denon-tv

If reduce objects then saved correctly.

Thanks.

### Homebridge UI Version

All versions

### Homebridge Version

All versions

### Node.js Version

20.10

### Operating System

macOS

### Environment Info

{"label"=>"Using hb-service?"}

### Raspberry Pi Model

Other (specify in description)

**Comment by grzegorz914** [comment]
I fixed this in my plugin config.schema by reduce objects count  in `oneOf` but the problem still exist in ConfigUi X.

**Comment by bwp91** [comment]
Hi @grzegorz914 is this something that I could reproduce myself, if I could install your plugin could you attach to this ticket an example config that I could use?

**Comment by grzegorz914** [comment]
Please instal version 4.7.0  because 4.8.0 contain temporary workaround for this issue. After install it try to create / change some buttons using UI. The UI will not save the changes.

**Comment by coryabooth** [comment]
Is this related to the "Accessories" tab and not saving the layout of rooms and accessories?
