### ISSUE TITLE
Homebridge not responding in HomeKit after update UI to 4.55.1

### ISSUE THREAD

**Issue by MarkM500** [oznu/homebridge-config-ui-x#1988]
### Current Situation

Hi together,
updated my Homebridge v1.7.0 to UI v4.55.1 (node.js v18.18.2). After that all bridges from homebridge do no responding in HomeKit . No errors in the log of homebridge.
node.js: Homebridge is running on synolgy DS415+ with DSM7.1. Update node.js to v20 is only possible with DSM7.2. Not possible with DS415+.
Can anyone help me? Thanks

### Homebridge UI Version

4.55.1

### Homebridge Version

1.70

### Node.js Version

18.18.2

### Operating System

Synology DSM

### Environment Info

None

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
With no logs and with it looking like Homebridge is running, this must be a network issue

**Comment by MarkM500** [comment]
Thanks a lot for the hint. It was a problem with the fritz.box.
