### ISSUE TITLE
Tooltips vanish immediately after they popup

### ISSUE THREAD

**Issue by jamieburchell** [oznu/homebridge-config-ui-x#1992]
### Describe The Bug

Tapping the small info "i" icon shows the tooltip but then the tooltip disappears before you can read it. Example in Settings > Network > mDNS Resolver.

iOS 17.2.1 / Safari

### Homebridge UI Version

4.55.1

### Homebridge Version

1.7.0

### Node.js Version

20.11.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 1 B

**Comment by jamieburchell** [comment]
Not stale

**Comment by bwp91** [comment]
Hi @jamieburchell 

In fact I just so happened to remove some of these tooltips in the beta version of the UI. Perhaps you can give it a try!

**Comment by bwp91** [comment]
This should be fixed in the new releases of the UI.
