### ISSUE TITLE
Password autofill on login not working in Safari for iOS

### ISSUE THREAD

**Issue by josemmc95** [oznu/homebridge-config-ui-x#1996]
### Describe The Bug

Title says it all.

when using Safari for iOS, it doesn’t give you the option to autofill the saved username and password from keychain.

it works well on macOS.

### Homebridge UI Version

1.7.0

### Homebridge Version

4.55.1

### Node.js Version

20.11.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by jackklink** [comment]
May I ask why Safari Autofill doesn't work on Homebridge's login screen? It doesn't work on Mac or iOS. I use safari to store high security passwords and my homebridge password is not something memorable. I need to autofill it every time. For the past year or so, I've been having to go to the Passwords app to find the password manually every time I login to Homebridge. Homebridge is the only website/app in my life that doesn't support autofill. Is the issue on your end or Apple's end?
