### ISSUE TITLE
Plugin status on homepage 

### ISSUE THREAD

**Issue by benfysh** [oznu/homebridge-config-ui-x#200]
Hi, is it possible to add an overall plugin status to the homepage next to the one for Homebridge? It would be easier to see at a glance if any plugins required an update. Thanks

**Comment by oznu** [comment]
Done in 4.2.0

**Comment by benfysh** [comment]
Thanks for adding this. The label ID  as opposed to text is showing for me?
<img width="1218" alt="Screenshot 2019-05-03 at 15 43 24" src="https://user-images.githubusercontent.com/404201/57150190-8773aa00-6dc5-11e9-881e-16de038d0071.png">

**Comment by oznu** [comment]
@benfysh - it may have cached the en.json; try a hard refresh.

**Comment by benfysh** [comment]
Yeah that was it, thought I already had. Thanks again
