### ISSUE TITLE
Zigbee and Zwave servers + Node Red + Camera

### ISSUE THREAD

**Issue by mkz212** [oznu/homebridge-config-ui-x#2000]
### Describe The Bug

@donavanbecker @bwp91 @NorthernMan54 

Are Homebridge and Homebridge UI abandoned projects?

Nothing has been happening for some time:
- no new updates
- new PRs not merged
- you do not respond to reported errors

I realize that this is a big project and I see that only a few people really contribute to develop it. Maybe it's time to change it somehow, improve this process?

Unfortunately, I also have the impression that a similar phenomenon applies to many plugins - have simply been abandoned.

### Homebridge UI Version

4.55.2-beta.15

### Homebridge Version

1.7.0

### Node.js Version

20

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by mkz212** [comment]
Oh, I just hit and my thread has a round number - 2000 🥳

**Comment by NorthernMan54** [comment]
@mkz212 personally I’m on a a few month vacation so have limited access to GitHub etc.  so my contributions will be minimal for the near future.

but when you look at homebridge itself, the code base is mature, and Apple has not released anything recently triggering us too make updates.  And that is what you’re seeing.

With plugins as they are community developed and supported by the individual developer. So they are a mixed bag.  With the Verified program we are attempting to restrict the verified flag to only those with support so they should be better.

**Comment by mkz212** [comment]
@NorthernMan54 

Thanks for the reply. I was worried that the project had been abandoned.

As for what you write that Apple has not changed too much lately, it's a fact. That a lot is expected to change with the next release.

As for the development of Homebridge and Homebridge UI itself, I think it has a lot of untapped potential and it is easy to fix it:
- Zigbee2mqtt server should be as easy to install as deConz / Phoscon (just open hb-config, go to Extra Packages and select Instal deConz), or even should be pre-installed in Raspbian Image
- the same should be an easily accessible Z-wave server
- the same Node-Red automations
- the same Camera UI
- These 4 servers should have their links in the Homebridge menu

**Comment by NorthernMan54** [comment]
As the developer of the integration to node-red, I feel strongly about the power of node-red automations.  But is your average Homebridge user prepared to leverage it effectively ?

PS My home is esp based with a mix of tasmota and other devices, so Zigbee and Z-Wave are not a personal priority, but it may be for others?

**Comment by mkz212** [comment]
Installing the deConz server is fabulously simple, but this server is very basic and works only with ConBee stick. 

I think that the installation of Zigbee2mqtt server, Zwave server, Node Red and Camera UI should be just as simple or even they should be pre-installed. Then everyone will decide whether they want to use them. Of course, a suitable USB stick is required for Zigbee and Zwave. 

In Home Assistant, enabling these servers is literally 1 click And I think it's the biggest (and only) advantage of Home Assistant over Homebridge - when you enter a "one hub to everything" phrase in the search engine, Home Assistant pops up.

**Comment by mkz212** [comment]
I think Homebridge's essence is to provide support for:
- cameras that do not support HSV (Camera UI)
- creating virtual switches for automation purposes in Apple Home (Dummy Switch or Delay Switch)
- Integration of plugins running via WiFi or in the cloud (plugins)
- Adding Zigbee devices (including Matter and Thread) (Zigbee2mqtt)
- Adding Zwave devices

With all this, Homebridge would be the best and most powerful hub. 

P.S.: Not everyone knows but for example Hub Aqara only supports Aqara devices, etc. It is not that every Zigbee device works with every hub - that's why Zigbee2mqtt is so good because it supports different manufacturers.

**Comment by hjdhjd** [comment]
> @NorthernMan54
> 
> Thanks for the reply. I was worried that the project had been abandoned.
> 
> As for what you write that Apple has not changed too much lately, it's a fact. That a lot is expected to change with the next release.
> 
> As for the development of Homebridge and Homebridge UI itself, I think it has a lot of untapped potential and it is easy to fix it:
> 
> * Zigbee2mqtt server should be as easy to install as deConz / Phoscon (just open hb-config, go to Extra Packages and select Instal deConz), or even should be pre-installed in Raspbian Image
> * the same should be an easily accessible Z-wave server
> * the same Node-Red automations
> * the same Camera UI
> * These 4 servers should have their links in the Homebridge menu

No, they shouldn't. They're arbitrary selections. Leave each project to do what it does best. You never know what other projects choose to do, or not, or evolve, or not. If someone wants to create a meta FAQ or wiki, terrific. But this instinct of "change for change's sake" and "links just because some find it useful" is the path to cruft and UI/UX/documentation confusion.

Keep it simple. 😄

That's what's made this project successful, the unix movement successful, and is good governance.

**Comment by mkz212** [comment]
> > @NorthernMan54
> > Thanks for the reply. I was worried that the project had been abandoned.
> > As for what you write that Apple has not changed too much lately, it's a fact. That a lot is expected to change with the next release.
> > As for the development of Homebridge and Homebridge UI itself, I think it has a lot of untapped potential and it is easy to fix it:
> > 
> > * Zigbee2mqtt server should be as easy to install as deConz / Phoscon (just open hb-config, go to Extra Packages and select Instal deConz), or even should be pre-installed in Raspbian Image
> > * the same should be an easily accessible Z-wave server
> > * the same Node-Red automations
> > * the same Camera UI
> > * These 4 servers should have their links in the Homebridge menu
> 
> No, they shouldn't. They're arbitrary selections. Leave each project to do what it does best. You never know what other projects choose to do, or not, or evolve, or not. If someone wants to create a meta FAQ or wiki, terrific. But this instinct of "change for change's sake" and "links just because some find it useful" is the path to cruft and UI/UX/documentation confusion.
> 
> Keep it simple. 😄
> 
> That's what's made this project successful, the unix movement successful, and is good governance.

After all, I haven't written anywhere about combining it into one big project. Each server would be separate as it is now but:
- easy to start / install
- in Homebridge UI, a link to each server (only for these enabled), the link, not iframe, not implementing server into Homebridge UI etc., only link.

**Comment by hjdhjd** [comment]
I didn't write that you advocated combing it all into one project. 

I did write that we should not be linking to any other project. And I maintain the position that I wrote.

If you're advocating (which I understand you are) that there be links to other projects from Homebridge (either the site, or the webUI), as I've stated above: no. Again - you may think this is a helpful addition, but I do not. It is counterproductive and an unnecessary distraction for the development team to maintain. This type of stuff belongs with a passionate individual(s) who want to maintain a meta-FAQ or HOWTO. Not links in the software we maintain and document.

**Comment by mkz212** [comment]
> I didn't write that you advocated combing it all into one project.
> 
> I did write that we should not be linking to any other project. And I maintain the position that I wrote.
> 
> If you're advocating (which I understand you are) that there be links to other projects from Homebridge (either the site, or the webUI), as I've stated above: no. Again - you may think this is a helpful addition, but I do not. It is counterproductive and an unnecessary distraction for the development team to maintain. This type of stuff belongs with a passionate individual(s) who want to maintain a meta-FAQ or HOWTO. Not links in the software we maintain and document.

But you will surely agree that easy installation of these servers would not hurt anyone? By easy installation I mean E.G. dedicated one simple command in the terminal. Then everyone will easily launch what they want and need.

**Comment by hjdhjd** [comment]
I do not agree. Easy installation of Homebridge - which already exists in multiple forms - is the North Star. You can install an RPi image, you can install via NPM, and you can install via preexisting repos that we maintain. That's more the sufficient and already covers the overwhelming majority of the community.
