### ISSUE TITLE
A new Japanese translation file

### ISSUE THREAD

**Issue by yima0913** [oznu/homebridge-config-ui-x#2005]
### Feature Description

Hi! I am Japanese and use Homebridge. I have created a fully supported Japanese file to make it even easier for Japanese to use. Please take advantage of it!
[ja.json](https://github.com/homebridge/homebridge-config-ui-x/files/14269189/ja.json)

**Comment by bwp91** [comment]
Hi @yima0913 

thanks a lot for taking the time to write this file out!

I have added this file into the beta version of the UI in this commit:
https://github.com/homebridge/homebridge-config-ui-x/pull/1980/commits/11d8b4f97bf0ee546b80268c8b4f0a50284b615b

and is now available with the most recent beta version of the UI, and will be included in the next stable release of the UI!
