### ISSUE TITLE
Can't add my first accessory to Homebridge

### ISSUE THREAD

**Issue by hayesmccarty** [oznu/homebridge-config-ui-x#2010]
### Current Situation

Downloaded Homebridge on my iMac and tried to add both the ring and ADT accessories.  In both instances I got an error message 243 and an error EACCES.  Please help.  I am not a coder and can't understand what to do next.  I have searched all the help and support files on the Homebridge site but can't find any answers.  

### Logs

USER: hayesmccarty
DIR: /usr/local
CMD: npm install -g homebridge-ring@12.1.0

npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/hayesmccarty/.npm/_cacache/tmp/199dbfe0
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/hayesmccarty/.npm"

npm ERR! A complete log of this run can be found in: /Users/hayesmccarty/.npm/_logs/2024-02-19T19_08_01_655Z-debug-0.log

Operation failed with code 243.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

### Homebridge UI Version

v4.55.1

### Homebridge Version

v1.7.0

### Node.js Version

v18.0

### Operating System

macOS

### Environment Info

None

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Did you try 

 sudo chown -R 501:20 "/Users/hayesmccarty/.npm"

**Comment by hayesmccarty** [comment]
Thanks so much for getting back to me.  I did that and I think it is now working.  I am away from my home now but will follow up and let you know that it works.  Really appreciate your follow up!Hayes McCarty(703) 819-7777On Feb 19, 2024, at 7:40 PM, Northern Man ***@***.***> wrote:﻿
Did you try
sudo chown -R 501:20 "/Users/hayesmccarty/.npm"

**Comment by hayesmccarty** [comment]
I want to thank you so much for your help.  Every time you give me a suggestion, I get a little closer to getting it to work.  As you recall I am running Homebridge on my iMac.  I have downloaded Homebridge, added several plug-in accessories (Ring, ADT, Carrier infinity), I have run the plugin config, manage versions on each one and have logged in with my user name and password.  Then when trying to + Add Accessory to my HomeKit on my iPhone I get the following two screens.  The first telling me my accessory needs to be powered on and connected by ethernet cable.  My computer is powered on and connected to he router by ethernet but none of the 3 accessories that I am trying to add can be connected to the router by ethernet as they are wireless.  Then I get the final message saying I need to restart my accessory.  I have  restarted my computer and phone as well as my ring camera and the art server but ti doesn’t help.

When I go to accessories on my computer in Homebridge, I do see a number of badges showing my Carrier infinity heating system but still none of this can get transferred to HomeKit on my phone.

Thanks in advance for any help you can give me.

Hayes McCarty
703-819-7777

￼￼￼
