### ISSUE TITLE
unable to find plugin

### ISSUE THREAD

**Issue by cristianpilot** [oznu/homebridge-config-ui-x#2019]
### Current Situation

Good morning. I got this error in my home bridge
Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help
I can not look for any plugin as well. any help?

Regards 

Cristian 

### Homebridge UI Version

4.55.1

### Homebridge Version

1.7.0

### Node.js Version

18.13.0

### Operating System

QNAP

### Environment Info

{"label"=>"Using Docker?"}

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Looks like an issue from your container connecting to the internet - Did you look at this ? https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting#npm-registry-issues

**Comment by cristianpilot** [comment]
thanks. looks like is a DNS problem. Any help in how change DNS inside container? Thanks in advance

**Comment by cristianpilot** [comment]
fixed. thanks a million for the help!

Regards
