### ISSUE TITLE
Backup won't run…

### ISSUE THREAD

**Issue by albi** [oznu/homebridge-config-ui-x#2021]
### Describe The Bug

Unfortunately, the Homebridge backup is not running. The path I specified exists but no backups are created there. It is an external drive that is correctly mounted as other services backup there too.

<img width="731" alt="Bildschirmfoto 2024-03-16 um 13 19 33" src="https://github.com/homebridge/homebridge-config-ui-x/assets/89451/78403f30-3c2a-496b-9632-26122309408f">

<img width="375" alt="Bildschirmfoto 2024-03-16 um 13 25 35" src="https://github.com/homebridge/homebridge-config-ui-x/assets/89451/9d69c4cc-537d-4899-b34a-bd4b0f6a09dc">

### Logs

[16/03/2024, 00:31:49] [Homebridge UI] Could not run scheduled backup: Custom instance backup path is not writable / readable by service: EACCES: permission denied, access '/media/pi/Pi-Data/Backups/Homebridge'

### Homebridge UI Version

latest

### Homebridge Version

latest

### Node.js Version

latest

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by NorthernMan54** [comment]
The error / problem is here - [16/03/2024, 00:31:49] [Homebridge UI] Could not run scheduled backup: Custom instance backup path is not writable / readable by service: EACCES: permission denied, access '/media/pi/Pi-Data/Backups/Homebridge'


You need to change ownership of the directory to the user account that is running the homebridge process.   Current ownership is root based on your directory listing.

**Comment by albi** [comment]
you're right
