### ISSUE TITLE
Consider zajsf fork for plugin layout

### ISSUE THREAD

**Issue by drewcovi** [oznu/homebridge-config-ui-x#2022]
### Feature Description

Is there any way we might consider moving off of [ajsf](https://github.com/hamzahamidi/ajsf) for plugin layout support? We're unable to nest arrays and have the results show up unless we abandon the "layout" option available in ajsf (https://github.com/hamzahamidi/ajsf/issues/144). It does appear that this fork is more up-to-date and has been applying various patches to make our lives better [zahmo/zajsf](https://github.com/zahmo/zajsf). Thanks to @zahmo for picking this one up.

**Comment by bwp91** [comment]
I think i have updated to this fork in the alpha version of the UI as part of an overall update of angular and bootstrap.

The alpha is obviously a work in progress but is pretty usable (there are some styles that still need work)

**Comment by drewcovi** [comment]
love to see that. looks like oznu forked ajsf awhile back, and the alpha is pulling in zajsf/core which would go a long way!

i guess I'll hang tight then, since updating my plugin won't matter till this fix rolls out to the public :)
