### ISSUE TITLE
How to add custom logo for plugin

### ISSUE THREAD

**Issue by carlosgamezvillegas** [oznu/homebridge-config-ui-x#2023]
### Current Situation

I have noticed that Raspberry Pi and Nest Camera plugins have custom logos on the left hand side of the plugin name (please see picture attach). Is there a way that I can add a custom logo to my plugins? if so, How can I do that?

<img width="662" alt="image" src="https://github.com/homebridge/homebridge-config-ui-x/assets/67111609/1cbc2665-ab40-4d6a-91b3-0b74ee25a1d4">

Thank you,

### Homebridge UI Version

v4.55.1

### Homebridge Version

v1.7.0

### Node.js Version

 v16.20.2

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

{"label"=>"Using hb-service?"}

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi @carlosgamezvillegas 

See the `Request Plugin Icon` issue template on the verified repo:

https://github.com/homebridge/verified/issues/new/choose
