### ISSUE TITLE
Unable to uninstall a plugin

### ISSUE THREAD

**Issue by HGordonH** [oznu/homebridge-config-ui-x#2024]
### Describe The Bug

The ‘Weather Plus’ plugin broke for me some time ago and does not run and cannot be upgraded. I am unable to uninstall the plugin and the authors of the plugin has directed me to Homebridge as they say they do not recognise the errors as something related to the plugin.

Raspbian GNU/Linux Buster (10)

### Logs

USER: homebridge
DIR: /usr
CMD: sudo -E -n npm uninstall -g homebridge-weather-plus
[?25l
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠇ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed in 27ms

[?25h
npm
 ERR!
 code ENOTEMPTY
npm ERR!
syscall rename
npm
ERR!
 path /usr/lib/node_modules/homebridge-weather-plus
npm ERR!
dest /usr/lib/node_modules/.homebridge-weather-plus-RCH9Us1A
npm ERR! errno
 -39
npm
ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-weather-plus' -> '/usr/lib/node_modules/.homebridge-weather-plus-RCH9Us1A'
npm ERR! A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-03-20T20_02_30_697Z-debug-0.log

Operation failed with code 217.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

### Homebridge UI Version

4.55.1

### Homebridge Version

1.7.0

### Node.js Version

18.19.1

### Operating System

Other (specify in description)

### Environment Info

{"label"=>"Using hb-service?"}

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi @HGordonH 

Try running this from the Homebridge terminal:

```sh
sudo rm -rf /usr/lib/node_modules/.homebridge-weather-plus-RCH9Us1A
```

and then trying again to uninstall the plugin

**Comment by HGordonH** [comment]
That works !!Many thanks for your help.RegardsGordon On 30 Mar 2024, at 13:49, Ben ***@***.***> wrote:﻿
Hi @HGordonH
Try running this from the Homebridge terminal:
sudo rm -rf /usr/lib/node_modules/.homebridge-weather-plus-RCH9Us1A
and then trying again to uninstall the plugin
