### ISSUE TITLE
All Devices - No Response

### ISSUE THREAD

**Issue by coryabooth** [oznu/homebridge-config-ui-x#2027]
### Describe The Bug

Lastnight 3/27/2024 10pm CST - I noticed that none of my devices hosted by HomeBridge show as responsive in Apple home.
Devices with direct connection (Ecobee) and devices with a different bridge (RATGD and Scrypted) do still show and are responsive.

Initially, when I loaded the Web UI none of my "SmartThings" devices where showing - several reboots later and I finally got the HomeBridge UI back to normal.

The Accessories tab in HomeBridge does show all my devices and they are controllable:

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/5266177/8cd9b8a9-4f29-4996-b29c-f4b339ad3c23)

However, on the Home App - none of the devices show as "Responsive"
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/5266177/42318fae-b308-403d-b28f-f37d482c6b41)

I have had this configuration - with no changes - for over a year now...
This just suddenly happened with no traceable reason...

I have five plugins - none of the devices exposed by these plugins are responsive in HomeKit - but they are in HomeBridge.

### Homebridge UI Version

4.55.1

### Homebridge Version

1.7.0

### Node.js Version

20.12.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi @coryabooth , closing this as I believe this is the same issue as https://github.com/homebridge/homebridge/issues/3582

If I am mistaken the please feel free to re-open!

**Comment by coryabooth** [comment]
This was fixed by:

Disabling IGMP Snooping
Disabling Multicast and Broadcast Control
