### ISSUE TITLE
Operation failed with code 243

### ISSUE THREAD

**Issue by Berger1983-has** [oznu/homebridge-config-ui-x#2028]
### Describe The Bug

USER: andreasberger
DIR: /usr/local
CMD: npm install -g homebridge-deebot@6.1.1
[?25l
[..................] \ idealTree:lib: sill idealTree buildDeps
[..................] \ idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps
[..................] / idealTree:lib: sill idealTree buildDeps

[?25h
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/andreasberger/.npm/_cacache/tmp/fa790b1b
npm
ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/andreasberger/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /Users/andreasberger/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

Operation failed with code 243.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

### Homebridge UI Version

v4.55.1

### Homebridge Version

Homebridge v1.7.0

### Node.js Version

v20.12.0

### Operating System

macOS

### Environment Info

{"label"=>"Using hb-service?"}

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
try deleting this folder `/Users/andreasberger/.npm` and then trying this installation again.

**Comment by Lukeneedshelp** [comment]
I am having the same issue but am very new to any of this. Can you help me with error code 243?

**Comment by cohen-sydney** [comment]
I am having the same issue, any fix??

**Comment by NikoMuffin** [comment]
> try deleting this folder `/Users/andreasberger/.npm` and then trying this installation again.



Wanted to tell anyone seeing this, that this comment helped solve my code 243 error after trying to reinstall homebridge

**Comment by lyleberman** [comment]
> try deleting this folder `/Users/andreasberger/.npm` and then trying this installation again.

Worked for me too! Thx!

**Comment by dulrich85** [comment]
how can I deleting this folder?
