### ISSUE TITLE
Can‘t Update Node - Download Error

### ISSUE THREAD

**Issue by Kohle81** [oznu/homebridge-config-ui-x#2029]
### Describe The Bug

If I want to update Node with „sudo hb-config“ node could not updated because download error.

### Logs

Updating Node.js to LTS, please wait...
Installed: v20.10.0
Current Node.js LTS: v20.12.0
Updating Node.js to v20.12.0...
Downloading to /tmp/tmp.PvRJx5pT9V/node-v20.12.0-linux-armv6l.tar.gz ...
curl: (22) The requested URL returned error: 404 Not Found

Failed to download node-v20.12.0-linux-armv6l.tar.gz. See logs above.

### Homebridge UI Version

4.55.1

### Homebridge Version

1.7.0

### Node.js Version

20.10.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

{"label"=>"Using hb-service?"}

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
How did you install your existing version v20.10.0?

**Comment by Kohle81** [comment]
Actually always via sudo hb-config….But it could be that I installed this version manually as an exception, I'm not quite sure anymoreAm 31.03.2024 um 12:08 schrieb Ben ***@***.***>:﻿
How did you install your existing version v20.10.0?

**Comment by Kohle81** [comment]
I had to uninstall und reinstall config-ui:„ sudo npm install -g --unsafe-perm homebridge-config-ui-x“It could be that I used:sudo hb-service update-node 20.10.0 to update node…..If I used this command I could install node 20.12.0……Am 31.03.2024 um 20:13 schrieb Manuel Kohler ***@***.***>:﻿Actually always via sudo hb-config….But it could be that I installed this version manually as an exception, I'm not quite sure anymoreAm 31.03.2024 um 12:08 schrieb Ben ***@***.***>:﻿
How did you install your existing version v20.10.0?

**Comment by bwp91** [comment]
So just to confirm, the steps to resolve (i.e. install node 20.12.0) were to reinstall the UI

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

and then the usual command worked?

```
sudo hb-service update-node 20.12.0
```

**Comment by Kohle81** [comment]
Hi,
I can‘t update node about

„ sudo hb-config“

But if I used the command

„ sudo hb-service update-node 20.12.0“ it worked.

I doesn‘t reinstalled the UI - should I?

Greetings….

**Comment by bwp91** [comment]
Ah I understand now. No you don't need to reinstall the UI.

Using `hb-service` is the recommended way to update node:
- https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js/

So great that `sudo hb-service update-node 20.12.0` worked for you.

I will close this issue now as I assume resolved. Feel free to re-open if needed 👍

**Comment by Kohle81** [comment]
Hello, unfortunately it's me again with the same problem...

I wanted to update node via the menu using sudo hb-config and again received the error during the download. The command sudo hb-service update-node 20.12.1 worked again.


pi@homebridge:~ $ sudo hb-config
Updating Node.js to LTS, please wait...
Installed: v20.12.0
Current Node.js LTS: v20.12.1
Updating Node.js to v20.12.1...
Downloading to /tmp/tmp.gmmfQ1MKzW/node-v20.12.1-linux-armv6l.tar.gz ...
curl: (22) The requested URL returned error: 404 Not Found

Failed to download node-v20.12.1-linux-armv6l.tar.gz. See logs above.
pi@homebridge:~ $ sudo hb-service update-node 20.12.1
ℹ Installing Node.js v20.12.1 over v20.12.0...
ℹ Target: /usr/local
✔ Download complete.✔ Cleaned up npm at at /usr/local/lib/node_modules/npm
✔ Installed Node.js v20.12.1
ℹ Restarting Homebridge Service...
✔ Homebridge Restarted

**Comment by maximumcollins** [comment]
Just chiming in to say I was having this problem and running:

"sudo hb-service update-node 22.12.0"

made it work! thanks!

**Comment by jamieburchell** [comment]
Same here @bwp91 but the suggested fix doesn't work either

 sudo hb-config
ℹ Updating Node.js from v20.15.1 to v22.12.0...
ℹ Target: /opt/homebridge
✖ Request failed with status code 404

sudo hb-service update-node 22.12.0
ℹ Installing Node.js v22.12.0 over v20.15.1...
ℹ Target: /opt/homebridge
✖ Request failed with status code 404

**Comment by Kohle81** [comment]
Perhaps trysudo hb-service update-node 22.12.0Am 24.12.2024 um 15:51 schrieb Jamie Burchell ***@***.***>:﻿
Same here:
sudo hb-config
ℹ Updating Node.js from v20.15.1 to v22.12.0...
ℹ Target: /opt/homebridge
✖ Request failed with status code 404

**Comment by jamieburchell** [comment]
@Kohle81 Doesn't work unfortunately.

**Comment by NorthernMan54** [comment]
@jamieburchell Does the error message include the failed url ?   Is there a possibility your RPI or OS is too old, and not able to update anymore ?

**Comment by jamieburchell** [comment]
@NorthernMan54 The output I pasted is all I see. Possibly an age thing, it's a Pi Model B. Otherwise works perfectly though but I see this project is dropping support for it.
