### ISSUE TITLE
Update from 4.55.1 to 4.56.0 fails with an error.

### ISSUE THREAD

**Issue by roe1974** [oznu/homebridge-config-ui-x#2032]
### Describe The Bug

An update from 4.55.1 fails with an error (see log)

### Logs

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

### Homebridge UI Version

4.55.1

### Homebridge Version

1.7.0

### Node.js Version

18.20.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

Using systemd

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Please install git on your raspberry pi using this command from the homebridge terminal:

```
sudo apt install git
```

Once this has finished, try the upgrade again

**Comment by roe1974** [comment]
That was it :-) ... Thank you very much !
greetings Richard

**Comment by muzzymate** [comment]
Getting the same issue on a Windows install of Homebridge following instructions at URL below. Attempted to install git by running "npm install -g git" and tried  "npm install git" after still receiving the same error.

Can not seem to get past this error. 

`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

**Comment by bwp91** [comment]
> Getting the same issue on a Windows install of Homebridge following instructions at URL below. Attempted to install git by running "npm install -g git" and tried "npm install git" after still receiving the same error.
> 
> Can not seem to get past this error.
> 
> `npm ERR! code ENOENT npm ERR! syscall spawn git npm ERR! path git npm ERR! errno -4058 npm ERR! enoent An unknown git error occurred npm ERR! enoent This is related to npm not being able to find a file. npm ERR! enoent`
> 
> https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

For Windows install git with this method:
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10#git

**Comment by muzzymate** [comment]
Thank you! That did it. Didn't notice that section got added. Appreciate it!
