### ISSUE TITLE
npm ERR! errno -4058

### ISSUE THREAD

**Issue by mikellas1983** [oznu/homebridge-config-ui-x#2033]
### Current Situation

Trying to upgrade config-ui-x from  v4.55.1 → v4.56.0 i get below error

### Logs

411 verbose stack Error: An unknown git error occurred
1411 verbose stack     at makeError (C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
1411 verbose stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
1411 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1412 verbose cwd C:\WINDOWS\system32
1413 verbose Windows_NT 10.0.22000
1414 verbose node v18.18.0
1415 verbose npm  v10.5.0
1416 error code ENOENT
1417 error syscall spawn git
1418 error path git
1419 error errno -4058
1420 error enoent An unknown git error occurred
1421 error enoent This is related to npm not being able to find a file.
1421 error enoent
1422 verbose exit -4058
1423 timing npm Completed in 43884ms
1424 verbose unfinished npm timer reify 1712157429438
1425 verbose unfinished npm timer reify:loadTrees 1712157429447
1426 verbose code -4058
1427 error A complete log of this run can be found in: C:\Users\Nicolas Server\AppData\Local\npm-cache\_logs\2024-04-03T15_17_08_852Z-debug-0.log

### Homebridge UI Version

v4.55.1

### Homebridge Version

1.7.0

### Node.js Version

v18.18.0

### Operating System

Windows 11

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Please see https://github.com/homebridge/homebridge-config-ui-x/issues/2032#issuecomment-2034904361

**Comment by mikellas1983** [comment]
Thanks @bwp91 !After restarting the pc  this worked pefectly!
