### ISSUE TITLE
Homebridge still loading at UI

### ISSUE THREAD

**Issue by hlong0712** [oznu/homebridge-config-ui-x#2037]
### Describe The Bug

Homebridge still loading at UI
![Screenshot 2024-04-05 114949](https://github.com/homebridge/homebridge-config-ui-x/assets/70058073/244b3024-536d-4386-a4ea-313d7277284d)

### Homebridge UI Version

Homebridge UI v4.55.1

### Homebridge Version

Homebridge v1.7.0

### Node.js Version

v18.19.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

None

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @hlong0712 is this still an issue?

**Comment by hlong0712** [comment]
When i change to chrome it normal now. Something wrong with edge
