### ISSUE TITLE
Delay at the measurements of ram and cpu

### ISSUE THREAD

**Issue by HackyPaddy** [oznu/homebridge-config-ui-x#2038]
### Describe The Bug

Hello,

with the update to 4.56.1 the measurements from the start page / dashboard are delayed. In previous version the loads are very exactly and fast.

Now, is very slow and inaccurate. Load injections are no longer displayed.

The refresh rate needs to be set high again.

Greetings

Patrick

### Homebridge UI Version

4.56.1

### Homebridge Version

1.7.0

### Node.js Version

18.19.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by bwp91** [comment]
Hi @HackyPaddy can you try the beta version of the UI? see if this has improved? there are options in the widget settings to set the refresh rate of each 'graph' widget
