### ISSUE TITLE
Homebridge status stays starting

### ISSUE THREAD

**Issue by arp013** [oznu/homebridge-config-ui-x#2044]
### Describe The Bug

![IMG_4173](https://github.com/homebridge/homebridge-config-ui-x/assets/61652669/61d34aa6-8b44-4b60-a1a8-34c026670e13)
![IMG_4174](https://github.com/homebridge/homebridge-config-ui-x/assets/61652669/7e6db35d-59d7-41d4-be84-9d41204546df)

### Homebridge UI Version

Latest

### Homebridge Version

Latest

### Node.js Version

20.10

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
Looks like your Hue plugin is having a hard time connecting to your hue bridge. Resolve that and it will resolve the status.

**Comment by arp013** [comment]
> Looks like your Hue plugin is having a hard time connecting to your hue bridge. Resolve that and it will resolve the status.

Solved the IP adress was changed
