### ISSUE TITLE
Accessoires from homebridge not responding in apple homekit

### ISSUE THREAD

**Issue by arp013** [oznu/homebridge-config-ui-x#2045]
### Current Situation

![IMG_4176](https://github.com/homebridge/homebridge-config-ui-x/assets/61652669/8028e715-f82e-49e1-92ab-a78f58e9a35d)
Accessoires are working in homebridge but not responding in apple homekit

### Homebridge UI Version

Latest

### Homebridge Version

Latest

### Node.js Version

20_10

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by NorthernMan54** [comment]
A couple more details would be appreciated

ie new installation or other recent changes

Also any changes to your network recently ?

**Comment by arp013** [comment]
Recently had to do a hard reset off the router, have had yo remove the home bridge hub from apple home kit and re added it. After that moment this is the status everything works in homebridge but in apple homekit the are added but not responding

**Comment by bwp91** [comment]
Which mdns advertiser are you currently using?

![Screenshot 2024-04-19 at 23 42 28](https://github.com/homebridge/homebridge-config-ui-x/assets/43026681/3116552d-e2fb-4bd4-839a-81969e32ce47)

**Comment by bguscott** [comment]
Same issue here after updating to v18. Using avahi for mDNS.

**Comment by arp013** [comment]
![IMG_4177](https://github.com/homebridge/homebridge-config-ui-x/assets/61652669/29930b6e-f2bd-4bab-9b96-3dbea423e85d)
At this moment ciao but have tried all the others

**Comment by arp013** [comment]
![IMG_4178](https://github.com/homebridge/homebridge-config-ui-x/assets/61652669/31baa31f-3333-4e6a-9178-b2f916beee14)
With dns discovery it shows up but homebridge.local is not working

**Comment by bguscott** [comment]
I just noticed after the update to homebridge v1.8 I was getting the following error:
`The selected advertiser, "avahi", isn't available on this platform. Reverting to "bonjour-hap"`

Installing avahi directly on my ubuntu host cleared up the error but doesn't seem to have helped with not seeing my devices though.

**Comment by arp013** [comment]
Changed to Ciao everything works again
