### ISSUE TITLE
No access from mobile devices

### ISSUE THREAD

**Issue by gruntoff** [oznu/homebridge-config-ui-x#205]
Can't access UI from mobile devices. Both Android and iOS, different browsers, though desktop is fine. No logs in debug mode while connecting.
![photo_2019-01-25 14 28 03](https://user-images.githubusercontent.com/16617167/51743353-753eed00-20ad-11e9-96b3-7686fbe24ae8.jpeg)
![photo_2019-01-25 14 28 06](https://user-images.githubusercontent.com/16617167/51743354-753eed00-20ad-11e9-9a3c-66379309c659.jpeg)

**Comment by gruntoff** [comment]
Figured out I can't ping raspberry pi from mobile devices and can't access local web server. And still everything is okay on desktop

**Comment by oznu** [comment]
Hi @gruntoff,

This is probably a firewall/networking issue not related to this plugin. Do your mobile devices connect  to the same network as your desktop?

**Comment by gruntoff** [comment]
Sometimes it worked. I figured it out eventually. It was crappy router
