### ISSUE TITLE
no child bridge govee

### ISSUE THREAD

**Issue by jhayarr1562** [oznu/homebridge-config-ui-x#2052]
### Current Situation

I configured my govee plugin. The accessories show up but not the child bridge setup. I have various plugins with bridges connected, but the govee plugin doesn't. Help?

### Homebridge UI Version

v. 4.55.1

### Homebridge Version

1.7.0

### Node.js Version

20.11.1

### Operating System

Windows 10

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
This is likely a config.json problem, pls share your config file

**Comment by jhayarr1562** [comment]
I'm new to this. how exactly do I do that? (hand covering face)

**Comment by jhayarr1562** [comment]
> I'm new to this. how exactly do I do that? (hand covering face)

![IMG_7024](https://github.com/homebridge/homebridge-config-ui-x/assets/113423784/41617756-ae1d-4453-acb1-16198f2fd7f6)

**Comment by NorthernMan54** [comment]
Sorry, started down the editing the config file path, to configure child bridges, the option is on the plugins page, and under the three dots menu.


![image](https://github.com/homebridge/homebridge-config-ui-x/assets/19808920/c5e9fdb6-7ade-4f0a-853e-df7ff9027314)

**Comment by jhayarr1562** [comment]
![Screenshot (1)](https://github.com/homebridge/homebridge-config-ui-x/assets/113423784/fa2c631f-c907-4cf7-b439-06bc1bca3320)

No child bridge menu

**Comment by NorthernMan54** [comment]
Was just chatting with @bwp91 offline and try the following

1 - Update to the latest beta version of the UI ( PS The top bar menu moves to the side, so be aware of that )
2 - Configure the plugin from the UI
3 - Restart
4 - The ability to configure a plugin as a child bridge appears here - 
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/19808920/dd55fde0-10db-449b-84ee-84150abad178)

**Comment by jhayarr1562** [comment]
I updated and created child bridge. They aren't responding at all now. 
![Screenshot (2)](https://github.com/homebridge/homebridge-config-ui-x/assets/113423784/8f94b6fc-24eb-4330-8492-2cfe5914b0d9)
![Screenshot (3)](https://github.com/homebridge/homebridge-config-ui-x/assets/113423784/ff62a1ee-e4ed-4fb8-bba8-58e43cbdfe69)

**Comment by NorthernMan54** [comment]
Your original child bridge issue is resolved, and it looks like you are now into govee issues, please raise this as an issue with the govee plugin so that the govee developers can assist is resolution.

**Comment by jhayarr1562** [comment]
I did. Thank you.
