### ISSUE TITLE
Add "setting" button for another plugins

### ISSUE THREAD

**Issue by iShift** [oznu/homebridge-config-ui-x#206]
Another plugins may have they own web UI, it would be good if we can integrate it in config plugin (this plugin) page, so they can pass link to it's UI to config plugin.

**Comment by oznu** [comment]
Hi @iShift,

Any plugin who wishes to display a GUI based setup, like this plugin has, can publish a `config.schema.json`.

This plugin: https://github.com/oznu/homebridge-config-ui-x/blob/master/config.schema.json
Something a bit simpler: https://github.com/oznu/homebridge-daikin-esp8266/blob/master/config.schema.json

Documentation on this: https://github.com/homebridge/Documentation/blob/master/Schema.md
