### ISSUE TITLE
 homebridge-config-ui-x does not install under Windows 11

### ISSUE THREAD

**Issue by jormajo** [oznu/homebridge-config-ui-x#2062]
### Current Situation

Trying to install homebridge under Windows, I get the following log:

### Logs

C:\Windows\System32>npm install -g --unsafe-perm homebridge homebridge-config-ui-x
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'homebridge@1.8.2',
npm warn EBADENGINE   required: { node: '^18.15.0 || ^20.7.0' },
npm warn EBADENGINE   current: { node: 'v22.2.0', npm: '10.7.0' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'homebridge-config-ui-x@4.56.2',
npm warn EBADENGINE   required: { node: '^18 || ^20', homebridge: '^1.6.0' },
npm warn EBADENGINE   current: { node: 'v22.2.0', npm: '10.7.0' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'hap-nodejs@0.12.1',
npm warn EBADENGINE   required: { node: '^18 || ^20' },
npm warn EBADENGINE   current: { node: 'v22.2.0', npm: '10.7.0' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@homebridge/ciao@1.2.0',
npm warn EBADENGINE   required: { node: '^18 || ^20' },
npm warn EBADENGINE   current: { node: 'v22.2.0', npm: '10.7.0' }
npm warn EBADENGINE }
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\jordi\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@fastify\static\test\static\deep\path'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static\\test\\static\\deep\\path'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\jordi\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@fastify\static\test\static\deep'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static\\test\\static\\deep'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\jordi\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@fastify\static\test'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules\\@fastify\\static\\test'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\jordi\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\jordi\\AppData\\Roaming\\npm\\node_modules\\homebridge-config-ui-x\\node_modules'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\jordi\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@homebridge\node-pty-prebuilt-multiarch
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/check-prebuild.js || prebuild-install --verbose || node scripts/install.js
npm error Prebuild binary missing for platform.

### Config

```JSON
versions included in the log

Node.js 22.2.0 (x64)
```

### Homebridge UI Version

see log

### Homebridge Version

see log

### Node.js Version

22.2.0 (x64)

### Operating System

Windows 11

### Environment Info

Other (specify in description)

### Raspberry Pi Model

Other (specify in description)

**Comment by NorthernMan54** [comment]
@jormajo We are still working thru NodeJS 22 support.  At this time please downgrade NodeJS to the LTS version ( 20.x ), and it should be fine.
