### ISSUE TITLE
homebridge-homematic This plugin generated a warning from the characteristic 'Current Relative Humidity'

### ISSUE THREAD

**Issue by StanLaurel13** [oznu/homebridge-config-ui-x#2064]
### Current Situation

I get this warning message how can I delete it because the device no longer exists. I had once declared a weather station, but this is gone again and since then I get this message

### Logs

[homebridge.log.txt](https://github.com/user-attachments/files/15758165/homebridge.log.txt)

### Homebridge UI Version

Homebridge v1.8.3-beta.5 · UI v4.56.2 

### Homebridge Version

Debian GNU/Linux Bookworm (12)

### Node.js Version

v20.12.2

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by NorthernMan54** [comment]
Have you tried the 'Remove single cached accessory' option in the UI settings menu ?

<img width="1488" alt="image" src="https://github.com/homebridge/homebridge-config-ui-x/assets/19808920/00abddf3-be46-49b0-baaa-3c2ebaf8a116">

**Comment by StanLaurel13** [comment]
doesn't work

[6/25/2024, 11:33:14 AM] [homebridge-homematic] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
