### ISSUE TITLE
Top bar covers the page content

### ISSUE THREAD

**Issue by vedmant** [oznu/homebridge-config-ui-x#2084]
### Describe The Bug

Top bar covers the page content

https://github.com/homebridge/homebridge-config-ui-x/assets/5052406/378c5736-f4f8-452e-a9a7-2f8bdb3536ce

### Homebridge UI Version

4.56.4

### Homebridge Version

1.8.3

### Node.js Version

20

### Operating System

macOS

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by mkz212** [comment]
It displays correctly for me. Maybe update Homebridge and Homebridge UI? And clear the cache?

**Comment by vedmant** [comment]
@mkz212 I noticed this only appears on the first install and first load, then works ok after refresh.

**Comment by mkz212** [comment]
> @mkz212 I noticed this only appears on the first install and first load, then works ok after refresh.

Strange. I didn't encounter it. But anyway, there will be a completely new menu layout (it's already in beta).
