### ISSUE TITLE
Unable to update Node.jls from 18.x.x to 20.15.0 installed on rueNAS-13.0-U4

### ISSUE THREAD

**Issue by Sir3lly** [oznu/homebridge-config-ui-x#2085]
### Current Situation

<img width="834" alt="Screenshot 2024-06-30 at 8 43 23 AM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/154022160/873b4097-392f-4967-8ab0-80db8f2f21c4">

### Homebridge UI Version

FreeBSD (13.1)

### Homebridge Version

V1.8.3

### Node.js Version

18.18.2

### Operating System

Other (specify in description)

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by mkz212** [comment]
Maybe backup homebridge, install newest fresh homebridge and restore from backup?

**Comment by Sir3lly** [comment]
I haven’t attempted to do a fresh install of homebridge I am currently running Truenas core and I have learned that core is withdrawing support for apps I might try and update to truenas scale

**Comment by Sir3lly** [comment]
installed H/B on truenas scale as a docker and running well now
