### ISSUE TITLE
UI Graphs stop updating after the Widget window is fully populated

### ISSUE THREAD

**Issue by TheEngineerGuy** [oznu/homebridge-config-ui-x#2086]
### Describe The Bug

When you have the webUI open for some time, all graphs will stop updating once they have fully covered their respective Widget window.

Numbers continue to change, but not the graph.

### Logs

Logs don't show this bug.

### Config

```JSON
Un-related to config.
```

### Homebridge UI Version

v4.56.4

### Homebridge Version

v1.8.3

### Node.js Version

v20.15.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

Using hb-service

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by TheEngineerGuy** [comment]
Not Stale. Issue is still prevalent.

**Comment by mkz212** [comment]
I just checked and the graph is refreshing all the time every about 7-8 seconds. Can you give more details in what situation it happens that it doesn't refresh?

**Comment by TheEngineerGuy** [comment]
I can post a video screen recording if you like. Happens on windows and Mac. Firefox and safari. 

All you have to do is watch the cpu graph. Then run something that pushes it. It will go up and down on the extreme right, but that up and down will never show up on graph progression. Not if you refresh browser after that, a peak will show up. 

So the only way to see what happened while you have UI open, is to refresh the UI page.

**Comment by mkz212** [comment]
> I can post a video screen recording if you like. Happens on windows and Mac. Firefox and safari.
> 
> All you have to do is watch the cpu graph. Then run something that pushes it. It will go up and down on the extreme right, but that up and down will never show up on graph progression. Not if you refresh browser after that, a peak will show up.
> 
> So the only way to see what happened while you have UI open, is to refresh the UI page.

Sure, you can show video. Hmm.. And does it happen only after some time of inactivity?

**Comment by TheEngineerGuy** [comment]
> > I can post a video screen recording if you like. Happens on windows and Mac. Firefox and safari.
> > All you have to do is watch the cpu graph. Then run something that pushes it. It will go up and down on the extreme right, but that up and down will never show up on graph progression. Not if you refresh browser after that, a peak will show up.
> > So the only way to see what happened while you have UI open, is to refresh the UI page.
> 
> Sure, you can show video. Hmm.. And does it happen only after some time of inactivity?

Basically, all you have to do is, let UI run for a bit, and you will notice that last pixel of graph keeps going up and down, but the peaks and valleys no longer refresh.

**Comment by TheEngineerGuy** [comment]
https://github.com/user-attachments/assets/dec48d31-d25b-40d9-b358-27e907d461ae

If you see here, the last pixel of graph goes up and down based on the CPU load, but the peaks and valleys dont show up, untill after I refresh the browser at 50 second mark.

**Comment by TheEngineerGuy** [comment]
I dont know if this happens for memory graph as well, because memory usage doesn't fluctuate that much on my Pi with my usage, but I can definitely confirm it happens for network and CPU usage graphs.

**Comment by mkz212** [comment]
> Screen.Recording.2024-07-31.at.9.01.49.AM.mov 
> 
> If you see here, the last pixel of graph goes up and down based on the CPU load, but the peaks and valleys dont show up, untill after I refresh the browser at 50 second mark.

Yes. I see. Pixel is maybe wrong definition, but it is known that it is the last part of the graph, the one showing the current state.

It looks like this for me (on Raspberry Pi 4B, Homebridge 1.8.4, Homebridge UI 4.56.5-beta.20):


https://github.com/user-attachments/assets/bd6efaee-6fcf-47b6-a5bf-0991a6f860de

**Comment by TheEngineerGuy** [comment]
> > Screen.Recording.2024-07-31.at.9.01.49.AM.mov
> > If you see here, the last pixel of graph goes up and down based on the CPU load, but the peaks and valleys dont show up, untill after I refresh the browser at 50 second mark.
> 
> Yes. I see. Pixel is maybe wrong definition, but it is known that it is the last part of the graph, the one showing the current state.
> 
> It looks like this for me (on Raspberry Pi 4B, Homebridge 1.8.4, Homebridge UI 4.56.5-beta.20):
> 
>  ScreenRecording_07-31-2024.17-09-53_1.mov

You are right, I couldn't figure out a better term to describe the last most dot going up and down, and stretching the line up and down with it.

As far as your video, a few updates ago, that is how my graph used to be as well. Not anymore.

**Comment by TheEngineerGuy** [comment]
Not stale.

Latest HB UI update to v4.57.1 seems to have fixed the issue with CPU graph, but Network graph still seems to have a hard boundary on the left which does let graph move in that direction once fully populated in widget window. Video attached below.


https://github.com/user-attachments/assets/23d273de-cf59-4ea9-97c7-0a9fe0608e5f

**Comment by TheEngineerGuy** [comment]
Thanks to everyone who worked on this bug, I can confirm that it has been fixed in v4.58.0

Closing.

**Comment by bwp91** [comment]
Thanks for confirming that it seems okay now!
