### ISSUE TITLE
Unable to update, every time it says "sudo: a password is required"

### ISSUE THREAD

**Issue by dacarson** [oznu/homebridge-config-ui-x#2090]
### Current Situation

Anything I try to update, I get this error:
```
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge@1.8.3

sudo: a password is required

Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

This started when I moved from version 11 to 12. Exactly as called out in this reddit post:
https://www.reddit.com/r/homebridge/comments/mpmpvr/comment/jy9xtck/
However, no fix was listed. 

### Homebridge UI Version

v4.56.2

### Homebridge Version

v1.8.2

### Node.js Version

v18.19.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by mkz212** [comment]
Easiest way to fix this and also update and be happy with newest homebridge, ui and dependencies is to backup homebridge, perform fresh install (e.g using newest version of homebridge raspbian image) and restore backup. Operation is reali simple and automatic.
