### ISSUE TITLE
Unable to Update NodeJS

### ISSUE THREAD

**Issue by mzagaja** [oznu/homebridge-config-ui-x#2091]
### Analysis

When attempting to update NodeJS from the terminal, the update can't download the Node package.

### Expected Behavior

NodeJS will be updated to the latest version.

### Steps To Reproduce

```sh
pi@homebridge:~ $ sudo hb-config
Updating Node.js to LTS, please wait...
Installed: v16.14.0
Current Node.js LTS: v20.15.1
Updating Node.js to v20.15.1...
Downloading to /tmp/tmp.KULqzgyRnZ/node-v20.15.1-linux-armv6l.tar.gz ...
curl: (22) The requested URL returned error: 404 Not Found

Failed to download node-v20.15.1-linux-armv6l.tar.gz. See logs above.
```

### Logs

```markdown
See above.
```

### Configuration

```json
Probably not relevant.
```

### Environment

- OS: *** Homebridge Raspbian v1.0.30 - Raspberry Pi 4 Model B Rev 1.2 ***

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Looking at the messages, am thinking you are running an older version of the Homebridge UI, and that the download URL it is trying to download from was changed.

Also if it is an older implementation, the OS won't support NodeJS 20.  NodeJS 20 is only supported by Bullseye or newer.

```
 * Debian Version - Supplied GLIBC Version
   *
   *  9 - Stretch       2.24
   * 10 - Buster        2.28
   * 11 - Bullseye      2.31
   * 12 - Bookworm      2.36
   * 13 - Trixie
   *
   * NodeJS Version - Minimum GLIBC Version
   *
   *      18            2.28
   *      20            2.31
 ```

**Comment by mkz212** [comment]
@mzagaja 

I think it's easiest for you if you backup homebridge and then perform fresh homebridge installations from the latest version of homebridge raspbian image and restore the backup. The operation is really simple. 

If you currently have e.g. Linux Bullseye, you will not go to Bookworm through the simple Homebridge update. You need to backup, install newest radpbian image and restore backup.

**Comment by mzagaja** [comment]
@mkz212 will give it a shot. Thanks for the advice here.
