### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by gaojie429** [oznu/homebridge-config-ui-x#210]
Hi, I want use this plugin at Japanese.
But I don't know where do I have to add the translation file.
could you tell me how to do?

**Comment by oznu** [comment]
Hi @gaojie429,

Thanks! Check out the bottom of this page for details on addition translations: 
https://github.com/oznu/homebridge-config-ui-x/blob/master/CONTRIBUTING.md#contributing-to-translations

A JSON file and the country code added to 
https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/app/app.component.ts#L18 is all that is required.

**Comment by gaojie429** [comment]
Awesome!
I created JSON file and added country code to the assigned file.
Also, I sent Pull-Requests of these two changes.

Please check it :)

**Comment by oznu** [comment]
Thanks! I'll review this in the next day or so.
