### ISSUE TITLE
No way to rename a room

### ISSUE THREAD

**Issue by lifeiscontent** [oznu/homebridge-config-ui-x#2101]
### Describe The Bug

it doesn't appear there's a way to rename/delete a room in the UI

### Homebridge UI Version

v4.56.4

### Homebridge Version

v1.8.3

### Node.js Version

 v20.15.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

Using hb-service

### Raspberry Pi Model

Raspberry Pi 5

**Comment by mkz212** [comment]
Confirm. Beta also have these problems. It is not possible to change the name or delete the room. You can only add a new room, although not always because on small screens (e.g. iPhone) the top buttons are invisible (there is a button to add a room).

**Comment by mkz212** [comment]
@lifeiscontent I think that if you remove all accessories from room it will be deleted automaticaly after page refresh.
