### ISSUE TITLE
error on reinstall

### ISSUE THREAD

**Issue by fedexhusky** [oznu/homebridge-config-ui-x#211]
I'm quite stuck with the installation of the plugin.
This is what I get when I try to reinstall it. I mean reinstall because I just reinstalled Homebridge from scratch because nom broke

> iMac:~ federico$ sudo npm install -g --unsafe-perm homebridge-config-ui-x
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dasherize-06635385/example'026584d.lock for /usr/local/lib/node_m
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/core-util-is-f5cbff6a/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dasherize-06635385/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/asynckit-8bdc4ade/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/delayed-stream-6ec08bbf/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/combined-stream-175f63ac/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dns-prefetch-control-ac283142/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dont-sniff-mimetype-1a3db11b/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/depd-ad8a2b25/lib/browser'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/camelize-9dc52537/example'
tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/async-limiter-a7b5dce1/coverage'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/bluebird-35a42a7c/js/browser'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dashdash-737e5984/etc'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/camelize-9dc52537/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/depd-ad8a2b25/lib/compat'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dashdash-737e5984/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/async-limiter-a7b5dce1/coverage/lcov-report/async-throttle'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/feature-policy-efff6812/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fast-json-stable-stringify-e7f2f06a/benchmark'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/har-schema-4cf1df2b/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/getpass-399aa67e/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/extsprintf-034daa48/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/frameguard-992fcdb5/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fast-json-stable-stringify-e7f2f06a/example'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/helmet-crossdomain-f3507d89/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/hide-powered-by-e7b73ec6/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/qr-image-372175ff/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fast-json-stable-stringify-e7f2f06a/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ws-57a4748d/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ienoopen-5850521b/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-d9058dc9/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-http-a942a867/lib/passport-http'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/semver-9aa478ce/bin'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-d9058dc9/lib/errors'
 tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-http-a942a867/lib/passport-http/strategies'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/dotenv-1535fe7b/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-d9058dc9/lib/framework'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/bluebird-35a42a7c/js/release'
WARN tarWARN EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/cors-c50e261b/lib'
 tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-d9058dc9/lib/http'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/dist'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/jsonwebtoken-6ea48d35/lib'
WARN WARNtar  EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/express-cf169aac/lib'
tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/commander-cba2bf1a/typings'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/dist/bin'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-d9058dc9/lib/middleware'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/express-cf169aac/lib/middleware'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/misc'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/copy-sync'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/@oznu/hap-client-ee97b943/dist'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-d9058dc9/lib/strategies'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/copy'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/har-validator-035bc4ec/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/jsprim-bffb69e0/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/http-signature-e40db416/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/empty'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/express-cf169aac/lib/router'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/ensure'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/verror-f7852727/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/request-bd733683/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/dist/routes'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/dist'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/misc/Font-Report-June2016'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/@oznu/hap-client-ee97b943/scripts'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uuid-a88b0f83/bin'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/body-parser-3312e588/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uuid-a88b0f83/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/xregexp-a1e25b4f/lib/addons'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/fs'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uri-js-627f5022/dist/es5'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/body-parser-3312e588/lib/types'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/sshpk-be7fed4c/bin'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/json'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/dist/routes/platform-tools'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/sshpk-be7fed4c/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/mkdirs'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/stealthy-require-5822c38d/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/move-sync'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/move'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/request-promise-5a82e04d/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/tough-cookie-7fcba7d5/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/output'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/path-exists'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/remove'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/dist/wss'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uri-js-627f5022/dist/esnext'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/source-map-33a7f974/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/fs-extra-90938b87/lib/util'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/sshpk-be7fed4c/lib/formats'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/lib/compile'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/asn1-e682dd88/lib/ber'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/iconv-lite-a07c07fe/encodings'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ecc-jsbn-27f2f0cb/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/jws-046c78d2/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/xregexp-a1e25b4f/src/addons'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/iconv-lite-a07c07fe/encodings/tables'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ecdsa-sig-formatter-8b5e65ea/src'
WARN tarWARN EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/lib/dot'
 tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uri-js-627f5022/dist/esnext/schemes'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/public'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/request-promise-core-44831249/configure'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/request-promise-core-44831249/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/source-map-33a7f974/dist'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/qs-89ae11eb/dist'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/sshpk-be7fed4c/man/man1'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/qs-89ae11eb/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/performance-now-ee06046b/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/public/assets'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/passport-strategy-b9636a6c/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/performance-now-ee06046b/src'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/helmet-csp-d3ce5cab/lib/check-options/check-directive'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/performance-now-ee06046b/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/psl-6ecba66f/data'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/performance-now-ee06046b/test/scripts'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/psl-6ecba66f/dist'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/iconv-lite-a07c07fe/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/qs-89ae11eb/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uri-js-627f5022/src'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/ship'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uri-js-627f5022/src/schemes'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/negotiator-504268c8/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/agent'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/mime-d61c4208/build'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/form-data-a0ca56c0/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/uri-js-627f5022/tests'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/lib/dotjs'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-stringify-safe-6182a4e7/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/draft-01'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-traverse-b8711441/spec'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/debug-9f47e1ea/src'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-traverse-b8711441/spec/fixtures'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/draft-02'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/inflection-63e51ff1/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ipaddr.js-62b497eb/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/nan-0d53cb96/doc'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/lib/refs'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/ajv-e30017ad/scripts'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/nan-0d53cb96/tools'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/draft-03/examples'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/public/assets/hap-icons'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/draft-04'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/draft-00'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/debugserver'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/include'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/libwinpty'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/json-schema-293afa9d/test'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/shared'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/tests'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/deps/winpty/src/unix-adapter'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/lib'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/scripts'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/src'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/src/unix'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/src/win'
tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/node-pty-d2561a80/typings'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/homebridge-config-ui-x-b1e31c26/public/i18n'
WARN tar EISDIR: illegal operation on a directory, open '/usr/local/lib/node_modules/.staging/lodash-e1e3a35a/fp'
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/sshpk/bin/sshpk-conv
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/federico/.npm/_logs/2019-02-01T00_30_35_286Z-debug.log
iMac:~ federico$ 

>

**Comment by oznu** [comment]
It looks like a corrupted npm/node issue similar to this: https://npm.community/t/global-installs-sudo-npm-i-g-fail-on-mac-after-6-5-upgrade-works-fine-after-6-4-1-downgrade/4082
