### ISSUE TITLE
What do I do now? Can't update.

### ISSUE THREAD

**Issue by larrybradshaw-thinkdifferent** [oznu/homebridge-config-ui-x#2149]
### Current Situation

hoobs@hoobs:/var/lib/homebridge $ sudo hb-service update-node
ℹ Updating Node.js from v18.15.0 to v20.16.0...
✖ Your version of Linux does not meet the GLIBC version requirements to use this tool to upgrade Node.js. Wanted: >=2.31. Installed: 2.28 - see https://homebridge.io/w/JJSun
hoobs@hoobs:/var/lib/homebridge $ 

### Config

```JSON
Raspbian GNU/Linux Buster (10)
```

### Homebridge UI Version

Installed: v4.56.4

### Homebridge Version

Homebridge v1.8.4 (HAP v0.12.2) (HOOBS) is running on port 51826

### Node.js Version

v18.15.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
High level steps are here

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js/#does-my-operating-system-support-an-updated-nodejs

You need to update the operating system on the device your running homebridge on in order to upgrade.
