### ISSUE TITLE
More than just "accessories" shown

### ISSUE THREAD

**Issue by n0rt0nthec4t** [oznu/homebridge-config-ui-x#2154]
### Current Situation

On the accessories page, there appears more than just the "main" services for an accessory. Things such as teh battery service, speaker, microphone etc services are shown

I've marked for example, the battery service as "hidden" in my code, but still visible

HKSV video camera also shows things Cush as Event Recording services etc. 

These should be hidden from the user??

<img width="711" alt="Screenshot 2024-08-13 at 1 42 51 pm" src="https://github.com/user-attachments/assets/7df16560-1c68-44cf-9ca7-f0a4d29768ca">

### Homebridge UI Version

1.8.4

### Homebridge Version

4.56.4

### Node.js Version

20.16.0

### Operating System

macOS

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by n0rt0nthec4t** [comment]
@bwp91 why does HB UI show a service that has been marked as "hidden" in code on the accessories view? Shouldn't these be automatically hidden based on the service visability state?

**Comment by bwp91** [comment]
@n0rt0nthec4t i don’t know is the answer!

maybe it is just a case that has never been thought about.

would it not be better to let a user decide whether they want to hide each individual service on an accessory?

**Comment by n0rt0nthec4t** [comment]
The problem as I see it, lots of accessories create hidden services which a user probably doesn't need to interact with. The option in HB UI is to only hide the entire accessory.  I think it should respect the visibility status of the service themselves. Cameras created alot of services which have no meaning to teh end user and appear in HB UI for example

**Comment by bwp91** [comment]
> The option in HB UI is to only hide the entire accessory.

This is not the case for me. As each tile is already its own service and not accessory, clicking the hide toggle hides just this tile, not any others
