### ISSUE TITLE
Homebridge v2 Bridged camera support

### ISSUE THREAD

**Issue by DG517** [oznu/homebridge-config-ui-x#2158]
### Feature Description

Upgrading to HBv2 will eliminate a crucial feature I rely on in my specific setup. I run HB using RPI and Docker, creating two containers to separate two instances of HB. This setup enables me to connect our home’s Ring camera unbridged to the first instance of HB, while the second instance allows me to connect the Ring camera again in bridge mode. This feature is particularly useful for sharing HomeKit PIP notifications on Apple TV hubs with my roommates who have separate AppleIDs. However, HBv2 will remove the ability to connect my Ring cameras to two instances of HB. I kindly request that you reconsider removing bridged camera support for special circumstances like this.

**Comment by donavanbecker** [comment]
The ring plugin is planning on removing bridged cameras either way. Not because of v2.0, it's just what the developer is wanting to do because it handles cameras better.
