### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by Rubenfer** [oznu/homebridge-config-ui-x#216]
I'm using homebridge-config-ui-x with a SSL certificate.

I can access only via https://url:port, but if I use only url:port "Safari cannot open the page".

It's possible to redirect the traffic of http to https like websites?

**Comment by oznu** [comment]
To do this without some sort of dodgy `net`proxy I would need to expose another port to serve plain http just to redirect to the https+port.

Example: http://localhost:8080 -> https://localhost:8443
