### ISSUE TITLE
UI shows Apple TV Enhanced as incompatible with 2.0

### ISSUE THREAD

**Issue by maxileith** [oznu/homebridge-config-ui-x#2163]
### Current Situation

The UI shows Apple TV Enhanced 1.6.0-2 as not explicitly marked as compatible with homebridge 2.0 although it is.

https://github.com/maxileith/homebridge-appletv-enhanced/blob/ad87e7c3d3142174f206826d373f8b38d9e76ea7/package.json#L20

Am I missing something?

### Homebridge UI Version

4.57.0

### Homebridge Version

1.8.4

### Node.js Version

20.17.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

Using Docker

### Raspberry Pi Model

None

**Comment by mkz212** [comment]
It is probably the case that the information is get from the version of npm with tag 'latest' (not from newest release). And your 'latest' (v1.5.2) don't have in package.json support for homebridge ^2.

**Comment by maxileith** [comment]
Okay, fair point. Haven't looked at the code. However, now that I did ... I have found a potential issue: https://github.com/homebridge/homebridge-config-ui-x/commit/1dceff53ae9d65a227faf948b5139816da50a9f4#r145829593

**Comment by bwp91** [comment]
fixed in 4.57.1

![Screenshot 2024-08-26 at 12 53 20](https://github.com/user-attachments/assets/5c4b51da-2672-4d00-a517-9ac042498a2f)

thanks for flagging this!
