### ISSUE TITLE
Cannot update plugins since latest ui-x update

### ISSUE THREAD

**Issue by redeemer666** [oznu/homebridge-config-ui-x#2173]
### Current Situation

Since latest update to ui-x, if I click on the (up arrow) to update plugins nothing happens. Already tried to change browser but issue persist. No error on logs either

### Homebridge UI Version

4.57.1

### Homebridge Version

1.8.4

### Node.js Version

20.17

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

Using hb-service

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by mkz212** [comment]
I just checked on Raspberry Pi 4B, Homebridge 1.8.4, Homebridge UI 4.57.1 and works without problems. 

![IMG_7120](https://github.com/user-attachments/assets/a47a8e29-7452-495b-81e8-2586a37fb18e)
![IMG_7121](https://github.com/user-attachments/assets/6a9b4228-cb88-43dc-a21e-133699b10c73)

**Comment by Palinghaas** [comment]
I'm having the same issue. Homebridge 1.8.4 and UI 4.57.1. I'm on a RPi Model 3 B+.

**Comment by bwp91** [comment]
@Palinghaas can you give an example of a plugin that you are trying to update and isn't working?

**Comment by Palinghaas** [comment]
Sure, I'm unable to update the [Denon TV](https://github.com/grzegorz914/homebridge-denon-tv#readme) plugin.

**Comment by bwp91** [comment]
I just installed an older version of this plugin, tried to update, and it worked fine :/

What happens when you click the 'up' icon? does a modal appear with the plugin release notes?

I'm really asking how far you get. A screen recording would be useful.

and if possible could you do it with the browser dev tools open on the console screen, to see if any errors appear there?

**Comment by Palinghaas** [comment]
Attached you'll find a screen recording. Immediately after clicking the update arrow 1 error is displayed in the console. I've copied the text below. Let me know if you need more.

```
main.f1717ed88be56f6b.js:1 ERROR Error: Uncaught (in promise): TypeError: Invalid comparator: ^20.15.1,
TypeError: Invalid comparator: ^20.15.1,
    at n.parse (main.f1717ed88be56f6b.js:1:1692216)
    at new n (main.f1717ed88be56f6b.js:1:1692034)
    at main.f1717ed88be56f6b.js:1:1695296
    at Array.map (<anonymous>)
    at n.parseRange (main.f1717ed88be56f6b.js:1:1695288)
    at main.f1717ed88be56f6b.js:1:1693929
    at Array.map (<anonymous>)
    at new n (main.f1717ed88be56f6b.js:1:1693916)
    at Le.exports (main.f1717ed88be56f6b.js:1:1712618)
    at main.f1717ed88be56f6b.js:1:266985
    at n.parse (main.f1717ed88be56f6b.js:1:1692216)
    at new n (main.f1717ed88be56f6b.js:1:1692034)
    at main.f1717ed88be56f6b.js:1:1695296
    at Array.map (<anonymous>)
    at n.parseRange (main.f1717ed88be56f6b.js:1:1695288)
    at main.f1717ed88be56f6b.js:1:1693929
    at Array.map (<anonymous>)
    at new n (main.f1717ed88be56f6b.js:1:1693916)
    at Le.exports (main.f1717ed88be56f6b.js:1:1712618)
    at main.f1717ed88be56f6b.js:1:266985
    at K (polyfills.985044b7a7399140.js:1:16771)
    at polyfills.985044b7a7399140.js:1:15859
    at polyfills.985044b7a7399140.js:1:15965
    at e (main.f1717ed88be56f6b.js:1:2683423)
    at E (main.f1717ed88be56f6b.js:1:2683626)
    at y.invoke (polyfills.985044b7a7399140.js:1:7352)
    at Object.onInvoke (main.f1717ed88be56f6b.js:1:2302356)
    at y.invoke (polyfills.985044b7a7399140.js:1:7292)
    at x.run (polyfills.985044b7a7399140.js:1:2715)
    at polyfills.985044b7a7399140.js:1:17566
```

https://github.com/user-attachments/assets/5990259c-e267-4eaa-9b47-dd8e1b7ae00e

**Comment by bwp91** [comment]
@Palinghaas can you do me a favour and click the three dots on this plugin to update to **5.1.2**.

Then restart homebridge (or the child bridge if you have this set up)

Then go back to the plugins page, and see if it will let you _then_ update to 5.1.7?

**Comment by Palinghaas** [comment]
After selecting the version I want to install and I click the purple install button the 'pop up' window just disappears and nothing happens further.

**Comment by grzegorz914** [comment]
In the 5.1.1 was bug in package.json, just uninstall this plugin without removing config and install latest version again.

**Comment by bwp91** [comment]
yes i noticed that comma 😆 but this has made me wonder why when trying to update a plugin, the UI checks your node version vs the `engines.node` of the version of the plugin you have installed rather than for the newer version of the plugin

**Comment by Palinghaas** [comment]
> In the 5.1.1 was bug in package.json, just uninstall this plugin without removing config and install latest version again.

This fixed my issue. Thanks! :)

**Comment by bwp91** [comment]
@redeemer666 im assuming you were experiencing this issue for the same plugin? please see fix above.

i am making some changes to the UI to avoid this situation happening in the future!
