### ISSUE TITLE
Ring Plugin Config Setup 

### ISSUE THREAD

**Issue by JamesLittleDude** [oznu/homebridge-config-ui-x#2174]
### Current Situation

When I try and add my ring account with password to the setup confin screen it just spins with a purple gear. I believe ring has a multi factor verification code that is needed to connect. How do I input multi factor code?

### Homebridge UI Version

New download 

### Homebridge Version

2024 · Homebridge v1.8.4 · UI v4.57.1 

### Node.js Version

Node.js Version	 v16.16.0

### Operating System

Windows 10

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
This should be opened on the ring plugin repo.
