### ISSUE TITLE
Prebuild binary missing for platform MacMini M1

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#2188]
### Describe The Bug

Always during update the error appear on MacMini M1

![IMG_1017](https://github.com/user-attachments/assets/a395daeb-9178-45c9-abf2-8bfa2025f0d7)

### Logs

N/A

### Config

```JSON
N/A
```

### Homebridge UI Version

All

### Homebridge Version

All

### Node.js Version

All

### Operating System

macOS

### Environment Info

Using hb-service

### Raspberry Pi Model

Other (specify in description)

**Comment by NorthernMan54** [comment]
This is from M1 MacBook Pro

```
> @homebridge/node-pty-prebuilt-multiarch@0.11.14 install
> node scripts/check-prebuild.js || prebuild-install --verbose || node scripts/install.js

Prebuild binary missing for platform.
prebuild-install info begin Prebuild-install version 7.1.2
prebuild-install info looking for local prebuild @ prebuilds/node-pty-prebuilt-multiarch-v0.11.14-node-v115-darwin-arm64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/xxxx/.npm/_prebuilds/62587c-node-pty-prebuilt-multiarch-v0.11.14-node-v115-darwin-arm64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /Users/xxxx/.npm/_prebuilds/62587c-node-pty-prebuilt-multiarch-v0.11.14-node-v115-darwin-arm64.tar.gz
prebuild-install info unpack resolved to /Users/xxxxx/Code/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node
prebuild-install info unpack required /Users/xxxx/Code/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> @homebridge/node-pty-prebuilt-multiarch@0.11.14 postinstall
> node scripts/post-install.js
```

The message `Prebuild binary missing for platform.` is normal on the M1 platform.  For M1, the prebuilt binary is pulled from GitHub, and placed into build/Release/pty.node.

What messages did you get afterwards ?

**Comment by grzegorz914** [comment]
Same as Your, but why is marker as error in red.

**Comment by NorthernMan54** [comment]
Mine was in Red as well, I just did text copy rather than an image.

That portion of text is red on my screen as well.  I did look at what is happening, and both 'scripts/check-prebuild.js' and the installer 'prebuild-install' uses red for everything.  Hence the color in that section.

**Comment by grzegorz914** [comment]
Ok, I think this need to be green or white if passed withouth error.

**Comment by NorthernMan54** [comment]
Looking further at the code, and it is a chain of commands, and if the first fails it goes to the second.  So the first fails, and displays the error in Red ( which would be expected if it was standalone ).  Without rewriting the whole thing totally differently I don't think I can change it

**Comment by grzegorz914** [comment]
Ok, clear.
