### ISSUE TITLE
Safari iOS - does not offer prefill credentials for login to GUI

### ISSUE THREAD

**Issue by MartinKristof** [oznu/homebridge-config-ui-x#2198]
### Describe The Bug

In previous versions the login form offered me prefil credentials. Now is even impossible to use keychain.

### Homebridge UI Version

4.59.1

### Homebridge Version

1.8.4

### Node.js Version

20.17.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

Using hb-service

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by donavanbecker** [comment]
I am not able to reproduce.

**Comment by bwp91** [comment]
neither am i 🤔

i am running 4.59.1 here:

![IMG_0111](https://github.com/user-attachments/assets/98d23e99-a527-4c5d-b892-87749e508c45)

**Comment by MartinKristof** [comment]
iOS 18.0.0 and 18.0.1 - Safari.

FF and Chrome okay.
