### ISSUE TITLE
Can't login to UI

### ISSUE THREAD

**Issue by Horvath-N** [oznu/homebridge-config-ui-x#22]
I have everything configured properly, but I can't access the web ui. this is whats in my config.json

```
"platform": [
         {
               "platform": "config",
               "name":  "Config",
               "port": 8080,
               "sudo": true,
               "theme": "blue"
         }
]
```

**Comment by oznu** [comment]
Hi @Horvath-N,

Would you be able to post the Homebridge logs from the time it was last restarted, this might help me see what's gone wrong here.

Thanks.

**Comment by Horvath-N** [comment]
Here it is.
----------------------------------------------------------------------------------------------------
Jan 29 19:11:55 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Jan 29 19:11:56 raspberrypi homebridge[1775]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Jan 29 19:11:56 raspberrypi homebridge[1775]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 29 19:11:56 raspberrypi homebridge[1775]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Jan 29 19:11:56 raspberrypi homebridge[1775]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jan 29 19:11:56 raspberrypi homebridge[1775]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 29 19:11:56 raspberrypi homebridge[1775]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jan 29 19:11:56 raspberrypi node[1775]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Jan 29 19:11:56 raspberrypi node[1775]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 29 19:11:56 raspberrypi node[1775]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Jan 29 19:11:56 raspberrypi node[1775]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jan 29 19:11:56 raspberrypi node[1775]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jan 29 19:11:56 raspberrypi node[1775]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] Loaded plugin: homebridge-config-ui-x
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] Registering platform 'homebridge-config-ui-x.config'
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] ---
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] Loaded plugin: homebridge-mqtt-switch-tasmota
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] ---
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] Loaded config.json with 1 accessories and 0 platforms.
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] ---
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] Loading 1 accessories...
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] [Lights] Initializing mqtt-switch-tasmota accessory...
Jan 29 19:11:58 raspberrypi homebridge[1775]: [2018-1-29 19:11:58] [Lights] Nazwa do RESULT  POWER
Jan 29 19:11:58 raspberrypi homebridge[1775]: Setup Payload:
Jan 29 19:11:58 raspberrypi homebridge[1775]: X-HM://0023ISYWY0F8E
Jan 29 19:11:58 raspberrypi homebridge[1775]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by oznu** [comment]
I see why. I have an error in my documentation.

`platform` should be plural, `platforms`.

```json
"platforms": [
         {
               "platform": "config",
               "name":  "Config",
               "port": 8080,
               "sudo": true,
               "theme": "blue"
         }
]
```

I will fix the docs, sorry about that.

**Comment by Horvath-N** [comment]
Hmmm. I changed that, but it didn't seem to help. `sudo netstat -plnt` doesn't even show that the port is listening.

**Comment by oznu** [comment]
Here are the relevant bits from the log you posted earlier:

```
[2018-1-29 19:11:58] Loaded plugin: homebridge-config-ui-x
[2018-1-29 19:11:58] Registering platform 'homebridge-config-ui-x.config'
[2018-1-29 19:11:58] Loaded config.json with 1 accessories and 0 platforms.
```

After updating the `config.json` is it still showing `0 platforms`?

**Comment by Horvath-N** [comment]
Here's what it says now.
----------------------------------------------------------------------------------------------------
Jan 29 19:39:10 raspberrypi homebridge[769]: [2018-1-29 19:39:10] Loading 1 platforms...
Jan 29 19:39:10 raspberrypi homebridge[769]: [2018-1-29 19:39:10] [Config] Initializing config platform...

**Comment by oznu** [comment]
Please remove the plugin:

```
sudo npm uninstall -g homebridge-config-ui-x
```

Then reinstall:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by Horvath-N** [comment]
That did it. It works. Thank you!
