### ISSUE TITLE
Unclickable checkboxes with static configuration schemas

### ISSUE THREAD

**Issue by thoukydides** [oznu/homebridge-config-ui-x#2200]
### Describe The Bug

Checkbox inputs are not displaying correctly with static configuration schemas. This is an example from [homebridge-aeg-robot](https://github.com/thoukydides/homebridge-aeg-robot):

![image](https://github.com/user-attachments/assets/d52708fd-51df-410a-a3cf-e45ae8caa972)

It corresponds to this part of the [`config.schema.json`](https://github.com/thoukydides/homebridge-aeg-robot/blob/77398c9bbcdc92cd20660da28c39099d7c7413a0/config.schema.json):
```json
{
    "schema": {
        "type": "object",
        "properties": {
            "hideServices": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                    "type": "string",
                    "enum": [
                        "Battery",
                        "Contact Sensor",
                        "Fan",
                        "Filter Maintenance",
                        "Occupancy Sensor",
                        "Switch Clean",
                        "Switch Home"
                    ]
                }
            }
        }
    },
    "form": [{
        "type": "fieldset",
        "title": "Disable Unwanted Features",
        "expandable": false,
        "expanded": true,
        "items": [{
            "key": "hideServices",
            "notitle": true,
            "description": "Checking an option <b>disables</b> the corresponding HomeKit Service"
        }]
    }]
}
```

The selected items are clearly not being styled appropriately. However, more serious, is that the selected items can be deselected, but clicks on the deselected items do nothing.

Custom UI checkbox inputs still work correctly; this only appears to affect static `config.schema.json` usage. I have seen the same with other plugins that use static configuration schemas, such as [homebridge-weather-plus](https://github.com/naofireblade/homebridge-weather-plus).

This was first raised as thoukydides/homebridge-aeg-robot#54.

### Homebridge UI Version

4.60.1

### Homebridge Version

1.8.4

### Node.js Version

18.20.4

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

Using systemd

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @thoukydides 

Thanks for reporting this issue, I believe I have managed to fix this in a beta version of the UI that has been published a few minutes ago.

Would you be able to install and confirm?

**Comment by thoukydides** [comment]
I have just tested [4.60.2-beta.1](https://www.npmjs.com/package/homebridge-config-ui-x/v/4.60.2-beta.1) and it fixes the problem for all of the plugins I use, so looks good to me.

Thank you for fixing it so quickly.

**Comment by bwp91** [comment]
Fixed in latest version 👍, thanks again for the report
