### ISSUE TITLE
Can't update config-ui 4.60.1 -> 4.64.0

### ISSUE THREAD

**Issue by peck4919** [oznu/homebridge-config-ui-x#2204]
### Describe The Bug

Update fails with code 1. If it helps, my Homebridge install was done some time ago. It is running on Ubuntu, but was not installed as an apt package which is the recommended way now. 

### Logs

USER: homebridge
DIR: /usr/lib/node_modules/homebridge-config-ui-x
CMD: sudo -E -n npm run upgrade-install -- 4.61.0 /usr v4.61.0
sudo: a password is required

Bundled update failed. Trying regular update using npm.
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-config-ui-x@4.61.0
sudo: a password is required

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Error: Operation failed with code 1.

You can download this log file for future reference.

### Homebridge UI Version

4.60.1

### Homebridge Version

1.8.4

### Node.js Version

20.18.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

Using Hyper-V

### Raspberry Pi Model

None

**Comment by peck4919** [comment]
I guess maybe disregard..   I was able to update from the shell of the OS when logged in with my admin user credentials with sudo access.

**Comment by NorthernMan54** [comment]
Tks for the update
