### ISSUE TITLE
failed to uninstall plugin

### ISSUE THREAD

**Issue by gaojie429** [oznu/homebridge-config-ui-x#221]
I tried to uninstall a plugin through config-ui-x, but the error occured like this:
execvp(3) failed.: no such file or directory.

This is because I installed node by using nodebrew and the exact path is this.: /Users/[username]/.nodebrew/current/bin/node

How can I configure the path of node on config-ui-x ?

Thanks!

**Comment by oznu** [comment]
The node binary is retrieved from the current node process env. On Linux/macOS npm needs to be in your PATH environment variable.

Can you post the full output of the error? Including the bits that's show exactly what command is being executed - and try and run the same command as the same user manually. You probably don't want to be using the `sudo`option.

**Comment by gaojie429** [comment]
Here is the full-version of the error. (As I could not copy the command line, I post the screenshot.)
I run the same command as same user, and done successfully.
![img_0537](https://user-images.githubusercontent.com/36978407/52849791-37d1fa80-3155-11e9-95a7-58e901302ef0.png)

**Comment by oznu** [comment]
Are you starting homebridge with `launchctl`? If so you might not be including any PATH additions in that you've defined in that users, or your local users `.bash_profile` to make nodebrew work.

**Comment by gaojie429** [comment]
Yes, I'm runnning homebridge with `launchctl`.
Where should I add the PATH of node?

**Comment by oznu** [comment]
Logged in as the user, something like this should do it:

```
launchctl setenv PATH $PATH
```

I haven't tested this, so you might have to do some googling to see how to make it persist etc.

**Comment by gaojie429** [comment]
I googled and try this kind of command, but it didn't solve this problem...
However I found that when I run `homebridge` command on terminal, I can install plugin through config ui-x.
This problem only cause when I run homebridge via `launchctl`.

**Comment by dpyy** [comment]
Same problem for me, it works if I run 'homebridge' but does not work if I use launchctl, my error is this one

DIR: /usr/local/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier uninstall --unsafe-perm homebridge-wink3

execvp(3) failed.: No such file or directory

Command failed. Please review log for details

**Comment by martonky** [comment]
hello.. i have probably simillar problem. I am tryin to find the way, how to run another node js with your plugin. When I typed to the command  node -v, then command show me v11.12.0. When I opened your plugin, there is node.js v8.9.0. How can I change that?
<img width="819" alt="Snímka obrazovky 2019-03-31 o 13 35 53" src="https://user-images.githubusercontent.com/48962610/55288777-dd1af800-53bc-11e9-8640-97dcd11ddbd1.png">

**Comment by oznu** [comment]
I've created a wiki article, derived from the one on the homebridge wiki, that shows step by step how to get homebridge and homebridge-config-ui-x up and running.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-UI-on-macOS

Everything works, uninstalling, updating, installing plugins, logs, and restart - all running as a non-root user and without `sudo`.
