### ISSUE TITLE
CPU tile no longer shows temperature

### ISSUE THREAD

**Issue by justjam2013** [oznu/homebridge-config-ui-x#2216]
### Describe The Bug

The CPU tile on the status screen still displays `Load`, but not `Temp`.

### Homebridge UI v4.62.0
<img width="445" alt="Screenshot 2024-10-26 at 6 31 35 PM" src="https://github.com/user-attachments/assets/4608ba37-08a4-4c6a-be55-475bd3f01499">

### Homebridge UI v4.62.1-beta.11
<img width="423" alt="Screenshot 2024-10-26 at 6 31 49 PM" src="https://github.com/user-attachments/assets/5bcd9a4f-6cc1-463b-8b40-20598dbe888f">

### Homebridge UI v4.62.1-beta.11
I widened the tile, in the event that this was related to the internal tile layout not being adjusted after the menu down the side shrunk the tile width, but `Temp` was still not displayed 
<img width="427" alt="Screenshot 2024-10-26 at 6 32 40 PM" src="https://github.com/user-attachments/assets/1c5c2587-9d0c-40b7-9aa1-4cb41901ffbf">

### Homebridge UI Version

v4.62.1-beta.11

### Homebridge Version

1.8.5

### Node.js Version

22.9.0

### Operating System

MacOS Sequoia

### Environment Info

Using hb-service

**Comment by bwp91** [comment]
are the screenshots from the same homebridge instance?

**Comment by bwp91** [comment]
i say this because the temperature does not show when running the UI from a mac

**Comment by justjam2013** [comment]
Ah! The non-beta is running on a Raspberry Pi, whereas the beta is indeed running on a Mac. Thanks for the clarification.
And I probably should have selected MacOS under Operating System rather than Ubuntu, which is running on the RPi.

Maybe could there be a note in the CPU widget configuration indicating that Temp is not available on MacOS? I spent half an hour comparing the two instances and going through all the settings twice, sure that I had missed something, before opening this bug report.

**Comment by justjam2013** [comment]
**Update** corrected the ticket with MacOS and hb-service, for completeness.
