### ISSUE TITLE
I can't add Homebridge to the home app. 

### ISSUE THREAD

**Issue by Ad120360** [oznu/homebridge-config-ui-x#2217]
### Current Situation

Ik kan Homebridge niet toevoegen aan de woning app. Als ik accessoire toevoeg dan duurt het erg lang en krijg ik onderstaande meldingen. Ik heb deze problemen met zowel de laatste versie als de Beta versies. Ik gebruik een iPhone 15 Pro Max en heb Homebridge via Docker op mijn Nas geïnstalleerd. Van zowel de iPhone als de Nas heb ik de laatste softwareversies geinstalleerd.

I can't add Homebridge to the home app. When I add an accessory it takes a long time and I get the following messages. I have these problems with both the latest version and the Beta versions. I use an iPhone 15 Pro Max and have installed Homebridge via Docker on my Nas. I have installed the latest software versions of both the iPhone and the Nas.

![IMG_0454](https://github.com/user-attachments/assets/da36a82c-e61d-4cbc-932d-cb22d206b357)
![IMG_0455](https://github.com/user-attachments/assets/50890753-7529-46e0-a7ae-aab55425db0e)
<img width="1435" alt="Scherm­afbeelding 2024-10-27 om 10 08 42" src="https://github.com/user-attachments/assets/d6b298e5-64f8-4142-a
<img width="1719" alt="Scherm­afbeelding 2024-10-27 om 10 21 09" src="https://github.com/user-attachments/assets/94b076aa-2725-499c-93c1-9576e7f43423">
ba0-cdb533a19a47">

### Logs

[homebridge.log.txt](https://github.com/user-attachments/files/17533362/homebridge.log.txt)

### Homebridge UI Version

V4.62.0

### Homebridge Version

V1.8.5

### Node.js Version

V20.18.0

### Operating System

QNAP

### Environment Info

Using Docker

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @Ad120360 

Can you try changing the mdns advertiser to avahi or ciao, restarting homebridge, and then trying to add it again?

https://github.com/homebridge/homebridge/wiki/mDNS-Options#how-to-set-mdns-advertiser

**Comment by Ad120360** [comment]
I did that but it doesn't matter

**Comment by Ad120360** [comment]
It seems that Apple has tightened security since the arrival of IOS18, which prevents me from adding the Homebridge to Homekit.

**Comment by Ad120360** [comment]
Hi Ben ,

Ik heb dat geprobeerd maar heeft niet geholpen.

------ Oorspronkelijke bericht ------
Van "Ben" ***@***.******@***.***>>
Aan "homebridge/homebridge-config-ui-x" ***@***.******@***.***>>
CC "Ad120360" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Datum 27-10-2024 10:44:49
Onderwerp Re: [homebridge/homebridge-config-ui-x] I can't add Homebridge to the home app. (Issue #2217)


Hi @Ad120360<https://github.com/Ad120360>

Can you try changing the mdns advertiser to avahi or ciao, restarting homebridge, and then trying to add it again?

https://github.com/homebridge/homebridge/wiki/mDNS-Options#how-to-set-mdns-advertiser

**Comment by Ad120360** [comment]
It could also be that something went wrong with the installation. The images on your website look different and during the installation on the Qnap you can set less. Maybe you can look at this sometime. The version of containerstation is V3.0.8.981 (24-10-04). The version on my NAS is QuTS hero h5.2.0.2860.

**Comment by Ad120360** [comment]
It could also be that something went wrong with the installation. The images on your website look different and during the installation on the Qnap you can set less. Maybe you can look at this sometime. The version of containerstation is V3.0.8.981 (24-10-04). The version on my NAS is QuTS hero h5.2.0.2860.


------ Oorspronkelijke bericht ------
Van "Ben" ***@***.******@***.***>>
Aan "homebridge/homebridge-config-ui-x" ***@***.******@***.***>>
CC "Ad120360" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Datum 27-10-2024 10:44:49
Onderwerp Re: [homebridge/homebridge-config-ui-x] I can't add Homebridge to the home app. (Issue #2217)


Hi @Ad120360<https://github.com/Ad120360>

Can you try changing the mdns advertiser to avahi or ciao, restarting homebridge, and then trying to add it again?

https://github.com/homebridge/homebridge/wiki/mDNS-Options#how-to-set-mdns-advertiser
