### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ifeign** [oznu/homebridge-config-ui-x#222]
Not a pressing issue, but would a dark mode be possible as a theme option? Now that most of the major browsers and OSes have native dark mode, along with many websites, it'd be great to have this feature.

**Comment by oznu** [comment]
While I'm not a big dark mode fan, I'll happily accept a pull request that implements a new dark mode theme.

This would be the starting point:
https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/scss/themes.scss

**Comment by RaymondMouthaan** [comment]
Work in progress

**Comment by oznu** [comment]
Available in 3.10.0

**Comment by andyblac** [comment]
just shows blue header here ???
