### ISSUE TITLE
Missing 'Startup Script' option in Settings on MacOS

### ISSUE THREAD

**Issue by justjam2013** [oznu/homebridge-config-ui-x#2222]
### Describe The Bug

The beta version is missing the `Startup Script` option in the `Startup & Environment` section of Settings.

Homebridge UI: v4.62.0
Homebridge: v1.8.5
Node.js: v20.18.0
OS: Ubuntu Jammy (22.04.5 LTS)
Docker: Yes
<img width="377" alt="Screenshot 2024-10-29 at 9 58 36 AM" src="https://github.com/user-attachments/assets/2d1e789f-2d10-47d3-a990-b8611d57f35b">

Homebridge UI: v4.62.1-beta.15
Homebridge: v1.8.5
Node.js: v22.9.0
OS: macOS Sequoia
Docker: No
<img width="330" alt="Screenshot 2024-10-29 at 9 58 52 AM" src="https://github.com/user-attachments/assets/10f991a5-36e4-4c4e-bfb6-de87e5777159">

### Homebridge UI Version

v4.62.1-beta.15

### Homebridge Version

1.8.5

### Node.js Version

22.9.0

### Operating System

macOS

### Environment Info

Using hb-service

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
This startup script is only for docker users

**Comment by justjam2013** [comment]
That is perfect, thank you!
I need pyatv for the `Homepod mini radio support` plugin. But every time I update the docker container I have to reinstall it, which is quite annoying because I always forget about it. So this is the place to add the `pip install` command to ensure that it gets reinstalled after a new container is created. Awesome!

Closing this ticket as not a bug.
