### ISSUE TITLE
lodash version issue with v3.9.6

### ISSUE THREAD

**Issue by JacVid** [oznu/homebridge-config-ui-x#223]
Hello,

I've installed the latest update : homebridge-config-ui-x v3.9.6

here the messages I get:

> /homebridge # npm audit
>                                                                                 
>                        === npm audit security report ===                        
>                                                                                 
>                                                                                 
>                                  Manual Review                                  
>              Some vulnerabilities require your attention to resolve             
>                                                                                 
>           Visit https://go.npm.me/audit-guide for additional guidance           
>                                                                                 
>                                                                                 
>   Moderate        Prototype Pollution                                           
>                                                                                 
>   Package         lodash                                                        
>                                                                                 
>   Patched in      >=4.17.11                                                     
>                                                                                 
>   Dependency of   homebridge-nest                                               
>                                                                                 
>   Path            homebridge-nest > request-promise > lodash                    
>                                                                                 
>   More info       https://npmjs.com/advisories/782                              
>                                                                                 
>                                                                                 
>   Low             Prototype Pollution                                           
>                                                                                 
>   Package         lodash                                                        
>                                                                                 
>   Patched in      >=4.17.5                                                      
>                                                                                 
>   Dependency of   homebridge-nest                                               
>                                                                                 
>   Path            homebridge-nest > request-promise > lodash                    
>                                                                                 
>   More info       https://npmjs.com/advisories/577                              
>                                                                                 
> found 2 vulnerabilities (1 low, 1 moderate) in 2381 scanned packages
>   2 vulnerabilities require manual review. See the full report for details.

I've tried this:

```
$ npm i -g npm
$ npm i --save lodash.update
```

and even after a reboot, I still have a "lodash issue"

Any idea ?

Thanks for your help

**Comment by oznu** [comment]
This plugin has up-to-date dependencies to that fix these vulnerabilities. GitHub spams me with alerts if I don't action them :)

These issues, as noted by your logs are being caused by the `homebride-nest`plugin.

Additionally, you may want to enable this plugin in Docker using the supported method which takes care of all the setup/permissions for you:

https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-UI-with-Docker

**Comment by JacVid** [comment]
Hello,

I've uninstall the homebridge-nest plugin and you are right, the `npm audit` is then clean.

But even if I reinstall the plugin via the Docker up to date as well as the homebridge-config-ui-x, I still have the 2 vulnerabilities (1 low, 1 moderate).

I'm gonna ask @chrisjshull for that.

Thank you.

**Comment by oznu** [comment]
It's a nested dependency, and I would say the risk is very low, but the reason it keeps that version keeps getting installed is its defined in the plugins `package-lock.json`:

https://github.com/chrisjshull/homebridge-nest/blob/master/package-lock.json#L622

An `npm update` / `npm audit fix` on that plugin should be all that is required.
