### ISSUE TITLE
Grammatical error with JSON Config UI help.  There should be Their.

### ISSUE THREAD

**Issue by jasonbrowne44** [oznu/homebridge-config-ui-x#2240]
### Describe The Bug

In the Accsessories help popup window it states: Plugins that expose a "Accessory" should have there config entered in this array. Separate each plugin config block using a comma.

there should be their

### Homebridge UI Version

v4.62.0

### Homebridge Version

1.8.5

### Node.js Version

v20.18.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

Using systemd

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @jasonbrowne44 thanks for reporting this, it should be fixed with a recent release!
