### ISSUE TITLE
Failed to search the npm registry - "Request failed with status code 400" - see logs.

### ISSUE THREAD

**Issue by NorthernMan54** [oznu/homebridge-config-ui-x#2259]
### Describe The Bug

Search for a plugin with a longer name -` homebridge-daikin-esp8266`

This is also triggering the failed automated tests.

### Logs

Under the covers, the search string is - https://registry.npmjs.org/-/v1/search?text=homebridge-daikin-esp8266+keywords:homebridge-plugin+not:deprecated&size=30

Which gives this message when used in a browser

`{"error":"The 'text' parameter must be between 2 and 64 characters","code":"ERR_TEXT_LENGTH"}`

### Homebridge UI Version

Latest and Beta

### Homebridge Version

1

### Node.js Version

1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

Other (specify in description)

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
From bwp `could probably remove the not deprecated part, and just filter these out of the response, that’s a start, then just truncate the search term so the string is max 64 chars`

**Comment by bwp91** [comment]
should be fixed in 4.64.0

**Comment by NorthernMan54** [comment]
Pls unskip the tests as well...

**Comment by bwp91** [comment]
i will when i merge the changes from 4.64.0 into the beta
