### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by mikesalz** [oznu/homebridge-config-ui-x#226]
I receive the following errors when installing homebridge-config-ui-x.  This is in Docker on a Synology.  Suggestions?

![image](https://user-images.githubusercontent.com/46855061/53187256-bfde5700-35d0-11e9-8f0a-86fb0bb81c9f.png)

**Comment by oznu** [comment]
Hi,

If your running the oznu/homebridge please enable using the environment variable:

https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-UI-with-Docker

This will take care of the setup for you.
