### ISSUE TITLE
Plugin search filters

### ISSUE THREAD

**Issue by dcompane** [oznu/homebridge-config-ui-x#2266]
### Feature Description

What is happening? When we search for a plugin, all plugins that conform to the search are returned. 
What you expect to happen? I would like to see on Verified plugins, or v2.0 compatible, or of a specific developer I trust, or number of plugins in use (maybe a different feature needs to be made available to centrally track it?)
What problems would this new feature solve? Over-abundance of responses makes the choosing of the plugin more complex than it should be

**Comment by bwp91** [comment]
Plugin search has been improved in the v4.65.1 version of homebridge ui

**Comment by marshalisms** [comment]
Update:  Searching the term "homebridge-hubspace" the plugin named "Homebridge Hubspace" would be found.   Just searching for "hubspace" yields no results.

When I search for plugins that I know exist, there is an empty list.  For example search for "hubspace" or "SmartHQ".  On the previous version I know "hubspace" returned several hubspace plugins...along with tons of others that had nothing to do with hubspace.  Is anyone else having this issue?

**Comment by bwp91** [comment]
The plugin search issue should *finally* be resolved in `v4.67.0` that was published this morning (also included in `v5.0.0-beta.26` for users on the beta track).
