### ISSUE TITLE
Plugin search returns unrelated plugins

### ISSUE THREAD

**Issue by justjam2013** [oznu/homebridge-config-ui-x#2272]
### What is happening?
When I search for a plugin, I get a whole number of unrelated plugins before I get matching plugins. These unrelated plugins are all verified plugins, so it looks like it is inserting validated plugins at the top of the search results list regardless of whether they are matches or not.

The search results start with verified plugins:
<img width="1365" alt="Screenshot 2024-12-09 at 10 41 20 PM" src="https://github.com/user-attachments/assets/e17e3b59-0286-4920-a446-5ebb70152d2b"><p>

Finally, after scrolling past 17 verified but unrelated plugins, I get to the actual matches:
<img width="1362" alt="Screenshot 2024-12-09 at 10 41 38 PM" src="https://github.com/user-attachments/assets/da172882-cc69-4a91-9597-495db69c0c43"><p>

I randomly sampled the plugins and none of them had the search term (in this case "esphome") as a keyword in `package.json`. In fact the search term did not appear in the entire github repository.

### What you expect to happen?
I expect to see search results that match my search term(s). I would expect to see verified plugins at the top of the search results only if they are highly relevant.

### Homebridge UI Version

Main: 4.65.0
Dev: 5.0.0-beta.19

### Homebridge Version

Main: 1.8.5
Dev: 1.8.5

### Node.js Version

Main: 20.18.0
Dev: 22.12.0

### Operating System

Main: Ubuntu / Debian (or a variant)
Dev: macOS Sequoia

### Environment Info

Main: Using Docker

### Raspberry Pi Model

Main: Raspberry Pi 4 B

**Comment by justjam2013** [comment]
The current search:
https://github.com/homebridge/homebridge-config-ui-x/blob/feba9aca98d9c90f4a1fee28d6df444a89f25162/src/modules/plugins/plugins.service.ts#L255-L259

using the search term `esphome` generates this GET request:
```
https://registry.npmjs.org/-/v1/search?text=esphome+keywords:homebridge-plugin+not:deprecated&size=30
```
However, this does not return correct search results from NPM. According to the [NPM registry API documentation](https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md), the `text` parameter does a full full-text search with the `+` acting as a logical `AND`. So the search URL above should be a full text search for `"esphome" AND with keyword "homebridge-plugin" AND not deprecated`.

The results do not support the documentation. The above search returns:
```
1  ✅
"searchScore": 50.820904,
"name": "homebridge-esphome-ts",
"keywords": ["homebridge", "esphome", "homebridge-plugin"],
2  ✅
"searchScore": 46.812386,
"name": "@mpathirage/homebridge-gosundsw2-esphome",
"keywords": ["homebridge","homebridge-plugin","ESPHome","Gosund"],
3  ✅
"searchScore": 42.071747,
"name": "@sam-hunt/homebridge-esphome-ts",
"keywords": ["homebridge","esphome","homebridge-plugin"],
4  🚫
"searchScore": 36.984367,
"name": "homebridge-config-ui-x",
"keywords": ["homebridge-plugin",...,"homebridge",...],
5  ✅
"searchScore": 36.513916,
"name": "homebridge-esphome-garagedoor",
"keywords": ["homebridge-plugin","homebridge","esphome",...],
6  ✅
"searchScore": 35.117645,
"name": "homebridge-esphome",
"keywords": ["homebridge-plugin",...,"esphome","homebridge"],
7  🚫
"searchScore": 34.890022,
"name": "homebridge-gsh",
"keywords": ["homebridge-plugin","homebridge",...],
8  ✅
"searchScore": 31.73177,
"name": "@mpathirage/homebridge-accessory-example",
"keywords": ["homebridge","homebridge-plugin","ESPHome",...],
9  🚫
"searchScore": 31.068613,
"name": "homebridge-ring",
"keywords": ["homebridge","homebridge-plugin",...],
10  🚫
"searchScore": 30.763636,
"name": "homebridge-hue",
"keywords": ["homebridge-plugin",...],
11  ✅
"searchScore": 30.443197,
"name": "homebridge-esphome-doorbell",
"keywords": ["homebridge-plugin"],
12  🚫
"searchScore": 30.093561,
"name": "@switchbot/homebridge-switchbot",
"keywords": ["homebridge-plugin",...],
13  ✅
"searchScore": 30.061798,
"name": "homebridge-esphome-ac",
"keywords": ["homebridge-plugin","homebridge-esphome","homebridge-esphome-ac","esphome","esphome-ac",],
14  ✅
"searchScore": 29.662842,
"name": "homebridge-ratgdo-esphome",
"keywords": ["homebridge-plugin"],
15  🚫
16  🚫
17  🚫
18  🚫
19  🚫
20  🚫
21  🚫
22  ✅
"searchScore": 27.801123,
"name": "@seiry/homebridge-esphome-ts",
"keywords": ["homebridge","esphome","homebridge-plugin"],
23  🚫
24  🚫
25  🚫
26  🚫
27  🚫
28  🚫
29  🚫
30  🚫
"searchScore": 26.388968,
"name": "homebridge-ratgdo",
"keywords": ["chamberlain","esphome","homebridge-plugin",...],
```
Out of 30 results, 10 are a match, 20 are ???
Out of the top 10, 6 are a match, 4 are ???

**Comment by justjam2013** [comment]
Unfortunately, the search uses a "search score" which is not used to order search results, but is part of the search itself. Here is an interesting article on how it's calculated: [Increasing an NPM package’s search score](https://itnext.io/increasing-an-npm-packages-search-score-fb557f859300)

And all of the non-matches are verified plugins, so when the code reorders the results, the first plugins are irrelevant to the search:
https://github.com/homebridge/homebridge-config-ui-x/blob/feba9aca98d9c90f4a1fee28d6df444a89f25162/src/modules/plugins/plugins.service.ts#L308

**Comment by justjam2013** [comment]
[NPMS API](https://api-docs.npms.io/) returns a better list of results.

The following query:
```
https://api.npms.io/v2/search?q=esphome+keywords:homebridge-plugin+not:deprecated&size=30
```
returns the following results:

1  ✅
"name": "homebridge-esphome",
"keywords": ["homebridge-plugin",...,"esphome","homebridge"],
2  ✅
"name": "homebridge-esphome-ts",
"keywords": ["homebridge","esphome","homebridge-plugin"],
3  ✅
"name": "homebridge-esphome-garagedoor",
"keywords": ["homebridge-plugin","homebridge","esphome",...],
4  ✅
"name": "homebridge-esphome-doorbell",
"keywords": ["homebridge-plugin"],
5  ✅
"name": "homebridge-esphome-mi-flower-care",
"keywords": ["homebridge-plugin"],
"unstable": true
6  ✅
"name": "@mpathirage/homebridge-gosundsw2-esphome",
"keywords": ["homebridge","homebridge-plugin","ESPHome","Gosund"],
7  ✅
"name": "@mpathirage/homebridge-accessory-example",
"keywords": ["homebridge","homebridge-plugin","ESPHome","Gosund"],

**Comment by justjam2013** [comment]
Comparison of the API calls:
```
https://registry.npmjs.org/-/v1/search?text=esphome+keywords:homebridge-plugin+not:deprecated&size=30

https://api.npms.io/v2/search?q=esphome+keywords:homebridge-plugin+not:deprecated&size=30
```

**Comment by justjam2013** [comment]
Opened PR with code changes: [Remove unrelated plugins from search](https://github.com/homebridge/homebridge-config-ui-x/pull/2280)

**Comment by bwp91** [comment]
Fixed in latest release
