### ISSUE TITLE
Blank tiles on Homebridge UI

### ISSUE THREAD

**Issue by Glyking** [oznu/homebridge-config-ui-x#2285]
### Describe The Bug

There are blank tiles for child bridges and system status, this seems to be related to me updating to the Homebridge image.

### Logs

There are no logs indicating this issue.

### Homebridge UI Version

UI v4.65.0

### Homebridge Version

Homebridge v1.8.5 

### Node.js Version

v22.12.0

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 5

**Comment by bwp91** [comment]
It’s maybe from switching between the beta version of the UI and the stable release?

If you go to the show/hide widgets section and reset, then it should go back to like a new install

**Comment by NorthernMan54** [comment]
Can confirm, reset works

**Comment by Glyking** [comment]
Yes, that works for me. 

 

Thank you.
