### ISSUE TITLE
Raspberry Pi version can not locate all plugins when searching for new plugins

### ISSUE THREAD

**Issue by svandive** [oznu/homebridge-config-ui-x#2287]
### Raspberry Pi Model

Raspberry Pi 4 B

### Describe The Bug

I installed the Raspberry Pi image to a fresh SD-Card and booted in a Raspberry Pi 4b 8GB device.  After installation completed and basic setup, I searched for the primary plugin that I wanted to setup on this instance.  This is Homebridge Kasa Python plugin, created by ZeliardM.  

I have installed HomeBridge on various devices to figure out what device I want to permanently run on and with every other installation, I've always been able to simply go to the Plugins tab in the GUI and search for 'kasa' and find the Homebridge Kasa Python plugin.  However, with the install of the Raspberry Pi image, when I search for 'kasa' on the Plugins tab all I see are 'Homebridge Tplink Smarthome' and 'Homebridge Kasa Lightstrip'. Neither of these are the correct plugin that I expected to see.  When I search 'kasa' from the Homebridge website (e.g. https://homebridge.io) I am able to locate the Homebridge Kasa Python Plugin.

I guess what I am asking is, is there a configuration file that I need to update so the Plugin search function. is searching the correct or all of the known repositories for Plugins?

Thank You....

**Comment by NorthernMan54** [comment]
Under the covers we are running this query against npm, and we are just displaying the results from npm.  It looks like npm has an issue with their database, and this is what you are seeing.  If you use the full plugin name in the query, it will find it, so please use this until npm fixes the issue.

`homebridge-kasa-python`

The query

`https://api.npms.io/v2/search?q=kasa+keywords:homebridge-plugin+not:deprecated`

**Comment by svandive** [comment]
Thank you for the support, I can see the search results now.
