### ISSUE TITLE
config ui x shows the log with AM/PM Timestamps ....

### ISSUE THREAD

**Issue by roe1974** [oznu/homebridge-config-ui-x#229]
Hi
config-ui-x shows the log time stamps in AM/PM time mode .....
Is it possible to show in 24h format ?

thx, Richard

**Comment by oznu** [comment]
Hi,

The UI just displays the raw logs as they are outputted by Homebridge. This feature would have to be implemented in the main Homebridge repo.

**Comment by roe1974** [comment]
no thats not right ..... see the log:

`Feb 25 07:28:07 homebridge-raspi homebridge[2078]: [2/25/2019, 7:28:07 AM] [Lautsprecher Wohnzimmer] Setting power to false
Feb 25 07:28:08 homebridge-raspi homebridge[2078]: [2/25/2019, 7:28:08 AM] [Lautsprecher Wohnzimmer] Mute attempt with success: undefined
Feb 25 07:28:08 homebridge-raspi homebridge[2078]: [2/25/2019, 7:28:08 AM] [Lautsprecher Badezimmer] Mute attempt with success: undefined
Feb 25 07:28:08 homebridge-raspi homebridge[2078]: [2/25/2019, 7:28:08 AM] [Lautsprecher Schlafzimmer] Mute attempt with success: undefined
`

The part ... [2/25/2019, 7:28:08 AM] comes with your plug-in ... on my 3rd homebridge instance there is only the time stamp at the beginning from the line ....

richard

**Comment by oznu** [comment]
`[2/25/2019, 7:28:08 AM]` is generated by homebridge here:

https://github.com/nfarina/homebridge/blob/0d77bb93d33a7b6e158efe4b4d546636d976d5c7/lib/logger.js#L85

You may have disabled timestamps on your other homebridge instance by starting homebridge with the [`-T` option](https://github.com/nfarina/homebridge/blob/0d77bb93d33a7b6e158efe4b4d546636d976d5c7/lib/cli.js#L21)?

**Comment by oznu** [comment]
It seems the pre-built node.js binaries is not built with internationalization support so `toLocalString()` is not working as expected.

node:

```
new Date().toLocaleString('de')
'2/25/2019, 8:25:00 PM'
```

browser:

```
new Date().toLocaleString('de')
"25.2.2019, 20:25:37"
```

**Comment by roe1974** [comment]
ok ... so it is at it is ;-)
thx a lot ! ;-)
