### ISSUE TITLE
Security Panel Accessory UI no longer displays correctly or works.

### ISSUE THREAD

**Issue by jgrimard** [oznu/homebridge-config-ui-x#2294]
### Describe The Bug

No longer able to set Security System (alarm panel) from Homebridge UI.  Something changed when UI changed from Purple to Orange.  I'm using @balansse/homebridge-vivint but I'm not sure if that makes a difference with this issue since it is only an issue in Homebride UI Accessories view.
Refer to two screenshots below.

This is what it looks like now:
![Screenshot 2024-12-23 165933](https://github.com/user-attachments/assets/a22aa535-eba7-4d13-95f4-399500d057d9)
This is what it used to look like:
![Screenshot 2024-12-23 165420](https://github.com/user-attachments/assets/5d2de0ba-71a2-4ab8-b8d0-de9c2c20bba1)

### Homebridge UI Version

4.65.2

### Homebridge Version

v2.0.0-beta.23

### Node.js Version

18.16.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

Using Hyper-V

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @jgrimard thanks for reporting - a fix will be in the next version of the UI.

If you want to try now - you can install `v4.65.3-beta.1`.

**Comment by jgrimard** [comment]
That was fast! Thank you. Nice work.
