### ISSUE TITLE
Incorrect link for support.dev.verified

### ISSUE THREAD

**Issue by jgrimard** [oznu/homebridge-config-ui-x#2295]
### Describe The Bug

The following link is incorrect.  
https://github.com/homebridge/homebridge-config-ui-x/blob/68f9bcda9f1fef88255136742c29a5ee093a8ccc/ui/src/app/modules/support/support.component.html#L172

It should be: `https://github.com/homebridge/homebridge/wiki/Verified-Plugins`

Both bottom links point to the Template Repo
![image](https://github.com/user-attachments/assets/eece691a-00ed-45d3-9029-e3174b9f081f)

### Homebridge UI Version

4.65.2

### Homebridge Version

2.0.0-beta.23

### Node.js Version

18.16.0

### Operating System

Ubuntu / Debian (or a variant)

### Environment Info

None

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @jgrimard thanks for reporting - a fix will be in the next version of the UI.

If you want to try now - you can install `v4.65.3-beta.1`.
