### ISSUE TITLE
Separate "Reset Homebridge" button at bottom of status page

### ISSUE THREAD

**Issue by glyates** [oznu/homebridge-config-ui-x#230]
Please separate the "reset homebridge - homebridge-config-ui-x v3.9.6 - node.js v11.4.0" buttons at bottom of Status page.  It is not intuitive that these are separate and it looks like one big long string.  Caused some unnecessary troubleshooting issues today when helping users. 
![separate 3 buttons in homebridge ui-x](https://user-images.githubusercontent.com/26008802/53529749-6b404d80-3aa2-11e9-99d8-eb4c0090553f.jpg)

**Comment by oznu** [comment]
Links will now underline when the user hovers over them to show they are separate:

![image](https://user-images.githubusercontent.com/3979615/54863170-877d9480-4d99-11e9-831b-89b27015f7b6.png)
