### ISSUE TITLE
Failed to create scheduled instance backup: EPERM: operation not permitted, copyfile ...

### ISSUE THREAD

**Issue by appliko** [oznu/homebridge-config-ui-x#2302]
### Current Situation

I'm trying to setup scheduled backup to a network drive (cifs with automount).
I can see the backups from settings/backup if I manually save there.
Full message I get is this: _Failed to create scheduled instance backup: EPERM: operation not permitted, copyfile '/tmp/homebridge-backup-Yp5NIl/homebridge-backup-0E5C9B6D7E59.1735434800089.tar.gz' -> '/mnt/Fritz/homebridge/homebridge-backup-0E5C9B6D7E59.1735434801024.tar.gz'_

Backup file is still on tmp folder, so I did try manually with same parameters and it works. 
Backup is visible. Only autobackup do not works.
_pi@raspberrypi:/tmp $ sudo -u homebridge cp /tmp/homebridge-backup-Yp5NIl/homebridge-backup-0E5C9B6D7E59.1735434800089.tar.gz /mnt/Fritz/homebridge/homebridge-backup-0E5C9B6D7E59.1735434801024.tar.gz
pi@raspberrypi:/tmp $_ 

I'm going to try to update UI in the while

### Logs

[29/12/2024, 01:13:20] [Homebridge UI] Running scheduled instance backup...
[29/12/2024, 01:13:20] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-Yp5NIl/homebridge-backup-0E5C9B6D7E59.1735434800089.tar.gz
[29/12/2024, 01:13:27] [Homebridge UI] Failed to create scheduled instance backup: EPERM: operation not permitted, copyfile '/tmp/homebridge-backup-Yp5NIl/homebridge-backup-0E5C9B6D7E59.1735434800089.tar.gz' -> '/mnt/Fritz/homebridge/homebridge-backup-0E5C9B6D7E59.1735434801024.tar.gz'

### Homebridge UI Version

v4.65.0 

### Homebridge Version

v1.8.5

### Node.js Version

v22.12.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

None

### Raspberry Pi Model

Raspberry Pi 3 B+

**Comment by NorthernMan54** [comment]
Where your writing the backup to needs to be writeable by the homebridge account.

**Comment by appliko** [comment]
I think this command is proofing that is writable. I did the copy of same temporary backup from original source to original destination as homebridge user, without errors. Copy paste of paths from log.

**pi@raspberrypi:/tmp $** sudo -u homebridge cp /tmp/homebridge-backup-Yp5NIl/homebridge-backup-0E5C9B6D7E59.1735434800089.tar.gz /mnt/Fritz/homebridge/homebridge-backup-0E5C9B6D7E59.1735434801024.tar.gz
**pi@raspberrypi:/tmp $**

Do you know if there is a particularly strict timeout on homebridge side ? 
I'm wondering if automount is adding any delay.

**Comment by NorthernMan54** [comment]
This is where we are copying the file in the code, and it is pretty simple - https://github.com/homebridge/homebridge-config-ui-x/blob/cc19ba22ad3d002f40331a65c6e8003c2279a4c0/src/modules/backup/backup.service.ts#L225

Would a soft mount be better than automount ?

**Comment by appliko** [comment]
I agree, nothing fancy there.
I prefer automount to be sure connection is restored if needed. However I can try a soft mount to check if it is a point.
Looking at old issues related to EPERM copyfile/raspberry/node, I just added "noperm" option to the cifs mount on fstab.
Any way to force an autobackup ? Or to change manually the time ? This would speedup debugging a lot.

**Comment by NorthernMan54** [comment]
Timing of the backup, and set when the UI is started - https://github.com/homebridge/homebridge-config-ui-x/blob/cc19ba22ad3d002f40331a65c6e8003c2279a4c0/src/modules/backup/backup.service.ts#L74

**Comment by appliko** [comment]
It works adding noperm to the fstab entry !
Not sure where is the difference compared to an homebridge user cp, but it works.
