### ISSUE TITLE
Automatic updates and push notifications 

### ISSUE THREAD

**Issue by kennymc-c** [oznu/homebridge-config-ui-x#232]
I think it's great that you can already update Homebridge and all plugins via the UI. Even better would be an option for automatic updates and notifications when something has been updated or an update is available. The notifications could be done via webhooks or alternatively via Pushover/Pushbullet.

**Comment by oznu** [comment]
Hi @kennymc-c,

Thanks for your suggestion. I have no plans to implement this functionality at this time, or do anything to users systems without their input / control.

npm modules have the ability to run pretty much any script they please during installation, and when installing global modules, often with root permissions, with unattended updates users have no chance of spotting something dodgy going on.

**Comment by kennymc-c** [comment]
Ok, i can unterstand that. Only notifications would be enough for me. I am just looking for a way via push messages to know when an update for a plugin is available .

**Comment by brianleesmith** [comment]
Bring this one back up.  I completely agree that a notification mechanism (email, webhook that could be used via IFTTT, etc) would be helpful.

The purpose of a smart home is I shouldn’t be to managing it all the time.  It should tell me when I need to do something...you know, the “smart” part!  :-)
