### ISSUE TITLE
Plugin changelog - show before update

### ISSUE THREAD

**Issue by nicoduj** [oznu/homebridge-config-ui-x#233]
Hi,

First, thank you for your work on this ! 

I have a suggestion : I think it could be better to show the changelog  of a plugin (if it exists)  before updating, with an option to cancel, rather than after, what do you think ?

**Comment by oznu** [comment]
Hi @nicoduj,

Thanks for your suggestion. This will land in the next major release (4.0.x).

The system will attempt to pull the latest release notes from GitHub and display them screen allowing the user to review them before proceeding with an update.

This will only work when the plugin author publishes a release on GitHub with release notes.

**Comment by tobiwashere** [comment]
Hi,

would it be possible to show the changelogs of all versions between the currently installed plugin version and the latest version?
Currently only the changelog of the very latest version is displayed, but if I have installed an older version, that is older than one release behind the latest update, I do miss the changes between my installed version and the latest update.

For example:
My installed plugin version: 1.0
Released updates of this plugin: 1.1, 1.2 and 1.3
Displayed changelog in config ui x: only 1.3 and not 1.1 and 1.2 (so I'm missing the changes of 1.1 and 1.2 here and have to look them up manually)
