### ISSUE TITLE
Wrong server status of running services only on iOS browsers

### ISSUE THREAD

**Issue by kennymc-c** [oznu/homebridge-config-ui-x#238]
When I access the config page on my iPhone X / iOS 12.1.4, the services (Homebridge / Console) are displayed as not running with both safari and chrome. The search for Homebridge updates also takes forever. On macOS they are displayed as running and that's correct. I also can't reproduce it by changing the user agent on the Mac. I've had this problem before when I haven't switched to the Docker Image. But after that it didn't happen anymore. Now it has occurred again. Could it be related to the new update to 3.10?

**Comment by oznu** [comment]
It sounds like the web socket connection is not being established.

I can't replicate this issue on the same version of iOS. Perhaps try clearing your browser cache / try a private tab?

The changes in 3.10.0 were mainly cosmetic.

**Comment by kennymc-c** [comment]
Clearing Browser cache or using a private tab didn‘t help

**Comment by oznu** [comment]
Changes in 4.0.0 to how WebSockets are handled may have fixed this.

**Comment by kennymc-c** [comment]
I'm afraid not. What I noticed before the update was that when I opened the log an error message appeared saying that the connection to the WebSocket could not be established. This message does not appear any more and the log remains completely empty. However, if you wait a while, the status for the console changes to green. Nevertheless the log remains empty.

**Comment by oznu** [comment]
@kennymc-c, I've added a new flag `websocketCompatibilityMode`. This will allow `socket.io` to fallback to using xhr/polling if a native WebSocket connection cannot be established. After upgrading to 4.0.2 you can enable this by setting `"websocketCompatibilityMode": true`. Example:

```js
"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "websocketCompatibilityMode": true,
      ... // the rest of your config
    }
]
```

**Comment by kennymc-c** [comment]
Enabling websocketCompatibilityMode solved my problem. Thanks!

**Comment by oznu** [comment]
Thanks for confirming!
