### ISSUE TITLE
Calling custom restart using init.d always fails

### ISSUE THREAD

**Issue by aveach** [oznu/homebridge-config-ui-x#240]
Config:
```
{
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "theme": "dark-mode",
            "restart": "/etc/init.d/homebridge restart",
            "log": {
                "method": "file",
                "path": "/var/log/homebridge.log"
            }
```
init.d is setup using the steps found in the Homebridge wiki:
`https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-initd`

I can call `sudo /etc/init.d/homebridge restart` directly on the Pi but when I run it from the config UI I always get:

```
[3/28/2019, 1:04:59 PM] [Config] Executing restart command: /etc/init.d/homebridge restart
[3/28/2019, 1:05:10 PM] [Config] Restart command exited with an error. Failed to restart Homebridge.
```
even if I change the call to use sudo, -E, -n, etc...

**Comment by oznu** [comment]
Have you tried leaving removing the restart attribute from the config? If no restart command is specified then Homebridge will just kill itself and then init.d should do its job and bring it back up - if it's configured that way.

Otherwise, if you're OS supports it, systemd is the way to go.

**Comment by aveach** [comment]
The init.d script doesn't auto-restart the process if its killed unless `/etc/init.d/homebridge restart` is specifically called. 

Does "sudo": true affect the restart call if it's custom? Would adding that help?

**Comment by oznu** [comment]
sudo: true is not added if a custom restart command is used.

Try adding a `&` to the end of the command. I suspect the init.d script is being terminated when the parent process is killed and I think this should detach it.

**Comment by aveach** [comment]
Yup, looks running it in the background works. Should have tried that before opening up an issue... Thanks, appreciate the help! Sorry for the churn.

**Comment by aveach** [comment]
Looks like I jumped the gun on this one. It does call the restart and the UI shows a "successfully restarted" pop up but it doesn't actually restart the server.

**Comment by oznu** [comment]
Not sure sorry. Is it possible to make init.d auto-restart or for you to use systemd instead?

**Comment by Leprechaun91** [comment]
100% the same at mine.
Didnt find a way to solve it anyway

**Comment by oznu** [comment]
Swapping to Systemd will resolve this. I've written up a guide on how to setup Homebridge with Homebridge Config UI X using systemd on Raspbian, Ubuntu and Debian:

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)
