### ISSUE TITLE
Node Module Version Error with Node.js version 11.12.0

### ISSUE THREAD

**Issue by jamesg311** [oznu/homebridge-config-ui-x#241]
When I startup Homebridge, I receive the error below. tried searching around for how to fix, even blasted my home bridge and npm installations but can't get past this error.

[Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Thanks for any help.

**Comment by oznu** [comment]
This occurs when you upgrade Node.js to a different major version.

Try uninstalling / reinstalling:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

If that fails, do this (this may take a while on something like a Raspberry Pi):

```
cd $(npm -g prefix)
cd lib/node_modules
npm rebuild
```
