### ISSUE TITLE
Discovering other homekit devices.

### ISSUE THREAD

**Issue by NajibNour** [oznu/homebridge-config-ui-x#242]
Good morning,

I have just installed this and I cannot seem to get it to detect my lifix lights. those lights are not connected through home bridge but are straight to home kit. This seems like normal behaviour but I was wondering if there was an easy way for it to discover them without finding a plugin for each device on my network?

Thanks.

**Comment by bohtho** [comment]
Homebridge (and config-x) can only see devices added to HomeKit by Homebridge. You could try to attach your lights through a Homebridge plugin instead (of the native solution) to be able to interact with both through HomeKit and Homebridge. The added benefit of then being able to interact with them through any further system connected to Homebridge again.

**Comment by NajibNour** [comment]
Perfect thanks for the clarification!!
