### ISSUE TITLE
password change

### ISSUE THREAD

**Issue by Leprechaun91** [oznu/homebridge-config-ui-x#245]
Hey,

maybe I'm just way to stupid, but how do i change the password? 
I know its stored into the auth.json file - but in a hashed way and as long as I dont know which algorithm is used, i cannot replace it with another one.

Sorry for te stupid question :-D

**Comment by oznu** [comment]
You can do it via the UI after logging in using the Users page; or if you delete the auth.json file and restart it will reset the default of admin:admin.

**Comment by ebo** [comment]
I was able to change the password in the UI by going to the drop-down panel in the upper right hand corner (the three dots) -> "User Accounts" and then click on "Edit".  From there you can change the password.  Hope this helps.  I was not able to find it searching the net.

**Comment by sinaghenaat** [comment]
> I was able to change the password in the UI by going to the drop-down panel in the upper right hand corner (the three dots) -> "User Accounts" and then click on "Edit". From there you can change the password. Hope this helps. I was not able to find it searching the net.

hi how you can do it? Please explain it
