### ISSUE TITLE
Installing Plugins won't work

### ISSUE THREAD

**Issue by Phoenix-DH** [oznu/homebridge-config-ui-x#247]
Hi,

I got an raspberry pi 2 with homebridge installed and running as user homebridge.
In homebridge-config-ui-x I enabled "SUDO MODE".
Everything is working, but installing PLUGINS via WEBUI not.
The file fur sudo use I created in /etc/sudoers.d for pw less

I get the following:

> USER: homebridge
DIR: /usr/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-fritz@latest
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/homebridge/.npm'
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
Command failed. Please review log for details

When I create the directory, it will also not work ...
Has somebody some hint how to get it working?

I thought that with sudo I should have the permissions.

**Comment by oznu** [comment]
Could you try this fix?

https://github.com/oznu/homebridge-config-ui-x/issues/198#issuecomment-476911233

**Comment by Phoenix-DH** [comment]
Hey,

I already saw this and tried. I need this solution to get log showing working with sudo, but installing plugins does still not work
`[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_SETGID CAP_NET_RAW CAP_NET_ADMIN CAP_SETUID CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target`

**Comment by Phoenix-DH** [comment]
For updates the same.
The rights on /home/homebridge are default, created by the user account itself - homebridge:homebridge.
Also changing the rights to root will not work.

Thank you for the support.

**Comment by oznu** [comment]
npm uses the $HOME/.npm directory as a cache; it does not look like there is a way to turn this off, only change it's location. For some reason or another it looks like there are some permission problems when it is attempting to create this cache.

Try creating the directory manually and giving the homebridge user permissions:

```
rm -rf /home/homebridge/.npm
mkdir /home/homebridge/.npm
chown -R homebridge: /home/homebridge
```

**Comment by Phoenix-DH** [comment]
Homebridge is my user running the bridge itself, directory has been created already manually ... I also tried this:
![Rights](https://user-images.githubusercontent.com/44058592/55699299-8324be80-59ca-11e9-8571-abeed29f28bf.PNG)

There everything is fine in my opinion.
When I then try to install an plugin I get now this:
![error screen](https://user-images.githubusercontent.com/44058592/55699325-9f286000-59ca-11e9-93f9-13fae285d5d1.PNG)

Like I said, I have to use sudo, maybe it has something to do with this?

Passwordless sudo in the system itself is working. I double checked this, I never have been forced to enter the password somewhere. File in /etc/sudoers.d/homebridge created and added the full set of rights to everything:
> homebridge ALL=(ALL) NOPASSWD: ALL

Homebridge user has this rights:
![groups](https://user-images.githubusercontent.com/44058592/55699414-19f17b00-59cb-11e9-8097-6973449b1416.PNG)

I moved the user from the original PI user to the homebridge user because I had some issues with this user and some plugins. When using the PI user, everything was fine. All files for the service have been changed. Service has been restarted, PI not booted.

**Comment by Phoenix-DH** [comment]
I did an additional check ....
When I take the cmd out of the aupdate/install window from homebrtidge-ui-x and use terminal with
`sudo -su - homebridge`
as the user which is running homebridge ... then everything is working fine ...

Only via WebGUI I have thos issues.

**Comment by oznu** [comment]
Hi @Phoenix-DH,

I did some testing today on Ubuntu 18.04 and Raspbian. Adding a few more items to the caps list in the systemd service seemed to be required to make everything work as it should:

```
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW
```

Then:

```
systemctl daemon-reload
systemctl restart homebridge
```

**Comment by Phoenix-DH** [comment]
Hey, great! Thank you!
Just added the changes and tried to install and uninstall a package!

Works great!
