### ISSUE TITLE
Enhancement request - config validation and auto restore 

### ISSUE THREAD

**Issue by askovi** [oznu/homebridge-config-ui-x#248]
I’d like to have the config self validate with json lint before saving. This way it can prevent homebridge crashes that require ssh to go fix the config because the UI won’t come back on. 

The 2nd feature probably doesn’t belong here as it should probably be implemented directly in homebridge but auto restoring a recent config backup in case of a crash loop would be really amazing. Is this even possible to detect?

**Comment by oznu** [comment]
Hi @askovi,

The config editor should be validating the it's valid JSON already, as well as doing some basic structural checks. Is this not working for you?

**Comment by oznu** [comment]
The next version (4.0.x) will allow you to run the UI in stand-alone mode, meaning, if you configure it to do so, the UI will still run even if Homebridge is crashing due to bad config.

```shell
# If you start homebridge like this:
homebridge -U /var/lib/homebridge -I

# You'll be able to run the UI in standalone mode like this:
homebridge-config-ui-x -U /var/lib/homebridge -I
```

I'll post a guide on the wiki once 4.0.0 is live.
