### ISSUE TITLE
(nginx) reverse proxy in subdirectory

### ISSUE THREAD

**Issue by JanJastrow** [oznu/homebridge-config-ui-x#256]
Hi there,

I'm trying to use homebridge-config-x with an nginx reverse proxy.
It works fine, when I "map" the reverse proxy to ```/``` but it does not work when I'm trying to use ```/homebridge```

My config
```
        location /homebridge/ {
                proxy_pass              http://127.0.0.1:8040/;
                proxy_http_version      1.1;
                proxy_buffering         off;
                proxy_set_header        Host $host;
                proxy_set_header        Upgrade $http_upgrade;
                proxy_set_header        Connection "Upgrade";
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

Any idea how I can make it work?

**Comment by oznu** [comment]
Hi @JanJastrow,

See existing issue: https://github.com/oznu/homebridge-config-ui-x/issues/184

The UI / Angular AOT prebuild makes it a bit challenging to run off a custom path unfortunately - I've spent a fair few hours trying to find a nice solution but have yet to come up with something.

**Comment by SylvainCecchetto** [comment]
Any news concerning this issue?
I am building a package of Homebridge for YunoHost but theirs approval procedure requires that the app works on a subdirectory with Nginx :-/

Thank you!
