### ISSUE TITLE
Added the ability for the plugin to run as a separate service.....

### ISSUE THREAD

**Issue by roe1974** [oznu/homebridge-config-ui-x#258]
How can this be configured ? I didn't found anything in the readme :-)

Richard

**Comment by roe1974** [comment]
ok ... i will test it :)
is it now possible to manage more homebridge instances with one standalone config-ui-x service ?
richard

**Comment by oznu** [comment]
> is it now possible to manage more homebridge instances with one standalone config-ui-x service ?

No sorry.

**Comment by roe1974** [comment]
so one systemd config-ui-x service for each homebridge instance .... right ?

richard

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-config-ui-x/wiki/Standalone-Mode

**Comment by skop1986** [comment]
I get this error! Help please

pi@kop:~ $ sudo systemctl daemon-reload
pi@kop:~ $ sudo systemctl enable homebridge-config-ui-x
pi@kop:~ $ sudo systemctl start homebridge-config-ui-x
Failed to start homebridge-config-ui-x.service: Unit homebridge-config-ui-x.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status homebridge-config-ui-x.service' for details.

**Comment by oznu** [comment]
Can you show the contents of /etc/systemd/system/homebridge-config-ui-x.service?

**Comment by skop1986** [comment]
@oznu 
[Unit]
Description=Homebridge Config UI X
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=$(which homebridge-config-ui-x) \$HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target

**Comment by oznu** [comment]
@skop1986 - you need to paste the command from the wiki in a single command - or populate the variables in the command yourself.

ExecStart=`$(which homebridge-config-ui-x)` $HOMEBRIDGE_OPTS

**Comment by skop1986** [comment]
@oznu 

[Unit]
Description=Homebridge Config UI X
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=$homebridge-config-ui-x -U /home/pi/.homebridge -I \$HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target

**Comment by oznu** [comment]
@skop1986, not quite 😄 

Type this command at the command line:

```
which homebridge-config-ui-x
```
Then whatever it returns put in the file:

```
/homebridge # which homebridge-config-ui-x
/usr/local/bin/homebridge-config-ui-x
```

```
ExecStart=/usr/local/bin/homebridge-config-ui-x $HOMEBRIDGE_OPTS
```

Don't add any extra variables to the line - these need to go in the `/etc/default/homebridge` file so both the UI and Homebridge are running the same config.

**Comment by roe1974** [comment]
for multiple homebridge instances i need multiple config-ui-x standalone services running ?

**Comment by oznu** [comment]
@roe1974 - yep, no change there.

**Comment by skop1986** [comment]
@oznu 

# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file an$
HOMEBRIDGE_OPTS=-U /usr/bin/homebridge-config-ui-x

# If you uncomment the following line, homebridge will log more
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*
# To enable web terminals via homebridge-config-ui-x uncomment the following li$
#HOMEBRIDGE_CONFIG_UI_TERMINAL=1

**Comment by skop1986** [comment]
@oznu 

I can't start homebridge

● homebridge-config-ui-x.service - Homebridge Config UI X
   Loaded: loaded (/etc/systemd/system/homebridge-config-ui-x.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-05-04 10:37:07 MSK; 545
  Process: 2669 ExecStart=/usr/bin/homebridge-config-ui-x $HOMEBRIDGE_OPTS (code=exited, status
 Main PID: 2669 (code=exited, status=217/USER)

май 04 10:37:07 kop systemd[1]: homebridge-config-ui-x.service: Failed with result 'exit-code'.
~
