### ISSUE TITLE
Apache Reverse Proxy WebSocket Connection Not Working After 4.x Update

### ISSUE THREAD

**Issue by iShift** [oznu/homebridge-config-ui-x#259]
Hi, i update to last version and now WSS don't work, in safari console i got this:

![Снимок экрана 2019-04-17 в 21 09 46](https://user-images.githubusercontent.com/426427/56310682-286f2d80-6155-11e9-9d11-0d9a7954f496.png)
(translate: connection established)

i take config from wiki:
![Снимок экрана 2019-04-17 в 21 10 29](https://user-images.githubusercontent.com/426427/56310737-4177de80-6155-11e9-8490-e1dde5786ed2.png)

**Comment by iShift** [comment]
in consol i get:
`socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNTU1NTI0MzcyLCJleHAiOjE1NTU1NTMxNzJ9.AvmmI-Ea3ZMA2GtNN2pCP-NnrnHD5bjGta6vhVeDfSs&EIO=3&transport=websocket' failed: Status line does not end with CRL`

**Comment by oznu** [comment]
The template in the wiki was missing a `%` before `{REQUEST_URI}` - and the trailing slash after the port needs to be removed. The old WebSocket server implementation didn't care, but socket.io does.

Replace this line in your config:

```apache
 RewriteRule .* ws://localhost:8081/{REQUEST_URI} [P]
```

with this:

```apache
RewriteRule .* ws://localhost:8081%{REQUEST_URI} [P]
```

Full example:

```apache
<Location />
    ProxyPass http://localhost:8081/
    ProxyPassReverse http://localhost:8081/
    RewriteEngine on
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule .* ws://localhost:8081%{REQUEST_URI} [P]
</Location>
```

Updated Wiki:

https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Apache

**Comment by iShift** [comment]
Thanks, now works!
