### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by patrik72** [oznu/homebridge-config-ui-x#26]
Update is offered regardless of Wanted or not, this could lead to incompatibilities. Updates should only be offered fort the wanted version.

npm -g outdated
Package           Current  Wanted  Latest  Location
homebridge-fritz   0.5.12  0.5.12   0.6.0

**Comment by oznu** [comment]
For this to work it would depend on plugin authors using semver properly. 

Ging from 1.5.12 -> 1.6.0, there should not be any breaking changes as it's only a semver minor. Though while it's pre-1.0.0 the rules don't apply yet and anything can be a breaking change.

https://semver.org/

> MINOR version when you add functionality in a backwards-compatible manner

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I think the way it's currently implemented works, the updates are not happening automatically and the users can see what version will be installed before updating which leaves the decision (and consequences) of updating in their hands.
