### ISSUE TITLE
ipv6 lost

### ISSUE THREAD

**Issue by Alex7802** [oznu/homebridge-config-ui-x#260]
Hello. Just updated homebridge-config-ui-x to 4.0.2 and lost connectivity to web interface: home bridge listen only on ipv4. 
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      22230/homebridge-co 

but, other plugins and main program use ipv6 well. 
tcp6       0      0 :::51826                :::*                    LISTEN      22203/homebridge    
tcp6       0      0 :::39475                :::*                    LISTEN      22203/homebridge  
Early that works fine. Please fix.

**Comment by oznu** [comment]
Hi @Alex7802,

Thanks for raising this issue, it has been fixed in 4.0.3.
