### ISSUE TITLE
cannot load GUI after v4

### ISSUE THREAD

**Issue by ivan-aleksandrov** [oznu/homebridge-config-ui-x#262]
I noticed that after upgrading to v4 i can access GUI only if I use localhost and not via IP. I'm using it in docker so it is impossible to access GUI via 'localhost'.

I think it might be related to this in main.ts:

`// setup cors
  app.enableCors({
    origin: ['http://localhost:8080', 'http://localhost:4200'],
  });`

**Comment by oznu** [comment]
Can you show the startup logs?

**Comment by mspiridakis** [comment]
Same here. Startup logs look fine except this:
`[0;37m[4/21/2019, 12:20:15 AM][0m [0;36m[homebridge-config-ui-x][0m [0;33mConsole v4.0.4 is listening on undefined port 8080[0m.` 
Homebridge working perfectly, but no access to GUI (haven't tried to call it locally since its a headless pi).

**Comment by oznu** [comment]
Thanks, can you show the config for the UI from your config.json?

**Comment by oznu** [comment]
After looking at my code... are you running in docker so don't have any config set for the UI (which is a perfectly valid setup)?

**Comment by mspiridakis** [comment]
There aren't any (config-ui) entries in my config.json.

**Comment by mspiridakis** [comment]
Yes. Your docker

**Comment by mspiridakis** [comment]
On chrome I get a :

This site can’t be reached 192.168.10.39 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I tried the usual stuff(delete cache etc)

**Comment by oznu** [comment]
Yep, sorry about this, I'll push up a fix in a moment. I see what I did wrong!

**Comment by mspiridakis** [comment]
Ok. Keep up the good work man.

**Comment by mspiridakis** [comment]
Is there a quick fix to access it or do I have to pull the docker from the start?

**Comment by oznu** [comment]
A new docker image is building right now; if you don't want to pull that, you can exec into the container and run:

```
npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by mspiridakis** [comment]
One last question (If you have the time). Where is the homebridge container folder on a pi?

**Comment by oznu** [comment]
@mspiridakis if you followed the guide on oznu/homebridge it should be under `~/homebridge`.

**Comment by oznu** [comment]
A new docker image has been published that implements this fix also. User's who encountered this bug and need to restore access to the GUI have two options.

1. Exec into the container and manually update:

```
npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

2. Pull the latest version of oznu/homebridge and recreate the container. If you're using `docker-compose` do it this way:

```
docker-compose pull homebridge
docker-compose up -d
```

**Comment by fraho67** [comment]
Hi oznu,

I'm running your config ui on a synology. Today either your Homebridge UI or docker was updated (don't know what it was). Since then I'm getting "This site can’t be reached xxxxxxx refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED"

I uninstalled the UI as well as docker (no files were left) and reinstalled everything but it's no more working.

**Comment by canoben** [comment]
> Hi oznu,
> 
> I'm running your config ui on a synology. Today either your Homebridge UI or docker was updated (don't know what it was). Since then I'm getting "This site can’t be reached xxxxxxx refused to connect.
> Try:
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_REFUSED"
> 
> I uninstalled the UI as well as docker (no files were left) and reinstalled everything but it's no more working.

Yeah, I'm having the same connection. As I just re-installed everythign I suppose there is no need to try the commands above as my docker image should already include the fix, isn't it?
