### ISSUE TITLE
After update from UI cannot start it anymore

### ISSUE THREAD

**Issue by stich86** [oznu/homebridge-config-ui-x#263]
Hi,

i've updated the HB (first) and UI (after second restart) itself from the UI (i'm running oznu/homebridge Docker container) without update the container itself.

After restart HB running again with anyissue, then update the UI plugin on second reboot doesn't start anymore with this error:

```
(node:7717) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:133215:47)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:133201:58)
(node:7717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

I've already tried to destroy container, pull latest version and deploy it again without success. May be I need to destroy also the volume mounted as /homebridge and setup it again on my HomeKit App?

Thanks in advance!

**Comment by oznu** [comment]
I see what the problem is.. fix incoming.

**Comment by oznu** [comment]
Updating the plugin or pulling the latest version of the docker image should fix this. Thanks for reporting.

**Comment by stich86** [comment]
thanks man! 
it works now :)
