### ISSUE TITLE
After Update issue with webinterface (other computer)

### ISSUE THREAD

**Issue by RainbowStar1980** [oznu/homebridge-config-ui-x#264]
Hi,

i update my config-ui-x Plugin. 
Since this update the Webbrowser local on the Raspberry pi works fine, only remote Connections from other Computers are unauthorized. Deinstall and reinstall didnt solve the Problem.

The Homebridge self runs in multiple instances and all devices are avaiable. Only the web interfaced  in malfunctioning. 

Anyway the UI is very nice and usefull! 

error message in the browser : api/Plugin 401 
*UPDATE*
seems to be only one instance affected by this issue. Al other instaces are not affected and work fine.

For any Suggestion of solving this simple error i would be very thankful

**Comment by oznu** [comment]
Clearing the local storage for the website in the browser should fix this.
