### ISSUE TITLE
Error after update to newest version

### ISSUE THREAD

**Issue by Bartjuh4** [oznu/homebridge-config-ui-x#265]
After the update to the latest version i got this error when restarting homebridge:

[4/22/2019, 9:59:48 PM] [homebridge-config-ui-x] SyntaxError: Unexpected token (

Remove and reinstall tried several times but with zero results.

Version i installed: 4.0.6

**Comment by oznu** [comment]
What version of Node.js are you running?

**Comment by BindersFullOfWomen** [comment]
I'm having the same issue. 

Using Node.js v. 8.9.4 on Windows 10

**Comment by oznu** [comment]
@BindersFullOfWomen - your issue is a different one, Node.js 10 or higher is required when running on Windows as node-pty requires this.
