### ISSUE TITLE
will not load QR code/digit code, or status

### ISSUE THREAD

**Issue by cmdshft** [oznu/homebridge-config-ui-x#267]
I am running homebridge via systemd on boot and homebridge is in fact running and iOS is able to use it. However, I am unable to get homebridge-config-ui-x to see the status of homebridge.

I used this guide for auto-running homebridge: https://timleland.com/setup-homebridge-to-start-on-bootup/

How can I correct this? I used "sudo npm install -g --unsafe-perm homebridge-config-ui-x" to install.

![Screen Shot 2019-04-24 at 1 46 30 AM](https://user-images.githubusercontent.com/8571823/56635422-8e672380-6633-11e9-90a0-8f8a7e2fe795.png)

**Comment by oznu** [comment]
It looks like the websocket is not connecting. Are you behind a reverse proxy?

**Comment by cmdshft** [comment]
It’s running on a RPI that is used as a pi-hole. Is there something I need to whitelist?

**Comment by oznu** [comment]
What does the javascript console say (Open developer tools).

**Comment by cmdshft** [comment]
![Screen Shot 2019-04-24 at 1 59 09 AM](https://user-images.githubusercontent.com/8571823/56636174-f880c800-6635-11e9-813b-aae528170fc0.png)

![Screen Shot 2019-04-24 at 2 00 17 AM](https://user-images.githubusercontent.com/8571823/56636178-fb7bb880-6635-11e9-8cdf-4efb826c3f98.png)

**Comment by oznu** [comment]
That all looks fine, what about the systemd homebridge logs?

**Comment by cmdshft** [comment]
Apr 24 06:04:01 pihole systemd[1]: Started Node.js HomeKit Server.
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Loaded config.json with 1 accessories and 1 platforms.
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] ---
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Loaded plugin: homebridge-config-ui-x
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Registering platform 'homebridge-config-ui-x.config'
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] ---
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Loaded plugin: homebridge-xbox-one
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Registering accessory 'homebridge-xbox-one.Xbox'
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] ---
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Loading 1 platforms...
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] [Config] Initializing config platform...
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] [Config] Spawning homebridge-config-ui-x with PID 578
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] Loading 1 accessories...
Apr 24 06:04:08 pihole homebridge[352]: [4/24/2019, 6:04:08 AM] [Xbox] Initializing Xbox accessory...
Apr 24 06:04:08 pihole homebridge[352]: Setup Payload:
Apr 24 06:04:08 pihole homebridge[352]: X-HM://0023ISYWYDMM3
Apr 24 06:04:08 pihole homebridge[352]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Apr 24 06:04:08 pihole homebridge[352]:                                                       
Apr 24 06:07:30 pihole homebridge[6229]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Apr 24 06:07:30 pihole homebridge[6229]:                        
Apr 24 06:07:30 pihole homebridge[6229]:     ┌────────────┐
Apr 24 06:07:30 pihole homebridge[6229]:     │ 031-45-154 │
Apr 24 06:07:30 pihole homebridge[6229]:     └────────────┘
Apr 24 06:07:30 pihole homebridge[6229]:                        
Apr 24 06:07:30 pihole homebridge[6229]: [4/24/2019, 6:07:30 AM] Homebridge is running on port 51826.
Apr 24 06:07:36 pihole homebridge[6229]: [4/24/2019, 6:07:36 AM] [homebridge-config-ui-x] Console v4.0.6 is listening on :: port 8080

**Comment by oznu** [comment]
That looks fine to.. hmm what about your config.json?

**Comment by cmdshft** [comment]
I installed the xbox accessory to test rpm in this, ignore it.
```
{
                "bridge": {
                "name": "Homebridge Pi",
                "username": "CC:22:3D:E3:CE:55",
                "port": 51826,
                "pin": "031-45-155"
        },
        "description": "This is an example configuration",
        "platforms": [{
                "platform": "config",
                "name": "Config",
                "port": 8080,
                "sudo": false
        }],
        "accessories": [{
                "accessory": "Xbox",
                "name": "Xbox",
                "ipAddress": "<Xbox IP address>",
                "liveId": "<Xbox Live ID>"
        }]
}
```

**Comment by oznu** [comment]
Can you try adding `"websocketCompatibilityMode": true` to the UI config?

**Comment by cmdshft** [comment]
So, not sure what happened. I added that line, restarted homebridge and it didn’t work. I deleted the line from config.json, restarted homebridge and logged in to the panel and it’s working.

**Comment by oznu** [comment]
Great, I couldn't see anything wrong in the logs or in the console, so I'll close this for now.
