### ISSUE TITLE
Extension for Monitoring multiple Homebridge instances?

### ISSUE THREAD

**Issue by Nastras** [oznu/homebridge-config-ui-x#27]
Hello, I have an idea for a cool extension for your plugin. Maybe it is possible to install this.

Many users use multiple Homebridge instances, would not it be great to have a monitor for all Homebridge instances in your plugin where all Homebridge statuses are displayed?

**Comment by oznu** [comment]
Hi @Nastras,

Thanks for your suggestion.

Similar request to this: https://github.com/oznu/homebridge-config-ui-x/issues/17
My response: https://github.com/oznu/homebridge-config-ui-x/issues/17#issuecomment-359729771

I have no plans to extend the plugin to monitor multiple homebridge instances at this time, but I welcome any contributions/pull requests that can implement this in a user friendly and secure way.
