### ISSUE TITLE
No UI on docker

### ISSUE THREAD

**Issue by RienduPre** [oznu/homebridge-config-ui-x#270]
Hi,

I installed your HB docker on a QNAP, this works without errors.

Then I installed you config-ui-x succesfully, as described no config.json platform entry for the plugin (correct ?) but I cannot connect to the ui using ip adres and port 8080.

When I create a config.json platform it works, but I don't see any docker menu on the top bar.

What am I doing wrong here ?

**Comment by oznu** [comment]
Make sure you're enabling the UI using the environment variable:

https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-UI-with-Docker

```
HOMEBRIDGE_CONFIG_UI=1
HOMEBRIDGE_CONFIG_UI_PORT=8080
```

I'm not sure where you set this in the QNAP UI - you may have to recreate the container.

**Comment by RienduPre** [comment]
Thank you !!
Solved.
