### ISSUE TITLE
Where are the img files at on disk?

### ISSUE THREAD

**Issue by cmdshft** [oznu/homebridge-config-ui-x#271]
I want to change the background of the login UI, but I cannot find them on the disk. Where are they located?

**Comment by oznu** [comment]
Hi @cmdshft,

To change the background wallpaper, just enter the full path to the image you want to use in the settings, which will populate the `loginWallpaper` option:

![image](https://user-images.githubusercontent.com/3979615/56859499-3e8bb200-69cf-11e9-9071-ccd02e0208a6.png)

You may have to force a hard refresh after setting this to clear the cache.
