### ISSUE TITLE
[Enhancement] Plugins that can be updated on top

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#275]
I'm not sure if this already was the case with an earlier version of the plugin, but using @4.1.0 plugins that can be updated are not listet on top of the list.
So at the moment you have to scroll through the entire list to have an eye on what plugin has an update available. 
Would be helpful to see these types of plugins sorted on top.
Or maybe there is an even more useful method available?
Thanks a lot for your work and sharing.

**Comment by oznu** [comment]
Thanks, this should be how it works - I'll push up a fix soon.
