### ISSUE TITLE
Web interface not working after upgrade to the latest

### ISSUE THREAD

**Issue by zonehun** [oznu/homebridge-config-ui-x#278]
Dear oznu,

I upgraded to the v4.1.0 and my browser (Chrome) said Connection refused. I did not change anything in my config.json, just upgraded the plugin. Browser cache cleared, nothing happened.

I have Nodejs v11.15.0 on a Raspbian.

After restarting Homebridge no errors were occured. Tried to check all related log files but I did not find any error. 

Do you have any idea about this? Or how to start the investigation?

Thank you.

**Comment by zonehun** [comment]
Here is my config about the plugin:
```
		{
			"platform": "config",
			"name": "Config",
			"port": 8080,
			"restart": "sudo -n systemctl restart homebridge",
			"log": {
				"method": "custom",
				"command": "sudo journalctl -o cat -n 100 -f -u homebridge"
		        },			
			"sudo": true
		},

```

**Comment by zonehun** [comment]
Hmmm. Now I found a weird line in the homebridge log:

May  1 21:12:59 raspi homebridge[17259]: [5/1/2019, 9:12:59 PM] #033[36m[homebridge-config-ui-x]#033[0m #033[31mError: Cannot find module '../build/Debug/pty.node'#033[0m

**Comment by zonehun** [comment]
If I switched back to v3.11.0 Homebridge is strating to work normally. But the web interface is not working :(

**Comment by oznu** [comment]
Please try:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

Note any errors during installation.

**Comment by zonehun** [comment]
Thank you! Your suggested solution was worked. Issue should be closed.

**Comment by zonehun** [comment]
Thank you! Your suggested solution was worked.
