### ISSUE TITLE
Can you please bring back the backup button for the config(s)?

### ISSUE THREAD

**Issue by palasinio** [oznu/homebridge-config-ui-x#279]
Hi,

after the update to v4 I discovered that there is no longer a backup button (save as) for the config.
Could you please bring this button back?

regards,

**Comment by oznu** [comment]
Done in 4.2.0

**Comment by Scialla** [comment]
i've installed 4.3.0 and backup button is not present (do not come back in 4.2.0 for me)

**Comment by palasinio** [comment]
Maybe you need to clear the  browsercache?
Which browser on which system? SSL enabled?

**Comment by Scialla** [comment]
Yes, you are right!
Thanks and sorry..

Inviato da iPhone
