### ISSUE TITLE
Error running on port 80

### ISSUE THREAD

**Issue by Cerberus74** [oznu/homebridge-config-ui-x#28]
Setting port to '80' causes homebridge not to start.

`Feb  8 21:16:46 HomeBridge homebridge[1237]: [2018-2-8 21:16:46] [Config] Using Form Authentication
Feb  8 21:16:46 HomeBridge homebridge[1237]: Error: listen EACCES 0.0.0.0:80
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at Object._errnoException (util.js:1003:13)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at _exceptionWithHostPort (util.js:1024:20)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at Server.setupListenHandle [as _listen2] (net.js:1349:19)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at listenInCluster (net.js:1407:12)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at Server.listen (net.js:1495:7)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at HomebridgeConfigUi.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/index.ts:39:17)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at Generator.next (<anonymous>)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/index.js:4:58)
Feb  8 21:16:46 HomeBridge homebridge[1237]:     at <anonymous>
Feb  8 21:16:46 HomeBridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb  8 21:16:46 HomeBridge systemd[1]: homebridge.service: Unit entered failed state.
Feb  8 21:16:46 HomeBridge systemd[1]: homebridge.service: Failed with result 'exit-code'.`

**Comment by oznu** [comment]
Hi @Cerberus74,

Only privileged users (i.e. root) can run services on ports 0-1024.

While I'm not going to provide support for running on ports below 1024, you can get it working by adding a line to your `systemd` service.

To allow Homebridge to bind to privileged ports (like port 80) you need to add `AmbientCapabilities=CAP_NET_BIND_SERVICE` in the `Service` section of `/etc/systemd/system/homebridge.service`. Giving you something like:

```
[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
AmbientCapabilities=CAP_NET_BIND_SERVICE
User=homebridge
EnvironmentFile=/etc/default/homebridge
# Adapt this to your specific setup (could be /usr/bin/homebridge)
# See comments below for more information
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Don't copy/paste my entire example! Just add the `AmbientCapabilities=CAP_NET_BIND_SERVICE` line to your existing `/etc/systemd/system/homebridge.service` file.**
