### ISSUE TITLE
admin:admin not working

### ISSUE THREAD

**Issue by cmdshft** [oznu/homebridge-config-ui-x#282]
New install, logging in with default user/pass isn't working. How do I correct this via SSH?

(I added the custom wallpaper in the config prior to install)

![Screen Shot 2019-05-05 at 3 43 26 AM](https://user-images.githubusercontent.com/8571823/57190427-f6492400-6ee7-11e9-915d-33f873a928b5.png)

**Comment by oznu** [comment]
Delete the `auth.json` file and restart to reset the password.

**Comment by WendelFelius** [comment]
Try Administrator:Admin

**Comment by oznu** [comment]
The solution for someone in the Slack group was to ensure the time/date on their server was correct.

**Comment by oznu** [comment]
The next version will show a warning if the date/time on the server/client vary by more than 4 hours.

![image](https://user-images.githubusercontent.com/3979615/57283515-ad18f000-70f2-11e9-84d0-0044718dd236.png)
