### ISSUE TITLE
Frozen on extraction (rxjs in /usr/local/lib/node_modules/.staging...)

### ISSUE THREAD

**Issue by themick4u** [oznu/homebridge-config-ui-x#283]
Frozen on extraction (rxjs in /usr/local/lib/node_modules/.staging...) While trying to update, reinstall latest version.... im running node -v 11.12.0 and npm -v 6.9.0... can anyone assist in helping me get ui-x back and working again? I’ve already tried the uninstall and reinstall procedures listed in the troubleshooting.

**Comment by oznu** [comment]
Hi @themick4u,

Please give the latest version a go. Some changes were made to try and reduce installation errors.

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x@latest

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by themick4u** [comment]
oznu.. It still wont let me perform a re-install.... / loadRequestedDeps: sill install loadAllDepsIntoIdealTree and sits there... i've tried manually @4.1.0 - @4.2.0 versions and all seem to lock up in same fashion... Perhaps I have something else going on? Im at a loss and open to suggestions
