### ISSUE TITLE
Feature request: handling of log messages

### ISSUE THREAD

**Issue by ebaauw** [oznu/homebridge-config-ui-x#288]
Please add the following changes to the logging:
- Honour homebridge's `-T` flag to refrain from adding timestamps to log messags (as syslog already provides the timestamp);
- Include the timestamp from syslog in the _View Logs_ window;
- Honour the value from the `"name"` key in config.json for the logging prefix.  Now the first message from homebridge-config-ui-x shows the name, but the others are hardcoded to use `homebridge-config-ui-x`.
```
[5/6/2019, 8:30:10 PM] [Config] Initializing config platform...
[5/6/2019, 8:30:11 PM] [homebridge-config-ui-x] Console v4.3.0 is listening on :: port 8080
```

**Comment by oznu** [comment]
Hi @ebaauw,

The next release will:

* honor the `-T` flag
* populate the name from the `config.json` correctly when possible (application crashing is the exception to this)

---

I'm holding off changing the default systemd logs at this time. I currently run journalctl with `-o cat` which formats the QR code correctly and retains color. Unfortunately this removes the timestamps and I don't see an option to restore them.

If I use the journalctl default `-o short` the colour is removed and there is a lot more content added to the line:

```
May 07 08:34:03 homebridge-test homebridge[2772]: [Config] Initializing config platform...
```

Users can still manually define their logging command if they want to change the default behaviour. The following would include timestamps, but no colour:

```json
"log": {
     "method": "custom",
     "command": "sudo -n journalctl -n 500 -o short -f -u homebridge"
}
```

**Comment by oznu** [comment]
4.4.0

**Comment by ebaauw** [comment]
Thanks!

> I'm holding off changing the default systemd logs at this time.

I thought you might be reading the syslog yourself, but, of course, it’s easier to let `journalctl` do the heavy lifting.  I’ll do some experiments with the various options it provides.

**Comment by ebaauw** [comment]
> The next release will:
> - honor the `-T` flag
> - populate the name from the `config.json` correctly when possible (application crashing is the exception to this)

Confirmed, works in 4.4.0.  Thanks!
