### ISSUE TITLE
close log file session

### ISSUE THREAD

**Issue by pelaxa** [oznu/homebridge-config-ui-x#29]
I'm using systems and journalctl and sudo to view the log and it all works, but once I start a session, there is no way to close it, so if I go to another section of the GUI and then back to logs, then i have to journalctl sessions and the logs are repeated twice.

you can also grep on ps to see that the command is running twice.  This will only get worse as you tab away and back again. 

Is there a way to close the session?  I tried clicking on the view logs button again but nothing happens.  I have to manually kill the existing sessions.

Thx.

**Comment by oznu** [comment]
Thanks for reporting this. 

I can replicate this issue and it only seems to present itself as a problem when `sudo` mode is used.

**Comment by oznu** [comment]
Hi @pelaxa,

This should be fixed in 2.6.2.
