### ISSUE TITLE
Feature request: disable Add Platform Block button

### ISSUE THREAD

**Issue by ebaauw** [oznu/homebridge-config-ui-x#290]
Homebridge dynamic platform plugins should only be specified once in config.json.  The persisted accessories in `~/.homebridge/accessories/cachedAccessories` don't know which instance of the platform they belong to.  They're all restored to a single instance, causing the other instance to re-create the accessory, with the usual "cannot add another accessory with the same UUID" blues.

The _Add Platform Block_ button should not appear for dynamic platform plugins.  I might be a bit too much for homebridge-config-ui-x to scan the plugin code to see if it's a dynamic platform plugin, but using a different value `"pluginType"` seems doable.

**Comment by oznu** [comment]
@ebaauw - thanks for your suggestion. I'm happy to expand the schema requirements as plugin developers demand.

I've added support for a  new `singular` boolean attribute you can add to the top level of your `config.schema.json` to the "Add Block" button being displayed if set to `true`.

Docs update: https://github.com/homebridge/Documentation/blob/master/Schema.md#basic-structure

**Comment by oznu** [comment]
4.4.0

**Comment by ebaauw** [comment]
Confirmed: works in v4.4.0.  Thanks!
