### ISSUE TITLE
Error when searching for plugin

### ISSUE THREAD

**Issue by JordanPatterson** [oznu/homebridge-config-ui-x#291]
I am getting an error when searching for a new plugin. 

Failed search npm: http failure response for http://myip:8080/api/plugins/search/people: 500 internal server error

**Comment by oznu** [comment]
I can not replicate this issue with the same search query.

The NPM registry is having issues with search at the moment which may be related.

**Comment by JordanPatterson** [comment]
My Raspberry Pi had an incorrect static DNS server configured. This was causing this search issues.

**Comment by skazzyskills** [comment]
How does one fix that?

**Comment by weiw11** [comment]
I had same issue on **rpi3** due to `ipv6` being enabled on my `wlan0` interface.

## Steps to disable:

Open terminal and run the following command:

```sh
sudo nano /etc/sysctl.conf
```

In the `sysctl.conf` file, add the following lines at the end:

```sh
# Disable IPv6 for wlan0
net.ipv6.conf.wlan0.disable_ipv6 = 1
```

Then reboot.
