### ISSUE TITLE
error updating from webui and console

### ISSUE THREAD

**Issue by cmdshft** [oznu/homebridge-config-ui-x#292]
From web UI:

`USER: homebridge
DIR: /usr/local/lib
CMD: npm --no-update-notifier install --unsafe-perm homebridge-config-ui-x@latest

Unhandled rejection Error: EACCES: permission denied, mkdir '/home/homebridge'6

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

Command failed. Please review log for details.`

From cosole:

`pi@pihole:~ $ sudo npm --no-update-notifier install --unsafe-perm homebridge-config-ui-x@latest
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ homebridge-config-ui-x@4.4.0
updated 1 package and audited 818 packages in 25.608s
found 0 vulnerabilities`

**Comment by oznu** [comment]
You need to enable sudo mode: https://github.com/oznu/homebridge-config-ui-x#sudo-mode

**Comment by cmdshft** [comment]
Sudo is set to true in my config. Issue persists.

I’ll try adding -g now.

**Comment by oznu** [comment]
> CMD: npm --no-update-notifier install --unsafe-perm homebridge-config-ui-x@latest

This line shows sudo not being used.

**Comment by cmdshft** [comment]
Yes, I used sudo in both console and had sudo enabled in my config.json, still had those errors. But it seems -g in console got it to work, so might need to update homebridge-config-ui-x to do the same?

**Comment by cmdshft** [comment]
Yes, I was using sudo in the console and had sudo enabled in config.json, and that's how I got those errors. Using -g in console got it to update, but the plugins version reports the current version installed but the main page at the bottom reports 4.3.0 is installed.

**Comment by oznu** [comment]
If sudo mode is active and you're still getting errors make sure you have these lines in your systemd service file:

```
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW
```

**Comment by jeylites** [comment]
this is the same issue I'm having. 

```
{
    "bridge": {
        "name": "#####",
        "username": "#####",
        "port": #####,
        "pin": "#####"
    },
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8087,
            "sudo": true,
            "service": "homebridge",
            "restart": "sudo pm2 restart homebridge"
        },
        {
```

**ERROR** 

```
The user "pi" does not have write access to the target directory:

/usr/local/lib

This may cause the operation to fail.
See the docs for details on how to enable sudo mode:
https://github.com/oznu/homebridge-config-ui-x#sudo-mode

USER: pi
DIR: /usr/local/lib
CMD: npm --no-update-notifier install --unsafe-perm homebridge@latest

```

#330

**Comment by mafyata** [comment]
Try this:
echo 'pi    ALL=(ALL) NOPASSWD: ALL' | sudo
And this:
chown -R pi: /usr/local/lib/

**Comment by jeylites** [comment]
made the changes on `visudo` and it took it. I'm able to update the UI. Thank you @mafyata
