### ISSUE TITLE
docker standalone mode issue with ports and updating

### ISSUE THREAD

**Issue by askovi** [oznu/homebridge-config-ui-x#293]
This is related to #285 
The issue is tricky but can easily be reproduced for testing:
When running in standalone mode with docker-homebridge if the Config block is present in the platforms array, the console runs twice and keeps erroring out about the port already being in use. If the block is removed from config.json then it runs fine, however the plugin cannot be updated. (see #285) 
I believe this is quite critical for docker users.

**Comment by oznu** [comment]
Are you running on oznu/homebridge?

**Comment by askovi** [comment]
Yes

**Comment by oznu** [comment]
I'm having trouble replicating this. Here is what I have tried:

Start command:

```
docker run -e HOMEBRIDGE_CONFIG_UI=1 -p 8080:8080 oznu/homebridge:latest
```

Command used inside container to downgrade the UI for testing:

```
npm install -g homebridge-config-ui-x@4.2.0
```

Testing Results:

### 1. No platforms[] in `config.json`

Removed the `platforms[]` (via terminal) from the `config.json` and restarted. Both UI and Homebridge start and restart as they should. 

Tested on v4.2.0 and v4.4.0.
Update from v4.2.0 to v4.4.0 successful. Homebridge and UI resume after a restart.

### 2. Empty platforms[] in `config.json`

Created an empty `platforms[]` in the `config.json` and restarted. Both UI and and Homebridge start and restart as they should. 

Tested on v4.2.0 and v4.4.0.
Update from v4.2.0 to v4.4.0 successful. Homebridge and UI resume after a restart.

### 3. platforms[] with UI config block in `config.json`

Added UI config to the `platforms[]` in the `config.json` and restarted. Both UI and and Homebridge start and restart as they should. 

Config used:

```json
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "teal",
            "tempUnits": "c",
            "platform": "config"
        }
```

Tested on v4.2.0 and v4.4.0.
Update from v4.2.0 to v4.4.0 successful. Homebridge and UI resume after a restart.

Confirmed only one instance of the UI is running:

```
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   27 root      0:00 s6-supervise docker-cmd
   28 root      0:00 s6-supervise s6-fdholderd
  335 root      0:00 s6-supervise avahi
  337 root      0:00 s6-supervise dbus
  338 root      0:00 s6-supervise homebridge
  339 root      0:00 s6-supervise homebridge-config-ui-x
  341 root      0:00 s6-supervise cron
  342 messageb  0:00 dbus-daemon --system --nofork
  345 root      0:00 /usr/sbin/crond -f -S -l 5 -c /etc/crontabs
  348 avahi     0:00 avahi-daemon: running [eb0637749a24.local]
 1233 root      0:00 sh /usr/bin/with-localenv sh ./run
 1235 root      0:00 sh ./run
 1238 root      0:00 sh /usr/bin/with-localenv sh ./run
 1241 root      0:00 sh ./run
 1242 root      0:02 homebridge-config-ui-x
 1243 root      0:00 tee -a /homebridge/logs/homebridge.log
 1266 abc       0:00 homebridge
 1267 root      0:00 tee -a /homebridge/logs/homebridge.log
 1292 root      0:00 /bin/sh
 1294 root      0:00 ps
```

Logs:

```
[Config] Homebridge restart request received
[Config] Executing restart command: killall -9 homebridge && killall -9 homebridge-config-ui-x
[Config] Console v4.4.0 is listening on 0.0.0.0 port 8080
[Config] Initializing config platform...
[Config] Running in Standalone Mode.
```

**Comment by askovi** [comment]
I’m running it with docker-compose on a raspberry pi. I’ll document every step and post back.

**Comment by oznu** [comment]
Thanks, also provide the full output of the `env` command from inside the UI terminals. It should output something like this.

```
HOMEBRIDGE_CONFIG_UI=1
HOMEBRIDGE_VERSION=0.4.49
...
```

**Comment by askovi** [comment]
ugh well this is awkward. I started by pulling your latest docker container from oznu/homebridge:raspberry-pi which you published 18 hours ago and I couldn't replicate any of the above on it. What did you change in the latest build? 
When I did my tests previously it was using the older container and I managed to replicate multiple times.

**Comment by oznu** [comment]
Nothing would have changed that might have impacted the UI.

This commit changed how plugins were in /homebridge/node_modules, but homebridge-config-ui-x is not installed in the location.

https://github.com/oznu/docker-homebridge/commit/cf306ec889f69adc408356c12a6ab251bffef3b8

Either way; I'm glad you have got it working 😄.
