### ISSUE TITLE
Error updating from console and webUI no matter sudo or -g

### ISSUE THREAD

**Issue by Xusqui** [oznu/homebridge-config-ui-x#294]
Hi...

I've tried to update from 4.0.6 -> 4.4.0 from the console and got an error message. After that, I tried to update from console with sudo permission and -g option and still got this error:

pi@HomeBridge:/var/homebridge $ sudo su
root@HomeBridge:/var/homebridge# npm install -g --unsafe-perm homebridge-config-ui-x
/usr/lib
└── (empty)

npm ERR! Linux 4.14.98-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-config-ui-x"
npm ERR! node v8.16.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/@nuxtjs/opencollective-f95f2d9a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@nuxtjs/opencollective-f95f2d9a' -> '/usr/lib/node_modules/homebridge-config-ui-x/node_modules/@nuxtjs/opencollective'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@nuxtjs/opencollective-f95f2d9a' -> '/usr/lib/node_modules/homebridge-config-ui-x/node_modules/@nuxtjs/opencollective'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /var/homebridge/npm-debug.log
npm ERR! code 1

So no, don't have the plugin running and when trying to start homebridge, it stops because it doesn't have the platform "config"... To make it run I completely removed this plugin config from the config.json file.

Any ideas?

Thanks in advance!

**Comment by Xusqui** [comment]
I've tried to completely uninstall (sudo npm uninstall -g homebridge-config-ui-x) and no errors...

After that tried to install again (sudo npm install -g --unsafe-perm homebridge-config-ui-x) with the same error...

**Comment by Xusqui** [comment]
Any clue on this?

**Comment by oznu** [comment]
Hi @Xusqui,

You're npm version is to old.

```
npm v3.10.10
```

Please try with Node.js 10 and npm 6.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)#step-2-install-nodejs-and-homebridge

**Comment by Xusqui** [comment]
OK... Will try now!

Thank you!

**Comment by Xusqui** [comment]
It worked!!!

Thanks a lot!!
