### ISSUE TITLE
Restart standalone homebridge-config-ui-x

### ISSUE THREAD

**Issue by sschuste** [oznu/homebridge-config-ui-x#295]
I run homebridge-config-ui-x in standalone mode, and whenever there is an update of it, I use the web interface of course. But unfortunately I cannot restart homebridge-config-ui-x with homebridge-config-ui-x after an update. The restart button restarts homebridge and not your plugin. So: back to the shell! Do you have any idea how to solve this more elegant?

Stefan

**Comment by oznu** [comment]
Are you using the updated restart command as shown in the wiki?

https://github.com/oznu/homebridge-config-ui-x/wiki/Standalone-Mode#step-1-edit-configjson-to-enable-standalone-mode
