### ISSUE TITLE
Running a Command

### ISSUE THREAD

**Issue by JordanPatterson** [oznu/homebridge-config-ui-x#296]
I run the Homebridge Samsung-Tizen plugin and I need to run homebridge with the tizen-apps parameter to get a code of an installed app. This is detailed below in an excerpt from their Readme file. [https://github.com/tavicu/homebridge-samsung-tizen](url)

> Applications
> 
> Below you can find a table with most common apps. If you don't find what you are looking for you can start the homebridge server with tizen-apps as parameter (homebridge tizen-apps) and it will show a table with all the apps that are installed on the TV.
> 
> Please make sure your TV is ON and paired.

I don’t know how to accomplish this with the config UI plugin installed. I followed your raspberry pi tutorial and am running the standalone UI. I am running with the terminal exposed in the UI but I don’t know what command to enter to get the expected output.

**Comment by oznu** [comment]
I'll leave this for the plugin author to answer, the UI is just a management interface, the setup of Homebridge is standard.

https://github.com/tavicu/homebridge-samsung-tizen/issues/99

At a guess though; try running `homebridge tizen-apps` at the command line?

**Comment by JordanPatterson** [comment]
I get an error running just hombridge at the command prompt in the web interface. I just don’t know what I am doing wrong?

**Comment by JordanPatterson** [comment]
When I type the command “homebridge” I tot he web ui terminal is says that it can not locate the config.json file.

**Comment by oznu** [comment]
Try this, from a ssh connection / desktop terminal, not the web terminal: 

```shell
# stop homebridge
systemctl stop homebridge

# start with temporary flag, ctrl+c when finished
homebridge -U /var/lib/homebridge -I tizen-apps

# restart homebridge
systemctl start homebridge
```

**Comment by JordanPatterson** [comment]
YES, that is exactly what I needed. Thank you for you help and excellent software.
