### ISSUE TITLE
Need to update Wiki for Node.js 12 installation

### ISSUE THREAD

**Issue by dikodahan** [oznu/homebridge-config-ui-x#297]
Following the wiki installation article with the sole change of `curl -sL https://deb.nodesource.com/setup_10.x | bash -` to `curl -sL https://deb.nodesource.com/setup_12.x | bash -` does not complete well. 
I initially tried to just upgrade node from 10 to 12, but that broke things for me.

I would suggest the following two updates in the wiki:
1. Update the install documentation to fit node 12.
2. Add a node upgrade instruction to properly update from 10 to 12 in your environment.

Thank you!

**Comment by oznu** [comment]
Hi,

The guide shows the installation steps for the LTS version of Node:

https://nodejs.org

While v12 is now supported by this plugin, v10 is still recommended and will be until October 2019.

https://nodejs.org/en/about/releases/

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)#major-nodejs-version-updates
