### ISSUE TITLE
Doesn't see Homebridge is running because my Homebridge process runs as "Node".

### ISSUE THREAD

**Issue by realdannys** [oznu/homebridge-config-ui-x#298]
I'm not sure if this is a recent Node v12 change, or a problem with my system but when I run Homebridge now the process appears in macOS as "node" and not "homebridge" like it used to. 

Presumably config ui looks for the homebridge process when judging if it's running or not and thus gives me a message saying homebridge isn't running.

**Comment by oznu** [comment]
The process name won't be causing a problem.

The UI checks that Homebridge is running on `http://localhost:<port from config.json>`.

If you're not seeing any errors in the logs try and enable [websocketCompatibilityMode](https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#websocketcompatibilitymode) mode in the Homebridge Config UI X config block.

**Comment by realdannys** [comment]
Thanks @oznu that pointed me in the right direction - I didn't have the port listed in the config! Sorted now.
