### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by cmdshft** [oznu/homebridge-config-ui-x#300]
I have a few ideas to propose, I have no way of coding these at all but as a consumer of the config-ui, it would be nice to have the following:

1: Have the config page report to the user the currently loaded config.json (including the path). Allow the user to backup to the remote machine instead of the local machine accessing the web-ui.

2: Idk if this is a feature that config-ui-x can do or if it has to be implemented in homebridge itself, but the ability to auto-config the installed plugins to the config.json file. I have to always load a json validator to make sure I am doing it right.

3: The ability to launch just the web-ui even if homebridge itself is crashing due to an improper config.json or other issue. (idk if this is possible right now with the standalone install)

4: During install, allow the user to customize in the terminal their install options (such as a new or existing user, homebridge child or standalone, etc. I am at an intermediate level with console installations and I can get easily lost when I follow the instructions but the instructions are cumbersome. I sometimes end up googling a lot of these issues to find that I had to do things not mentioned in the guides.

5: Not have to manually uninstall and reinstall when upgrading node.js. I found this out the hard way when the announcement was made to support Node.js12. I happily updated to find that my config-ui install completely bugged out after.

**Comment by oznu** [comment]
Hi @cmdshft. Thanks for your feedback.

> 1. Allow the user to backup to the remote machine instead of the local machine accessing the web-ui.

Every time the config is changed a backup is made on the remote machine automatically. The files are named `config.json.201903034334` or similar - the number is the current timestamp. This is where the *Restore* feature gets its list of available backups from. These backups are stored in the same folder as your `config.json`.

> 2: Idk if this is a feature that config-ui-x can do or if it has to be implemented in homebridge itself, but the ability to auto-config the installed plugins to the config.json file.

Plugins can define their own [config.schema.json](https://github.com/homebridge/Documentation/blob/master/Schema.md) which will allow the defaults to be populated and and provide a GUI editor for the plugins settings. An example of this  is the "Settings" button on the plugin for [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x/blob/master/config.schema.json) itself - any third party plugin can implement this (and more and more are doing so). 

>  I have to always load a json validator to make sure I am doing it right.

The config editor already validates the config is valid JSON before it allows you to save it. It even puts a red arrow on the side letting you know where the syntax error is. It sends it to the server as a JSON payload so the server itself would reject it as well if it were malformed.

> 3: The ability to launch just the web-ui even if homebridge itself is crashing due to an improper config.json or other issue. (idk if this is possible right now with the standalone install)

Standalone mode takes care of this.

> 4: During install, allow the user to customize in the terminal their install options (such as a new or existing user, homebridge child or standalone, etc. 

This would probably require an external install script, `npm install` does not really support interactive setup like this. It's something I am open to doing though, but would probably be only for `systemd` on debian based platforms (like Raspberry Pi and Ubuntu). I would probably just combine all the steps in [this wiki article](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)) into a single script.

> 5: Not have to manually uninstall and reinstall when upgrading node.js.

Not really able to get around this at this time. The `node-pty` module which is used in many areas of this plugin has custom c++ code compiled against a certain Node.js ABI major version, as such a reinstall is required after doing a major version update.

I would also recommend users stay on the current LTS version of Node. Node.js 12 goes into LTS mode in October 2019. Plugin authors aren't typically going to be using any of the new features in Node 12 until this time anyway.

**Comment by cmdshft** [comment]
I see, thanks for your reply.

1: I didn't realize it made the backups on it's own. That's awesome!

2: Your plugin is the only one I have personally seen that does this, which is great. I don't have many homebridge devices that I am using right now, so I am going to bet that's why I haven't seen it. Hope that changes in the future.

3: I will have to look into doing standalone mode again, then. I don't enjoy the web-ui going down when homebridge complains about something.

4: That would be amazing, systemd and Raspbian are what I am running this on so that would work wonderfully.

5: I see. Is there no way for homebridge-config-ui-x to detect a major change and then trigger the reinstall?

**Comment by oznu** [comment]
@cmdshft 

> 2: Your plugin is the only one I have personally seen that does this

Here are a few:

https://github.com/merdok/homebridge-webos-tv/blob/master/config.schema.json
https://github.com/itsmepetrov/homebridge-zigbee/blob/master/config.schema.json
https://github.com/ebaauw/homebridge-ws/blob/master/config.schema.json
https://github.com/ebaauw/homebridge-zp/blob/master/config.schema.json

**Comment by oznu** [comment]
In 4.4.2 I have added a more detailed error when `node-pty` fails to load, including possible causes such as upgrading node. The error also provides steps to resolve the issue.
