### ISSUE TITLE
Feature request: support for GitHub Registry

### ISSUE THREAD

**Issue by cbrandlehner** [oznu/homebridge-config-ui-x#301]
GitHub is currently building their own registry: https://github.com/features/package-registry
I expect some projects to move from npmjs.com to using the new github feature, so it would be nice to be prepared by supporting the github registry as well for searching available plugins.

**Comment by ebaauw** [comment]
> I expect some projects to move from npmjs.com to using the new github feature

Why would they do that, especially when homebridge itself is on `npm`?  What does the GitHub registry offer me (as a plugin developer) that `npm` doesn't?

**Comment by cbrandlehner** [comment]
I see these potential reasons to use GitHub Registry:
a) Using two services also needs you to maintain password etc for both. 
b) Ease of publishing. Imagine a team of multiple developers on a single github projects. Per default, only the project owner can upload a new version to npmjs. I expect this to be way easier in what github is building.
c) As a NEW developer, why would I care about learning how to use npm registry, if github already has a registry?

**Comment by oznu** [comment]
> Note: GitHub Package Registry only supports scoped NPM packages. Scoped packages have names with the format of @owner/name. Scoped packages always begin with an @ symbol. You may need to update the name in your package.json to use the scoped name. For example, "name": "@codertocat/hello-world-npm".

https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry

Homebridge does not support scoped packages presently.

**Comment by oznu** [comment]
Thanks for your suggestion @cbrandlehner - due to the [above comment](https://github.com/oznu/homebridge-config-ui-x/issues/301#issuecomment-493740334) I'll close this until Homebridge has support for scoped repos. I would be happy to implement this feature in the future should GitHub's NPM Package Repo turn out to be popular.
