### ISSUE TITLE
Unable to execute commands in web gui

### ISSUE THREAD

**Issue by misanthrophy** [oznu/homebridge-config-ui-x#302]
Hello,

I am getting install/update errors since today, when using the web ui.

sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin

When I execute the same command in terminal directly, it works just fine.

Where could I start troubleshooting that issue?

PS: I already updated to the latest release from 2hours ago. (The update to that version, was also the first notice of the issue)

**Comment by oznu** [comment]
Are you using systemd?

Make sure your `/etc/systemd/system/homebridge.service` file contains these lines in the `[Service]` section:

```
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW
```

If you had to add them run this to restart:

```
systemctl daemon-reload
systemctl enable homebridge
systemctl start homebridge
```

**Comment by misanthrophy** [comment]
Nice, at least a simple restart is working again.

My two lines were much shorter with less information than yours are, which you kindly provided me.

Thanks a lot for the super fast assistance!
