### ISSUE TITLE
Feature request: support changing /etc/defaults/homebridge

### ISSUE THREAD

**Issue by ebaauw** [oznu/homebridge-config-ui-x#303]
I've added initial support for config.json.scheme to all my plugins (though I haven't yet published new versions for all) and I'm seriously looking at running homebridge-config-ui-x in my production environment.  I'm still not sure whether I'll allow it to install or upgrade plugins (I don't like to expose privileged commands, or password-less `sudo`, through a web interface), but I like being able to change the homebridge config, view the log, and restart homebridge through the web interface.  I would also like to be able to change the command line parameters to homebridge this way, e.g. to turn debugging on or off.

I understand this might be tricky, since different installations start homebridge differently.  I run homebridge on a RaspBerry Pi, through `systemctl`.  homebridge-config-ui-x actually knows this, as `log.method` in `config.json` is set to `"systemd"`.

As is typical for `systemd` services, I've created a `homebridge.service` file in `/etc/systemd/system` and a `homebridge` defaults file in `/etc/defaults`.  Note that name of these files matches the name of the service, which is also configured in `config.json` under `log.service`.  As I run multiple instances of homebridge, I've created multiple `.service`, defaults, and `config.json` files.

The `homebridge.service` file includes:
```
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
```
The defaults file sets the `HOMEBRIDGE_OPTS` and `DEBUG` environment variables.  Note that any user directory (`-U `_user-storage-path_ parameter) is hardcoded in the `.service` file, but the other parameters, `-C`, `-D`, `-I`, `-Q`, `-R`, and `-T` are set through `HOMEBRIDGE_OPTS`.   Obviously, the defaults and `config.json` files are writeable by the user running homebridge, whereas the `.service` file is not.

I'm not sure how to deal with `-P `_plugin-path_; I don't use it as I've installed all plugins globally (`sudo npm -g i `_plugin_) and use the `"plugins"` key to control what plugins to load per homebridge instance (see #287).

Would it be possible to create a form with checkboxes to set the homebridge parameters in `HOMEBRIDGE_OPTS`, and a text box for the `DEBUG` variable?  This form would be accessible only when `log.method` is `"systemd"`, and it would set `/etc/defaults/`_service_, where _service_ is the value of `log.service`.

**Comment by SeydX** [comment]
text box for the DEBUG variable would be awesome!

**Comment by oznu** [comment]
Docker users get this:

![image](https://user-images.githubusercontent.com/3979615/57983034-7054dd80-7a90-11e9-8e0e-9f838a0ee6e1.png)

So adding support for systemd would not be to far fetched...

**Comment by SeydX** [comment]
@oznu 

is it possible to set own keys for DEBUG?

eg DEBUG=TestPlugin or multiple DEBUG=TestPlugin1,TestPlugin2 etc..

to enable DEBUG only for certain plugin(s)

**Comment by oznu** [comment]
No, but they can edit the `.docker.env` file directly from the web interface (once again - only Docker!)

**Comment by oznu** [comment]
I would probably not add support for adjusting the -U and -P flags as the UI itself depends on these to load itself correctly. I see no problem with the other ones though.

**Comment by oznu** [comment]
While it's not exactly what was requested here, and probably won't help those with existing setups, I've implemented this in a cross-platform way for users who setup Homebridge as a service using the provided [`hb-service`](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command) command.

Users to set the Homebridge `-D` and `-R` flags, as well as the `DEBUG` and `NODE_OPTIONS` environment variables directly from the UI.

<p align="center">
  <img width="600px" src="https://user-images.githubusercontent.com/3979615/72317538-b92b6780-36ed-11ea-8001-77921be18417.png">
</p>

The remainder of the Homebridge flags are predefined when running in this mode.
