### ISSUE TITLE
Change "config" to a visual web form of switches & inputs

### ISSUE THREAD

**Issue by MBarti** [oznu/homebridge-config-ui-x#306]
The biggest issue with homebridge for non-technical people is to manually edit the config files. Config files are scary to many people, they are easy to mess up.

It'd be relatively easy to convert config editing into a simple web form and it'd be a game-changer for homebridge (could be advertised as not requiring any technical skills).

For each plugin:
- a true/false value would be a visual on/off switch
- a numerical value would be a numerical input field
- IP address would be a text field with format validation
- a "+" button would add a new row for a variable name + value, etc.

- there could be a switch to put a plugin's config into "Accessories" or "Platforms" section.

Then at saving, the plugin would take the values and save them properly into the config file, adding the necessary technicals like bracket closing, quotation marks, etc. - ensuring 100% that the config file is valid.

This would open up homebridge to a LOT of new potential users!

For most plugins it'd be very easy to just use REGEX to go line by line of their sample-config.json file and determine the required variables, their type and placement (platforms vs accessories section). In rare cases of plugins for which you cannot determine what variables they require, just start with an empty screen with a manual "+" button to add rows or add a multiline text box, for the user to be able to paste a config section.

**Comment by ebaauw** [comment]
homebridge-config-ui-x has already implemented this.  Plugins can provide a `config.json.scheme` that is used to generate the form.  See https://github.com/homebridge/Documentation/blob/master/Schema.md.

**Comment by MBarti** [comment]
WOW, you're absolutely right, sorry for the duplicate then.
I have not seen that with any of the plugins I use.

**Comment by oznu** [comment]
I've added this to my own wiki:

https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI

**Comment by oznu** [comment]
Also added a list of plugins I could find that implement this:

https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI#plugins-using-this

Only 4 out of the 10 are my own plugins 😄
