### ISSUE TITLE
Standalone Mode problem

### ISSUE THREAD

**Issue by netRunner0** [oznu/homebridge-config-ui-x#308]
pi@raspberrypi:~ $ homebridge-config-ui-x

[5/26/2019, 4:03:05 PM] [Config] Console v4.4.2 is listening on :: port 8080
 
ok:

pi@raspberrypi:~ $ sudo systemctl start homebridge-config-ui-x
Job for homebridge-config-ui-x.service failed because of unavailable resources or another system error.
See "systemctl status homebridge-config-ui-x.service" and "journalctl -xe" for details.
pi@raspberrypi:~ $ systemctl status homebridge-config-ui-x.service
● homebridge-config-ui-x.service - Homebridge Config UI X
   Loaded: loaded (/etc/systemd/system/homebridge-config-ui-x.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Sun 2019-05-26 16:25:03 MSK; 156ms ago

May 26 16:25:03 raspberrypi systemd[1]: homebridge-config-ui-x.service: Failed to load environment files: No such file or directory
May 26 16:25:03 raspberrypi systemd[1]: homebridge-config-ui-x.service: Failed to run 'start' task: No such file or directory
May 26 16:25:03 raspberrypi systemd[1]: Failed to start Homebridge Config UI X.
May 26 16:25:03 raspberrypi systemd[1]: homebridge-config-ui-x.service: Unit entered failed state.
May 26 16:25:03 raspberrypi systemd[1]: homebridge-config-ui-x.service: Failed with result 'resources'.

**Comment by oznu** [comment]
Logs?

```
journalctl -u homebridge-config-ui-x
```

And also show your systemd service file.

**Comment by oznu** [comment]
> May 26 16:25:03 raspberrypi systemd[1]: homebridge-config-ui-x.service: Failed to load environment files: No such file or directory

This looks like the issue.

Make sure you have setup your system according to this:

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian)

**Comment by netRunner0** [comment]
Please close
