### ISSUE TITLE
Unable to access Web UI after a short time, requires restart of RPI/config-ui-x

### ISSUE THREAD

**Issue by cmdshft** [oznu/homebridge-config-ui-x#309]
https://streamable.com/crse8

I am not sure why this has been happening, but has been at least since the most recent update.

**Comment by oznu** [comment]
They symptoms in the video look the same as https://github.com/oznu/homebridge-config-ui-x/issues/299

**Comment by cmdshft** [comment]
Ah yes, your update has resolved that it seems.
