### ISSUE TITLE
Cannot login with admin/admin

### ISSUE THREAD

**Issue by hangmanandhide** [oznu/homebridge-config-ui-x#310]
Generated SSL keys through this resource (https://medium.freecodecamp.org/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec) before initial execution.

Config file is as follows:

`{
    "bridge": {
      "name": "Homebridge",
      "username": "CC:22:3D:E3:CE:30",
      "pin": "867-53-090"
    },

    "platforms": [{
        "platform": "LiftMaster2",
        "name": "MyQ",
        "username": "USERNAME",
        "password": "PASSWORD",
        "openDuration": 20,
        "closeDuration": 25,
        "polling": true,
        "longPoll": 300,
        "shortPoll": 5,
        "shortPollDuration": 120
     },
     {
        "platform": "config",
        "name": "Config",
        "port": 8080,
        "ssl": {
            "key": "/Users/USERNAME/.homebridge/server.key",
            "cert": "/Users/USERNAME/.homebridge/server.crt"
          },
        "log": {
            "method": "file",
            "path": "/Users/USERNAME/.homebridge/logfile.log"
        },
        "restart": "launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist"
    }
    ]

}`

No errors are being thrown in terminal. Console v4.4.2 is listening on port 8080. Https://localhost:8080 brings up the login page.

auth.json has an id1 with a username of admin, pass admin. 

Tried admin/admin, Administrator/admin nothing worked. Opened inspector in safari and it shows an error when I try: 

{
    "statusCode": 403,
    "error": "Forbidden"
}

Am I missing something or did I do something wrong? logfile.log is empty... so I'm guessing I dont have that working correctly either?

**Comment by cmdshft** [comment]
"username": "USERNAME",
    "password": "PASSWORD",

Did you login with that?

**Comment by hangmanandhide** [comment]
Yes. Ddint work either.

**Comment by hangmanandhide** [comment]
Note I am getting a POST 'http://localhost:9090/api/auth/login 403 (forbidden)error in Inspector. I said http, and I also mean https. I thought maybe it had something to do with my ssl certs but that's not the case becaues I disabled it out of the code and still can't authenticate through.

**Comment by oznu** [comment]
Can you show me the permissions on the auth.json file?

**Comment by hangmanandhide** [comment]
Hi @oznu 

-rw-r--r--@ is auth.json
-rw-r--r-- is config .json

I had to google to figure out what the @ means... did ls -al@ auth.json and got this for you:

	com.apple.lastuseddate#PS

if thats also necessary/needed

**Comment by oznu** [comment]
Is the owner of both files the same?

**Comment by hangmanandhide** [comment]
Yes, they're all in the same directory.

**Comment by oznu** [comment]
Thanks. What about the contents of the `auth.json`? Can you paste it here?

**Comment by hangmanandhide** [comment]
sure.

`[
    {
        "id": 1,
        "username": "admin",
        "password": "admin",
        "name": "Administrator",
        "admin": true
    }
]`

**Comment by oznu** [comment]
That's not s valid auth file - and hasn't been since at least release 2.0. If you delete the file and restart Homebridge it will fix itself.

**Comment by hangmanandhide** [comment]
Ugh! Thank you! that totally did it. I can't explain how that file was as it was, as I just setup the homebridge server the day I wrote the error up. thank you for all your time!

**Comment by oznu** [comment]
It may have been from the original plugin "homebridge-config-ui" which you might have tried at some point in the past.

Notice how the auth.json now includes a hashed and salted password rather than just having it in plain text.

Version 2 and 3 of this plugin handled the auth file "upgrade" process, but I removed it in version 4 as part of a code cleanup. I might add the check back in.

**Comment by hangmanandhide** [comment]
Yeah I would think having a clean-up script run at first to check to see if there's any duplicate files in the target directory and then prompting the user to either press 'd' to delete them or 'm' to move them to a new dir titled 'Archived' within so they can keep the files for reference and not let anything contaminate the install.

Could this be why I now get unexpected token errors?
