### ISSUE TITLE
Create Rooms by Polling Homebridge for Rooms

### ISSUE THREAD

**Issue by mkormendy** [oznu/homebridge-config-ui-x#311]
I know that there's some sort of endpoint in the HomeKit API that I am pretty sure Homebridge can access to sync the rooms set up in Homekit with this Config-UI-X package. I know this because the Philips Hue app syncs rooms between the Hue bridge and HomeKit.

It would be nice if homebridge-config-ui-x would mirror it's rooms with HomeKit this way.

**Comment by ebaauw** [comment]
That is technically not possible.  You can only setup rooms using the HomeKit API, which is available only to HomeKit apps running on iOS.  homebridge uses the HomeKit Accessory Protocol (HAP), which doesn’t provide access to rooms (nor scenes nor automations).

**Comment by oznu** [comment]
Thanks @ebaauw.

**Comment by mkormendy** [comment]
My bad. But that's also Interesting .. a homebridge helper app on iOS could help with this. Though, Apple may reject it due to the nature of homebridge not being "certified" or an official partner.
