### ISSUE TITLE
Unable to modify the config from Safari browser due Json incorrect

### ISSUE THREAD

**Issue by monsterciattolo** [oznu/homebridge-config-ui-x#313]
Hello,
If i use safari on iOS 12.3.1 to modify the configuration, editor doesn’t recognize a valid json syntax and i’m not able to save.
No problem to do the same operation from desktop web browser.
I’m using the plugin version 4.4.3

Thanks

**Comment by oznu** [comment]
Can you provide an example?

**Comment by oznu** [comment]
Tested on iOS 12.2:

Valid Syntax:

![BD0A5A40-45D2-4FF6-B562-F7BEC637E8F9](https://user-images.githubusercontent.com/3979615/58517772-e7f0de00-81ef-11e9-839c-35d49c42f3f8.jpeg)

Intentionally testing invalid syntax:

![3C35FDCC-154B-4C88-AD7C-496F198339AF](https://user-images.githubusercontent.com/3979615/58517847-2b4b4c80-81f0-11e9-848f-c3174302bd3a.jpeg)

**Comment by monsterciattolo** [comment]
This the original part.

![IMG_2744](https://user-images.githubusercontent.com/48657716/58586106-a1849900-825a-11e9-9dea-9717d316b65d.png)

then i added a row in my config from safari on iOS 12.3.1 " "verbose": true, " and i got the error.

![IMG_2745](https://user-images.githubusercontent.com/48657716/58586175-c6790c00-825a-11e9-8992-4dcba134324f.png)

i did the same operation from safari on Mac OS 10.14.5 without problem during the config saving

**Comment by oznu** [comment]
I see the problem. Safari is trying to use fancy quotes. Notice how the quotes around `verbose` are slightly angled?

You can turn this off by going to Settings -> General -> Keyboard -> Smart Punctuation -> Off.

I'll also investigate trying to block smart punctuation in this text box.

**Comment by oznu** [comment]
This should be resolved in 4.4.4.
