### ISSUE TITLE
Feature request: Support multiple homebridge instances

### ISSUE THREAD

**Issue by SeydX** [oznu/homebridge-config-ui-x#315]
Hallo @oznu 

First of all, many thanks for this great work. I use it with some of my Homebridge instances. That's why I need to set up different ports for each configuration server. That's a bit annoying.

It would be really great if it would be possible to add all the accessories to Config-UI-X with one server, regardless of the config.json location.

Or an array of the various services in config.json to add the accessories to Config-UI-X

**Comment by oznu** [comment]
Are you more wanting the accessories across multiple instances to be show, or to be able to just run one copy of the UI? The former is much easier and wouldn't require any changes to your setup - apart from an update to the UI.

---

Onto multiple instances. This has been requested many times and I have been hesitant to do so. However, the new code base (4.0.0) is a lot more flexible in regards to hot-loading config so could be done.

Firstly, if I were to do this I would have some restrictions around the supported environment. While it can probably work on other environments, I don't want to have to support every bespoke setup. So only issues relating to this feature for the following setup will be accepted:

- Linux only (Ubuntu / Raspbian / Debian)
- Node.js installed using the official [repository](https://nodejs.org/en/download/package-manager/)
- All instances must be running on the same host
- All homebridge instances running via homebridge running via systemd only
- Homebridge Config UI X running in [standalone mode](https://github.com/oznu/homebridge-config-ui-x/wiki/Standalone-Mode) (master of multiple instances) as its own systemd service

To implement this a flag would be added to the standalone systemd file, enabling multi-instance mode and pointing to the location where the UI can store shared config (and auth.json etc.):

```
homebridge-config-ui-x --multimode /var/lib/homebridge-config-ui-x
```

In this location there would be a file named `ui.json` that looks something like the below sample. Each instances to manage would be added to the `instances` array, and the UI config that needs to stay the same across all the instances would be here (like port, auth method, ssl settings etc.), pretty much all other UI config such as the log method, restart command and even theme would remain in each instances `config.json` as it does today.

Example `/var/lib/homebridge-config-ui-x/ui.json`:

```
{
  "port": 8080,
  "auth": "form",
  "instances": [
    {
      "name": "Homebridge 1",
      "path": "/var/lib/homebridge-one",
      "insecure": true,
      "customPluginPath": "/var/lib/homebridge-one/node_modules"
    },
    {
      "name": "Homebridge 2",
      "path": "/var/lib/homebridge-two",
      "insecure": true
    }

  ]
}
```

When running in multiple instance mode a new drop down will be added to the menu bar displaying the instance currently being configured. Users can use this dropdown bar to toggle between instances which will trigger a hot-reload of the config server side to use the config for the newly selected instance.

This way of doing thing has a couple issues:

* Only one instance can be configured at a time.
* Attempting to open the config for multiple instances in separate browser tabs will lead to unexpected results.
* Will need a way to ensure all open tabs of an instance on all devices clearly let the user know the instance being managed changed server side.

Now, ideally the above issues would be resolved by implementing the instance selection at a user session level - however this would require nearly a complete rework of the existing server side code that I am not going to do at this time (don't hold your breath).

⚠️ **This feature has not been implemented** - the example command and code samples shown in this comment will not work with the current plugin.

**Comment by SeydX** [comment]
@oznu 

One copy of config-ui-x would nice. Maybe something like homebridge-alexa that loads every accessory found in the network 

I think with this method there will be no problems with environments and it allow to create only one config-ui-x server

The accessories found in the network could be parsed with your accessory parser and only accessories that are currently supported could be added to config-ui-x 

That all can be done maybe via a parameter in config.json, i.e

```
"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": true,
      "standalone": true,
      "multipleInstances": true
    }
]
```

**Comment by ebaauw** [comment]
Do you really need the instances key?  Couldn’t the central standalone service build the list from the plugins registering?
