### ISSUE TITLE
Feature Request: Clean url for server

### ISSUE THREAD

**Issue by MickL** [oznu/homebridge-config-ui-x#316]
It would be very nice to have a clean url like "home.bridge" like Fritzbox does instead of the IP of the RaspberryPi .

**Comment by oznu** [comment]
This is achieved using Raspbian. eg. `http://raspberrypi.local`; just replace `raspberrypi` with whatever the hostname of your device is.

Only the `.local` prefix will work as that's what Bonjour will look for. Your fritzbox can probably use any domain as it's intercepting your DNS requests.

You might need to install Bonjour if you're running an older version of Windows.

**Comment by MickL** [comment]
The port was missing on your example, the correct url is `http://raspberrypi.local:8080` when default port is defined. Still a little bit inconvenient, a special url for homebridge without a port would be nice like `http://homebridge.local`
