### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by seppelicous** [oznu/homebridge-config-ui-x#32]
Hi,
I got the following error, when installing on my RPI3. 
Thanks in advance for your support:

> pi@Homebridge:~ $ npm install -g --unsafe-perm homebridge-config-ui-x
> /usr/local/bin/homebridge-config-ui-x -> /usr/local/lib/node_modules/homebridge-config-ui-x/bin/standalone.js
> 
> > node-pty@0.7.4 install /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty
> > node scripts/install.js
> 
> gyp ERR! configure error 
> gyp ERR! stack Error: Command failed: /usr/bin/python2 -c import platform; print(platform.python_version());
> gyp ERR! stack ValueError: bad marshal data (string ref out of range)
> gyp ERR! stack 
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
> gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
> gyp ERR! stack     at emitOne (events.js:116:13)
> gyp ERR! stack     at Socket.emit (events.js:211:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
> gyp ERR! System Linux 4.9.63-v7+
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty
> gyp ERR! node -v v8.9.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-pty@0.7.4 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-pty@0.7.4 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/pi/.npm/_logs/2018-02-18T10_20_57_657Z-debug.log

**Comment by oznu** [comment]
Hi @seppelicous,

Please try again with `sudo`:

```shell
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by seppelicous** [comment]
[2018-02-18T10_41_16_898Z-debug.log](https://github.com/oznu/homebridge-config-ui-x/files/1734599/2018-02-18T10_41_16_898Z-debug.log)
Same error, here is the log.

**Comment by oznu** [comment]
Does running this command manually succeed?

```
/usr/bin/python2 -c "import platform; print(platform.python_version());"
```

**Comment by seppelicous** [comment]
pi@Homebridge:~ $ /usr/bin/python2 -c "import platform; print(platform.python_version());"
ValueError: bad marshal data (string ref out of range)

**Comment by oznu** [comment]
That shouldn't be happening, it's a corrupt python `.pyc` file somewhere that is causing the problems. 

Once you fix that, `homebridge-config-ui-x` will probably install fine.

Similar issues I found by putting the error into Google:

https://stackoverflow.com/a/30861494
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=744185

**Comment by seppelicous** [comment]
Thanks oznu, I pretty new to Linux and I am still learning. Now I am upgrading or installing python3.6

**Comment by oznu** [comment]
node-gyp (the utility that is failing) requires Python 2.7. Installing Python 3.x won't break it, since both versions can be installed at the same time, but it won't fix the problem either. 

One of the sites I linked above suggested reinstalling Python 2.7:

```
apt-get install --reinstall python2.7
```

**Comment by seppelicous** [comment]
Great, I didn't know which Version I need. I will try that

**Comment by seppelicous** [comment]
That worked for me! Thank you very much
