### ISSUE TITLE
UI Issues when behind Synology Reverse Proxy

### ISSUE THREAD

**Issue by rcork** [oznu/homebridge-config-ui-x#320]
I've installed homebridge in docker on Synology and it's working great. The homebridge UI also works correctly when using the synology hostname and the port i configured for the homebridge UI. However, when i use Synology's built in reverse proxy, the QR code and the homebridge and console status is not reflected correctly. 
<img width="1003" alt="Screen Shot 2019-06-11 at 3 20 25 PM" src="https://user-images.githubusercontent.com/3687003/59310827-7a679780-8c5c-11e9-85d1-768d29983aad.png">
When i look in the browsers console, i see a lot of websocket errors.

`Firefox can’t establish a connection to the server at ws://homebridge.corknation.net/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJhZG1pbiI6dHJ1ZSwiaW5zdGFuY2VJZCI6IjAxZDQzYjgwOGRiMTM1N2RkYTlmM2VjZmFjNWQ5MzE3MjkxMjU1ZWMyMjA1M2E1M2ViYmVhMDZjODI5NzIzNGEiLCJpYXQiOjE1NjAyOTAxNTgsImV4cCI6MTU2MDMxODk1OH0.sNnq3B2zlabqg48pecljSoQh84Mv2kzy97X_2s0T4rY&EIO=3&transport=websocket. main.6607883f922479f730be.js:1:241012
`

and

`The connection to ws://homebridge.corknation.net/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJhZG1pbiI6dHJ1ZSwiaW5zdGFuY2VJZCI6IjAxZDQzYjgwOGRiMTM1N2RkYTlmM2VjZmFjNWQ5MzE3MjkxMjU1ZWMyMjA1M2E1M2ViYmVhMDZjODI5NzIzNGEiLCJpYXQiOjE1NjAyOTAxNTgsImV4cCI6MTU2MDMxODk1OH0.sNnq3B2zlabqg48pecljSoQh84Mv2kzy97X_2s0T4rY&EIO=3&transport=websocket was interrupted while the page was loading. main.6607883f922479f730be.js:1:241012
`

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Apache

**Comment by rcork** [comment]
The problem is that Synology's built in proxy doesn't allow you to modify the configuration directly. It's all through the DSM UI
<img width="475" alt="Screen Shot 2019-06-11 at 3 40 32 PM" src="https://user-images.githubusercontent.com/3687003/59311687-48a40000-8c5f-11e9-8f8c-6a8fc1604e7c.png">
You can set the values in the screenshot as well as set HTTP Headers. That's about it.

**Comment by oznu** [comment]
Try this.

Go to the Plugins page and open up the settings for Config UI. Just hit save without making any changes.

The go to the config editor and add `"websocketCompatibilityMode": true` to the Config UI block.

https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#websocketcompatibilitymode

The restart and refresh the page. This should allow you to run without websocket support.

**Comment by rcork** [comment]
That worked. Thank you very much!
