### ISSUE TITLE
The footer links on the status page are not showing correctly

### ISSUE THREAD

**Issue by mafyata** [oznu/homebridge-config-ui-x#322]
**Describe The Bug:**
The footer links on the status page are not showing correctly at small displays. I use iPhone 6S.

**Environment:**

* **Node.js Version**: 10.16.0
* **NPM Version**: 6.9.0
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.5.0
* **Operating System**: Raspbian / Hoobs
* **Process Supervisor**: Systemd
![0EF4E6DF-5195-4C52-A0FB-C3B60FA0B37C](https://user-images.githubusercontent.com/48009267/59437342-167ad580-8dfa-11e9-82ff-bfcd35dc083a.jpeg)

**Comment by oznu** [comment]
Can replicate. Thanks.

**Comment by oznu** [comment]
Fixed in 4.5.1.
