### ISSUE TITLE
Unable to load accessories on Config-UI webpage

### ISSUE THREAD

**Issue by ukypayne** [oznu/homebridge-config-ui-x#323]
**Describe Your Problem:**
When I run "homebridge -I" I get the following error whenever trying to use the Accessories tab from webpage. 

This was functional for about 6 days, but during that time I added a few plugins. I left everything functional one night and within 12 hours, I had this issue.

My config-UI webpage also doesn't show the QR code to scan anymore.

**Logs:**

```
"Log file shows "Failed load accessories from Homebridge: Error: connect ECONNREFUSED 127.0.0.1:52460"```

**Homebridge Config:**

```
`{
    "bridge": {
        "name": "GaragePi",
        "username": "BB:22:4D:E3:CE:92",
        "port": 52460,
        "pin": "052-32-019"
    },
    "accessories": [
        {
            "accessory": "GarageGateOpener",
            "name": "Garage",
            "switchPin": 23,
            "switchPressTimeInMs": 1000,
            "switchValue": 0,
            "closedSensorPin": 24,
            "closedSensorValue": 1,
            "pollInMs": 2500,
            "opensInSeconds": 10
        },
        {
            "accessory": "OnStar",
            "name": "Malibu",
            "deviceId": "23a35938-992a-4d35-bba4-230809d96d73",
            "vin": "VINNUMBER",
            "username": "EMAIL",
            "password": "PASS",
            "onStarPin": "CODE"
        },
        {
            "name": "Bedroom TV",
            "ip": "10.0.250.32",
            "mac": "94:6a:b0:46:51:46",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "true",
            "volumeLimit": 69,
            "channelControl": true,
            "mediaControl": true,
            "remoteControlButtons": [
                "PROGRAM"
            ],
            "remoteSequenceButtons": [
                {
                    "sequence": [],
                    "interval": 500
                }
            ],
            "accessory": "webostv"
        },
        {
            "name": "Living Room TV",
            "ip": "10.0.249.69",
            "mac": "d4:63:fe:d3:67:47",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "true",
            "volumeLimit": 69,
            "channelControl": true,
            "mediaControl": true,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Apple TV"
                }
            ],
            "remoteSequenceButtons": [
                {
                    "sequence": [],
                    "interval": 500
                }
            ],
            "accessory": "webostv"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "navi-blue",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "f",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "manualDevices": [
                "http://10.0.250.17:49153/setup.xml",
                "http://10.0.250.19:49153/setup.xml"
            ]
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true
        },
        {
            "platform": "camera-ffmpeg-ufv",
            "name": "UniFi Video (ffmpeg)",
            "nvrs": [
                {
                    "apiHost": "10.0.249.72",
                    "apiPort": 7443,
                    "apiProtocol": "https",
                    "apiKey": "APIKEY123",
                    "motionSensors": true
                }
            ]
        }
    ]
}
`
```

**Environment:**

* **Node.js Version**: <!-- node -v -->
v.12.4.0
* **NPM Version**: <!-- npm -v -->
v.6.9.0
* **Homebridge Version**: <!-- homebridge -V -->
v.0.4.50
* **Homebridge Config UI X Version**:
v.0.4.50
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
Raspbian latest
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none
systemd

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by mafyata** [comment]
Did you update node.js before error ? I have a problem when updated node.js from 8.15.1 to 12.4.0.

**Comment by ukypayne** [comment]
That possibly could be it. I'll try to roll back to v 11 and see if that helps. I thought I was on version 8, but then I was getting an error for one plugin that said it needed a newer version.

**Comment by ukypayne** [comment]
Looks like this was because of another plugin that it was causing the error. I think it was because I was running another plugin that brings cameras to the bridge. I’m not sure why that wasn’t an issue that presented itself sooner.
