### ISSUE TITLE
iOS Display issue still not fixed with 4.5.1

### ISSUE THREAD

**Issue by bubffm** [oznu/homebridge-config-ui-x#324]
I still have the footer signature line showing up mid screen on my iPad. Does not seem to have been fully fixed although the change log says it has....

**Comment by oznu** [comment]
Did you refresh the page?

**Comment by bubffm** [comment]
yes I did.  But  now found what I had to do is to close Safari altogether and restart.  Now it looks ok

**Comment by oznu** [comment]
Great!
