### ISSUE TITLE
Support for Grafana dashboards

### ISSUE THREAD

**Issue by misanthrophy** [oznu/homebridge-config-ui-x#326]
**Is your feature request related to a problem? Please describe:**
In the near future I want to setup multiple homebridge server on different PI's due to some hardware limitations. Opening different websites for different instances is annoying

**Describe the solution you'd like:**
Is there any chance to use some basic information from your plugin to display them on grafana? Like uptime, is homebridge running or not, any updates needed and maybe a hint when an error occured, like a plugin lost a connection and threw out an error in the log etc.

**Describe alternatives you've considered:**
I am new to this, so I don't know if there is anything else possible or not. 

**Additional context:**
I don't need any special things, if I would be able to reboot homebridge, execute updates, and see if homebridge is running or not is definitely enough for me.

**Comment by roysbike** [comment]
Please ! Add export metric to grafana!!!
