### ISSUE TITLE
Raspberry PI memory

### ISSUE THREAD

**Issue by adavison007** [oznu/homebridge-config-ui-x#329]
My memory is almost out, does anyone know how to upgrade the memory on a raspberry PI?

![Screenshot 2019-06-23 at 20 16 51](https://user-images.githubusercontent.com/47482260/59981500-11890380-95fc-11e9-8f5b-50ede1f3f38b.jpeg)

**Comment by oznu** [comment]
You can't; but the used memory is probably just Linux doing a good job at using free ram to caching things.

**Comment by adavison007** [comment]
Thanks, as if by magic... https://www.raspberrypi.org/products/raspberry-pi-4-model-b/

**Comment by ebaauw** [comment]
Yeah, just got a newsletter from my local electronics webshop, announcing the 4B.  It needs a 3.0A power supply (as opposed to 2.5A for the 3B and 3B+).  I wonder how well it manages its heat.  Any experiences yet?

**Comment by mafyata** [comment]
What is the price at your local electronics webshop?

**Comment by oznu** [comment]
I've ordered a Pi 4 to test with.

**Comment by ebaauw** [comment]
€ 40 for the 1GB model to € 60 for the 4GB.  But you need a new power adapter, hdmi cable, and, optionally, case.

https://www.kiwi-electronics.nl/raspberry-pi-4?utm_source=Kiwi+Electronics+Mailing&utm_campaign=2144e8568a-RASPBERRY_PI_4&utm_medium=email&utm_term=0_779f4f564e-2144e8568a-154817201&mc_cid=2144e8568a&mc_eid=7e9867bcad

**Comment by oznu** [comment]
The website does say you can get away with a good quality 2.5A power supply if your USB devices use less than 500mA.

> * A good quality 2.5A power supply can be used if downstream USB peripherals consume less than 500mA in total.

You will need a USB-C cable if you don't have one already though.

**Comment by mafyata** [comment]
I don’t think that it need new power adapter. Mineis usb and need to change only usb cable or adapter from micro usb to usb C.
