### ISSUE TITLE
Reset password?

### ISSUE THREAD

**Issue by seannymurrs** [oznu/homebridge-config-ui-x#33]
I attempted to change the admin password, and I used Safari’s built in password generator. The proble is, it didn’t save the password like it typically does. Now I’m locked out of the web access. Is there anyway to reset the password, or do I need to completely uninstall the plugin and reinstall it?

**Comment by oznu** [comment]
Hi @seannymurrs,

If you delete the `auth.json` file in your homebridge config directory and restart the username and password will be reset to the default.
