### ISSUE TITLE
the lines of the logs

### ISSUE THREAD

**Issue by djrams10** [oznu/homebridge-config-ui-x#339]
Hello, I would have liked to increase the lines of the logs. I tried with this command line, "sudo -n tail -n 500 -f /var/log/homebridge.log" but it did not work. Can you help me?

**Comment by oznu** [comment]
Hi @djrams10,

I'm assuming your using docker based on your previous issue.

It's currently not possible to change the log settings for docker, the app forces the certain settings when it detects it's running inside oznu/docker-homebridge. Unfortunately this means it's also not possible to increase the tail line beyond 200.

I have been meaning to increase this to 500 by default; as that's what systemd logging's default is.

**Comment by djrams10** [comment]
thank you for your explanations, and for your work.

**Comment by oznu** [comment]
Change will be in 4.6.0
