### ISSUE TITLE
apple-touch-icon.png 

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#34]
@oznu Thanks for your great work and sharing. 👍🏻
Maybe you want to consider to integrate a apple-touch-icon.png in one of your next updates? 😉😃

And is there a chance to change Login screen wallpaper snapshot.jpg individual? With every update of course it's going to default at the moment.

Best,
Daniel
![napkin 12 18 02 18 10 40 44 pm](https://user-images.githubusercontent.com/3874239/36357371-5f830aee-14fd-11e8-86ab-e392d1b818c0.png)
![apple-touch-icon](https://user-images.githubusercontent.com/3874239/36399480-5d891ace-15cc-11e8-9279-71fe4e10ccd3.png)

**Comment by oznu** [comment]
Hi @DJay-X,

Thanks for this. I'll implement it soon.

Did you create this icon?

**Comment by DJay-X** [comment]
I did create this. So its maybe not everyones taste but I thought it could be a good start.
Thx

**Comment by oznu** [comment]
Nice work, I think it looks good. I just wanted to make sure I gave credit to the right person when including it in this project.

I'll see if i can find a way to customise the login wallpaper as well.

**Comment by oznu** [comment]
@DJay-X, do you have an SVG version of this icon?

**Comment by DJay-X** [comment]
[apple-touch-icon.svg.zip](https://github.com/oznu/homebridge-config-ui-x/files/1738261/apple-touch-icon.svg.zip)

**Comment by oznu** [comment]
Thanks @DJay-X, the icons have been added. I'll look at adding support to change the wallpaper another day.
