### ISSUE TITLE
Searchable Logs

### ISSUE THREAD

**Issue by ifeign** [oznu/homebridge-config-ui-x#341]
**Is your feature request related to a problem? Please describe:**
The log isn't searchable, at least in Chrome and Safari on Mac OS. This would be very helpful to aid in debugging, currently I copy the whole log into a text editor and search that.

**Describe the solution you'd like:**
Make the field searchable via the browser "find in page"

**Describe alternatives you've considered:**
Add a search field to the UI itself

**Additional context:**

![image](https://user-images.githubusercontent.com/32289760/62592731-18f12d00-b889-11e9-866d-31f69fcc4a3e.png)

**Comment by grzegorz914** [comment]
Will be better to add a word filter, like in FronTail in OH2.

**Comment by grzegorz914** [comment]
In other thing to the log, can U make then log better readable? (other type of fonts and size) compare to frontail.
![IMG_0064](https://user-images.githubusercontent.com/28867813/63098892-3eaac000-bf74-11e9-89e2-6fe8d672fb8a.png)
![IMG_0065](https://user-images.githubusercontent.com/28867813/63098907-479b9180-bf74-11e9-9f8d-0d0ea9083d45.png)

**Comment by ifeign** [comment]
That would be nice. Not too keen on the black text on white background look, but the filter option on the top right would be cool.

**Comment by ifeign** [comment]
Any chance this can be added?
