### ISSUE TITLE
Missing a style for active Accessory

### ISSUE THREAD

**Issue by Caribsky** [oznu/homebridge-config-ui-x#343]
**Describe The Bug:**
Missing a style for active Accessory

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**
![HB-UI-X__2019-08-07__20 08 49](https://user-images.githubusercontent.com/37780308/62639262-3e953980-b950-11e9-92ea-866d8de0ed69.png)

**Environment:**

* **Node.js Version**: 10.16.0 
* **NPM Version**: 6.9.0 
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.5.1 
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
Which plugin?

Can you right click one of the accessories in the on state and screenshot the characteristics dump shown.

**Comment by Caribsky** [comment]
Screenshot of accessory (plugin homebridge-http-switch v0.5.24)

![Снимок экрана 2019-08-08 в 2 33 53](https://user-images.githubusercontent.com/37780308/62662634-c0ec2080-b985-11e9-8a46-23a8b5379fba.png)

Actually, it doesn't depend on plugin. The same problem with other accessories. 
I found that CSS class "switch-on" for accessory with state ON is missing in file of styles

**Comment by oznu** [comment]
> I found that CSS class "switch-on" for accessory with state ON is missing in file of styles

Thanks for the tip. I'll check this out.

**Comment by oznu** [comment]
Thanks for reporting this @Caribsky,

This is now fixed and will be published in 4.6.0.

I'm waiting on a few things before publishing this build, but you can install the current beta that includes this fix by running this command via the terminal in the UI (Config UI -> Docker Logo -> Terminal):

```
npm install -g --unsafe-perm homebridge-config-ui-x@next
```

Then just restart and refresh the page.

**Comment by Caribsky** [comment]
Thank you @oznu
Just installed next version. Looks good! 

ps. Just note... All my rooms have disappeared. All accessories in Default room

**Comment by oznu** [comment]
That's to be expected... changelog:

> Due to the changes required to identify accessories across multiple instances your room layout will be reset after upgrading
