### ISSUE TITLE
Small bug in the interface Gui of Thermostat

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#349]
Just look on the screenshot (marked area)
Safari on Mac the border is white, on iPad is black.
![IMG_0275](https://user-images.githubusercontent.com/28867813/62792357-665edb80-bacf-11e9-9560-56d1549a6ac3.jpeg)

The new DarkMode looks very nice.

**Comment by oznu** [comment]
Thanks, fixed.
