### ISSUE TITLE
Config editor - kursor in wrong place

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#351]
Hi,

the cursor in config page are placed in wrong place and not corespondend right position, right now we dont know what will be deleted, because if we place the cursor between (d | ark) "d" und "a" and press delete button on the keyboard the deleted charakter is "k" not "d".

Problem exist since beta.26 on safari macOS, on the iPad all OK.

Thanks

**Comment by oznu** [comment]
Can you screen shot the issue?

**Comment by oznu** [comment]
Nevermind, can replicate in Safari, thanks for reporting.

**Comment by oznu** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/3979615/62818886-04ff4100-bb91-11e9-8297-8ca8e86ede03.png)

Also made the selection highlight a more appropriate color for dark mode:

![image](https://user-images.githubusercontent.com/3979615/62818895-1ea08880-bb91-11e9-9654-a44b6345528b.png)

**Comment by grzegorz914** [comment]
Thanks for the quick support.

**Comment by oznu** [comment]
Fixed in the latest beta. Thanks for testing 😄.
