### ISSUE TITLE
NL translation wrong : installeerd -> Geïnstalleerd

### ISSUE THREAD

**Issue by tooh** [oznu/homebridge-config-ui-x#353]
NL translation wrong : installeerd -> Geïnstalleerd

https://github.com/oznu/homebridge-config-ui-x/search?q=Installeerd&unscoped_q=Installeerd

**Comment by oznu** [comment]
Thanks @tooh.

Feel free to edit the language file (you can edit directly on GitHub) and send any other improvements through.
