### ISSUE TITLE
beta.33 does not show accessories

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#354]
Hi,

updated to beta.33 and no any accessories are displayed in webUI.

**Comment by oznu** [comment]
I can't replicate this. I tested on al the major browsers.

Have you tried restarting again?

**Comment by oznu** [comment]
Beta 33 was just cosmetic changes.

**Comment by grzegorz914** [comment]
Yes, 

system restarted 2 times, no accessory displayed.

**Comment by oznu** [comment]
Right, I guess now would be a good time to try out the accessory control debug feature.

Check the box under the plugin settings > accessory control > debug mode:

![1B13814D-3BB3-4244-A6DC-CAC09DC4ADE7](https://user-images.githubusercontent.com/3979615/62833478-d19cdf00-bc82-11e9-81b2-f05c77441002.jpeg)

The save, restart, and post the logs here and I should be able to see what's wrong.

**Comment by grzegorz914** [comment]
Sorry, but nothing new in the log regarding accessory.

**Comment by oznu** [comment]
That's strange, it should have dumped heaps of information into the log. Can you post the startup log anyway?

**Comment by grzegorz914** [comment]
After complete reboot something strange in the log about memory leak.


`(node:2196) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by oznu** [comment]
I can't see anything of the debug info that should be there. There should at least be an error or notice when you native to the accessories page.

You can try rolling back:

```
sudo npm install -g --unsafe-perm Homebridge-config-ui-x@4.6.0-beta.31
```

**Comment by grzegorz914** [comment]
Rollback to .31 all accessory available

**Comment by oznu** [comment]
Interesting, what about .32?

**Comment by grzegorz914** [comment]
.32 was also all OK

**Comment by oznu** [comment]
I just pushed up .34, can you give that a go?

**Comment by grzegorz914** [comment]
.34 not show accessory

**Comment by grzegorz914** [comment]
some mistake, accessory again show after OH reload

**Comment by Caribsky** [comment]
hi @grzegorz914, 
I saw the same problem few versions ago. For some reason, the another instance of Homebridge was launched with a different pairing code when i clicked on restart button.
Only restart docker helped me.

**Comment by grzegorz914** [comment]
hi @oznu 
again tested beta.34 and accessory does not show in web GUI, may be the problem is because right now I have 115 accessories. On iPhone and iPad all accessory are available without any problem.

**Comment by oznu** [comment]
I'm thinking this might be an issue discovering homebridge using bonjour. In beta .35 I've added lots more logging in debug mode and the system now sends a new discovery broadcast every time the accessories page is loaded.

**Comment by grzegorz914** [comment]
beta.37 all working OK.

**Comment by oznu** [comment]
Thanks for confirming @grzegorz914.

I'll be publishing v4.6.0 to everyone in the next two days.

**Comment by oznu** [comment]
Hey @grzegorz914, I made some more changes to instance discovery. Do you mind testing the latest beta to make sure everything is still ok?

**Comment by grzegorz914** [comment]
beta.40 all OK macOS, iPhone, iPad.
