### ISSUE TITLE
Feature request: ability to hide Homebridge QR code page element

### ISSUE THREAD

**Issue by TimofeyK** [oznu/homebridge-config-ui-x#355]
The HomeKit code is generally required only once, when adding the Homebridge instance to HomeKit, however the huge QR code is given a permanent prime position on the status page pushing down the actual server status. This is especially annoying when accessing the page from a mobile browser

Is it possible to add a simple toggle in plugin settings that would fold a hide the whole QR code section? Or maybe a show/hide toggle directly on the page that would remember the choice?

I can hide the page element using Safari's content blocking but prefer the native solution

**Comment by TimofeyK** [comment]
It would be even more logical from the UI design / usage logic to move the QR code to the Config tab or give it its own tab

**Comment by ebaauw** [comment]
Or: simply hide the QR code when homebridge has been paired to HomeKit.  The Bonjour announcement contains this info.

**Comment by benfysh** [comment]
@ebaauw it would be useful to be able to display it when required as some plugins such as [homebridge-ring](https://github.com/dgreif/ring/tree/master/homebridge) and [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen) require you to add devices using the same HomeKit code as Homebridge and it is easier to scan it from another device than manually type it out.

**Comment by ebaauw** [comment]
Does the same QR code work for external accessories?  I thought it is specific for the homebridge accessory, as encodes more info that the pin code:
https://github.com/nfarina/homebridge/blob/84b4733ac75aba9e7c19d36be282cd8162077860/lib/server.js#L685

**Comment by benfysh** [comment]
I have just double checked and it works for me, I assume the home app is just pulling the PIN from the QR code?
![Image](https://user-images.githubusercontent.com/404201/62950656-6406c500-bde0-11e9-9548-c89f0b5d0de6.gif)

**Comment by ebaauw** [comment]
Cool.  Should work with homebridge-zp's new Television accessories as well, then.

**Comment by oznu** [comment]
I've been thinking about hiding the QR code when viewing on a mobile - it's not as if you can make use of the QR code on the same device it's being viewed on.

More generally, I think the whole status page needs a makeover in general; ideas are welcome 😄.
