### ISSUE TITLE
Unable to configure SSL 

### ISSUE THREAD

**Issue by danewallace** [oznu/homebridge-config-ui-x#356]
**Describe Your Problem:**

Hello, when I add the ssl configuration to my JSON, there appears to be no change in behavior. The site fails to load when specifying HTTPS. The HTTP version continue to load. This persists after restarting homebridge, computer, etc. 

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
 {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "restart": "sudo -n systemctl restart homebridge",
            "ssl": {
                "key": "/private/etc/apache2/ssl/idanemacminiprivkey.key",
                "cert": "/private/etc/acpach2/ssl/idanemacminicertificate.crt"
            },
            "log": {
                "method": "file",
                "path": "/Users/danewallace/.homebridge/logfile.log"
            }
        },

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
12.7.0
* **NPM Version**: 
6.10.3
* **Homebridge Version**: 
0.4.50

* **Homebridge Config UI X Version**:
Current 

* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
macOS Mojave (current)

* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none
launchctl

**Comment by oznu** [comment]
While I don't use the SSL feature myself; I have just tested this feature and confirmed it is working.

Please check certificate and key file paths are correct and you have a valid certificate (self signed is ok).

**How I tested:**

Create self signed cert:

```
openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
```

Updated config:

```json
"ssl": {
    "key": "/Users/username/.homebridge/key.pem",
    "cert": "/Users/username/.homebridge/certificate.pem"
}
```

Restart Homebridge. Browser to **https**://localhost:8080. Accept self signed certificate warning.

**Comment by danewallace** [comment]
Ah, must have had an issue with the file extensions. Once they were both output as .pem files everything seemed to fall into place. Thanks for the help.
