### ISSUE TITLE
bug in beta.40, camera duplication

### ISSUE THREAD

**Issue by Caribsky** [oznu/homebridge-config-ui-x#359]
**Describe The Bug:**

Camera duplication. Two tiles of one camera

![Снимок экрана 2019-08-14 в 18 01 13](https://user-images.githubusercontent.com/37780308/63027609-56277180-bebe-11e9-85df-bf3fa0291ac6.png)

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**
```json
{
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "DAHUA CH-1",
                    "uploader": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://***:***@192.168.10.104:554/cam/realmonitor?channel=1&subtype=0",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "packetSize": 1316,
                        "maxFPS": 25,
                        "maxBitrate": 2500,
                        "debug": false
                    }
                }
            ]
        },

```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: v4.6.0-beta.40
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
This is a side effect of multi-instance accessory control.

I was looking at cameras earlier this evening and noticed this, it turns out cameras expose themselves as two "accessories". You can check this by going to http://localhost:<camera port>/accessories.

**Comment by grzegorz914** [comment]
If U enable 2 streams for 1 cam then U have Two tiles of one camera.
I have enabled only 1 and show One tile

**Comment by Caribsky** [comment]
> If you right click the accessory you'll see they have different names I think.

Actually, I see one name "Camera Rtp Stream Management" and same long string of "Supported Video Stream Configuration" for both tiles. 

![Снимок экрана 2019-08-14 в 18 42 59](https://user-images.githubusercontent.com/37780308/63030457-6857de80-bec3-11e9-91aa-dff6c9891dbf.png)

**Comment by Caribsky** [comment]
@grzegorz914
> If U enable 2 streams for 1 cam then U have Two tiles of one camera.
> I have enabled only 1 and show One tile


My DAHUA XVR (in config above ) has General stream and Sub Stream. I can't to disable sub stream. I will try today attach another cam and disable sub stream.

**Comment by grzegorz914** [comment]
Please set 1 stream and look how much Tiles will be displayed. Only for test.

**Comment by Caribsky** [comment]
Thank you @grzegorz914 
I understand. 

`"maxStreams": 1,`

I see one tile. 
I am closing this issue
