### ISSUE TITLE
Issue/Question if i have run node 6.10 the ui-x works fine

### ISSUE THREAD

**Issue by testpaul999** [oznu/homebridge-config-ui-x#36]
Hello,

im not sure about issue/question.
But if i have run node at this Version
pi@raspberrypi:~ $ node -v
v6.10.0
then your UI runs fine.
But for unsing the HUE Plugin i read that i must update node to 8.9.4,
If i do this your pulgin dont will run.

i follow this Instruktion for update node.
https://forum.smartapfel.de/forum/thread/1007-plugin-homebridge-hue/?postID=20159#post20159

homebridge runs fine with this Version of node, but your plugin wont start the WEB-UI

Regads for help

jens

**Comment by oznu** [comment]
This plugin runs fine on 8.9.4. You will have to uninstall the reinstall it (using --unsafe-perm) after upgrading Node.js.
