### ISSUE TITLE
update for Bulgarian language

### ISSUE THREAD

**Issue by mafyata** [oznu/homebridge-config-ui-x#364]
I noticed some wrong translations. Here is re-translated file. Now everything is perfect. :)
[bg.zip](https://github.com/oznu/homebridge-config-ui-x/files/3507365/bg.zip)

**Comment by oznu** [comment]
This will be included in 4.6.1... if you want to try the beta release:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

**Comment by mafyata** [comment]
[bg.zip](https://github.com/oznu/homebridge-config-ui-x/files/3653822/bg.zip)
Fixed translations.

**Comment by mafyata** [comment]
Will you put new language improvments in next update? I uploaded the new file at 25 september.

**Comment by oznu** [comment]
Sorry I missed that. If you edit the file on GitHub you'll be given the opportunity to create a "Pull Request" which allows me to merge in your changes directly (and you're given attribution for them).

https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/i18n/bg.json

**Comment by mafyata** [comment]
I don’t remember all changes that I had made.

**Comment by mafyata** [comment]
Please put the updated bg.json in the plugin.

**Comment by mafyata** [comment]
Hi , yesterday I updated the plugin but changes on my translation are not included. Will you update Bulgarian language?

**Comment by oznu** [comment]
Hi @mafyata, it will be included in the next release.

Thanks.
