### ISSUE TITLE
 TypeError: Cannot read property 'md' of undefined

### ISSUE THREAD

**Issue by GPL71** [oznu/homebridge-config-ui-x#370]
Hello ...
Thank you for your great work!!!
just finished install homebrdidge and config ui x plugin.
Then all is at the last release
I have the follow message, but nothing found in the net.
Please can you help me?
Thank you

![Schermata 2019-08-19 alle 22 01 55](https://user-images.githubusercontent.com/34108470/63295501-194be800-c2cd-11e9-8c76-595d9c78db9b.png)

**Comment by oznu** [comment]
Can you provide details of your environment?

```markdown
**Environment:**

* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
```

**Comment by kalety** [comment]
Same here!
**Node.js Version**: 10.16.3
**NPM Version**: 6.9.0
**Homebridge Version**: 0.4.50
**Homebridge Config UI X Version**: homebridge-config-ui-x v4.6.0
**Operating System**: Raspbian

Thanks in advance!

**Comment by GPL71** [comment]
**Node.js Version**: 10.15.2
* **NPM Version**: 5.8.0
* **Homebridge Version**: 4.5.0
* **Homebridge Config UI X Version**: 4.6.0
* **Operating System**: Raspbian

Thank you for your help

**Comment by oznu** [comment]
This should be fixed in 4.6.1... if you want to try the beta release:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

**Comment by GPL71** [comment]
thank you

**Comment by GPL71** [comment]
updated to beta release ... but same problem!

![Schermata 2019-08-21 alle 21 12 31](https://user-images.githubusercontent.com/34108470/63461221-745e1600-c458-11e9-9139-ebf8a47bf55b.png)
Maybe the problem is bonded to accessories tab ? Message appear when I tap the accesory tab.
I have a camera and ffmpeg plugin.

![Schermata 2019-08-21 alle 21 19 06](https://user-images.githubusercontent.com/34108470/63461648-5b099980-c459-11e9-85b5-c890aaffb3bd.png)

**Comment by oznu** [comment]
Sorry @GPL71,

Try that again.

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

**Comment by kalety** [comment]
> Sorry @GPL71,
> 
> Try that again.
> 
> ```
> sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
> ```

At last!, this seems work flawlessly

Thank you

**Comment by oznu** [comment]
Thanks for confirming. 4.6.1 has now been published.
