### ISSUE TITLE
SSL cert

### ISSUE THREAD

**Issue by onefish2** [oznu/homebridge-config-ui-x#373]
What is the easiest and cheapest way to enable SSL for config-ui-x? I tried a self signed cert but the browsers (FF, Chrome) don't like it and give errors. So I had to create an certificate exception.

**Comment by oznu** [comment]
Check out https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Nginx-and-SSL.

**Comment by onefish2** [comment]
@oznu, as always, thank you for the quick response!!
