### ISSUE TITLE
Add system/CPU temp to the status page

### ISSUE THREAD

**Issue by guyssbrown** [oznu/homebridge-config-ui-x#374]
Would it be possible to add a feature to display the system temp (or CPU temp) on the status page. 

It could be done via entering a command based on the os/system in the plugin config via config.json, such as “temp”:  “/opt/vc/bin/vcgencmd measure_temp”, and only show on the status page if there is a value entered for “temp”. 

Thanks,

Guy

**Comment by ebaauw** [comment]
https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#temp

**Comment by mafyata** [comment]
Please read wiki before you open issue.

**Comment by guyssbrown** [comment]
How did I miss that!!! Sorry 😐
