### ISSUE TITLE
Temperature value with decimal place and...

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#376]
Hi @oznu 

can u adapted accessory tiles for temperature and thermostat to display same value as in HomeKit app, with decimal place and additional value in bottom?
![IMG_0068](https://user-images.githubusercontent.com/28867813/63637643-d1d3ac00-c67e-11e9-930b-ce76b0c68eae.jpeg)
![IMG_0073](https://user-images.githubusercontent.com/28867813/63646305-b31df580-c710-11e9-9851-1dccbefe788f.jpeg)
![IMG_0069](https://user-images.githubusercontent.com/28867813/63637647-d8622380-c67e-11e9-9f5d-20fc85c8895a.jpeg)

Thanks

**Comment by oznu** [comment]
Is that iOS 13 beta?

**Comment by grzegorz914** [comment]
Yes

**Comment by AdamVR7** [comment]
I need it, too. Please add a decimal place. I have iOS 13.3.1.

**Comment by Kahuna711** [comment]
Maybe I have also a problem with decimal character? Siri can't get temperature when is ".5"

**Comment by oznu** [comment]
Done in the next release.

![image](https://user-images.githubusercontent.com/3979615/84144736-1f00fd00-aa9c-11ea-8e08-44c16a5241f9.png)

**Comment by AdamVR7** [comment]
Very well)))
