### ISSUE TITLE
Value and descriptions of tiles

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#377]
It will be nice to align all description of tiles and state value to left and bottom of the tile.
Please also move all descriptions of tile to the bottom to make same margin from the left and bottom.
Look on the screenshots:
![IMG_0072](https://user-images.githubusercontent.com/28867813/63637839-938bbc00-c681-11e9-8fec-b90c1475ed8d.jpeg)

![IMG_0071](https://user-images.githubusercontent.com/28867813/63637797-558e9800-c681-11e9-80bc-b8f15b4b3450.jpeg)

**Comment by oznu** [comment]
These will be aligned in an upcoming release.

![image](https://user-images.githubusercontent.com/3979615/71777895-d3cd5480-2ffa-11ea-957c-185a0ba52c2f.png)

**Comment by mafyata** [comment]
Please don’t forget to update json file I have send for Bulgarian language.
