### ISSUE TITLE
iPad, iPhone move tiles not correct

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#378]
Moving tiles on iPhone or iPad is not possible, moved tile in horizontal position working, but if we moving tile in vertical position then, after touch the tile and hold them and moved in vertical position the tile is not moved, only whole page is moved.

**Comment by oznu** [comment]
Thanks, this is a know issue I don't plan on fixing. The UI disables tile dragging on mobile by default (on wider screens you might be able to unlock, but it's still not something I support).

**Comment by grzegorz914** [comment]
OK
all clear.

**Comment by oznu** [comment]
Yeah I'm limited by what third party libraries are capable of when it comes to drag-and-drop. I haven't come across one that actually works 100%  in a mobile browser.

**Comment by grzegorz914** [comment]
No problem,
in other thing iPadOS now uses full desktop Safari browser.
