### ISSUE TITLE
New issue with config 4.6.1

### ISSUE THREAD

**Issue by GPL71** [oznu/homebridge-config-ui-x#379]
Hello ... new issue with version 4.6.1
All was working fine ...
After 4.6.1 update starts the follow issue after a while since homebridge starts

Node.js Version: 9.11.2
NPM Version: 5.8.0
Homebridge Version: 4.5.0
Homebridge Config UI X Version: 4.6.1

![Schermata 2019-08-24 alle 22 32 49](https://user-images.githubusercontent.com/34108470/63642435-25fe8080-c6bf-11e9-996b-c5339351a71c.png)

Operating System: Raspbian

**Comment by oznu** [comment]
These errors are saying your sever can't connect or resolve the DNS records for the npm registry. Please check your network settings - or just try again later, it's not uncommon for npm to have issues.
