### ISSUE TITLE
[Enhancement] Show homebridge instance name

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#38]
Currently the web page always shows "Homebridge" as the title. It would be nice if it could use the actual name given for the homebridge instance.

Background: I have multiple homebridge servers running and when you have multiple web pages open it can become cumbersome to see which servers page you're on.

Thanks for this awesome software!

**Comment by oznu** [comment]
Hi @normen,

Thanks for your suggestion. This will be added in the next major release.

**Comment by normen** [comment]
Awesome, thanks. For now the nice "theme" feature helps - but not in the tab bar :)

**Comment by Hatika78** [comment]
Thanks for your work. But it would be great if the instance name were beside the status button. When I'm connect on my smartphone I don't have the page name on the tab bar.
