### ISSUE TITLE
plugin doesn't update

### ISSUE THREAD

**Issue by paqpaqpaq** [oznu/homebridge-config-ui-x#380]
Since 4.5, whenever there's an update, homebridge more or less freezes at the plugin update screen. After about 15 minutes of no change, I press CLOSE.
The [UPDATE] button now disappears, but the plugin hasn't been updated though.
The plugin overview also displays the old version (still 4.5.0).
After a reboot, all remains the same.
Status: 4.5.0. up to date (currently it is 4.6.1. actually)

**Comment by oznu** [comment]
Hi @paqpaqpaq,

Filling in the issue template will help me help you solve the problem.

```
**Environment:**

* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->
```

**Comment by paqpaqpaq** [comment]
Sorry

Node 8.14.0
npm 6.4.1
homebridge 0.4.50
Raspbian systemd

**Comment by oznu** [comment]
Thanks; which raspberry Pi model?

**Comment by paqpaqpaq** [comment]
Pi 3B

**Comment by oznu** [comment]
Ah I see the problem. This plugin does not work properly with Node.js versions lower than v8.15.3. Specifically the module used during the update process.

https://github.com/oznu/homebridge-config-ui-x#supported-nodejs-and-npm-versions

Ideally you should upgrade to Node.js 10, which is the current LTS version.

You will need to reinstall the plugin after updating:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

And rebuild any other plugins:

```shell
cd $(npm -g prefix)/lib/node_modules
npm rebuild
```

**Comment by paqpaqpaq** [comment]
On another pi (same setup) I have node 10.
Same issue

**Comment by Hedinjar** [comment]
Hi.
i have node 10.16 and my plugin do not update too (((

**Comment by Hedinjar** [comment]
The problem was never solved. To install the plug-in does not work! 

Error code:
 `pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-config-ui-x
[..................] - loadRequestedDeps: sill install loadAllDepsIntoIdealTree
`

**Comment by paqpaqpaq** [comment]
is this issue still alive?
