### ISSUE TITLE
Config UI unavailable after DSM 6.2.2-24922-3 update

### ISSUE THREAD

**Issue by willio** [oznu/homebridge-config-ui-x#381]
My homebridge installation was acting up, so I decided to redo my installation all over again. I updated DSM to the latest per the title above, and proceeded to install homebridge docker per the instruction in this page. Everything went smooth, and the log showed that homebridge docker is running, except when I open the config UI, the 'page cannot be found' error is shown in the browser. Any idea what's going on here?

**Comment by oznu** [comment]
Please see https://github.com/oznu/docker-homebridge/issues/227
