### ISSUE TITLE
UI 4.6.1 

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#382]
@oznu 

Im on 4.6.1 beta.4 and alway in status page display update available to 4.6.1.

**Comment by oznu** [comment]
Hi @grzegorz914, `4.6.1` is an update to `4.6.1-beta.4`.

https://semver.org/#spec-item-11

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by grzegorz914** [comment]
4.6.1 relesaed 3 days ago, beta.4 yesterday
I think 4.6.1 does not contain changes from beta.4 or?

**Comment by oznu** [comment]
Where do you see that?

![image](https://user-images.githubusercontent.com/3979615/63827514-b16d5f80-c9a6-11e9-9b01-733e85371f85.png)

**Comment by grzegorz914** [comment]
OK

my mistake.
