### ISSUE TITLE
UI not loading after update to Synology Docker Package.

### ISSUE THREAD

**Issue by JDogg016** [oznu/homebridge-config-ui-x#383]
## Please see this issue for solution: https://github.com/oznu/docker-homebridge/issues/227

---
I have two instances of home bridge running.

Both on the same IP, but different ports and they have worked flawlessly for about a year.

I had to reset my entire Eero network, but kept the IP address for Homebridge the same.

I can go to my local ip http://192.168.7.x:8081 and access the homebridge
I cannot go to http://192.168.7.x:8080 to access my other home bridge instance.

I can view (from Synology) that home bridge is running and I have a code.

I even reinstalled homebridge in its entirety with the same result.

I must be missing a step.

**Comment by fraho67** [comment]
Yesterday I also reinstalled everything and can since then no more access the GUI. I'm glad that I'm not the only one :-)

**Comment by oznu** [comment]
Did you update the Synology Docker page recently?

https://github.com/oznu/docker-homebridge/issues/227

**Comment by fraho67** [comment]
Yes, that was yesterday

**Comment by oznu** [comment]
See the issue linked above. The Docker Package SPK Synology rolled out is broken and is not applying environment variables to containers.

There are a couple work arounds in that issue.

**Comment by oznu** [comment]
Adding it to the config.json is just a work around, logs and installing plugins won't work without the environment variables being set.

**Comment by fraho67** [comment]
I've downgraded and it's working again, thanks for the info!
