### ISSUE TITLE
Testers Wanted: Homebridge as a Service on Windows 10

### ISSUE THREAD

**Issue by oznu** [oznu/homebridge-config-ui-x#384]
One of the new features released in 4.6.0 was the ability to setup Homebridge Config UI X and Homebridge to run as a service on Windows 10.

The setup is a simple 3 step process:

1. Install Node.js
2. Install Homebridge and Homebridge Config UI X
3. Run `hb-service install`

See https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-on-Windows-10 for the full commands.

I've been testing this on fresh Windows 10 / Server 2016 virtual machines and it seems to work quite well. I'm looking for a few people to try this out (uninstall instructions are also provided) to get feedback.

![hb-service-install](https://user-images.githubusercontent.com/3979615/63936029-34bfab80-caa2-11e9-8cd6-abfecdc540a4.gif)

**Comment by gladiatormax** [comment]
Hi,
I installed the service on a already running homebridge system without any problems.
Windows 1903 64bit.
with nodejs v10.16.3.

Nice to see it became so easy on a windows system.

Thank you for all your work!
