### ISSUE TITLE
default username and password incorrect

### ISSUE THREAD

**Issue by Tucker28** [oznu/homebridge-config-ui-x#385]
**Describe Your Problem:**
Cannot login to UI.  Default username and password of admin do not work.
I have uninstalled and reinstalled.  Doesn't let me log in.

**Logs:**
I set the config.json file to write logs, but nothing is listed.

```
Nothing in the log file
```

**Homebridge Config:**

```json
{
    "bridge": {
      "name": "Homebridge",
      "username": "CC:22:3D:E3:CE:30",
      "port": 51826,
      "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
          "accessory": "TuyaOutlet",
          "name": "Tuya Outlet",
          "devId": "012005935ccf7fdf8e19",
          "localKey": "966e64437e7670b7"
        }
    ],

    "platforms": [
      {
        "platform": "Hue",
        "users": {
          "001788FFFE7D2003": "8SC039ooD3uvucBYelCzyZ99D8hEuffkEUhJU-bD",
          "001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
        },
        "sensors": true,
        "nativeHomeKitSensors": false,
        "excludeSensorTypes": ["CLIPPresence", "Geofence"],
        "lights": true
      },
      {
          "platform": "config",
          "name": "Config",
          "port": 8080,
          "log": {
            "method": "file",
            "path": "~/.homebridge/homebridge.log"
          },
          "sudo": true
      }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 10.11.0
* **NPM Version**: 6.11.3
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.6.1
* **Operating System**:  macOS
* **Process Supervisor**: launchd

**Comment by toshibochan** [comment]
You try username: admin and password: admin?

**Comment by Tucker28** [comment]
Yes.  Different variations of caps as well, nothing works.  I've uninstalled and reinstalled twice now.  Still nothing

**Comment by toshibochan** [comment]
Did you change passwords some point?

**Comment by Tucker28** [comment]
No, today was the first time I downloaded it.  I had Homebridge Config UI first for a while, but it never did anything except show the status.  So I uninstalled it, then installed Homebridge Config UI X.  I tried my old username and password for the old UI just in case it read from that, but that didn't work either.

**Comment by oznu** [comment]
Delete the `~/.homebridge/auth.json` file and restart Homebridge.

**Comment by Tucker28** [comment]
that was it.  Which is odd, since it had the defaults correct in there as well as my personal username, but it works now.  Thank you!

**Comment by oznu** [comment]
It was likely the old format from the `homebridge-config-ui` plugin. I did have code in place for about two years to automatically migrate from the old format to the new format, but it got removed in the last major update as I thought most people would have migrated by now.

You'll notice your password is no longer stored in plain text when using the `homebridge-config-ui-x` format 😄.
