### ISSUE TITLE
Docker - 401 Unauthorized

### ISSUE THREAD

**Issue by tavicu** [oznu/homebridge-config-ui-x#387]
Hei! I have two instances of Homebridge through docker and since the last update i get an error in the second instance:

`[Config] [HapClient] [INSTANCE1 IP:PORT (INSTANCE1 MAC)] 401 Unauthorized - make sure Homebridge pin for this instance is set to INSTANCE2 PIN.`

From what i understand the second intance (INSTANCE2) want's to set the same pin to INSTANCE1.

There is a method to declare the pin or should i use the same pin on all my instances?

Thank you!

**Comment by oznu** [comment]
> From what i understand the second intance (INSTANCE2) want's to set the same pin to INSTANCE1.

Yes, if you wish to be able to control allaccessories from one instance.

> There is a method to declare the pin or should i use the same pin on all my instances?

You just have to make sure it's the same in the config.json for both instances.
