### ISSUE TITLE
Different Login Accounts

### ISSUE THREAD

**Issue by mkormendy** [oznu/homebridge-config-ui-x#389]
I would like to be able to provide different users access to the Config UI with different logins so I don't have to share the same login with all users in the house.

It would be nice to also restrict some users from modifying certain accessories when the -i flag is used with homebridge for insecure mode.

**Comment by oznu** [comment]
Hi @mkormendy,

It's already possible to create multiple login accounts. Each account has their own customisable accessory layout, and you can choose not to display certain accessories on the accessories page on a per-account basis (though this is not restricted, the user can unhide them).

**Comment by mkormendy** [comment]
Okay @oznu - you can also label this ticket "user-error". I can't believe I missed the users option at the top:

![Screen Shot 2019-09-13 at 10 21 27 PM](https://user-images.githubusercontent.com/1437667/64902860-07aff300-d675-11e9-9b6a-20d4b9560f9b.png)

Thanks for putting that in there!
