### ISSUE TITLE
[Feature] Shutdown button (and others)

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#39]
It would be nice to have a shutdown button for the whole computer as well. As many people use Raspberry PI computers without any physical power button the web interface would be an easy way to shut down the computer.

Other buttons could be added too for restarting etc. - maybe the whole thing could be a configuration option to extend the top bar with custom commands.

Thanks again for this awesome plugin.

**Comment by oznu** [comment]
This has been implemented in 3.3.0.

The extra actions menu will only show up on linux when not running in docker.

If you wish to customise the restart and shutdown commands you can add this to your config block:

```json
{
  "platform": "config",
  "name": "Config",
  "port": 8080,
  "sudo": true,
  "linux": {
     "shutdown": "my custom shutdown command",
     "restart": "my custom restart command"
  }
}
```

**Comment by normen** [comment]
I'm sorry but was the option to have custom commands removed? I'd like to set up a backup script I can start from config-ui-x.

Cheers!

**Comment by oznu** [comment]
The config example in my comment above  to customise the restart and shutdown commands should still work.

https://github.com/oznu/homebridge-config-ui-x/blob/master/config.schema.json#L298

**Comment by normen** [comment]
Sorry, I was under the impression that you could enter any command as well as shutdown/reboot, I'll make this a feature request then ;)
