### ISSUE TITLE
delete persist

### ISSUE THREAD

**Issue by platini76** [oznu/homebridge-config-ui-x#391]
it is possible to have one button that delete persist when it is not more used?

**Comment by oznu** [comment]
Hi @platini76,

Can you elaborate on what you want to happen here?

**Comment by platini76** [comment]
I would like to have a button on fixture (unused or old) that allow me to cancel them from homekit is it possible? thanks for your work!

**Comment by platini76** [comment]
it is possible? I have 2 old persist that I don't use anymore... and they are always off.. the only solution is to reset homebridge and restart all?

**Comment by platini76** [comment]
any news? I have two persist devices that I cannot delete....

**Comment by platini76** [comment]
hello?
