### ISSUE TITLE
[Config] [HapClient] [x.x.x.x:42267 (xx:xx:xx:xx:xx:xx)] Failed to connect

### ISSUE THREAD

**Issue by sherazan** [oznu/homebridge-config-ui-x#393]
Hi, I configured a 2th HB istance for test pourpuse (using -I paramter in the startup option); now I'm not using this 2th istance and the related server is powered off, but in the my 1st (main) HB istance I receive the following message:

[Config] [HapClient] [x.x.x.x:42267 (xx:xx:xx:xx:xx:xx)] Failed to connect

every time that i select Accessories in the Config UI-X panel.

HB version 0.4.50
UI-X version 4.6.1

Please, let me know.

Thanks

Guido

**Comment by oznu** [comment]
If you restart your main instance the message will go away.

**Comment by sherazan** [comment]
Done. Solved!

Thanks
