### ISSUE TITLE
What is "debug level logging for accessory control"

### ISSUE THREAD

**Issue by dcaccount** [oznu/homebridge-config-ui-x#394]
Hello,
under the "Accessory control settings" I have found this setting that I can not understand:

"enable/disable debug level logging for accessory control"

Can anyone lease explain its purpose?
Thanks,
Dan

**Comment by mkellsy** [comment]
It's used for developing accessory controls. It outputs more data to the log, which in normal operation, would be unnecessary.

**Comment by oznu** [comment]
Hi @dcaccount,

I made some major changes to accessory control recently and thought these new features might be problematic so I added the debug option - fortunately I haven't had to ask any users to enable this option yet 😄!
