### ISSUE TITLE
configuration of multiple instances?

### ISSUE THREAD

**Issue by iGodPhil** [oznu/homebridge-config-ui-x#396]
Hey first of all thanks to your nice plugin.

My Config UI X is running in standalone mode.
Is it possible to manage multiple instances on one server and use a drop-down menu to select which instance you want to configure?

**Comment by oznu** [comment]
Hi @iGodPhil,

Not currently, maybe one day. I did some work on this a while ago but ran into some blockers.

https://github.com/oznu/homebridge-config-ui-x/tree/multi-instance
