### ISSUE TITLE
FFMPEG issue 'Error Code -2'

### ISSUE THREAD

**Issue by JDogg016** [oznu/homebridge-config-ui-x#397]
When accessing any of my cameras I receive the log below

[9/2/2019, 6:38:29 PM] [Camera-ffmpeg] Start streaming video from Playground with 1280x720@299kBit                                              
[9/2/2019, 6:38:29 PM] [Camera-ffmpeg] An error occurs while making stream request                                                              
[9/2/2019, 6:38:29 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code -2   

The config.json file works fine and is follows:

{
                    "name": "Playground",
                    "videoConfig": {
                        "source": "-re -i rtsp://xxx:xxx@xxx.xxx.xxx.xxx:554/videoMain",
                        "stillImageSource": "-i http://xxx.xxx.xxx.xxx:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=JDogg016&pwd=helen143&",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10

This is my startup.sh file:

#!/bin/sh

#
# Docker Homebridge Custom Startup Script - oznu/homebridge
#
# This script can be used to customise the environment and will be executed as
# the root user each time the container starts.
#
# If using this to install plugins DO NOT use the global flag (-g).
#
# Example installing homebridge plugin:
#
# npm install homebridge-hue
#
# Example installing packages using default image (Alpine Linux):
#
# apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
#
# If you're running a debian based version of this container please use apt-get to install packages.
#

apk add --no-cache ffmpeg ffmpeg-libs
Environment:
Homebridge ozone no-avahi (although I have tried Debian no-avahi as well as 'latest)
Homebridge UI 4.6.1
Node JS 10.16.3
FFMPEG 0.1.12
Docker Version: 18.09

**Comment by oznu** [comment]
Hi @JDogg016,

Please direct this issue to the issues page on homebridge-camera-ffmpeg; this is not a problem with homebridge-config-ui-x.
