### ISSUE TITLE
Homebridge Does Not Restart after Power Loss

### ISSUE THREAD

**Issue by dawger1** [oznu/homebridge-config-ui-x#399]
In general my homebridge server running on a Raspberry Pi 3 is rock solid, and works flawlessly.  However, if the raspberry pi loses power for whatever reason, the homebridge service does not restart.  When power is restored to my raspberry pi, I can access config UI X, but the homebridge service is not running (red circle with a line through it).  Manually deleting the cachedAccessories file and restarting the homebridge server via the terminal restarts the service correctly, but this is impossible to fix when I'm away from home at work or travelling.

In an attempt to fix this issue, I added a line to my startup script in homebridge to remove the cachedAccessories folder as follows: "rm -rf homebridge/volumes/homebridge/accessories/cachedAccessories".  Unfortunately, it does not appear as though the command runs after restoring power, as the homebridge service does not restart after restoring power, and the cachedAccessories file remains.  It appears as though homebridge is not restarting because of a problem with this cachedAccessories file, but because homebridge is not restarting correctly, it never has a chance to run the startup script to remove the file.

As a Linux newb, can you please tell me how I can setup raspbian to automatically remove the cachedAccessories file upon restoring power?  

Unfortunately, there are no logs to show when I check.  The logs are blank between the time power is lost, and the time I manually restart homebridge after deleting cachedAccessories.

Thanks in advance for your time.  Have a good day.

**Comment by oznu** [comment]
Hi @dawger1,

Please fill in the issue template; without this information I can only guess how your system is setup.

```
**Environment:**

* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none
```

**Comment by dawger1** [comment]
Hi there,

Here’s my additional info as requested:
* **Node.js Version**:  10.14.2

* **NPM Version**:  6.8.0

* **Homebridge Version**:  0.4.50

* **Homebridge Config UI X Version**: 4.6.1

* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other:  Docker on Raspberry Pi 3

* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none?  Not sure, followed the wiki instructions to manually setup Homebridge & Docker on my Raspberry Pi 3B here: https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi#manual-install

Thanks for your time and patience. Have a good day. 

Brian

**Comment by 2Qt2beStr8** [comment]
Hi,
I have the same issue

**Environment:**

* **Node.js Version**:  v10.16.3
* **NPM Version**:  6.9.0
* **Homebridge Version**:  0.4.50
* **Homebridge Config UI X Version**: v4.6.3
* **Operating System**: Raspbian Buster
* **Process Supervisor**: Systemd

**Comment by bohtho** [comment]
This is a consistent issue as described above.

Environment:

Node.js Version: v12.11.1
NPM Version: 6.9.0
Homebridge Version: 0.4.50
Homebridge Config UI X Version: v4.6.6
Operating System: DietPi
Process Supervisor: Systemd
