### ISSUE TITLE
[Enhancement] Show Version of n, npm, node

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#40]
@oznu First, thanks a lot for your great work and sharing. Wouldn't want to miss config-ui-x

Maybe you will consider in one of the next updates to also show the Version of n, npm, node running.
Would be a helpful enhancement.

Thanks in advance for the time you are investing. 

Have a good one. 👍🏻

**Comment by normen** [comment]
Hm.. as long as it can't update them why clutter the interface? But having the option would certainly be good!

**Comment by oznu** [comment]
Getting the npm version would require an file system call which I don't really want to do. I will add the current node.js version for you.

I'll add the current plugin and node version to the bottom of the status page next to that small "reset homebridge" button 

![image](https://user-images.githubusercontent.com/3979615/36942797-a643c450-1fcf-11e8-989a-fa9aeda60975.png)

This will be added in the next major release (3.x).
