### ISSUE TITLE
How to Restart or Shutdown server if "sudo": false?

### ISSUE THREAD

**Issue by Olepir** [oznu/homebridge-config-ui-x#402]
How to Restart or Shutdown server if "sudo": false?
Thanks

**Comment by DigiH** [comment]
I just added the following line to the sudoers file with `sudo visudo`

homebridge ALL=(ALL) NOPASSWD: /bin/systemctl restart homebridge

**Comment by Olepir** [comment]
I need to restart Server (RPi in my case), not Homebridge service.

**Comment by oznu** [comment]
You can customise the shutdown and restart commands as per this comment: https://github.com/oznu/homebridge-config-ui-x/issues/39#issuecomment-373681891

**Comment by Olepir** [comment]
> You can customise the shutdown and restart commands as per this comment: [#39 (comment)](https://github.com/oznu/homebridge-config-ui-x/issues/39#issuecomment-373681891)

Thanks!!!
