### ISSUE TITLE
Plugin Settings

### ISSUE THREAD

**Issue by DewGew** [oznu/homebridge-config-ui-x#405]
Im trying to add settings menu to my plugin.
I have a variable in config.json like this:

`"excludedDevice": ["1234", "134", "456"]`

How can I add this to my setting menu?

**Comment by oznu** [comment]
Checkout https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI#arrays

```json
{
  "pluginAlias": "YourPluginAlias",
  "pluginType": "accessory",
  "schema": {
    "type": "object",
    "properties": {
      "excludedDevice": {
        "title": "Excluded Devices",
        "type": "array",
        "items": {
          "title": "Excluded Item IDs",
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by DewGew** [comment]
Thanks now I figured it out. I had to add layout also
