### ISSUE TITLE
I can't open homebridge when i install this plugin

### ISSUE THREAD

**Issue by CharlieCatt** [oznu/homebridge-config-ui-x#407]
**Describe The Bug:**

when i starts homebridge with this plugin in stops

**To Reproduce:**

**Expected behavior:**

stop homebridge
**Logs:**

```
i haven't got logs
```

**Homebridge Config:**

```json
{
  "bridge": {
    "name": "Homebridge Hub",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "258-02-580"
  },

  "accessories": [
      {
        "platforms": [
          {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true
          }
      ]
  }
]
}

```

**Screenshots:**
![Snímka obrazovky 2019-10-10 o 21 03 11](https://user-images.githubusercontent.com/50016870/66598606-aa3e9180-eba1-11e9-9413-5ebbb1c3eec0.png)

**Environment:**

* **Node.js Version**: v10.16.3
* **NPM Version**: i do not know
* **Homebridge Version**: 0.4.64
* **Homebridge Config UI X Version**: 4.6.2-test.1
* **Operating System**: Raspbian
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / other / none i do not know

**Comment by tooh** [comment]
I encounter the same problem.

Found following in the logs

'''
argv "/usr/bin/node" "/usr/bin/npm" "--verbose" "install" "-g" "homebridge-config-ui-x"
npm verb node v10.16.3
npm verb npm  v6.11.3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
'''

**Comment by oznu** [comment]
@CharlieCatt - see revised config below. The config should not be in the `accessories[]` array.

```json
{
  "bridge": {
    "name": "Homebridge Hub",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "258-02-580"
  },
  "accessories": [],
  "platforms": [
     {
        "platform": "config",
         "name": "Config",
         "port": 8080,
          "sudo": true
     }
  ]
}
```
