### ISSUE TITLE
Create theme

### ISSUE THREAD

**Issue by edwardbattistini** [oznu/homebridge-config-ui-x#408]
Hi,

I'm trying to create an iOS like theme for the config UI but I'm not sure how to get the scss file on my instance of homebridge. Let me know if you can point me in the right direction.

Thanks

**Comment by oznu** [comment]
Hi @edwardbattistini,

The scss is compiled and bundled for distribution in npm packages which won't provide anything useful.

Checkout https://github.com/oznu/homebridge-config-ui-x/blob/master/CONTRIBUTING.md

And

https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/scss/theme-dark.scss

As starting points.

**Comment by edwardbattistini** [comment]
I've had a first go in my spare time.
Here is where I got to. If anyone wants to contribute more 
https://github.com/edwardbattistini/homebridge-config-ui-x
