### ISSUE TITLE
Unknown lvalue 'AmbientCapabilities' in section 'Service'

### ISSUE THREAD

**Issue by themick4u** [oznu/homebridge-config-ui-x#409]
Following the guide and also Standalone Mode procedures I am getting this in my journal logs within homebridge:

[/etc/systemd/system/homebridge.service:14] Unknown lvalue 'AmbientCapabilities' in section 'Service'

Wondering if I am missing something?
Here is the txt from my /etc/systemd/system/homebridge-config-ui-x.service:

[Unit]
Description=Homebridge Config UI X
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge-config-ui-x $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_$
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target

**Comment by oznu** [comment]
Hi @themick4u,

It looks like this message will appear on older versions of `systemd`. You can remove the `AmbientCapabilities` and it will probably still work.

**Comment by oznu** [comment]
If it's not causing any issues (apart from that log line), I would just leave it to ensure everything keeps working if you do update systemd later.

**Comment by themick4u** [comment]
Ok, great! And thanks so much
