### ISSUE TITLE
[Bug] file logging leaves leftover processes in sudo mode

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#41]
Setup:
- homebridge-config-ui-x v2.7.0
- Raspbian jessie / latest stable version of most everything
- homebridge running as a different user (called "homebridge")
- homebridge-config-ui-x running with sudo mode enabled
- homebridge-config-ui-x logging with a file parameter ("/var/log/homebridge.log")

When opening and then closing the logging window multiple times there is a "tail" process being created each time and never closed. These processes remain active during the runtime of homebridge.

This is not the case on another homebridge server where the homebridge process runs as root and the sudo mode is disabled (otherwise same setup).

**Comment by oznu** [comment]
I can't replicate this on Raspbian **Stretch**. This was fixed in https://github.com/oznu/homebridge-config-ui-x/issues/29 and tested on Ubuntu 16.04 and Raspbian Stretch.

Running homebridge as a non-root user.

Before accessing log page:

```
root@raspberrypi:/home/pi# ps aux | grep "tail"
root      1211  0.0  0.0   4372   564 pts/0    S+   23:38   0:00 grep tail
```

Access log page:

```
root@raspberrypi:/home/pi# ps aux | grep "tail"
root      1212  3.0  0.3   7228  3268 pts/1    Ss+  23:39   0:00 sudo -n tail -n 100 -f /var/log/daemon.log
root      1217  0.0  0.0   3504   392 pts/1    S+   23:39   0:00 tail -n 100 -f /var/log/daemon.log
root      1219  0.0  0.0   4372   544 pts/0    S+   23:39   0:00 grep tail
```

Leave log page:

```
root@raspberrypi:/home/pi# ps aux | grep "tail"
root      1224  0.0  0.0   4372   556 pts/0    S+   23:39   0:00 grep tail
```

Go back to log page:

```
root@raspberrypi:/home/pi# ps aux | grep "tail"
root      1225  3.0  0.3   7228  3344 pts/1    Ss+  23:39   0:00 sudo -n tail -n 100 -f /var/log/daemon.log
root      1230  0.0  0.0   3504   412 pts/1    S+   23:39   0:00 tail -n 100 -f /var/log/daemon.log
root      1232  0.0  0.0   4372   564 pts/0    S+   23:39   0:00 grep tail
```

**Comment by normen** [comment]
Well I could copy-paste the same snippets doing the opposite :) Maybe its because my homebridge user is a nologin user?

**Comment by normen** [comment]
Well whaddyaknow.. Now they do quit, must be an edge case as I didn't update or change either homebridge, the plugin or its settings (or the general linux setup). I did reboot the server and change other settings in the homebridge setup though.

By the way I didn't have the "doubling" of the log like the guy in the issue you linked.

**Comment by normen** [comment]
WTF, okay yes it's an edge case :)

` ps -ax | grep tail
13843 ?        Ss     0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
13848 ?        S      0:00 tail -n 100 -f /var/log/homebridge.log
13853 ?        Ss     0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
13858 ?        S      0:00 tail -n 100 -f /var/log/homebridge.log
13861 ?        Ss     0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
13866 ?        S      0:00 tail -n 100 -f /var/log/homebridge.log
14069 ?        Ss     0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
14074 ?        S      0:00 tail -n 100 -f /var/log/homebridge.log
14079 pts/8    Ss+    0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
14084 pts/8    S+     0:00 tail -n 100 -f /var/log/homebridge.log
14086 pts/5    S+     0:00 grep --color=auto tail`

**Comment by normen** [comment]
Now again for sure..

Don't even have the page open.

```
ps aux | grep tail
root     13843  0.0  0.4   6724  3124 ?        Ss   03:37   0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
root     13848  0.0  0.0   3908   376 ?        S    03:37   0:00 tail -n 100 -f /var/log/homebridge.log
root     13853  0.0  0.4   6724  3056 ?        Ss   03:37   0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
root     13858  0.0  0.0   3908   408 ?        S    03:37   0:00 tail -n 100 -f /var/log/homebridge.log
root     13861  0.0  0.4   6724  3184 ?        Ss   03:37   0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
root     13866  0.0  0.0   3908   380 ?        S    03:37   0:00 tail -n 100 -f /var/log/homebridge.log
root     14069  0.0  0.4   6724  3128 ?        Ss   03:40   0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
root     14074  0.0  0.0   3908   368 ?        S    03:40   0:00 tail -n 100 -f /var/log/homebridge.log
root     14079  0.0  0.4   6724  3056 ?        Ss   03:40   0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
root     14084  0.0  0.0   3908   388 ?        S    03:40   0:00 tail -n 100 -f /var/log/homebridge.log
root     14472  0.1  0.4   6724  3108 ?        Ss   03:44   0:00 sudo -n tail -n 100 -f /var/log/homebridge.log
root     14477  0.0  0.0   3908   364 ?        S    03:44   0:00 tail -n 100 -f /var/log/homebridge.log
pi       14532  0.0  0.2   4768  2036 pts/5    S+   03:44   0:00 grep --color=auto tail
```

**Comment by normen** [comment]
Hm, why the heck is the sudo above run by root as well? That might be the hint? sudo-ception?

**Comment by oznu** [comment]
> Hm, why the heck is the sudo above run by root as well? It should be run by homebridge. That might be the hint? sudo-ception?

I think that's normal sudo behaviour. 

I'll see if I can add a little *hack* to forcibly kill the process after the log page is left.

**Comment by oznu** [comment]
Please update and try with 2.7.1

https://github.com/oznu/homebridge-config-ui-x/commit/260e7b824dc5c166d3e066dbabec1ae4db2cba6f

**Comment by normen** [comment]
Cool, thanks. Looks fine at the moment, I‘ll check again a few times over the day and report back.

**Comment by oznu** [comment]
Great, I'll close this for now, feel free to re-open if the issue surfaces again.

Thanks for reporting it.
