### ISSUE TITLE
Web Ui is not loading on Desktop

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [oznu/homebridge-config-ui-x#413]
Getting this Error when loading on my Mac.

<img width="1440" alt="Screen Shot 2019-11-07 at 6 58 23 PM" src="https://user-images.githubusercontent.com/9875439/68440422-9da55d00-0190-11ea-950f-43856a9d47de.png">
<img width="1439" alt="Screen Shot 2019-11-07 at 6 57 52 PM" src="https://user-images.githubusercontent.com/9875439/68440423-9da55d00-0190-11ea-9899-a228f66e1fca.png">
<img width="1437" alt="Screen Shot 2019-11-07 at 6 58 02 PM" src="https://user-images.githubusercontent.com/9875439/68440424-9e3df380-0190-11ea-892b-44ebb4fda3c7.png">

**Comment by oznu** [comment]
Try this: https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#websocketcompatibilitymode

**Comment by d0n4v4nb3ck3r** [comment]
That fixed it. Any other recommendations for config?
