### ISSUE TITLE
Help needed to get logging working on windows 10.

### ISSUE THREAD

**Issue by teymur1988** [oznu/homebridge-config-ui-x#414]
**Describe Your Problem:**
I've enabled logging in the config.json but don't see the logs in the UI. Homebridge is running under admin and has full rights to access the log file, however the log file is 0 KB.

**Logs:**
No errors in the logs when homebridge is run from cmd as "homebridge -D"

```
Show the Homebridge / Homebridge Config UI X logs here.
THose are the ones I'm after...

**Homebridge Config:**


Show your homebridge config.json here
{
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "file",
                "path": "C:\\Users\\teymu\\.homebridge\\homebridge.log"
            }
        },

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: 12.13.0
* **NPM Version**: 6.12.0
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**:4.6.3
* **Operating System**:  Windows
* **Process Supervisor**: ?


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by mafyata** [comment]
Try this:
 "path": "C:\Users\teymu\.homebridge\homebridge.log"

**Comment by teymur1988** [comment]
> Try this:
> "path": "C:\Users\teymu.homebridge\homebridge.log"

Hi,

Thanks, but "\" breaks the json syntax. Homebridge won't launch. I've tried "/", "//", "\\" - none of them work, the file is 0 KB. No errors in the logs...

**Comment by oznu** [comment]
The logs option just tells the UI where to find the logs - your Homebridge process manager needs take care of writing the logs.

**Comment by teymur1988** [comment]
> The logs option just tells the UI where to find the logs - your Homebridge process manager needs take care of writing the logs.

OK, now this makes things a bit more clear. THanks for that, Now I need to find out how to make that process manager to write the logs.

**Comment by oznu** [comment]
This might work for you: https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-on-Windows-10

**Comment by teymur1988** [comment]
> This might work for you: https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-on-Windows-10

It did indeed work! Thanks a lot for that!
