### ISSUE TITLE
All devices with generic names instead of real names in Home App (IOS 13)

### ISSUE THREAD

**Issue by TroisSix** [oznu/homebridge-config-ui-x#416]
Hi. 

I just discovered your homebridge and it is amazing that's so simple to install, configure and see in IOS, great job guys!

I use the plugins:
- homebridge-config-ui-x v4.6.3 
- homebridge-edomoticz v2.1.13
My iPhone is on IOS 13.

I can access to the UI, and see all my devices with the names/values. 
I can also move them in some rooms, great.

**Describe The Bug:**
But in the application Home (IOS): 
- I can see all my devices (switch, temperature) but without any name, 
- and I cannot see the rooms I previously configured in the UI.

**To Reproduce:**
I removed all my accessories in Home app (IOS)
In the application Home (IOS): I added the accessory with the qr code, and then I see all my devices with generic names (switches, temperature).
If I use the application MyTouchHome: I wasn't able to add the accessory of homebridge, it failed to add it. But once I added the accessory with the application Home, I could see the names! So only the application Home is not displaying the names.

**Expected behavior:**
To see all the names of my devices, and sorted in the rooms configured in the UI.

**Homebridge Config:**
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "...",
        "port": ...,
        "pin": "..."
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 9898,
            "auth": "form",
            "theme": "teal",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "USER:PASSWORD@127.0.0.1",
            "port": "8080",
            "ssl": false,
            "roomid": ROOM_ID,
            "excludedDevices": []
        }
    ]
}
```

**Environment:**
* **Node.js Version**: 10.15.2
* **NPM Version**: 2.15.12
* **Homebridge Version**: 0.4.5 (version in the UI)
* **Homebridge Config UI X Version**: 4.6.3
* **Operating System**: Raspbian buster (pi3)

Please help ;)

**Comment by mafyata** [comment]
Rooms in home app and config ui x are different.Names too. Changes on one app does not affect on other app.

**Comment by TroisSix** [comment]
Weird cause I used to deal with another version of homebridge, and I remember it was displaying the good names in Home app.
So what should I do to have the names in Home app?

**Comment by oznu** [comment]
> Changes on one app does not affect on other app.

This is correct. Room data and customised accessory names (usually) are stored in iCloud and are not sent back to the accessory (Homebridge) to use.

**Comment by TroisSix** [comment]
That is not a normal behaviour to have all the devices with the same generic name in Home app, and it's a bug...
To help the others who encounter the same issue, I found a way to avoid this bug: rename your device homebridge in the conf, and add the homebridge acessory in MyTouchHome (which recognize the devices with the good name), then in Home app, the devices appear with their unic name...
