### ISSUE TITLE
I have 2 config.json files!.... HELP!!

### ISSUE THREAD

**Issue by iDeeW** [oznu/homebridge-config-ui-x#425]
I am new to homebridge and this question is about the location of the config.json file.

After I successfully installed the homebridge server (on my old RPi 2), I created the config.json file at "/home/pi/.homebridge/config.json". Everything was working fine.
Then after installing "homebridge-config-ui-x" I noticed that UI-X is looking at another config.json file at "/var/homebridge/config.json".

How can I force the UI-X plugin to read config.json file at "/home/pi/.homebridge/" ?

Thanks

**Comment by oznu** [comment]
Hi @iDeeW,

What guide have you followed to setup Homebridge? The UI "discovers" the config path from the homebridge process, so unless you're running two instances of Homebridge then Homebridge is probably using `/var/homebridge/config.json` as well.

I would recommend taking a look at the Homebridge wiki and following these instructions to get a stable setup:

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Raspbian

**Comment by iDeeW** [comment]
I did not follow this guide. But the process was exactly the same.
The only difference I see is the path in the "/etc/default/homebridge" file.
My path is ,

> HOMEBRIDGE_OPTS=-U /var/homebridge -I

instead of the path in the guide, 
which is,
> HOMEBRIDGE_OPTS=-U /var/lib/homebridge -I

Thanks

**Comment by oznu** [comment]
How are you starting the homebridge service?

**Comment by iDeeW** [comment]
It is set to start automatically on boot ....and it does.
Everything works as expected, including  UI-X plugin and the mqtt plugin.

The only thing I'm experiencing is the config.json I see on the web browser (UI-X) is not what homebridge server is using.
(I probably have done something stupid during the installation! )

Just curious if there is any way that I can force the UI-X to see my real config file inside 
> "/home/pi/.homebridge" 

instead of looking at the one inside.

> "/var/homebridge".

Thanks

**Comment by oznu** [comment]
So how did you tell homebridge to start on boot?

**Comment by iDeeW** [comment]
this is what I followed to do that...

> https://timleland.com/setup-homebridge-to-start-on-bootup/

**Comment by oznu** [comment]
Hi @iDeeW,

Based on the guide you linked, the config should be located inside `/var/homebridge`. Homebridge Config UI X does not actually have an option to tell it where the `config.json` is located, when Homebridge loads, it tells the UI where it has loaded it's config from. For this reason I suspect the config file actually in use by the Homebridge service is `/var/homebridge/config.json` if that is the one being shown in the UI.

If it really isn't the one in use, I would start checking for multiple instances of Homebridge running on your system and remove them if necessary.
