### ISSUE TITLE
Node and NPM Version on Dash

### ISSUE THREAD

**Issue by mitch7391** [oznu/homebridge-config-ui-x#428]
I was wondering if we could add the Node and NPM version on the dash just like the Homebridge version is displayed? This would then also let us know if they are out of date. Thanks in advance, really loving this plugin so far.

**Comment by oznu** [comment]
The node version is currently displayed in the footer of the status page.

**Comment by mitch7391** [comment]
I did not notice that haha thanks! Glad to hear there are some new tweaks coming. When do you expect that to happen?

**Comment by oznu** [comment]
The new dashboard should be out early in the new year. I'll try and remember to update this issue when I get a test release out.

**Comment by mitch7391** [comment]
Thanks :) can’t wait!
