### ISSUE TITLE
instead of run restart command, it runs reboot?

### ISSUE THREAD

**Issue by elfive1992** [oznu/homebridge-config-ui-x#429]
**Describe The Bug:**
when I click restart homebridge in webui, the whole server shutdown and reboot...not execute the "restart" command.

**To Reproduce:**
Just click restart button in web UI. and the whole system will process a reboot.

**Expected behavior:**
just issue a restart command which in this case is: systemctl restart homebridge

**Logs:**

```
no logs....
```

**Homebridge Config:**

```json
{
    "mdns": {
        "interface": "192.168.x.82"
    },
    "bridge": {
        "name": "Homebridge_Rasp",
        "username": "1E:AB:21:8F:F1:xx",
        "port": 53873,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "HomeBridge-UI",
            "port": 28581,
            "auth": "form",
            "theme": "indigo",
            "restart": "systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "websocketCompatibilityMode": true,
            "log": {
                "method": "systemd"
            },
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },
        {
            "platform": "Rpi"
        },
        {
            "platform": "Camera-ffmpeg",
            "name": "Raspi Camera",
            "cameras": [
                {
                    "name": "Raspi Camera",
                    "videoProcessor": "/usr/bin/ffmpeg",
                    "videoConfig": {
                        "source": "-i /dev/video0 -f v4l2 -r 20 -s 960x540",
                        "stillImageSource": "-f v4l2 -s 1280x720 -i /dev/video0",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "debug": true
                    }
                }
            ]
        }
    ]
}
```

**Screenshots:**
no

**Environment:**

* **Node.js Version**: 12.13.1 and 12.14.0 both reproduced
* **NPM Version**: 6.13.4
* **Homebridge Version**: 0.4.50 running whit root user
* **Homebridge Config UI X Version**: 4.6.7
* **Operating System**: Raspbian(Linux RaspPi3BPlus 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux)
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
How are you triggering a restart?

You should be using the on/off icon button in the top bar will restart homebridge.

If you're using the drop down menu with the "restart server" and "shutdown server" options; these will restart/shutdown the host.

**Comment by elfive1992** [comment]
not restart server, it's restart homebridge.
my dropdown list only shows two items: 1) restart homebridge 2) shutdown server
my top bar icon shows a reboot/restart tip.

If you said: 
> If you're using the drop down menu with the "restart server" and "shutdown server" options; these will restart/shutdown the host.

was right, so that should be a translation mistake:
my top bar icon only says restart/reboot, I don't know if it reboot homebridge or reboot the server, so I never use it....

And I just confirmed it, you are right, and it should be a translation mistake or misunderstanding.

**Comment by elfive1992** [comment]
and can I  submit a PR to make the translation more specific?
