### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by theOrakle** [oznu/homebridge-config-ui-x#43]
I have tried to put this behind an apache2 proxy/vhonst, but have failed with everything I know how to try.  Is this possible?  Are the loopback calls based on the config or based on the URL?  Please tell me if I missed something obvious.  All works awesome if I go directly to port 8081, but when I proxy/vhost, the logs, status and other things stop working. 

Sample vhost I was using:
<VirtualHost 10.0.69.116:80>
        ServerName homebridge.wiesalani.com
        ServerAdmin die@oal.com
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ProxyPass / http://localhost:8081/ nocanon
        ProxyPassReverse / http://localhost:8081/
</VirtualHost>

Thanks and great job.

**Comment by oznu** [comment]
Hi @theOrakle,

You'll need to add support for WebSockets to your apache vhost config. I'm not how to do this on apache, but for nginx I posted the config here: https://github.com/oznu/homebridge-config-ui-x/issues/35#issuecomment-366680023 which you might be able to translate.

Otherwise doing a google search for "how to proxy websockets in apache" should help.

The web socket path is `/`.

**Comment by theOrakle** [comment]
Awesome - thank you.

Here is what I came up with that works for apache after some googling...

<VirtualHost 10.0.69.116:80>
        ServerName homebridge.wiesalani.com
        ServerAdmin die@aol.com
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Location />
                ProxyPass http://localhost:8081/
                ProxyPassReverse http://localhost:8081/
                RewriteEngine on
                RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
                RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
                RewriteRule .* ws://localhost:8081%{REQUEST_URI} [P]
        </Location>
</VirtualHost>
~

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Apache for latest template.
