### ISSUE TITLE
No responding accessoires when I am not on WiFi 

### ISSUE THREAD

**Issue by klaaspiet** [oznu/homebridge-config-ui-x#430]
hey

Homebridge is running good when I am at home on the WiFi. 
But when I leaving the WiFi my accessoires are not responding any more. 

I can’t find a solution.

**Comment by oznu** [comment]
Hi,

This is going to be a remote access / Home Hub issue rather than a problem with the Homebridge Config UI X project.

I'd recommended posting your issue one of the community support platforms:

https://github.com/nfarina/homebridge#community

**Comment by jannnfe** [comment]
Looking on this Issue, it seems like this is a config ui x issue?!

https://github.com/nfarina/homebridge/issues/2348#issuecomment-549272951

I have the Same issue

**Comment by oznu** [comment]
Reading that issue to the end, people still have the issue after removing it.

Config UI X runs as a seperate process to Homebridge.
