### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by redfirebrooks** [oznu/homebridge-config-ui-x#436]
Tried to use the plugin but it is not working.
I have already Domoticz running on port 8080 so I tried to use the port 8888 (or others) with no result.

Is it the right syntax ? It is not explained correctly...

"platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 0,
            "mqtt": 1,
            "excludedDevices": []
        }
    {
      "platform": "config",
      "name": "Config",
      "port": "8888",
      "sudo": false
    }
    ],

**Comment by mafyata** [comment]
Try port 8081

**Comment by oznu** [comment]
Hi @redfirebrooks,

Can you show the logs, full config, environment details and everything else the issue template requested?

Thanks.

**Comment by RCdiy** [comment]
There is a comma missing. The comma is not explained to us.

"mqtt": 1,
"excludedDevices": []
},  <------------------------ add that comma
{
"platform": "config",
