### ISSUE TITLE
View Logs in Browser

### ISSUE THREAD

**Issue by fhughes90** [oznu/homebridge-config-ui-x#437]
Hello, I have homebridge running as a service and everything is working fine. Only issue I have is viewing logs via the browser.

I can view my logs via terminal using "journalctl -f -u homebridge", but when I try to view via browser, the content being displayed seems to be overloading my CPU - as in the CPU load will keep increasing until I restart my service in fear of damaging the RPi. Any Idea why this happening? Almost like the CPU can not keep up with the amount of info being displayed.

I have tried multiple ways on configuring my config.json file based on guidlines. (see below)

**Logs:**
I don't have any error logs to provide as my service is running fine.

Below are my Configs:
- config.json
```
"platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "f",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
             }
```

```
"platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "f",
            "sudo": true,
            "log": {
                "method": "custom",
                "service": "homebridge",
                "command": "journalctl -f -u homebridge.service"
            }
```

- environment file
```
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/lib/homebridge -I

# If you uncomment the following line, homebridge will log more
# You can display this via systemd’s journalctl: journalctl -f -u homebridge
DEBUG=*
```
- homebridge service
```[Unit]
Description=Homebridge Service
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target
```

**Environment:**

* **Node.js Version**: 12.14.0
* **NPM Version**: 6.13.4
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.6.7
* **Operating System**: Raspbian buster
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
Hi @fhughes90,

Please disable debug mode (comment out the like) in your `/etc/default/homebridge` file or change the `*` to be more specific.

With debug mode set as you have it the stream of the logs being sent to the browser will be logged again, which results in a never ending loop.

**Comment by fhughes90** [comment]
Oh wow, I thought I had to leave DEBUG mode like that.

Thank you for your help!

**Comment by oznu** [comment]
No problem. I might be able to disable debug mode at run time if it's set to `*` just before the logs are displayed - no promises though.
