### ISSUE TITLE
Cannot install - installation freezes

### ISSUE THREAD

**Issue by paqpaqpaq** [oznu/homebridge-config-ui-x#439]
I **was** on npm 6.3, node 8.14
the plugin would not update higher than version 4.5, for the installation would freeze.

I update npm and node to 8.17
I had the same issue. 
Removing the plugin and reinstalling it failed.

so, drastic measures, upgrade to node 11:

> pi@raspberrypi:~ $ npm -v
> 6.7.0

> pi@raspberrypi:~ $ node -v
> v11.15.0

> pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-config-ui-x
> [..................] | loadRequestedDeps: sill install loadAllDepsIntoIdealTree

And here it freezes... as it did on all attempts before.

Any suggestions?

**Comment by softwarebouwer** [comment]
I seem to have the same issue on a Rapberry Pi Zero W with npm 6.13.4 and node 12.13.0

**Comment by paqpaqpaq** [comment]
I more or less ‘solved’ it I think...

`cd /usr/lib/node_modules

sudo uninstall homebridge-config-ui-x

cd

sudo npm install -g hombridge-config-ui-x
`
And now wait... can take up to 15 mins. 

`sudo reboot`

The latest version actually starts now according to the log, however, the homescreen shows “latest version, 0.4.50

**Comment by softwarebouwer** [comment]
Seems to be working for me now too, it didn't earlier in the afternoon.

**Comment by oznu** [comment]
Installation can take a while on a Pi Zero, the issue is further compounded if you have a slow SD card. Not much you can do but be patient.

>  the homescreen shows “latest version, 0.4.50

This is the homebridge version. The UI version is shown in the footer.
