### ISSUE TITLE
secure web

### ISSUE THREAD

**Issue by Itsmmai** [oznu/homebridge-config-ui-x#44]
Hi Oznu,

I would like to ask if it is possible to add a secure https connection to your config-ui-x. For now it's my only website without https and because I want to connect over the internet to this great applet I really would like to send my password over https.

Is it possible?

Kind regards,
Abel

**Comment by oznu** [comment]
Hi @Itsmmai,

Please see: https://github.com/oznu/homebridge-config-ui-x/issues/35
