### ISSUE TITLE
Option to specify shutdown for PM2 

### ISSUE THREAD

**Issue by npburns224** [oznu/homebridge-config-ui-x#442]
**Describe The Bug:**
Homebridge Config UI X not honoring custom shutdown command specified in the config.json file. Pressing the "Shutdown" button on the web interface runs the specified custom reboot command.

**To Reproduce:**
1. Insert `"linux": { "shutdown": "pm2 stop", "restart": "pm2 restart" }` into config.json.
2. Restart Homebridge instance.
3. Press "Shutdown" button on web interface.

**Expected behavior:**
pm2 stops Homebridge instance.

**Snippit from pm2 Log:**
`| Homebridge-MQTT | [Config] Shutting down linux server with command: "pm2 restart"`
`| Homebridge-MQTT | [Config] Got SIGINT, shutting down Homebridge...`
`| Homebridge-MQTT | [Config] Loaded config.json with 0 accessories and 3 platforms.`
[*Homebridge continues to run from this point*]

**Homebridge Config:**
```json
{
            "platform": "config",
            "name": "Config",
            "port": 8084,
            "auth": "form",
            "theme": "dark-mode",
            "linux": {
                "shutdown": "pm2 stop",
                "restart": "pm2 restart"
            },
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "sudo": false,
            "log": {
                "method": "custom",
                "command": "pm2 logs --out --lines 50"
            }
        }
```

**Environment:**

* **Node.js Version**: v13.5.0
* **NPM Version**: v6.13.4
* **Homebridge Version**: v0.4.50
* **Homebridge Config UI X Version**: v4.6.7
* **Operating System**: Raspbian
* **Process Supervisor**: pm2

**Comment by oznu** [comment]
Hi @npburns224,

I can confirm this is a bug. Thanks for reporting this. It will be fixed in the next release.

https://github.com/oznu/homebridge-config-ui-x/blob/4.6.7/src/modules/platform-tools/linux/linux.service.ts#L39

**Comment by oznu** [comment]
This bug is fixed in the `@test` release. Thanks again for raising this.

https://github.com/oznu/homebridge-config-ui-x/issues/443
