### ISSUE TITLE
Testers Wanted: New Dashboard, New Config Editor, and Service Installer

### ISSUE THREAD

**Issue by oznu** [oznu/homebridge-config-ui-x#443]
Hello,

I'm looking for some people willing to help test the next version of Homebridge Config UI X.

# How To Test

To install the test version of Homebridge Config UI X run this command in the terminal to install from npm using the `@test` tag:

```bash
# remove sudo for Docker and Windows 10 installs
sudo npm install -g  --unsafe-perm homebridge-config-ui-x@test
```

You can rollback to the stable version at any time by re-installing the `@latest` tag:

```bash
# remove sudo for Docker and Windows 10 installs
sudo npm install -g  --unsafe-perm homebridge-config-ui-x@latest
```

The source code for this test can be found under the [new-dashboard](https://github.com/oznu/homebridge-config-ui-x/tree/new-dashboard) branch on GitHub.

_While I am aiming for this to be a "no breaking changes" release, please take care to backup your setup if you think it's necessary._

# New Features

## New Dashboard

This release comes with a brand new status dashboard that features a fully customisable, widget-based design. Users can decide which widgets they wish to enable and position and resize them as they like.

<p align="center">
  <img width="600px" src="https://user-images.githubusercontent.com/3979615/71886653-b16d3f80-3190-11ea-9ff8-49dc4ae4fff0.png">
</p>

New widgets include:

* **Homebridge Status Widget** - Homebridge version and update check, current Homebridge service status and Homebridge plugins update check
* **CPU Widget** - shows the current cpu load (now much more accurate) and CPU temperature when available, plus a graph of the last 0-10 minutes cpu load
* **Memory Widget** - shows the total and available memory (previously "Free" memory as show which is not a reliable indicator of "Available" memory), plus a graph of the last 0-10 minutes free memory
* **Uptime Widget** - shows the server uptime and the process uptime
* **QR Code Widget** - shows the pairing QR Code and Homebridge PIN
* **Homebridge Logs Widget** - shows the Homebridge logs stream
* **Homebridge Terminal Widget** - an interactive terminal (only available when interactive web terminals are enabled)
* **System Information Widget** - shows details about your server and homebridge setup
* **Weather Widget** - shows the current weather for the set location (may add a forecast later)
* **Accessories Widget** - display and control the accessories you select

## Simple Service Installer

This release expands the `hb-service` command to support macOS and Linux in addition to Windows 10. This command allows you to setup a Homebridge instance in seconds.

Running `hb-service install` will setup Homebridge and Homebridge Config UI X to run as a service with auto-start on boot. The same command works across Linux, macOS and Windows 10.

<p align="center">
  <img width="600px" src="https://user-images.githubusercontent.com/3979615/71888439-4291e580-3194-11ea-8687-a3d58f94ba47.gif">
</p>

Notable Features:

* The UI will remain running even if there is an issue preventing Homebridge from starting
* Easily setup and manage multiple homebridge instances
* The ability to start, stop, restart and view the logs of your Homebridge instances using the `hb-service` commands
* [See the wiki for further details](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command)

## New Config Editor

The config editor (non-mobile) has had the Ace Editor replaced with the [Microsoft Monaco Editor](https://microsoft.github.io/monaco-editor/) (the code editor that powers VS Code).

This allow for much more powerful JSON syntax checking, more helpful error messages and the new ability to detect duplicate keys in object (like when a second platforms[] array is added by mistake!).

<p align="center">
  <img width="600px" src="https://user-images.githubusercontent.com/3979615/71890579-b635f180-3198-11ea-98ab-cc7b7263afd9.gif">
</p>

In addition:

* Help text is now shown when hovering over the core components of the config.json
* Autocomplete of the bridge, plugins, ports and mdns objects
* Detect when accessory config has been added to the platform array, or vice versa
* Warnings when the JSON does not match what is allowed by Homebridge

# Translations Required

Thank you to everyone who has helped translate Homebridge Config UI X into 16 different languages with a special mention to @the0neyouseek, @razer4908, @mientki, @Caribsky, @HonzaaD, @niinaranpo, @fafoulon, @KamistixX, @r951236958, @kgdudhqcigeg, @rrroyal, @gaojie429, @Rubenfer, @RaymondMouthaan, @cyberfafu, @mafyata, @fschaefer, @grzegorz914, @DewGew, @fmandal, and @elfive1992.

This release does add some new language strings that need translation and any help you or others in the community can provide to achieve this would be most appreciated.

The translation files that require updating are currently in the [new-dashboard](https://github.com/oznu/homebridge-config-ui-x/tree/new-dashboard) branch here:

https://github.com/oznu/homebridge-config-ui-x/tree/new-dashboard/ui/src/i18n

# Feedback and Issues

Thanks for testing! Feel free to post your feedback in the comments below. I'm also regularly available on the [Homebridge Slack](https://slackin-znyruquwmv.now.sh/) channel via @oznu and the [#ui](https://homebridgeteam.slack.com/messages/C9NH0CUTY) channels.

---

Tagged Issues:

* New Dashboard - https://github.com/oznu/homebridge-config-ui-x/issues/432
* NPM Version on Dashboard - https://github.com/oznu/homebridge-config-ui-x/issues/428
* Process uptime on dashboard - https://github.com/oznu/homebridge-config-ui-x/issues/411
* CPU temp on dashboard - https://github.com/oznu/homebridge-config-ui-x/issues/374
* Ability to hide QR code - https://github.com/oznu/homebridge-config-ui-x/issues/355
* Memory reporting - https://github.com/oznu/homebridge-config-ui-x/issues/329
* Uptime and memory reporting - https://github.com/oznu/homebridge-config-ui-x/issues/76

**Comment by mitch7391** [comment]
@oznu love the new dashboard, no issues so far :) two quick questions:

1. I see you have added the NodeJS and Npm versions like I requested (thanks!). Will they notify you on the dashboard if they are outdated or have an update available?

2. I notice the widgets have a settings cog on them but none of the widgets have any options. Is that something to come later?

Once again, thanks and love your work!

**Comment by sorriso93** [comment]
Hello beatiful!
On OSX 10.15.2 with safari I don't get the editor available. Clicking on the tab, the page changes but no editor is available...

**Comment by oznu** [comment]
Hi @mitch7391,

Thanks for testing and your feedback.

> I see you have added the NodeJS and Npm versions like I requested (thanks!). Will they notify you on the dashboard if they are outdated or have an update available?

It does now as of v4.7.0-test.30.

> I notice the widgets have a settings cog on them but none of the widgets have any options. Is that something to come later?

The box also contains the delete button to remove the widget from the dashboard. Some widgets do have settings, including the Weather widget and now the Logs and Terminal widgets, eg.

![image](https://user-images.githubusercontent.com/3979615/72057955-69caed00-3323-11ea-8379-dd1814217766.png)

**Comment by mitch7391** [comment]
This sounds really good @oznu :) what suffix do I add to the install command to test these recent changes?

**Comment by oznu** [comment]
Thanks @mitch7391. You can update to the latest test using the same command described in the original post above.

**Comment by mitch7391** [comment]
Awesome thanks!

**Comment by henkied** [comment]
Hi @oznu  i would like to test for you! I installed everything in the docker on synology nas. Can this also be tested?

**Comment by oznu** [comment]
Hi @henkied. To test on Docker you can run the same commands in my original post (this is the one time you **should** include the `-g` flag).

**Comment by henkied** [comment]
super, it works great. few questions:
- I see that my node and npm are outdated how can I update it?
<img width="274" alt="Schermafdruk 2020-01-10 15 09 48" src="https://user-images.githubusercontent.com/20031014/72158808-5c614180-33bb-11ea-86a6-7094e2470846.png">
<img width="281" alt="Schermafdruk 2020-01-10 15 09 39" src="https://user-images.githubusercontent.com/20031014/72158809-5c614180-33bb-11ea-976f-a8fac11e7892.png">
- How can I add the weather widget?

**Comment by oznu** [comment]
@henkied to update Node just pull the latest version of the Docker image; it's kept up to date.

I've already pushed the new version of the UI to the Docker builds (it's a know/stable environment).

**Comment by oznu** [comment]
4.7.0 has now been released. Anyone currently on the test version can update via the UI.

**Comment by rbhr** [comment]
Hey @oznu hope you are managing with the smoke over there.
Wish I had been on here to test for you but just want to say this is absolutely AWESOME!
Thanks for all your great efforts.

**Comment by mitch7391** [comment]
Hey @oznu just before I updated from the test version to the v4.7.0 I noticed this. I have only been a recent user, but I think I remember that when it told you there was a plugin for update it would replace the tick with an 'x'; is this a bug or something you moved away from or am I just remembering wrong? If it is a bug, it may have carried into the new version, so just letting you know just in case.

![image](https://user-images.githubusercontent.com/40288237/72199406-89bef580-3476-11ea-902b-d8feab928f8c.png)

**Comment by mafyata** [comment]
This is the old plugin update reminder. 

![5DC86F11-D893-41EB-AC28-931193B73BA3](https://user-images.githubusercontent.com/48009267/72201278-de547780-345a-11ea-8bd8-20162b1f5767.png)

**Comment by henkied** [comment]
> @henkied to update Node just pull the latest version of the Docker image; it's kept up to date.
> 
> I've already pushed the new version of the UI to the Docker builds (it's a know/stable environment).

HI @oznu do you mean these one? 
<img width="763" alt="Schermafdruk 2020-01-11 09 33 02" src="https://user-images.githubusercontent.com/20031014/72201539-8404e800-3455-11ea-91d3-295ee7b36d00.png">

**Comment by Olepir** [comment]
How to switch to hb-service?
Why I tried to enter sudo `hb-service install --user homebridge` I get `hb-service: command not found`

**Comment by oznu** [comment]
> HI @oznu do you mean these one?

Since you're using the SPK there is a little trick you can do to update. Go into DSM Package Centre (Not Docker) and stop the Homebridge app, the start it again. This get you the latest version of the image as the SPK checks for updates each time it starts.

**Comment by oznu** [comment]
@Olepir - make sure you've got the latest version installed globally; if you're still facing issues please hit my up on Slack and I'd be happy to try and work this out for you.

**Comment by Olepir** [comment]
> @Olepir - make sure you've got the latest version installed globally; if you're still facing issues please hit my up on Slack and I'd be happy to try and work this out for you.

Yes, latest version is installed globally. Sorry, I don’t have Slack.
Also I tried this command without sudo and I got this
```
[HB Supervisor] Installing Homebridge Service
[HB Supervisor] ERROR: This command must be executed using sudo on Linux
```

**Comment by henkied** [comment]
> > HI @oznu do you mean these one?
> 
> Since you're using the SPK there is a little trick you can do to update. Go into DSM Package Centre (Not Docker) and stop the Homebridge app, the start it again. This get you the latest version of the image as the SPK checks for updates each time it starts.
> 
> https://github.com/oznu/homebridge-syno-spk#updating-homebridge

Ehm I understand but I can't figure it out completely. I have installed several homebridge. I can only install one version of the spk according to me. Or do you have a tip?

**Comment by oznu** [comment]
@Olepir - it looks like the command is not available in the root users PATH. This is a bit strange, while you could use the `sudo -E` flag to preserve the PATH I haven't encountered this during my testing and not sure how your setup will react.

I do have some more ideas/questions, but don't want to spam this thread to much. Can you open another issue providing details of your setup + how you originally installed Node.js?

**Comment by oznu** [comment]
@henkied - looking through [your previous issues](https://github.com/oznu/docker-homebridge/issues/204) I found you might be using `docker-compose`? To update this, go to the path where your `docker-compose.yml` file is located and run these commands:

```
docker-compose pull
docker-compose up -d
```

Otherwise, if you've configured your additional containers manually using the Docker app in DSM, then updating is a bit of a pain - the easiest way to to remove the containers, download the new images, and recreate them, making sure to point the `/homebridge` volume mount to the same location (if you do this right you won't lose any config or your HomeKit pairings).

Of course, if Node.js 10 is still working for everything you need it to, you could just leave it. Node.js v10 still has support until April 2021.

**Comment by oznu** [comment]
@mitch7391 @mafyata - the plugin updates available icon is fixed in the next release (currently in `@test`). Thanks for reporting this.

**Comment by mitch7391** [comment]
No worries @oznu, thanks for the quick fix :)

**Comment by mitch7391** [comment]
Love that you snuck a clock widget in there too haha

**Comment by oznu** [comment]
I'm thinking about changing the Node.js / NPM version notice so it only shows the **circle warning icon** if the user is on an unsupported version.

That would be: 

* Node.js < v10
* NPM < v6

These versions would change as the LTS versions of Node.js stop being supported; or if plugins start using features exclusive to a later version.

The latest version will still be available by hovering over the version number - I'm just removing the icon so people don't feel the need to do an upgrade of Node.js on a fully working system running a supported version of Node.js.

**Comment by mitch7391** [comment]
That makes sense, I only suggested it in the first place as I like to keep everything fully updated at all times. Is there any downside to updating constantly to the latest versions of node.js and npm when they become available? Just sussing out if I should stop that practise (might just be my lack of knowledge and experience).

**Comment by oznu** [comment]
@mitch7391 If you're familiar with the update process, then there shouldn't be any issues staying up-to-date. At the same time, anything v10+ is perfectly fine for now as well.

**Comment by mitch7391** [comment]
No worries @oznu :) thanks for the info

**Comment by oznu** [comment]
4.8.0 is out - I'm closing this issue off now.

A big thank you to everyone who tested! 😄
