### ISSUE TITLE
New Dashboard Lock Mechanism 

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#448]
@oznu 

Thanks for the new nice Dashboard very good work, one things, can U add on the Toolbar top right Lock Icon to lock the dashboard edit mode, on iPad is difficulty to move the complete site up and down, every time moved the widgets and changes it’s positions and size.

**Comment by oznu** [comment]
Hi @grzegorz914,

Thanks for testing and providing feedback. I've added this feature, but it's hidden in the add widget modal (this might get renamed).

![image](https://user-images.githubusercontent.com/3979615/72057259-320f7580-3322-11ea-85a8-f96bb3bfab7f.png)

When the dashboard is locked the "Add Widget" button icon changes to a lock:

![image](https://user-images.githubusercontent.com/3979615/72057360-6420d780-3322-11ea-8948-29b460ef64e7.png)

There are a few more translation strings as a result of this.

Available now in `@test` v4.7.0-test.30.

**Comment by grzegorz914** [comment]
Very nice, thanks again.
