### ISSUE TITLE
System Information Widget

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#449]
@oznu 

Some text does not pass in the widget window, it will be nice to ad options to the widgets to wrap its text if.
![022A6541-8935-488D-BC79-834A0C7DBECC](https://user-images.githubusercontent.com/28867813/71974505-ef5e7800-3211-11ea-9bd9-06e6bedc8a4f.jpeg)

**Comment by oznu** [comment]
This one is a bit tricky and I originally spent a bit of time on this, and have done so again today.

The widget is scrollable (with scrollbars hidden for athletics), I'm not sure how well this works on a touch device such as an iPad though?

**Comment by grzegorz914** [comment]
OK, i can scroll the window left and right but, optimal will be if only the text will scroll itself if does not pass the window. (Scrolllabel)
If this is difficulty to make done I can live with this as it is, no worries.
