### ISSUE TITLE
change loglines to > 100

### ISSUE THREAD

**Issue by Itsmmai** [oznu/homebridge-config-ui-x#45]
Hi Oznu,

I'm really quit happy with your docker files and your config-ui-x modification. You really did great work and it is more stable then before (when I was running homebridge on a standalone debian installation)

I was wondering, can I somehow change the number of logfile lines.. now it is:
tail -n 100 -f /homebridge/logs/homebridge.log and it would be nice if I can change it to 200 or 300 instead of the current 100.

thanks in advance (again :-))

Abel

**Comment by normen** [comment]
You can use a custom log command for that https://github.com/oznu/homebridge-config-ui-x#configuration

**Comment by oznu** [comment]
I had noticed that 100 lines is not really enough to see what happened before homebridge restarted/crashed.

From > 3.0 the default is 200 lines. This commit was already in place before you raised the issue, it's just not published yet. 

As @normen said, you can also feed in a custom command and set the value to whatever works for you:

```json
{
  "platform": "config",
  "name": "Config",
  "port": 8080,
  "log": {
    "tail": "sudo -n tail -n 500 -f /var/log/homebridge.log"
  }
}
```
