### ISSUE TITLE
Logs Widget

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#450]
@oznu 
It will be nice to add option in this widget to change size of text in log.

**Comment by oznu** [comment]
Done in the latest `@test` v4.7.0-test.30.

![image](https://user-images.githubusercontent.com/3979615/72057541-aa763680-3322-11ea-84ba-32eef30001d2.png)

This only changes the Widget logs, not the main log screen.

**Comment by grzegorz914** [comment]
Thanks woking OK.
