### ISSUE TITLE
Config Editor

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#451]
@oznu 
1- Please move the marked buttons and description to the Top Toolbar, this make more space to working in this editor.
2- Only if position 1 not done.
Please lock the Top Toolbar on the editor screen if possible, on iPad devices if we moved up and down the  complete Red marked area moved up and down.
![9A0B644F-E717-4C51-9679-E597543CD669](https://user-images.githubusercontent.com/28867813/71981265-52f0a180-3222-11ea-9b4f-34258d2df7f5.jpeg)

**Comment by grzegorz914** [comment]
Some video how config editor working on iPad.

https://vimeo.com/383850999

**Comment by oznu** [comment]
Which iPad model is this?

**Comment by grzegorz914** [comment]
11” Pro

**Comment by oznu** [comment]
Thanks, I'll see if I can source one to test with.

**Comment by oznu** [comment]
Hi @gaojie429, please give the latest `@test` a go, I've fixed a number of issues with the editor while using both the on-screen keyboard as well as the folio keyboard.

**Comment by grzegorz914** [comment]
Now is OK, thanks.
