### ISSUE TITLE
Accessory state not updated after restart

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#453]
@oznu 

After restart Homebridge Config UI X (all Versions) dummy accessory are not updated but if U go to logs and again to accessory then updated all.

Look on rollershutter and thermostats.

Here the video:
https://vimeo.com/383703844

**Comment by oznu** [comment]
While the states of the accessories are not being shown, can you use the UI to control an accessory and let me know if this triggered all the other accessories to correctly reflect their states?

**Comment by grzegorz914** [comment]
Yes I can control all accessory normal, the correct state is show after going to logs window and again to accessory or if the accessory change its state itself. This happened only on dummy rollershutter or thermostat. T think restart Config UI X clear the state and not refresh again.

**Comment by oznu** [comment]
Try the latest `@test` v4.7.0-test.31. I've done a small change that I think might fix this.

**Comment by grzegorz914** [comment]
Thanks, now working as excepted.
