### ISSUE TITLE
Status Page blank After update

### ISSUE THREAD

**Issue by Luftloch80** [oznu/homebridge-config-ui-x#458]
after Update to latest widget version the status page does not show any information anymore->

**Comment by TimofeyK** [comment]
Click the cogwheel in the lower right corner and enable widgets you need

**Comment by Luftloch80** [comment]
![IMG_0799](https://user-images.githubusercontent.com/20800008/72201344-37201200-3453-11ea-9519-62ae999a8049.png)
This Is what i get

**Comment by Luftloch80** [comment]
Okay only Works in landscape

**Comment by oznu** [comment]
Which iPad model?

**Comment by Luftloch80** [comment]
Did another restart Now it is working. 
Thx
