### ISSUE TITLE
Clock Widget

### ISSUE THREAD

**Issue by Luftloch80** [oznu/homebridge-config-ui-x#459]
great job 
Would be nice to have a clock widget for wall mounted iPad

**Comment by oznu** [comment]
Sounds like a good idea. I've already got an Angular clock component I can reuse too.

**Comment by oznu** [comment]
This has been added in the next release (currently in `@test`).

**Comment by Luftloch80** [comment]
Looks Great. Thank you. 
Would Great if Font size would be custom die clock an Weather Widget. 
Is ist also possible to Add the HomeKit Secenes or is it restricted By Apple?
