### ISSUE TITLE
Change Font size in Weather/Clock widgets

### ISSUE THREAD

**Issue by Luftloch80** [oznu/homebridge-config-ui-x#463]
Thx for clock Widget. 
Would be Great to change Font size of Clock and weather widget. 
Is it possible to add created HomeKit scenes as well?

**Comment by oznu** [comment]
I can't do HomeKit scenes are they are locked away in your Apple iCloud account. I'll look into the font size.

**Comment by mitch7391** [comment]
Not urgent at all, but when you get a chance could we be able to get the option to change the date format from MM/DD/YYYY to DD/MM/YYYY? Like I said, not urgent at all :)

**Comment by oznu** [comment]
It should be taking the date format from your browsers `.toLocalDateString()` function which here in Australia returns the date in the correct (and logical) DD/MM/YYYY format.

I can add an option to change it though and I'll set the default to DD/MM/YYYY.

**Comment by mitch7391** [comment]
Maybe something changed on my last browser update, explains why suddenly it was trying to spell check ‘colour’ to ‘color’ recently :) I will look at how to change it there.

**Comment by oznu** [comment]
Many date format options now available:

![image](https://user-images.githubusercontent.com/3979615/72323301-7e7cfb80-36fc-11ea-8db1-d2f25bafb658.png)

**Comment by Caribsky** [comment]
Hi, @oznu 
Could you please add the date formats: 

**DD.MM.YYYY** 
**14 January 2020**
**Thuesday, 14 January 2020**

It's most used in our country. 
By the way… i saw localisation of dates in javascript code. Will be good to use it.

**Comment by oznu** [comment]
@Caribsky - added the new date formats, in `@test` now. The date localisation is in another open issue.
