### ISSUE TITLE
Warning saveError ENOENT: no such file or directory, open '/usr/lib/package.json'

### ISSUE THREAD

**Issue by dcaccount** [oznu/homebridge-config-ui-x#464]
Hello,
I have updated to the latest version and I got following warnings:

> npm WARN saveError ENOENT: no such file or directory, open '/usr/lib/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/lib/package.json'
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN lib No description
npm WARN lib No repository field.
npm WARN lib No README data
npm WARN lib No license field.

**Environment:**

* **Node.js Version**: 11.15.00
* **NPM Version**: 6.13.4
* **Homebridge Version**: latest
* **Homebridge Config UI X Version**: latest
* **Operating System**: Raspbian

Can you please advise what shall I do to correct this issue?
Thanks!
Dan

**Comment by oznu** [comment]
These are just warnings, not errors, is anything broken?

**Comment by dcaccount** [comment]
> These are just warnings, not errors, is anything broken?

All is working but I would like to understand the reason for:
They have never happened and maybe sooner or later they might lead to something broken.

Can you please help to identify their reason?

Thanks and congratulations for your great plugin!

**Comment by oznu** [comment]
It's just warning you that the package.json does not exist for where the plugin is getting installed. This is normal for a global install directory like `/usr/lib`.

The description, readme repository fields missing warnings are just part of this.

Nothing to worry about.

**Comment by dcaccount** [comment]
Thanks!
