### ISSUE TITLE
Fonts in Logs unreadable

### ISSUE THREAD

**Issue by charona** [oznu/homebridge-config-ui-x#465]
Fantastic software to find after having setup homebridge manually for a couple of years. Works like a dream, except the log window shows either black on black, or probably nothing at all. Using Brave browser on Mac. Looks OK in Safari, Firefox, Chrome, so it may only be a problem in Brave, but I still wanted to report it.

![SUP kayak screenshot 2020-01-12 at 09 43 10](https://user-images.githubusercontent.com/44541652/72216490-d4e21280-3521-11ea-8dd1-8c715ab02175.jpg)

**Comment by oznu** [comment]
Hi @charona,

I think it's brave browser blocking something that is stopping this from working. You need to change the site settings to allow device recognition. 

<img width="420" alt="Screen Shot 2020-01-12 at 9 00 47 pm" src="https://user-images.githubusercontent.com/3979615/72217152-d1c93f80-357e-11ea-8887-c0902fa72a71.png">

**Comment by charona** [comment]
Brilliant, I took down the shield for that local site - did the trick. Thanks oznu! Amazing piece of software.

**Comment by oznu** [comment]
Thanks @charona!
