### ISSUE TITLE
/etc/network/interfaces: No such file or directory

### ISSUE THREAD

**Issue by RaymondMouthaan** [oznu/homebridge-config-ui-x#466]
Hi Oznu,

Thanks for the new homebridge gui, looks great! 

Just upgraded and faced the message below. Not very urged, but thought worth reporting it.

Greetz,
Ray

**Describe The Bug:**
HB Gui version 4.7.0 gives: 

```
cat: /etc/network/interfaces: No such file or directory 
```

**To Reproduce:**
Reboot Docker container

**Expected behavior:**
Not this cat message :)

**Logs:**

```
[1/12/2020, 11:10:09 AM] Homebridge is running on port 10006.
[1/12/2020, 11:10:09 AM] [Temperature 2] Received MQTT: tele/wemos-12/LWT = Online
[1/12/2020, 11:10:09 AM] [Humidity 1] Received MQTT: tele/wemos-13/LWT = Online
[1/12/2020, 11:10:09 AM] [Humidity 2] Received MQTT: tele/wemos-12/LWT = Online
[1/12/2020, 11:10:09 AM] [Temperature 1] Received MQTT: tele/wemos-13/LWT = Online
cat: /etc/network/interfaces: No such file or directory
```

**Environment:**

* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: 4.7.0
* **Operating System**: Ubuntu / Docker
* **Docker Engine:** 19.03.5

**Comment by oznu** [comment]
I've created a pull request for the library that is generating this message.

**Comment by oznu** [comment]
The author of the [systeminformation](https://github.com/sebhildebrandt/systeminformation) has just published a fix for this.

The updated library will be included in the next release (currently in @test).

**Comment by RaymondMouthaan** [comment]
Great! Thanks for the quick response and fix! 🥇

**Comment by Itsmmai** [comment]
I'm a little bit confused. It is a bug so no solution jet or is it solved as what I think to read in your response?

**Comment by oznu** [comment]
This is fixed in the next release. See https://github.com/oznu/homebridge-config-ui-x/issues/466#issuecomment-573405085.
