### ISSUE TITLE
Memory Widget

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#468]
@oznu 

Please look at the screenshot red marked area, the free memory are total different, total memory seems be OK.

<img width="1683" alt="Zrzut ekranu 2020-01-12 o 12 41 45" src="https://user-images.githubusercontent.com/28867813/72218272-98221580-3539-11ea-9149-9f9cb39aec96.png">

**Comment by oznu** [comment]
So "free" memory is misleading in Linux as the OS will use as much memory as it it can for cache.

If you enter the command `free -m`, depending on the Linux distribution you are using, you should see an "Available" column, which is a more accurate measure of memory utilisation.

The UI now uses the "Available" memory for its reporting.

See https://askubuntu.com/questions/867068/what-is-available-memory-while-using-free-command/867073#867073 for more info.

**Comment by oznu** [comment]
![image](https://user-images.githubusercontent.com/3979615/72218924-8752bd80-3594-11ea-9112-ba121aa15cf8.png)

**Comment by grzegorz914** [comment]
OK,
its available not free, need to change translations.

**Comment by grzegorz914** [comment]
Actual available memory not exist in translations:

```
 "status.memory.label_free": "Wolna",
    "status.memory.label_total": "Całkowita",
    "status.memory.label_used": "Użyta",
    "status.memory.title_memory": "Pamięć",
```

**Comment by oznu** [comment]
We can update the free label; it's not used anywhere else.

**Comment by oznu** [comment]
I've renamed `status.memory.label_free` to `status.memory.label_available` and updated the English translation.
