### ISSUE TITLE
GUI is not accessible if debug flag is set to true

### ISSUE THREAD

**Issue by Staubgeborener** [oznu/homebridge-config-ui-x#469]
In the main window of homebridge-config-ui-x I went to settings at the top right and set debug (it was  called something like that) as enabled under `Advanced`. Since then homebridge-config-ui-x is no longer accessible in the browser ("no connection possible"). When I use `systemctl status homebridge`, I see that the service is running:

```
user@server:~$ ● homebridge.service - Homebridge
   Active: active (running) since Sun 2020-01-12 16:12:32 CET; 11min ago
 Main PID: 11796 (homebridge)
    Tasks: 22 (limit: 4915)
   CGroup: /system.slice/homebridge.service
           ├─11796 homebridge
           └─11816 homebridge-config-ui-x
```

homebridge itself is still working in the background, but not homebridge-config-ui-x.

I changed the flag in my config respectively i deleted the line `"debug": true`. So homebridge-config-ui-x is now working, but where is the problem with `debug` `true`?

Running:
Node.js Version: v12.14.1
homebridge-config-ui-x: v4.7.0
Ubuntu: 18.04.3 LTS

**Comment by oznu** [comment]
Thanks @Staubgeborener,

I was able to replicate this. It will be fixed in the next release (currently in `@test`).
