### ISSUE TITLE
UI Supported Accessory Types

### ISSUE THREAD

**Issue by oznu** [oznu/homebridge-config-ui-x#47]
This issue tracks the types of accessories supported by the Homebridge Config UI X accessory control feature which allows you to view and control your Homebridge accessories in a web browser.

**Accessory Types not listed here can still be controlled using your iOS apps.**

### Currently Supported Accessory Types:

These accessory types can be fully controlled via the Homebridge Config UI X interface:

- [x] Switch
- [x] Outlet
- [x] Motion Detector
- [x] Occupancy Sensor
- [x] Contact Sensor
- [x] Temperature Sensor
- [x] Humidity Sensor
- [x] Air Quality Sensor
- [x] Leak Sensor
- [x] Garage Door Opener
- [x] Lock Mechanism
- [x] Speaker
- [x] Security System
- [x] Battery Service
- [x] Valve
- [x] Irrigation System
- [x] Light Sensor

### Partially Supported Accessory Types:

These accessory types can controlled via the Homebridge Config UI X interface, but some controls are still not fully implemented:

- [ ] Light Bulb
  - [x] On / Off
  - [x] Brightness
  - [ ] Hue
  - [ ] Saturation
- [ ] Fan
  - [x] On / Off
  - [x] Rotation Speed
  - [ ] Rotation Direction
- [ ] Fan v2
  - [x] On / Off
  - [x] Rotation Speed
  - [ ] Rotation Direction
  - [ ] Swing Mode
- [ ] Air Purifiers
  - [x] On / Off
  - [x] Rotation Speed
  - [ ] Rotation Direction
  - [ ] Swing Mode
- [ ] Thermostat
  - [x] Set Mode - Off / Cool / Heat / Auto
  - [x] Current Heating / Cooling State 
  - [x] Set Target Temperature
  - [x] Current Temperature
  - [ ] Set Target Relative Humidity
  - [ ] Current Relative Humidity
  - [ ] Set Cooling Threshold Temperature
  - [ ] Set Heating Threshold Temperature
- [ ] Heater Cooler
  - [x] Set Mode - Off / Cool / Heat / Auto
  - [x] Current Heating / Cooling State 
  - [x] Current Temperature
  - [x] Set Cooling Threshold Temperature
  - [x] Set Heating Threshold Temperature
  - [ ] Set Fan Speed
  - [ ] Toggle Oscillate
- [ ] Window Covering
  - [x] Opening / Closing / Stopped
  - [x] Position
  - [ ] Tilt Angle
  - [ ] Obstruction Detected
- [ ] Television
  - [x] On / Off
  - [x] Show Current Input
  - [ ] Select Input
  - [ ] Remote Control
  - [x] Volume Control
  - [x] Mute

###  Accessory Types Not Yet Implemented:

If it's not listed above, it's not currently supported.

### Adding New Accessory Types

Each accessory type is implemented using an Angular Component. If you know Angular + TypeScript then pull requests for new accessory types are more than welcome.

https://github.com/oznu/homebridge-config-ui-x/tree/master/ui/src/app/modules/accessories/types

**Comment by henkied** [comment]
hello again, is the add room button not working, when i click on it and put a new room nothing happend

**Comment by oznu** [comment]
@henkied, it's working on all the browsers I test with. 

https://github.com/oznu/homebridge-config-ui-x#supported-browsers

The rooms are only for displaying accessories in the Homebridge Config UI X interface, adding a room here will have no effect on iOS. If a room is empty when the page is left or reloaded it will be deleted. 

You should be able to drag an accessory into the new room once it's created, do you not get this option at all? 

![image](https://user-images.githubusercontent.com/3979615/37248273-acbc73fc-2521-11e8-8448-f7c3220ff861.png)

**Comment by henkied** [comment]
With Safari 11.03 not possible, chrome and firefox great!!

I have made a rooom "test" with chrome! How can ik change this name    :)

**Comment by oznu** [comment]
Hmm you're right 😕 . I'll see if I can fix Safari.

Just create a new room and empty out the "test" room. It will be removed when you refresh the page if it's empty.

**Comment by henkied** [comment]
Thx @oznu

**Comment by oznu** [comment]
@henkied - That issue with safari is fixed in 3.1.2.

**Comment by Itsmmai** [comment]
He Onze, it is really great.. I'm quit happy with this because this is (as far as I know) no other way to do this without an IOS device. Is there a way to rename devices ? Now it is hard to find out what is what ?

**Comment by iShift** [comment]
+ can you support camera?

**Comment by Kepete** [comment]
Awesome project! I was thinking all the time that it should be possible to control device with non IOS device when running homebridge. I think this is the first plugin doing it. 
Some key features like blinds and camera support are missing but I don't think I will manage adding them.

This plugi can help me creating a dashboard on wall without an iPad!

**Comment by oznu** [comment]
@Itsmmai - I'd like to add that ability, it will probably come at the same time as a generic status page for each service type. Think the "Details" page in the Home app that shows all that extra info about a service.

@iShift - Maybe. I have ordered an IP camera which will allow me to try this out. Stay tuned.

@Kepete - I'll see what I can do about blinds, or as HomeKit calls them, "Window Coverings".

**Comment by maciboy** [comment]
@oznu 
First of all, thank you so much for this plugin!
For sooo long I was angry about Apple not giving access to HomeKit from my Mac, even when using Siri…
Now, I can circumvent this :)

Above you stated, that it is possible to change the brightness of bulbs.
Could you please explain how to change the percentage?
For now the percentage is taken from what I set it to in iOS Home.app.
I can only turn on and off, using the predefined percentage…

Thanks!

**Comment by oznu** [comment]
@maciboy - long-clicking / long-pressing (on mobile) will bring up the additional properties box where you can adjust the brightness.

**Comment by maciboy** [comment]
Ah, shame on me 😄

**Comment by mientki** [comment]
which parameter in the accessory configuration is responsible for displaying the window with the brightness after slider? I want to set it to not appear in ordinary light bulbs.
http://prntscr.com/k6fwrj

**Comment by oznu** [comment]
@mientki, only light bulbs that expose the optional brightness characteristic will show the slider.

**Comment by mientki** [comment]
I'm talking about the on / off slider. It is not needed for ordinary incandescent bulbs without brightness adjustment. A popup window is also unnecessary. Can a popup window be hidden by a parameter?

**Comment by mientki** [comment]
@onzu, I have sent a file with a Polish translation for you to the e-mail.

**Comment by oznu** [comment]
@mientki; from 3.8.7 the light bulb popup will no longer display at all if the bulb does have a  brightness option.

I've received your polish translation, thank you.

**Comment by thesquaremedia** [comment]
@oznu I was thinking for cameras that already have a web app an I frame that will load the url May be a quick solution. At least for the camera view accessory some could be control through it.

**Comment by splunkme** [comment]
@oznu Hello, I was wondering if there is support for gpio-relay to be controlled through this interface? If not is it on the roadmap or could you point me in the right direction to work on this integration? Thanks!

**Comment by linuscool2** [comment]
Hi,
Will contact sensors be supported in the future?

**Comment by mientki** [comment]
would be nice...

**Comment by chrisremie** [comment]
This is great!
If window coverings will be included, it will be fantastic!

**Comment by megane999** [comment]
What about blynk accessories?

**Comment by RaiSoN-DE** [comment]
Can you please add sprinklers?

**Comment by thehauntedmattress** [comment]
@oznu Can you add support for the iOS 12.2 TV on/off switches and inputs?  This would be for plugins such as [homebridge-samsung-tizen](https://www.npmjs.com/package/homebridge-samsung-tizen) and [homebridge-webos-tv](https://github.com/merdok/homebridge-webos-tv#readme).

**Comment by oznu** [comment]
Window Covering support is coming in the next release.

Short Press (fully open / close):

![window-1](https://user-images.githubusercontent.com/3979615/59323555-6edca500-8d1e-11e9-9fcf-19bbf39d75f6.gif)

Long Press:

![window-2](https://user-images.githubusercontent.com/3979615/59323558-7308c280-8d1e-11e9-85f8-23a2fff7ee66.gif)

**Comment by mientki** [comment]
Very nice :)

**Comment by mafyata** [comment]
Hi, I updated the plugin now , but I can’t see my Samsung Tv in accessories tab.
![D40FE830-7BF2-43AC-9861-69979A366400](https://user-images.githubusercontent.com/48009267/59365496-4e721200-8d41-11e9-8e29-866832419682.png)
![AFEC2C26-5619-4346-BCE7-8F77FC891A52](https://user-images.githubusercontent.com/48009267/59365499-4f0aa880-8d41-11e9-9dcb-4e43d097a781.png)

**Comment by ebaauw** [comment]
Is the TV exposed through the homebirdge bridge, or did you pair it to HomeKit separately?

**Comment by oznu** [comment]
The Samsung TV plugin exposes the accessory separately to the test of the bridge accessories (like cameras). The current endpoints only work with accessories on the main bridge.

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#6-adding-the-tv-to-home-app

The LG TV plugin will work.

**Comment by oznu** [comment]
In the upcoming release of 4.6.0 the plugin will support accessory control of multiple homebridge instances, this should also discover the Samsung TV plugin and similarly exposed accessories.

* **Accessory Control:** Multi-instance support. You can now control accessories from multiple Homebridge instances.
  * All instances you want to control must have the same PIN, be on the same network, and running in insecure mode
  * You can blacklist instances you don't want to control using the plugin settings
  * Due to the changes required to identify accessories across multiple instances your room layout will be reset after upgrading
* **Accessory Control:** Accessory characteristics (on, off, brightness etc) now update immediately when changed in HomeKit (previously there was up to a 3 second delay)

I'm looking for a few people to test this out and confirm everything works as it should. You can install the current beta by running this command:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@next
```

Users of the beta will be able to upgrade to the official release of 4.6.0 from the UI once it's made available.

To roll back:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by grzegorz914** [comment]
Thanks for Your good work, I tested **Accessory Control** behavior and all working OK. 
In other thing one questions, Have You in plan add support for other accessory like:



**Binary Sensors:**
**Leak Sensor** - Homebridge configuration type: **leak**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "leak",
    "item": "Itemname-within-OpenHAB",
    "inverted": "true",
    "batteryItem": "Itemname-within-OpenHAB",
    "batteryItemInverted": "false"
}
```
**Carbon Monoxide Sensor** - Homebridge configuration type: **co**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "co",
    "item": "Itemname-within-OpenHAB",
    "inverted": "true",
    "levelItem": "Itemname-within-OpenHAB",
    "batteryItem": "Itemname-within-OpenHAB",
    "batteryItemInverted": "false"
}
```
**Carbon Dioxide Sensor** - Homebridge configuration type: **co2**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "co2",
    "item": "Itemname-within-OpenHAB",
    "inverted": "true",
    "levelItem": "Itemname-within-OpenHAB",
    "batteryItem": "Itemname-within-OpenHAB",
    "batteryItemInverted": "false"
}
```
**Smoke Sensor** - Homebridge configuration type: **smoke**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "smoke",
    "item": "Itemname-within-OpenHAB",
    "inverted": "true",
    "batteryItem": "Itemname-within-OpenHAB",
    "batteryItemInverted": "false",
}
```
**Filter Maintenance Sensor** - Homebridge configuration type: **filter**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "filter",
    "item": "Itemname-within-OpenHAB",
    "inverted": "true",
    "levelItem": "Itemname-within-OpenHAB"
}
```

**Position Based Actors:**
**Door** - Homebridge configuration type: **door**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "door", 
    "item": "Itemname-within-OpenHAB",
    "inverted": "false",
    "multiplier": "1",
    "stateItem": "Itemname-within-OpenHAB",
    "stateItemInverted": "false",
    "stateItemMultiplier": "1",
    "manuMode": "false"
}
```
**Window** - Homebridge configuration type: **window**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "window", 
    "item": "Itemname-within-OpenHAB",
    "inverted": "false",
    "multiplier": "1",
    "stateItem": "Itemname-within-OpenHAB",
    "stateItemInverted": "false",
    "stateItemMultiplier": "1",
    "manuMode": "false"
}
```
**Lock Mechanism** - Homebridge configuration type: **lock**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "lock", 
    "item": "Itemname-within-OpenHAB",
    "inverted": "false",
    "stateItem": "Itemname-within-OpenHAB",
    "stateItemInverted": "false"
}
```

**Complex Accessories:**
**Fan** - Homebridge configuration type: **fan**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "fan",
    "item": "Itemname-within-OpenHAB",
}
```
**Security System** - Homebridge configuration type: **security**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "security"
    "homeItem": "Itemname-within-OpenHAB",
    "homeItemInverted": "false",
    "awayItem": "Itemname-within-OpenHAB",
    "awayItemInverted": "false",
    "sleepItem": "Itemname-within-OpenHAB",
    "sleepItemInverted": "false",
    "alarmItem": "Itemname-within-OpenHAB",
    "alarmItemInverted": "false"
}
```

Thanks

**Comment by grzegorz914** [comment]
@oznu 
any plan add support for FFmpeg cam plugin?

**Comment by tooh** [comment]
I have a Withings scale connected and get results. The device API reports Air quality OK and the Battery Service as Unsupported. Can I do something to improve this ?

**Comment by oznu** [comment]
Added security systems. Currently in `@test`.

![image](https://user-images.githubusercontent.com/3979615/75872514-686cfb00-5e62-11ea-84af-bac80a672424.png)

**Comment by oznu** [comment]
Added leak sensors.

![image](https://user-images.githubusercontent.com/3979615/75970208-20161180-5f24-11ea-8c3e-45dc2e539708.png)

Plus new icons for exiting sensor types:

![image](https://user-images.githubusercontent.com/3979615/75970445-72efc900-5f24-11ea-8d05-a268bbbb041b.png)

**Comment by NoniKoli** [comment]
Hi could you add support for Valves ? I can control them from the home app however they don’t work in the web UI. Thanks
I love this Plugin it would be perfect if it has Valve Support.

**Comment by oznu** [comment]
Added valves and irrigation systems.

Generic Valve:

![image](https://user-images.githubusercontent.com/3979615/79462476-dea47600-803a-11ea-918f-db8659bf5252.png)

Irrigation System / Irrigation Valve:

![image](https://user-images.githubusercontent.com/3979615/79463036-a94c5800-803b-11ea-99ee-7c8a0636d8e6.png)

Setting the default duration is also supported for accessories that implement it.

**Comment by oznu** [comment]
Light sensors added @NicoFR75: https://github.com/oznu/homebridge-config-ui-x/pull/623

**Comment by oznu** [comment]
Added support for Fan v2.

**Comment by oznu** [comment]
Added support for Air Purifiers

**Comment by mitch7391** [comment]
Hey @oznu I have noticed an issue with the irrigation system accessory. In config-ui-x it always shows as ‘running’, whereas in HomeKit it shows as ‘scheduled’ and appears off (which is correct).

![510B64FD-5341-49A2-B064-3FDC76D0F88A](https://user-images.githubusercontent.com/40288237/81484804-2b1a5480-927b-11ea-8492-dec9292d5ff9.png)
![98AFCC56-F7C0-4B56-BA41-9162B55B7FE5](https://user-images.githubusercontent.com/40288237/81484805-30779f00-927b-11ea-857a-3b4b746585d9.jpeg)

**Comment by grzegorz914** [comment]
@oznu 
Any plan to add door, is not listed on Your list:
**Door** - Homebridge configuration type: **door**
```
{
    "name": "An items name, as shown in Homekit later",
    "type": "door", 
    "item": "Itemname",
    "inverted": "false",
    "multiplier": "1",
    "stateItem": "Itemname",
    "stateItemInverted": "false",
    "stateItemMultiplier": "1",
    "manuMode": "false"
}
```

**Comment by oznu** [comment]
Added [Heater Cooler](https://developers.homebridge.io/#/service/HeaterCooler).

![image](https://user-images.githubusercontent.com/3979615/84145092-9fbff900-aa9c-11ea-98ed-e9e1cb6a81a2.png)
![image](https://user-images.githubusercontent.com/3979615/84145144-b403f600-aa9c-11ea-9279-997238038197.png)

**Comment by alfag4** [comment]
Hello, for Window Covering should be great to have the "pause" option to stop opening or closing.
Thanks

**Comment by RCdiy** [comment]
Could accessories be auto organized? Instead of all of them going to the default room could they go to rooms based on the plugin, type (fan, switch, weather).

**Comment by mitch7391** [comment]
> Hey @oznu I have noticed an issue with the irrigation system accessory. In config-ui-x it always shows as ‘running’, whereas in HomeKit it shows as ‘scheduled’ and appears off (which is correct).
> 
> ![510B64FD-5341-49A2-B064-3FDC76D0F88A](https://user-images.githubusercontent.com/40288237/81484804-2b1a5480-927b-11ea-8492-dec9292d5ff9.png)
> ![98AFCC56-F7C0-4B56-BA41-9162B55B7FE5](https://user-images.githubusercontent.com/40288237/81484805-30779f00-927b-11ea-857a-3b4b746585d9.jpeg)

Hey @oznu, just wanted to bring this one up again :)

**Comment by Feilner** [comment]
Created pull request for Window and Door #945

**Comment by mitch7391** [comment]
@oznu I was just wondering with this one being closed out if you have finished with the accessory support? The one I had brought up for irrigation two comments ago still has an issue with saying it is ‘running’ when it should state it is ‘scheduled’.
