### ISSUE TITLE
Don’t see Temperatur anymore since update to 4.7

### ISSUE THREAD

**Issue by testpaul999** [oznu/homebridge-config-ui-x#470]
**Describe The Bug:**

Don’t see Temperatur anymore since update to 4.7

**To Reproduce:**

Every time 

**Expected behavior:**

Use intel nuc with Ubuntu’s 19.10
Until the old version this string displays the temperature 

temp": "/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input",
            

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

"platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "blue-grey",
            "restart": "sudo systemctl restart homebridge",
            temp": "/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input",
            "tempUnits": "c",
            "sudo": true,
            "standalone": true,
            "log": {
                "method": "systemd",
                "command": "sudo journalctl -fau homebridge"
            }
        },
    

**Screenshots:**

![IMG_1861](https://user-images.githubusercontent.com/35597907/72221832-899a2500-355e-11ea-89a1-ee25a9da7a8f.png)

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by SSMARTREPAIR** [comment]
On Synology Docker is the same issue

**Comment by SSMARTREPAIR** [comment]
Still Open (Note Stale)

**Comment by testpaul999** [comment]
Hi, this issue is there the whole time. All versions after the 4.7 don’t shows the temperature at an none RPI. 

Zeitzone | GMT+0100
-- | --
Ubuntu Eoan Ermine (19.10)
pi386


Node v12.15.0
v6.13.7
pi
/var/homebridge
/var/homebridge/config.json

**Comment by oznu** [comment]
Temperature display is now supported on more platforms and does not require config thanks to a 3rd party library.

The downside to this is, as you have discovered, it may not work in all cases.

**Comment by testpaul999** [comment]
Sorry installed the newest version of this ui ist down‘t show my temperature.
:-( 
At all versions before 4.7 this will work fine

**Comment by Caribsky** [comment]
IMHO, it would be better to allow users to add custom temperature settings in the config or CPU widget to display the temperature in case when a 3rd party library doesn't support equipment.

ps. I have a Synology docker, cpu temperature is not displayed now.

**Comment by oznu** [comment]
I doubt this will help Docker, but for Ubuntu/Debian based systems, you may be able to get the temperature readings by installing the `lm-sensors` package and doing a restart.

```
sudo apt-get install lm-sensors
```

⚠️ Do not install `lm-sensors` on Raspbian.

**Comment by testpaul999** [comment]
Hi, 

as i write at my issue description, before the ui version 4.7 the temperature works fine.

and lm-sensors already installed the whole time.

pi@pi386:~$ sudo apt install lm-sensors 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
lm-sensors ist schon die neueste Version (1:3.5.0-3ubuntu1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

**Comment by Caribsky** [comment]
Thank you @oznu for advise 

> sudo apt-get install lm-sensors

Just installed on Docker via Terminal of Homebridge Config UI without restarting.
It works on my Synology DS218+
may be needs to correct offsets of temperature.

**Comment by oznu** [comment]
The `temp` option is back in the next release. Currently in `@test`.

**Comment by bubez81** [comment]
Hello! I can't figure out why I don't see the cpu temperature on macosx, yet the System Information library also supports macosx. Are there any special steps that I need to perform by any chance?
