### ISSUE TITLE
Homebridge with hb-service and start with options (-R for example)

### ISSUE THREAD

**Issue by imsturmdernacht** [oznu/homebridge-config-ui-x#472]
Dear developer,

it's just a little question. How to start or restart home bridge (running with hb-service) with options (-R for example)?

Kind regards
Oli

**Comment by oznu** [comment]
You can pass -R by editing the relevant supervisor script that was created.

I do have plans to allow these options to be enables via the UI when using hb-service.

**Comment by oznu** [comment]
If you tell me details of your environment I can tell you what you need to do to enable this now.

**Comment by oznu** [comment]
The next release (currently in `@test`) will allow you to set the `-R`, and `-D` flags directly from the UI when running with `hb-service`.

![image](https://user-images.githubusercontent.com/3979615/72255877-f9daa080-365b-11ea-9028-52b832e8107e.png)
