### ISSUE TITLE
Not quite an error but would like to know how to fix/stop this

### ISSUE THREAD

**Issue by 400HPMustang** [oznu/homebridge-config-ui-x#473]
**Describe Your Problem:**
I would just like to be able to have whatever is causing the below log message resolved

**Logs:**

[homebridge-config-ui-x] "secretOrPrivateKey" has been deprecated, please use the new explicit "secret" or use "secretOrKeyProvider" or "privateKey"/"publicKey" exclusively.

**Homebridge Config:**

I don't believe that's relevant

**Screenshots:**

![image](https://user-images.githubusercontent.com/45641587/72223960-4d54cd80-353a-11ea-9241-97ade80c0908.png)

**Environment:**

* **Node.js Version**: v12.13.1
* **NPM Version**: v6.12.1
* **Homebridge Version**: v0.4.50
* **Homebridge Config UI X Version**: v4.7.0
* **Operating System**: Win 10 x64
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Do you have SSL configured?

Your config would be useful please.

**Comment by 400HPMustang** [comment]
SSL is not configured. Config is as follows

`{
    "mdns": {
        "interface": "10.107.112.25"
    },
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51826,
        "pin": "xxx-xx-xxx",
        "log": {
            "method": "file",
            "path": "C:\\Users\\UserName\\.homebridge\\homebridge.log"
        }
    },
    "description": "Non-HomeKit Stuff",
    "accessories": [
        {
            "accessory": "OctoPrint",
            "name": "Right Side S5",
            "server": "http://10.107.112.114",
            "api_key": "26BC23FA96DD42EF8AAEE45891E4F2B5"
        },
        {
            "accessory": "OctoPrint",
            "name": "Left Side S5",
            "server": "http://10.107.112.109",
            "api_key": "DD76398C2FC74618A8F67819B8F11CA5"
        },
        {
            "accessory": "OctoPrint",
            "name": "Right Side CR-10",
            "server": "http://10.107.112.38",
            "api_key": "395483438D4D4187BF0DB7FFABD4F99F"
        },
        {
            "accessory": "OctoPrint",
            "name": "Left Side CR-10",
            "server": "http://10.107.112.29",
            "api_key": "18560D36666B442794C1241A6290D81C"
        },
        {
            "ip": "http://10.107.112.63:8060",
            "info": {
                "udn": "02780016-0c00-1047-8016-3052cbd0fddd",
                "serialNumber": "2N00F3018198",
                "deviceId": "4565CF018198",
                "advertisingId": "82632802-7e84-5fcd-9873-ee6e03a63caf",
                "vendorName": "Sharp",
                "modelName": "Sharp LC-43LB371U",
                "modelNumber": "5303X",
                "modelRegion": "US",
                "isTv": "true",
                "isStick": "false",
                "screenSize": "43",
                "panelId": "2",
                "tunerType": "ATSC",
                "supportsEthernet": "false",
                "wifiMac": "30:52:cb:d0:fd:dd",
                "wifiDriver": "aardvark",
                "networkType": "wifi",
                "networkName": "xxxxx",
                "friendlyDeviceName": "Office TV",
                "friendlyModelName": "Sharp•Roku TV",
                "defaultDeviceName": "Sharp•Roku TV - 2N00F3018198",
                "userDeviceName": "Office TV",
                "buildNumber": "139.10E04501A",
                "softwareVersion": "9.1.0",
                "softwareBuild": "4501",
                "secureDevice": "true",
                "language": "en",
                "country": "US",
                "locale": "en_US",
                "timeZoneAuto": "false",
                "timeZone": "US/Central",
                "timeZoneName": "United States/Central",
                "timeZoneTz": "America/Matamoros",
                "timeZoneOffset": "-360",
                "clockFormat": "12-hour",
                "uptime": "1216352",
                "powerMode": "PowerOn",
                "supportsSuspend": "true",
                "supportsFindRemote": "false",
                "supportsAudioGuide": "true",
                "supportsRva": "true",
                "developerEnabled": "false",
                "keyedDeveloperId": "",
                "searchEnabled": "true",
                "searchChannelsEnabled": "true",
                "voiceSearchEnabled": "true",
                "notificationsEnabled": "true",
                "notificationsFirstUse": "true",
                "supportsPrivateListening": "true",
                "supportsPrivateListeningDtv": "true",
                "supportsWarmStandby": "true",
                "headphonesConnected": "false",
                "supportsEcsTextedit": "true",
                "supportsEcsMicrophone": "true",
                "supportsWakeOnWlan": "false",
                "hasPlayOnRoku": "true",
                "hasMobileScreensaver": "false",
                "supportUrl": "www.sharptvusa.com/support",
                "grandcentralVersion": "2.7.91",
                "davinciVersion": "2.5.75"
            },
            "inputs": [
                {
                    "id": "tvinput.hdmi3",
                    "name": "HDMI 3"
                },
                {
                    "id": "tvinput.hdmi1",
                    "name": "Cable box"
                },
                {
                    "id": "tvinput.hdmi2",
                    "name": "Computer"
                },
                {
                    "id": "tvinput.dtv",
                    "name": "Antenna TV"
                },
                {
                    "id": "2016",
                    "name": "Crackle"
                },
                {
                    "id": "52838",
                    "name": "Nickelodeon"
                },
                {
                    "id": "45437",
                    "name": "FilmRise"
                },
                {
                    "id": "41468",
                    "name": "Tubi - Free Movies & TV"
                },
                {
                    "id": "6119",
                    "name": "Popcornflix"
                },
                {
                    "id": "38896",
                    "name": "WatchFreeFlix"
                },
                {
                    "id": "52679",
                    "name": "channel PEAR"
                },
                {
                    "id": "74218",
                    "name": "Paramount Network"
                },
                {
                    "id": "47389",
                    "name": "FXNOW"
                },
                {
                    "id": "12",
                    "name": "Netflix"
                },
                {
                    "id": "13",
                    "name": "Prime Video"
                },
                {
                    "id": "143088",
                    "name": "BritBox"
                },
                {
                    "id": "2285",
                    "name": "Hulu"
                },
                {
                    "id": "291097",
                    "name": "Disney Plus"
                }
            ],
            "name": "Roku",
            "accessory": "Roku"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8008,
            "auth": "form",
            "theme": "blue-grey",
            "restart": "hb-service restart",
            "tempUnits": "f",
            "sudo": false,
            "debug": true,
            "log": {
                "method": "file",
                "path": "C:\\Users\\UserName\\.homebridge\\homebridge.log"
            },
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },
        {
            "platform": "SleepNumber",
            "username": "xxxxxxxxxx@gmail.com",
            "password": "xxxxxxxxxx",
            "refreshTime": 5
        },
        {
            "platform": "MagicHome-Platform",
            "debug": true,
            "lights": [
                {
                    "name": "Humidor LED Strip",
                    "disableDiscovery": false,
                    "ip": "10.107.112.40",
                    "setup": "RGBW",
                    "purewhite": false,
                    "timeout": 10000
                }
            ],
            "presetSwitches": [
                {
                    "name": "Fade White Lights",
                    "ips": {
                        "10.107.112.40": "255,255,255"
                    },
                    "preset": "white_gradual_change",
                    "speed": 120,
                    "shouldTurnOff": false
                },
                {
                    "name": "Fade Red Lights",
                    "ips": {
                        "10.107.112.40": "255,255,255"
                    },
                    "preset": "red_gradual_change",
                    "speed": 120,
                    "shouldTurnOff": false
                }
            ]
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "pollingInterval": 10,
            "timeout": 0
        },
        {
            "platform": "People",
            "threshold": 2,
            "anyoneSensor": false,
            "nooneSensor": true,
            "webhookPort": 51828,
            "cacheDirectory": "",
            "pingInterval": 10000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "Person 1",
                    "target": "10.107.112.53",
                    "threshold": 15,
                    "pingInterval": 10000
                },
                {
                    "name": "Person 2",
                    "target": "10.107.112.50",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Person 3",
                    "target": "10.107.112.51",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Person 4",
                    "target": "10.107.112.68",
                    "threshold": 15,
                    "pingInterval": 10000,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Person 5",
                    "target": "10.107.112.95",
                    "threshold": 15,
                    "pingInterval": 10000
                }
            ],
            "name": "People"
        },
        {
            "email": "xxxxxxxxxx@gmail.com",
            "password": "xxxxxxxxx",
            "cameraStatusPollingSeconds": 10,
            "cameraDingsPollingSeconds": 2,
            "platform": "Ring"
        },
        {
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "CR-10 Left Side",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://10.107.112.29:8080/?action=stream",
                        "stillImageSource": "-f mjpeg -i http://10.107.112.29:8080/?action=snapshot",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 800,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "S5 Right Side",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://10.107.112.97:8080/?action=stream",
                        "stillImageSource": "-f mjpeg -i http://10.107.112.97:8080/?action=snapshot",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 800,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "CR-10 Right Side",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://10.107.112.38:8080/?action=stream",
                        "stillImageSource": "-f mjpeg -i http://10.107.112.38:8080/?action=snapshot",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 800,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "S5 Left Side",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://10.107.112.109:8080/?action=stream",
                        "stillImageSource": "-f mjpeg -i http://10.107.112.109:8080/?action=snapshot",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 800,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}`

**Comment by oznu** [comment]
Thanks for reporting this @400HPMustang.

I've found the issue here and replaced the depreciated option.

This will be available in the next release (v4.7.1-test.5 currently in `@test`).
