### ISSUE TITLE
Using hb-service with npm?

### ISSUE THREAD

**Issue by npburns224** [oznu/homebridge-config-ui-x#474]
I’ve installed the latest version of node through nvm because I prefer not having to “sudo” everything like you do with npm. 
Is there any way to run the hb-service sudo-less with nvm?

**Comment by oznu** [comment]
Hi @npburns224,

Currently not, and I'm not sure if I will make this option configurable for `hb-service` on Linux. If you want more advanced options like this then using `pm2` or `systemd` (directly) are probably more for you.

The goal of `hb-service` is to have a consistent set up process across platforms/linux distributions, the lack of this at the moment is part of what makes Homebridge a bit inaccessible to new users.

**Comment by gpoul** [comment]
Hi @oznu,

I just set up homebridge on a new Raspberry and given this is my second time around I wanted to get fancy and tried the nvm route as well; I've gotten it working pretty nicely using your systemd scripts, but the updates don't work out of the box as you're using sudo when service mode is enabled, which hb-service seems to do prior to launching through systemd.

Do you think it would be a good solution to look for a defined "NVM_DIR" or some other environment variable?

I can go ahead and change this locally and test it, but I'd like to get your input whether this would be a solution that you'd consider merging and where you might see further challenges that will have to be overcome in that case to build a worthwhile solution?
