### ISSUE TITLE
Snippet / Template for Terminal Widget

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#477]
The latest update is fantastic. Thanks you so much for your great work and time you are investing @oznu 

I seeing myself using the Terminal Widget a lot now instead of an additional App like Terminus.
For most small commands the Terminal Widget is great and useful.
However I miss a feature like Snippet or Template to have some command always available.
It would be great if I could define some snippets by myself like i.e. "npm list -g --depth=0" or "sudo systemctl stop homebridge" and so forth and paste them with a click in the terminal widget.

Maybe you are willing to consider a feature like this. 
Thanks again and all the best to you.

**Comment by oznu** [comment]
Hi @DJay-X,

Thanks for the suggestion. It's unlikely I'll implement this feature sorry as my priorities are elsewhere and the other dedicated apps like Terminus already do this well.

You might like to look into creating [aliases](https://shapeshed.com/unix-alias/) which allow you to to alias a long command with a short one.

Or you could use shell history search, you press `CTRL + R` then type the first few letters of a command you have previously entered and it will populate the rest of the command for you.

Or you could create a few shell scripts which would make it easier to run more complex commands quickly.
