### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Luftloch80** [oznu/homebridge-config-ui-x#479]
there is a miss spelling in German translation 
“augfeschlossen“ Must be „aufgeschlossen“

**Comment by oznu** [comment]
Thanks @Luftloch80,

Would you be willing to make the change here: https://github.com/oznu/homebridge-config-ui-x/blob/master/ui/src/i18n/de.json

There a few other new strings that need translation too.

**Comment by sschuste** [comment]
I'll care about that.
