### ISSUE TITLE
freebsd 12: route has not been found error with 4.7.0 and 4.8.0

### ISSUE THREAD

**Issue by jwcasl** [oznu/homebridge-config-ui-x#488]
Thank you for config-ui-x. 

Since 4.7.0, I've been unable to get the config-ui-x to work in FreeBSD 12 jail. It would seem to work and I can get to the log in screen and log in. But once I log in, the page doesn't load and I get a big spinning arrow forever. I've downgraded to 4.6.7 which still works.

**Log**
[Config] Homebridge Config UI X v4.8.0 is listening on 0.0.0.0 port 8080
route: route has not been found
Error: Command failed: route get 0.0.0.0 | grep interface:
route: route has not been found

    at checkExecSyncError (child_process.js:609:11)
    at execSync (child_process.js:645:15)
    at getDefaultNetworkInterface (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/systeminformation/lib/network.js:96:18)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/systeminformation/lib/network.js:175:20
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[1/17/2020, 9:58:37 PM] Got SIGTERM, shutting down Homebridge...

I tried to manually set a "host" to the local IP of the machine, but that didn't work either.

**Environment**
    Node.js Version: Node.js v13.3.0
    NPM Version: 6.13.6
    Homebridge Version: 0.4.50
    Homebridge Config UI X Version:v4.7.0 and 4.8.0
    Operating System: FreeBSD-12.1-release-p1
    Process Supervisor: freeBSD jail

Thank you for looking into this.

**Comment by oznu** [comment]
I can't replicate this on native FreeBSD 11/12 or in a FreeBSD 11.3 Jail running in FreeNAS.

**Comment by oznu** [comment]
Try the latest `@test` releases, I have stopped the network information from being displayed when running on FreeBSD entirely. 

```
npm install -g --unsafe-perm homebridge-config-ui-x@test
```

**Comment by jwcasl** [comment]
Thank you. This works!
