### ISSUE TITLE
Enhance Plugin Settings GUI with ability to trigger a script

### ISSUE THREAD

**Issue by buenyamin-olgun** [oznu/homebridge-config-ui-x#489]
**Is your feature request related to a problem? Please describe:**
As far as I know currently there's no option to gather information from anywhere in the plugin setting GUI. There are plugins which need to authenticate via OTP to a page, plugins which need a MAC-Address of a device or an API key of a device itself. Currently the user has to gather these informations himself.

**Describe the solution you'd like:**
There should be a way to define a button in config.schema.json which triggers a script with user given data as arguments and the return statement of the script should end up as a value for a pre-defined key in the Plugin Settings GUI. 

For example:
The user enters username, password and OTP code the 3 different fields in Plugin Settings GUI and clicks a button "authenticate".

Homebridge-config-ui-x takes these data and executes a "authenticate.js" file with the given data as arguments.

"authenticate.js" returns a hash which will be set in the Plugin Settings GUI.

**Comment by oznu** [comment]
Hi @buenyamin-olgun,

I don't really like the idea of plugins being able to run arbitrary scripts in the UI context.

I am happy to add custom screens and even server side logic for plugins that have special requirements beyond what the `config.schema.json` can support if the plugin author reaches out to me.

I've done this already for [Homebridge Ring](https://github.com/dgreif/ring/tree/master/homebridge), the screen prompts for the users OTP password if they have 2FA enabled:

![image](https://user-images.githubusercontent.com/3979615/72675181-a5f50f00-3ad4-11ea-9200-84a0b4fdb649.png)

And [Homebridge Honeywell Home](https://github.com/donavanbecker/homebridge-honeywell-home):

![image](https://user-images.githubusercontent.com/3979615/72675185-b0afa400-3ad4-11ea-808a-3d381691d1af.png)

As well as [Homebridge GSH](https://github.com/oznu/homebridge-gsh) (which I am the author of):

![homebridge-gsh-signup](https://user-images.githubusercontent.com/3979615/62948031-ff228d80-be26-11e9-9e07-ef1023f28fa8.gif)

I'll add a note about this to the wiki.
