### ISSUE TITLE
Feature Request: Per-User Dashboard Config

### ISSUE THREAD

**Issue by jchenevey** [oznu/homebridge-config-ui-x#491]
I'm working on a smart home control panel, and wanted to leverage Homebridge Config UI for the control panel UI.

I have an `admin` user, and I have a `panel` user. Currently, if I change the dashboard layout for one user, it changes the layout for the other user as well.

Would it be possible to have a separate dashboard layout per user?

**Comment by trise-ne** [comment]
I'd love to see this feature as well! It would be nice to grant sb access to control devices in status/widget view but block every other widget module and the other pages (plugin, devices, config).
