### ISSUE TITLE
NPM & Node Versions

### ISSUE THREAD

**Issue by donavanbecker** [oznu/homebridge-config-ui-x#493]
**Is your feature request related to a problem? Please describe:**

*No*

**Describe the solution you'd like:**

*Would be nice if there was an option on this widget to flag to see if there is a new update for node or npm, or if there is an updated that is needed for minimum requirements*

**Describe alternatives you've considered:**

*Not sure if this is possible, but figured i would suggest.*

**Additional context:**

![image](https://user-images.githubusercontent.com/9875439/72672355-9e772c80-3a26-11ea-95de-3795d43cad45.png)
![image](https://user-images.githubusercontent.com/9875439/72672361-a9ca5800-3a26-11ea-8898-0ca8babdffe6.png)

**Comment by oznu** [comment]
Hi @donavanbecker,

> Would be nice if there was an option on this widget to flag to see if there is a new update for node or npm, or if there is an updated that is needed for minimum requirements

That's exactly how it currently works. If your Node.js/npm version does not meet the minimum requirements a warning icon will appear. If there is an update available that's not required (like a minor patch) the latest version number will be displayed when you hover over the current version listed.

**Comment by donavanbecker** [comment]
Sorry I thought you took this out, from reading another list. Sorry.
