### ISSUE TITLE
FreeNAS Jail - Problem with Mellanox Cards

### ISSUE THREAD

**Issue by Grinchii** [oznu/homebridge-config-ui-x#499]
It now works on FreeNAS with the newest Version.

But there seems to be a problem with 10GBE Mellanox Cards. While Homebridge is running the system gets flooded with noise from this card.

    mlx4_core0: port level mtu is only used for IB ports
    mlx4_core0: port level mtu is only used for IB ports
    mlx4_core0: port level mtu is only used for IB ports
    mlx4_core0: port level mtu is only used for IB ports
    mlx4_core0: port level mtu is only used for IB ports

About every 3sec I get this message twice.

It seems like homebridge in the newest version is using something like sysctl quite often. This trys accessing the card and the error occurs.

**Comment by oznu** [comment]
This should be fixed in the next release.

Currently in `@test`.
