### ISSUE TITLE
[Feature] Ability to update core system (apt)

### ISSUE THREAD

**Issue by davetaz** [oznu/homebridge-config-ui-x#50]
I use many Raspberry PIs as homebridge nodes with LED strips and z-wave etc on them. 

It would be nice to also use this interface to perform the system updates and get alerted about apt updates (including security etc). Would this be a challenge to add?

**Comment by oznu** [comment]
Hi @davetaz,

I think this feature might be a bit out of scope for this project.

I have implemented a terminal feature that is currently only activated when running the plugin in a docker container. Perhaps I could enable this for other users as well (via an opt-in flag) which would allow users to be to quickly run their `apt` commands without having to connect over ssh (or attach a kb/mouse/screen in the case of some users)?

![image](https://user-images.githubusercontent.com/3979615/37450069-b07d3438-2880-11e8-9c4e-ed3680b74b0c.png)

**Comment by davetaz** [comment]
Having given this some further thought, I think that perhaps it might be great to try and have a "plugin style" architecture for other features. Perhaps apt can be one, another could be related to editing other config files (e.g. shaireport-sync). I'm keen to apply my down time to look at the potential of this. Haven't used the exact framework before but sure I could work it out.

If I was to add a plugin that could edit another files config in /etc/ where would be the place to start (file or dir)? Happy then to take a look.

**Comment by oznu** [comment]
> If I was to add a plugin that could edit another files config in /etc/ where would be the place to start (file or dir)? Happy then to take a look.

There are two components that will be required for this to work. The user interface and the server.

Any plugins should be implemented as a standalone Angular 5 compatible module. For example: https://github.com/oznu/homebridge-config-ui-x/tree/master/ui/src/app/platform-tools/docker

And this is the server side routes for that module: https://github.com/oznu/homebridge-config-ui-x/blob/master/src/routes/platform-tools/docker.ts

This could be split out into it's own npm module.

**Comment by davetaz** [comment]
Thanks!
