### ISSUE TITLE
All installed accessories from second 'Homebridge' installation appearing

### ISSUE THREAD

**Issue by LaborEtArs** [oznu/homebridge-config-ui-x#501]
After setting up the development env. on my Mac (Many thanks for your support), all  installed accessories of my 'production' installation (on the Raspberry) appeared in the development homebridge/config-ui too. Even if the needed plugins weren't installed in the development system.
The dev. installation is just locally installen and not added to homekit and uses a different name/id.
Is this an expected behavior?

**Comment by donavanbecker** [comment]
If you add them to the black list in the config UI x accessory control settings, does it delete them out of the development instance?

**Comment by LaborEtArs** [comment]
Indeed! All gone now :-)
Are those two homebridge installations talking to each other without being connected to homekit?

**Comment by donavanbecker** [comment]
Yep! @oznu has it setup so that other accessories show up from other instances and that is why he has the blacklist option.

**Comment by LaborEtArs** [comment]
I see. Do you know the reasoning behind this. From my point of view the other way around (allow to integrate another instance's accessories) would have been the 'expected' behavior...

**Comment by donavanbecker** [comment]
@oznu

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x#accessory-control -> Controlling Multiple Instances

The UI just finds all Homebridge  instances running in `-I` mode on your network and displays the accessories for them. You can't control the other instance accessories unless then PIN is set the same on both instances.

The reason for this is many users run multiple instances of Homebridge but wanted a consolidated accessories view. Additionally this feature allowed access to devices that are not on the main bridge, such as TVs (and Cameras - though they are not supported, but now show up).
