### ISSUE TITLE
I suggest adding hls player for viewing from IP cameras.

### ISSUE THREAD

**Issue by roysbike** [oznu/homebridge-config-ui-x#505]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by oznu** [comment]
Hi @roysbike,

Checkout this plugin which provides the functionality you're after:

https://github.com/SeydX/homebridge-camera-ui

There are too many different camera configurations out there and I don't want to go down that rabbit hole with this plugin.
