### ISSUE TITLE
Cannot find serialport and other plugin's

### ISSUE THREAD

**Issue by gmqkyp** [oznu/homebridge-config-ui-x#507]
**Describe Your Problem:**
When I use the UI search function and add SerialPort in the field it returns blank  i.e. it cannot find it. I can manually find it using npm on a webpage

**Comment by donavanbecker** [comment]
Can you send the npm link?

**Comment by gmqkyp** [comment]
https://www.npmjs.com/package/serialport

**Comment by oznu** [comment]
That is not a homebridge plugin. Only homebridge plugins show in the search results.
