### ISSUE TITLE
Speakers service

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#509]
Hi @oznu 
in the Speaker Tile we get control Switch with label On/Off, what is it exactly? is that Power On/Off or is that Mute On/Off, if this is Mute state switch them need to be labeled “Mute On/ Mute Off”.

Other case the “Volume” label at the end of name the Speaker Tile need to be also translatable. I have marked this cases on screenshot.

Thanks
![E19447A9-81DD-4E8B-9DD3-56EEC55D0CDC](https://user-images.githubusercontent.com/28867813/73117752-e8926d80-3f52-11ea-8eb1-c68bb3d0bddd.jpeg)

**Comment by oznu** [comment]
Thanks @grzegorz914,

I've changed the labels to be On / Mute.

Regarding the tile name, that is coming directly from the Homebridge plugin that is providing the speaker service. You can rename the tile manually using the cog on the accessory.

Currently in `@test`.

**Comment by grzegorz914** [comment]
Hi @oznu 
now we have the switch labeled: ON —— Mute, nothing else.
The label need to be labeled: Mute ON —— Mute OFF.
Also the tile right now display state Mute however device is not muted, and displays 100% if device is Muted.

**Comment by oznu** [comment]
Just how I see it... "Mute ON" I feel is an oxymoron, you don't turn a speaker "Mute ON", you just set a speaker to "Mute", which silences the speaker, then to unsilence it, you turn the sound back "ON". This may be different elsewhere but that's how devices I have encountered work.

Either way, I have added the `accessories.control.label_not_mute` i18n string so different regions can set this to what makes sense to them 😄 

I should also have fixed an issue where the volume was showing even when the device did not support volume sliders. In `@test`.

**Comment by ebaauw** [comment]
I’m no native speaker, but I’d either use _Mute On_ and _Mute Off_ or _Mute_ and _Unmute_.  The first better reflects the characteristic vs the characteristic value; the second seems a bit more natural.

Note that Eve displays _Mute_ as _Audio_ with reversed logic (i.e. _Audio_ on is _Mute_ off).
