### ISSUE TITLE
[Enhancement] kind of 😉 Releases Change Log

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#51]
@oznu Thanks for your ongoing development and constant update.
A lot of people ( as I can see in the very passionated German Forum http://homekit.community ) love the recent implementation of accessories feature. ❤️👍🏻

One question was asked due to the frequent updates, if it is possible you could give some info when a new version is out, what the changes are. Would be very appreciated.
https://github.com/oznu/homebridge-config-ui-x/releases

As always, thanks a lot for your time you are investing and for sharing with the community. 😃

**Comment by oznu** [comment]
Good idea. I've been thinking of the best way to do this for a while, I would like to be able to display the change log in the interface during the update workflow.

**Comment by oznu** [comment]
I had a read of the forum (thanks to Google Translate, my german skills are limited to numbers and the word no). You're accessory screen looks very impressive, I didn't imagine people would have so many accessories. 

I'll paste it here for others to see:

![image](https://user-images.githubusercontent.com/3979615/37260638-b9760806-25e9-11e8-802e-63e4cff1ddee.png)

The issue with Safari was fixed last night.

**Comment by oznu** [comment]
Change log implemented. Any updates you install *after* 3.2.0 will display the changelog in the user interface after installation. The update *to* 3.2.0 won't display it.

It will also show the change log for any other plugin that has a change log published in the npm package.

**Comment by oznu** [comment]
Hi @DJay-X,

Creating a GitHub release and adding notes to it is now a supported method of getting the changelog to show up when updating and can replace the need for a dedicated CHANGELOG.md.

GitHub Release Notes - Shown before update occurs
CHANGELOG.md - Shown after update has happened

I'm doing both in this plugin at the moment but, I think the GitHub release method would be the one to recommend authors support.
