### ISSUE TITLE
remove old entries after plugin deletion

### ISSUE THREAD

**Issue by henkied** [oznu/homebridge-config-ui-x#510]
remove old entries after plugin deletion.

Can someone help me after removing the ikea plugin. I continue to receive a notification see below. How can I delete it?

I have deleted the persist and accessories folder. Unfortunately, this has no result.

[1/25/2020, 10:42:09 AM] [Config] Failed to parse plugin "homebridge-ikea-tradfri-gateway": ENOENT: no such file or directory, open '/homebridge/node_modules/homebridge-ikea-tradfri-gateway/package.json'

**Comment by mafyata** [comment]
Did you deleted ikea code in your config.json ?

**Comment by henkied** [comment]
thx for reply yes config.json is clean

**Comment by donavanbecker** [comment]
There is a HomeBridge setting that will clear old accessories.

**Comment by donavanbecker** [comment]
> There is a HomeBridge setting that will clear old accessories. On the right side of config ui-x

**Comment by henkied** [comment]
Ah great were can i find this option i only see this, ser att![](![Image](https://i.imgur.com/W0cI4EB.jpg))

**Comment by henkied** [comment]
![Image](https://i.imgur.com/gT47a0B.jpg)

**Comment by henkied** [comment]
Thx but i do not see this option, see attachment. 
<img width="515" alt="Schermafdruk 2020-01-25 22 31 32" src="https://user-images.githubusercontent.com/20031014/73127575-a6087980-3fc2-11ea-8f71-912c0af7229f.png">

**Comment by henkied** [comment]
I think that is because I don't have the hb service running? is that right?

I have homebridge running on a synology NAS.

@oznu  how should I install hb service on an existing installation. I can't find anything about this in the wiki.

Thanks

**Comment by oznu** [comment]
Just delete `/homebridge/node_modules/homebridge-ikea-tradfri-gateway` manually and the message will go away.

> how should I install hb service on an existing installation. I can't find anything about this in the wiki.

You shouldn't. The wiki says you shouldn't 😄.

**Comment by henkied** [comment]
haha oke. but sorry there is no file in that root I can't find any file like ikea or tradfri

**Comment by oznu** [comment]
It's inside the container/your volume mount. 

rm -rf it from the web terminal.

**Comment by henkied** [comment]
sorry i do not understand (noob;)) do you mean the container on the synology? and where do i give the command "rm -rf" I can not find the file in de root with filemanager synology
