### ISSUE TITLE
System Information Widget question

### ISSUE THREAD

**Issue by ldellus** [oznu/homebridge-config-ui-x#518]
**The Problem:**

I just want to know where the System Information Widget gets the IP address it is displaying because on my system it shows the wrong IP.

**Homebridge Config:**

{                                                                                                                                                                     "bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30", 
"port": 51826, 
"pin": "031-45-154"
},
"description": "Homebridge configuration file.", 
"platforms": [
{
"platform": "config", 
"name": "Config",
"port": 8080,
"restart": "pm2 restart \"homebridge -I\"",
"sudo": false,
"log": {
"method": "file",
"path": "/root/.pm2/logs/homebridge--I-out.log"
}

**Screenshots:**

![Homebridge Config Wrong IP](https://user-images.githubusercontent.com/1569174/73556405-11859780-4458-11ea-920f-f534c9b8b074.png)

**Environment:**

* **Node.js Version**: v12.14.1
* **NPM Version**: 6.13.4
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**:homebridge-config-ui-x v4.9.0
* **Operating System**: Ubuntu Bionic Beaver (18.04.3 LTS)
* **Process Supervisor**: pm2

**Comment by oznu** [comment]
It is the IP address of the interface used as the default route.

**Comment by ldellus** [comment]
Thanks, problem solved. I deleted the offending route.

**Comment by oznu** [comment]
Great!
