### ISSUE TITLE
Only npm button after update 3.2 in safari

### ISSUE THREAD

**Issue by henkied** [oznu/homebridge-config-ui-x#52]
<img width="510" alt="schermafdruk 2018-03-12 19 00 04" src="https://user-images.githubusercontent.com/20031014/37301015-bab05742-2627-11e8-82f1-abdf4096f98d.png">

**Comment by oznu** [comment]
I removed it for just for the homebridge-config-ui-x plugin since accidentally clicking would not be good.

https://github.com/oznu/homebridge-config-ui-x/blob/master/CHANGELOG.md#320-2018-03-12

It shows up for your other plugins right?
