### ISSUE TITLE
Config-ui-x page looses session when added to home screen in IOS

### ISSUE THREAD

**Issue by tooh** [oznu/homebridge-config-ui-x#523]
**Describe The Bug:**

- Add page to IOS home screen.
- login
- it works but after a while it does not work, page does not appear

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by mafyata** [comment]
Open config ui x , enter password and then add to home screen. Mine works. You can disable password, I done it and work.

**Comment by oznu** [comment]
I've added this to my home screen and haven't been able to replicate this over the last two days.

When you get the blank screen have you tried force quitting the app the opening it again?

**Comment by oznu** [comment]
I've been testing this for about 2 weeks and still can't replicate this.

Just force quit the app (swipe force close) to refresh everything if this ever happens.
