### ISSUE TITLE
how to clear cached accessories?

### ISSUE THREAD

**Issue by platini76** [oznu/homebridge-config-ui-x#525]
System: Added the ability for hb-service users to clear the Homebridge cached accessories from the UI (without doing a full Homebridge reset)

how to use it? sorry but I don't see any button...

**Comment by oznu** [comment]
Menu -> Homebridge Settings -> Clear Cache

![image](https://user-images.githubusercontent.com/3979615/73893703-82043c80-48ce-11ea-83f9-803ea79d168a.png)

![image](https://user-images.githubusercontent.com/3979615/73893711-86305a00-48ce-11ea-9f45-19ccca866e16.png)

If you don't see this option then you're probably not running under `hb-service`.

**Comment by platini76** [comment]
I have not this option
![IMG_0505](https://user-images.githubusercontent.com/10352902/73895609-7558f780-4880-11ea-9519-7f9fc42da8a6.PNG)

**Comment by oznu** [comment]
That means you're not running Homebridge + Homebridge Config UI X using the [`hb-service`](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command) process supervisor.

**Comment by platini76** [comment]
pi@home_hub:~$ systemctl status homebridge
● homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor prese
   Active: active (running) since Thu 2020-02-06 01:56:07 CET; 5min ago
  Process: 765 ExecStartPre=/usr/lib/node_modules/homebridge-config-ui-x/dist/bi
 Main PID: 996 (hb-service)
    Tasks: 22 (limit: 4915)
   CGroup: /system.slice/homebridge.service
           ├─ 996 hb-service
           └─1407 homebridge

now is correct?

**Comment by oznu** [comment]
Should be.
