### ISSUE TITLE
Date Widget German translation

### ISSUE THREAD

**Issue by buenyamin-olgun** [oznu/homebridge-config-ui-x#528]
Similiar to #515: Would it be possible to add translations for the date / time widget?

Thank you for your great job!

**Comment by oznu** [comment]
This is a bit more complicated that it might seem as the date formats are generated by the Angular lib - I will need to include other Angular i18n translations into the one build.

**Comment by oznu** [comment]
This will be included in the next release. The dates will be formatted for any supported translation.
