### ISSUE TITLE
Trigger a state change via http?

### ISSUE THREAD

**Issue by uspino2** [oznu/homebridge-config-ui-x#530]
I'd like to trigger a switch with a simple http call. Since this is basically what the Accessories panel does when you click on an accessory, is there an easy way to find the url being hit? Thanks.

**Comment by oznu** [comment]
Nothing special is done by this plugin.

You can send a PUT request directly to your Homebridge server.

https://github.com/NorthernMan54/Hap-Node-Client/blob/master/HAPNodeJSClient.js#L178

**Comment by uspino2** [comment]
Thanks, exactly what I was looking for. Sounds a little embarrassing, but how do I get a list (json?) of all the available characteristics?

**Comment by oznu** [comment]
Do a GET request to `/accessories`.

**Comment by uspino2** [comment]
Got it. But what if the accessory I want to control is linked to a platform (motion sensor in camera-ffmpeg)? GET request to `/accessories` only lists stand-alone accessories...

**Comment by oznu** [comment]
That endpoint lists everything.

It's unlikely you will be able to control the state of a motion sensor via this endpoint though, that's something the plugin would have to do I would imagine. Give it a try though.

**Comment by uspino2** [comment]
The plugin has a dummy switch to trigger the motion sensor (turns off automatically) so the idea was to trigger the switch with a PUT request or http call. Interestingly enough, the GET request to my endpoint lists all accessories except for cameras or motion/switches associated to those cameras...

**Comment by oznu** [comment]
Cameras start on a different port, the port should be listed in the Homebridge log it starts.

**Comment by uspino2** [comment]
Got it working perfectly. Thanks!

**Comment by oznu** [comment]
Great!
