### ISSUE TITLE
Node version not updated in GUI

### ISSUE THREAD

**Issue by Phoenix-DH** [oznu/homebridge-config-ui-x#533]
Hey,

maybe it would be possible to update the node version in the GUI?

At the moment a service restart is needed.

**Comment by oznu** [comment]
Hi @Phoenix-DH,

The node version shown the is version that the UI is currently running under.

A restart is needed after a Node.js update for Homebridge to pick up the new version.

**Comment by Phoenix-DH** [comment]
Ok, thanks for the info.

**Comment by oznu** [comment]
Did you mean actually performing a Node.js update via the GUI?

If so, I have thought about that to, but there are just to many different methods for installing and updating Node.js out there I don't even want to start getting into that.

**Comment by Phoenix-DH** [comment]
No, no update via GUI... only actual installed version
