### ISSUE TITLE
How do you install a python plugin?

### ISSUE THREAD

**Issue by jlhunter2008** [oznu/homebridge-config-ui-x#534]
**Describe Your Problem:**
I am running this on a Synology using docker. How do I install a python script/plugin? Specifically, the script called sucks.

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

OS	Alpine Linux (3.10.3)
Node.js Version	v12.14.0
Npm Version	v6.13.4
Docker	Yes

**Comment by oznu** [comment]
I'm not sure what you are trying to do with Python from the description of have provided; but can use the terminal via the UI or via the Synology DSM Docker app to download and run Python scripts if you wish.
