### ISSUE TITLE
[Developer] Settings Panel description appears twice

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#535]
**Describe The Bug:**
When adding a "description" tag to an array the description appears in two places, see this image:
https://i.imgur.com/eRCsGGk.png
(note the text :"leave empty to...")

**To Reproduce:**
Add an array to config.schema.json and give it a description, see this config.schema.json producing the output above.
https://github.com/normen/homebridge-bravia/blob/master/config.schema.json

**Expected behavior:**
The description should only appear in the 

**Logs:**
See image above

**Homebridge Config:**
```json
omitted, see config.schema.json above
```

**Screenshots:**
https://i.imgur.com/eRCsGGk.png

**Environment:**

* **Node.js Version**: 10.15
* **NPM Version**: 6,9
* **Homebridge Version**: 0.50
* **Homebridge Config UI X Version**: 0.4.10
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
Hi @normen - after spending to long trying to figure this out - it looks like a bug in the upstream library (https://github.com/hamzahamidi/ajsf).

I'll try work on it more later.

**Comment by oznu** [comment]
The same duplicate description effect can be seen in the [demonstration playground](https://hamidihamza.com/ajsf/?framework=bootstrap-4).

**Comment by normen** [comment]
Thanks for checking, no biggie for now, just thought it should be documented. Cheers!

**Comment by donavanbecker** [comment]
I experienced this two when I was going through different plugins to add the config.schema.json. I believe I was able to work around this by adding the layout schema, and adding the description there.

**Comment by oznu** [comment]
@donavanbecker - that's what I thought would be the solution as well. It turns out that doesn't work so well when using nested arrays inside nested arrays.

**Comment by donavanbecker** [comment]
@oznu Good to know.

**Comment by normen** [comment]
Awesomesauce, my settings panel looks very nice now, thanks! :)
