### ISSUE TITLE
Found left-over process (homebridge-conf)

### ISSUE THREAD

**Issue by roe1974** [oznu/homebridge-config-ui-x#538]
Hello
I am runing config-ui-x in the new version.
Config-ui-x is running in two homebridge instances.....
Everytime when i restart homebridge (systemctl restart) i have this error in the log:

Found left-over process 590 (homebridge-conf)

Is this coming from your Plug-In config-ui-x ?

thx, Richard

**Comment by oznu** [comment]
Hi @roe1974,

Please fill in the issue template so I can help with this issue.

Config file so I can see your restart command, full log file so I can see the error in context, plus environment details.

**Comment by roe1974** [comment]
here the log while restart:

Feb 12 11:34:11 homebridge-raspi homebridge[485]: [2/12/2020, 11:34:11] Got SIGTERM, shutting down Homebridge...
Feb 12 11:34:16 homebridge-raspi systemd[1]: homebridge-nest.service: Succeeded.
Feb 12 11:34:16 homebridge-raspi systemd[1]: Stopped Node.js HomeKit Server.
Feb 12 11:34:16 homebridge-raspi systemd[1]: homebridge-nest.service: Found left-over process 590 (homebridge-conf) in control group while starting unit. Ignoring.
Feb 12 11:34:16 homebridge-raspi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 12 11:34:16 homebridge-raspi systemd[1]: Starting Node.js HomeKit Server...
Feb 12 11:34:16 homebridge-raspi systemd[1]: Started Node.js HomeKit Server.
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Loaded config.json with 0 accessories and 2 platforms.
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] ---
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Loaded plugin: homebridge-config-ui-x
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Registering platform 'homebridge-config-ui-x.config'
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] ---
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Loaded plugin: homebridge-nest
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Registering platform 'homebridge-nest.Nest'
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] ---
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Loading 2 platforms...
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] [Config] Initializing config platform...
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] [Config] Spawning homebridge-config-ui-x with PID 7630
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] [Nest] Initializing Nest platform...
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] [Nest] Fetching Nest devices.
Feb 12 11:34:17 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:17] Loading 0 accessories...
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Nest] initing protect "Living Room": deviceId: xxxxxxxxx structureId: xxxxxxxxxxxxxxxxxxxxxxxx
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Nest] initing protect "Bedroom": deviceId: xxxxxxxxx structureId: xxxxxxxxxxxx
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Nest] initing protect "Kitchen": deviceId: xxxxxxxxx structureId: xxxxxxxx
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Nest] Initializing platform accessory 'Living Room'...
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Nest] Initializing platform accessory 'Bedroom'...
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Nest] Initializing platform accessory 'Kitchen'...
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: Setup Payload:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: X-HM://0023ISYZXD7ME
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:     ┌────────────┐
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:     │ 031-47-281 │
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:     └────────────┘
Feb 12 11:34:20 homebridge-raspi homebridge[7582]:
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] [Config] Homebridge Config UI X v4.10.1 is listening on :: port 8083
Feb 12 11:34:20 homebridge-raspi homebridge[7582]: [2/12/2020, 11:34:20] Homebridge is running on port 51828.

... and here the config part:

    "platform": "config",
    "name": "Config",
    "port": 8083,
    "temp": "/sys/class/thermal/thermal_zone0/temp",
    "restart": "sudo systemctl restart homebridge-nest",
    "log": {
      "method": "systemd",
      "service": "homebridge-nest"

thx, Richard

**Comment by oznu** [comment]
Ok that all looks fine.

The UI will terminate itself immediately after the Homebridge process exits; but systemd is probably checking before this happens hence the warning.

You can safely ignore this warning. The logs confirm the UI is terminating correctly as it spawns and binds to port 8083 after the restart - if the UI process was still running you would get a port in use error.

**Comment by oznu** [comment]
If this really bugs you, you can tell the UI to run in the same Node.js process as Homebridge using this config option:

https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#nofork

I would not recommend this however.

**Comment by roe1974** [comment]
ok thx !!
i just wanted to know where this log entry comes from ;)
Richard
