### ISSUE TITLE
Devices twice in the device overview

### ISSUE THREAD

**Issue by Spy-1** [oznu/homebridge-config-ui-x#539]
I have several devices twice in the device overview.
I have ony one instance!
Is it possible to delete all devices and rescan them?

**Comment by oznu** [comment]
The accessories are discovered on demand each time the tab loads.

Can you pick one of your duplicate accessories and click the "cog" icon (shown when hovering over the accessory) and show the results from BOTH as a screenshot here?

**Comment by Spy-1** [comment]
Hi oznu,

 

The problem is solved!

I had installed a second Pi which was set to the same port. I changed that and the duplicates disappeared.

Sorry for the effort!

 

Von: oznu <notifications@github.com> 
Gesendet: Mittwoch, 12. Februar 2020 22:20
An: oznu/homebridge-config-ui-x <homebridge-config-ui-x@noreply.github.com>
Cc: Spy-1 <info@brittnacher.com>; Author <author@noreply.github.com>
Betreff: Re: [oznu/homebridge-config-ui-x] Devices twice in the device overview (#539)

 

The accessories are discovered on demand each time the tab loads.

Can you pick one of your duplicate accessories and click the "cog" icon (shown when hovering over the accessory) and show the results from BOTH as a screenshot here?

**Comment by oznu** [comment]
Glad you got it sorted.
