### ISSUE TITLE
Top expanded menu on small mobile screen

### ISSUE THREAD

**Issue by Caribsky** [oznu/homebridge-config-ui-x#540]
**Describe The Bug:**

**A part of menu is not accessible on mobile devices with small screen.**

**Screenshots:**

![ui-x_mobile_menu_bug](https://user-images.githubusercontent.com/37780308/74429361-3d4f4700-4e74-11ea-9206-a8f89e836ac2.png)

**[solution] change order of `<ul>` tags**

![ui_x_menu_code](https://user-images.githubusercontent.com/37780308/74430067-94095080-4e75-11ea-8f3b-7c318c12a00d.png)

**[result]**

![ui-x_mobile_menu_fix](https://user-images.githubusercontent.com/37780308/74430085-9cfa2200-4e75-11ea-9080-333110b1e257.png)

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
Thanks, on smaller screens the menu will now start at the top of the screen.

**Comment by Caribsky** [comment]
please add a close button, it's hard to close this menu now. 
thanks
