### ISSUE TITLE
Feature Request: More json files configurable

### ISSUE THREAD

**Issue by snowdd1** [oznu/homebridge-config-ui-x#541]
**Is your feature request related to a problem? Please describe:**
As the author of a homebridge platform plugin that uses separated, very large JSON files I would like to have the opportunity to specify multiple configuration files that are editable like homebridge's native config.json

**Describe the solution you'd like:**
Have one or multiple sections in the config.json for the hombridge-config-ui-x to add additional json file entries.

**Describe alternatives you've considered:**
A switch to make all JSON files in the homebridge directory editable.

**Additional context:**
The KNX platform requires a lot of configuration, as it does not support auto discovery and the like (it is after all, a protocol from the 1980s). So I needed to separate the configuration file from the config.json to keep it manageable. A lot of people have more than 100 KNX devices and are even running multiple homebridge instances to avoid the 99 devices limit. 
The plugin writes back the generated UUIDs into the file on startup, so config-ui-x must not keep a write lock on them. It is safe to modify the file after startup of the plugin, but it will be read on next startup only.
The configuration file is standard JSON, supporting all accessories and services available to homekit.
See here for doc: https://github.com/snowdd1/homebridge-knx/blob/master/knx_config.json.md
and here for a simple sample: https://github.com/snowdd1/homebridge-knx/blob/master/knx_config.json

**Comment by snowdd1** [comment]
Anybody else interested in additional JSON files?

**Comment by Luehrsen** [comment]
Well, yes. I would be highly interested.

**Comment by Cocco17** [comment]
+1  Would be great to be able to configure json files from the UI!

**Comment by martijndierckx** [comment]
Yes!

**Comment by UliSchirm** [comment]
Would be great!

**Comment by awahlig** [comment]
I concur. I just started using homebridge-knx and this would be very helpful while I slowly add all the devices.
