### ISSUE TITLE
Homebridge Status Widget bug when plugin update available

### ISSUE THREAD

**Issue by mtressl** [oznu/homebridge-config-ui-x#542]
**Describe The Bug:**
The Status widget first shows the three areas version /port /plugins, and after a couple of seconds the plugins disappear when there is a plugin update available.

**To Reproduce:**
Widget in Status page, plugin available.

**Expected behavior:**
Plugin update-count should increase to 1, not disappear

**Screenshots:**
![image](https://user-images.githubusercontent.com/1140154/74535654-92ec2800-4f36-11ea-911d-aeb2ca1147e3.png)

**Environment:**
![image](https://user-images.githubusercontent.com/1140154/74535721-badb8b80-4f36-11ea-9340-6081212ad18d.png)

**Comment by oznu** [comment]
This is due to the widget being resized to small. This widget allows you to have the items in a row or a column, but you need to give it a little extra space.

I've made the middle option a little shorter in the next release, so this should be less likely to occure.
