### ISSUE TITLE
Updates from terminal not reflected in Homebridge-config-ui-x

### ISSUE THREAD

**Issue by rjblake** [oznu/homebridge-config-ui-x#546]
**Describe The Bug:**
Updated homebridge-edomoticz from command line in terminal (sudo -E -n npm install homebridge-edomoticz@latest), which completed successfully (to v2.1.34). UI in Homebridge-config-ui-x still showed as update needed and earlier version. Restarted (pm2 stop homebridge, pm2 start homebridge) and version still showing earlier version v2.1.22. Ran update again from web interface and completed with corrected version

**To Reproduce:**
Updated homebridge-edomoticz from command line in terminal (sudo -E -n npm install homebridge-edomoticz@latest), which completed successfully (to v2.1.34). UI in Homebridge-config-ui-x still showed as update needed and earlier version. Restarted (pm2 stop homebridge, pm2 start homebridge) and version still showing earlier version v2.1.22. Ran update again from web interface and completed with corrected version

**Expected behavior:**
Web UI shows the currently installed version of the plugin (seems to be getting this from somewhere else)

**Environment:**

* **Node.js Version**: v11.3.0
* **NPM Version**: 6.4.1
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: v4.10.1
* **Operating System**: Raspbian 
* **Process Supervisor**: pm2

**Comment by oznu** [comment]
Hi @rjblake,

Can you provide the logs. From homebridge startup.

**Comment by oznu** [comment]
If installing from the terminal manually make sure you add the `-g` flag.

```
sudo npm -g install homebridge-edomoticz@latest
```

See Option 2 of the plugin's guide: https://www.npmjs.com/package/homebridge-edomoticz#installation
