### ISSUE TITLE
Port not showing in Homebridge Widget

### ISSUE THREAD

**Issue by Spy-1** [oznu/homebridge-config-ui-x#558]
Port is not diplayed in Homebridge Widget.
![Port not showing](https://user-images.githubusercontent.com/44490104/75111099-7fc41100-5636-11ea-8735-43334c78e1a1.jpg)

**Comment by oznu** [comment]
I removed this intentionally to compress how much space this row utilises, it wasn't the sort of thing that people need to know on a dashboard; and it's one click away when you view the config anyway.

If the grey text that should translate as "running" doesn't make sense anymore in your language, please feel free to change it:

https://github.com/oznu/homebridge-config-ui-x/tree/master/ui/src/i18n

**Comment by kennymc-c** [comment]
@oznu Already created a pull request for this in de.json a few days ago

**Comment by oznu** [comment]
Thanks @kennymc-c, I'll merge that before this weeks release.
