### ISSUE TITLE
[Feature Request] HTTP API

### ISSUE THREAD

**Issue by iShift** [oznu/homebridge-config-ui-x#56]
Make http api for toggle accessory state

**Comment by oznu** [comment]
Hi @iShift,

Once homebridge is running in insecure mode it exposes it's own http api that you can use to control accessories.

Get list of accessories:

```http
GET http://localhost:51826/accessories
``` 

Set accessory characteristic value, (e.g. turn on the light):

```http
PUT http://localhost:51826/characteristics
Authorization: 031-45-154
{
  "characteristics": [
    {
      "aid": 2,
      "iid": 13,
      "value": 35
    }
  ]
}
```

Some accessory types won't update their values unless asked, you can tell Homebridge to ask the accessory for an update like this:

```http
GET http://localhost:51826/characteristics?id=2.13,2.12
```

Where the format of the `id` is: `aid`.`iid` - comma separated if you want to query multiple values at the same time.

The full documentation is available in the HomeKit specification documents from Apple:

https://developer.apple.com/homekit/specification/

---

The user interface for this plugin uses this API in a pretty raw form. When you click on a switch for example, the only data that gets sent back to the server component of this plugin is:

```json
{"accessories":{"set":{"aid":4,"siid":8,"iid":10,"value":true}}}
```
