### ISSUE TITLE
Compact Mode Features

### ISSUE THREAD

**Issue by donavanbecker** [oznu/homebridge-config-ui-x#560]
**Is your feature request related to a problem? Please describe:**

It would be nice to have the option to enable or disable each widget for compact mode
![0A2EF671-DE18-4171-940F-C1368D3FD563](https://user-images.githubusercontent.com/9875439/75312207-d8ee9900-581e-11ea-90a6-4dede7283d7d.jpeg)

**Describe the solution you'd like:**

I would like to see a setting that you can either enable or disable a widget from showing up in compact mode.

**Describe alternatives you've considered:**

Being able to customize the compact mode

**Additional context:**

None Right now.

**Comment by oznu** [comment]
This should land in next weeks release. It also enables the ability to to show the terminal/logs widget in mobile view as well.

**Comment by donavanbecker** [comment]
Awesome! Thanks @oznu!!!!
