### ISSUE TITLE
Homebridge-config-Uni-x.service

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#566]
@oznu 

after install hb-service the created Homebridge-config-ui-x.service contain default user “homebridge”

[Unit]
Description=Homebridge Config UI X
After=syslog.target network-online.target

```
[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge-config-ui-x $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target
```

for me it is not true, I do not use this user, how to change? If I change it manually after every reinstall the user changed.

**Comment by oznu** [comment]
Hi @grzegorz914,

If you've setup Homebridge using `hb-service` there is no need to use "standalone" mode which is what the `homebridge-config-ui-x.service` systemd service file is used for.

`hb-service` replaces the need for standalone mode and uses `homebridge.service` by default.

You can remove the `homebridge-config-ui-x.service` using these commands:

```
systemctl stop homebridge-config-ui-x
systemctl disable homebridge-config-ui-x
rm -rf /etc/systemd/system/homebridge-config-ui-x.service
systemctl daemon-reload
```

I hope this answers your question? 

Standalone mode still works, but should not be used in conjunction with `hb-service`. I need to update the wiki page for standalone directing people to use `hb-service` instead.

**Comment by oznu** [comment]
Added a note to the top of the standalone mode wiki page: https://github.com/oznu/homebridge-config-ui-x/wiki/Standalone-Mode
