### ISSUE TITLE
Running Plugin Under Insecure Mode (systemd)

### ISSUE THREAD

**Issue by mrtekkid** [oznu/homebridge-config-ui-x#57]
Hello, I setup homebridge to launch on ubuntu on boot in my virtual box machine using scripting referenced here - https://github.com/nfarina/homebridge/wiki/Running-Homebridge-on-a-Raspberry-Pi#running-homebridge-on-bootup

It works fine in this setup however I am curious with the browser based accessory control you have to launch Homebridge using the -i flag. How do you do that with a systemd set up? 

thanks!

**Comment by oznu** [comment]
Hi @mrtekkid,

Please see https://github.com/oznu/homebridge-config-ui-x/issues/37#issuecomment-368417328

**Comment by mrtekkid** [comment]
This was fantastic

Thank you!

**Comment by Itsmmai** [comment]
Hi Oznu, is there a env settings I can you to switch on/off insecure mode (I use a docker under synology)

**Comment by oznu** [comment]
There is:

https://github.com/oznu/docker-homebridge/blob/master/README.md#optional-settings

**Comment by mientki** [comment]
very nice. I am waiting for an update :)

**Comment by johhiq** [comment]
Hi! As ref to above: Is this correct: 
HOMEBRIDGE_OPTS=-U /var/lib/homebridge -I
Can't get that to work. First tried to change -U to -I but then Homebridge fails to start, but with the above - at least it starts. 
Thanks.
