### ISSUE TITLE
Compact Mode Organizing

### ISSUE THREAD

**Issue by donavanbecker** [oznu/homebridge-config-ui-x#570]
**Is your feature request related to a problem? Please describe:**

Going off of Issue #560, is there anyway that you can add option for sequence number. so they can be displayed in a different order? Similar to my mock up drawing.

<img width="513" alt="Screen Shot 2020-02-28 at 3 22 37 PM" src="https://user-images.githubusercontent.com/9875439/75588638-b1761700-5a3e-11ea-865c-e0fd2056166e.png">

**Describe the solution you'd like:**

I would like to be able to change the sequence of the widgets on the compact mode so that I can have them show up high or lower in the sequence.

**Describe alternatives you've considered:**

Being about to move the widgets and then lock them on compact mode.

**Additional context:**

None

**Comment by oznu** [comment]
If you're feeling adventurous you can edit the  `mobileOrder` in `~/.homebridge/.uix-dashboard.json`.

**Comment by donavanbecker** [comment]
@oznu i will try it out.

**Comment by donavanbecker** [comment]
@oznu tried changing the order and assigned 1 through 9 and the mobile order never stuck. restarted homebridge and it kept the `HomebridgeStatusWidgetComponent` at the top.

```
[{"x":5,"y":0,"component":"HomebridgeStatusWidgetComponent","cols":9,"rows":4,"mobileOrder":10,"hidePort":false},{"x":17,"y":0,"component":"WeatherWidgetComponent","cols":3,"rows":4,"mobileOrder":20,"hideOnMobile":false,"location":{"id":5690366,"name":"Mandan","country":"US","coord":{"lat":46.8264,"lon":-100.8897}}},{"x":14,"y":0,"component":"ClockWidgetComponent","cols":3,"rows":4,"mobileOrder":23,"hideOnMobile":true,"timeFormat":"h:mm a","dateFormat":"EEEE, MMMM d, y"},{"x":14,"y":7,"component":"AccessoriesWidgetComponent","cols":6,"rows":12,"mobileOrder":9,"hideOnMobile":false,"accessoryOrder":["393605692a804216f2b3481bdf243dd6cfd56a4ebcab7f9adee51236a6f9bd70","f60b98562ffbd26037772fceca3ab6d94a8b83df30900145c051b91d6e57b13a","6453d3df850fdc2df879f061c4528f94752a77874c149d9a72f2bf1965fbb631","996f2b29878f0713408dfc2620b09f4516aebb69603be0e18cb411b93dd47132","a21b1227268effa70539b3d25f5b4ed92753c87908c5fa1e6aed43a122ec01e2","09d3dccf04324f200907517d90af82d4476d8dc111ab565346400283441b1ac8","39725b728dd4e1c55d5706bc47cbdddb088a0a53ac7b67c5056052ba354f7293"]},{"x":5,"y":4,"component":"CpuWidgetComponent","cols":5,"rows":3,"mobileOrder":40},{"x":10,"y":4,"component":"MemoryWidgetComponent","cols":5,"rows":3,"mobileOrder":50},{"x":15,"y":4,"component":"UptimeWidgetComponent","cols":5,"rows":3,"mobileOrder":60,"hideOnMobile":false},{"x":0,"y":9,"component":"SystemInfoWidgetComponent","cols":5,"rows":10,"mobileOrder":70,"hideOnMobile":true},{"x":0,"y":0,"component":"HapQrcodeWidgetComponent","cols":5,"rows":9,"mobileOrder":100,"hideOnMobile":true},{"x":5,"y":7,"component":"HomebridgeLogsWidgetComponent","cols":9,"rows":12,"mobileOrder":1000,"hideOnMobile":true,"fontWeight":"400","fontSize":15}]
```

**Comment by donavanbecker** [comment]
I had it set from 1 to 9 and that didn't stick.
