### ISSUE TITLE
Config Editor select on touch devices

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#574]
@oznu 

On all Apple touch devices in config editor is not possible to select anything.
After long press we get menu options, after 2press the text is selected but cannot marked selected area.

P.S. - also move the accessory tile is not possible, after long press moved tile with complete screen or open submenu from tile.

https://vimeo.com/394744338

**Comment by Staubgeborener** [comment]
I get different results with different devices. What exact devices do you use?

I can select and edit my config.json in config editor with all my apple devices. No problem at all.

But yeah moving tiles (which don't have options at long press like temperature or light color, etc) is possible. Moving tiles (_with_ options) is not possible. With a single press i'll get the option menu, also with a long press. I can move the tile with a long press but like in you're video i'ts not possible to move it around. And also there is an option menu in the foreground. All in all moving tiles (no matter with or without option menu) seems to be buggy on apple devices - maybe on all mobile devices.

Test with: iPhone Xs, iOS 13.3.1 and iPad 2017, iPadOS 13.3.1.

**Comment by grzegorz914** [comment]
I use iPad Pro 11” 2018.
Yes moving tile like Thermostat or Volume is quit problematic. Can U test moving tile from Top to Bottom and Bottom to Top?

Maybe U can add lock mechanism for tile with submenu if accessories are in moving unlock mode.

Regarding config editor all working OK except select and marked some area, this is not possible at all in my iPad.

**Comment by Staubgeborener** [comment]
Moving stuff from top to bottom and vice versa is working. But i got you‘re idea: the screen moves/is scrolling, which is quite annoying. This could be problematic.

**Comment by oznu** [comment]
I no longer have an iPad to test on.

The config editor should really revert to a basic text box on mobile - the iPad Pro's desktop mode prevents this behaviour.

Do you experience the same select issue using the monaco editor here:

https://microsoft.github.io/monaco-editor/

**Comment by grzegorz914** [comment]
Yes, the same select issue on this page.
