### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by marcgrc** [oznu/homebridge-config-ui-x#579]
Hi
what should I do to have a backup from the graphical interface config-ui-x ?
Thank you

**Comment by Staubgeborener** [comment]
Update to [version 4.11.0](https://github.com/oznu/homebridge-config-ui-x/blob/master/CHANGELOG.md#4110-2020-02-27), go to the main panel and click `...` in the upper right corner. You should see `Backup / Restore`.

**Comment by oznu** [comment]
Thanks @Staubgeborener.

![image](https://user-images.githubusercontent.com/3979615/75972439-8e100800-5f27-11ea-8b08-f1d930c0b3e6.png)
