### ISSUE TITLE
iOS Chrome login not working

### ISSUE THREAD

**Issue by pax0707** [oznu/homebridge-config-ui-x#58]
iOS Chrome 65 web login doesn't respond to either keyboard return or login button press.
WOrks fine in safari.

**Comment by oznu** [comment]
I cannot replicate this on iOS Chrome 65.0.3325.152.

**Comment by pax0707** [comment]
Just realized I was using my work phone that's on 11.3 beta...
Private one that's on 11.2 works fine.

**Comment by oznu** [comment]
Thanks @pax0707, once 11.3 is out I'll ensure it's still working / fix if required.
