### ISSUE TITLE
Support for Google account credentials

### ISSUE THREAD

**Issue by EjvindHald** [oznu/homebridge-config-ui-x#582]
In https://www.npmjs.com/package/homebridge-gsh you have made a very nice interface for linking to Google Account.

Would it possible to somehow add this functionality to https://www.npmjs.com/package/homebridge-nest ? I cannot use this binding, because I cannot find the Google account credentials.

Thank you very much for this UI for Homebridge.

**Comment by oznu** [comment]
Hi @EjvindHald,

Thanks for using `homebridge-gsh` and the email you sent earlier. Unfortunately there are some differences between the nest auth and the `homebridge-gsh` auth that made this imposible to do from a web page running in a browser.

In the case of `homebridge-gsh`linking the Google OAUTH flow is controlled by me, so I can allow the token to be sent back to the `homebridge-config-ui-x`. Google does not allow this for their Nest accounts.

It's also not possible for another website to intercept the tokens / cookies required for obvious reasons.

It might be possible to create a Google Chrome extension that handles this, as they can intercept requests. This is something I'll leave to the `homebridge-nest` authors to take care of though.
