### ISSUE TITLE
error updating/installing package

### ISSUE THREAD

**Issue by Catta1997** [oznu/homebridge-config-ui-x#587]
the command "sudo -E -n npm install homebridge-plex-sensors@latest" give me error, is possible to convert in to "sudo npm install -g homebridge-plex-sensors@latest"? 
the command give me error with all packages

**Comment by oznu** [comment]
Hi @Catta1997,

Can you fill in the issue template so I can assist you with this.

**Comment by Catta1997** [comment]
**Describe Your Problem:**
the command "sudo -E -n npm install homebridge-plex-sensors@latest" give me error, is possible to convert in to "sudo npm install -g homebridge-plex-sensors@latest"?
the command give me error with all packages

**Logs:**
with: "sudo -E -n npm uninstall homebridge-plex-sensors"

CMD: sudo -E -n npm uninstall homebridge-plex-sensors

sudo: impossibile inviare il messaggio di audit: Operazione non permessa
npm WARN enoent ENOENT: no such file or directory, open '/home/plex/.npm-global/lib/package.json'
npm WARN lib No description
npm WARN lib No repository field.
npm WARN lib No README data
npm WARN lib No license field.

npm ERR! code EPERM
npm ERR! syscall lchown
npm ERR! path /home/plex/.npm/_locks/staging-02cd207849a1b32d.lock
npm ERR! errno -1
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 0:0 "/home/plex/.npm"

Command failed. Please review log for details.

with "sudo npm uninstall -g homebridge-plex-sensors"

removed 1 package in 0.385s


I have try "sudo chown -R 0:0 "/home/plex/.npm"" but no success

**Environment:**

* **Node.js Version**: <v12.16.1>
* **NPM Version**: <6.13.4>
* **Homebridge Version**: <0.4.50>
* **Homebridge Config UI X Version**:
* **Operating System**: Ubuntu
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
Are you running homebridge as the "plex" user?

**Comment by Catta1997** [comment]
yes, I have problem if I run it as "homebridge"

**Comment by oznu** [comment]
Run this to fix permissions:

```
chown -R plex: /home/plex/.npm
chown -R plex: /home/plex/.npm-global
```

Then disable `sudo` mode in the Homebridge UI Config.

Restart the homebridge / ui service and try again.

**Comment by oznu** [comment]
To make the logs work after disabling sudo mode, you may need to add the `plex` user to the `systemd-journal` group:

```
sudo usermod -a -G systemd-journal plex
```

**Comment by Catta1997** [comment]
thanks!
