### ISSUE TITLE
Showdown after a while

### ISSUE THREAD

**Issue by Donni1966** [oznu/homebridge-config-ui-x#589]
**Describe The Bug:**
i start the homebrigde and all is fine for some hours. than the hombebridge shutting down with the entry in the log
**To Reproduce:**

restart, wait ... it happens last two days more than 10 times
**Logs:**

<--- Last few GCs --->

[22718:0x3ec4988] 13995911 ms: Scavenge 133.0 (140.6) -> 133.0 (140.6) MB, 7.2 / 0.0 ms  (average mu = 0.982, current mu = 0.795) allocation failure 
[22718:0x3ec4988] 13996498 ms: Mark-sweep 133.0 (140.6) -> 124.2 (134.8) MB, 587.4 / 0.1 ms  (average mu = 0.994, current mu = 0.996) last resort GC in old space requested
[22718:0x3ec4988] 13997327 ms: Mark-sweep 124.2 (134.8) -> 124.2 (128.8) MB, 828.9 / 0.1 ms  (average mu = 0.984, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xe0d11c]
Security context: 0x2044e40d <JSObject>
    1: toString [0x27307cb1] [buffer.js:~761] [pc=0x51db5364](this=0x376e9065 <Uint8Array map = 0x5ca144a1>,0x21e0027d <undefined>,0x21e0027d <undefined>,0x21e0027d <undefined>)
    2: arguments adaptor frame: 1->3
    3: /* anonymous */ [0x3852ac65] [/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/request/request.js:1128] [bytecode=0x386cf3a1 offset=1...

[16/03/2020, 20:57:03] Got SIGTERM, shutting down Homebridge...

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**
 {
            "accessoryControl": {
                "debug": false
            },
            "auth": "none",
            "log": {
                "method": "file",
                "path": "/var/log/homebridge.log"
            },
            "name": "ConfigPi3",
            "platform": "config",
            "port": 8181,
            "restart": "sudo systemctl restart homebridge",
            "sudo": true,
            "tempUnits": "c",
            "theme": "dark-mode"
        },

**Environment:**

Node.js Version | v13.8.0
-- | --
v6.14.2
root
/root/.homebridge
/root/.homebridge/config.j

* **Node.js Version**: <v13.8.0>
* **NPM Version**: <v6.14.2>
* **Homebridge Version**: <0.45.2>
* **Homebridge Config UI  last**:
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by Staubgeborener** [comment]
Its not a problem with homebridge itself, but with your _local_ homebridge installation (Node.js). It seems, that you have to allocate more memory, 'cause your buffer is full (or better just reinstall homebridge). What raspberry pi do you use?

Maybe a quick and dirty way:
There is always the possibility to set the `NODE_OPTIONS="--max-old-space-size=4096"` ENV variable, which should propagate to all `node` processes that are launched. That does have the drawback, though, of propagating to all `node` processes launched, whether intentionally or not.

_Originally posted by @bridzius in https://github.com/nrwl/nx/issues/1110#issuecomment-467575016_

**Comment by Donni1966** [comment]
Yesterday is installed hombre version .53 and reinstall HB completely. And i update UX-I to the last version. 
it seems to work. Wait now. 

one question: The Set of the NODE Options. Is this permanent? Or have so do after every restart again?  Don´t found infos ... i read there is on json file to put it in, but not what file oder where it is placed

thanx - and by the way - you do a good job. Give you some bugs on PayPal :-)

**Comment by Staubgeborener** [comment]
Changing the environment variable should be permanent. But there should also be a temporary option.

btw any thanks (and donations ツ) to this code should go to @oznu.

**Comment by Donni1966** [comment]
;-) still done last week i remember. Thanks  a lot.
