### ISSUE TITLE
Plugins page fails to load when plugins do not have descriptions

### ISSUE THREAD

**Issue by KaidenR** [oznu/homebridge-config-ui-x#59]
A couple plugins I have installed do not have descriptions in their `package.json` files. That causes this line to throw a null pointer when loading the plugins page:
https://github.com/oznu/homebridge-config-ui-x/blob/master/src/pm.ts#L240

**Comment by oznu** [comment]
@KaidenR, thanks for reporting this. Should be an easy fix.

**Comment by oznu** [comment]
I must have fixed it when searching the registry already:

https://github.com/oznu/homebridge-config-ui-x/blob/master/src/pm.ts#L311-L312

**Comment by oznu** [comment]
This will be fixed in the next release which I will publish later tonight.

**Comment by KaidenR** [comment]
Awesome! Thanks for the quick turnaround!
