### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by moguennouni** [oznu/homebridge-config-ui-x#590]
Hello,
I don’t know if it is possible a would like access to my homebridge ui config remotely from the internet, I tried to open some ports on my rooter but no success
Can you please help ( if possible to do that)
Thank you

**Comment by Staubgeborener** [comment]
Sure, it's possible, you just have to create a VPN. You will need to open port 80 (https) or 443 (https) in your router settings. Also you have to create a VPN access. Depends on your router how to do it. Here an [example](https://en.avm.de/service/fritzbox/fritzbox-7490/knowledge-base/publication/show/49_Setting-up-a-VPN-connection-to-FRITZ-Box-in-Windows-FRITZ-VPN/) of how it works on the FRITZ!Box 7490. It is recommended to have a static IP from your provider or a domain for DynDNS. If everything is set up, you can log in to your vpn remotely with a client and call up your homebridge in the browser (as before `homebridge-ip:port`, so everything as usual).

**Comment by moguennouni** [comment]
Thank you for your help, I will check all of that.
