### ISSUE TITLE
Switch from PM2 to service mode

### ISSUE THREAD

**Issue by jnanes** [oznu/homebridge-config-ui-x#592]
Hello,

I am trying to switch from pm2 to service mode for Homebridge startup.

I tried to pass the path during install so that all my acccessories/plugins came over but I could not get it to work properly. Can you assist?

My current homebridge path is /home/jesse/.homebridge

**Comment by oznu** [comment]
Run these commands

```
sudo hb-service uninstall
sudo mkdir -p /var/lib
sudo cp -R /home/jesse/.homebridge /var/lib/homebridge
sudo hb-service install --user homebridge
```

Assuming you had somewhat of a valid config in your original install, it should set everything else up for you with your existing config/HomeKit connection (no need to repair).

Also make sure you stop and disable the homebridge service running in pm2.
