### ISSUE TITLE
multi instance UI

### ISSUE THREAD

**Issue by lukasa1993** [oznu/homebridge-config-ui-x#593]
is there a way to have multi instance in 1 UI ?

**Comment by oznu** [comment]
There is not currently. It would require a major reworking of how the backend handles sessions.

**Comment by lukasa1993** [comment]
so you guys just separate them with ports and just go 1 by 1? like for 20+ devices it will be very tidius.

any other idea how to manage it ?

**Comment by oznu** [comment]
Most people would run their plugins in one instance of Homebridge.

**Comment by lukasa1993** [comment]
well i did but, when i fails all hangs

**Comment by oznu** [comment]
Isolating the problem-causing plugin and keeping that one seperate to the rest is probably the way to do. If your running the same plugin across multiple instances to get an accessory-per-instance then I'd raise an issue with the developer of the plugin about it taking down all of Homebridge when one device is not responding.

**Comment by lukasa1993** [comment]
its not just plugin, like sometimes hardware is not running of for 1 device and all homebridge hangs at that point

**Comment by oznu** [comment]
The plugin should handle that senario, I've found the trick is to never return an error in the `callback()` as that is a quick way for HomeKit to reject the entire bridge and all attached accessories until a restart happens. 

Log the error, and update the characteristic back to "off" or whatever makes sense for the accessory type.

**Comment by lukasa1993** [comment]
hmm, so you suggest to have very small http timeout so it doesn't halt others and dont report error back to homekit ?

**Comment by oznu** [comment]
Yep. In my plugins I don't even wait for the network request to finish before saying "it's done" to HomeKit. That may not be suitable for your own requirements, but I generally notice when the command I issued didn't work so can go look what's wrong.

**Comment by oznu** [comment]
When it comes to getting the current status of a plugin via `.on('get')...` caching the current status in the plugin is a great way to make the Home app very responsive. Alternatively you can doaway with the `.on('get')...` calls all together and "push" them when they change using `updateCharacteristic`.

**Comment by lukasa1993** [comment]
but how will i know which one is malfunctioning after that ?

**Comment by oznu** [comment]
I guess that depends on if the accessory is something where you notice the action happening in your physical environment. In that case you can write to the homebridge log a detailed enough error that explains which accessory had what problem.

**Comment by lukasa1993** [comment]
no i wound't get it in physical enviroment

**Comment by lukasa1993** [comment]
performance with multi instance are way way better like its the best, i still think unified UI would be great for this
