### ISSUE TITLE
Apache reverse proxy sub directory 

### ISSUE THREAD

**Issue by tumekee** [oznu/homebridge-config-ui-x#594]
Hi im having difficulty  adding a sub directory or location to the template provided. the template without any modification works perfectly so thank you ! BUT i am wanting to make it work on a sub directory / location - as soon as i do that  just get a blank page in my browser :( iv googled everything i can think of  and no result . any ideas ? probably obvious....

        <Location />
            ProxyPass http://localhost:8080/
            ProxyPassReverse http://localhost:8080/
            RewriteEngine on
            RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
            RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
            RewriteRule .* ws://localhost:8080%{REQUEST_URI} [P]
        </Location>

to 
        <Location /home/>
            ProxyPass http://localhost:8080/
            ProxyPassReverse http://localhost:8080/
            RewriteEngine on
            RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
            RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
            RewriteRule .* ws://localhost:8080%{REQUEST_URI} [P]
        </Location>

Ubuntu Server 18.4

**Comment by oznu** [comment]
Hi @tumekee,

Sub-directories/non-root paths are not supported currently.

**Comment by tumekee** [comment]
that would make a lot of sense ! cheers :)

**Comment by forsethc** [comment]
Are there any plans to support this in the future?

**Comment by jannnfe** [comment]
Is there anything planed in the future?
