### ISSUE TITLE
OS Version Update Indication

### ISSUE THREAD

**Issue by mitch7391** [oznu/homebridge-config-ui-x#595]
**Describe the solution you'd like:**
Hey @oznu I was wondering what your thoughts were on adding the OS indication to show more detail on the version number (e.g 10.X). Also I was wondering if it could have have the hover-over indication (!) that Node.js and NPM versions have? Currently I have no way of knowing if my RPi has updates without just running the commands. I understand other people use other platforms to run Homebridge so maybe it’s not entirely possible. Thanks :)

**Comment by mitch7391** [comment]
Hey @oznu what are your thoughts on this one?

**Comment by oznu** [comment]
Probably not. I'm wanting to limit the use of "sudo" and make it as cross platform compatible as possible.

Thanks for the suggestion though.
