### ISSUE TITLE
Setting sessiontimeout to not time out

### ISSUE THREAD

**Issue by chromusphil** [oznu/homebridge-config-ui-x#596]
**Describe Your Problem:**
I want to set the sessiontimeout to be either crazy long or preferably NOT time out. 
 

Do I set it to 0 (which I have tried but still times out) or is there a "no" or do I need to add a bunch of 0's to the end of the 8 hour value?

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
{
            "name": "Config",
            "port": 8000,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "sessionTimeout": 2880000,
            "platform": "config"
        }

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: latest 
* **NPM Version**: latest
* **Homebridge Version**: 0.4.53
* **Homebridge Config UI X Version**: 4.13.2
* **Operating System**: Raspbian 
* **Process Supervisor**: Dhb-service

**Comment by oznu** [comment]
You can set it to `9007199254740990` which is the longest timeout possible.

**Comment by chromusphil** [comment]
That was amazingly fast -> done the change thanks.

**Comment by oznu** [comment]
You probably want to change that to something like `900719925` actually. The really large number seems to break logins.

900719925 is still 28 years.

**Comment by chromusphil** [comment]
Thanks

**Comment by chromusphil** [comment]
I was still able to log in on my Pi/Raspbian setup but I have adjusted to this recommendation
