### ISSUE TITLE
Fantastic plugin, one of the best, how to donate?

### ISSUE THREAD

**Issue by zany92** [oznu/homebridge-config-ui-x#597]
I'm using your code almost everyday, I love it. 
How to donate, I can't find the link. I want to support and thank you for your effort.

**Comment by oznu** [comment]
Hi @zany92,

Thank you for your feedback, I really appreciate it and glad you find this plugin useful.

While I thank you for the offer of a donation, it's not at all necessary 😄. If you still want to show your appreciation in some way, feel free to ⭐️ the project here on GitHub if you haven't already.

**Comment by zany92** [comment]
Oh, thank you that's generous to share your time and skills for all of us. For sure, I will.

**Comment by Olepir** [comment]
I think donation option will be useful for plugin developers.
