### ISSUE TITLE
Homebridge not working on Windows 10 since latest update

### ISSUE THREAD

**Issue by TheHomekitWayFinder** [oznu/homebridge-config-ui-x#600]
I have just updated to the latest version and now homebridge won’t start. I am running hb-service. I am happy to supply anything you need to get this sorted. Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oznu** [comment]
Try running these commands (you won't loose any settings):

```
hb-service uninstall
npm install -g homebridge@latest homebridge-config-ui-x@latest
hb-service install
```

If it's still not working after than, open a new issue and please fill in the issue template including logs etc.
