### ISSUE TITLE
Setting up a HDD Network Drive Alongside Homebridge

### ISSUE THREAD

**Issue by mitch7391** [oznu/homebridge-config-ui-x#602]
**Describe Your Problem:**
Hey @oznu not exactly related to your work, but something I want to use on the same RPi with it; I was wondering if you could provide some advice? 

I have recently stopped using a RPi 4 for LibreElec/Kodi as I upgraded to an Apple TV 4K, however I am still using that RPi solely as a network link to my media on a HDD plugged into it. I have your Homebridge service running on an RPi 3 and want to eliminate the need for two RPis running by running homebridge and a network drive on just the RPi 4. 

I have tried to follow several guides online on how to set up a network access to a HDD plugged into a RPi through Samba (this is what Infuse app on the Apple TV4K seems to prefer connecting to my HDD with) and eventually ended up getting my RPi stuck in emergency mode due to an fstab issue; a bit of googling and I fixed this. After all of this I have not really had a win with setting up my HDD as a network drive. What would be the best way to set this all up? By all means tell me to bug someone else if you are too busy or can't be bothered with a non config-ui-x problem; there will be no hard feelings :)

**Logs:**
N/A

**Homebridge Config:**

N/A

**Screenshots:**
N/A

**Environment:**

* **Node.js Version**: 12.16.1
* **NPM Version**: 6.14.4
* **Homebridge Version**: 0.4.53
* **Homebridge Config UI X Version**: 4.13.3
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Hi @mitch7391,

I am not familiar with setting up Samba shares on Linux sorry so won't be much help. I use NFS locally to achieve the same thing (mounting NFS shares from my NAS to all my VMs) as it's a bit simpler to setup.

**Comment by mitch7391** [comment]
All good :) might post on Reddit or take a look into NFS (if Infuse uses it). Thanks anyway!
