### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by Thlb** [oznu/homebridge-config-ui-x#604]
Hi,

When typing http://myhombridge-config-ui-x.url**/api/**, it display a blank page with "Hello World!".

Is there any url we can access to get some data (system info, cpu usage, homebrigde status, devices ...) in json (or other)

Thanks

**Comment by oznu** [comment]
The system info, cpu usage, homebrigde status methods are done via web sockets rather than regular REST endpoints.

If you use the web inspector you should be able to see the network calls and message frames that make these happen.
