### ISSUE TITLE
Time Zone incorrect

### ISSUE THREAD

**Issue by Finch106** [oznu/homebridge-config-ui-x#606]
Where do I adjust the timezone? The timezone showing on the Status page shows GMT-500, when the system should be in CDT. Typing date in terminal shows correctly: Tue  7 Apr 17:13:31 CDT 2020

**Comment by oznu** [comment]
CDT is -5 isn't it?

**Comment by Finch106** [comment]
Oh no, I’m that stupid. Yes it is CDT-500 and CST-600 and the GMT threw me off. You can close this.

**Comment by rfhayn** [comment]
How do you change the timezone in homebridge-config-ui-x.  the date/time/timezone is correct on the raspberry pi, but the timezone showing in system information is incorrect.
