### ISSUE TITLE
Feature Request - Plugins 

### ISSUE THREAD

**Issue by thechris1992** [oznu/homebridge-config-ui-x#607]
Hey all,

Please add an „installed Version“ Field to the Plugins. 
Then i can see if an update is needed, or not :)

Enough space is there

**Comment by oznu** [comment]
The installed version is shown:

<img width="366" alt="Screen Shot 2020-04-08 at 10 54 46 am" src="https://user-images.githubusercontent.com/3979615/78732954-675e4a80-7987-11ea-9273-db46f92fba8b.png">

The UI will also tell you if an update is available.

**Comment by thechris1992** [comment]
Hello, 

I mean the Version of the Update who is available.
And it would be nice if I can unselect an Plugin from the Update search. 

Best,
Christian
