### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by jamoir** [oznu/homebridge-config-ui-x#610]
**Describe Your Problem:**

After updating home bridge and config to the latest versions I now get a couple of issues I can't resolve. "Checking update" is continually spinning. I get an " Unable To Find Homebridge Installation " bottom right. And none of my plugins appear under the plugins tab. Other than that it works fine.
 
**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```
How do I find these?

**Homebridge Config:**

```json
Show your homebridge config.json here
```
{
    "bridge": {
        "name": "GadgetControl",
        "username": "xxx",
        "port": xxxx,
        "pin": "xxxx"
    },
    "description": "Woodside configuration file",
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo service homebridge restart",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        },
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "expected_accessories": "5",
            "timeout": "60",
            "homekit_safe": "0"
        },
        {
            "platform": "Nest",
            "token": "xxxx"
        },
        {
            "platform": "netatmo",
            "name": "netatmo weather",
            "ttl": 5,
            "auth": {
                "client_id": "xxxx",
                "client_secret": "xxxx",
                "username": "xxxx,
                "password": "xxxx"
            }
        },
        {
            "platform": "ZWayServer",
            "url": "http://192.168.1.252:8083/",
            "login": "admin",
            "password": "xxxxx"
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Hubname",
            "hubIP": "192.168.1.23",
            "publishActivitiesAsIndividualAccessories": false
        }
    ],
    "accessories": [
        {
           
        }
    ]
}

**Screenshots:**

**Environment:**

* **Node.js Version**: 
v11.15.0 
* **NPM Version**: 
v6.7.0 
* **Homebridge Version**: 
0.4.53
* **Homebridge Config UI X Version**:
homebridge-config-ui-x v4.14.0 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
Raspbian
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
Systemd

**Comment by oznu** [comment]
Please provide logs, os and process supervisor details.

**Comment by jamoir** [comment]
Hi, thanks for replying to quickly.  

The OS is Raspbian:

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

Process Supervisor is 'Systemd'

Where do I find the actual log files? I've only ever tailed  /var/log/daemon.log to see what's going on. 

Thanks,
Jamie

**Comment by oznu** [comment]
Can you run these command and provide the output:

```
sudo which homebridge
sudo which homebridge-config-ui-x
sudo which node
```

And those same commands again without sudo, but as the user you run the homebridge process as.

**Comment by jamoir** [comment]
pi@gadgetcontrol:~ $ sudo which homebridge
/usr/bin/homebridge
pi@gadgetcontrol:~ $ sudo which homebridge-config-ui-x
/usr/bin/homebridge-config-ui-x
pi@gadgetcontrol:~ $ sudo which node
/usr/bin/node
pi@gadgetcontrol:~ $ which homebridge
/usr/bin/homebridge
pi@gadgetcontrol:~ $ which homebridge-config-ui-x
/usr/bin/homebridge-config-ui-x
pi@gadgetcontrol:~ $ which node
/usr/bin/node

**Comment by oznu** [comment]
That all looks normal.

Get the logs with this command:

```
sudo journalctl -n 200 -u homebridge
```

Restart homebridge, and produce the error in the UI before running this command.
