### ISSUE TITLE
Reinstall option

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#612]
@oznu 
Sometimes we need to install some plugin again, it will be nice to add next to the “uninstall” option “reinstall” option. Right now we need first uninstall then search and install again.

Thanks

**Comment by oznu** [comment]
This is effectively covered by the "install previous version" feature in the upcoming v4.29.0 - as you can just select the current version and it will re-install.

**Comment by grzegorz914** [comment]
Yes, thanks for this nice improvement.👍
