### ISSUE TITLE
Feature request: Create a backup archive via script

### ISSUE THREAD

**Issue by Zer0x00** [oznu/homebridge-config-ui-x#616]
**Is your feature request related to a problem? Please describe:**

My goal is create and upload a homebridge-config-ui-x compatible backup archive to an other device via Bash / PHP.

**Describe the solution you'd like:**

hb-service could be extended to provide a backup function.

**Describe alternatives you've considered:**

I could use the REST API to obtain a backup archive by:
- POST request to http://192.168.0.100:8080/api/auth/noauth in order to obtain a bearer token
- GET request with the obtained bearer token to http://192.168.0.100:8080/api/backup/download

**Additional context:**

**Comment by Zer0x00** [comment]
(A restore option would be lovely, too!)

**Comment by oznu** [comment]
The backup of the storage directly is pretty straigh forward.

You can just use `tar` to create an archive and use `tar` to restore it (Google the commands).

The main problem is the plugin manifest. Generating this needs the UI running to do everything it does to scan the plugin folders and create a `plugins.json` manifest file which is used by the UI when you restore to know which plugins it should install.

> I could use the REST API to obtain a backup archive by...

This is probably your best option 😄

**Comment by Zer0x00** [comment]
Okay, utilizing the REST API via curl & python (for parsing) was way easier than I thought.

Here's the script in case someone needs it too:

```
#!/bin/bash
echo 'Starting Backup of Homebridge...'

Homebridge_Backup_Path="/tmp/backup/homebridge"

mkdir -p $Homebridge_Backup_Path

access_token=`curl -s -d -v http://localhost:8080/api/auth/noauth | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])"`

(cd $Homebridge_Backup_Path && curl -s -H "Authorization: bearer $access_token" -O -J http://localhost:8080/api/backup/download)

echo -e 'Backup of Homebridge ended.\n'
```

**Comment by jiehanzheng** [comment]
@Zer0x00 works like a charm!  Thanks for sharing this -- this is much better than just backing up the entire config directory, since it allows the backup to be restored on other machines too :)
