### ISSUE TITLE
Allowing setting of temperature config via environment variable

### ISSUE THREAD

**Issue by jamesrodda** [oznu/homebridge-config-ui-x#62]
I'm using homebridge-config-ui-x via docker-homebridge which allows the passing of certain environment variables. A facility to set the "temp" setting (to specify the temperature information path) is missing. Could you add: HOMEBRIDGE_CONFIG_UI_TEMP to allow this?

**Comment by oznu** [comment]
Hi @jamesrodda,

I will include this option in the next release. However, mounting the temp file from the host into the Docker container using a volume won't be an officially supported option of the [oznu/homebridge](https://github.com/oznu/docker-homebridge) docker image.
