### ISSUE TITLE
Latest update causes Raspberry Pi to go offline

### ISSUE THREAD

**Issue by noltondyer** [oznu/homebridge-config-ui-x#622]
The latest update of Homebridge UI caused the Raspberry Pi to crash. I am not very advanced with these services, but I can tinker a bit. I set up the RPi over SSH, but it is not discoverable after this update was pushed through.

**Comment by oznu** [comment]
I'll need logs, environment details, config etc to help out. Everything that was in the issue template 😄

**Comment by noltondyer** [comment]
So it looks like it’s stuck in a loop with starting the Homebridge service. I can access the UI after rebuilding everything and accessing from a different port. This is the error that is being thrown, and it’s on a Raspberry Pi.

![image](https://user-images.githubusercontent.com/35444650/79583049-34f0d380-8092-11ea-92d9-78664f4b4be8.png)

![image](https://user-images.githubusercontent.com/35444650/79583058-38845a80-8092-11ea-9cf2-539f18424be1.png)

**Comment by oznu** [comment]
Can you show your config? I suspect one of the entries under accessories is wrong.

**Comment by noltondyer** [comment]
Here is my confit: sensitive info replaced by Xs. 




{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [
        {
            "name": "Volt",
            "deviceId": "6e17387a-939b-4e39-870a-XXXXXXXXXX",
            "vin": "XXXXXXXXXXXX",
            "username": "XXXXXXXXXX",
            "password": "XXXXXXX",
            "onStarPin": "XXXX",
            "enableAlert": false,
            "enableCharger": true,
            "enableDoors": false,
            "doorsDefaultToUnlocked": false,
            "accessory": "OnStar"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "deep-purple",
            "tempUnits": "f",
            "platform": "config"
        },
        {
            "email": "XXXXXXXXXXXXXXXX",
            "password": "XXXXXXXX",
            "platform": "NeatoVacuumRobot",
            "hidden": [
                "eco",
                "nogolines",
                "extracare",
                "schedule",
                "spot"
            ]
        },
        {
            "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "XXXXXXXXXXXXXXX",
            "password": "XXXXXXXX",
            "country": "US",
            "accessories": [
                {
                    "ip": "XXXXXXX",
                    "displayName": "Dyson",
                    "serialNumber": "VV6-US-XXXXXXXX",
                    "displayFilterLife": "true"
                }
            ]
        }
    ]
}

**Comment by noltondyer** [comment]
My config was working fine before the update, but I guess something could’ve changed. I haven’t touched my config in months and have had 0 down time.

**Comment by noltondyer** [comment]
**UPDATE 

After resetting Homebridge completely via the online UI, and re-adding all of my accessories, everything is back up and running.
