### ISSUE TITLE
How to make hb-service run Homebridge or a specific plugin with sudo?

### ISSUE THREAD

**Issue by nicolasherrbach** [oznu/homebridge-config-ui-x#626]
**Describe Your Problem:**
I'm trying to write a plugin for Homebridge running on Raspberry Pi. This plugin uses the PIGPIO JS wrapper (https://github.com/fivdi/pigpio) which in turn makes use of the PIGPIO C Library, which requires sudo.

When I run Homebridge like this: `sudo homebridge`, everything is fine, however when I'm using HB-Service, I get this error, and the plugin won't load:

```
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+
```

What I've tried so far (without success):

- Add `"sudo": true` in Homebridge Config UI X

- Edit the sudoers file (`sudo visudo`) to write `homebridge ALL=(ALL) NOPASSWD: ALL` at the end

- Same but with the pi user: `pi ALL=(ALL) NOPASSWD: ALL`

- Restart hb-service with --allow-root: `sudo hb-service --allow-root restart`

- Allow user pi to run node with the rights of root: `sudo chmod u+s /usr/bin/node` (from https://github.com/fivdi/pigpio/issues/2)

**Logs:**

```
[4/20/2020, 10:22:10] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[4/20/2020, 10:22:10] [HB Supervisor] Started Homebridge with PID: 4271
[4/20/2020, 10:22:11] Loaded config.json with 0 accessories and 1 platforms.
[4/20/2020, 10:22:11] ---
[4/20/2020, 10:22:12] Loaded plugin: homebridge-config-ui-x
[4/20/2020, 10:22:12] Registering platform 'homebridge-config-ui-x.config'
[4/20/2020, 10:22:12] ---
2020-04-20 10:22:12 initCheckPermitted: 
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 595B",
        "username": "XXXXXXXX",
        "port": 51625,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "debug": false,
            "platform": "config"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 0.4.53
* **Homebridge Config UI X Version**: v4.15.1
* **Operating System**: Raspbian Buster Lite
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Note that the following instructions describe a non-supported setup.

Edit the following file:

```
/etc/systemd/system/homebridge.service
```

You will see a section like this:

```
[Service]
Type=simple
User=pi
```

Change the the user line to `User=root`. Do not change anything else in this file.

Save and Close.

Open this file for editing:

```
/etc/default/homebridge
```

Append `--allow-root` to the end of the HOMEBRIDGE_OPTS line:

```
HOMEBRIDGE_OPTS=-I -U "/var/lib/homebridge" --allow-root
```

Run this command to refresh systemd:

```
systemctl daemon-reload
```

Restart `hb-service`.

Homebridge will now run as root.

**Comment by nicolasherrbach** [comment]
Thank you for the quick answer, however I still get the error. I tried rebooting the Pi also with no improvement.

**Comment by nicolasherrbach** [comment]
I've got a solution for this on the [Raspberry Pi stackexchange](https://raspberrypi.stackexchange.com/questions/111884/pigpio-wont-initialise-when-used-by-a-script-started-by-a-service-even-with-roo).

The service file `/etc/systemd/system/homebridge.service` needed apparently a bit more modifications.

A working service file is:
```
[Unit]
Description=Homebridge
Wants=network-online.target
After=syslog.target network-online.target

[Service]
WorkingDirectory=/var/lib/homebridge
EnvironmentFile=/etc/default/homebridge
ExecStartPre=/bin/run-parts /etc/hb-service/homebridge/prestart.d
ExecStartPre=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before-start $HOMEBRIDGE_OPTS
ExecStart=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEBRIDGE_OPTS
KillMode=process

[Install]
WantedBy=multi-user.target
```
