### ISSUE TITLE
Showing wrong node version?

### ISSUE THREAD

**Issue by schweppy** [oznu/homebridge-config-ui-x#627]
I’ve just updated Node to v12.16.2 which shows when I type “node -v”. 

However CONFIG UIX is showing 10.15.2? 

Any ideas?

**Comment by oznu** [comment]
If you haven't restarted the UI yet, make sure you've done that.

Other wise you probably have two copies of Node.js installed using different methods.

**Comment by schweppy** [comment]
Yes I tried rebooting Homebridge server and then rebooted Pi. 

Any ideas how to check and sort a double install?

**Comment by oznu** [comment]
Do you run anything else that uses Node.js?
Where is your Homebridge storage directory? (eg. /var/lib/homebridge)

**Comment by schweppy** [comment]
No just homebridge. It’s in home/pi/.homebridge

I did the latest node update using NVM as thought I was being clever... 😂

**Comment by oznu** [comment]
How is your Homebridge service managed? if you don't know what command do you use to restart?

**Comment by schweppy** [comment]
I use PM2

**Comment by oznu** [comment]
Ok these commands will replace your setup with a fresh copy of Node.js and replace `pm2` with `hb-service`. Read them to the end before starting to make sure you're happy with the changes.

**Step 1:** Remove pm2 service.

```
pm2 stop all
pm2 delete all
sudo npm uninstall -g pm2
```

**Step 2:** Remove all copies of Node.js, this script will do that for you:

```
sudo curl -fL https://gist.githubusercontent.com/oznu/312b54364616082c3c1e0b6b02351f0e/raw/remove-node.sh | sudo bash
```

**Step 3:** Copy your homebridge storage directory to `/var/lib/homebridge`.

```
mkdir -p /var/lib
cp -R /home/pi/.homebridge /var/lib/homebridge
```

**Step 4:** Re-install everything using the guide in the wiki: 

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

This will get you the latest verison of Node.js and Homebridge + Homebridge UI setup. You won't loose any config as long as you followed **Step 3** to copy your config.

**Step 5:** Login to http://<ip address>:8581 and re-install your plugins. The UI password will be the same as what you had set originally.

**Comment by schweppy** [comment]
Thank you, very helpful. 

Can I ask if there’s anything wrong with using PM2?

I’ve just updated NPM and installed the latest update of Node with that and all is now correct in the UI dashboard. 

However if you think it’s better to use hb-service then I will do as you said.

**Comment by oznu** [comment]
If you've got it working then you can leave it.

`hb-service` does add a few things, for example, the UI will stay online even if Homebridge is crashing.

**Comment by schweppy** [comment]
Ok great. Thank you very much for all of your help.  I will upgrade to HB service soon.
