### ISSUE TITLE
Web UI cannot access if behind reverse proxy with additional path in front

### ISSUE THREAD

**Issue by ronald8192** [oznu/homebridge-config-ui-x#628]
I think this is something between feature request or bug

**Describe The Bug:**
Normally after setup will use `http://ip:8080` to access the UI, but I have nginx reverse proxy to serve the site and setup `http://ip/homebridge` to access homebridge web UI. The UI will show a white blank screen.

The reason is all js and css are not loaded. `/homebridge/` in the request path is missing. 
=> `http://ip/styles.e0dc902492593c470c22.css`
should be 
=> `http://ip/homebridge/styles.e0dc902492593c470c22.css` (will return 200)
![image](https://user-images.githubusercontent.com/5982132/79748309-cd5fb000-833f-11ea-937f-f9a005f0f666.png)

I try to edit the index page, adding `homebridge/` in all path:
![image](https://user-images.githubusercontent.com/5982132/79749498-e8cbba80-8341-11ea-9c19-7fcd2e53c9f0.png)

but still, the same problem happens on other requests:
`http://ip/api/auth/settings`
![image](https://user-images.githubusercontent.com/5982132/79758405-f12af200-834f-11ea-9911-568d46759b6a.png)

If reverse proxy use root `/` to serve, the UI is working

Seems the UI is an Angular app, and it can be fix in code or build parameter?

[http://www.projectcodify.com/angular-set-base-url-dynamically](http://www.projectcodify.com/angular-set-base-url-dynamically)
[https://stackoverflow.com/questions/55705637/how-to-set-base-url-for-angular-application](https://stackoverflow.com/questions/55705637/how-to-set-base-url-for-angular-application)
[https://angular.io/api/common/APP_BASE_HREF](https://angular.io/api/common/APP_BASE_HREF)

**To Reproduce:**
1. Setup like normal (i using homebridge docker version)
1. Setup nginx reverse proxy
```
server{
    listen 80;

    location /homebridge {
        proxy_pass http://127.0.0.1:8081/;
        proxy_buffering             off;
        proxy_set_header            Host $host;
        proxy_set_header            Upgrade $http_upgrade;
        proxy_set_header            Connection "Upgrade";
        proxy_set_header            X-Real-IP $remote_addr;
        proxy_set_header            X-Forward-For $proxy_add_x_forwarded_for;
    }
}
```
1. Browse web site at `http://ip/homebridge`

**Expected behavior:**
Can access the UI by `http://ip/homebridge/` like normal (or other paths in front)

**Logs:**
--

(not related)

**Homebridge Config:**

(default config)

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 0.4.53
* **Homebridge Config UI X Version**: v4.15.1
* **Operating System**: Docker
* **Process Supervisor**: Docker
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
oznu/homebridge     latest              fba80728acfd        5 days ago          471MB
```

**Comment by oznu** [comment]
Here is what needs to change:

https://github.com/oznu/homebridge-config-ui-x/compare/url-stub-support

Not merging yes as I'm not sure it won't break existing setups.

**Comment by ronald8192** [comment]
I want to test it. How to update?

**Comment by donavanbecker** [comment]
```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@4.15.2-test.11
```

**Comment by ronald8192** [comment]
I updated.
css and js in index page are loading correctly, but `/homebridge/api/auth/settings` returns the index html.

![image](https://user-images.githubusercontent.com/5982132/80127578-1d03dd00-85c7-11ea-8d12-b13f126e3cec.png)

![image](https://user-images.githubusercontent.com/5982132/80127740-59373d80-85c7-11ea-94b1-d74ffc3c4587.png)

**Comment by ronald8192** [comment]
Hi @oznu! I added 2 Nginx rewrite rule, it is working now!

```
rewrite /homebridge/api/(.*)       /api/$1        break;
rewrite /homebridge/socket.io/(.*) /socket.io/$1  break;
```

Also tested it works without url stub.

**Comment by leaky0320** [comment]
I have four Homebridge instances that I was trying to use Nginx so I could access them like local.host/bridge1, local.host/bridge2, etc. It looks like the past solution was a test branch and adding rewrite rules to Nginx. Is there any development on this issue as the test branch is several versions ago and don't want to miss any new features.

**Comment by arkeane** [comment]
I have the same problem with an nginx reverse proxy are there any news?

**Comment by mriksman** [comment]
+1 for me

**Comment by jpartain89** [comment]
I like how this was closed, without the MR actually getting merged.... So nothing was ever fixed. 

I'm also having the same issue.

**Comment by crazyelectron-io** [comment]
Looks like this will not be supported...
