### ISSUE TITLE
Restart non working (MacOS & launchd)

### ISSUE THREAD

**Issue by seannymurrs** [oznu/homebridge-config-ui-x#63]
When I attempt to restart homebridge using the web UI button, it will successfully shutdown homebridge but never start it back up again. I have homebridge setup to start automatically upon boot using launchd, and that seems to be working fine. Manually launching it using the launchd command also works. Below is what I have in the config file for the Restart command. I can't figure out why it isn't working.

`launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist`

**Comment by oznu** [comment]
Please see https://github.com/oznu/homebridge-config-ui-x/issues/14 for the simple solution.

**Comment by seannymurrs** [comment]
Awesome, thank you!
