### ISSUE TITLE
Clear cache on reboot

### ISSUE THREAD

**Issue by WesleyLiekens** [oznu/homebridge-config-ui-x#631]
**Describe Your Problem:**
Is there a way to clear the cached accessories every time on reboot?
I am using a plugin that does not support cached accessories called homebridge-nhc2 and I would like to skip that manual step every time the system reboots

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: v6.14.4
* **Homebridge Version**: v0.4.53
* **Homebridge Config UI X Version**: v4.16.0
* **Operating System**: MacOS Catalina
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Hi @WesleyLiekens,

The plugin instructions telling you to clear cached accessories is a terrible idea and is just a work around for a broken plugin. Doing this every restart would make it impossible to run any other plugins at the same time.

I'd recommend the plugin author fix their plugin on their end, as I don't think it's a good idea for the UI to facilitate bad design.

**Comment by WesleyLiekens** [comment]
That may be so. But I only have need for this one plugin. And the author doesn’t seem to be fixing this anytime soon. 
And I have no idea how to do it myself so I’m stuck with doing this manually
