### ISSUE TITLE
Cosmetics bug in bottom text

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#632]
In the red marked area U can see that the text I cut on the bottom:

![AFBCF6B2-E815-4B0A-B4CE-B6E42BA4FA08](https://user-images.githubusercontent.com/28867813/80213813-09458e80-863a-11ea-8653-6157de6bcd8f.jpeg)

**Comment by oznu** [comment]
I will look at this one day @grzegorz914

**Comment by oznu** [comment]
Does the latest update help this issue?

**Comment by grzegorz914** [comment]
Yes, it’s fixed now.
