### ISSUE TITLE
Cannot install homebridge-config-ui-x

### ISSUE THREAD

**Issue by asbesto01** [oznu/homebridge-config-ui-x#633]
Hello,

I currently run an homebridge instance via command line (version 0.4.53) and I am trying to install the homebridge-config-ui-x plugin to manage it via GUI.

However when launching npm install homebridge-config-ui-x

I receive following errors:

> node-pty-prebuilt-multiarch@0.9.0 install C:\Windows\system32\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

> @nestjs/core@7.0.7 postinstall C:\Windows\system32\node_modules\homebridge-config-ui-x\node_modules\@nestjs\core
> opencollective || exit 0

                           Thanks for installing nest
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 457
                              Number of backers: 348
                            Annual budget: US$ 48,176
                             Current balance: US$ 424

         Become a partner: https://opencollective.com/nest/donate

> node-pty-prebuilt-multiarch@0.9.0 postinstall C:\Windows\system32\node_modules\node-pty-prebuilt-multiarch
> node scripts/post-install.js

**npm WARN saveError ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})**

+ homebridge-config-ui-x@4.16.0
added 284 packages from 166 contributors and audited 47805 packages in 315.444s

8 packages are looking for funding
  run `npm fund` for details

found 1642 vulnerabilities (1621 low, 21 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Do you have any advice?
Running on Windows 10 machine, thanks!

**Comment by oznu** [comment]
Did you install with the global flag, `-g`?

```
npm install -g homebridge-config-ui-x
```

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

**Comment by asbesto01** [comment]
nope, I am trying it just now, thanks ;)

**Comment by asbesto01** [comment]
tried, this is the error output:

npm ERR! code EEXIST
npm ERR! path C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\standalone.js
npm ERR! dest C:\Users\PersonalComputerHP\AppData\Roaming\npm\homebridge-config-ui-x
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\standalone.js' -> 'C:\Users\PersonalComputerHP\AppData\Roaming\npm\homebridge-config-ui-x'
npm ERR! File exists: C:\Users\PersonalComputerHP\AppData\Roaming\npm\homebridge-config-ui-x
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PersonalComputerHP\AppData\Roaming\npm-cache\_logs\2020-04-24T13_48_55_339Z-debug.log

thanks

**Comment by oznu** [comment]
You may need to do a bit of cleanup.

Open `C:\Users\PersonalComputerHP\AppData\Roaming\npm` in Explorer and delete any files or folders than match these names:

* `hb-service`
* `homebridge-config-ui-x`

Then try again.

**Comment by asbesto01** [comment]
solved! thanks, can be closed :)

**Comment by GalaxyNerd** [comment]
I have this same issue, but It's a bit different. Whenever I execute `npm install -g --unsafe-perm homebridge homebridge-config-ui-x`, it goes as planned, but when I execute: `hb-service install` I get this error 
`TypeError: Cannot assign to read only property 'toString' of object '#<Cancel>'
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\axios\lib\cancel\Cancel.js:13:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\axios\lib\axios.js:40:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)`
Anyone know what's going on?
