### ISSUE TITLE
Homebridge Reporting Wrong Node JS Version

### ISSUE THREAD

**Issue by dawger1** [oznu/homebridge-config-ui-x#634]
Hi there,

I’ve got a pending update to config-ui-x, but noticed that it needed a later version of node (config-ui-x is reporting v10.14.2. I updated node to v13.13.0, but config-ui-x is still reporting 10.14.2. I read a similar issue that reported multiple instances of node installed. I’m a raspbian noob, and have no idea how to sort this out. Any suggestion how to remove the old version so that I’m not running two instances?

I followed the docker instructions to install homebridge on a raspberry pi a couple of years ago, but haven’t had to do much with it since then.  I’ve attached a screenshot of my configuration as an attachment to this. 

Here’s the path to my homebridge instance: /homebridge/volumes/homebridge/

When I check the node version in the root folder, it says 13.13.0, but when I check in the terminal within config-ui-x, it says 10.14.2. Help please!
![CE159A32-FEFA-48F4-A0F7-E2CE7F584B9D](https://user-images.githubusercontent.com/34188593/80286984-c00a4300-86fc-11ea-832f-e7f8dc288a09.jpeg)

**Comment by oznu** [comment]
You have multiple copies of Node.js installed.

See https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

**Comment by oznu** [comment]
Sorry just noticed you are running Docker. 

Please update the underlying Docker image to update Node.js. The latest Homebridge image comes with the current LTS version of Node.js, v12.14.2.

As long as you've mounted your /homebridge volume mount correctly you won't loose any settings.

**Comment by dawger1** [comment]
That did it. Thank you very much!
