### ISSUE TITLE
This plugin is not marked as Verified in GUI by itself 

### ISSUE THREAD

**Issue by piotrtobolski** [oznu/homebridge-config-ui-x#636]
**Describe The Bug:**
This plugin is not marked as Verified in GUI by itself 
Minor but surprising issue

**To Reproduce:**
Check the Plugins section

**Expected behavior:**
This plugin is marked as secure.

**Screenshots:**
<img width="998" alt="hb" src="https://user-images.githubusercontent.com/1545279/80291180-beb43700-874b-11ea-97b1-1a33878f58af.png">

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: v6.14.4
* **Homebridge Version**: 0.4.53
* **Homebridge Config UI X Version**: v4.16.0
* **Operating System**: Docker (Alpine, no-avahi on synology)
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
This is intended as it's not really a plugins anymore (especially when running in `hub-service` mode).

I'm thinking about moving it out of the plugins page at some point (you can already access the UI settings modal from the upper-right-corner dropdown menu).
