### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by netRunner0** [oznu/homebridge-config-ui-x#639]
See photo:

![IMG_0722](https://user-images.githubusercontent.com/44049295/80348500-50748f00-8887-11ea-84d8-aa0b01d7e0db.jpeg)
![IMG_0723](https://user-images.githubusercontent.com/44049295/80348525-59656080-8887-11ea-9186-7df868d9c4da.jpeg)
![IMG_0724](https://user-images.githubusercontent.com/44049295/80348537-5e2a1480-8887-11ea-9ea0-c1dade71ae77.jpeg)

**Comment by oznu** [comment]
I cannot replicate this. Did you recently update Node.js from 12.11.1 at all (soemthing might have cached somewhere)?

**Comment by Staubgeborener** [comment]
@oznu @netRunner0 i could replicate this. I also use the `homebridge-hue`-Plugin, so the "bug" (not really one though) was the same on my setup.

I updated `nodejs` from 12.14.1 to 12.16.2. After the update, the terminal shows the correct version, but it takes 1 or 2 restarts and some time before it has actually been recognized in the config-ui-x. As you said @oznu, it will have something to do with cached files.

**Comment by tooh** [comment]
I can confirm the same.

Just updated to latest stable node, even after 2 restarts of homebridge-ui the version on statuspage is behind

**Comment by oznu** [comment]
Are you running with `hb-service` @tooh? If so you may need to ensure the UI is actually restarting (it decides if it needs to restart, or if only Homebridge needs to restart when you restart Homebridge via the UI). You can force a service restart by running:

```
sudo hb-service restart
```

**Comment by tooh** [comment]
@oznu  running hb-service restart solved it

**Comment by oznu** [comment]
Thanks @tooh, you can do a full restart from the Homebridge Settings section.

![image](https://user-images.githubusercontent.com/3979615/83959837-2cb05a00-a8c5-11ea-9e6b-63b6e21474ff.png)
