### ISSUE TITLE
SSL option not finding certificates

### ISSUE THREAD

**Issue by AppElent** [oznu/homebridge-config-ui-x#640]
**Describe Your Problem:**
I can't set up my SSL certificates from certbot (Lets Encrypt). It cant find the certs

Certbot places the certificates in /etc/letsencrypt/live/www.example.com
This folder isnt accessible by the pi user (or I think the homebridge user which was created during installation of the service `sudo hb-service install --user homebridge`.

I tried several things:
sudo cp -a /etc/letsencrypt/live/www.example.com/. /home/homebridge/ssl/
sudo cp -a /etc/letsencrypt/live/www.example.com/. /home/pi/ssl/
sudo cp -a /etc/letsencrypt/live/www.example.com/. /ssl/ (created this folder on root and did chmod 777 on this folder)

The certs are present:
root@raspberrypi:/home/homebridge/ssl# ls
cert.pem  chain.pem  fullchain.pem  privkey.pem  README

I have a feeling this is a permissions issue but I cant seem to solve this (thats why I created this root folder with permissions for everyone, still no luck)

**Logs:**
[4/27/2020, 12:47:39 PM] Registering platform 'homebridge-config-ui-x.config'
[4/27/2020, 12:47:39 PM] ---
[4/27/2020, 12:47:40 PM] [homebridge-config-ui-x] Error: ENOENT: no such file or directory, open '/home/homebridge/ssl/privkey.pem'
[4/27/2020, 12:47:40 PM] [homebridge-config-ui-x] Caught Unhandled Rejection Error :: Details Below
[Error: ENOENT: no such file or directory, open '/home/homebridge/ssl/privkey.pem'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/homebridge/ssl/privkey.pem'
}

```
Show the Homebridge / Homebridge Config UI X logs here.
```
[4/27/2020, 12:47:39 PM] Registering platform 'homebridge-config-ui-x.config'
[4/27/2020, 12:47:39 PM] ---
[4/27/2020, 12:47:40 PM] [homebridge-config-ui-x] Error: ENOENT: no such file or directory, open '/home/homebridge/ssl/privkey.pem'
[4/27/2020, 12:47:40 PM] [homebridge-config-ui-x] Caught Unhandled Rejection Error :: Details Below
[Error: ENOENT: no such file or directory, open '/home/homebridge/ssl/privkey.pem'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/homebridge/ssl/privkey.pem'
}

**Homebridge Config:**

```json
Show your homebridge config.json here
```
Just regular config, using this example:
"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "ssl": {
        "key": "/path/to/privkey.pem",
        "cert": "/path/to/fullchain.pem"
      }
    }
]
Its a fresh install, no plugins configured

**Environment:**

* **Node.js Version**: latest
* **NPM Version**: latest
* **Homebridge Version**: 1.0.0
* **Homebridge Config UI X Version**: latest
* **Operating System**: Raspbian
* **Process Supervisor**:  hb-service

**Comment by oznu** [comment]
You have this in your configuration:

```
/home/homebridge/ssl/privkey.pem
```

But you copied the cert to this path:

```
/home/pi/ssl/privkey.pem
```

As you're using hb-service you should either make the certs accessible to the `homebridge` user or copy them to the `/var/lib/homebridge` folder and reference them from there.

**Comment by AppElent** [comment]
Hi, thanks for the quick response.
I tested several configurations, after each also editted the JSON.

With your path, var/lib, still no luck:

Error:
[4/27/2020, 1:10:27 PM] [homebridge-config-ui-x] Error: ENOENT: no such file or directory, open '/var/lib/homebridge-test/privkey.pem'
[4/27/2020, 1:10:27 PM] [homebridge-config-ui-x] Caught Unhandled Rejection Error :: Details Below
[Error: ENOENT: no such file or directory, open '/var/lib/homebridge-test/privkey.pem'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/lib/homebridge-test/privkey.pem'
}

Config json:
    "platforms": [
        {
            "name": "Config",
            "port": 8082,
            "platform": "config",
            "ssl": {
                "key": "/var/lib/homebridge-test/privkey.pem",
                "cert": "/var/lib/homebridge-test/fullchain.pem"
            }
        }
    ]

directory content:
root@raspberrypi:/var/lib/homebridge-test# ls
accessories  config.json			fullchain.pem	README
auth.json    config.json.1587973442606		homebridge.log
cert.pem     config.json.1587974835545		persist
chain.pem    config.json.invalid.1587974687030	privkey.pem
root@raspberrypi:/var/lib/homebridge-test#

**Comment by oznu** [comment]
can you run this?

```
ls -la /var/lib/homebridge-test/privkey.pem
```

**Comment by AppElent** [comment]
root@raspberrypi:/var/lib/homebridge-test# ls -la /var/lib/homebridge-test/privkey.pem
lrwxrwxrwx 1 homebridge homebridge 44 Apr 27 13:10 /var/lib/homebridge-test/privkey.pem -> ../../archive/home.appelent.com/privkey1.pem
root@raspberrypi:/var/lib/homebridge-test#

**Comment by oznu** [comment]
If you run `cat /var/lib/homebridge-test/privkey.pem` does the contents of the file output? (Don't post the file contents here).

**Comment by AppElent** [comment]
Nope...

**Comment by oznu** [comment]
I think you have a broken symlink from `/var/lib/homebridge-test/privkey.pem` to `../../archive/home.appelent.com/privkey1.pem`.

Try delete the `/var/lib/homebridge-test/privkey.pem` file then copy from the Let's Encrypt directory again.

**Comment by AppElent** [comment]
Whats the best command to copy all files from the letsencrypt dir to the new one?

**Comment by AppElent** [comment]
if I do ` sudo cp -r /etc/letsencrypt/live/home.appelent.com/. /var/lib/homebridge-test/` and after that a cat, still nothing. (I deleted the file first)

**Comment by AppElent** [comment]
In the origin dir it works:
root@raspberrypi:/etc/letsencrypt/live/www.example.com# cat privkey.pem
-----BEGIN PRIVATE KEY-----

**Comment by oznu** [comment]
Try this..

```
ln -sf /etc/letsencrypt/live/www.example.com/fullchain.pem /var/lib/homebridge-test/fullchain.pem
ln -sf /etc/letsencrypt/live/www.example.com/privkey.pem /var/lib/homebridge-test/privkey.pem
```

Then check it outputs the cert:

```
cat /var/lib/homebridge-test/privkey.pem
```

**Comment by AppElent** [comment]
Then cat works. What is going wrong here? I will adjust the JSON gimme a sec

**Comment by AppElent** [comment]
Now I get a permission denied error:
[4/27/2020, 1:31:15 PM] [homebridge-config-ui-x] Error: EACCES: permission denied, open '/var/lib/homebridge-test/privkey.pem'
[4/27/2020, 1:31:15 PM] [homebridge-config-ui-x] The process owner does not have permission to run services on port undefined.
[4/27/2020, 1:31:15 PM] [homebridge-config-ui-x] Please change the homebridge-config-ui-x port to something above 1024.
[4/27/2020, 1:31:15 PM] [homebridge-config-ui-x] Ending process now.

**Comment by AppElent** [comment]
Port isnt changed, so undefined would be weird. Worked before (port 8082)

**Comment by oznu** [comment]
Cool. Now run:

```
sudo chown -R homebridge: /etc/letsencrypt/live/www.example.com
```

Then:

```
sudo hb-service restart --service-name homebridge-two
```

**Comment by AppElent** [comment]
That changes the owner, but I also use this cert for domoticz. Is there another change in permissions I can do?

**Comment by oznu** [comment]
```
sudo rm -rf /var/lib/homebridge-test/{fullchain.pem,privkey.pem}
sudo cp /etc/letsencrypt/live/www.example.com/{fullchain.pem,privkey.pem} /var/lib/homebridge-test/
sudo chown -R homebridge: /var/lib/homebridge-test/
```

**Comment by AppElent** [comment]
That works (although I failed at first because I used http). Is there any way to force redirect to https?

**Comment by oznu** [comment]
No redirect using this method as I only bind to one port. Normal http -> https redirection works by using port 80 for http and 443 for https.

Nginx would let you do this. https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Nginx-and-SSL
