### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by bwoodruff** [oznu/homebridge-config-ui-x#641]
**Is your feature request related to a problem? Please describe:**

Not really.

**Describe the solution you'd like:**

Please consider adding a minimal-config option for supporting Let's Encrypt for SSL and enabling + auto-redirecting to SSL

**Describe alternatives you've considered:**

I'm not aware of any other certificate provider that makes it as easy (or free) to do this as Let's Encrypt

**Additional context:**

**Comment by mkellsy** [comment]
The issue with let's encrypt is it needs public access to the device or a domain to validate against.

We could use a self signed cert but Chrome won't play nice with this.

We are looking into an app based UI HOOBS Desktop and HOOBS Mobile which are being developed.

**Comment by oznu** [comment]
Hi @bwoodruff,

The easiest way to get Let's Encrypt SSL working is to use Ngnix as a reverse proxy. That way you can use the standard certbot tools to get a certificate.

A sample vhost config for nginx can be found here:

https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Nginx-and-SSL

**Comment by bwoodruff** [comment]
Thank you for the suggestion!

**Comment by oznu** [comment]
No problem. The official Homebridge Raspberry Pi image already has Nginx setup for SSL and we have writing a guide for using Let's Encrypt:

https://github.com/homebridge/homebridge-raspbian-image/wiki/SSL-HTTPS-Access#lets-encrypt--certbot
