### ISSUE TITLE
Config.Schema Generator

### ISSUE THREAD

**Issue by netRunner0** [oznu/homebridge-config-ui-x#645]
As you know, many plugin authors upload the config to the manual without creating config.schema.json.
This creates a lot of problems for new Homebridge users.

**I have an idea:**

Make a visual web generator so that more professional users can create config.schema.json and make a pull request for many popular plugins that do not have this feature.

**Comment by oznu** [comment]
This tool can help you generate the basic schema structure: https://www.jsonschema.net/home

I'd be happy to help out on a supporting project that does the full schema, but don't have the time to maintain one myself sorry!
