### ISSUE TITLE
Multi Instances

### ISSUE THREAD

**Issue by netRunner0** [oznu/homebridge-config-ui-x#646]
Some users use multiple homebridge instances on the same device (for testing and optimization).

Creating a new instance is not complicated, but it requires some knowledge (in my case, it is creating 3 files (systemd), creating a directory and config.json).

These instances have their own config and cache.

It would be nice to be able to create new homebridge instances via the web and be able to edit the config and backup for them.

Thank!

**Comment by oznu** [comment]
It's a single command 😄 

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#multiple-instances

**Comment by netRunner0** [comment]
Yes, but this is only for creation (and then on the official image)

I want versatility)

**Comment by oznu** [comment]
That works on any system with homebridge config ui x installed.

**Comment by netRunner0** [comment]
And how to edit the config and make a backup?

**Comment by oznu** [comment]
You go to the corresponding web ui for that service. eg. http://localhost:8582

**Comment by netRunner0** [comment]
Damn it, you need to read instructions more often 🤦‍♂️

Thank you, you can close 👍
