### ISSUE TITLE
after migrate to mac os catalina everything is working but web ui content is blank getting MIME err

### ISSUE THREAD

**Issue by divemasterjm** [oznu/homebridge-config-ui-x#649]
192.168.8.9/:1 Refused to apply style from 'http://192.168.8.9:8080/styles.45a35ff5a62783d58892.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
runtime-es2015.d4eba49024df75acf821.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
polyfills-es2015.bc3568e5b9f980731fca.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
main-es2015.5c14f147ac7e7b0324e1.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
192.168.8.9/:1 Refused to execute script from 'http://192.168.8.9:8080/scripts.f3c41e5168f1fdc808c0.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
192.168.8.9/:1 Refused to apply style from 'http://192.168.8.9:8080/styles.45a35ff5a62783d58892.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by divemasterjm** [comment]
can you please help me?

**Comment by Staubgeborener** [comment]
Which browser do you use, @divemasterjm? Try this please with safari, chrome and also firefox.

@oznu Hint: Seems to be a problem with you're `angular`. See [this](https://www.youtube.com/watch?v=JYPyy-hvjYc&list=PL6n9fhu94yhXwcl3a6rIfAI7QmGYIkfK5&index=1#t=05m17s), adding `bootstrap` could help maybe.  
(I don't have a macOS to test this and, to be honest, I'm too lazy to set up a virtual machine.)

**Comment by divemasterjm** [comment]
Ive tried but no luck, server is the one upgraded to Catalina, I can’t see it from iphone, iPad, windows, other Mac, different browsers, always blank screen with these errors, home ridge is runing and also says config-Ui runing on port xxxx

JuanMa

**Comment by divemasterjm** [comment]
Also dont have angular

**Comment by divemasterjm** [comment]
log view

[4/30/2020, 1:55:13 PM] [HB Supervisor] Homebridge Storage Path: /Users/juanma/.homebridge-test
[4/30/2020, 1:55:13 PM] [HB Supervisor] Homebridge Config Path: /Users/juanma/.homebridge-test/config.json
[4/30/2020, 1:55:13 PM] [HB Supervisor] Logging to /Users/juanma/.homebridge-test/homebridge.log
[4/30/2020, 1:55:13 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[4/30/2020, 1:55:13 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[4/30/2020, 1:55:13 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[4/30/2020, 1:55:13 PM] [HB Supervisor] Started Homebridge with PID: 17454
[4/30/2020, 1:55:14 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/30/2020, 1:55:14 PM] ---
[4/30/2020, 1:55:14 PM] Loaded plugin: homebridge-config-ui-x
[4/30/2020, 1:55:14 PM] Registering platform 'homebridge-config-ui-x.config'
[4/30/2020, 1:55:14 PM] ---
[4/30/2020, 1:55:14 PM] Loading 1 platforms...
[4/30/2020, 1:55:14 PM] [Config] Initializing config platform...
[4/30/2020, 1:55:14 PM] [Config] Running in Service Mode
Setup Payload:
X-HM://0023U1ZSBJ529
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 220-41-963 │
    └────────────┘

[4/30/2020, 1:55:14 PM] Homebridge is running on port 51888.
[4/30/2020, 1:55:15 PM] [Config] Homebridge Config UI X v4.16.0 is listening on :: port 8088
^C
Mac-mini-de-Juan-6:.homebridge-test juanma$

**Comment by oznu** [comment]
Have you tried reinstalling?

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by divemasterjm** [comment]
i did, but not uninstall, now it works but i have the following error

Loading logs using "file" method...
CMD: sudo -n tail -n 500 -f /Users/juanma/.homebridge/logfile.log


The log tail command "-n tail -n 500 -f /Users/juanma/.homebridge/logfile.log" exited with code 0.
Please check the command in your config.json is correct.

**Comment by oznu** [comment]
I think you might have multiple services setup based on that message.

Does this file exist on your system?

`~/Library/LaunchAgents/com.homebridge.server.plist`

Test with:

```
cat ~/Library/LaunchAgents/com.homebridge.server.plist
```

**Comment by divemasterjm** [comment]
yes, i have 5 instances plus a hb-service instance, i had to  delete "sudo": true, and works again, extrange cause everything was working for more than a year flawesly, the only thing was upgrade it to catalina.
I'm a little affraid cause i have more than 150 accesories in Homebridge and dont want to reinstall everything with the consecuent redo all automations on homekit. maybe you can give me some advice to check if everything is ok, plugins, homebridge etc.
