### ISSUE TITLE
Installation failure - 404 not found

### ISSUE THREAD

**Issue by blloyd78** [oznu/homebridge-config-ui-x#65]
Trying to carry out a fresh install of homebridge-config-ui-x but the process is failing with the following errors:

```
npm WARN engine homebridge-config-ui-x@3.4.0: wanted: {"node":">=6.9.1","homebridge":">=0.4.22"} (current: {"node":"4.8.2","npm":"1.4.21"})
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'oznu/hap-client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'homebridge-config-ui-x'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.80-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-config-ui-x"
npm ERR! cwd /home/pi
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```

When I check /home/<username>/node_modules, @oznu is present (along with all the other requisite packages), and the hap-client folder sits underneath it.

Any idea what I am doing wrong?

**Comment by oznu** [comment]
Hi @blloyd78,

It looks like your using a *really* old version of `npm`. v1.4.21 was released in 2014.

Additionally the this plugin requires at least node.js v6.9.1, and I can see you're only using v4.8.2.

I would recommend upgrading to the latest stable version of node, v8.10.0, which comes bundled with a recent version of `npm`.

https://nodejs.org
https://nodejs.org/en/download/package-manager/

**Comment by blloyd78** [comment]
I gave up and installed a Docker container - the problem seems to have gone away.
