### ISSUE TITLE
[Feature Request] Console filters and search

### ISSUE THREAD

**Issue by dobryc** [oznu/homebridge-config-ui-x#651]
First of all, thanks for sexy GUI!

It would be great if Homebridge's builtin console (journal) got search and device filters.
That will be useful for debugging and plugin development. Builtin browser search doesn't search in console.

**Comment by Staubgeborener** [comment]
What exactly are you looking for? You can use the `terminal widget` or the three dots in the upper right corner > `Terminal` to view the terminal and type in commands. There you can watch syslog or the homebridge-log itself and i.e. `grep` for devices.

![homebridge-terminal](https://user-images.githubusercontent.com/28908603/80690993-e1d64200-8acf-11ea-8d98-6ed10a2fc985.png)
