### ISSUE TITLE
Support for homebridge --plugin-path flag

### ISSUE THREAD

**Issue by JosephDuffy** [oznu/homebridge-config-ui-x#655]
**Is your feature request related to a problem? Please describe:**
homebridge-config-ui-x doesn't display plugins found by homebridge when using `--plugin-path`

**Describe the solution you'd like:**
homebridge-config-ui-x to pickup and allow the configuration of plugins found by homebridge when using `--plugin-path`

**Describe alternatives you've considered:**
Installing globally for testing, uninstall when testing is complete.

**Additional context:**
Locally I test my plugin by running `homebridge --debug -I --user-storage-path .homebridge-debug --plugin-path .` where `.homebridge-debug` has a `config.json` file that has my plugin and homebridge-config-ui-x

**Comment by oznu** [comment]
It will work if you use `-P` for now.

**Comment by oznu** [comment]
You can also just run `npm link` in your project folder, that makes your local plugin act as a global one until you run `npm unlink`.

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge#plugin-development

**Comment by JosephDuffy** [comment]
Ah I think I've found the issue. The output of `homebridge --help` describes `-P` as:

```
-P, --plugin-path [path]        look for plugins installed at [path] as well as the default locations
                                  ([path] can also point to a single plugin)
```

I am passing the path of the plugin (e.g. `.`) for the plugin path, which homebridge supports (`[path] can also point to a single plugin`), but homebridge-config-ui-x doesn't appear to pick up the plugin unless the parent directory is passed (e.g. `..`)

**Comment by oznu** [comment]
I'm happy to leave this as is for now, I don't want to risk breaking plugin discovery when `npm link` works for this purpose. Thank you for reporting this issue though!
