### ISSUE TITLE
Error in plugin screen when 2 plugins have the same name

### ISSUE THREAD

**Issue by uspino2** [oznu/homebridge-config-ui-x#658]
It's a very unlikely scenario, but here's the issue: 

I installed [homebridge-mqttgaragedoor](https://www.npmjs.com/package/homebridge-mqttgaragedoor) from the Plugin Screen search. Then I uninstalled it. 

Next I installed [this different plugin](https://github.com/iomax/homebridge-mqttgaragedoor) that has the same name. I had to clone it locally because it doesn't show up in Plugin Screen search.

The plugin installs fine and shows up in Plugins now, but the npm url, the author's name etc. links to the previous plugin, the old one. 

Is there some cache I can clear to make ConfigUI forget all about the previous plugin? Thanks

**Comment by oznu** [comment]
Plugin names are unique as `npm` only allows one module with that name.  You have cloned down a fork of the same plugin which is why the UI is showing the details from the published version on npm.

The plugin author needs to rename their plugin and publish it under a different name.
