### ISSUE TITLE
npm update check failed

### ISSUE THREAD

**Issue by thehauntedmattress** [oznu/homebridge-config-ui-x#66]
I keep getting a message in the logs that is saying:

> npm update check failed
Try running sudo or get access to the local update confnig store via 
sudo chown -R $USER:$(id -gn $USER) /home/homebridge/.config

I had this working on a Raspberry Pi Zero W.  Because of the whole [homebridge-config-ui-x and homebridge-alexa](https://github.com/NorthernMan54/homebridge-alexa/issues/76) conflict, l decided to buy a raspberry pi 3b+.  The other reason I bought a new Pi was because of performance issues.  When I take away the text below from my config file (thus disabling homebridge-config-ui-x), the issue is not present.

My config is here:

> 	 {      
            "platform": "config",
            "name": "Config",
            "restart": "sudo -n systemctl restart homebridge",
            "port": 8080,
            "sudo": true,
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": "systemd",  
  	    "theme": "indigo"
}

**Comment by oznu** [comment]
Hi @thehauntedmattress,

You can suppress these warning messages by adding this line to the bottom of your `/etc/default/homebridge` file:

```
NO_UPDATE_NOTIFIER=1
```

I'll push up a new version soon that will suppress these warnings by default.
