### ISSUE TITLE
 [Developer - Settings Panel] Get homebridge host name in settings panel

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#661]
**Is your feature request related to a problem? Please describe:**
Nope

**Describe the solution you'd like:**
It would be nice if one could get a placeholder for the hostname of the homebridge instance in config.schema.json. Some of my, and I suppose some other, plugins require the user to open a web page supplied by the plugin. If there was a placeholder variable one could have a link to that right in the settings panel. Something like this:

`"headerDisplay" : "To set up the server please visit http://%HOSTNAME%:8888/setup-server"`

**Describe alternatives you've considered:**
I looked around if there was something like this already but didn't really find anything. Sorry if this is already existing in some way.

Cheers,
Normen

**Comment by oznu** [comment]
Done in the next release.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes.

```
"headerDisplay" : "To set up the server please visit http://${{HOSTNAME}}:8888/setup-server"
```

hostname is the same value as `location.hostname`.

**Comment by mkormendy** [comment]
> **Is your feature request related to a problem? Please describe:**
> Nope
> 
> **Describe the solution you'd like:**
> It would be nice if one could get a placeholder for the hostname of the homebridge instance in config.schema.json. Some of my, and I suppose some other, plugins require the user to open a web page supplied by the plugin. If there was a placeholder variable one could have a link to that right in the settings panel. Something like this:
> 
> `"headerDisplay" : "To set up the server please visit http://%HOSTNAME%:8888/setup-server"`
> 
> **Describe alternatives you've considered:**
> I looked around if there was something like this already but didn't really find anything. Sorry if this is already existing in some way.
> 
> Cheers,
> Normen

Do you have a snapshot of what this looks like now? Can you attach to this thread?

**Comment by normen** [comment]
It looks as if you just put the URL in there:
`"headerDisplay": "Go to [http://${{HOSTNAME}}:8999](http://${{HOSTNAME}}:8999) to enter the PIN when your TV displays it"`
->
<img width="796" alt="Bildschirmfoto 2020-05-08 um 19 17 35" src="https://user-images.githubusercontent.com/3270528/81431059-cec31200-9160-11ea-8554-07ee3ab2d2b0.png">
