### ISSUE TITLE
Support for "heartbeat" like monitoring on Plugins summary page

### ISSUE THREAD

**Issue by tooh** [oznu/homebridge-config-ui-x#663]
**Is your feature request related to a problem? Please describe:**

Sometimes plugins have a problem to connect to an external API.
Some even don't handle this exception and all plugins are influenced.
Although the cause can be determined most of the time from the logs it is very inconvenient to find out after a while that things are not working any more.
**Describe the solution you'd like:**

Trafficlight like view for all the plugins, perhaps a notification like approach
**Describe alternatives you've considered:**

**Additional context:**

**Comment by oznu** [comment]
Hi @tooh,

This is a great suggestion, unfortuately right now it's not possible due to the way Homebridge combines plugins. I'll see what the HB team thinks of trying to add this to the core project... but don't hold your breath 😄.

**Comment by oznu** [comment]
Closing for now. Homebridge is looking at doing some changes to how dynamic platforms are loaded at the moment that may make this possible in the future.
