### ISSUE TITLE
Config for logs is not loaded.

### ISSUE THREAD

**Issue by superjunky** [oznu/homebridge-config-ui-x#664]
**Describe Your Problem:**

The log file is not changed after specifying a file in the config.json.
I also tried Custom Command, but it's never loaded.

The log widget keeps showing:
Loading logs using "file" method...
CMD: tail -n 500 -f /homebridge/logs/homebridge.log etc..

**Logs:**

```
/root/.homebridge/.env not found.
Default env variables will be used.
Force the installation of Homebridge version 'latest'.
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
+ homebridge@1.0.4
updated 1 package in 4.272s
/root/.homebridge/package.json not found.
Installing plugins from /root/.homebridge/install.sh.
Wed May  6 01:02:31 CEST 2020
Updated timezone to 'Europe/Amsterdam'..
[5/6/2020, 1:02:32 AM] Loaded config.json with 1 accessories and 1 platforms.
[5/6/2020, 1:02:32 AM] ---
[5/6/2020, 1:02:32 AM] Loaded plugin: homebridge-config-ui-x
[5/6/2020, 1:02:32 AM] Registering platform 'homebridge-config-ui-x.config'
[5/6/2020, 1:02:32 AM] ---
[5/6/2020, 1:02:33 AM] Loaded plugin: homebridge-http-sprinkler
[5/6/2020, 1:02:33 AM] Registering accessory 'homebridge-http-sprinkler.HttpSprinkler'
[5/6/2020, 1:02:33 AM] ---
[5/6/2020, 1:02:33 AM] Loading 1 platforms...
[5/6/2020, 1:02:33 AM] [Config] Initializing config platform...
[5/6/2020, 1:02:33 AM] [Config] Spawning homebridge-config-ui-x with PID 50
[5/6/2020, 1:02:33 AM] Loading 1 accessories...
[5/6/2020, 1:02:33 AM] [Tuin Sproeier v2] Initializing HttpSprinkler accessory...
[5/6/2020, 1:02:33 AM] [Tuin Sproeier v2] Check status: polling
Setup Payload:
X-HM://0023ISYWYK84M
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[5/6/2020, 1:02:33 AM] Homebridge is running on port 51827.
[5/6/2020, 1:02:35 AM] [Config] Homebridge Config UI X v4.17.1 is listening on :: port 8087
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge Test",
        "username": "CC:21:3E:E4:DA:31",
        "port": 51827,
        "pin": "031-45-154"
    },
    "description": "Configuration for Homebridge testing.",
    "platforms": [
        {
            "name": "Config",
            "port": 8087,
            "auth": "form",
            "theme": "default",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "file",
                "path": "/root/.homebridge/logs/output.log"
            },
            "proxyHost": "**mydomain**.com:80",
            "platform": "config"
        }
    ],
    "accessories": []
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.16.1
* **NPM Version**: v6.13.4
* **Homebridge Version**: 1.0.4
* **Homebridge Config UI X Version**: v4.17.1
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
I don't think you're using the supported Docker image:

https://github.com/oznu/docker-homebridge

**Comment by superjunky** [comment]
> I don't think you're using the supported Docker image:
> 
> https://github.com/oznu/docker-homebridge

True, but it does not explain why the logs part in the config is not loaded. This UI plugin does not read the config.json differently according to the type of Docker image.

Any ideas?

**Comment by oznu** [comment]
The other Docker images probably don't write the logs to somewhere process also running inside the container can read them.

**Comment by oznu** [comment]
> This UI plugin does not read the config.json differently according to the type of Docker image.

The UI plugin does actually enter a special "Docker" mode when it detects it's running in the supported Docker image. This mode automatically sets all the required settings (like log setup) and adds additional functionality like the ability to restart the container, or set startup flags (like toggling debug, or insecure mode).

**Comment by superjunky** [comment]
Also true :p But I have created my own log and can read it just fine in the UI-terminal with
```tail -f /root/.homebridge/logs/output.log```

Now I wonder why it can be tailed from within that terminal, but not loaded from config.json as my own custom command.

**Comment by superjunky** [comment]
Okay, so one more question before I switch to your supported Docker image:
Will it be possible to copy the persist and accessories dirs? I'm just not in the mood to setup my Homekit again (accessories, automations etc.)

**Comment by oznu** [comment]
As long as you mount `/homebridge` to wherever you mounted `/root/.homebridge` you should be fine.

Also follow the Readme to make sure you enable the UI.

You can also do a backup from the UI to make sure you have a copy of everything, restoring this will install all the plugins you use.

**Comment by superjunky** [comment]
Thanks for the info, I will consider switching images.

My neurotic mind is still wondering about this though:
> I wonder why it can be tailed from within the terminal, but not loaded from config.json as my own custom command.
> 
> No matter if it fails or not, I expect it to at least load the command.

**Comment by oznu** [comment]
Does your container set the HOMEBRIDGE_CONFIG_UI=1 variable?

**Comment by superjunky** [comment]
Yes it does

**Comment by superjunky** [comment]
If that's the case, then it would be nice for the options to modify the log settings to be disabled when that var is set. Let's call it a feature request for future noobies like me ;)

**Comment by oznu** [comment]
Just don't set that variable 😄

**Comment by superjunky** [comment]
HAhahha winner!

**Comment by superjunky** [comment]
Although it is needed to install plugins... And probably for restarting the container aswel.
It seems you wil get a new customer soon ;) Thanks again oznu
