### ISSUE TITLE
[Developer] Settings panel dropdown saves string "null" instead of removing parameter

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#665]
**Describe The Bug:**

When using a dropdown in the settings panel for a non-required string the config.json will store `"parameter": "null"` when selecting "None" in the dropdown.

**To Reproduce:**

Use e.g. homebridge-bravia and select "None" as TV input, see here: https://github.com/normen/homebridge-bravia/blob/master/config.schema.json

**Expected behavior:**

The settigs panel should remove the non-required variables where "None" is selected in the dropdown.

**Logs:**

- no errors -

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
v10.20.1
* **NPM Version**: 
v6.14.4
* **Homebridge Version**: 
v1.0.4
* **Homebridge Config UI X Version**:
v4.17.1
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
Raspbian 9 "Stretch
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
systemd

**Comment by oznu** [comment]
Hi @normen,

Can you test `4.17.3-test.6` (or latest `@test`) and let me know if the issue is resolved there?

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

Thanks.

**Comment by normen** [comment]
Yes it does, thanks!
