### ISSUE TITLE
Can not access GUI, Running on Mac Mini with OS X Server running

### ISSUE THREAD

**Issue by l80n63** [oznu/homebridge-config-ui-x#669]
Hi, I am having issues running my config UI. I can see that it is loading but can not access it from any computer or directly on the mini itself in a web browser. I have attached my config.json and log files. Happy to provide more details. I know there is some details missing in the Config file, they are removed for confidential reasons and therefore make the JSON invalid
[Archive 2.zip](https://github.com/oznu/homebridge-config-ui-x/files/4598735/Archive.2.zip)

**Comment by oznu** [comment]
Can you try uninstall / reinstall:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by l80n63** [comment]
I have tried that to no success, thank you for the fast reply

**Comment by oznu** [comment]
So the error is a little vague...

```
Caught Unhandled Rejection Error :: Details Below[0m
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

This pretty much means something that **should** be a *file* seems to be a *directory* instead.

Any ideas what might be causing that? Recent changes etc?

**Comment by l80n63** [comment]
That was resolved by removing the SSL component in my Config.json file. My OS X Server setup does have SSL enabled and tried adding to Homebridge for security. Haven't updated Node.js, home bridge or any plugins for a few days. The starupprocess for Homebridge in terminal reports no errors, states Homebridge is running (Checked on iOS and it was) but Homebridge UI is not accessible on port 8081 which the logs say it is on, tried on Chrome, Safari and Mac mini, Firewall has ports allowed for 8081 and port for home bridge

**Comment by oznu** [comment]
Can you post your logs again with the `EISDIR: illegal operation on a directory, read` issue resolved?

**Comment by oznu** [comment]
Also make sure you've restarted the service using:

```
sudo hb-service restart
```
