### ISSUE TITLE
Config editor

### ISSUE THREAD

**Issue by igitlin** [oznu/homebridge-config-ui-x#67]
it would be great to add the config editor in the form of entering data into the fields instead of the regular text editor, as well as automatically adding the default values to the config from the plug-in being installed.

**Comment by oznu** [comment]
The other homebridge ui plugins do this, in fact the original project this was forked from, [homebridge-config-ui](https://github.com/mkellsy/homebridge-config-ui) does this. However, I think they all fail at actually making it easier manage the config and are the source of many issues raised by the plugin users.

Plugins don't define their default config an any consistent way so knowing what the default config would be is pretty much impossible. If the upstream homebridge project got on board with a official definition of how to define required/optional config parameters this is certainly something I would like to implement.
