### ISSUE TITLE
Search field delete [X]

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#674]
Little suggestion... would be nice to have an icon to delete search field content fast. :) 

![Napkin 09 05 20, 6 28 53 PM](https://user-images.githubusercontent.com/3874239/81479354-f5e21800-9222-11ea-9549-415bd2393b89.png)

![np_delete_3325668_9E9E9E](https://user-images.githubusercontent.com/3874239/81479356-fbd7f900-9222-11ea-8a31-19d68ea28f88.png)

**Comment by oznu** [comment]
![image](https://user-images.githubusercontent.com/3979615/81558532-341d3a00-93d1-11ea-8e20-90cc42294cf4.png)

**Comment by oznu** [comment]
Hi @DJay-X 

Thanks for the great suggestion. This is available for testing in `4.19.0-test.1`.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by DJay-X** [comment]
Thanks. Works like expected. 👍
