### ISSUE TITLE
Issue with Node version

### ISSUE THREAD

**Issue by mac-n-cheese-uk** [oznu/homebridge-config-ui-x#675]
Hi, I'm seeing the following coming up in the logs on my Homebridge server (Mac Mini running Mojave):

`[5/9/2020, 11:08:39 PM] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^12.16.2 which does not satisfy the current Node version of v12.6.0. You may need to upgrade your installation of Node.`

If I run `node -v` it shows that I'm running v12.16.3 but config-ui reports v12.6.0.

I've uninstalled/reinstalled config-ui to see it that mad any difference but it's still picking up the old Node version from somewhere.

Any suggestions?

**Comment by oznu** [comment]
The UI does not bundle Node.js. You should upgrade Node.js using the same method you originally used to install it.

This might have been `brew` or just downloading the installer from the Node.js website.

**Comment by oznu** [comment]
If the UI is seeing a different version it probably means you have multiple versions of Node.js installed using different methods. Cleaning this up to make sure you only have one version of Node installed will prevent further strange behaviour.
