### ISSUE TITLE
Feature Request: download Homebridge log file and Homebridge Hue dump file

### ISSUE THREAD

**Issue by ebaauw** [oznu/homebridge-config-ui-x#676]
**Is your feature request related to a problem? Please describe:**

I get many support questions from users who don't know or understand their Homebridge configuration.  To troubleshoot my plugins, I really need the (full) Homebridge log file and the debug dump file that Homebridge Hue creates on startup.

I'd like for users to attach these to a GitHub issue, or upload them to Discord, rather than cutting/pasting large amounts of logs, often mangling the text.

**Describe the solution you'd like:**

Would it be possible for Homebridge Config UI X to allow the Homebridge log file and the Homebridge Hue dump file to be downloaded to the local machine (running the browser)?

To download the log file, I'd envision an option in the _View Logs_ windows, or under the menu, next to _Backup / Restore_.  To download the dump file, I'd envision an extra button (next to _NPM_, _UNINSTALL_, _SETTINGS_) on the plugin tile in the Plugins window.

Homebridge Config UI X already know where the Homebridge logs go.  The dump file is `homebridge-hue.json.gz` in the Homebridge user directory.

**Describe alternatives you've considered:**

I've described how to get these in my README, but that proves to be too cumbersome for many users.  See https://github.com/ebaauw/homebridge-hue#troubleshooting.

**Additional context:**

Homebridge Hue has masked IP addresses and API keys in `homebridge-hue.json.gz`.

**Comment by oznu** [comment]
![Screen Shot 2020-05-11 at 9 32 29 pm](https://user-images.githubusercontent.com/3979615/81557424-4a29fb00-93cf-11ea-9491-eeb902851181.png)

**Comment by oznu** [comment]
@ebaauw 

This is available for testing in 4.19.0-test.1.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by ebaauw** [comment]
Brilliant, @oznu, you’re a miracle worker!  I’ll update the Homebridge Hue README on the enxt release of Homebridge Config UI X.

Did you give any thoughts to downloading the Homebridge log file as well?

**Comment by oznu** [comment]
I think I'd rather the users copy/paste from the logs screen. 

This might not be ideal, but the logs, more often than they should, especially when running in debug mode, contain sensitive information which could compromise the users privacy.

At least when manually copying the logs they will be forced to glance at them to check.

**Comment by pradeepmouli** [comment]
Is this accessible in a generic way? I.e. for other plugins
