### ISSUE TITLE
Self-Signed SSL Certificate

### ISSUE THREAD

**Issue by eximiusvir** [oznu/homebridge-config-ui-x#68]
@oznu : This may be outside the scope of the config-ui-x plugin, but I would greatly appreciate a walkthrough for creating / binding a self-signed certificate to the port we configure for config-ui-x.

Creating the Self-Signed Certificate ([link](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps)) isn't hard, nor is the binding statement ([link](https://msdn.microsoft.com/en-us/library/ms733791(v=vs.100).aspx)); however, when I navigate to the port forwarded through my router, I'm unable to achieve a secure connection.

I'm sure this is a simple user education issue; however, after reading this article ([link](https://www.noip.com/support/knowledgebase/can-you-add-an-ssl-to-a-hostname-attached-to-no-ips-domain/)), I thought it would be really nice to be able to securely access my HomeBridge instance remotely.

If you've any tips, or **even a rough walkthrough here,** I'll commit to writing up a well formatted and fleshed out help document for others to follow.

**Comment by eximiusvir** [comment]
Was doing more reading on SSL with nodeJS servers and it looks like I was WAY off (I’m mostly familiar with Windows/IIS). 

Regardless, I’d still love this feature if it’s something you’d consider.

**Comment by iShift** [comment]
... and it would be perfect if you add support of lets encrypt for true https ...

**Comment by oznu** [comment]
Using a reverse proxy to achieve SSL is the method I recommend. Something like nginx is much more efficient when it comes to serving ssl traffic. 

I have been thinking of writing up a wiki article explaining how to do this, but there are already many guides available on the internet explaining how to set up let's encrypt using certbot and nginx.

[Nginx runs on Windows too!](http://nginx.org/en/docs/windows.html)

If you're running this in the [oznu/homebridge](https://github.com/oznu/docker-homebridge) docker image then I would recommend using this docker image, which I use, to add let's encrypt ssl support: https://github.com/linuxserver/docker-letsencrypt.

**Comment by pierrejochem** [comment]
I have configured openvpn for this issue. It is more secure to protect it via a VPN solution.

**Comment by oznu** [comment]
Added example nginx vhost to wiki: https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-SSL-with-Nginx
