### ISSUE TITLE
Failed to load node-pty module (Homebridge no longer starts) (still persist)

### ISSUE THREAD

**Issue by ItsNaud** [oznu/homebridge-config-ui-x#682]
Hello,

Unfortunately I still experience the issue reported in [https://github.com/oznu/homebridge-config-ui-x/issues/514](https://github.com/oznu/homebridge-config-ui-x/issues/514). First on an existing installation, after that I re-installed Raspbian and Homebridge.

**Environment:**

**Node.js Version:** v12.16.3
**NPM Version:** 6.14.5
**Homebridge Version:** 1.0.4
**Homebridge Config UI X Version:** 4.18.0

> [5/12/2020, 3:59:01 PM] Homebridge is running on port 51826.
> innerError Error: Cannot find module '../build/Debug/pty.node'
> Require stack:
> - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
> - /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
> - /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
> - /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
>     at Module.require (internal/modules/cjs/loader.js:1019:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:30:15)
>     at Module._compile (internal/modules/cjs/loader.js:1133:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
>     at Module.load (internal/modules/cjs/loader.js:977:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
>     at Module.require (internal/modules/cjs/loader.js:1019:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
>     '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js',
>     '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
>     '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'
>   ]
> }
> [5/12/2020, 3:59:02 PM] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 64. This version of Node.js requires
> NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).
> [5/12/2020, 3:59:02 PM] [Config] [node-pty] Node.js v12.16.3
> [5/12/2020, 3:59:02 PM] [Config] [node-pty] Failed to load node-pty module
> [5/12/2020, 3:59:02 PM] [Config] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
> [5/12/2020, 3:59:02 PM] [Config] [node-pty] Follow the steps below to resolve this issue.
> [5/12/2020, 3:59:02 PM] [Config] [node-pty] Trying to rebuild automatically...
> [5/12/2020, 3:59:26 PM] [Config] [node-pty] Module rebuilt successfully (maybe) - if you are still encountering errors follow the steps below.
> [5/12/2020, 3:59:26 PM] [Config] [node-pty] From the terminal run these commands (exact commands may vary):
> 
> [5/12/2020, 3:59:26 PM] [Config] cd /usr/local/lib/node_modules/homebridge-config-ui-x
> [5/12/2020, 3:59:26 PM] [Config] sudo npm rebuild --unsafe-perm
> 
> [5/12/2020, 3:59:26 PM] Got SIGTERM, shutting down Homebridge...

Also when I try to rebuild the plugin with the following it don't solve the problem:

`cd /usr/local/lib/node_modules/homebridge-config-ui-x`
`sudo npm rebuild --unsafe-perm`

Homebridge config:

> {
>   "bridge": {
>     "name": "Homebridge",
>     "username": "CC:22:3D:E3:CE:30",
>     "manufacturer": "homebridge.io",
>     "model": "homebridge",
>     "port": 51826,
>     "pin": "031-45-154"
>   },
>   
>   "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file cont$
>   "ports": {
>     "start": 52100,
>     "end": 52150,
>     "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
>   },
>   "accessories": [
>   ],
> 
>   "platforms": [
>     {
>       "platform": "config",
>       "name": "Config",
>       "port": 8080,
>       "sudo": true
>     }
> ]
> }

Any ideas?

Thanks for checking.

**Comment by oznu** [comment]
Can you share the output of these commands.


First, running as the user you run homebridge as, for example, `pi`:

```
node -v
which node
```

And also:

```
sudo node -v
sudo which node
```

**Comment by ItsNaud** [comment]
> Can you share the output of these commands.
> 
> First, running as the user you run homebridge as, for example, `pi`:
> 
> ```
> node -v
> which node
> ```
> 
> And also:
> 
> ```
> sudo node -v
> sudo which node
> ```

Hello oznu,

Thanks for your reply.

Here the outputs on user pi (also the user where I run homebridge):

pi@raspberrypi:~ $ node -v
v12.16.3
pi@raspberrypi:~ $ which node
/home/pi/.config/nvm/versions/node/v12.16.3/bin/node
pi@raspberrypi:~ $ sudo node -v
v10.19.0
pi@raspberrypi:~ $ sudo which node
/usr/bin/node

**Comment by oznu** [comment]
There is your problem. You have multiple versions of Node.js installed.

I'd probably just remove nvm and update Node.js the normal way.

If you can't figure out how, see https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux which will purge everything allowing you to start fresh.
