### ISSUE TITLE
Add disk usage widget

### ISSUE THREAD

**Issue by samuelcarreira** [oznu/homebridge-config-ui-x#685]
**Is your feature request related to a problem? Please describe:**
No, but it's useful to monitor the free disk space and it will be a nice addition to the memory and CPU usage.

**Describe the solution you'd like:**
Show the free disk space widget

**Additional context:**
You can add the fsSize feature of the systeminformation module, which produces the following result:
```
si.fsSize().then(data => console.log(data));
[
  {
    fs: '/dev/md2',
    type: 'ext4',
    size: 972577361920,
    used: 59142635520,
    use: 6.08,
    mount: '/'
  },
  {
    ...
  }
]
```

If it's useful I can write the code so you don't lose any time working on it. But if you want to write yourself the feature, I can wait for it to be implemented.

Thank you for your work

**Comment by samuelcarreira** [comment]
**status.service.ts**
```
 public async getDiskUsage() {
    return {
      diskUsage: await si.fsSize()
    };
  }

```


**./diskusage-widget/diskusage-widget.component.ts**
```
```

**Comment by Staubgeborener** [comment]
That cool, indeed, maybe open a new pull request @samuelcarreira ?

**Comment by samuelcarreira** [comment]
@Staubgeborener , should I write the feature or someone of the team will write it to make sure that it complies with the project structure and code styling?

**Comment by Staubgeborener** [comment]
I am not a developer of this code, but I would suggest to read the [CONTRIBUTING.md](https://github.com/oznu/homebridge-config-ui-x/blob/master/CONTRIBUTING.md), write the code (keeping the code styling as good as possible - it is quite manageable) and to open a pull request. With `npm run watch` you have a live environment of `homebridge-config-ui-x` to test your code.
