### ISSUE TITLE
Error: The requested platform 'config' has been registered multiple times. Please be more specific by writing one of: homebridge-config-ui.config, homebridge-config-ui-x.config

### ISSUE THREAD

**Issue by 18801054468** [oznu/homebridge-config-ui-x#69]
Error: The requested platform 'config' has been registered multiple times. Please be more specific by writing one of: homebridge-config-ui.config, homebridge-config-ui-x.config

2 at the same time? Or can only hold one

**Comment by oznu** [comment]
Please uninstall the `homebridge-config-ui`plugin. This plugin replaces it.

**Comment by 18801054468** [comment]
Thanks

**Comment by 18801054468** [comment]
How http://192.168.1.143:8080/accessories sets up access

**Comment by oznu** [comment]
I'm not sure what you are asking.

See https://github.com/oznu/homebridge-config-ui-x#accessory-control for info on accessory control.
