### ISSUE TITLE
Camera control -> Name of cam 

### ISSUE THREAD

**Issue by S474N** [oznu/homebridge-config-ui-x#690]
In Accessories have all cameras name as "Camera control".
![Homebridge-Camera_control](https://user-images.githubusercontent.com/16512337/82046554-6ec4f200-96b1-11ea-8b02-c21f611e91cb.png)

If user have defined "Name" in config.json, I think, that will better use this name, as name of cam.

Originally posted to plugin homebridge-camera-ffmpeg:
https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/issues/484

**Comment by oznu** [comment]
Can you click the cog (hover over tile) and show me what is there?

**Comment by S474N** [comment]
Of course:
![Camera](https://user-images.githubusercontent.com/16512337/82047046-6620eb80-96b2-11ea-87d7-25379796b0eb.png)

This is set in config.json in plugin homebridge-camera-ffmpeg.

**Comment by grzegorz914** [comment]
same for me, after added support for doorbell in ffmpeg-camera
<img width="866" alt="Zrzut ekranu 2020-05-17 o 08 22 43" src="https://user-images.githubusercontent.com/28867813/82137374-9df57380-9817-11ea-888e-67755962cb1a.png">
<img width="1708" alt="Zrzut ekranu 2020-05-17 o 08 22 15" src="https://user-images.githubusercontent.com/28867813/82137376-a0f06400-9817-11ea-91ee-d6e132ff9491.png">

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes
