### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by santheman-nl** [oznu/homebridge-config-ui-x#692]
It would be great if the UI could send out e-mail notifications if plugin updates or homebridge updates are available, so I don't have to check this every time.

**Comment by mbierman** [comment]
I just use cron

    15      3       *       *       *       npm update -g homebridge-config-ui-x@latest && echo $(date) update UI ... >> /homebridge/update.log

:tada:

**Comment by santheman-nl** [comment]
I am not so familiar with cron jobs in Homebridge, sorry

**Comment by mbierman** [comment]
1. Go to the three dots and choose `Terminal`.
1. type `crontab -e` and return. 
1. Copy and paste this line in at the end of that file.

			15      3       *       *       *       npm update -g homebridge-config-ui-x@latest

1. Save and close the file. The line above will update at 3:15am local time every day. You can change the time to anything you like. You can use a [tool ](http://www.cronmaker.com/?0)like this to help.

**Comment by santheman-nl** [comment]
Thanks, I did it directly on my Pi using Nano, I guess that works to?

**Comment by mbierman** [comment]
`crontab -e` does what is necessary to restart the cron daemon so your changes will take effect. Just using nano won't do that for you. A reboot or two might get things started properly but it is somewhat riskier.

**Comment by santheman-nl** [comment]
Thanks, eventually I did it the way you suggested. Thank you for your help!
