### ISSUE TITLE
Changing the login wallpaper

### ISSUE THREAD

**Issue by mbierman** [oznu/homebridge-config-ui-x#697]
**Is your feature request related to a problem? Please describe:**

In the current UI there is a box to customize the wallpaper. There is no hint about the path to the file. Ideally, this would be the homebridge storage path by default e.g. `/homebridge`.  it appears the default installation looks at: `/usr/local/lib/node_modules/homebridge-config-ui-x/public/assets` Using the storage path separates user customizations from the default install which could be overwritten during updates.

If there is a way to set the path to the storage to the storage path it isn't clear. 

I also notice that even putting an image in `/usr/local/lib/node_modules/homebridge-config-ui-x/public/assets` and then using the ui to set an image filename doesn't seem to work. Maybe there is something that just isn't obvious about how to make this work properly.

**Describe the solution you'd like:**

1. Put some text to let the user know how to customize. Since you know the storage path, you could note that everything will go from there (i.e. include their actual storage path in the instructions). So if the user wants to just drop the image in there all they need to do is put the name (with no path). If they want it under a directory within their storage path they could put `/foldername/image.jpg`
1. Update the wiki to explain how this works. 

**Describe alternatives you've considered:**
1. Another option would be to just let the user drop a file into their storage directory. If it is there, use is as wappaper. e.g. `/homebridge/wallpaper.jpg` would override the default wallpaper without requiring the user to set it. 
1. Lastly, provide a filepicker to let the user choose the file and use that to set the file so users don't have to worry about relative vs absolute paths, etc. 

**Additional context:**

**Comment by oznu** [comment]
Thanks. I'm probably going to go with option 2 and allow the user to upload a file.

**Comment by oznu** [comment]
> Another option would be to just let the user drop a file into their storage directory. If it is there, use is as wappaper. e.g. /homebridge/wallpaper.jpg would override the default wallpaper without requiring the user to set it.

The wallpaper will load from `<homebridge-storage-path>/ui-wallpaper.jpg` if it exists. eg. `/homebridge/ui-wallpaper.jpg`

![image](https://user-images.githubusercontent.com/3979615/82665875-05784c80-9c78-11ea-87e7-c721483defbe.png)

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

Uploading a file will come later, it's a bit tricky to add at the moment as I'm using the automatically generated settings for for the UI still.

**Comment by mbierman** [comment]
SWEET! Thank you. Working perfectly.
