### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by rchoughton** [oznu/homebridge-config-ui-x#7]
I have tried to use the log file two different ways and have issues with both.  I would appreciate some help.  

Here is the first way:
in the config.json file:
"log": "/var/log/daemon.log",

In the web gui I see nothing and the system crashes and restarts.  Here is the error I get from the log file.:
Dec 31 05:57:24 XXX homebridge[832]: fs.js:1453
Dec 31 05:57:24 XXX homebridge[832]: throw error;
Dec 31 05:57:24 XXX homebridge[832]: ^
Dec 31 05:57:24 XXX homebridge[832]: Error: watch /var/log/daemon.log EACCES
Dec 31 05:57:24 XXX homebridge[832]: at exports._errnoException (util.js:1020:11)
Dec 31 05:57:24 XXX homebridge[832]: at FSWatcher.start (fs.js:1451:19)
Dec 31 05:57:24 XXX homebridge[832]: at Object.fs.watch (fs.js:1478:11)
Dec 31 05:57:24 XXX homebridge[832]: at Tail.watch (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/tail/lib/tail.js:112:32)
Dec 31 05:57:24 XXX homebridge[832]: at new Tail (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/tail/lib/tail.js:84:10)
Dec 31 05:57:24 XXX homebridge[832]: at tailLogFromFile (/usr/lib/node_modules/homebridge-config-ui-x/lib/wss-logs.js:13:14)
Dec 31 05:57:24 XXX homebridge[832]: at WebSocketServer.wss.on (/usr/lib/node_modules/homebridge-config-ui-x/lib/wss-logs.js:72:7)
Dec 31 05:57:24 XXX homebridge[832]: at emitTwo (events.js:106:13)
Dec 31 05:57:24 XXX homebridge[832]: at WebSocketServer.emit (events.js:191:7)
Dec 31 05:57:24 XXX homebridge[832]: at handleUpgrade (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ws/lib/WebSocketServer.js:87:16)
Dec 31 05:57:24 XXX homebridge[832]: at WebSocketServer.completeUpgrade (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ws/lib/WebSocketServer.js:288:5)
Dec 31 05:57:24 XXX homebridge[832]: at WebSocketServer.handleUpgrade (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ws/lib/WebSocketServer.js:227:10)
Dec 31 05:57:24 XXX homebridge[832]: at Server.WebSocketServer._ultron.on (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ws/lib/WebSocketServer.js:86:14)
Dec 31 05:57:24 XXX homebridge[832]: at emitThree (events.js:116:13)
Dec 31 05:57:24 XXX homebridge[832]: at Server.emit (events.js:194:7)
Dec 31 05:57:24 XXX homebridge[832]: at onParserExecuteCommon (_http_server.js:409:14)
Dec 31 05:57:24 XXX homebridge[832]: at HTTPParser.onParserExecute (_http_server.js:377:5)

Also tried this in the config.json file:
"log": {
                "tail": "sudo tail -f /var/log/daemon.log"
            },

Error I receive in the web gui:
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
The log tail command "sudo tail -f /var/log/daemon.log" exited unexpectedly with code 1. Please check the command in your config.json is correct.

**Comment by oznu** [comment]
The errors shown with the first way is because your homebridge process user does not have the required permissions to access the log file. 

For your second attempt using tail, you'll need to configure the homebridge process user to have password-less sudo access to prevent that error - see https://serverfault.com/a/596988

I'm going to close this issue in favour of the currently open one here: https://github.com/oznu/homebridge-config-ui-x/issues/2
