### ISSUE TITLE
Accessories web pages cannot display devices

### ISSUE THREAD

**Issue by 18801054468** [oznu/homebridge-config-ui-x#70]
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3E:E4:DE:32",
        "port": 51826,
        "pin": "001-01-001"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "6060",
            "ssl": 0,
            "roomid": 2,
            "mqtt": 1
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": false
        }
    ],
    "accessories": []
}

手机上可以显示设备，网页里面无法显示：http://192.168.1.143:8080/accessories
设备是Domoticz插件里面的。

The homebridge -I command has been used

**Comment by 18801054468** [comment]
The device can be displayed on the mobile phone, which can not be displayed on the web page: http://192.168.1.143:8080/accessories

The device is inside the Domoticz plug-in.

**Comment by 18801054468** [comment]
The homebridge -I command has been used

**Comment by oznu** [comment]
Can you provide the homebridge logs / screenshots?

**Comment by 18801054468** [comment]
Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:96:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by oznu** [comment]
I'm going to need the logs from the homebridge instance running with `-I`.

**Comment by 18801054468** [comment]
Log file does not exist: /var/log/homebridge.stdout.log
Please set the correct path to the logs in your Homebridge config.json file.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

**Comment by 18801054468** [comment]
/root/.pm2/logs/homebridge-error-0.log last 15 lines:
0|homebrid | *** WARNING *** Please fix your application to use the native API of Avahi!
0|homebrid | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
0|homebrid | *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
0|homebrid | *** WARNING *** Please fix your application to use the native API of Avahi!
0|homebrid | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
0|homebrid | *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
0|homebrid | *** WARNING *** Please fix your application to use the native API of Avahi!
0|homebrid | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
0|homebrid | [2018-3-30 13:52:46] Plugin /usr/lib/node_modules/homebridge-config-ui does not contain a package.json.
0|homebrid | [2018-3-30 13:52:59] [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.
0|homebrid | [2018-3-30 13:53:29] [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.
0|homebrid | [2018-3-30 13:54:33] [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.
0|homebrid | [2018-3-30 13:57:01] [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.
0|homebrid | [2018-3-30 14:29:07] [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.
0|homebrid | [2018-3-30 14:29:09] [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.

**Comment by oznu** [comment]
> [Config] Homebridge must be running in insecure mode to view and control accessories from this plugin.

You need to run Homebridge with the `-I` flag from your process supervisor. Which looks like it could be `pm2`?

This message will only show up if homebridge is not running in insecure mode.

**Comment by 18801054468** [comment]
Is pm2, I uninstall pm2

**Comment by 18801054468** [comment]
Thanks, OK
