### ISSUE TITLE
2FA different Homebridge with same user

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#706]
Hi @oznu 

if U enable 2FA on two different Homebridge and both use same user name and pass to login then if U want add it to the Authenticator app, the firs added will be replaced with the next one and have no possibility to login to the firs one HB.

**Comment by oznu** [comment]
Which app did you use as an authenticator?

The Google Authenticator seems to accept two user accounts with the same username, but can imagine others might replace an existing TOTP with the same username.

**Comment by grzegorz914** [comment]
Authenticator from Microsoft

**Comment by oznu** [comment]
Ok tested that app and was able to see the warning. It's an easy fix.

**Comment by oznu** [comment]
Should be fixed in the latest test. Thanks for reporting before this went live 😄
