### ISSUE TITLE
How homebridge -I mode boot from Kai ？

### ISSUE THREAD

**Issue by 18801054468** [oznu/homebridge-config-ui-x#71]
How homebridge -I mode boot from Kai ？

**Comment by 18801054468** [comment]
Raspberry Pi homebridge -I boot automatically starts

**Comment by 18801054468** [comment]
How to set

**Comment by oznu** [comment]
Hi @18801054468,

You need to set the `-I` flag using whatever process manager you are using. Since every system setup is different figuring out where to add this flag is up to you.
