### ISSUE TITLE
Issue with node gyp

### ISSUE THREAD

**Issue by thesquaremedia** [oznu/homebridge-config-ui-x#710]
**Describe The Bug:**

getting an error when starting homebridge

**To Reproduce:**

**Expected behavior:**

**Logs:**

Error: The module '/Users/xavierserrano/.nvm/versions/node/v10.8.0/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).[0m
```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
{
		"platform": "config",
		"name": "Config",
		"port": 8080,
		"theme": "theme",
		"log": {
			"method": "file",
			"path": "/Users/xavierserrano/.homebridge/logfile.log"
		},
		"restart": "launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist"
	}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v10.8.0
* **NPM Version**: 6.2.0
* **Homebridge Version**: 0.4.50
* **Homebridge Config UI X Version**: downgraded to 3.8.0 latest didnt work either.
* **Operating System**: macOS
* **Process Supervisor**: launchctl

I tried uninstalligin and rebuilding under the '/Users/xavierserrano/.nvm/versions/node/v10.8.0/lib/node_modules/ directory with and without sudo and nothing.

**Comment by oznu** [comment]
There is something not right with your nvm install.

I'd start by cleaning up nvm, remove any existing homebridge services, and reinstalling the latest version.
