### ISSUE TITLE
Socket Hang up

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#712]
**Describe The Bug:**
As in log socket sometimes hang up and with this data in HomeKit app is not refresh

**To Reproduce:**

**Expected behavior:**

**Logs:**
[Web UI] Failed to refresh characteristics for 1:0:1:13ED:5DC:13E:820000:0:0:0:: socket hang up

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
{
            "name": "Web UI",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "debug": false,
            "accessoryControl": {
                "debug": false
            }
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 14.3
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.0
* **Homebridge Config UI X Version**: 4.20.1.test 6
* **Operating System**: Raspbian  / macOS 
* **Process Supervisor**: hb-service

**Comment by VaderMester** [comment]
I'm having the same issue. Tried many things, to mitigate it did not work.
Interestingly, these messages only show up in the log, if I restart HB through the WEB UI, however it seems a symptom of this is that in Home App - after Updating - stay as Not Responding.
Accessories respond correctly from UI in insecure mode.
