### ISSUE TITLE
Plugin Author/NPM link not the same value than package.json file

### ISSUE THREAD

**Issue by NebzHB** [oznu/homebridge-config-ui-x#717]
Hi,

the Plugin Author is not the same value than the plugin's package.json file, it's the npm value (if we have a custom plugin installed (not published), it's stated wrong), and in this case, it should not link to the npm repo but to the original github repo it was installed from.

**Comment by oznu** [comment]
Change the name of your custom plugin so it's not the same name as the published version. There is no way to know if you installed a plugin from GitHub or npm or manually once it's on disk.

**Comment by NebzHB** [comment]
yes in the package.json _from

**Comment by oznu** [comment]
That is added by npm after the fact. If you aren't running the "npm" version of the plugin, then it should have a different name.

**Comment by NebzHB** [comment]
it's npm installed with git

name change is not very a solution here, plugin is provided to thousand of users...

**Comment by oznu** [comment]
Which plugin?

**Comment by NebzHB** [comment]
NebzHB/homebridge-jeedom

**Comment by oznu** [comment]
Installing via git is not supported in the UI either. Are you planning on publishing your version of the plugin for others to use?

**Comment by NebzHB** [comment]
this plugin is embedded in the french Jeedom Domotic software, so there is no use to install it out of this system, that's why i didn't published it

**Comment by NebzHB** [comment]
or maybe a way to ignore a plugin in the display ? i don't mind if it's just not present ;)

that would be a more generic solution for you...

**Comment by oznu** [comment]
What is the relationship with https://www.npmjs.com/package/homebridge-jeedom?

**Comment by NebzHB** [comment]
absolutly none, it's a fork from another plugin named the same

**Comment by oznu** [comment]
In your package.json file, if you set `private`: `true` it will not not query npm for plugin information.

**Comment by NebzHB** [comment]
ok that's way better !!! any solution to avoid the "Uninstall" button ? i've seen there is only an exception for config-ui-x ...

**Comment by oznu** [comment]
Are you using this in a commercial application?

**Comment by NebzHB** [comment]
no, the application is free

**Comment by oznu** [comment]
Checked your forums, all seems fine :)

**Comment by oznu** [comment]
> ok that's way better !!! any solution to avoid the "Uninstall" button ?

No, not avoidable. You could always revoke file system permissions for the Homebridge user for where the plugin is installed.

**Comment by NebzHB** [comment]
no, then it's ok, i'll just teach the end users ;)

thank you for your help

**Comment by oznu** [comment]
I would still recommend changing the plugin name and publishing to npm, the users config will not have to change, or the github repo, and then your users will be able to update via the UI.

You can use a scope like `@jeedom/homebridge-jeedom`

**Comment by NebzHB** [comment]
no need for that, jeedom's ui is doing that + I only give the opportunity to users to manage their own personnal third party homebridge plugins in an easier way than the config.json file.

**Comment by rsm1024** [comment]
thank you.

[serrurier lyon](https://articoin.fr/serrurerie/auvergne-rhone-alpes/rhone-69/lyon-6eme-arrondissement-69006/serrurier-lyon-6eme-arrondissement-69006)
