### ISSUE TITLE
Status Page 'Hangs'

### ISSUE THREAD

**Issue by greztaylor** [oznu/homebridge-config-ui-x#718]
Over the course of the last week the 'Status' page on the Homebridge Config UI X has begun to hang on my MacOS.  I can navigate to the Plugins, Config, Accessories tabs without issue which all function as expected  however as soon as I open the 'Status' tab the page hangs. The 'Checking for updates' cog continues to turn, Homebridge Logs never update, the Accessories widget never load on the page nor does the QR code fully.  Homebridge is still working and I can access and control my devices in the Home app throughout without issue.  Any suggestions?

**Comment by oznu** [comment]
I'll need logs etc. please to help out with this.

**Comment by oznu** [comment]
Hi @greztaylor can you try the current `@test` version of the UI to see if this helps?

I assume you set up homebridge using the `hb-service tool`.

I've made some changes to the way the log file is managed by `hb-service` which may fix this lock up.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by oznu** [comment]
99% sure this is the same issue: #731
