### ISSUE TITLE
Improvement: Update NodeJS / NPM

### ISSUE THREAD

**Issue by timwegenerDE** [oznu/homebridge-config-ui-x#726]
Hi there,

first of all: I love Config UI! Thanks to everyone who are developing this plugin!

In the past I often receive the message that it‘s recomended to update NodeJS for several plugins. For me it‘s not a big thing, but it would be awesome if there was the possibility from the UI to upgrade NodeJS and NPM; Or the possibility to choose the desired version.

Thanks in advance.

**Comment by Olepir** [comment]
What are you using for running Homebridge? Just install Node.js and NPM same as you did before and update Homebridge and all your plugins.

**Comment by timwegenerDE** [comment]
I'm running homebridge nativ on a raspberry. As I said, for me it's not a big deal. However I think for someone who's just using Homebridge (e.g. when I set it up for them) it could be a real benefit if you could update Node.Js and/or NPM from the UI so there is no need for using the terminal.

**Comment by oznu** [comment]
Updating Node.js and NPM often require more permissions than the Homebridge/UI process runs with. This is certainly the case for any installs that followed the Homebridge Wiki in the last 12 months.

The [Homebridge Raspberry Pi Image
](https://github.com/homebridge/homebridge-raspbian-image) does have a helper tool to ensure Node.js is updated correctly every time.

https://github.com/homebridge/homebridge-raspbian-image#updating-nodejs
