### ISSUE TITLE
Latest Update keeps failing

### ISSUE THREAD

**Issue by Crox77** [oznu/homebridge-config-ui-x#727]
**Describe Your Problem:**

Every time I try to update to the latest version I keep getting this error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@3.0.2 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@3.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Crox-iMac/.npm/_logs/2020-06-01T20_02_34_500Z-debug.log

In fact every update or NPm I try to install keeps getting this, any ideas please?

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
> In fact every update or NPm I try to install keeps getting this, any ideas please?

This suggested it's a npm/node.js issue.

I'd remove any trace of Node.js and install it again using the instructions in the Homebridge wiki macOS guide.

> npm ERR! sodium@3.0.2 preinstall: node 

Not sure where this is coming from, the UI does not use this package.

**Comment by Crox77** [comment]
Thanks, by removing the node.js will this remove all my Homebridge?

**Comment by oznu** [comment]
Reinstalling Node.js won't remove your homebridge config or HomeKit pairing.

**Comment by Crox77** [comment]
What about all my other NPR’s/

**Comment by Crox77** [comment]
Sorry autocorrect npm’s

**Comment by oznu** [comment]
You may need to reinstall your other plugins.

**Comment by oznu** [comment]
If you're still having issues, I adapted a guide for Linux to work on macOS as well that might help:

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-macOS
