### ISSUE TITLE
Cannot reset password, cannot find auth.json on raspberry pi

### ISSUE THREAD

**Issue by shahtirathk** [oznu/homebridge-config-ui-x#728]
**Describe Your Problem:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
The full path to the auth.json file is printed in the logs when you input an incorrect password. It's in the same folder as your config.json file.
