### ISSUE TITLE
Status: Homebridge never shows "running" on Pi3

### ISSUE THREAD

**Issue by thatguychad** [oznu/homebridge-config-ui-x#73]
I'm running homebridge as user homebridge and using systemd (rasbian on Pi3). I have logs working with journalctl and everything else works (except for permissions when editing config.json since it needs to write as user homebridge), but it bothers me that I can't get the status to work.

**Comment by oznu** [comment]
Hi @thatguychad,

Without the logs I can only guess why this might be happening.

The plugin reads your `config.json` to determine what port homebridge is running on. It then makes a http request to `localhost` on that port to test if homebridge is running.

https://github.com/oznu/homebridge-config-ui-x/blob/master/src/wss/status.ts#L118-L131
