### ISSUE TITLE
"loading logs using native method..." hangs raspberry pi

### ISSUE THREAD

**Issue by ssllii** [oznu/homebridge-config-ui-x#731]
**Describe The Bug:**
After logging in to the UI, the raspberry pi hangs.  I can still get a ping response, but no response with putty.  The remote desktop session that I was on just sits there, did not disconnect but also no response.  Power off/on seems like the only recovery possible.
This happened with homebridge v1.0.4 and v1.1.0.  

**To Reproduce:**
Seems to happen whenever the Config-UI idle timeouts.  Then I tried to log back in as Admin.  As the status screen showed up, the log screen started showing "loading logs using native method...", then it happens. It does not fail the first time after reboot.  Forcing a logout and then logging back in is also ok.
![homebridge-config-ui](https://user-images.githubusercontent.com/29691593/83573661-c13f4480-a4e0-11ea-848f-c6297990fb32.png)

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**:   v1.1.0
* **Homebridge Config UI X Version**: v4.19.0
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
Hi @ssllii can you try the current `@test` version of the UI to see if this helps?

I've made some changes to the way the log file is managed by `hb-service`.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by ssllii** [comment]
thanks for the quick response.
It did not fail this morning.  I will let it run with v1.1.0/v4.19.0 for a few more days before trying out your test version.  Hope that's alright with you.

**Comment by jplongo** [comment]
I tried the @test version (4.21.1-test.4 but seems to have the same issue. Can’t solve it by rolling back both homebridge and Homebridge ux. 

An abort signal is sent from main.js:29123 <string too long> when trying to show log. And Homebridge service is restarted. This is why we receive a request timeout. 
There is an open request on [Homebridge github repo](https://github.com/homebridge/homebridge/issues/2585#issuecomment-633111075) . 

But I think the issue come from Homebridge-ux. 

Any idea about this issue ??

**Comment by jplongo** [comment]
I edit my post and after two restart I can confirm that the 4.21.1-test.4 solve the issue when loading log file. 
But there is a side effect and my devices stop working. I have them in my Home app but open/close actions don’t do anything. 

I will check your code and try to find an issue in debug mode.

**Comment by ssllii** [comment]
@oznu , I don't believe the issue here is exactly the same as #718, when my "hang" happens, ping is the only thing that works, not even PUTTY gets any response.  Homebridge is out cold.

@jplongo, have you tracked down the cause of the side effect of the test version, 4.2.1.1-test.4?

**Comment by oznu** [comment]
Is this still an issue on the latest versions?

**Comment by ssllii** [comment]
It is still happening to me with v1.1.6.
The system responds to ping but I can't get a response with SSH.
So it has crashed but it only responds to ping.
