### ISSUE TITLE
clean up config.json history files

### ISSUE THREAD

**Issue by mbierman** [oznu/homebridge-config-ui-x#732]
**Is your feature request related to a problem? Please describe:**
`config.json.*` history files are stored in the top level of a user's homebridge install. This can be cumbersome. (I have over 150 of these files at the moment). 

**Describe the solution you'd like:**
store them in a sub directory by default (e.g.` /homebridge/confighistory`)

**Describe alternatives you've considered:**
I can't think of a cleaner solution other than something complex like a database or checking in changes to github, which are overkill.

**Additional context:**

**Comment by oznu** [comment]
There is a button in the UI that deletes all of these. On the config editor tab, click restore, scroll down, then remove old backups.

**Comment by mbierman** [comment]
Yes, but I can imagine someone saying, "I want to be able to revert to previous versions." and still wanting to reduce clutter. Sticking them in a sub folder just seemed like a nice touch. The active file could still be at the root level. But stick edits one level down. 

Just a thought.

**Comment by taw123** [comment]
Perhaps a better refinement of this request might be to keep a rolling history for config.json files. [not going to touch the question of location].

Add a user configurable option to optionally roll off config.json history files automatically by either number files or date  (X files, or keep last X days/weeks/months).

Just a thought, if you find yourself with copious free time, not like it isn't hard to add a simple cleanup script hung on cron job myself.... If it really bothered ME  😀

--Tom

**Comment by mbierman** [comment]
Agreed. A script isn't complicated but this seems like functionality that should be baked in. I like your suggestion though.

**Comment by oznu** [comment]
As of v4.29.0 config backups will be stored in `./backups/config-backups`.

The folder path will be created on start - if the path cannot be created and does not already exist (for example, it might be a file), the original storage location will be used and a warning will be shown in the log.

The most recent 100 backup files will be migrated to the new location on the restart following this update.

**Comment by mbierman** [comment]
Awesome! Thanks.

**Comment by oznu** [comment]
v4.31.0 will complete this task by periodically removing config.json backups older than 60 days.
