### ISSUE TITLE
Timeout too soon

### ISSUE THREAD

**Issue by macjeff** [oznu/homebridge-config-ui-x#733]
**Describe The Bug:**
I have been using homebridge on a mac for years in terminal.  I just installed HomeBridge UI X yesterday and love it.  But every few hours the login screen comes up.  I set the timeout in advanced settings to the max which I think it like 100 days.  So it should not be timing out.  Problem is I cant sit and stare at it all day so no idea exactly when it goes back to login screen because nothing in log or anything.  Otherwise it seems to be working

For now I turned off AUTH to see if that helps but since I want to open this up to check on my iphone when not home I think I should have AUTH even though I use a different port.

**To Reproduce:**
Just run homebridge and check on it every hour.  Within a few hours its down

**Expected behavior:**

**Logs:**
Please tell me what log files you want and where they are.  The regular homebridge log shows nothing.

I attached regular homebridge logs and Config file

[config.json.zip](https://github.com/oznu/homebridge-config-ui-x/files/4730761/config.json.zip)
[Homebridge logs.zip](https://github.com/oznu/homebridge-config-ui-x/files/4730764/Homebridge.logs.zip)

**Environment:**

* **Node.js Version**: <14.4.0>
* **NPM Version**: <6.14.5>
* **Homebridge Version**: <1.1.0>
* **Homebridge Config UI X Version**: 4.21.0
* **Operating System**: macOS 
* **Process Supervisor**: hb-service

**Comment by macjeff** [comment]
dont think I mentioned when I log back in homebridge is still running so it does not go down.  I just dont want it to logme out as i want it to display status at all times.  I can live with one logout every month or so but not every few hours.

**Comment by macjeff** [comment]
two things.  I turned on debug logging for the UI.
and
When I changed the session time to the MAX I saw the config update get changed in the log but I did not restart homebridge.  It was saved in the preferences but maybe I needed to restart homebridge for it to take effect so I just did.  It went down 3 times in 22 hours so if it makes it until tomorrow morning I will close this issue.

**Comment by macjeff** [comment]
UPDATE- Bug confirmed.  Ran 15 hours with NO AUTH and did not have any issues

Turned AUTH back on and was out for about 4 hours.  Came back and it was on login screen.

I noticed there is old bug EXACTLY this one saying AUTH would timeout before the setting.  It is back i guess.

**Comment by oznu** [comment]
You will need to restart and logout and log back in for the change to take effect. 

`86400000` seconds is 1000 days, and the expiry is embeded in the [JWT token](https://jwt.io/). This seems to be working.

![image](https://user-images.githubusercontent.com/3979615/83942263-6e91bf80-a835-11ea-9abd-828a14b5b574.png)

**Comment by macjeff** [comment]
I just totally rebooted the machine and logged in again.  We will know later today.
Please leave open.

**Comment by macjeff** [comment]
by the way every time previously I made any change (after the first time) I used the RESTART button in the admin.  This time I totally rebooted the computer.  I will update in 6 hours.  Never gone that far on AUTH but went over a day in NO AUTH.

**Comment by macjeff** [comment]
After a complete restart it seems to be working.  I thought clicking the power button to restart homebridge would do the same thing?   I will close this in AM if still running

**Comment by macjeff** [comment]
OK a complete reboot seemed to stop this.   Before we close this....does every change require a complete restart of the system?   If so why the restart homebridge button in the interface.

**Comment by oznu** [comment]
No. You just need to restart AND logout for that particular change.
