### ISSUE TITLE
Link to GitHub 

### ISSUE THREAD

**Issue by Bankaifan** [oznu/homebridge-config-ui-x#74]
Hey, would it be possible to make an link to the regarding github-link like the already available NPM-Link?

**Comment by pierrejochem** [comment]
@oznu: It should be easily possible. It is included in the npm registry request but not defined in your service.

```
"versions": {
    ...
      "repository": {
        "type": "git",
        "url": "git+https://github.com/XXX/YYY.git"
      },
.....
```

@Bankaifan: If you are able to do it by your own then you just need to adapt the follwing files:

==>  homebridge-config-ui-x/src/pm.ts (getting the details from npm registry)
==>  homebridge-config-ui-x/ui/src/app/plugins/plugins.component.html (view template)

I'm pretty sure that pull request are welcome here ;-)

**Comment by oznu** [comment]
Thanks @pierrejochem. The original reason I did not include this was some plugin owners weren't adding their repository attributes in the `package.json`, and some even used BitBucket (why would you...?).

The`homepage` attribute might be more universal. NPM will *usually* set this to be the url of the GitHub project page if npm has been told which repo it is:

```sh
npm view homebridge-config-ui-x homepage
# https://github.com/oznu/homebridge-config-ui-x#readme
```

But it also handles the BitBucket exceptions:

```sh
npm view homebridge-plugin-chromecast homepage
# https://bitbucket.org/robertherber/homebridge-chromecast#readme
```

The upside of doing it this way would be that it matches what npmjs.org displays.
