### ISSUE TITLE
Can i install this plugin in an existant homebridge installation

### ISSUE THREAD

**Issue by CyberChris79** [oznu/homebridge-config-ui-x#740]
Hi there,

i already installed homebridge as a service as root and my config.json is located in /root/.homebridge/
So my question is, if this plugin recognizes this directory and use this one, or creates a new instance with a config.json in /var/homebridge/.

I want to use my existent configuration, and don't want to add another user called "homebridge"

Thank you very much.

Christian

**Comment by oznu** [comment]
You can. You can install and configure it like a normal plugin.

https://github.com/oznu/homebridge-config-ui-x#configuration

**Comment by CyberChris79** [comment]
Hello oznu,

thank you for your fast reply.
Last time i install this plugin, it created me the config.json in /var/homebridge/ and not /root./homebridge/ and also it created me an user called "homebridge"
In the paramater settings https://github.com/oznu/homebridge-config-ui-x#configuration there ist just the information about the log file location, but not the config.json.

**Comment by oznu** [comment]
If you just install it as a plugin, it will not create any config.json. It will use the one you configured it in.

**Comment by oznu** [comment]
Install as you would any other plugin:

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

Add this to your existing config.json, in the "platforms" section:

```json
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": false
    }
```

Restart, and you'll be able to access the UI. 

You will need to configure the log viewer manually in a way that suits your environment - but you can do that from inside the UI once it's setup.

The only time the UI would try and create its own config file is if you followed one of the guides to setup homebridge as a service using `hb-service` - this is optional.

**Comment by CyberChris79** [comment]
Ah i understand.

Thank you for your help and detailed explanation.
I will do so.

Greetings
Christian

**Comment by CyberChris79** [comment]
Hello oznu,

thank you, it works great, but after the installation of the plugin, I got no write access to the config.json in /root/.homebridge with my pi ftp user. 

How can I solve this?

Thank you very much

Christian
