### ISSUE TITLE
Where is release notes pulled from?

### ISSUE THREAD

**Issue by THX723** [oznu/homebridge-config-ui-x#744]
**Describe Your Problem:**
When updating plug-in: [homebridge-platform-insteonlocal](https://github.com/kuestess/homebridge-platform-insteonlocal), am seeing the wrong release notes displayed. Where does Homebridge-config-gui-x get the release notes from?

**Screenshots:**
Got this ...
<img width="845" alt="Screen Shot 2020-06-17 at 2 29 33 PM" src="https://user-images.githubusercontent.com/25112621/84953539-8f190f80-b0a8-11ea-9782-45f8610bca0f.png">

was expecting [this](https://github.com/kuestess/homebridge-platform-insteonlocal/blob/master/CHANGELOG.md) ...
<img width="872" alt="Screen Shot 2020-06-17 at 9 48 45 PM" src="https://user-images.githubusercontent.com/25112621/84979699-e9d05c80-b0e4-11ea-8008-978b9a9ec62d.png">

**Comment by oznu** [comment]
Here:

https://github.com/kuestess/homebridge-platform-insteonlocal/releases
