### ISSUE TITLE
migrate existing homebridge instances to hb-service

### ISSUE THREAD

**Issue by divemasterjm** [oznu/homebridge-config-ui-x#749]
**Describe Your Problem:**

i want to migrate existig homebridge instances to hb-service, is that possible without losing configurations?
can i create service with same name and config and start working without touching anything in homekit?
**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
As long as your existing storage folder is, or copied to `/var/lib/homebridge` then your existing connection to HomeKit won't be affected.

Make sure you stop and delete any exisiting services first.

**Comment by oznu** [comment]
That response assumes Linux.

**Comment by divemasterjm** [comment]
i have mac os

**Comment by oznu** [comment]
As long as your storage folder is in `~/.homebridge` and you remove and delete your existing service first then it should be fine.

**Comment by oznu** [comment]
Stop:

launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist

Delete:

~/Library/LaunchAgents/com.homebridge.server.plist

**Comment by divemasterjm** [comment]
thanks

**Comment by divemasterjm** [comment]
command for creating existing service?

**Comment by oznu** [comment]
Check out the wiki guide:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#step-2-install-homebridge-and-homebridge-config-ui-x

**Comment by divemasterjm** [comment]
I did, but there is no specific comment for migrating existing ones, that’s why I ask, don’t want to loose anything I hace already 5 instances with more than 150 accessories and a lot of automations on HomeKit

**Comment by oznu** [comment]
Yeah, so if your config is already in `~/.homebridge ` you won't loose anything 😄

**Comment by oznu** [comment]
You can make a backup first if you want to be safe.

**Comment by divemasterjm** [comment]
Do you recommend to migrate?

**Comment by oznu** [comment]
If you have a working setup then it's probably not nessesary.

**Comment by divemasterjm** [comment]
Thanks I thought it was worth of it and give more stability and/or performance

**Comment by oznu** [comment]
It certainly makes it much easier to get setup and running as a service using the same command across multiple platforms, and enabled you to keep the UI online even while Homebridge is crashing.

If your existing instance config is in `~/.homebridge` then removing your existing service files and running `sudo hb-service install` should be all you have to do. If you are running the UI already you may wish to make a back first:

https://github.com/homebridge/homebridge/wiki/Backup-and-Restore
