### ISSUE TITLE
config-ui-x breaks homebridge-apple-tv plugin

### ISSUE THREAD

**Issue by normen** [oznu/homebridge-config-ui-x#75]
Hi,

it seems this plugin is causing issues in another homebridge plugin for some reason:

https://github.com/lprhodes/homebridge-apple-tv/issues/9

**Comment by oznu** [comment]
Can you post the homebridge logs showing from startup? Knowing the order that the plugins get loaded in on your system might be helpful.

Are you running on a Raspberry Pi 3?

**Comment by normen** [comment]
Yeah, I noticed that config-ui-x increases the load time a lot. It is a RasPi3 in my case and yes, this change makes my homebridge setup discover the Apple TV with config-ui-x enabled.

In general the startup of Homebridge is much faster now, before config-ui-x would always warn me that the server takes a long time to start ^^

**Comment by oznu** [comment]
Great, thanks for testing. I'm going to run this test version for the next few days to make sure everything is ok before publishing it. Let me know if you encounter any quirks.

If it works well I might make it the default behaviour in the next major version.

**Comment by palasinio** [comment]
This multithreading thing sounds great.

**Comment by normen** [comment]
Yeah, and it seems to work great, my homebridge server has been running for the last few hours with me playing around in config-ui-x, updating plugins etc. The whole homebridge system seems to be a lot snappier - don't know if thats possible.

**Comment by oznu** [comment]
I've pushed up a new version to the `next` tag.

```
npm install -g homebridge-config-ui-x@next
```

Before restarting homebridge change `config-fork` back to `config`.

**Comment by normen** [comment]
works too!

**Comment by oznu** [comment]
Thanks. I'll try this on a single core raspberry pi some time in the next few days. If the performance is still acceptable I will push this change out to everyone. People running the [oznu/homebridge](https://github.com/oznu/docker-homebridge) docker container have been running this plugin as a separate process since I took over this project, so I'm fairly comfortable rolling this out to all users.

**Comment by oznu** [comment]
This has been published to the `latest` tag.

**Comment by DarKOrange75** [comment]
I have made a fresh install of Homebridge with AppleTV plugin and Config-ui-x and the latter is still preventing the appletv plugin from discovering the apple tv, so why is this ticket closed?

**Comment by mafyata** [comment]
Ask this at apple tv plugin’s page.

**Comment by DarKOrange75** [comment]
already asked: https://github.com/lprhodes/homebridge-apple-tv/issues/9#issuecomment-433597961
