### ISSUE TITLE
Update node.js

### ISSUE THREAD

**Issue by PhoenixPT** [oznu/homebridge-config-ui-x#751]
Hi,
I'm running homebridge with homebridge ui from oznu docker container in my qnap nas.
I updated the config ui to latest version (4.23.0) and tried the "sudo hb-service update-node" command.
The result was: "Your version of Linux is not supported by this command"

Is docker container not supported?
Thank you

**Comment by oznu** [comment]
Hi @PhoenixPT,

It is not. Check out: https://github.com/oznu/homebridge-config-ui-x/issues/745#issuecomment-646606339
