### ISSUE TITLE
iPad mouse scroll

### ISSUE THREAD

**Issue by adamrzanek** [oznu/homebridge-config-ui-x#754]
Is it possible to support probable scrolling on iPads safari in config?

**Comment by oznu** [comment]
What is "probable scrolling"? Google didn't help me find something related to iPad devices.

**Comment by adamrzanek** [comment]
I will record my screen later

**Comment by oznu** [comment]
Is this the same problem raised in #755?

**Comment by adamrzanek** [comment]
No - i mean this behavior in the config tab.

https://share.icloud.com/photos/0R4Da45BtW0wGSvAU1xjnVChQ
