### ISSUE TITLE
Lock layout on desktop class touch devices by default

### ISSUE THREAD

**Issue by adspen** [oznu/homebridge-config-ui-x#756]
**Is your feature request related to a problem? Please describe:**
It is very easy to mess up the status screen layout when using it on a touchscreen device like a tablet.   Instead of scrolling down the page, you end up resizing/moving widgets.

**Describe the solution you'd like:**
I would like to see a switch on the UI config settings (or elsewhere) to lock the layout.  This should then stop widgets being moved around accidentally.   When the layout is locked, the faint (+) add widget control should perhaps be hidden (or a message appear to inform the user that the layout is currently locked).

**Describe alternatives you've considered:**
I have checked and there doesn't seem to be any way to achieve this.  

**Additional context:**
I normally use the UI on my laptop, but periodically when this is powered down I might open up the UI on my iPad to check something out or look at the logs.  Almost without fail, attempting to navigate the status screen on my iPad will result in "widget chaos", with panes flying hither and thither.  It's nigh on impossible to sensibly alter the layout using a touch screen, so I then have to power up my laptop to reset the layout again.  Thanks.

**Comment by oznu** [comment]
Click that + button, then click "Lock Layout".

**Comment by adspen** [comment]
Wow - how did I miss something so obvious.   Many thanks for such a rapid reply - and for producing such a great UI.  Apologies for wrongly logging an enhancement request.

**Comment by oznu** [comment]
np. I've had a few people ask. I might change that + symbol to a cog.

**Comment by oznu** [comment]
FYI the lock is per device.

**Comment by oznu** [comment]
* Add feature to lock layout on touch devices that pretend to be a desktop.

**Comment by adspen** [comment]
Ok, great, thanks - I've now locked my layouts on my laptop and iPad.  I'd previously been looking for the lock facility on the 'UI Settings' page on the main menu.   It had been a while since I'd added an widgets, so must have not noticed that the lock facility was under there.  Yes, a cog icon would make it clearer that it isn't just adding a widget from here.

NB:  I've noted your change to this issue log - and yes in my view, locking by default on 'desktop class' touch devices makes a lot of sense.
