### ISSUE TITLE
Control an accessory by URL

### ISSUE THREAD

**Issue by JBChesh** [oznu/homebridge-config-ui-x#758]
I'm new to the Homebridge solution, and am trying to find a way to control a number of devices from my Loxone kit.

Within Homebridge and the Config UI X I can see and control all of my devices, including the Loxone ones which pulled across fine, but I can't find a way of turning on or off a TV for example which can be done from within the Accessories tab fine.

Is there either a plugin that would allow me to do this, or a way of creating a URL that would carry out a specific function from the accessories tab ?

Thanks,

**Comment by oznu** [comment]
The Homebridge service allows you to do this directly.

Connect to the Homebridge port/ip via http, eg:

```http
GET http://homebridge.local:54321/accessories
```

```http
GET http://homebridge.local:54321/characteristics?aid=1&iid=2
```

```http
PUT http://homebridge.local:54321/characteristics
Authorization: 453-23-23
{
  "characteristics": [
     {
       "aid": 1,
       "iid": 2,
       "value": 23
     }
  ]
}
```

See https://github.com/homebridge/homebridge/issues/2512#issuecomment-619303434
