### ISSUE TITLE
Unable to scroll log viewer in chromium based browsers

### ISSUE THREAD

**Issue by hpstephens** [oznu/homebridge-config-ui-x#759]
**Describe The Bug:**

Unable to scroll log viewer on main screen or in log viewer on a chromium based browser (Chrome on Raspberry or Chromium Edge.

**To Reproduce:**

Opening homebridge in chrome or edge.
<img width="828" alt="scrolling issue" src="https://user-images.githubusercontent.com/44702290/86036744-58c68300-ba0c-11ea-8583-cf5450bee069.png">
<img width="779" alt="scrolling issue1" src="https://user-images.githubusercontent.com/44702290/86036987-b955c000-ba0c-11ea-9700-3b0eb3bb41fa.png">

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```
 },
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "navi-blue",
            "restart": "sudo reboot",
            "tempUnits": "f",
            "lang": "en",
            "sudo": true,
            "debug": false,
            "log": {
                "method": "file",
                "path": "/var/log/homebridge.log"
**Screenshots:**

**Environment:**

* **Node.js Version**:  12.18.1
* **NPM Version**: 6.14.5
* **Homebridge Version**:  1.1.1
* **Homebridge Config UI X Version**: 4.23.2
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by mbierman** [comment]
Hmm it is working for me in homebridge-config-ui-x v4.23.2
