### ISSUE TITLE
Uptime and Memory

### ISSUE THREAD

**Issue by JDogg016** [oznu/homebridge-config-ui-x#76]
Anyone notice that uptime is always incorrect?  I am running on a synology disktation and I think 'Uptime' refers to how long the synology has been up and running (as opposed to homebridge).

Also, memory seems a bit weird.

The system shows 3.69 GB total memory and 3.55 used which would imply the system is REALLY stressed out.

**Comment by normen** [comment]
Uhm... Both are normal and as intended. Just start htop or some other analysis tool
a) Yes, its the uptime of your computer, not homebridge - as with most servers
b) Just look at htop or top, the memory you consider as "free" is probably reserved or idle.

**Comment by Caribsky** [comment]
DSM on my Synology 218+ shows 5% CPU Load, but Homebridge ui-x shows 52%

**Comment by normen** [comment]
Homebridge-ui-x shows an average over the last few seconds. Make sure that when you compare two meters that they show the same thing.

**Comment by Caribsky** [comment]
I also compared the value of using the CPU which shows using command 'top'. A big difference. Homebridge-ui-x always shows a value greater than 50%. It's strange. 
Looks like:  ui-x CPU Load = actual CPU usage x 10

**Comment by oznu** [comment]
@normen is correct regarding memory and uptime.

The CPU usage in Synology DSM is showing CPU **utilisation**. While `homebridge-config-ui-x` is showing the system **load**. If you open up Resource Monitor -> CPU tab you can compare the two results.

* DSM says CPU is 2% **utilised**.
* The 1 minute load average on a 2 core system is 0.31. This works out to be ~15.5% **load**.

![image](https://user-images.githubusercontent.com/3979615/38552340-34606328-3cff-11e8-9168-8c45322899fe.png)

What's the difference between utilisation and load? See https://serverfault.com/a/667250.
