### ISSUE TITLE
Sort plugins with updates automatically to top of plugin list

### ISSUE THREAD

**Issue by cclarke99** [oznu/homebridge-config-ui-x#762]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Super low priority, but it would be awesome if the UI automatically sorted the plugin list and put those with available updates automatically at the top of the list/view. Even better would be a way for the user to sort them via drop-down list with one of those list items for update/last-updated by dev/name/etc.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by palasinio** [comment]
On my Tablet they are sorted: Updates first, then A to Z.
On my desktop z to a, updates last(?).
