### ISSUE TITLE
Language translation file for plugins

### ISSUE THREAD

**Issue by NebzHB** [oznu/homebridge-config-ui-x#763]
Hi,

Would translations be available for plugins config schema too ?

**Comment by NebzHB** [comment]
Dear,

Is it in your roadmap ?

**Comment by seanzhang98** [comment]
It would be nice if support different language for plugins config schema. Looking forward for this function!

**Comment by kennymc-c** [comment]
+1

**Comment by dbisping** [comment]
How do I unsubscribe?

The app doesn’t work. 

O the joy of my spirit - it is uncaged - it darts like lightning!
It is not enough to have this globe or a certain time,
I will have thousands of globes and all time.

- Walt Whitman
