### ISSUE TITLE
Error restoring HOOBS hbfx

### ISSUE THREAD

**Issue by AdamDempsey** [oznu/homebridge-config-ui-x#764]
**Describe The Bug:**
I'm migrating from HOOBS to Homebridge and when I try to restore the hbfx I get a failure message.

File size is 39MB compressed and ~180MB uncompressed and when I check the size of /tmp/homebridge-backup-g7Xnah it's only 51MB.

Manual uncompress using the unzip command completes without error.

**To Reproduce:**
I can send the hbfx or happy to try debug at my end if easier.

**Expected behavior:**
Backup to restore successfully.

**Logs:**
```
[7/4/2020, 16:31:59] [Config] Extracting .hbfx file to /tmp/homebridge-backup-g7Xnah
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
```

**Homebridge Config:**
Still on default, fresh Homebridge install.

**Environment:**

* **Node.js Version**: 12.18.2
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.1
* **Homebridge Config UI X Version**: 4.23.2
* **Operating System**: Raspbian (Official Homebridge Raspberry Pi Image)
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Try connect to http://homebridge.local:8581 restore from there.

**Comment by AdamDempsey** [comment]
Same error but have noticed that it is the upload itself that is failing, it gets to approx 50% then errors but judging by the logs it is trying to extract even though upload hasn't completed hence the unexpected end of file error.

Did also try a different browser in case was an issue with Chrome.

I've tried to look if I can increase the file size limit anywhere in fastifyMultipart (I think that's what is handling the upload?) but it seems it's not set so appears to be no limit.

Is there a file upload limit I can change or can I easily(ish) makes changes to allow restoring from a locally (eg copied via SFTP) uploaded file?

**Comment by oznu** [comment]
You could remove the "node_modues" directory from the zip archive before uploading it. This is not used by and takes up 99% of the space.

Make sure the archive is still named .hbfx before uploading.

**Comment by AdamDempsey** [comment]
That did it thanks, it initially failed but I re-flashed a fresh install as I'd made a few changes trying to get it to work.
