### ISSUE TITLE
Revise CPU-Temperature widget configuration to allow temperature to be gathered by system call OR file  

### ISSUE THREAD

**Issue by taw123** [oznu/homebridge-config-ui-x#765]
### **Current state:**
Per [Oznu's Docker documentation]( https://hub.docker.com/r/oznu/homebridge/ ) homebridge-config-ui-x's CPU Temp widget expects the config.json to a path to a file that it tails and graphs for the current CPU temp. 

### **Describe the solution you'd like:**
Ideally I'd like to this support broadened to allow for not only file based data input for direct input via system command that can be executed by the config-ui-x widget. In addition it would be sensible to allow/require a the user also supply an appropriate filter/format/delimiter descriptor (RegEx perhaps?).

**Raw Data:**
` # getsysinfo cputmp
          37 C/98 F[/]

echo "CPU Temperature: $(getsysinfo cputmp)"
 CPU Temperature: 36 C/96 F'

**Config Example:**
`"sys-cmd" : "getsysinfo cputmp" 
"sys-cmd-filter" : ".(*)/.(*)"
"sys-cmd-unit" : "f"`

    

**Describe alternatives you've considered:**
Seems foolish to create a headless process to manually create a file where the system doesn't natively produce one, having to take into account file management (roll off the file, potential race conditions around shutdown/start up). More elegant solution would be to use native system service which all hosts I can think of support in one form or another, thus making this a UNIVERSAL solution rather then being platform specific. My example here was based upon a QNAP NAS hosting the docker container but would be appropriate for ANY host (container or not).  

Thanks for the thoughtful consideration. If there is another better way to do this I am all ears, perhaps hooking to syslog but that is a huge can of worms and at first glance seems less universal with more potential platform complications....

--Tom

**Comment by oznu** [comment]
The temperate information is gathered by this library now:

https://github.com/sebhildebrandt/systeminformation

If you would like to see the temperature information for your system in Homebridge Config UI X, I would suggest making a pull request to that excellent library.  

The "temp from file" is a depreciated config option that I won't be expanding on.

**Comment by taw123** [comment]
Thanks for the speedy response!

Interesting....   Reading though function cpuTemperature(callback) right now. Did you push a chance that now pulls data via systeminformation of is this a direction you are going and if so do you have a candidate release/build train for that support?  

Since you are online now I am replying while reading though's Sebastian info for configuration details.
