### ISSUE TITLE
Select Interface for QR code

### ISSUE THREAD

**Issue by fxhuhn** [oznu/homebridge-config-ui-x#768]
Hi there,

how can i change the interface/ip-adress in the web frontend?
Neither mdns nor bridge seem to work:
```
{
    "mdns": {
        "interface": "192.168.102.3"
    },
    "bridge": {
        "host": "192.168.102.3",
    },
```

![image](https://user-images.githubusercontent.com/49436733/86595053-6d6cc300-bf98-11ea-82b0-4d8ebe9ea817.png)

**Comment by oznu** [comment]
The System information panel is showing your default interface. If you fix your systems default interface, it will be reflected here. 

You can see your default route by running this (inside the conainer if Docker):

```
 route | grep default
```

If you are running Docker, make sure you have started the container with `--net=host`.
