### ISSUE TITLE
RFE: Online Backups 

### ISSUE THREAD

**Issue by Bankaifan** [oznu/homebridge-config-ui-x#77]
Hey,

I have another enhancement-request.
Would it be possible, that the plugin automatically stores a/several backups of the config whenever there is made a change to the config? 
The backup should be stored at the webserver, so it is reachable from everywhere. 

Would be really nice :)

Kind regards

**Comment by oznu** [comment]
> Would it be possible, that the plugin automatically stores a/several backups of the config whenever there is made a change to the config?

It already does 😄. Check the same folder your `config.json` is located.

> The backup should be stored at the webserver, so it is reachable from everywhere.

The backups are not currently exposed via the user interface, which I think is what you are asking for?

**Comment by oznu** [comment]
This will available in what should be 3.6.0.
