### ISSUE TITLE
ffmpeg exited with code: 1 when using hb-service

### ISSUE THREAD

**Issue by ashdwells** [oznu/homebridge-config-ui-x#770]
Hi

I am receiving this error when using sudo hb-service install:
[Camera-ffmpeg] [FFMPEG] ffmpeg exited with code: 1 and signal: null (error)

However camera works fine when not using hb-service by running Homebridge from the terminal.

"Camera-ffmpeg", here is my config:

 "name": "Dining Room",
                    "audio": false,
                    "videoConfig": {
                        "source": "-re -f avfoundation -video_size 1280x720 -framerate 30 

I'm stuck! Please help

**Comment by oznu** [comment]
It's most likey running as a different user when you're running as a service. Check the service user has the same permissions.

This is more of an Camera-ffmpeg issue, you can raise a report over there if you need help.
