### ISSUE TITLE
I can't restart homebridge via 'restart'

### ISSUE THREAD

**Issue by mreassassin** [oznu/homebridge-config-ui-x#771]
**Describe Your Problem:**

I can't restart homebridge via 'restart' button.  I've been launching my 2nd instance of homebridge standalone via PuTTy:
`homebridge -U /home/pi/.homebridge/instance2 > /home/pi/.homebridge/instance2/homebridge.log -I -D`
if I enter the above in the 'restart command' field I get this log (so I took it out of my config for now):
**Logs:**

```
[7/9/2020, 23:00:40] [Config] The "setBasePath" method has been deprecated. Now, a global prefix is populated automatically. If you want to ignore it, take a look here: https://docs.nestjs.com/recipes/swagger#global-prefix. Alternatively, you can use "addServer" method to set up multiple different paths.

```

**Homebridge Config:**

```json
        {
            "name": "Config",
            "port": 8081,
            "log": {
                "method": "custom",
                "command": "sudo -n tail -n 100 -f /home/pi/.homebridge/instance2/homebridge.log"
            },
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "sudo": true,
            "debug": false,
            "sessionTimeout": 600,
            "platform": "config"
        },
```

**Comment by oznu** [comment]
For ther restart feature to work you need to be running Homebridge using a service supervisor, such as systemd / hb-service.

See https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian
