### ISSUE TITLE
HeaterCooler accessory not turning on when hitting cool/heat in the detail screen

### ISSUE THREAD

**Issue by CyberMrProper** [oznu/homebridge-config-ui-x#772]
When I go to the detail screen inside the accessory and I click heat/cool, nothing happens.

I think the code is missing **this.service.getCharacteristic('Active').setValue(1);** before or after the following line:

https://github.com/oznu/homebridge-config-ui-x/blob/06a9666b4f5cb0e1036e6d33e18cbabaa81bdcb3/ui/src/app/core/accessories/types/heatercooler/heatercooler.manage.component.ts#L70

**Comment by oznu** [comment]
Thanks, this should be fixed in the next release.
