### ISSUE TITLE
Carbon dioxide sensor - display PPM value

### ISSUE THREAD

**Issue by Killator** [oznu/homebridge-config-ui-x#773]
Hi,

Could you please display the PPM value on a carbon dioxide sensor (accessory panel) ?

Thanks a lot for all your work... I love automated my home with HomeKit / HomeBridge and its AMAZING interface ! ;-)

Killator.

**Comment by oznu** [comment]
Linking to meta issue: https://github.com/oznu/homebridge-config-ui-x/issues/47
