### ISSUE TITLE
Animation Loader Using the Homebridge Logo?

### ISSUE THREAD

**Issue by mkormendy** [oznu/homebridge-config-ui-x#775]
I'd be interested to see this as the homebridge config UI X animated loader instead of the spinning circles:

![Jul-12-2020 21-17-22](https://user-images.githubusercontent.com/1437667/87264290-3a896a00-c485-11ea-9942-205a65c5cd67.gif)

I made an all SVG/CSS version here: https://codepen.io/mkormendy/full/dyGjNyv

Thoughts?

**Comment by oznu** [comment]
Thanks for your suggestion, I'm happy to leave it as is for now, I have plans to change the restart screen so this won't really be seen.

**Comment by mkormendy** [comment]
Maybe you can use it for something else. It's there if you need.

**Comment by oznu** [comment]
Thanks!
