### ISSUE TITLE
Improve Swagger documentation

### ISSUE THREAD

**Issue by mbierman** [oznu/homebridge-config-ui-x#776]
**Is your feature request related to a problem? Please describe:**
the swagger documentation doesn't allow you to try some endpoints because you can't insert required information. For example, See` /api/plugins/changelog/{pluginName}`

You can't edit the pluginName so you can't issue the command. 

**Describe the solution you'd like:**
These should be editable so that the documentation is more helpful to people learning the API.

**Describe alternatives you've considered:**

**Additional context:**
Other endpoints such as` /api/server/cached-accessories/{uuid}` allow the user to edit

**Comment by oznu** [comment]
Done in the 4.25.x.

**Comment by mbierman** [comment]
Awesome! Thank you.
