### ISSUE TITLE
BUG: Title for Settings of Arrays

### ISSUE THREAD

**Issue by mkormendy** [oznu/homebridge-config-ui-x#777]
**Describe The Bug:**
The title of arrays for a plugin's settings appear to be using the config name and not the imposed title in the `config.schema.json` file.

**To Reproduce:**
1. Create an array of configuration settings associated with a configuration for a plugin.
2. Set the title of the entire array.
3. See that the title is choosing the specific configuration identifier for that setting addressed in the `config.schema.json` instead of the title provided in the `config.schema.json` file.

**Expected behavior:**
Expected to see the title instead of the identifier.

**Logs:**
There is no output in the logs for this issue, see the screenshots.

**Screenshots:**
![Screen Shot 2020-07-15 at 12 07 30 PM](https://user-images.githubusercontent.com/1437667/87576277-bad2e980-c696-11ea-834e-3a85b734ed9d.png)

![Screen Shot 2020-07-15 at 12 07 47 PM](https://user-images.githubusercontent.com/1437667/87576285-bdcdda00-c696-11ea-873c-4669918837b7.png)

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: v6.14.6
* **Homebridge Version**: 1.1.1
* **Homebridge Config UI X Version**: v4.23.2
* **Operating System**: macOS
* **Process Supervisor**: launchd

**Comment by bwp91** [comment]
any updates on this?

**Comment by mkormendy** [comment]
@oznu thanks 👍🏻👍🏻

**Comment by bwp91** [comment]
a thanks from me too from *my* ocd point of view!
