### ISSUE TITLE
Is it possible to interact with Homebridge accessories from outside of Apple app?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [oznu/homebridge-config-ui-x#779]
Is it possible to interact with accessories available in Homebridge from the command line? 

![image](https://user-images.githubusercontent.com/15063294/87645606-05fc0380-c74e-11ea-8d03-9c85979b25bc.png)

The idea here is to be able to control devices exposed by Homebridge outside of the Apple app. Right now you can click on the web interface to manage it, so was wondering if there's some API I could access from cmd.

**Comment by oznu** [comment]
The Homebridge service allows you to do this directly.

Connect to the Homebridge port/ip via http, eg:

```http
GET http://homebridge.local:54321/accessories
```

```http
GET http://homebridge.local:54321/characteristics?aid=1&iid=2
```

```http
PUT http://homebridge.local:54321/characteristics
Authorization: 453-23-23
{
  "characteristics": [
     {
       "aid": 1,
       "iid": 2,
       "value": 23
     }
  ]
}
```

See https://github.com/homebridge/homebridge/issues/2512#issuecomment-619303434
