### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by kvpoma** [oznu/homebridge-config-ui-x#781]
What happens if you have 2FA turned on, and your authenticator app craps out? How do you turn off 2FA? Am I DOA and need to reinstall the whole image again?

**Comment by oznu** [comment]
You can delete the "auth.json" file stored in the homebridge storage directory and restart homebridge. This will reset the credentials back to the default of admin/admin.

**Comment by kvpoma** [comment]
Thanks, i'm new to Homebridge.  How do I get to the Homebridge storage directory?

**Comment by oznu** [comment]
You would do it via SSH and standard Linux commands to change directory and remove the file.

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Connect-Via-SSH
