### ISSUE TITLE
Allow weather and CPU temps to use different units of measurement

### ISSUE THREAD

**Issue by blcarson** [oznu/homebridge-config-ui-x#783]
**Is your feature request related to a problem? Please describe:**

I'm used to reading CPU temps in celsius and weather in fahrenheit, but current setup only allows for one unit of measurement for both.

**Describe the solution you'd like:**

Add a dropdown in either the weather or CPU widgets to pick unit of measurement.

**Describe alternatives you've considered:**

Joining the rest of the world and learning the proper way to tell how cold it is outside.

**Comment by oznu** [comment]
This will arrive in the next release.

![image](https://user-images.githubusercontent.com/3979615/90392488-4a264f00-e0d2-11ea-83d9-73cee5fc4915.png)
