### ISSUE TITLE
hb-service unsupported on FreeBSD-based platforms (FreeNAS specifically in this case).

### ISSUE THREAD

**Issue by hjdhjd** [oznu/homebridge-config-ui-x#784]
hh-service is unsupported on FreeBSD and FreeBSD-derived platforms like FreeNAS.

Title says it all. :smile:

* Login to a FreeNAS jail with a working `homebridge` and `homebridge-ui-x` installation.
* `hb-service install`
* `✖ ERROR: This command is not supported on freebsd.`

What you’d expect is for the install script to setup all the plumbing needed to start / stop homebridge on startup and on the fly on FreeBSD/FreeNAS platforms.

**Logs:**
See above.

**Screenshots:**

**Environment:**

* **Node.js Version**:  13.10.1
* **NPM Version**:  6.12.1
* **Homebridge Version**:  1.1.1
* **Homebridge Config UI X Version**: 4.23.2
* **Operating System**: FreeNAS 11.3-U2
* **Process Supervisor**: pm2 since I hb-service doesn’t support FreeBSD yet. :smile:

**Comment by oznu** [comment]
I'm not sure this is a bug. BSD isn't Linux :)

**Comment by hjdhjd** [comment]
Fair enough. :smile: The other categories didn’t feel right either...is it an _enhancement_ either? I’m not asking you to make the feature better or different...I’m asking you to make it _work_. :smile:

Any plans to add support?

**Comment by oznu** [comment]
FreeBSD usage is very low and there are alternatives that work, like pm2.

I'll accept a PR that adds FreeBSD support if anyone is interested in adding this - https://github.com/oznu/homebridge-config-ui-x/tree/master/src/bin/platforms
