### ISSUE TITLE
Provide for restart of Homebridge at predetermined time

### ISSUE THREAD

**Issue by DMBlakeley** [oznu/homebridge-config-ui-x#786]
**Is your feature request related to a problem? Please describe:**

I have found that plugins produce less connection errors after a Homebridge restart. Errors start to occur after ~24 hours of run time. Plugins where I have observed this are "Homebridge Nest", "Homebridge Ring", "Homebridge MyQ" and "Homebridge Node Alarm Dot Com".

**Describe the solution you'd like:**

Provide option to reboot homebridge every 24 hours at a predetermined time.

**Describe alternatives you've considered:**

All of the referenced plugins have introduced updates to reduce connection issues. I have also made sure that all of my devices have a strong wifi connection and have found using the Cloudflare DNS settings rather than the Spectrum defaults also has provided improvements. Even so a daily reboot seems to be the best remedy.

**Additional context:**

**Comment by oznu** [comment]
You can achieve this using a cron. Google "how to create a cron job on <my platform>" and you should find what you need.
