### ISSUE TITLE
Switch from systemd to hb-service?

### ISSUE THREAD

**Issue by MirkoKas** [oznu/homebridge-config-ui-x#788]
**Describe Your Problem:**
As the hb-service is the preferred way to run Homebridge with, I was wondering what to do to migrate from my Homebridge I run as root with systemd to the hb-service. Is this possible without too much trouble? 

**Logs:**
not needed 

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
{
            "name": "Config",
            "port": 8760,
            "auth": "form",
            "theme": "green",
            "restart": "sudo systemctl restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "debug": false,
            "standalone": true,
            "sessionTimeout": 28800,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        },
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v12.14.1
* **NPM Version**:  v6.13.6
* **Homebridge Version**:  v1.1.1
* **Homebridge Config UI X Version**: 4.24
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
Do a backup first to be safe: https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

If your current homebridge storage directory is `/var/lib/homebridge`, you can do the following without loosing any settings or having to restore the backup:

```
sudo systemctl stop homebridge
sudo systemctl stop homebridge-config-ui-x
sudo systemctl disable homebridge
sudo systemctl disable homebridge-config-ui-x

rm -rf /etc/systemd/system/homebridge.service
rm -rf /etc/systemd/system/homebridge-config-ui-x.service

sudo hb-service install --user homebridge --port 8760
```

If your storage directory is not `/var/lib/homebridge`, then you can still perform the commands above, you will just need to restore the backup one setup.

**Comment by MirkoKas** [comment]
Thx @oznu for your quick reply.
My current setup has the homebridge storage under /root/.homebridge 

If I got it right, I could also just stop & disable the current services and install the hb-service. 
When - for some reason - there is a problem with the restored hb-service homebridge instance, I could easily uninstall the hb-service again, reenable the old systemd services and would be running again. Right?

**Comment by oznu** [comment]
hb-service will overwrite the current systemd service named "homebridge".

**Comment by oznu** [comment]
You can manually copy your entire config folder to /var/lib/homebridge before running install if you want to avoid having to restore the backup.

**Comment by MirkoKas** [comment]
Thx. Everything worked flawlessly. I copied the files to the var/lib and followed your instructions.
