### ISSUE TITLE
Allow log path to be specified independently of storagePath

### ISSUE THREAD

**Issue by scamden** [oznu/homebridge-config-ui-x#789]
**Is your feature request related to a problem? Please describe:**
If I want to tell hb-service to log to a different directory, I currently have to change the entire storage path. The problem is that the directory I want it to log to is a log point construted by log2ram so it's in memory only. I don't want to have to try to store all my configs there. Just logs. 

**Describe the solution you'd like:**
Have an install parameter for logpath, maybe -L or something, that simply overrides the normal log path and isn't dependent on the storagePath prefix.

**Describe alternatives you've considered:**
running homebridge manually and sending the logs where I want.. but I like hb-service

**Comment by oznu** [comment]
Hi @scamden,

The idea of `hb-service` is to have a consistent setup that's easy for myself and others to help support. 

One option may be to symlink `homebridge.log` -> `/path/to/ram/drive/homebridge.log`?

It's also completely optional to use `hb-service`, so you can setup Homebridge and the UI [manually](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian,-Debian-or-Ubuntu-Linux-%5BNo-UI%5D) and configure everything exactly how you like.

**Comment by oznu** [comment]
updated comment with another alternative.

**Comment by scamden** [comment]
Would it be especially difficult to support? Unless I misread the code it
would be a one liner. I’d be happy to offer a PR if it helps. But please
also correct me if I’m missing something about how easy this would be.
