### ISSUE TITLE
Enable and disable plugins

### ISSUE THREAD

**Issue by yceballost** [oznu/homebridge-config-ui-x#790]
**Is your feature request related to a problem? Please describe:**
Sometimes plugins doesnt works by some reason. would be nice to have the possibility to disable them instead of remove.

**Describe the solution you'd like:**
Switch to enable and disable plugins installed.

**Comment by oznu** [comment]
Thanks for your suggestion, there is an existing feature request for this: https://github.com/oznu/homebridge-config-ui-x/issues/287
