### ISSUE TITLE
Ignore plugin config

### ISSUE THREAD

**Issue by ggroel** [oznu/homebridge-config-ui-x#791]
It would be great to be able to ignore the configuration of a plugin without removing it. For example, I want the next reboot to ignore a plugin. In other words, being able to activate / deactivate a plugin (which in the configuration omits the code, but remains there for when you activate the plugin again). Thanks!!!!!!

**Comment by milo526** [comment]
I believe this problem can be tackled by implementing #287

**Comment by oznu** [comment]
Tracking in https://github.com/oznu/homebridge-config-ui-x/issues/287 😄
