### ISSUE TITLE
Feature: suspend Homebridge service, so users can run it from Terminal

### ISSUE THREAD

**Issue by ebaauw** [oznu/homebridge-config-ui-x#795]
**Is your feature request related to a problem? Please describe:**

@oznu, as you know (see https://github.com/oznu/homebridge-config-ui-x/issues/676), my plugins log extensive debug information to the Homebridge log, to aid me in analysing issues my users might raise.  I really need the full Homebridge log file when running `homebridge -D`, from startup to the moment the issue occurs.

I appreciate your concerns about sensitive info, and understand you don't want to provide a means to download the full log file.  I'm happy to instruct my users to run `homebridge -D` manually, capturing the output into a file.  However, more and more users are using `hb-service` and Homebridge Config UI X and don't know how to `ssh` into the machine running homebridge.  The tend to know how to access the _Terminal_ from Homebridge Config UI X.

However, they cannot run `homebridge -D -U /var/lib/homebridge > homebridge.log 2>&1` from the _Terminal_ as homebridge is already running.

**Describe the solution you'd like:**
Could you add an option to Homebridge Config UI X to suspend the homebridge service, so a user can run `homebridge` manually from the _Terminal_?

**Describe alternatives you've considered:**
The only alternative I see is a really bad idea: Have my plugins log to a separate file, bypassing Homebridge's log feature.

**Additional context:**
See also  and https://github.com/homebridge/homebridge/issues/2637.

**Comment by oznu** [comment]
When running under `hb-service` there is already an option to toggle `-D` from the UI (that works on any platform; even windows).

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Enable-Debug-or-Insecure-Mode

Would an option to download the log file be enough (with appropriate warnings about potential confidential information)?

Getting Homebridge to stop I think is a lot of work - since I've programmed hb-service to do the exact opposite (attempt keep it running at all times).

**Comment by ebaauw** [comment]
> Would an option to download the log file be enough (with appropriate warnings about potential confidential information)?

That was indeed my original request.

**Comment by oznu** [comment]
In test now: https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command

**Comment by oznu** [comment]
![image](https://user-images.githubusercontent.com/3979615/89527506-c7c5a180-d82c-11ea-9cea-f1969d852ebd.png)

**Comment by oznu** [comment]
Just updated this so the download function strips the asci colour codes. This will make it easier to read the plain text logs.

**Comment by oznu** [comment]
Also added the ability for a user to "truncate" their log, which they might want to do just before starting a debug run so it's nice and short.

**Comment by ebaauw** [comment]
Thanks, mate, really appreciate this!

> Just updated this so the download function strips the asci colour codes. This will make it easier to read the plain text logs.

There's still some residual codes.  I would actually prefer the log file to contain the codes: easier to scan visually for errors and warnings.

> Also added the ability for a user to "truncate" their log

Is the log file still recycled or truncated automatically?

**Comment by oznu** [comment]
> Is the log file still recycled or truncated automatically?

Yeah at 2MB. 2MB is a lot of log file.
