### ISSUE TITLE
Terminal widget - does it exist? How can I find it?

### ISSUE THREAD

**Issue by womby1** [oznu/homebridge-config-ui-x#798]
Hi,

I recall reading that there is a terminal widget where you can type comments conveniently.

How can I find/enable said widget?

If it does not exist would it be a good enhancement?

Cheers!

**Comment by oznu** [comment]
If you're on Linux and run with [`hb-service`](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command) you can add the "Terminal" widget to the status screen, and also access the terminal from the option in the upper-right-corner drop down menu.

Terminal is disabled on macOS and Windows for various non-technical reasons.

**Comment by womby1** [comment]
How about Raspbian OS?

**Comment by oznu** [comment]
That is Linux, so yes.

**Comment by oznu** [comment]
If you setup using the Homebridge Wiki Guide for Raspbian,  then you should have this already.

https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

**Comment by womby1** [comment]
![image](https://user-images.githubusercontent.com/49666243/89289463-e0e21d00-d689-11ea-9a5b-3a5d31cd40a4.png)

I think that's what I did like a year ago, but terminal does not appear (see attached). I guess I used another way to set-up homebridge as a service. Perhaps I will just re-install if I find some time :)

WDYT?
