### ISSUE TITLE
update to last version failed

### ISSUE THREAD

**Issue by Kydix** [oznu/homebridge-config-ui-x#80]
Hi, on my raspberry pi 3 using homebridge with docker, update the pluging failed and broke the UI.

I have this message in my consol "homebridge_1  | s6-applyuidgid: fatal: unable to exec homebridge-config-ui-x: No                                                                                                                                                          such file or directory"

**Comment by oznu** [comment]
Hi @Kydix,

Please run this to fix it:

```
docker-compose exec homebridge npm uninstall --unsafe-perm homebridge-config-ui-x
docker-compose exec homebridge npm install --unsafe-perm homebridge-config-ui-x
```

Then restart the container:

```
docker-compose restart homebridge
```

**Comment by oznu** [comment]
I updated the commands you need to run - please check the github issue.

**Comment by Kydix** [comment]
thanks ! It works great now and i'm up to date :)
