### ISSUE TITLE
[npm registry issue] npm error installing scoped dependencies (@scope/package)

### ISSUE THREAD

**Issue by piejanssens** [oznu/homebridge-config-ui-x#800]
**Describe The Bug:**
Trying to update Ring homebridge plugin. It seems the '/' of the package name should not be URL escaped. See screenshot.
I checked the package.json of ring and some of the affected dependencies and that is not the source of the issue.

**To Reproduce:**

Update Ring plugin from v9.6.0 to v9.7.0.

**Expected behavior:**

**Logs:**
[homebridge.log](https://github.com/oznu/homebridge-config-ui-x/files/5034061/homebridge.log)

**Homebridge Config:**

N/A

**Screenshots:**

![image](https://user-images.githubusercontent.com/829098/89518125-c9667980-d7da-11ea-855b-07e0672e1848.png)

**Environment:**

* **Node.js Version**: v12.13.0
* **NPM Version**: v6.12.0
* **Homebridge Version**: 1.1.1
* **Homebridge Config UI X Version**: 4.23.2
* **Operating System**:  Docker
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
This is the raw output from the npm command. The UI is not doing this.

**Comment by piejanssens** [comment]
You are right, seeing the same from the terminal. Never had this issue before.

**Comment by piejanssens** [comment]
Same occurs when I do an npm install directly:

![image](https://user-images.githubusercontent.com/829098/89521521-f36e6a80-d7df-11ea-9527-82b63f594ed9.png)

**Comment by piejanssens** [comment]
OK there we go: https://status.npmjs.org/incidents/cksjqc1w11v5
