### ISSUE TITLE
Where is login information stored?

### ISSUE THREAD

**Issue by h00pak** [oznu/homebridge-config-ui-x#807]
The default login isn't working for me. I checked auth.json and have admin and admin there. Any ideas? Thanks a bunch.
Robby

**Comment by h00pak** [comment]
Sorry - deleted auth.json and restarted home bridge. Okay now.

**Comment by Karo-X** [comment]
This issue ist still there! admin / admin does not work. 
also deleting the auth.json is not the solution.
