### ISSUE TITLE
Web Page Blank- Fixed but would like your feedback

### ISSUE THREAD

**Issue by macjeff** [oznu/homebridge-config-ui-x#809]
I updated to new version this week.  I have never had issue in the past.  There was also a homebridge update the same day but I had not done that yet.
After the update hombridge UI restarted and the page was blank.  I checked and it was actually running.  Everything was working correctly but no web page.
I even checked and that port was being used for the webpage but nothing was on the browser (tried multiple machines using the same URL I had been using)
I rebooted and same thing.  Reinstalled (without uninstalling) same thing.
So I did the cleanup (remove and then reinstall) as outlined on your page.
It did not work but then I did it a second time and it did work.   I did a few other things.
Now I have rebooted the computer (mac os) and also restarted and its working.

Just wanted to run this by you.  been running this for months with zero issues and ran a few updates.  This is the first time I had any issues.

**Comment by oznu** [comment]
```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

If that does not work, please open a new issue with the logs, config and environment details.

**Comment by macjeff** [comment]
The new version resolved the issue.
