### ISSUE TITLE
Terminal option missing in my Homebridge ui-x v4.24.0

### ISSUE THREAD

**Issue by Martinx64** [oznu/homebridge-config-ui-x#812]
I dont have option "Terminal" in homebridge ui-x menu, so i can't use terminal directly from homebridge ui-x. I need it. Please help.

Thx

**Environment:**

* **Node.js Version**:  v14.7.0
* **NPM Version**:  v6.14.7
--
* **Homebridge Version**:1.1.1
* **Homebridge Config UI X v4.24.0
* **Operating System**: Ubuntu 18.04r
* **Process Supervisor**: dont know

**Comment by oznu** [comment]
Hi @Martinx64,

Please make sure you have followed the install guide from the Homebridge wiki:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

This will set you up with web-based terminal access.

You probably want to find out what your existing process supervisor is and remove any existing Homebridge services before following that guide.
