### ISSUE TITLE
Hide devices from HomeKit

### ISSUE THREAD

**Issue by timwegenerDE** [oznu/homebridge-config-ui-x#816]
Hi there and thanks for this beautiful plugin :)

It would be great if I could hide devices from HomeKit so they don‘t get exposed.

E.g. in the homebridge-hue plugin there is no (easy) possibility of hiding devices. https://github.com/ebaauw/homebridge-hue/issues/747#issuecomment-674527387

Also it could make sense that some devices are visible in the ui but not in HomeKit.

Kind regards
Tim

**Comment by oznu** [comment]
Hi @timwegenerDE,

This is not something the UI could do, as it operates at a different level to the plugins etc.

The plugin would need to have an option to expose or not expose the device.
