### ISSUE TITLE
v3.5.2: Empty browser page

### ISSUE THREAD

**Issue by jhubig** [oznu/homebridge-config-ui-x#82]
- _homebridge 0.4.38_
- _homebridge-config-ui-x v3.5.2_
- _node.js v8.9.4_

After installing the newest version v3.5.2 I had an empty page. It seemed the page was built but with empty body. Can somebody else confirm this behaviour? Thanks. 

Then I force-installed the previous version and now it works again.

`sudo npm install -g --unsafe-perm homebridge-config-ui-x@3.5.1`

**Comment by oznu** [comment]
This is a cached `index.html` issue. You can fix it by clearing the cache for the ui website.

In the next release I'll push up a change to prevent the index page from ever being cached (it's only 1.7KB), the static assets such as css, javascript, fonts and images files will still be cached.

**Comment by jhubig** [comment]
Shame on me. This is possible. I will try later and let you know. Thanks!
