### ISSUE TITLE
Command line 

### ISSUE THREAD

**Issue by roberkane212** [oznu/homebridge-config-ui-x#820]
I’m not sure if I’m doing something wrong however every time I try to use the command line it asks me for password for homebridge. I’ve used every password I can think of my log in password my pi password. Not sure what else to do

**Comment by oznu** [comment]
The "homebridge" service user does not have a password. Instead swap to your primary user, probably "pi":

```
su pi
```

Then enter the password for the `pi` user.

**Comment by roberkane212** [comment]
![9D42D9A0-1CD6-43B6-8F4D-E710BD2C3DAA](https://user-images.githubusercontent.com/44589993/90629049-abdadc00-e1ec-11ea-8393-18dd1e769dba.jpeg)
This is what I’m getting

**Comment by oznu** [comment]
Did you try the suggestion in the above comment?

**Comment by roberkane212** [comment]
@oznu yes however it applies to the pi not the config ui x. The command just won’t run I don’t know why makes no sense

**Comment by oznu** [comment]
The "homebridge" service user does not have a password and limited access. Swapping to the "pi" user before running commands that require `sudo` is the way to go.

**Comment by oznu** [comment]
You can also swap homebridge to use your own user that already has sudo access.

```
sudo hb-service uninstall
sudo hb-service install --user pi
```
