### ISSUE TITLE
Switching between Homebridge instances

### ISSUE THREAD

**Issue by hippopotam** [oznu/homebridge-config-ui-x#826]
Homebridge instances run on different ports, and you manage them via their own browser windows/tabs (e.g. localhost:port1, localhost:port2, etc.)

I am curious if it is possible to add something to UI-X to enable switching between instances, rather than opening several windows/tabs? Thanks.

**Comment by oznu** [comment]
This will come with #725 - which is needed to discover the ui instances that can be switched between.
