### ISSUE TITLE
Support for id's for homebridge-nest

### ISSUE THREAD

**Issue by EjvindHald** [oznu/homebridge-config-ui-x#831]
Hi

You have created support Nest token and id's for for homebridge-nest-cam which is great. However, I am using homebridge-nest, which needs similar tokens. Especially, the Cookie token needs to refreshed at regular intervals.

It would nice if this already existing functionality in configu-ui-x could also support that one.

Thanks.

Ejvind

**Comment by oznu** [comment]
All the code to make this happen lives in the homebridge-nest-cam repo; homebridge-nest would need to add the same or similar code to enable this.

**Comment by oznu** [comment]
Code ref: https://github.com/Brandawg93/homebridge-nest-cam/blob/master/src/uix.ts
