### ISSUE TITLE
Issue with Roomba Plugin since latest build of Homebridge Config UI X was installed

### ISSUE THREAD

**Issue by jnanes** [oznu/homebridge-config-ui-x#835]
**Describe The Bug:**

After installing 4.27.1 my Roomba plugin fails to start with this error " Plugin '@benmosher/homebridge-roomba690' tried to register with an incorrect plugin identifier: 'homebridge-roomba690'. Please report this to the developer!"

The roomba plugin has not updated or changed in awhile. I tried a couple other forks of the plugin and get the same error.

**To Reproduce:**

**Expected behavior:**

**Logs:**
 Plugin '@benmosher/homebridge-roomba690' tried to register with an incorrect plugin identifier: 'homebridge-roomba690'. Please report this to the developer!

Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```
   "bridge": {
        "name": "Homebridge",
        "username": "CD:22:3D:E3:CE:30",
        "port": 34869,
        "pin": "981-11-754"
    },
    "description": "My Homebridge",
    "accessories": [
        {
            "accessory": "Roomba690",
            "model": "690",
            "name": "Roomba",
            "hostname": "10.9.9.2",
            "blid": "3162880890518770",
            "password": ":1:REMOVEDFORSECURITY"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "none",
            "theme": "blue-grey",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "camera-ffmpeg-ufv",
            "name": "UniFi Video (ffmpeg)",
            "nvrs": [
                {
                    "apiHost": "10.5.5.11",
                    "apiPort": 7443,
                    "apiProtocol": "https",
                    "apiKey": "REMOVEDFORSECURITY"
                }
            ]
        },
        {
            "bonds": [
                {
                    "ip_address": "10.9.9.5",
                    "token": "REMOVEDFORSECURITY"
                }
            ],
            "include_dimmer": false,
            "fan_speed_values": false,
            "platform": "Bond"
        }
    ]
}
**Screenshots:**

**Environment:**

OS | Ubuntu Bionic Beaver (18.04.4 LTS)
-- | --
homebridge
10.9.9.3
fe80::5cdd:cbe9:ed7f:44b7
v10.22.0
v6.14.6

**Comment by oznu** [comment]
> Please report this to the developer!"

Please report this to the developer of that plugin 😄 

This message is unrelated to the UI.

**Comment by jnanes** [comment]
Thank you I did this as well, I'm just not clear why it operated fine until an update of Config-UI plugin.
I have now tried to remove the config from my config.json and uninstall the plugin but i cannot get Homebridge to start again...

I now get this: https://imgur.com/a/pbscdpv

**Comment by oznu** [comment]
One of your other plugins is blocking Homebrige from starting. Looking at the code for `camera-ffmpeg-ufv`; that uses the old style "blocking" platform that is likely to be the cause.
