### ISSUE TITLE
Feature Request: Show plugin release notes _before_ the update

### ISSUE THREAD

**Issue by HanSooloo** [oznu/homebridge-config-ui-x#839]
When I click on Update on a plugin, it will proceed with the update, and _then_ show me what the changes were.  

However, it would be nice if the user can review the release notes _FIRST_, and then update the plugin.

**Comment by oznu** [comment]
This already happens for plugins that provide release notes on GitHub.

Like this:

https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.27.1
