### ISSUE TITLE
Hide accessories and create groups

### ISSUE THREAD

**Issue by BoardLord82** [oznu/homebridge-config-ui-x#84]
Hi,

homebridge-config-ui-x is great! I have two enhancement-requests...

It would be very cool if i can hide accessoires or an entire room for non admins. 
And is it possible to group lights like in HomeKit?

Both would be awesome :-D

Kind regards

**Comment by razer4908** [comment]
Maybe an non admin is also not allowed to restart Homebridge as an Option :)

**Comment by razer4908** [comment]
@oznu do you think there is a possibility to integrate this feature ?

**Comment by razer4908** [comment]
Nice work, still love this project 👍 Keep up the great work!

**Comment by sergeyrozenblat** [comment]
Hiding an accessory does not mean it won't show up in Home.app?

**Comment by adavison007** [comment]
> Hiding an accessory does not mean it won't show up in Home.app?

Would be great if hiding it in the ui hid it in home app!

**Comment by pu-master** [comment]
@adavison007 Is the feature added to hide an accessory in Home.app?

**Comment by zyavrik** [comment]
It’s not possible to make a right click on an iPad.

**Comment by adavison007** [comment]
> @adavison007 Is the feature added to hide an accessory in Home.app?

Not that I am aware of :(

**Comment by zyavrik** [comment]
When I hid an accessory on a Mac, it did not disappear in HomeKit! I tried to restart Homebridge, but this didn't help. How can one hide garbage "devices" from HomeKit?
