### ISSUE TITLE
Requiring Authentication even though it should not

### ISSUE THREAD

**Issue by Salvora** [oznu/homebridge-config-ui-x#842]
**Describe Your Problem:**
I have 4 homebridge instances running with all of them set to requiring no authentication. However, two of these instances always ask me username and password. All of them has "auth": "none".
The weird thing is two of them (8581, 8510) work as expected but the other two (8520, 8530) always asks for username and password.

I tried deleting auth.json and recreating it but it didn't help.
Ports: 8581, 8510, 8520, 8530

**Logs:**

```
[9/11/2020, 10:49:39 AM] [Homebridge-HA] Failed login attempt
[9/11/2020, 10:49:39 AM] [Homebridge-HA] If you've forgotten your password you can reset to the default of admin/admin by deleting the "auth.json" file (/var/lib/homebridge-ha/auth.json) and then restarting Homebridge.
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge-Roomba",
        "username": "0E:E0:BC:11:A8:34",
        "port": 51639,
        "pin": "526-99-760"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Homebridge-Roomba",
            "port": 8520,
            "auth": "none",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "en",
            "sudo": true,
            "platform": "config"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: v6.14.8
* **Homebridge Version**: 1.1.6
* **Homebridge Config UI X Version**: v4.27.1
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
The `auth.json` file still needs to exist, even if authentication is disabled. So if you've deleted it, make sure you restart the service using `hb-service restart` so it gets recreated.

Note that you can still go to the `/login` route manually even when auth is disabled, so if you're on this page, navigate back to `/`.

I have tested this on all platforms (Linux, Windows, macOS - Node.js 10, 11, 12, 13 and 14) and it's working as expected.

**Comment by Salvora** [comment]
> 
> 
> The `auth.json` file still needs to exist, even if authentication is disabled. So if you've deleted it, make sure you restart the service using `hb-service restart` so it gets recreated.
> 
> Note that you can still go to the `/login` route manually even when auth is disabled, so if you're on this page, navigate back to `/`.
> 
> I have tested this on all platforms (Linux, Windows, macOS - Node.js 10, 11, 12, 13 and 14) and it's working as expected.

Exactly as you have said. The bookmarks were pointing to /login route which is why it was asking for credentials. I did not consider this. I will just change the address of the bookmarks . It is not a big issue but as a normal behavior shouldn't using "/login" forward the user to main page if the authentication is disabled?
