### ISSUE TITLE
Homebridge Rollback?

### ISSUE THREAD

**Issue by macjeff** [oznu/homebridge-config-ui-x#846]
This is just a simple question.  I am running your config UI on mac OS X and running great.  I run the Homebridge and plugin updates through the GUI.

If I upgrade to the latest homebridge it says roll back to last version if you have problems.  Using the GUI is there a method for rollback?

If not can you share the command to rollback (I understand the version number would change but as of this moment its 1.2.0 update and rollback would be 1.1.6

thanks!!!

**Comment by oznu** [comment]
```
npm install -g homebridge@1.1.6
```

**Comment by oznu** [comment]
This will land in 4.29.0. You will be able to select what version you want to rollback to.

![image](https://user-images.githubusercontent.com/3979615/95654652-2a992900-0b4d-11eb-9d9a-5e5c815a26ea.png)

**Comment by nscheffer** [comment]
Excellent !
