### ISSUE TITLE
Are plugin updates logged? 

### ISSUE THREAD

**Issue by crowston** [oznu/homebridge-config-ui-x#847]
**Describe Your Problem:**

I updated a plugin from the browser using Homebridge Config UI X. I saw some error messages flash by but then the update window closed. Are the updates logged to review? Perhaps the update window should stay open after the update runs? 

**Logs:**

I don't know where to find the logs of plugin updates. 
```

```

**Homebridge Config:**

```json

```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.1
* **Homebridge Config UI X Version**: v4.27.1 
* **Operating System**:  Ubuntu 
* **Process Supervisor**:  hb-service

**Comment by oznu** [comment]
> Perhaps the update window should stay open after the update runs?

The window will stay open if the task failed. In this case it sounds like the task succeeded.

**Comment by crowston** [comment]
As I said, the messages flashed by quickly so I didn't see exactly what they were, so they could have been warnings. The updated plugin seems to be working, so apparently the update succeeded. Still, it would be nice to be able to review the messages.

**Comment by oznu** [comment]
So i guess the answer to "Are plugin updates logged?" is "no".

npm outputs all sorts of garbage; npm v7 is suppose to impove this, so I'll review the situation again once it's released.

**Comment by crowston** [comment]
I copied what flashed on the screen at the last update (coincidentally of homebridge-config-ui-x), just for interest: 

```
USER: homebridge
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-config-ui-x@latest

npm WARN saveError ENOENT: no such file or directory, open '/usr/local/lib/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/lib/package.json'
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@6.8.0 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nestjs/mapped-types@0.1.0 requires a peer of class-transformer@^0.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN lib No description
npm WARN lib No repository field.
npm WARN lib No README data
npm WARN lib No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/pm2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ homebridge-config-ui-x@4.27.2
updated 15 packages and audited 1616 packages in 30.245s
```
