### ISSUE TITLE
URL suffix for websocket API?

### ISSUE THREAD

**Issue by jamieshaw** [oznu/homebridge-config-ui-x#85]
This may have the same answer as #81; but is it possible to use a suffix to identify the websocket connection (and perhaps something not along the lines of /api or /websocket?)

I've got this configured on a Mac mini running macOS server, which unfortunately has a cumbersome setup for reverse proxying — it has two apache servers, one that proxies the other.

In order to configure websocket proxying, the former layer has to have a simple ProxyPass applied but has no ability to filter by request URL, so it has to be done globally by the request path like so:
```
ProxyPass /hb/websocket wss://localhost:8123/hb/websocket
ProxyPassReverse /hb/websocket wss://localhost:8123/hb/websocket
```

Without this path, it's impossible to filter the websocket. 👍

**Comment by oznu** [comment]
Added prefix `wsocket`. Make sure you proxy the `?token=xxx` as well.

**Comment by jamieshaw** [comment]
Thanks — confirmed that's working now.
