### ISSUE TITLE
Plugin installation with HTTP Rest API

### ISSUE THREAD

**Issue by cylon147** [oznu/homebridge-config-ui-x#854]
Please add Plugin Installation using Rest API. I am Managing the Homebridge from another Control system. it will be great if we can install a plugin with Rest Command.

**Comment by rpolenthon** [comment]
Aren't you able to perform the installation over socket io? 

What kind of control system do you use?

**Comment by cylon147** [comment]
its a linux based platform. 

> Aren't you able to perform the installation over socket io?

Please share more infomration.  Thank you in adavnce.

**Comment by rpolenthon** [comment]
Take a look at the source code.

In /src/modules/plugins/plugins.gateway.ts you see all socket endpoints for the plugins,
in /src/modules/plugins/plugins.controller.ts you see all REST API Endpoints for plugins.

To see how the install request work, take a look at /ui/src/app/core/manage-plugins/manage-plugins-modal/manage-plugins-modal.component.ts

**Comment by cylon147** [comment]
Can you please help me out with an Example. I am not good at working with Source Code. Thanks in Advance.

**Comment by rpolenthon** [comment]
I am not the best guy to tell you how to do it in your specific case, as I integrated the socket.io sockets in a Swift based project.

First of all you may check out the library examples available for your preferred language. 

Then just connect to the ip with port of the API, pass the token as connection parameter, use `/plugins` as namespace for the socket and emit `install` with a json payload `{"name" : "homebridge-mqttthing"}`. The callback should return something like `[1]` in case of success. 

Together with examples from the library, that should be everything you need for your first test.

**Comment by cylon147** [comment]
I would Like to re-open this enchantment request.

Please add  HTTP post request for Plugin Installation.  

`/api/plugins/install/{pluginName}`

**Comment by cylon147** [comment]
Anyone Please..
