### ISSUE TITLE
Do you know this error??

### ISSUE THREAD

**Issue by henkied** [oznu/homebridge-config-ui-x#855]
HI ,

Do either of you know what this error means?

Everything works perfectly, only the log indicates this?

Encountered MDNS socket error on socket 'eth0' : send EPERM 10.0.1.186:5353
Error: send EPERM 10.0.1.186:5353
    at doSend (dgram.js:683:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
    at afterDns (dgram.js:629:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

**Comment by oznu** [comment]
Hi @henkied,

This is coming from Homebridge, it's related to the pinned issue, so please comment on the issue here: https://github.com/homebridge/homebridge/issues/2681

Be sure to follow the instructions in the top comment and provide the information requested.

**Comment by Supereg** [comment]
should be fixed with the latest 1.2.3 release

**Comment by henkied** [comment]
Sorry is not fixed

**Comment by Supereg** [comment]
ah yes missed something. This error isn't any bad though, as long as everything works as expected.

**Comment by Supereg** [comment]
out of interest, what OS and device are you homebridge running on?

**Comment by henkied** [comment]
Homebridge is running on Synology (718 And 218) both same error. The device (apple) with ios 14, apple tv TVos14 and homepod 13.4.8 (OS homepod not yet on 14)

**Comment by giss69** [comment]
Hi,

i've the same issue. HB running on DS718. two iPhones as error device.

**Comment by hagezi** [comment]
@oznu 
This error occurs since the last update of the dcoker images oznu/homebridge:ubuntu:
```
Encountered MDNS socket error on socket 'wg0' : Error: send Unknown system error -126 224.0.0.251:5353
    at doSend (node:dgram:705:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at afterDns (node:dgram:651:5)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```
