### ISSUE TITLE
Cannot see any accessories on the accessories tab

### ISSUE THREAD

**Issue by lukeredpath** [oznu/homebridge-config-ui-x#858]
**Describe The Bug:**
When I visit the accessories tab, no accessories are visible.

If I use curl to /api/accessories it returns all of the accessories as expected.

When I click on the accessories tab I do not see any XHR requests being made to the API endpoint as I do on other tabs (e.g. plugins, config).

**Logs:**
I'm not sure what logs you want me to attach but I'm not seeing anything in the logs that would seem helpful. I see this at the end of the logs after starting homebridge:

```
[9/24/2020, 20:27:29] Homebridge v1.2.3 is running on port 51826.
[9/24/2020, 20:27:30] [Config] [HapClient] Discovery :: Found HAP device with username 0E:26:7F:11:51:61
[9/24/2020, 20:27:30] [Config] [HapClient] Discovery :: Testing 0E:26:7F:11:51:61 via http://127.0.0.1:51826/accessories
[9/24/2020, 20:27:30] [Config] [HapClient] Discovery :: Success 0E:26:7F:11:51:61 via http://127.0.0.1:51826/accessories
[9/24/2020, 20:27:30] [Config] [HapClient] Discovery :: [127.0.0.1:51826 (0E:26:7F:11:51:61)] Instance Registered
```

**Homebridge Config:**

Just running a single plugin right now while I try and debug this issue.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:26:7F:11:51:61",
        "port": 51826,
        "pin": "460-95-131"
    },
    "platforms": [
        {
            "platform": "Hue",
            "users": {
                "001788FFFE1431D8": "5xatJ9aPFKKZtPHjJLKhwkCGNXWVWe2h63Va0n1G"
            },
            "name": "Hue",
            "lights": true
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "debug": true,
            "accessoryControl": {
                "debug": true
            },
            "platform": "config"
        }
    ],
    "accessories": []
}
```

**Environment:**

* **Node.js Version**: v12.18.4
* **NPM Version**: v6.14.6
* **Homebridge Version**: 1.2.3
* **Homebridge Config UI X Version**: 4.10.3
* **Operating System**: macOS 10.15.6
* **Process Supervisor**: hb-service and standalone

**Comment by oznu** [comment]
The accessories page uses WebSockets, make sure they aren't getting blocked.

**Comment by lukeredpath** [comment]
I've turned off all content blockers and tried both Safari and Chrome. Any other ideas I could try?
