### ISSUE TITLE
Error when updating to the last version 4.27.2

### ISSUE THREAD

**Issue by Ludelag** [oznu/homebridge-config-ui-x#861]
When updating to the last version 4.27.2 manually as it is running cmd windows, appear the next message

npm WARN @nestjs/mapped-types@0.1.0 requires a peer of class-transformer@^0.3.0 but none is installed. You must install peer dependencies yourself

How and what peer should be installed?

**Comment by Ludelag** [comment]
C:\WINDOWS\system32>npm install -g homebridge@latest homebridge-config-ui-x@latest
C:\Users\aaaa\AppData\Roaming\npm\homebridge -> C:\Users\aaaa\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge
C:\Users\aaaa\AppData\Roaming\npm\homebridge-config-ui-x -> C:\Users\aaaa\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\standalone.js
C:\Users\aaaa\AppData\Roaming\npm\hb-service -> C:\Users\aaaag\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\hb-service.js
npm WARN @nestjs/mapped-types@0.1.0 requires a peer of class-transformer@^0.3.0 but none is installed. You must install peer dependencies yourself.

+ homebridge@1.2.3
+ homebridge-config-ui-x@4.27.2
updated 6 packages in 28.439s

**Comment by Ludelag** [comment]
Solved!

**Comment by oznu** [comment]
That was a warning, not an error 😄. You can safely ignore it.

**Comment by Ludelag** [comment]
Thank you
