### ISSUE TITLE
Temporarily disable plugin

### ISSUE THREAD

**Issue by tomsteenbakkers** [oznu/homebridge-config-ui-x#864]
I notice that sometimes plugin are failing to load or causing errors when there are network problems. Homebridge crashes and try’s to restart, but this will fail.

I have a plugin which which will reject a login when you login too many times.

It would be nice if you can disable a plugin temporarily. Now, I remove the item in the config.json, but after enabling the plugin you have to manual restore the entry in the config.json. 

Not a big issue, but would make life easier

**Comment by oznu** [comment]
Thanks for your suggestion, effectively the same feature is being tracked here: https://github.com/oznu/homebridge-config-ui-x/issues/287
