### ISSUE TITLE
Disable login not working

### ISSUE THREAD

**Issue by EjvindHald** [oznu/homebridge-config-ui-x#865]
I am using this ui a lot, and it is really working great.
My network is closed from external access, so I have set the authentication to ‘None’ in advanced ui settings.
However, this seems to only work for a short period of time. After initial login it keeps showing the login screen after some time - often around 1 hour.
I am running newest version in Docker, and I have multiple instances.

**Comment by oznu** [comment]
Did you restart after changing the authentication option?

**Comment by oznu** [comment]
I've made some changes, so that the login page will automatically redirect the `/` when auth is disabled, and the socket connections will automatically re-connect when refreshing a session while auth is disabled.
