### ISSUE TITLE
Can’t update to 4.28.0

### ISSUE THREAD

**Issue by mafyata** [oznu/homebridge-config-ui-x#866]
Hi , I can’t update from 4.27.2 to 4.28.0
I run homebridge on raspberry with hb-service

![A9F52769-0018-414D-BFEE-6CF55D1BC2BB](https://user-images.githubusercontent.com/48009267/94835562-890e2b00-041a-11eb-9249-169a93fedcb0.png)

**Comment by oznu** [comment]
It looks like you didn't restart after updating from 4.27.1 to 4.27.2. Please restart manually then try update again.

**Comment by mafyata** [comment]
Yes , that works. Thanks.
