### ISSUE TITLE
Error message while updating any plugin

### ISSUE THREAD

**Issue by noppie** [oznu/homebridge-config-ui-x#869]
**Describe Your Problem:**
When trying to update a plugin using config-ui-x i get the message:
Error: Plugin "[object Object]" Not Found
When updating the plugin using terminal, the update ends successfully

**Logs:**
No log

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/866

You didn't restart the the UI after the last update.

**Comment by BrotherWrong** [comment]
> 
> 
> See #866
> 
> You didn't restart the the UI after the last update.

I have the same issue and I did restart the UI (numerous times) since the last update.

**Comment by oznu** [comment]
This would only occur if the UI service was not restated. Maybe try rebooting to make sure.

**Comment by BrotherWrong** [comment]
Done. Same issue. :(

**Comment by oznu** [comment]
Try re-installing then, see bottom of the readme.

**Comment by BrotherWrong** [comment]
Reinstalled and no change I'm afraid.
