### ISSUE TITLE
Update not possible since 3.5.4

### ISSUE THREAD

**Issue by URBANsUNITED** [oznu/homebridge-config-ui-x#87]
Hi!

After my update from 3.5.0 to 3.5.4 I am not able to do any further updates using the web ui.
It worked before without any higups. And I didn't change anything to my setup! 
Root is activated and I am using systemd setup
Raspbian stretch on Rpi3

The message I'll get:

USER: pi
DIR: /usr/local/lib/node_modules
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-config-ui-x@latest

sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin

The Log file doesn't spit out any further information .

Is it me or is there anything new/wrong I am not aware off?

Thanks

URBANsUNITED

**Comment by oznu** [comment]
What happens if you run this command, as the `pi` user, not root?

```
sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-config-ui-x@latest
```

Please try that in a fresh terminal that you haven't used sudo on before.

**Comment by oznu** [comment]
Command updated in comment above

**Comment by URBANsUNITED** [comment]
That worked fine:

Last login: Mon Apr 23 06:58:17 2018 from 192.168.0.75
pi@Homebridge:~ $ sudo -E -n npm --no-update-notifier install -g --unsafe-perm homebridge-config-ui-x@latest
/usr/local/bin/homebridge-config-ui-x -> /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
+ homebridge-config-ui-x@3.5.5
updated 1 package in 39.038s
pi@Homebridge:~ $ 

Restarted Homebridge and got 3.5.5 as the installed version

**Comment by oznu** [comment]
Does viewing the logs in the app work with `sudo` enabled using the `systemd` option?

It's the switching to root which is the issue as shown by this error:

```
sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin
```

**Comment by URBANsUNITED** [comment]
Doesn't work.

Using systemd to tail logs
CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge

sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin

The log tail command "sudo -n journalctl -o cat -n 500 -f -u homebridge" exited with code 1.
Please check the command in your config.json is correct.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

"platform": "config",
            "name": "Config",
            "port": 8811,
            "sudo": true,
            "restart": "sudo -n systemctl restart homebridge",
            "log": "systemd"

Command in Terminal works
sudo -n journalctl -o cat -n 500 -f -u homebridge

**Comment by oznu** [comment]
Can you rollback to v3.4.1 and see if the issue persists?

```
sudo npm install -g --unsafe-perm homebridge-config-ui-x@3.4.1
```

Make sure you refresh your browser tab manually after installing a lower version.

I can't replicate this issue on my end using the `pi` or `homebridge` users on a standard rasbpian stretch installation with node.js 8.11.1 installed from the official node.js repos and cannot spot anything between 3.5.0 and 3.5.5 that may have caused this.

**Comment by URBANsUNITED** [comment]
No change!

Log file doesn't show anything.
Message:

> Using systemd to tail logs
> CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge
> 
> sudo: unable to change to root gid: Operation not permitted
> sudo: unable to initialize policy plugin

> The log tail command "sudo -n journalctl -o cat -n 500 -f -u homebridge" exited with code 1.
> Please check the command in your config.json is correct.

When I restart the server from GUI, it looks like it restarts, gets also the green box right hand corner, but it doesn't restart:

taken from manually log file  using 

sudo -n journalctl -o cat -n 500 -f -u homebridge

[2018-4-24 09:34:24] [Config] Homebridge restart request received
[2018-4-24 09:34:24] [Config] Executing restart command: sudo service homebridge restart
[2018-4-24 09:34:24] [Config] Restart command exited with an error. Failed to restart Homebridge.

**Comment by URBANsUNITED** [comment]
Problem solved!

Was on my side. Permissions error without changing anything to my system.
Changed now the config dir to /var/lib/homebridge (was /var/homebridge) with permissions for user homebridge ans now all works fine again.

Sorry for the trouble it my has caused.

URBANsUNITED
