### ISSUE TITLE
Apple HomeKit stoped communication with HomeBridge

### ISSUE THREAD

**Issue by PrimaryInc** [oznu/homebridge-config-ui-x#870]
Hi,

Okay so I just started getting a issue, and I do believe it came after upgrading ui plugin to 4.28.0
Even it sound strange, Apple HomeHit now stoped communication with homebridge.

Environment:
Node.js Version v12.18.4
Npm Version v6.14.8
HomeBridge Version 1.1.6

Now there is no error in the logs as far as I can see and homebridge is starting. But result is:

![Screenshot 2020-10-02 at 11 04 42](https://user-images.githubusercontent.com/45151934/94906615-14310480-049f-11eb-9051-b6691ea9a429.png)

**Comment by oznu** [comment]
The UI runs as a seperate process to the bridge so wouldn't cause this - it's most likely an issue that has occurred while restarting the bridge after some time. Your logs will have more information.
