### ISSUE TITLE
Windows update uninstalls Homebridge service

### ISSUE THREAD

**Issue by AndrewMorsillo** [oznu/homebridge-config-ui-x#873]
**Describe The Bug:**
Per the title, Windows updated overnight and the next morning the Homebridge service was no longer installed. I had to open an admin prompt and `hb-service install` again. 

I'm not sure if it's possible to work around this behavior, unfortunately I know little about how Windows services work. I'm also on the Windows insiders dev channel, currently build 20226, not sure if that has an impact on the issue beyond updates happening more frequently. 

**To Reproduce:**
1. Follow homebridge-config-ui-x windows service installation instructions
2. Perform a windows update

**Expected behavior:**
The service continues to exist and work across windows updates.

**Logs:**

```
N/A Unless someone knows where to find Windows logs pertaining to updates and service uninstallation. 
I poked around the event viewer but wasn't able to locate anything relevant.
```

**Homebridge Config:**

```json
N/A
```

**Screenshots:**
N/A

**Environment:**

* **Node.js Version**: 12.18.3
* **NPM Version**: 6.14.6
* **Homebridge Version**: 1.1.6 
* **Homebridge Config UI X Version**: 4.28.0
* **Operating System**: Windows 10 Insider Preview build 20226
* **Process Supervisor**: none

**Comment by oznu** [comment]
I'm no expert in Windows services / development either. I would be accept a PR that would resolve this issue.
