### ISSUE TITLE
Option to install latest beta homebridge

### ISSUE THREAD

**Issue by simonrb2000** [oznu/homebridge-config-ui-x#877]
**Is your feature request related to a problem? Please describe:**
Current 1.1.6 stable has some issues for me that the latest beta has addressed

**Describe the solution you'd like:**
A setting in the advanced menu that would allow us to toggle between latest stable or latest beta version. 

**Describe alternatives you've considered:**
Manually update to beta

**Additional context:**

**Comment by oznu** [comment]
This will land in v4.29.0.

![image](https://user-images.githubusercontent.com/3979615/95654644-12c1a500-0b4d-11eb-9b70-66d582496608.png)

**Comment by TautFlorian** [comment]
@oznu Will this include a note on dashboard if a new beta version is available?

**Comment by oznu** [comment]
It won't. The npm registry "api" endpoint that I need to call to get non-latest version information can be quite slow as it also returns the full README contents for every single version ever - the API call to get version information for the UI is over 6MB of JSON.

**Comment by simonrb2000** [comment]
Brilliant; thank you.

Simon

On 10 Oct 2020, at 13:05, oznu <notifications@github.com> wrote:

﻿

This will land in v4.29.0.

[image]<https://user-images.githubusercontent.com/3979615/95654644-12c1a500-0b4d-11eb-9b70-66d582496608.png>

**Comment by arkadicolson** [comment]
Is there a place where I can see the changes of the latest beta version?

**Comment by oznu** [comment]
The GitHub commit history on the beta branch 😄.

Beta builds are not formal releases so don't have a changelog etc.
