### ISSUE TITLE
Standalone web app

### ISSUE THREAD

**Issue by benfysh** [oznu/homebridge-config-ui-x#88]
Would it be possible to add the Apple specific meta tag that would enable Config UI X as a standalone web app. Looking at the documentation it appears that it _just_ requires the following code to be added:
`<meta name="apple-mobile-web-app-capable" content="yes">`

From the [Apple developer site](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW3)

Thanks for the plugin by the way has made dealing with Homebridge especially when I have had to rebuild a **lot** easier.

**Comment by oznu** [comment]
Hi @benfysh,

Thanks for the suggestion. This will be implemented in what should be 3.6.0.

**Comment by benfysh** [comment]
Great thanks @oznu :)
