### ISSUE TITLE
Show change history before updating plugins

### ISSUE THREAD

**Issue by epheterson** [oznu/homebridge-config-ui-x#887]
**Is your feature request related to a problem? Please describe:**
When updating plug-ins, at the end the change log is shown. It'd be nice to have access to the change log prior to starting the update, to decide if it's worth updating to get the change.

**Describe the solution you'd like:**
When clicking on a plugin to update it, show a change log first (currently it goes right into the update).

**Describe alternatives you've considered:**
The change log is already shown after, but you have to install the update to see it.

**Additional context:**
I believe updating Homebridge works this way (showing change log first) and only updating plug-ins shows it after.

**Comment by oznu** [comment]
This already happens for plugins that provide release notes on GitHub.

Like this:

https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.27.1

**Comment by epheterson** [comment]
I tried a plug-in update just before opening this issue and didn't see the change log before updating, I suppose it is implementing only CHANGELOG.md. Thanks!
