### ISSUE TITLE
Dropdown with all DeviceNames 

### ISSUE THREAD

**Issue by pwilms** [oznu/homebridge-config-ui-x#896]
**Is your feature request related to a problem? Please describe:**
Some plugins need to be configured for single devices or device names. It would be much easier to choose them from a dropdown. 

**Describe the solution you'd like:**
Configuration option in the config.scheme.json to choose devices by name

```
      {
          "key": "deviceList",
          "type": "array",
          "items": {
            "title": "DeviceName",
            "description": "Name of the device you want to ignore",
            "type": "deviceName"
          }
        }
```

<img width="768" alt="mock" src="https://user-images.githubusercontent.com/4242261/95958727-d5d20880-0e01-11eb-968d-befecceea68c.png">

**Describe alternatives you've considered:**
Currently you have to specify them by string by yourself

**Comment by oznu** [comment]
Do you want the UI to provide the device names from Homebridge? Or are you just looking for a way to generate the list using the schema?

**Comment by pwilms** [comment]
I would prefer that the devices are directly available within the ui like the devices view. Of course only if the devices feature is available in this instance. 


Common workflow: 
- Add new device to homebridge 
- configure the plugin you like
- setup the device for example within a list that needs a device name based configuration


This would be awesome because you could much easier provide a list of accepted devices (like the upcoming feature in the homebridge-alexa plugin) for security reasons. Such a feature would increase the acceptance factor for handling such processes and makes it easy to use without copy&paste.

**Comment by oznu** [comment]
This would be a painful process to do with the current schema form.

Plugins should either use a dynamic schema form (generated at plugin runtime) with a list of accessories, or create an entirety custom user interface: https://github.com/homebridge/plugin-ui-utils

Homebridge nest cam uses dynamic schema forms to populate the different houses a user has in a drop down.
