### ISSUE TITLE
Error with installation of V4.29.0

### ISSUE THREAD

**Issue by sblitzer** [oznu/homebridge-config-ui-x#902]
during the installation of V4.29.0 I'm getting this error:

USER: homebridge
DIR: /usr/lib
CMD: sudo -E -n npm install homebridge-config-ui-x@latest

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/uuid: Integrity verification failed for sha512-M7C5z9T7L641CJ9VFaJQvH1m0kce7v+uoRZTAEKP7IZzoj23BaOViH22rVys7NX8t2jaaVLEE7AgsgF13yQ9dg== (/home/homebridge/.npm/_cacache/content-v2/sha512/33/b0/b9cfd4fb2fae35089f5515a250bc7d66d2471eeeffaea1165300428fec8673a23db705a395887db6ad5cacecd5fcb768da6952c413b020b20175df243d76)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-10-17T04_51_13_751Z-debug.log

Command failed. Please review log for details.

Error Log file:
501 verbose stack     at Readable.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:195:14)
501 verbose stack     at Readable.emit (events.js:321:20)
501 verbose stack     at /usr/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:92:30
501 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
501 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
501 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
501 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
501 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
501 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
501 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
501 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
501 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
501 verbose stack     at processImmediate (internal/timers.js:456:21)
502 verbose cwd /usr/lib
503 verbose Linux 4.19.75-v7+
504 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "homebridge-config-ui-x@latest"
505 verbose node v12.16.0
506 verbose npm  v6.14.5
507 error code EINTEGRITY
508 error errno EINTEGRITY
509 error Invalid response body while trying to fetch https://registry.npmjs.org/uuid: Integrity verification failed for sha512-M7C5z9T7L641CJ9VFaJQvH1m0kce7v+uoRZTAEKP7IZzoj23BaOViH22rVys7NX8t2jaaVLEE7AgsgF13yQ9dg== (/home/homebridge/.npm/_cacache/content-v2/sha512/33/b0/b9cfd4fb2fae35089f5515a250bc7d66d2471eeeffaea1165300428fec8673a23db705a395887db6ad5cacecd5fcb768da6952c413b020b20175df243d76)
510 verbose exit [ 1, true ]

**Comment by oznu** [comment]
This is an issue with your npm cache, not the UI package.

See https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0 for various solutions that may work for you.

**Comment by sblitzer** [comment]
thanks
I use npm cache clear --force && npm install --no-shrinkwrap --update-binary
Fix the issue
