### ISSUE TITLE
NodeJS 15 and NPM 7 issues with Homebridge-config- UI

### ISSUE THREAD

**Issue by macjeff** [oznu/homebridge-config-ui-x#904]
I wanted to let you know I am working fine on NodeJS 14.14.0 and NPM 6.14.8 on Mac OS X

I installed the new version NodeJS 15 and NPM 7.02 and when I open the browser (after a reboot) i get nothing so its not running.

For now I went back to the old version and it instantly (after a reboot) worked fine.

So for now I will stay there.  I am reporting this here first before I report on homebridge since the UI is not working at all either.  Let me know if you think this is a homebridge issue.

Since I keep a clone backup and also reinstalling the old version fixes issues I am happy to try again if you want me to test something.

**Comment by oznu** [comment]
Thank you for the report.

We recommend running the LTS version of Node.js. Anything newer may "work" but is not officially supported.

**Comment by oznu** [comment]
The current `@test` version should work on Node.js v15 and npm v7.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

I do see some weird things happening with npm v7 still (even when not using the Homebridge UI) - so proceed with caution (or downgrade npm back to 6.x.x and use that with Node.js v15).

**Comment by oznu** [comment]
Build and tests passing on Node.js 15: https://github.com/oznu/homebridge-config-ui-x/runs/1285246728?check_suite_focus=true

**Comment by oznu** [comment]
Should be fixed in 4.30.0. Please ensure you update the UI before upgrading Node.js.

**Comment by macjeff** [comment]
thanks.  I was just posting this as an FYI.  I always have a clone backup and in this case the fix is as easy as installing the old version of NodeJS over the new one. 
Your fast response and efforts are MUCH appreciated.  thanks!!!
