### ISSUE TITLE
New version fails to install

### ISSUE THREAD

**Issue by LutzRFrank** [oznu/homebridge-config-ui-x#905]
pi@homebridge:~ $ sudo -E -n npm install homebridge-config-ui-x@latest
npm WARN npm npm does not support Node.js v12.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-10-21T11_51_28_360Z-debug.log

**Comment by LutzRFrank** [comment]
Cant update to the latest version

**Comment by oznu** [comment]
This is an issue with `npm`.

**Comment by LutzRFrank** [comment]
Thank you 🤗
I'm on 12.19.0 ... thought this is supported

**Comment by oznu** [comment]
It is, the issue is your `npm` install has some how gotten out of date.

Work through this carefully to repair your install:

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

**Comment by LutzRFrank** [comment]
Thank You again. Had to reinstall my Raspberry Pi to pick up the npm. 
All fixed now. 
Upgrade went flawless.

**Comment by oznu** [comment]
Great! I'm happy you got it sorted.
