### ISSUE TITLE
Config.schema conditional display not working

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#907]
@oznu 

looks like conditional display not working, if use it in config.schema the conditional position still hidden even the 'auth' change to true or false.

Here the part of code:
```
"auth": {
              "title": "Authentication",
              "type": "boolean",
              "default": false,
              "required": true
            },
            "user": {
              "title": "User",
              "type": "string",
              "required": false,
              "condition": {
                "functionBody": "return model.auth === true;"
              }
            },
            "pass": {
              "title": "Password",
              "type": "string",
              "required": false,
              "condition": {
                "functionBody": "return model.auth === true;"
              }
```

Config UI X 4.30.0

**Comment by oznu** [comment]
Can you show the whole thing? Or just a link is fine.

**Comment by grzegorz914** [comment]
`{
  "pluginAlias": "OpenWebIfTv",
  "pluginType": "platform",
  "singular": true,
  "headerDisplay": "This plugin works with Sat Receivers Basis on the OpenWebIf interface and are exposed to HomeKit as separate accessories and each needs to be manually paired.\n\n1. Open the Home <img src='https://user-images.githubusercontent.com/3979615/78010622-4ea1d380-738e-11ea-8a17-e6a465eeec35.png' height='16.42px'> app on your device.\n2. Tap the Home tab, then tap <img src='https://user-images.githubusercontent.com/3979615/78010869-9aed1380-738e-11ea-9644-9f46b3633026.png' height='16.42px'>.\n3. Tap *Add Accessory*, and select *I Don't Have a Code or Cannot Scan*.\n4. Enter the Homebridge PIN, this can be found under the QR code in Homebridge UI or your Homebridge logs, alternatively you can select *Use Camera* and scan the QR code again.",
  "footerDisplay": "This plugin works with Sat Receivers basis on OpenWebIf interface which is available [here](https://github.com/grzegorz914/homebridge-openwebif-tv).",
  "schema": {
    "type": "object",
    "properties": {
      "devices": {
        "title": "Devices",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "title": "Device name",
              "type": "string",
              "default": "Sat Receiver",
              "required": true
            },
            "host": {
              "title": "Address IP",
              "type": "string",
              "default": "192.160.1.10",
              "required": true,
              "format": "ipv4"
            },
            "port": {
              "title": "Port",
              "type": "integer",
              "default": 80,
              "maximum": 65535,
              "required": true
            },
            "auth": {
              "title": "Authentication",
              "type": "boolean",
              "default": false,
              "required": true
            },
            "user": {
              "title": "User",
              "type": "string",
              "required": false,
              "condition": {
                "functionBody": "return model.auth === false;"
              }
            },
            "pass": {
              "title": "Password",
              "type": "string",
              "required": false,
              "condition": {
                "functionBody": "return model.auth === false;"
              }
            },
            "volumeControl": {
              "title": "Volume control mode",
              "type": "integer",
              "default": 0,
              "maximum": 2,
              "description": "Here select what a volume control mode You want to use. If select *None* only hardware buttons in RC app can be used to control volume.",
              "oneOf": [
                {
                  "title": "None",
                  "enum": [
                    0
                  ]
                },
                {
                  "title": "Slider",
                  "enum": [
                    1
                  ]
                },
                {
                  "title": "Fan",
                  "enum": [
                    2
                  ]
                }
              ],
              "required": false
            },
            "switchInfoMenu": {
              "title": "Switch Info/Menu",
              "type": "boolean",
              "default": false,
              "required": false,
              "description": "This toggle behaviour for *I* button in RC app and *PowerModeSelection* in settings."
            },
            "inputs": {
              "title": "Channels",
              "buttonText": "Add channel",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "title": "Channel name",
                    "type": "string",
                    "default": "TVN 24",
                    "required": true
                  },
                  "reference": {
                    "title": "Channel reference",
                    "type": "string",
                    "default": "1:0:1:3DD2:640:13E:820000:0:0:0:",
                    "required": true
                  }
                }
              }
            },
            "manufacturer": {
              "name": "Manufacturer",
              "type": "string",
              "placeholder": "Manufacturer",
              "description": "Set the manufacturer name.",
              "required": false
            },
            "modelName": {
              "name": "Model",
              "type": "string",
              "placeholder": "Model",
              "description": "Set the model name.",
              "required": false
            },
            "serialNumber": {
              "name": "Serial Number",
              "type": "string",
              "placeholder": "SerialNumber",
              "description": "Set the serial number.",
              "required": false
            },
            "firmwareRevision": {
              "name": "Firmware Revision",
              "type": "string",
              "placeholder": "Firmware Revision",
              "description": "Set the firmware revision.",
              "required": false
            }
          }
        }
      }
    }
  },
  "layout": [
    {
      "key": "devices",
      "type": "tabarray",
      "title": "{{ value.name || 'new device' }}",
      "items": [
        "devices[].name",
        "devices[].host",
        "devices[].port",
        {
          "key": "devices[]",
          "type": "section",
          "title": "Channels",
          "expandable": true,
          "expanded": false,
          "items": [
            {
              "key": "devices[].inputs",
              "type": "array",
              "orderable": false,
              "buttonText": "Add channel",
              "items": [
                "devices[].inputs[].name",
                "devices[].inputs[].reference"
              ]
            }
          ]
        },
        {
          "key": "devices[]",
          "type": "section",
          "title": "Advanced Settings",
          "expandable": true,
          "expanded": false,
          "items": [
            "devices[].auth",
            "devices[].user",
            "devices[].pass",
            "devices[].switchInfoMenu",
            "devices[].volumeControl"
          ]
        },
        {
          "key": "devices[]",
          "type": "section",
          "title": "Branding",
          "expandable": true,
          "expanded": false,
          "items": [
            "devices[].manufacturer",
            "devices[].modelName",
            "devices[].serialNumber",
            "devices[].firmwareRevision"
          ]
        }
      ]
    }
  ]
}`

**Comment by oznu** [comment]
`auth` is under the `devices[]` array, so your condition should look like this:

```json
              "condition": {
                "functionBody": "return model.devices[arrayIndices].auth === true;"
              }
```

**Comment by grzegorz914** [comment]
Thanks

this working OK.

**Comment by oznu** [comment]
I noticed the tabs look strange in dark mode, I'll fix those next release.

**Comment by grzegorz914** [comment]
Nice.

**Comment by grzegorz914** [comment]
any look on #856 ?

**Comment by oznu** [comment]
No yet, it's a painful exercise to debug that.
