### ISSUE TITLE
Request: Stronger visual distinction for plugins with updates

### ISSUE THREAD

**Issue by Firehed** [oznu/homebridge-config-ui-x#908]
**Is your feature request related to a problem? Please describe:**
When on the plugin screen (after clicking "N plugins out of date" on the home screen), I find it hard to determine which plugins have updates available because they don't visually stand out from the plugins that are up to date.

The only difference is that `UNINSTALL` is replaced with `UPDATE` (this also seems wrong; it should be possible to uninstall a plugin that's out of date) and `Installed` is replaced with `Update Available`, but both do so in a way that matches the existing color scheme and fonts exactly so it doesn't visually scan well.

This came up on the default theme, but I checked a couple others and it seems to be present in all of them.

**Describe the solution you'd like:**
A few options come to mind, any or all of which I think could help:

- Tinting the card background on plugins that are out of date with some sort of color to add visual distinction
- Changing the color of `Update Available`
- Leave `UNINSTALL` in place so that the addition of `UPDATE` stands out more
- Have entirely separate sections for plugins with updates and plugins and those that are up to date

If any of the maintainers support this idea and have a preference of which direction to go, I can look into making the change myself and sending a PR.

**Comment by oznu** [comment]
> Leave UNINSTALL in place so that the addition of UPDATE stands out more

This is already the case. The "Homebridge UI" plugin does not have an uninstall option, which is what you were probably seeing.
