### ISSUE TITLE
Specify the order the plugins are loaded

### ISSUE THREAD

**Issue by pjotal** [oznu/homebridge-config-ui-x#909]
**Is your feature request related to a problem? Please describe:**
Some plugins requires 2FA and those code tend to refresh in 20s or less. So as the plugins are loaded in a random order, those with 2FA tend to fail. As a workaround we're suggesting people to build a simple config file with one plugin at a time so guarantee that the token is generated before the time expires.

**Describe the solution you'd like:**
Being able to specify the order you load the plugins can be a good way to set the user priority and avoid those types of issues. It's simple, allows a good amount of flexibility and, the most important, avoid crappy workarounds (like the one i mentioned above).

**Describe alternatives you've considered:**
As mentioned above, we're suggesting people to build a simple config file with one plugin at a time so guarantee that the token is generated before the time expires.

**Additional context:**
None.

**Comment by oznu** [comment]
> NOTE 1: once you authenticate with 2FA once, a token is generated and we'll reuse it from that time on so you don't need to mind using the pin everytime you need to restart homebridge. clever, right?

Why not create a small CLI tool to generate the token that the user can add to their config directly? Like the Ring plugin does for example. If the plugin becomes popular enough we can look at building the auth directly into the UI.

**Comment by oznu** [comment]
To answer the actual question, this feature would need to be done in Homebridge before we could think about adding a way to configure it in the Homebridge UI.

**Comment by pjotal** [comment]
> Why not create a small CLI tool to generate the token that the user can add to their config directly?
because the token needs to be refreshed from times to times to keep functional, that's why we're managing it inside the plugin. so we can store the token and update it automatically whenever needed. building an external tool may work but will probably just create some other set of issues.

> this feature would need to be done in Homebridge before we could think about adding
makes sense as you're just a ui wrapper on top of it.

**Comment by oznu** [comment]
Closing as this needs work to be done in the Homebridge itself.
