### ISSUE TITLE
Allow for a short description of changes made when saving config

### ISSUE THREAD

**Issue by joberembt** [oznu/homebridge-config-ui-x#910]
**Is your feature request related to a problem? Please describe:**

When trying to restore a config from the saved/cached configs, it's hard to differentiate between them to know which one you want. 

**Describe the solution you'd like:**
I suggest allowing a small text field when saving that you can summarize changes to be able to refer back to them easier, like 'removed manual device entry'. Then, when trying to pick one, you could see the one that has the change you were looking for vs a Date/Time to try to pick based on a wild guess. Conversely, maybe have a basic diff tool style view that could be toggled to show/hide the diff between the currently loaded config and the one to potentially restore.

**Comment by oznu** [comment]
There isn't really any metadata storage for this sort of thing - the timestamps are derived from the file name.

> Conversely, maybe have a basic diff tool style view that could be toggled to show/hide the diff between the currently loaded config and the one to potentially restore.

What about this?

![image](https://user-images.githubusercontent.com/3979615/97165114-4c461180-17d7-11eb-8c5d-8ccc7479e015.png)

You can test it in `@test`:

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by joberembt** [comment]
@oznu Yes, something like that is what I was thinking. One small change I would like to see to it though, is to label which pane is which above each pane.

Thanks for adding this!

--JOsh

**Comment by oznu** [comment]
Landing in v4.31.0.
