### ISSUE TITLE
Cannot update to v4.30

### ISSUE THREAD

**Issue by AndrewJ1990** [oznu/homebridge-config-ui-x#911]
> 

**Describe Your Problem:**
Error message when trying to update to version 4.30

**Logs:**
USER: pi
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-config-ui-x@latest

npm ERR! code ENODATA
npm ERR! Cache input stream was empty

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-10-24T00_26_53_737Z-debug.log

Command failed. Please review log for details.
```
Show the Homebridge / Homebridge Config UI X logs here.
[2020-10-24T00_26_53_737Z-debug.log](https://github.com/oznu/homebridge-config-ui-x/files/5432220/2020-10-24T00_26_53_737Z-debug.log)


**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: <V12.18.3>
* **NPM Version**:

**Comment by oznu** [comment]
Issue is with npm.

Try run this in the terminal:

```
sudo npm cache clean --force
```

```
npm cache clean --force 
```

If still not working, try rebooting.

**Comment by AndrewJ1990** [comment]
Thanks, That fixed the problem 👍
