### ISSUE TITLE
Turn off Terminal in browser

### ISSUE THREAD

**Issue by SK8081** [oznu/homebridge-config-ui-x#912]
Is there any way to turn off terminal in the browser?  I prefer to SSH directly

**Comment by oznu** [comment]
Remove `HOMEBRIDGE_CONFIG_UI_TERMINAL=1` from `/etc/default/homebridge`.

**Comment by MorelloCherry** [comment]
On my installation (Raspberry Pi 4B) I do not have the file `/etc/default/homebridge` and there seem to be no sanctioned way to remove it properly. As @SK8081 mentioned before he prefers the SSH option only and so do I.

As an intermediate measure I have modified the `~homebridge/.bashrc` file to just contain:

```
#!/bin/sh

exec sleep 1
```

This is to prevent busy waits burning up CPU time.


In addition I have changed `/etc/passwd` for the user homebridge not to allow logins

```
homebridge:x:108:112::/home/homebridge:/usr/sbin/nologin
```

For now the terminal session remains a black screen with the cursor blinking and according to the logs the terminal session starts and stops after a second but at least not allow to interact with it.

For now the Terminal button is still visible in the web UI but entering anything fails but it seems disabled.

Please add the option to disable the terminal for good pr even better allow to enable it if wanted in the config, don't just assume.

Thank you.
