### ISSUE TITLE
"integrity checksum failed" when try to install on raspberry pi 3

### ISSUE THREAD

**Issue by Kirorus** [oznu/homebridge-config-ui-x#92]
When I try to install plugin on raspberry pi 3 with fresh and updated Rspbian I have Error "integrity checksum failed"

<img width="573" alt="2018-05-09 18 32 08" src="https://user-images.githubusercontent.com/21147066/39825569-bce82376-53ba-11e8-8196-f70cea6acdf5.png">

In LOG this text

`2982 verbose cwd /home/pi
2983 verbose Linux 4.14.34-v7+
2984 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm$
2985 verbose node v8.11.1
2986 verbose npm  v5.6.0
2987 error code EINTEGRITY
2988 error sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y= integrity checksum failed when us$
2989 verbose exit [ 1, true ]`

all other plugins for homebridge install normal

Could you help me?

**Comment by oznu** [comment]
Hi @Kirorus & @hackruu,

Thanks for reporting this. The latest update should fix this, can you try again and let me know?

**Comment by hackruu** [comment]
i think you forgot to bump ver :)

**Comment by oznu** [comment]
What version are you getting when you download `@latest`? 3.6.3-3 is what is published to npm.

![image](https://user-images.githubusercontent.com/3979615/39859741-2d84c53a-547e-11e8-9d56-27bb5a18ffdf.png)

**Comment by oznu** [comment]
I'm just lazy about pushing git tags 😄.

Thanks for confirming it all works now.
