### ISSUE TITLE
Cannot update confit-ui-x plugin

### ISSUE THREAD

**Issue by Mattserati** [oznu/homebridge-config-ui-x#923]
Over the last month or two, every time I try to update via the update button, I get the following error.
Can someone please help point me at a solution?
![E098A1BF-5967-4676-8E14-E26E13762804](https://user-images.githubusercontent.com/35052287/97548208-c9f16380-1a09-11eb-919f-d7dcd6d935f5.jpeg)

**Comment by paqpaqpaq** [comment]
is your npm up to date?

**Comment by Mattserati** [comment]
The log is here:
![84BE3105-FE2B-476C-9C21-214BE80AA2DE](https://user-images.githubusercontent.com/35052287/97548762-80eddf00-1a0a-11eb-9167-26322e78d347.png)

**Comment by Mattserati** [comment]
I’m not sure if NPM is up to date, and also not sure how to do any update of it inside the UI

**Comment by oznu** [comment]
Run this in the terminal:

```
sudo npm cache clean --force
```

and

```
npm cache clean --force
```

**Comment by Mattserati** [comment]
Fixed!!! Ran that command, then updated NPM, and update installed perfectly.
Thanks so much!

You are obviously someone who knows waaaaaay more than me, so can I ask one more question?
How do I update node.us, in line with this recommendation?
![7055C54A-3A49-408D-8A73-779FAF7EF0BF](https://user-images.githubusercontent.com/35052287/97551818-69b0f080-1a0e-11eb-98df-cfe1b2e77950.jpeg)

**Comment by oznu** [comment]
I'm happy that you have fixed it.

To find out how to update Node.js; click the link in that modal "How to Update Node.js" - then follow the instructions for Linux.

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js#macos-and-linux

**Comment by Mattserati** [comment]
Perfect - thanks again to both of you.

**Comment by oznu** [comment]
No problem.
