### ISSUE TITLE
Manually change Accessory Type.

### ISSUE THREAD

**Issue by Electr1fying** [oznu/homebridge-config-ui-x#924]
Hi Oznu,

Absolutely love HomeBridge UI, so thanks for your dedicated effort!

I used the search function but i didn't find a feature request like this.

I was wondering if you can implement a feature so we can manually change an accessory type of an accessory within the "Accessoiries" tab.

I use the eDomoticz plugin, so i have a somewhat limited control on accessory types. But it is difficult to get this changed once HomeBridge settles on a specific type. 

When you open the details/configuration page of an accessory, it states its type right on top. It would be nice if we would be able to change this so we can fit accessory types to our liking. 

E.g. There appears to be a new accessory type within Homekit for AVR Receivers, but my receiver is not recognised as such. It would be nice if we can give it a matching accessory type ourselves. Is this possible or is it more involving then to add supported Homekit accessory types into Homebridge/Homebridge UI?

Thanks in advance!

**Comment by masterfordev** [comment]
I think that is not possible, because the plugins are in charge of specifying what type of accessory it is. Each type of accessory has its own characteristics and if you change the type, it will cause problems in the plugin.

**Comment by oznu** [comment]
@masterfordev pretty much sums it up. You would need to ask the plugin developer to enable this in their own code.
