### ISSUE TITLE
Camera and Ring issues on 4.31

### ISSUE THREAD

**Issue by paqpaqpaq** [oznu/homebridge-config-ui-x#925]
**Describe The Bug:**
Cameras either not streaming OR not showing stills

**To Reproduce:**
FFmpeg plugin + Config UI X 4.31
Ring 4.12.1 + Config UI X 4.31

**Expected behavior:**
Ring gives weird behavior, e.g. no stills / shows camera offline, whilst stream works fluently.
FFmpeg plugged camera's do show and refresh stills, but won't stream. 

**Logs:**
That's the thing, there is no log that shows an error of any kind.

**Environment:**

* **Node.js Version**: 12.18.1
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.2.3
* **Homebridge Config UI X Version**: 4.31
* **Operating System**: pi 3B+

As soon as I revert to 4.30 or earlier, all works again.

**Comment by oznu** [comment]
The UI runs as a seperate process to Homebridge and can't really impact plugins. I see you've opened another issue on the ring project page, so I'll close this in favour of that. 

https://github.com/dgreif/ring/issues/484

**Comment by paqpaqpaq** [comment]
Well, it is not just with the ring plugin, also with Camera ffmpeg. 
As soon as I update to 4.31, there are issues with cameras, if I revert to 4.30 all problems are gone.

**Comment by serenacloos** [comment]
Wow, so you’re not even gonna take a look at it? 
Really nice… 👌🏼

**Comment by oznu** [comment]
Here is the diff from 4.30 to 4.31.

https://github.com/oznu/homebridge-config-ui-x/compare/4.30.0...4.31.0

If someone can find an issue, I will be happy to resolve it.

**Comment by paqpaqpaq** [comment]
@oznu 
Well, clearly there isn't something that is 'obviously' causing this. 
However, both plugins aren't returning any errors in the log when this occurs running 4.31. That is the weird part. There is nothing to go after.

**Comment by oznu** [comment]
Just saw your edit. I'm glad you got it resolved 😄

**Comment by paqpaqpaq** [comment]
> Just saw your edit. I'm glad you got it resolved 😄

#metoo 
Cache most likely.
