### ISSUE TITLE
Connection to Homebridge with Home app failed

### ISSUE THREAD

**Issue by Nrigoni** [oznu/homebridge-config-ui-x#926]
**Describe Your Problem:**
When trying to add the bridge accessory to home app in iPhone running iOS 14 it find the accessory ask the PIN but after a minute it said the accerory is not available

**Logs:**
attaching here the log file
[homebridge.log](https://github.com/oznu/homebridge-config-ui-x/files/5470457/homebridge.log)

```
Show the Homebridge / Homebridge Config UI X logs here. HERE THE CONFIG OF HOMEBRIDGE
```
[config.txt](https://github.com/oznu/homebridge-config-ui-x/files/5470459/config.txt)

**Homebridge Config:**

```json
Show your homebridge config.json here 

[config.txt](https://github.com/oznu/homebridge-config-ui-x/files/5470459/config.txt)
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v14.15.0.
* **NPM Version**: 6.14.8
* **Homebridge Version**: v1.1.6
* **Homebridge Config UI X Version**: v4.31.0
* **Operating System**: Windows 10 Pro
* **Process Supervisor**: Homebridge UI

**Comment by oznu** [comment]
Windows can have some issues running Homebridge - the exact cause isn't really known, it works fine on a fresh install of Windows 10 in my testing.

Because of this I recommend users running Windows 10 Pro / Enterprise / Edu run Homebridge in a HyperV VM instead:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V

**Comment by Nrigoni** [comment]
ok thanks so I have a raspberry pi 3 b+ you suggest to use it? 
can I use as OS the one here attached in the image? because I need to connect via wifi homebridge to the home network and ethernet configured for communication with PLC for use the homebridge-plc plugin

thanks for support

**Comment by oznu** [comment]
A Raspberry Pi 3 would be much better. We have a dedicated image for that:

https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

You can connect via WiFi - details are all in the guide above :)

**Comment by Nrigoni** [comment]
Perfect, and after can I setting the ethernet port with a static ip for connecting to plc?

thanks

**Comment by oznu** [comment]
Yep, you can:

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Set-A-Static-IP-Address

**Comment by Nrigoni** [comment]
Hello, I have setup the Raspberry with Homebridge image and all works fine. But I have an issue because I need to use Homebridge with Siemens PLC via the plugin Homebridge-plc I have set the static IP in ethernet connection using your guide, but if I power on the Raspberry with the ethernet cable attached it will connect to the static IP of ethernet port. There is a solution? Thanks

**Comment by Nrigoni** [comment]
If I power the system without ethernet cable attached to raspberry it will go online and I can see in the Home app all it's fine. but at this point when I attach the ethernet cable in the Home app the bridge will go offline and after a few minutes I reach this error 

[05/11/2020, 20:28:04] [Homebridge UI] [homebridge] Failed to check registry.npmjs.org for updates: "connect EHOSTUNREACH 104.16.23.35:443" - see https://git.io/JJSz6 for help.
[05/11/2020, 20:28:07] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "connect EHOSTUNREACH 104.16.17.35:443" - see https://git.io/JJSz6 for help.
[05/11/2020, 20:28:07] [Homebridge UI] [homebridge-plc] Failed to check registry.npmjs.org for updates: "connect EHOSTUNREACH 104.16.25.35:443" - see https://git.io/JJSz6 for help.

and they repeat every one minutes 

in system information I can always see 

IPv4 (wlan0) | 192.168.1.59 but it seams try to connect via ethernet so this is why the system go offline

**Comment by oznu** [comment]
On your static interface, do not assign a gateway or dns. That should result in WiFi becoming the default gateway.
