### ISSUE TITLE
How can we enable accessory control when running windows ?

### ISSUE THREAD

**Issue by goldriver2** [oznu/homebridge-config-ui-x#930]
I am starting homebridge via a scheduled task in windows 10 an can't find how to enable the accessory control, here is the arguments line I am using to start Homebridge 4 minutes after Homeseer startup:

/C "C:\Users\username\AppData\Roaming\npm\homebridge -U c:\users\username\.homebridge"

I tried adding the - I option like below but that does not work:
/C "C:\Users\username\AppData\Roaming\npm\homebridge -I -U c:\users\username\.homebridge"

thanks

**Comment by oznu** [comment]
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

This will create a real service named "homebridge". You can go into the service manager and stop it starting automatically on boot, then use your scheduled task to start it after Homeseer.
