### ISSUE TITLE
Add a "On/Off" button for each plugin

### ISSUE THREAD

**Issue by bxlouis** [oznu/homebridge-config-ui-x#931]
**Is your feature request related to a problem? Please describe:**
I recently had an issue with my Raspberry Pi, resulting in some services being down for a couple of days. 
During this time, I would have liked to be able to simply disable the Homberidge plugins that were linked to these services.

**Describe the solution you'd like:**
On the plugin page, add an "On/Off" button to each listed plugin.
Turning a plugin "Off" would comment it in the JSON config file, allowing to pause it without loosing the configuration.
Turning a plugin "On" would uncomment the JSON config file.

**Describe alternatives you've considered:**
Manually comment the config file.

**Comment by masterfordev** [comment]
It is a very good idea, hopefully it can be implemented.

**Comment by oznu** [comment]
Would be the same implementation as https://github.com/oznu/homebridge-config-ui-x/issues/287 - closing this in favour of that one.
