### ISSUE TITLE
disable scheduledBackup

### ISSUE THREAD

**Issue by det-box** [oznu/homebridge-config-ui-x#932]
Hello,
Thanks for the great program,
how can I disable scheduledBackup (./backups/instance-backups/) for all instances?
Thanks

**Comment by oznu** [comment]
There is not configurable option to disable these backups.

You can configure the backup destination:

https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#scheduledbackuppath

If set to a path the process does not have permission to write to, the backup won't happen.

**Comment by det-box** [comment]
A pity,
a switch would be an option.
Thanks
