### ISSUE TITLE
Configure off terminal/restart/shutdown

### ISSUE THREAD

**Issue by matts07** [oznu/homebridge-config-ui-x#933]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Ability to disable the terminal and restart/shutdown in UI config file

**Describe alternatives you've considered:**
N/A

**Comment by oznu** [comment]
You can disable the web terminal by removing `HOMEBRIDGE_CONFIG_UI_TERMINAL=1` from the `/etc/default/homebridge` file then restarting the service. This is done as an environment variable as having a config option to disable / re-enable the terminal wouldn't be very secure.

You can prevent the UI from rebooting or shutting down your server using the `visudo` tool and removing the shutdown command from the homebridge service user.

**Comment by matts07** [comment]
@oznu Thank you very much!
