### ISSUE TITLE
Disable automatic backup

### ISSUE THREAD

**Issue by efkayx** [oznu/homebridge-config-ui-x#938]
Hi,

how can I disable the automatic backup each night as my homebridge folder is beeing used as well for homebridge-camera-ui trigger recordings and my recording folder is right now 10GB and growing. So each night I'm gonna backup everything. How can I exclude certain folders within the homebridge folder in the configu-ui-x or disable the automatic completely?

Thanks,

EfkayX

**Comment by oznu** [comment]
This will land in the next release:

https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#scheduledbackupdisable

**Comment by oznu** [comment]
Recordings made by `homebridge-camera-ui` and stored in the `./recordings` directory are now exlucded from backups.
