### ISSUE TITLE
What changed for websocket proxy?

### ISSUE THREAD

**Issue by theOrakle** [oznu/homebridge-config-ui-x#94]
I had a working config #43 until the last upgrade.

Do we have a working Apache Proxy config now?

**Comment by oznu** [comment]
Hi @theOrakle,

You might have to pass through the `Host` header from the browser so the appropriate CSP headers can be returned to the browser.

https://www.ctrl.blog/entry/how-to-httpd-reverseproxy-hostheader

**Comment by theOrakle** [comment]
Perfect!

That’s what I needed to know. I added both:
        UseCanonicalName on
        ProxyPreserveHost on

Take care & thank you.

**Comment by oznu** [comment]
Thanks @theOrakle, do you mind sharing your full apache vhost block so I can add this to the wiki?

**Comment by theOrakle** [comment]
No worries.

<VirtualHost 10.0.69.116:80>
        ServerName homebridge.domain.com
        ServerAdmin me@domain.com
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/homebridge.error.log
        CustomLog ${APACHE_LOG_DIR}/homebridge.access.log combined

        <Location />
                ProxyPass http://localhost:8081/
                ProxyPassReverse http://localhost:8081/
                UseCanonicalName on
                ProxyPreserveHost on
                RewriteEngine on
                RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
                RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
                RewriteRule .* ws://localhost:8081%{REQUEST_URI} [P]
        </Location>
</VirtualHost>
