### ISSUE TITLE
Just a question about Security of Homebridge

### ISSUE THREAD

**Issue by masterfordev** [oznu/homebridge-config-ui-x#941]
**Describe Your Problem:**

The plugins have always been able to make connections to external servers? Since before version 4.32? I understood that Homebridge was running only within the local network. Now with the new option to run server-side scripts is not compromised security? Or the new functionality is only for UI?

Thanks !

**Comment by oznu** [comment]
Plugins running in the Homebridge context (not the UI) have always been able to run server side code - that's just how they work.

**Comment by masterfordev** [comment]
I see. I always had that concern but I never dared to ask it.. thank you for clarifying it!

Thanks for the new interface functionality, I hope it will be very useful for many developers.

**Comment by oznu** [comment]
No problem 😄 

Any malicious plugins (we haven't had any reports of one yet...) would be blacklisted in the UI, and reported to the npm registry and GitHub for removal (neither of these platforms tolerate malware of any kind).
