### ISSUE TITLE
Notification of available updates

### ISSUE THREAD

**Issue by jcleek** [oznu/homebridge-config-ui-x#943]
I see several asks for update changes but nothing about getting notified of updates available. Right now you must open the Config UI to see updates are needed. How about sending an email or push notification when they are available?

**Comment by masterfordev** [comment]
I did this request before and the answer was click "watch" this project to be emailed by github when have new releases. Thats what i did. 

I dont know if @oznu have any idea to this.

**Comment by jcleek** [comment]
Thanks for the response. That "solution" isn't really helpful if you have 10 plugins and what is the point of having a tool that pulls it all together if it can't pull notifications together? It is already there anyway. It tells me in the web page if a plugin or the UX is updated. Just give me an option to receive an email...
