### ISSUE TITLE
Homebridge.local doesn’t load with latest Config UI update

### ISSUE THREAD

**Issue by ahmadnazirafiq** [oznu/homebridge-config-ui-x#944]
I didn’t install any new plugins. Just recently I’ve been prompted to update to the latest Homebridge UI plugins, rebooted, loads just fine.

Until after a few minutes, homebridge.local doesn’t load for me anymore. It’s stuck at loading. I’ve tried several different device, same issue. Home app loads all Homebridge accessories just fine, its the Config UI that fails to load.

**To Reproduce:**
Update to the latest Config UI, with Homebridge version 1.2.3 installed on Raspberry Pi 4b then reboot Homebridge

**Expected behavior:**
After for a few minutes/hours, config UI no longer loads. No error message, just a blank page. After rebooting, it loads fine again. Until it wasn’t again.

**Comment by oznu** [comment]
Hi @ahmadnazirafiq,

I think you forgot to attach the logs?

**Comment by ahmadnazirafiq** [comment]
> Hi @ahmadnazirafiq,
> 
> I think you forgot to attach the logs?

I’m not sure how to obtain it without access to the config UI. How do I get the logs?

**Comment by oznu** [comment]
Can you tell me about your setup? Without this information I can't even tell you how to get the logs 😄 

```
**Environment:**

* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none
```

**Comment by oznu** [comment]
Ok looking though your issue history on GitHub I can see you are running the Homebridge Rasoberry Pi Image?

**Comment by oznu** [comment]
Also, I assume you've tried connecting via IP address? Connections via homebridge.local are not guaranteed to work - the homebridge raspberry Pi image setup guide says as much.

**Comment by ahmadnazirafiq** [comment]
> ```
> **Environment:**
> 
> * **Node.js Version**: 
> * **NPM Version**: 
> * **Homebridge Version**: 
> * **Homebridge Config UI X Version**: v4.32.0
> * **Operating System**: Raspbian
> * **Process Supervisor**: hb-service
> ```

**Comment by ahmadnazirafiq** [comment]
> Ok looking though your issue history on GitHub I can see you are running the Homebridge Raspberry Pi Image?
> 
> If so; see https://github.com/homebridge/homebridge-raspbian-image/wiki#useful-commands for the log viewing command.

This is silly but how I do access the Pi through my Mac via Terminal? Both devices are on the same network.

**Comment by oznu** [comment]
Before bothering with that, can you access the UI by going to the IP address of your Pi in a browser?

EXAMPLE: `http://192.168.1.255`

**Comment by ahmadnazirafiq** [comment]
> Before bothering with that, can you access the UI by going to the IP address of your Pi in a browser?
> 
> EXAMPLE: `http://192.168.1.255`

Yes, I can access it via IP just fine. Until after a few hours, it wasn’t accessible for no reason although accessories on Home app loads just fine. I’m not sure what’s causing it.

**Comment by oznu** [comment]
The "homebridge.local" dns functionality is not anything to do with the UI (or the UI update) - that's taken care of by the Linux operating system Homebridge is running on top of.

Why it would stop working randomly, I have no idea sorry.

**Comment by oznu** [comment]
By chance, are you running another instance of homebridge on another device somewhere in your network?

**Comment by ahmadnazirafiq** [comment]
> By chance, are you running another instance of homebridge on another device somewhere in your network?

No. Not running Homebridge anywhere other than Pi

**Comment by oznu** [comment]
Thanks, I'm still not sure what would cause this behaviour then.

But so long as you're able to access the UI via the Pi's IP address; it sounds like homebridge-config-ui-x is working as expected.
