### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by ands0me** [oznu/homebridge-config-ui-x#954]
![AC8D4EEF-5763-415B-A05E-D9E89945C35F](https://user-images.githubusercontent.com/74508966/99194405-73ad5000-277f-11eb-85d4-e4e8c332e9d1.jpeg)

**Comment by ands0me** [comment]
The Backup function has been working before the last updates.

**Comment by oznu** [comment]
Delete the `/var/homebridge/nano.save` file - it's likely a broken synlink.
