### ISSUE TITLE
Homebridge Server Monitoring - Causing Performance Issues

### ISSUE THREAD

**Issue by sgerlach** [oznu/homebridge-config-ui-x#956]
I think, homebridge-config-ui is doing some kind of CPU/Memory stat every second and it's causing performance issues on my system ecasue sometimes the tasks lag and back up. Is there a way to tune the frequency of these polls or turn them off? Something is causing this command to run every second (it could be homebridge itself, but I can't find the thing that's doing it)
```
/bin/sh -c /sbin/sysctl -a 2>/dev/null | grep -E "hw.realmem|hw.physmem|vm.stats.vm.v_page_count|vm.stats.vm.v_wire_count|vm.stats.vm.v_active_count|vm.stats.vm.v_inactive_count|vm.stats.vm.v_cache_count|vm.stats.vm.v_free_count|vm.stats.vm.v_page_size"
```

**Comment by oznu** [comment]
Added the `disableServerMetricsMonitoring` option. Set to `true` to disable all CPU / RAM metric collection.

**Comment by oznu** [comment]
This will be available in the next release, but is in `@test` now:

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-config-ui-x/wiki/Config-Options#disableservermetricsmonitoring

**Comment by sgerlach** [comment]
Sweet! Thanks @oznu
