### ISSUE TITLE
dont see QR-Code after change to hb-services

### ISSUE THREAD

**Issue by testpaul999** [oznu/homebridge-config-ui-x#958]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by testpaul999** [comment]
H,

after I change to use hs-services I dont see the QR-Code at the homebridge protokoll
Setup Payload:
X-HM://0023NJAQP1ENH
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 110-92-001 │     
    └────────────┘     
                       
[16.11.2020, 19:23:15] Homebridge v1.2.3 is running on port 51515.

regards

**Comment by oznu** [comment]
This is intentional, the QR code is shown in the UI instead.
