### ISSUE TITLE
Temperature display units should be configurable

### ISSUE THREAD

**Issue by charlesvestal** [oznu/homebridge-config-ui-x#96]
It appears the plugin displays in Celsius; it would be great to have display be configurable to F for other regions.

**Comment by pilot76103** [comment]
I would also like this functionality.

**Comment by jfanok** [comment]
This is great! Where do you change it though, @oznu ? I can't find the config setting anywhere

**Comment by pilot76103** [comment]
@jfanok according to the code it looks like you go to the Plugin page then edit the settings for homebridge-config-ui.

**Comment by oznu** [comment]
I haven't published this yet, will do soon.

**Comment by oznu** [comment]
Landed in 3.7.0

You can configure this option using the plugin settings, which can be found in on the  *Plugins* screen or by setting `tempUnits` to `c` or `f` in your `config.json`.

![image](https://user-images.githubusercontent.com/3979615/40780976-94bf4ec8-651d-11e8-827d-b3fc1fe3fe54.png)

**Comment by pilot76103** [comment]
@oznu does this only work for the OS Temp File? I believe the request may have been a request for the accessories section as well. For example even with the Fahrenheit setting enable the Nest thermostat under accessories still displays as Celsius.

**Comment by oznu** [comment]
I'll make it happen for the accessories display as well, using the same config option.

**Comment by oznu** [comment]
Imperial display units now apply to temperature sensors and thermostat accessories as well as of 3.8.0.

**Comment by tracyajones** [comment]
Have you released 3.8.0?  I just see 3.5.1 which does not seem to have this feature.  Thanks for the great plugin btw

**Comment by mafyata** [comment]
4.6.7 is latest version. 
https://github.com/oznu/homebridge-config-ui-x/releases

**Comment by tracyajones** [comment]
Ha - sorry i was looking at the nest plugin and not the ui plugin

can you give an example of how to configure it?  Im struggling if it belongs in the config section, the accessory section, or ??  If i put it in the accessory section homebridge does not start up as it does not thing Thermostat is an accessory

**Comment by mafyata** [comment]
Sorry , I don’t use nest plugin.
