### ISSUE TITLE
not starting up after latest update homebridge ui x

### ISSUE THREAD

**Issue by arp013** [oznu/homebridge-config-ui-x#960]
homebridge doesn't start up after latest update homebridge uix

after trying to install previous version by ssh getting the following error

pi@homebridge:~ $ npm install --prefix /usr -g --unsafe-perm homebridge-config-ui-x@4.32.0
npm WARN checkPermissions Missing write access to /usr/lib
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-11-17T22_19_36_023Z-debug.log

**Comment by arp013** [comment]
![Schermafbeelding 2020-11-17 om 23 23 36](https://user-images.githubusercontent.com/61652669/99457888-f96dfe80-292b-11eb-8c73-155c5da47fd3.png)

**Comment by oznu** [comment]
Can you show the logs?

**Comment by arp013** [comment]
with the tail command:

    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:99547:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
[17/11/2020, 23:25:12] Loaded config.json with 0 accessories and 1 platforms.
[17/11/2020, 23:25:12] ---
[17/11/2020, 23:25:13] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM

**Comment by oznu** [comment]
Also, why the `--prefix=/usr` in your command?

**Comment by arp013** [comment]
sorry don't know what you mean?

**Comment by arp013** [comment]
what would the right command be?

**Comment by oznu** [comment]
Uninstall re-install using the following:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by arp013** [comment]
> # cleanup
> sudo npm uninstall -g homebridge-config-ui-x

then it pops up with password, it is a standard install but the pi password doesn't work

**Comment by arp013** [comment]
pi@homebridge:~ $ sudo npm uninstall -g homebridge-config-ui-x
removed 363 packages in 27.422s
pi@homebridge:~ $ sudo npm install -g --unsafe-perm homebridge-config-ui-x
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-rwvjx/oO5mIoq98KR+xdvgGysDG/ZBXJ4MpdBCG8NStA/U9jKGIlqqvG1QwaLmZQxDx5hWfk3ZZjPaIw8JZ1eA== integrity checksum failed when using sha512: wanted sha512-rwvjx/oO5mIoq98KR+xdvgGysDG/ZBXJ4MpdBCG8NStA/U9jKGIlqqvG1QwaLmZQxDx5hWfk3ZZjPaIw8JZ1eA== but got sha512-UyOCfcMQ6VRBZLBvbvenQsmH0Sh4YmQeIeIXFEK1s3RhfK1MJFXispWfk67WChANHyydrFpCCY0FgHL1ruQ4eQ==. (962 bytes)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/code-point-at: Integrity verification failed for sha512-rwvjx/oO5mIoq98KR+xdvgGysDG/ZBXJ4MpdBCG8NStA/U9jKGIlqqvG1QwaLmZQxDx5hWfk3ZZjPaIw8JZ1eA== (/root/.npm/_cacache/content-v2/sha512/af/0b/e3c7fa0ee66228abdf0a47ec5dbe01b2b031bf6415c9e0ca5d0421bc352b40fd4f63286225aaabc6d50c1a2e6650c43c798567e4dd96633da230f0967578)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-17T22_32_02_827Z-debug.log

**Comment by oznu** [comment]
Clean cache then try again

Run both:

```
npm cache clean --force
sudo npm cache clean --force
```

**Comment by arp013** [comment]
did this and the the install again, and then got this
client_loop: send disconnect: Broken pipefy: sill extract gauge@~2.7.3 extracted to /

**Comment by oznu** [comment]
Disconnect from ssh, reconnect, try the clean cache and re-install command again.

**Comment by arp013** [comment]
thanks it is working again, what have i done wrong in the first place you think? but thanks for the super support

**Comment by oznu** [comment]
I'm not sure; sometimes a slow / dying SD card can cause strange problems like this, other times it's just `npm` being special.

I'd suggest making a backup while your up and running in case you ever need it:

https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

**Comment by arp013** [comment]
i sure will do , thanks again
