### ISSUE TITLE
Restart w/ log delete

### ISSUE THREAD

**Issue by ssllii** [oznu/homebridge-config-ui-x#961]
**Is your feature request related to a problem? Please describe:**
Restart w/ log delete

**Describe the solution you'd like:**
I can restart from the UI, but I would really like to have an option to restart w/ log delete.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by oznu** [comment]
When running with `hb-service` there is an option to delete the logs on the main log page.

I don't think it needs to happen automatically as it would not be the behaviour most people expect.

**Comment by ssllii** [comment]
Ok, thanks for the response.
I was more thinking as an additional option for Restart, something like Restart w/log delete.
