### ISSUE TITLE
Issue with Restore and HomeKit reg number

### ISSUE THREAD

**Issue by gdotp01** [oznu/homebridge-config-ui-x#963]
**Describe The Bug:**
Did a full backup and restored to a new Pi. Everything seems to work and it’s visible in the HomeKit home app. However the HomeKit registration number displayed in the UI is different from that advertised in the log file. It also did not save the UI settings, Colour changed on the restored version and screen layout returned to default. I’ve moved from one pi zero to a new one as a test before migrating to a pi 4

**To Reproduce:**
Restore from backup

**Expected behavior:**
Numbers should match and UI should be restored

**Logs:**
Screen shot attached showing numbers different

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**
Attached
![07661314-829C-4DEE-8CC0-4DB567B30713](https://user-images.githubusercontent.com/50060482/99737309-f6a41280-2abf-11eb-9593-65646beecea6.jpeg)

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
It looks like you didn't click the "Restart Homebridge" button from the "Restore" tab. The button on this page restarts the bridge in a special way to ensure none of the existing stuff is left over.

![image](https://user-images.githubusercontent.com/3979615/99737900-61d00200-2b1d-11eb-8b9c-d72234970350.png)

I have just tested *not* clicking this button and was able to reproduce the issue you describe, however when clicking the "Restart Homebridge" button from the "Restore" tab it works as expected.

**Comment by oznu** [comment]
Have added a small change to make it so the "Normal" restart button will work as well.

**Comment by gdotp01** [comment]
Thanks. I tried it last night and it all worked
