### ISSUE TITLE
Not a bug, would like some pointers on modifing Config-ui-x

### ISSUE THREAD

**Issue by Final-Hawk** [oznu/homebridge-config-ui-x#967]
Hi,
This is NOT a bug report, just simply looking for some help.  I am currently using a homebridge managing app that only works with hoobs and config-ui-x  but I would like to monitor another different systemd service, more specifically HAP-NodeJS. I was wondering how or if I could get config ui x to monitor that service instead of the homebridge service. I do not care if it gives errors for not being able to find plugin details as well. To note I am on raspberry os and have spent over 2 hours trying to figure it out myself.  Thanks in advance and hope you can help.

**Comment by oznu** [comment]
You could look into standalone mode:

https://github.com/oznu/homebridge-config-ui-x/wiki/Standalone-Mode

You can set the logger and restart command to be any systemd service.

That's beyond the scope of this project though.
