### ISSUE TITLE
Update node.js

### ISSUE THREAD

**Issue by Ludelag** [oznu/homebridge-config-ui-x#968]
Hello, good evening. I want to update the NODE.JS, is running in my pc the v. 12.18.4 and i would like to install the last version. will it affect the behaivor of the homebridge? to install it should I stop the service of the homebridge and then install the newest version and then start again the services or should I install all again?

Thank you

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10#major-nodejs-version-updates for guidance on updating Node.js on Windows.

**Comment by Ludelag** [comment]
Dear @oznu we got this problem updating the Node.js to the version recommended in your post.
The Homebridge crashes even following the instructions and making the rebuild of the services, please see attach pics. 
![IMG_4633](https://user-images.githubusercontent.com/69207063/100428094-c34f1e00-3093-11eb-8474-34cde0ea591f.JPG)
![IMG_4634](https://user-images.githubusercontent.com/69207063/100428099-c4804b00-3093-11eb-9969-c6272b582239.jpg)
