### ISSUE TITLE
Whitelist IP Address

### ISSUE THREAD

**Issue by anhnvme** [oznu/homebridge-config-ui-x#97]
Hello,

Can you add feature whitelist IP Addresss without login ?
Example,  i will whitelist with 192.168.1.0/24 that mean i all device from home will be access dashboard without login

**Comment by oznu** [comment]
It's possible to disable authentication entirely by setting `auth` to `none` in the `config.json`.

If your exposing the UI to the internet as well you should be using a reverse proxy which can be used to add authentication back in for remote users.
