### ISSUE TITLE
Add "device not responding" to UI

### ISSUE THREAD

**Issue by trise-ne** [oznu/homebridge-config-ui-x#973]
**Is your feature request related to a problem? Please describe:**

If a device is not responding there is no representation in the UI. For example someone cut power of a smart-lamp. The "offline/not-responding-state" is is represented in the Home-App, but it's not shown in the HB UI. Making this possible would increase the usability of the HB UI.

**Describe the solution you'd like:**

Display an error icon/label for unresponsive (offline) devices.

**Describe alternatives you've considered:**

**Additional context:**

Here is a screenshot of the Home-App showing the unresponsive device:
<img width="104" alt="Bildschirmfoto 2020-11-26 um 10 41 10" src="https://user-images.githubusercontent.com/58232489/100334970-ba4b4780-2fd4-11eb-8ba4-554f0c249a34.png">

This is the corresponding HB UI screenshot of the unresponsive device:
<img width="104" alt="Bildschirmfoto 2020-11-26 um 10 41 25" src="https://user-images.githubusercontent.com/58232489/100335979-e4e9d000-2fd5-11eb-9eea-31fda89b5f78.png">

I hope that I'm guessing right, that this is related to the HB UI and not something that's up to the plugin developers.
Thanks for your great work and your time to look through this.

**Comment by trise-ne** [comment]
I‘m still here mr. stale 🎅🏻

**Comment by trise-ne** [comment]
This should not be stale.

**Comment by oznu** [comment]
If i ever implement this, I'll mention this issue 😄 

It's very far down the to-do list and can be closed for now.
