### ISSUE TITLE
can not update from  v4.29.0 to v4.34.0 

### ISSUE THREAD

**Issue by Seven75271** [oznu/homebridge-config-ui-x#974]
unable to update plug-in. vry self taught on this.

USER: pi
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-config-ui-x@latest

npm ERR! code EEXIST
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/.bin/prebuild-install
npm ERR! Refusing to delete /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/.bin/prebuild-install: ../lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js symlink target is not controlled by npm /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/prebuild-install
npm ERR! File exists: /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/.bin/prebuild-install
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-11-26T18_48_21_841Z-debug.log

Command failed. Please review log for details.

[11/26/2020, 12:45:55] [Config] Running Command: sudo -E -n npm install homebridge-config-ui-x@latest
INFO: [Device Event]: (water heater) [TEMPERATURE] is 72.1
ERROR: (update) | We received a request from a client that didn't provide a valid access_token and app_id
[11/26/2020, 12:48:22] [Config] Command failed. Please review log for details.
[1606416533487] INFO     (21729 on homebridge): incoming request
    v: 1
    reqId: 641
    req: {
      "method": "GET",
      "url": "/api/server/qrcode.svg",
      "hostname": "homebridge.local",
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 58900
    }
[1606416533559] INFO     (21729 on homebridge): request completed
    v: 1
    reqId: 641
    res: {
      "statusCode": 200
    }
    responseTime: 70.9315242767334

**Homebridge Config:**

	 "bridge": {
	        "name": "Homebridge EA7F",
	        "username": "0E:7D:78:1B:EA:7F",
	        "port": 51291,
	        "pin": "000-00-000"
	    },
	    "accessories": [],
	    "platforms": [
	        {
	            "name": "Config",
	            "port": 8581,
	            "auth": "form",
	            "theme": "auto",
	            "tempUnits": "f",
	            "lang": "auto",
	            "debug": true,
	            "sessionTimeout": 86400000,
	            "platform": "config"
	        },
	        {
	            "name": "SmartThings-v2",
	            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
	            "app_id": "c1a3f-478d-000000000",
	            "access_token": "00000-0000-0000f9",
	            "direct_port": 8000,
	            "temperature_unit": "F",
	            "validateTokenId": true,
	            "logConfig": {
	                "debug": false,
	                "showChanges": true,
	                "hideTimestamp": true,
	                "hideNamePrefix": true,
	                "file": {
	                    "enabled": true,
	                    "level": "good"
	                }
	            },
	            "platform": "SmartThings-v2"
	        },
	        {
	            "email": "T0000@gmail.com",
	            "password": "00000000",
	            "platform": "NeatoVacuumRobot"
	        },
	        {
	            "refreshToken": "ey0000000zUxMi000000000vYXV0aC9pbnRw",
	            "debug": true,
	            "platform": "Ring"
	        },
	        {
	            "name": "Bedroom",
	            "hubIP": "192.168.7.76",
	            "hubName": "Bedroom",
	            "otherPlatforms": [
	                {
	                    "name": "Living Room",
	                    "hubIP": "192.168.7.54",
	                    "hubName": "Living Room"
	                }
	            ],
	            "platform": "HarmonyHubWebSocket"
	        }
	    ]
	}
```

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Homebridge Version**: <!-- homebridge -V -->
* **Homebridge Config UI X Version**:
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by oznu** [comment]
Uninstall / reinstall:

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm --force homebridge-config-ui-x
```

What version of npm / node are you using?

**Comment by Seven75271** [comment]
Node.js Version | v12.17.0

Npm Version | v6.14.5

**Comment by Seven75271** [comment]
When I try to clean up I get this	


npm ERR! code EEXIST
	npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/.bin/prebuild-install
	npm ERR! Refusing to delete /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/.bin/prebuild-install: ../lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js symlink target is not controlled by npm /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/prebuild-install
	npm ERR! File exists: /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/.bin/prebuild-install
	npm ERR! Remove the existing file and try again, or run npm
	npm ERR! with --force to overwrite files recklessly.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2020-11-27T21_40_58_488Z-debug.log

**Comment by oznu** [comment]
Manually delete it:

```
sudo rm -rf /usr/local/lib/node_modules/homebridge-config-ui-x
```

Then re-install.
