### ISSUE TITLE
Some accessories missing v1.3.0 beta 29

### ISSUE THREAD

**Issue by MatthewGCampbell** [oznu/homebridge-config-ui-x#982]
The homebridge UI seems to be missing my nest cameras as well as my unifi protect cameras they all show up in homekit but just not the homebridge UI accessories section:
![7842637C-EA53-4DE4-B752-67CF63D584E4](https://user-images.githubusercontent.com/31420840/100634894-d8c78080-32fd-11eb-96dc-a3182e4bb56e.jpeg)
![1306585B-A5E5-4A1F-92A7-FF023ADB4311](https://user-images.githubusercontent.com/31420840/100635009-fbf23000-32fd-11eb-9197-3f1607be9ba9.jpeg)

**Comment by oznu** [comment]
Cameras aren't shown in the Homebridge UI accessories tab.
