### ISSUE TITLE
Can one simply update from systemd to hb-service?

### ISSUE THREAD

**Issue by paqpaqpaq** [oznu/homebridge-config-ui-x#984]
**Describe Your Problem:**
pi is now running hb as systemd

**Environment:**

* **Node.js Version**: 12.17
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.2.3
* **Homebridge Config UI X Version**: 4.33
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

What is the safe way to go from systemd to hb-service? I installed hb-service on another pi which had a dead SD card, and I like that better, but don't want to start from scratch.

**Comment by oznu** [comment]
If your current storage path is `/var/lib/homebridge` you can do so easily.

Just stop the existing service:

```
sudo systemctl stop homebridge
```

Then run:

```
sudo hb-service install --user homebridge
```

The UI port will change to 8581; but you can change that back to whatever you want after logging in.

I'd recommended taking a backup first.

**Comment by paqpaqpaq** [comment]
hmmm it's on /var/homebridge

**Comment by oznu** [comment]
You can copy/move it first.

**Comment by paqpaqpaq** [comment]
thanks.  Sounds like something to first pibaker the sd card ;)
