### ISSUE TITLE
Updating homebridge-config-ui-x is not possible

### ISSUE THREAD

**Issue by Waylikemark** [oznu/homebridge-config-ui-x#985]
Everytime i want to update Homebridge config ui x i keep getting the same error. The previous updates i've managed to install by keep trying every day, through terminal (SSH) with and without sudo su and ofcourse the webinterface. after i guess 50 tries it updated and everything was fine untill this update the bug returned. 

I just click update un the UI or type in "sudo -E -n npm install -g homebridge-config-ui-x@latest" in the SSH terminal. Which produces the following error:

"npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-xzwVSdiTKJ4osf4Pu4SMsw1VYX43UnfKCr3Huuy7lAwfHNDIqhaiVUjdcYYYBTdbRnBU4l+OHTm1KImfOduQbw== integrity checksum failed when using sha512: wanted sha512-xzwVSdiTKJ4osf4Pu4SMsw1VYX43UnfKCr3Huuy7lAwfHNDIqhaiVUjdcYYYBTdbRnBU4l+OHTm1KImfOduQbw== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes) npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/@nestjs%2fcommon: Integrity verification failed for sha512-xzwVSdiTKJ4osf4Pu4SMsw1VYX43UnfKCr3Huuy7lAwfHNDIqhaiVUjdcYYYBTdbRnBU4l+OHTm1KImfOduQbw== (/root/.npm/_cacache/content-v2/sha512/c7/3c/1549d893289e28b1fe0fbb848cb30d55617e375277ca0abdc7baecbb940c1f1cd0c8aa16a25548dd71861805375b467054e25f8e1d39b528899f39db906f)

npm ERR! a complete log of this run can be found in:
npm ERR!       /root/.npm/_logs/2020-12-02T09_17_34_008Z-debug.log"

**Environment:**

* **Node.js Version**: v14.15.1
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.1.6
* **Homebridge Config UI X Version**: None atm
* **Operating System**: Raspbian 
* **Process Supervisor**: hb-service

At last i removed Homebridge config UI X in case there was something wrong with the installation it self bij entering ""sudo npm uninstall -g homebridge-config-ui-x" and tried to reinstall again by entering "sudo npm install -g --unsafe-perm homebridge-ui-x" and "sudo npm install -g --unsafe-perm --force homebridge-ui-x" but i get the exact same error. 

For somemore background information i installed homebridge with the iso for Rasbian so i did not do any wierd things during the setup. The system it self runs since august on a Pi 3 model B plus rev 1.3. I also run Pi-hole on the same installation, installed with hb-config, additional packages en i also have PiVPN on this system for remote access and remote adblocker.

Can someone help me install the UI again?

**Comment by oznu** [comment]
Run this:

```
sudo npm cache clean --force
npm cache clean
```

The latest update will automatically clean the cache if a UI update fails.

**Comment by Waylikemark** [comment]
Well i tried it but i think it killed my npm. If i now enter that command it does nothing. Npm -v says -bash: npm: command not found

**Comment by oznu** [comment]
That command would not have broken npm, so something else must be wrong. 

You can try and get a fresh copy of Node.js which should repair `npm`:

```
curl -Lf# "https://unofficial-builds.nodejs.org/download/release/v14.15.1/node-v14.15.1-linux-armv6l.tar.gz" | sudo tar xzf - -C /usr/local --strip-components=1 --no-same-owner
```

Then again run:

```
sudo npm cache clean --force
npm cache clean --force
```

---

If that still does not fix the problem, take a [backup](https://github.com/homebridge/homebridge/wiki/Backup-and-Restore) and reflash.

**Comment by Waylikemark** [comment]
Thanks that did the trick. My Raspberry Pi got stuck on the first attemt to run sudo npm cache clean --force thats why it broke, atleast i think. But i'm glad everything is working now!
