### ISSUE TITLE
Recent upgrade breaks ffmpeg?

### ISSUE THREAD

**Issue by maisun** [oznu/homebridge-config-ui-x#988]
Hi, 
For some unknown reason camera-ffmpeg stops working recently. I received lots of errors in the log:
Error: spawn Unknown system error -8
Not sure if it is caused by the upgrade however I didn't have any other upgrade during the last two weeks.
Any suggestion is appreciated!

**Comment by oznu** [comment]
Hi @maisun,

The UI won't cause this. The UI runs in it's own process (seperate to Homebridge) and does not touch ffmpeg at all.

You would be better off redirecting this question to camera-ffmpeg.

**Comment by maisun** [comment]
Thanks will ask there

**Comment by oznu** [comment]
Make sure you fill out the issue template the plugin author has created so they'll be able to help you properly 😄
