### ISSUE TITLE
Disable Plugin

### ISSUE THREAD

**Issue by gamma** [oznu/homebridge-config-ui-x#990]
I have at least one plugin that I only need seasonal and would therefore like to disable. I also have a bunch of other plugins that, despite correct configuration do not work. I'd rather not uninstall them but have them disabled instead.

AFAIK there is no option in HB - so maybe UI-X can solve this by putting the configuration away temporarily - or by some other means - to not have the plugin run, but still be available and configured.

It is OK when accessories are not available in the meantime.

**Comment by gamma** [comment]
Push

**Comment by QuarterSwede** [comment]
I'd like to see this as well. It would definitely be helpful and could help diagnose a bad plugin.

**Comment by oznu** [comment]
Same as https://github.com/oznu/homebridge-config-ui-x/issues/287

**Comment by oznu** [comment]
The solution to this feature request will land in the next release. 

It will require Homebridge 1.3.0-beta.47 or later to support the new `disabledPlugins` array (https://github.com/homebridge/homebridge/pull/2775).

As part of these changes users will be able to toggle enable/disable a plugin, their config will be able to remain in the config.json and not stop Homebridge from loading.

![image](https://user-images.githubusercontent.com/3979615/105021438-a552d800-5a9c-11eb-8f9c-f69b23dc1801.png)
![image](https://user-images.githubusercontent.com/3979615/105021494-b4398a80-5a9c-11eb-9fca-1fcf38e2fafd.png)

**Comment by ggroel** [comment]
THANKSSSS!!!!!!!!!

Gastón
