### ISSUE TITLE
Homebridge UI dont show update for homebridge

### ISSUE THREAD

**Issue by masterfordev** [oznu/homebridge-config-ui-x#992]
**Describe The Bug:**
Don show update available for homebridge, any issue for detect it?

**Screenshots:**

[screenshot](https://ibb.co/mvNnDJ6)

**Environment:**

* **Node.js Version**: 12.18.3
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.3
* **Homebridge Config UI X Version**: 4.35
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
> Homebridge Version: 1.2.3

The "latest" homebridge version is currently set to 1.1.6 due to some users facing issues in 1.2.x. When the "latest" version is set to be > 1.2.3 you will see an update available notification in the UI.

**Comment by masterfordev** [comment]
Ohh.. ok. So, its secure update to 1.2.4? (To me that im in 1.2.3).

**Comment by oznu** [comment]
Yes, 1.2.4 won't be any worse than 1.2.3 😄

**Comment by masterfordev** [comment]
Lol ok 😂, thanks.
