### ISSUE TITLE
Lock GUI layout to prevent accidental drag-and-drop

### ISSUE THREAD

**Issue by RafeSacks** [oznu/homebridge-config-ui-x#996]
_First I want to say how much appreciate this tool. It has been a breeze to use and I love visiting my dashboard!_

**Is your feature request related to a problem? Please describe:**
The UI drag-and drop can really shuffle things around if wide or large widgets are involved. E.g. a left column of narrow widgets stacked vertically with big Log and Terminal widgets taking up most of the width and stacked vertically. It took me some time to get it the way I wanted because dragging a small widget can push other widgets around and reorder them in odd ways. Once I had it done, I accidentally dragged one and had to go back to work to get it back to the way it was.

**Describe the solution you'd like:**
I would love an option to lock the layout to prevent accidental widget dragging.

**Additional context:**
homebridge-config-ui-x v4.35.0

**Comment by oznu** [comment]
This already exists 😄 

Click the + add widget button in the bottom right -> Lock Layout.

![image](https://user-images.githubusercontent.com/3979615/101555498-e7541d00-3a0c-11eb-8cc7-1074003f2d46.png)
