### ISSUE TITLE
Battery Service not showing up as percentage in accessories widget

### ISSUE THREAD

**Issue by Dima-Kal** [oznu/homebridge-config-ui-x#998]
**Describe The Bug:**
Battery Service accessory is not shown as percentage in "Accessories" widget in Status Screen.

**To Reproduce:**
Get a battery service accessory and add it to the "Accessories" widget in Status Screen.

**Expected behavior:**
To see the accessory the same way it is shown in accessories tab

**Logs:**
irrelevant

**Homebridge Config:**
irrelevant

**Screenshots:**
![Screen Shot 2020-12-09 at 15 58 09](https://user-images.githubusercontent.com/39248175/101639270-c0f7a700-3a37-11eb-8c42-fbd0e03a5200.png)
![Screen Shot 2020-12-09 at 15 58 24](https://user-images.githubusercontent.com/39248175/101639038-7ece6580-3a37-11eb-91ae-1bf05139f9b6.png)

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 1.2.4
* **Homebridge Config UI X Version**: 4.36.0
* **Operating System**: Mac
* **Process Supervisor**: hb-service

**Comment by Dima-Kal** [comment]
Anyone?

**Comment by oznu** [comment]
thanks for reporting, this will be fixed in the next release.
