### ISSUE TITLE
Add Homebridge start delay option

### ISSUE THREAD

**Issue by jasonlboggs** [oznu/homebridge-config-ui-x#999]
**Is your feature request related to a problem? Please describe:**
Each time I reboot my server, I have to manually restart the Homebridge service because it starts up before a dependent service (unifi video). This causes a plugin to crash (because the service’s API is not online yet) and Homebridge to crash. 

**Describe the solution you'd like:**
A simple delay option either in the config file or even when installing hb-service

**Describe alternatives you've considered:**
Before using hb-service, I added a simple wait timer to the script that launched Homebridge as a service. 

**Additional context:**
hb-service.ts has a delay for raspberry pi zero.  I imagine we could utilize this space to add some sort of optional delay setting.

**Comment by Krillle** [comment]
I like the idea, as I am encountering the same with my plugin homebridge-signalk. 
Even more sophisticated (but bigger change) would be a load delay time per plugin. 

[1] https://www.npmjs.com/package/homebridge-signalk

**Comment by riconr1** [comment]
The same by me with phoscon. I need a delay to :)

**Comment by jasonlboggs** [comment]
This is still an issue, but I was able to circumvent it by adding a script to restart the Homebridge service 15 seconds after server start.

**Comment by SunnyBoy-DK** [comment]
Have same challenge loading Homebridge Music plug-in on Mac OS X

**Comment by DarylMc** [comment]
This is how I add a startup delay for homebridge service with systemd

_sudo systemctl stop homebridge
sudo systemctl disable homebridge.service
sudo nano /etc/systemd/system/homebridge.timer
sudo systemctl daemon-reload
sudo systemctl enable homebridge.timer
sudo reboot_

text for homebridge.timer delay in seconds

_[Unit]
Description=Delay

[Timer]
OnBootSec=60


[Install]
WantedBy=multi-user.target_
